### ISSUE TITLE
Using PyArray_SetBaseObject

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#10001]
From the docs, it seems that [`PyArray_SetBaseObject` is part of the public API]( https://docs.scipy.org/doc/numpy-1.13.0/reference/c-api.array.html#c.PyArray_SetBaseObject ). However, I can't see it defined in any header file. It does seem to be defined in a C file though with an `NPY_NO_EXPORT`. So how should one use this function? 😕

https://github.com/numpy/numpy/blob/e94ed84010c60961f82860d146681d3fd607de4e/numpy/core/src/multiarray/arrayobject.c#L130-L131

**Comment by jakirkham** [comment]
To answer my own question, it seems this is available from `arrayobject.h`, but am really not sure how that happens as it doesn't appear clearly in the raw source code.

**Comment by njsmith** [comment]
You can't use regular C linking to call between python modules. So numpy
has some scripts that run as part of the build process that generate
headers and glue code that lets other python modules call its public API
functions.

On Nov 10, 2017 18:09, "jakirkham" <notifications@github.com> wrote:

To answer my own question, it seems this is available from arrayobject.h,
but am really not sure how that happens as it doesn't appear clearly in the
raw source code.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/numpy/numpy/issues/10001#issuecomment-343632647>, or mute
the thread

**Comment by jakirkham** [comment]
Oh! That’s very interesting. Where is this code just out of curiosity?

**Comment by njsmith** [comment]
[`numpy/core/code_generators`](https://github.com/numpy/numpy/tree/master/numpy/core/code_generators)

**Comment by jakirkham** [comment]
Thanks.
