### ISSUE TITLE
about numpy.ndarray.view

### ISSUE THREAD

**Issue by ABILIBILI** [numpy/numpy#10043]
case1:
code is:
`a=np.arange(12).reshape(3,4)`
`c=a.view()`
`c.base is a             #this value is False`
Then the result is False

case2:
code is:
`a=np.random.random((3,4))`
`c=a.view()`
`c.base is a              #this value is True`
Then the result is True

So I just wonder why the difference,because the reshape() and the random() all return the same ndarray type,what in details makes this difference?

**Comment by seberg** [comment]
Bases are "skipped" sometimes, don't remember the reason for it to be honest. Since `a` already has a base in the first example, `a.base is c.base` should be True.

**Comment by seberg** [comment]
Might be just an optimization, but I think there was some issue that was fixed or mitigated by it.

**Comment by charris** [comment]
IIRC, the original was to have base point to the object of which a view was taken. Because of problems with stack depth, or some such, that was changed so that all views pointed to the original base. But then that led to some compatibility errors -- I don't recall the details -- and so things were changed once again to their current behavior, which is admittedly odd. There was some discussion of the choice, but I'm not sure how to find it these days. I think the final patch may have come from Travis himself.

**Comment by seberg** [comment]
Yeah, I am pretty sure it was from Travis (actually likely there was one after that regarding being writable or not). I do not remember why it wanted to point to the bottom, stack depth seems like a good reason. There may also be weirder reasons.
I seem to remember that there was also an issue of not jumping different subclass boundaries (or maybe only the writable thing).

In any case, if the arrays are all writable (and ndarray type?), then I am pretty sure it always points to the lowest in the stack.

As for checks for a similar reason, `np.may_share_memory` may be more reliable/easier, otherwise you have to traverse both arrays bases probably.

**Comment by eric-wieser** [comment]
Note also that if `base`s just pointed to parents, then you could end up in confusing situations where `np.may_share_memory(a, a.base)` returns false!

```
base = np.zeros((10, 10))
a = base[:5,:]
b = np.lib.stridetricks.as_strided(a, ...)  #too lazy here, but could do this so that b == base[5:,:]
```

**Comment by seberg** [comment]
If you do strange enough things, yeah, you can likely manage to do that, and skipping parents makes it less likely.

Anyway, since it seems to me this was just a question and not an issue, I will close this. Feel free to complain if you think there is an issue here.
