### ISSUE TITLE
Unexpected itemsize creating string array from numeric dtype array

### ISSUE THREAD

**Issue by taldcroft** [numpy/numpy#10062]
For operations which involve converting numeric array data to strings I get unexpected itemsize values on the output:
```python
In [1]: np.array([1, 2], dtype='U')
Out[1]: 
array(['1', '2'], 
      dtype='<U1')  # Expected result

In [2]: np.array([1, 2]).astype('U')
Out[2]: 
array(['1', '2'], 
      dtype='<U21')  # Not '<U1'

In [3]: np.array([1., 2.]).astype('U')
Out[3]: 
array(['1.0', '2.0'], 
      dtype='<U32')  # Not '<U3'
```
Using numpy 1.13 and Py3.6 in this.

**Comment by seberg** [comment]
The string size is determined based on the input dtype right now, and that is probably an int64 or so on your system. I think there is a 2.5year old PR which might try to change some of it, but with these things, someone would have to think long and hard if it should be changed or not.

**Comment by seberg** [comment]
Of course for string input it actually uses the string length, but for non-strings....

**Comment by seberg** [comment]
Well, you could try to calculate the actually necessary size based on the maximum and minimum value manually, I suppose.

**Comment by ahaldane** [comment]
I think `np.array(arr.tolist(), dtype='U')` is probably the best thing to do. It might even be very close to what numpy "should" do internally. 

The difficulty is that it is pretty much impossible to compute the max string size without actually doing the string conversion for all elements as a first pass. Eg, it is hard to predict that `10.0` is shorter than `3.141592653589793` without actually converting to string.

I recently noticed this fixed-size issue as well when fixing https://github.com/pandas-dev/pandas/issues/18123#issuecomment-341987009, but I didn't mention it since it seems like the kind of thing we are stuck with forever due to compatibility, and I'm not sure it really hurts.

**Comment by eric-wieser** [comment]
I can't reproduce:
```
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import numpy as np
>>> np.__version__
'1.13.1'
>>> np.array([1, 2], dtype='U')
array(['1', '2'],
      dtype='<U1')
>>> np.array([1., 2.], dtype='U')
array(['1.0', '2.0'],
      dtype='<U3')
```

**Comment by eric-wieser** [comment]
Perhaps we need a method to trim trailing nulls from an array of strings?

**Comment by ahaldane** [comment]
@eric-wieser it should be

```python
>>> np.array([1, 2]).astype('U')
array([u'1', u'2'],
      dtype='<U21')
>>> np.array([1., 2.]).astype('U')
array([u'1.0', u'2.0'],
      dtype='<U32')
```

**Comment by ahaldane** [comment]
I just checked the code in `convert_datatype.c`. It turns out that when converting from object type `'O'`, numpy really does just do exactly `np.array(a.tolist(), dtype='U')`.

But for all the other types, here's the hardcoded sizes from that file:
```
 3 uint8
 5 uint16
10 uint32
20 uint64
32 float16-float128
64 cfloat32-cfloat256
21 timedelta
```
Add one to the unsigned int length for the signed length.

datetime size is determined by `get_datetime_iso_8601_strlen(dtype)`

**Comment by taldcroft** [comment]
For kicks I did timing on an alternate implementation that uses `np.char.str_len` to find the max length.  Looks like this one loses by a factor of 2.5 in speed.
```
In [2]: def with_str_len(arr):
   ...:     str_arr = arr.astype('U')
   ...:     max_len = np.char.str_len(str_arr).max()
   ...:     str_arr = str_arr.astype('U' + str(max_len))
   ...:     return str_arr
   ...: 

In [6]: arr = np.arange(100000)

In [7]: %timeit with_str_len(arr)
10 loops, best of 3: 58.9 ms per loop

In [8]: %timeit np.array(arr.tolist(), dtype='U')
10 loops, best of 3: 23.1 ms per loop
```

**Comment by ahaldane** [comment]
Yeah it looks like the speed is a simple function of the number of passes through the array. In current numpy on my system, `arr.astype('U')` is almost exactly 2x faster than `np.array(arr.tolist(), dtype='U')`, which makes sense since the former uses 1 pass while the latter uses 2 passes.

Your code uses 3 passes: One to convert to U, one to determine the max length, and one to convert to the shorter string length. Therefore we should expect it to be 2x slower than the 2-pass `np.array(arr.tolist(), dtype='U')`, which indeed it is.

**Comment by seberg** [comment]
Is there anything to act up on here, otherwise I think we can close it?

**Comment by taldcroft** [comment]
Personally I think this shows an inconsistent and unexpected behavior that should be fixed.  The apples-to-apples way to say this is:
```
In [1]: np.array([1, 2], dtype='U')
Out[1]: 
array(['1', '2'], 
      dtype='<U1')

In [2]: np.array(np.array([1, 2]), dtype='U')
Out[2]: 
array(['1', '2'], 
      dtype='<U21')
```
Most of the time in numpy I would expect the same output when passing in a list or a numpy array of that list.

If this is a huge deal to fix (which I understand could be the case), perhaps a warning could be issued to tell the user the result is probably not what they expect?  It could even be extra helpful by mentioning that they might want to use `tolist()`.  I know in my case I *thought* things were working and only happened to notice that the string itemsize was large.

**Comment by seberg** [comment]
The problem is that currently if you do things with a too small U
dtype, things can be silently ignored I think, so if you would reduce
it, people might end up losing information, instead of just using a
little bit more RAM.
You could give it a warning, but I wonder if it would not be more noise
then worth the trouble. How come having a larger then expected dtype is
so bad?

**Comment by taldcroft** [comment]
I wasn't suggesting making the fixed values smaller, which indeed causes worse problems.

About the larger-than-expected dtype, if someone happens to have a billion elements in their array then a factor of a few to 20 could mean the difference between all-fine and their machine grinding to a halt.  The warning is just to tell users "hey, numpy is doing something you probably didn't expect".

But if this is just too much noise then I'm fine with closing.

**Comment by eric-wieser** [comment]
I suspect that you have comparable memory problems by calling `tolist()` first.

**Comment by eric-wieser** [comment]
> I ended up doing (effectively): np.array(arr.tolist(), dtype='U'). Is there a better way that doesn't involve going to a pure Python list?

Yes, you can do `arr.astype(object).astype(np.unicode_)`, which still goes via builtin python objects, but at least avoids the lists.

**Comment by taldcroft** [comment]
Good point about memory, and thanks for the slightly better implementation via `object`.

I'll just add that I encountered this on two separate occasions, and having a lousy memory I had to discover what was going on each time.  The actual thing I was doing was using `np.concatenate` to concatenate arrays and counting on numpy to do type conversion as needed.  It mostly works except for this problem.  So I was proposing a warning to help me out next time, except I guess then at least there will be a numpy issue that I will hopefully find.  :smile:

**Comment by eric-wieser** [comment]
In my opinion, warnings have to be avoidable - otherwise, they can't just turn on `warnings.simplefilter('error')` to track them all down, since the end up stuck on the first one that is not avoidable.

What you're suggesting would make it impossible for "strict" code like that to use `astype(str)`, forcing them to use `astype(obj).astype(str)`. I don't know if that's acceptable.

**Comment by taldcroft** [comment]
OK sounds like no action to be taken.  Closing.
