### ISSUE TITLE
numpy.reshape order='C' ('F') not return array in C (F) contiguous

### ISSUE THREAD

**Issue by sunqm** [numpy/numpy#10069]
The keyword argument "order" of numpy.reshape function does not work the same way as the kwarg "order" of numpy.array function.  Is it a design or a bug?  For example, in the following code snippet, numpy.reshape does not return C (F) contiguous array
```
a = numpy.arange(9).reshape(3,3)
print numpy.reshape(a[:2,:2], order='C').flags.c_contiguous
print numpy.reshape(a[:2,:2], order='F').flags.c_contiguous
print numpy.array(a[:2,:2], order='F').ravel('A')
print numpy.reshape(a[:2,:2], order='F').ravel('A') # not output [0,3,1,4] as last statement
```

**Comment by pv** [comment]
The documentation says:
"""
order : {‘C’, ‘F’, ‘A’}, optional

     Read the elements of a using this index order, and place the 
elements into the reshaped array using this index order. ‘C’ means to 
read / write the elements using C-like index order, with the last axis 
index changing fastest, back to the first axis index changing slowest. 
‘F’ means to read / write the elements using Fortran-like index order, 
with the first index changing fastest, and the last index changing 
slowest. Note that the ‘C’ and ‘F’ options take no account of the memory 
layout of the underlying array, and only refer to the order of indexing. 
‘A’ means to read / write the elements in Fortran-like index order if a 
is Fortran contiguous in memory, C-like order otherwise.

Returns:	

reshaped_array : ndarray

     This will be a new view object if possible; otherwise, it will be a 
copy. Note there is no guarantee of the memory layout (C- or Fortran- 
contiguous) of the returned array
"""
Do you think this needs to be clarified?

**Comment by sunqm** [comment]
I didn't realize this description in the document points to the problem I got. I think the document is clear enough.  Thanks a lot.
