### ISSUE TITLE
np.pad fills empty arrays with floats even if constant value is int

### ISSUE THREAD

**Issue by jamesmullenbach** [numpy/numpy#10118]
Hello, 

I noticed that np.pad takes on relatively unexpected behavior for empty array inputs. The result of `np.pad([], (0, 2), 'constant', constant_values=1)` is `array([1., 1.])` of dtype float64, although the constant value given is an int.

This happens because the default dtype of `np.array([])` is float64. However, I think it may be more user-friendly to have np.pad return the same dtype as given in constant_values in this case (this caused a bug for me downstream, which I fixed by just adding an .astype(np.int64) after my call to np.pad).

I'm using numpy version 1.13.3 with Python 2.7.14 on Ubuntu 14.04.

Feel free to ignore/close if this was a deliberate design decision.

Thanks!

**Comment by eric-wieser** [comment]
You've diagnosed the problem correctly as due to `[]` being `np.float64([])`.

At best, `np.pad` should choose the dtype which can represent _both_ the array argument and the `constant_values` argument. I don't know if this is the case, but there's a strong precedent for _not_ ignoring the `dtype=float64` that the array has attached, just because its empty.

Another example is `np.concatenate(([], [1])) == np.array([1.0])`

> which I fixed by just adding an .astype(np.int64) after my call to np.pad

This is not an ideal fix. You should fix this by passing in an `array` of the right type to `pad`, rather than working with `list`s.

**Comment by eric-wieser** [comment]
Related to #7615

**Comment by mattip** [comment]
Closing, this is a deliberate design decision
