### ISSUE TITLE
Misleading error message for reshape

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#10146]
Error message says the array is non-contiguous, but it means non-**C**-contiguous - in the following example, the array is contiguous, yet the error is still emitted:

```python
>>> a = np.eye(2)
>>> b = a.T
>>> b.flags.f_contiguous
True
>>> b.shape= 4
Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    b.shape= 4
AttributeError: incompatible shape for a non-contiguous array
```

**Comment by hanjohn** [comment]
I'm investigating the issue; based the documentation, however, I don't see why mutating the shape shouldn't just work whether the array is C- or F- contiguous:

https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.shape.html

It sounds like it's not a typo/documentation issue: `b.shape= 4` in your snippet should just reshape array `b` instead of raising an exception at all, so this looks like an implementation bug.

Let me know if I'm missing something here (I'm a new contributor), but I'm happy to work on it either way

**Comment by eric-wieser** [comment]
`b.reshape(4)` is defined to reshape in C order, giving `[b[0,0], b[0,1], b[1, 0], b[1,1]]`. But the order of elements in memory is `[b[0,0], b[1,0], b[0, 1], b[1,1]]` - so a copy has to be made

**Comment by deepakgouda** [comment]
`shape` uses C order by default. So, flattening an f-contiguous array would result in the loss of the constant stride needed to access the memory blocks. So, I believe it's a documentation error and the correct error message should be 

> Cannot flatten f-contiguous array. Unable to access memory with constant stride. Use `reshape` to copy array into new memory block.

or

> Cannot flatten f-contiguous array. Unable to access memory row-wise. Use `reshape` to copy array into new memory block.

Correct me if I am wrong(I am a new contributor).

**Comment by hanjohn** [comment]
I'm in agreement now; I was confused because the live documentation for ndarray.shape doesn't say much about the behavior of mutating shape at all: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.shape.html

Where does the live doc page get the docstrings from? The docstring in https://github.com/numpy/numpy/blob/master/numpy/add_newdocs.py#L2944 is much stronger; if the live documentation is just serving an old version of the docstrings in add_newdocs.py, then I won't worry about updating documentation besides the error message itself.


It makes sense that mutating shape should be restricted to c-contiguous arrays, however; performing no-copy shape changes for f-contiguous arrays could result in confusing behavior at runtime if the users don't want to worry about how the bytes are stored in memory.

Thanks for explaining!

**Comment by hanjohn** [comment]
@eric-wieser Could you please confirm that the live documentation at https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.shape.html is just serving an outdated version of https://github.com/numpy/numpy/blob/master/numpy/add_newdocs.py#L2944?

Or are the docstrings being pulled from somewhere else?

**Comment by Shashi456** [comment]
has this been taken care of ?

**Comment by SahanaJavgal** [comment]
Hello, Im new to Open Source and I am Applying for Outreachy. I would like to work on this Issue. Could you please assign it to me

**Comment by hanjohn** [comment]
done, sorry about dropping this

I don't think I have permissions to assign this issue but feel free to open up a PR and I can close mine

**Comment by anshulshankar** [comment]
Hey 
New to the open source. Can i solve this issue. Any prerequisite requires for the same

**Comment by mattip** [comment]
Hi @anshulshankar. Please read our [developer guide](https://numpy.org/devdocs/dev/index.html) which discusses the required workflow. Since this is a documentation issue, you will want to [build the documentation](https://numpy.org/devdocs/docs/index.html) to check that it renders properly before you issue a pull request (PR) from your fork.

We don't assign issues, you should mention this issue in your PR by writing `xref gh-10146` to link back to here.

**Comment by krishnakatyal** [comment]
is this issue resolved?

**Comment by eric-wieser** [comment]
No, there are pending comments that need addressing in #10600

**Comment by panpiort8** [comment]
Is anyone working on that? If not - I can take it.

**Comment by hanjohn** [comment]
not to my knowledge, go ahead

**Comment by seberg** [comment]
@panpiort8, Matti rebased and fixed up gh-10600, I assume that it is basically ready to be merged closing this issue. But very happy if you have a quick look and see if it looks good to you!

**Comment by seberg** [comment]
Ah, missed the commit message "closes" tag, so closing.
