### ISSUE TITLE
memmap behavior is different between C order and F order

### ISSUE THREAD

**Issue by dogod621** [numpy/numpy#10345]
when i use "reshape / ravel" with F order memmap, 
it will return a copy, and make my F order memmap writing fail, 
because it will write to the copy array, not write to the memmap.

It seem it will transform to C contiguous array，and than reshape.

Is that a BUG? 

```
import numpy as np

m1 = np.memmap("data1", dtype='float32', mode='w+', shape=(3,2,4), order = 'C')
m2 = np.memmap("data2", dtype='float32', mode='w+', shape=(3,2,4), order = 'F')

def PrintAdd ( array ): 
    print ( array.__array_interface__['data'][0] )
    print ( array.reshape (-1,).__array_interface__['data'][0] )
    print ( array.ravel ().__array_interface__['data'][0] )

print ( "C order address" )
PrintAdd ( m1 )
PrintAdd ( m1.view () )
PrintAdd ( np.ascontiguousarray ( m1 ) )

print ( "F order address" )
PrintAdd ( m2 )
PrintAdd ( m2.view () )
PrintAdd ( np.ascontiguousarray ( m2 ) )
```

Output:
```
C order address
2397050044416
2397050044416
2397050044416
2397050044416
2397050044416
2397050044416
2397050044416
2397050044416
2397050044416
F order address
2397050109952
2397032773488
2397032773488
2397050109952
2397032773488
2397032773488
2397032773488
2397032773488
2397032773488
```
 and np.frombuffer will raise error
```
a1 = np.frombuffer ( m1 )
a2 = np.frombuffer ( m2 )
```
Error:
```
Traceback (most recent call last):
  File "C:\Users\CGLab\Desktop\test\main.py", line 24, in <module>
    a2 = np.frombuffer ( m2 )
ValueError: ndarray is not C-contiguous
```

**Comment by njsmith** [comment]
No, this is working as designed. Most numpy operations treat the underlying storage structure of the array as an internal detail – the actual array you get back from `ravel` or `reshape` etc. always has the same shape, and the same elements at the same indexes, regardless of how the original array was stored. So this means that if we have two arrays with the same contents but different storage:

```
In [17]: a_c = np.array([[1, 2, 3], [4, 5, 6]])

In [18]: a_f = np.array([[1, 2, 3], [4, 5, 6]], order="F")

In [20]: a_c.flags.c_contiguous
Out[20]: True

In [21]: a_f.flags.f_contiguous
Out[21]: True
```

Then `ravel` returns the same thing in both cases:

```
In [22]: a_c.ravel()
Out[22]: array([1, 2, 3, 4, 5, 6])    # this is a view

In [23]: a_f.ravel()
Out[23]: array([1, 2, 3, 4, 5, 6])    # this is NOT a view
```

(And this also works for arrays that aren't contiguous at all – numpy supports lots of memory layouts beyond C contiguous and F contiguous.)

But, F order means that `a_f` array is stored in memory like `[1, 4, 2, 5, 3, 6]`. So there's no way to make that ravelled array be a view onto it. `ravel` makes the output a view if, and only if, that's possible.

If you want to `ravel` an F order array, and have it come out a view, then you have to tell `ravel` to traverse the elements in a F-style ordering, by calling it like `ravel(order="F")`. Importantly, this doesn't make `ravel`'s output depend on the ordering of the underlying array – you can do this to a C order array or an F order array:

```
In [25]: a_c.ravel(order="F")
Out[25]: array([1, 4, 2, 5, 3, 6])    # This is NOT a view

In [26]: a_f.ravel(order="F")
Out[26]: array([1, 4, 2, 5, 3, 6])    # This is a view
```

But by doing things this way, it becomes possible to make the second one a view, so it does.

`reshape` also takes an `order` argument, and works the same way. You can think of it as walking over the array in whichever order you tell it to create a 1-d array, and then filling in the new shape using that same order. And if that's possible to do as a view, then it will; otherwise, it'll make a copy.
