### ISSUE TITLE
einsum broadcast regression (with optimize=True)

### ISSUE THREAD

**Issue by d70-t** [numpy/numpy#10343]
In numpy 1.13.3, it was possible to execute the following snippet without errors, while in 1.14.0 this happens:
```python
In [1]: import numpy as np
In [2]: a = np.ones((10,2))
In [3]: b = np.ones((1,2))
In [4]: np.einsum('t...i,ti->t...', a, b)
Traceback (most recent call last):
  File "<ipython-input-4-fa62d1d882f9>", line 1, in <module>
    np.einsum('t...i,ti->t...', a, b)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/einsumfunc.py", line 1087, in einsum
    einsum_call=True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/einsumfunc.py", line 710, in einsum_path
    "not match previous terms.", char, tnum)
ValueError: ("Size of label '%s' for operand %d does not match previous terms.", 't', 1)

```
However `optimize=False` solves the problem:
```python
In [5]: np.einsum('t...i,ti->t...', a, b, optimize=False)
Out[5]: array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
```
Is this intended behavior and the user is now responsible to explicitly disable optimization or is this a bug?

**Comment by charris** [comment]
Both? `optimize=True` was made the default, but it shouldn't be causing errors.

@dgasmith Another one ;)

**Comment by eric-wieser** [comment]
Seems we failed to format the error message correctly either

**Comment by mhvk** [comment]
This hit at least one user of astropy (though not our tests, annoyingly!). The following breaks (but works with `optimize=False`):
```
np.einsum('...ij,j...->i...', np.eye(3)[np.newaxis], np.array([[1., 1.], [2., 2.], [3., 3.]]))
```

**Comment by mhvk** [comment]
The fix in #10352 seems correct. Note also that the current optimization choice makes no sense: for 2 argument, optimization should not be attempted; see #10357.

**Comment by mhvk** [comment]
@charris - this issue is biting lots of astropy users now (https://github.com/astropy/astropy/issues/7051#issuecomment-357468791) as it screws up one of our coordinate transformations. Those are all with 3x3 matrices, so pending not just a solution but also a better understanding of impacts of performance, I would indeed suggest to revert the default for 1.14.1. Obviously, we also need #10352 and especially its tests so this doesn't recur! (We missed it in astropy in part because for python3 our transformations use `matmul` -- guess we should test our last python2 version also with `numpy-dev`...)

**Comment by charris** [comment]
@mhvk See #10403.

**Comment by mhvk** [comment]
OK, good, that gives more time.
