### ISSUE TITLE
numpy reshape will not reorder if input same shape

### ISSUE THREAD

**Issue by dogod621** [numpy/numpy#10349]
for example: Why a3_C is the same as a3_F，it do not reorder

```python
a1_C = np.arange(6).reshape((3, 2))
# [[0 1]
#  [2 3]
#  [4 5]]
a2_C = np.reshape(a1_C, (2, 3), order='C')
# [[0 1 2]
#  [3 4 5]]
a2_F = np.reshape(a1_C, (2, 3), order='F')
# [[0 4 3]
#  [2 1 5]]
a3_C = np.reshape(a1_C, (3, 2), order='C')
# [[0 1]
#  [2 3]
#  [4 5]]
a3_F = np.reshape(a1_C, (3, 2), order='F')
# [[0 1]
#  [2 3]
#  [4 5]]
```

**Comment by njsmith** [comment]
[StackOverflow](https://stackoverflow.com) is a better place to ask these kinds of questions.

In this case, the order is different because you requested it be different with the `order` argument... `reshape` has to have some rule for deciding which elements in the old array get place at which positions in the new array, and that involves walking over the two arrays in a particular order. The `order` flag changes that order, so it changes the output.

**Comment by eric-wieser** [comment]
@njsmith, I think the question is why `a3_C` and `a3_F` _are_ the same, which is far less clear to me.

**Comment by njsmith** [comment]
Oh, yeah, I missed that. But sounds like you've sorted it out :-)
