### ISSUE TITLE
Equality of numpy scalars and lists fails

### ISSUE THREAD

**Issue by mitar** [numpy/numpy#10399]
Why does this happen

```python
>>> np.int64(1) == [np.int64(2)]
array([False])
```

Instead of returning simply `False` or `True`?

I understand that ndarray has overloaded equality operator, but here I am using just base integer values and a list. Why is this magically converted to an array?

This really surprises downstream code which expects a boolean context:

```python
>>> bool(np.int64(1) == [np.int64(2), np.int64(3)])
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by eric-wieser** [comment]
Note this applies to all numpy scalars, not just int64.

Auto-conversion of lists to arrays was probably a mistake, but I think it's way too late to remove that entirely. Perhaps `scalar op list` is a narrow enough case that the upcast could be foregone

**Comment by mitar** [comment]
One example how this blows up:

```python
cache = []
cache.append(numpy.int64(2))
cache.append([numpy.int64[1], numpy.int64[2])
numpy.int64(3) in cache
```

Bam. You cannot check if a value is in a list.

**Comment by eric-wieser** [comment]
Caching a list is probably a poor idea, since that list can change value after you cache it

**Comment by eric-wieser** [comment]
Perhaps we should start requiring users to write `np.asarray(sc) == list` or `sc == np.asarray(list)` if they want this behavior - we could start emitting a `DeprecationWarning`, and have a long deprecation cycle.

**Comment by seberg** [comment]
I would be up for it if someone wants to try that, the old issue of `PyArray_Return` kicks in, so some code that generalizes to 0D might get caught in it. So unfortunately, it would probably be good to at least see that the large downstream packages would be unaffected.

**Comment by hameerabbasi** [comment]
Scalars behave like zero-dimensional NumPy arrays at the moment, and we have to maintain this duality. We discussed this in the community call and agreed that it should be closed.

**Comment by mitar** [comment]
I understand. It is just sad that it explodes in random places in Python.

**Comment by seberg** [comment]
It is, its true that in the long term maybe we should try to remove that duality... but its tricky :(.

**Comment by mitar** [comment]
Yes, backwards compatibility is a problem. Maybe numpy should start suggesting to use `ndarray.equals` or something and deprecate use of `==` for equality. And then in the future `==` is changed to be closer to Python expectations?

**Comment by seberg** [comment]
I disagree with making `==` not behave like it does for arrays (it could stop converting the other object to an array, but that is a tougher sell). But, right now we conflate 0-D arrays and scalars. And we should somehow fix that conflation. Maybe by just asking you to use `.item()` and making scalars not really be a thing or maybe by using 0-D arrays more and making scalars more like scalars... I do not know.

For what its worth, I think `==` should return elementwise comparisons for arrays, because its convenient. Yes, it breaks some stuff in Python, but thats just life, not even python is fully consistent with Python in these ways anyway...

**Comment by mitar** [comment]
Yes, but problem is that things like type checking explode for you because of this: https://github.com/Stewori/pytypes/issues/27

So comparing for equality really should return just true or false. Not an exception.

**Comment by seberg** [comment]
I don't really would prefer not to discuss this here for long. I get that there are issues, but its also super inconvenient to write things like `arr[np.equal(arr, 0)] = 1` by comparison. So IMHO if this is a big problem, we should rather try to find a solution for typing projects rather than create think whether NumPy is "impure" and how to fix it. (for all I know the fact that NumPy allows raising errors from `==` may have been to support this type of use-case better).
