### ISSUE TITLE
numpy.sum() was err

### ISSUE THREAD

**Issue by zijungit** [numpy/numpy#10449]
ERR:
np.sum(range(10000000))
Out[117]: -2014260032

correct:
sum(range(10000000))
Out[118]: 49999995000000

The max num:2**16
np.sum(range(65536)) == sum(range(65536))
True
np.sum(range(65536+1)) == sum(range(65536+1))
False

Feel the np.sum's speed is not good
Can you fix this bug?Thanks

**Comment by eric-wieser** [comment]
Noting that `sum(range(N))` is `N * (N - 1) / 2`, your expected results are `2**31 - 65536` and `2**32 * 32768`.

The first of these fits in a 32-bit signed integer, which is why the result is correct. The second does not, so you see integer overflow.

If you pass `dtype=np.int64` to `sum`, then the result will fit. If you want to store numbers larger than `2**127`, then you should use `dtype=object` instead, but by that point you lose all the speed advantages of numpy.

**Comment by eric-wieser** [comment]
Dupe of #4638, among others
