### ISSUE TITLE
BUG: ufunc.__call__ treats out passed by position and keyword differently

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#10450]
Extracted from #10382, which this is partly the cause of.

Using this simple class to debug:
```python
class MyArray(np.ndarray):
    def __array_wrap__(self, obj, context=None):
        print('__array_wrap__   ({}, {}, {})'.format(self, obj,context))
        return self
    def __array_prepare__(self, obj, context=None):
        print('__array_prepare__({}, {}, {})'.format(self, obj,context))
        return self

a = np.zeros((), int).view(MyArray)
```
we have:
```python
# all ok
>>> np.add(-1, 1, a)
__array_prepare__(0, 0, (<ufunc 'add'>, (-1, 1, MyArray(0)), 0))
__array_wrap__   (0, 0, (<ufunc 'add'>, (-1, 1, MyArray(0)), 0))

# no out argument to __array_wrap__
>>> np.add(-1, 1, out=a)
__array_prepare__(0, 0, (<ufunc 'add'>, (-1, 1, MyArray(0)), 0))
__array_wrap__   (0, 0, (<ufunc 'add'>, (-1, 1), 0))

# where did __array_prepare__ go?
>>> np.add(-1, 1, out=(a,))
__array_wrap__   (0, 0, (<ufunc 'add'>, (-1, 1), 0))
```
and with an input
```python
#ok
>>> np.add(0, a, a)
__array_prepare__(0, 0, (<ufunc 'add'>, (0, MyArray(0), MyArray(0)), 0))
__array_wrap__   (0, 0, (<ufunc 'add'>, (0, MyArray(0), MyArray(0)), 0))

# no out argument to __array_wrap__
>>> np.add(0, a, out=a)
__array_prepare__(0, 0, (<ufunc 'add'>, (0, MyArray(0), MyArray(0)), 0))
__array_wrap__   (0, 0, (<ufunc 'add'>, (0, MyArray(0)), 0))

# holy tuple batman
>>> np.add(0, a, out=(a,))
__array_prepare__(0, 0, (<ufunc 'add'>, (0, MyArray(0), (MyArray(0),)), 0))
__array_wrap__   (0, 0, (<ufunc 'add'>, (0, MyArray(0)), 0))
```

---

I can see a few other places where this bug might exist too - anything passing `args` in PyUfunc_GenericFunction` may be guilty. I think we need to fix this at the earliest possible location, and convert positional to keyword arguments as soon as possible.

**Comment by eric-wieser** [comment]
Should `__array_wrap__` receive the output argument at all in `args`? What if `out=None` or `out=(None,)`?

`MaskedArray.__array_wrap__` does the wrong thing if output arguments are passed, so it's possible that other users in the wild have this problem too.

**Comment by mhvk** [comment]
I don't actually understand why the outputs are passed to either `__array_prepare__` or `__array_wrap__` -- after all, one gets `obj` already (in `Quantity` we certainly immediately get rid of any outputs). The only reason I can think of is to know whether `self` is an output or an input, but that is trivially checked with `self in inputs` or `self is obj`.

There is actually little documentation: at [1], it is stated that "a 3-element tuple: (name of the ufunc, arguments of the ufunc, domain of the ufunc)", and at [2] "the context consisting of the ufunc itself, the arguments passed to the ufunc, and the ufunc domain". Currently, we seem to pass only positional arguments, which seems very unexpected. My tendency would be to drop the outputs from `context` altogether, i.e., clarify the meaning of context to state "input arguments".

[1] https://docs.scipy.org/doc/numpy/user/basics.subclassing.html#array-wrap-for-ufuncs-and-other-functions
[2] https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#output-type-determination

**Comment by eric-wieser** [comment]
Currently we very deliberately pass `out` into `__array_prepare__` though

**Comment by mhvk** [comment]
Yes, indeed. But any code that looks at it will break when we start passing a tuple, as we should for multi-output ufuncs. Sigh.

**Comment by eric-wieser** [comment]
Good catch, added to the top post

**Comment by mhvk** [comment]
I guess the options are:
1. Remove all outputs in both; risks breaking some `__array_prepare__` implementations;
2. Expand output tuples in `__array_prepare__`; also risks breaking `__array_prepare__` implementations;
3. Add expanded output arguments in both; risks as (2) but also breaking `__array_wrap__` implementations.

I'd think (2) is the least risky, but I don't like keeping the inconsistent `context` that is being passed. Ideally, this is just constructed once and then used multiple times. Next least risky may well be (1), since `__array_prepare__` implementations that relied on the output argument would already break if a tuple was passed in; in contrast, it seems quite likely `__array_wrap__` implementations might rely on `context` only passing on inputs. So, overall, I'd be in favour of removing the output arguments.

Of course, ideally we just get rid of this altogether...

**Comment by mhvk** [comment]
@shoyer - since you (I think) have also worked with duck-type classes that use `__array_prepare__` and `__array_wrap__`, do you have any input on the use of output arguments in `context`? (see comments above and at top).

**Comment by shoyer** [comment]
I don't think any of dask, pandas or xarray implement `__array_prepare__`, and I believe our `__array_wrap__` methods entirely ignore the `context` argument. So at least you don't have to worry about breaking us!

We have one other alternative option to consider: (4) don't do anything at all here. `context` could be considered a strictly inferior version of `__array_ufunc__`, and if don't recommend that new code use it there is little to be gained by changing its semantics (even to clean up its inconsistencies).

**Comment by mhvk** [comment]
Good point: @eric-wieser - if so, we would only fix `MaskedArray`. Though I think your cleanup of the argument parsing might well end up making the pure ndarray path faster...

**Comment by eric-wieser** [comment]
Another data point: @hgrecco's `pint` does not expect output arguments to appear in either `__array_wrap__` or `__array_prepare__

**Comment by eric-wieser** [comment]
Option (5): Concatenate the output tuples  in both methods, but only if one of the outputs is not `None`. This keeps old code working that forgot about output arguments, and likely breaks in similar ways when output arguments are provided.

**Comment by mhvk** [comment]
An advantage of your option (5) to make out tuples is that it could be done even before checking for `__array_ufunc__` -- i.e., some code from `override.c/normalize__call___args` could be moved up. Though any code that used the output arguments for the simplest case in `__array_prepare__` -- say, `np.add(a, b, out=c)` -- might well break on now getting a tuple.

Perhaps another argument for not doing anything is that any code that does break now has to worry about compatibility with older versions of numpy (though arguably that is easiest to solve by moving to `__array_ufunc__`...).

**Comment by eric-wieser** [comment]
> any code that used the output arguments for the simplest case in __array_prepare__ -- say, np.add(a, b, out=c) -- might well break on now getting a tuple.

Right, but this code would already break on `np.add(a, b, c)`, which is a reasonably common way to write it too.

> Some code [...] could be moved up

I completely agree - we should be able to convert our 3-4x `dict.__getitem__` call + 1 super-optimized kwarg parse into just 1 super-optimized kwarg pass. But we need to make the code paths use the same data for this to work. We could add some ugly flags for `out_was_tuple` and `out_prepare_not_wrap` instead...

**Comment by eric-wieser** [comment]
It seems that passing the `out=` keyword argument to `__array_prepare__` was by design right from the beginning: https://github.com/numpy/numpy/commit/9ab33b7f5c78c3f1caad36a53af29a72a2e0bf4d#diff-ded4bbd920a163719d3850ce89bbcfa9R3067

Handling tuples properly here was then forgotten when support for them was added.

**Comment by mhvk** [comment]
That code is most curious, it even copies further positional arguments.

Some further thought on option (5). I actually dislike this since one cannot pass an `out` tuple as a positional argument to regular `ufunc` calls (`np.add(0., 1., (out,))` doesn't work). 

In the end, if we want to keep the output arguments, it seems easiest to follow your initial [suggestion[(https://github.com/numpy/numpy/issues/10450#issuecomment-360339959), i.e., option (3): always expand tuples and just pass both to prepare and wrap (removing trailing `None` perhaps). That preserves the existing behaviour for all-positional argument calls, and does the logical thing for a keyword argument. (Initially, I hadn't really appreciated that `__array_wrap__` does currently get positional output arguments, so if code cannot handle that, the increased risk from now passing on keyword `out` arguments seems minimal.)

**Comment by mhvk** [comment]
Good to see the different options in code (gh-10470, gh-10488). I quite like how the `struct` works in the remove-the-outputs scenario, and can see how this would be handy elsewhere.

But in the end it boils down to the question posed here, of whether to continue passing the output arguments on. I think your quick scan showed that many implementations do not expect `out` arguments. But I'm not sure that is a good reason for us to stop passing on outputs: currently, those implementations may well if an output argument is passed on, while if we do not pass `out` on, it will still get set, to something which may well be wrong.

In contrast, I see little downside to passing on all outputs. For the keyword case, it might make code that treats `np.add(a, b, result)` correctly to work also for `np.add(a, b, out=result)`. Probably, much code would  fail for multiple outputs, especiallt if those include `None`, but that would not really be a change in behaviour, but more likely a slightly different failure.

Since continuing to pass on `out` also preserves the present behaviour of methods which, as @shoyer pointed, we probably want to eventually deprecate anyway, I think it may be best to just go with passing on all `out` arguments.

**Comment by eric-wieser** [comment]
So am I right in thinking the way forward here is:

* Start off with the parsing used by the remove-the-outputs scenario
* Only pass the outputs if some of them are non-None:
```
if (full_args.out == NULL) {
    wrap_prep_args = full_args.in;
    Py_INCREF(wrap_prep_args);
}
else {
   wrap_prep_args = PySequence_Concat(full_args.in, full_args.out);
   if (wrap_prep_args == NULL) return NULL;
}
```

**Comment by mhvk** [comment]
@eric-wieser - belatedly, yes, I think your suggestion above is the way forward. With perhaps (don't really care), trailing `None` in the outputs cut off.
