### ISSUE TITLE
list(ndarray) != ndarray.tolist()

### ISSUE THREAD

**Issue by MartinThoma** [numpy/numpy#10494]
I stumbled over this:

```
import numpy as np
import json

ndarray = np.array([1, 2, 3], dtype=np.float32)

# works:
json.dumps(ndarray.tolist())

# does not work: json.dumps(list(ndarray))
```

**Comment by rlabbe** [comment]
As the documentation for tolist states() "Data items are converted to the nearest compatible Python type", which is not what list() does. list() does not convert types.

Hence tolist works because np.float32 is converted to float. list() doesn't because it outputs a list of np.float32, which json cannot handle.

**Comment by MartinThoma** [comment]
@rlabbe Yes, I think [the documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tolist.html) - or at least the example - is pretty good. I would like to see a warning / notice about this in the text as well, though.

Also: Is there an advantage of having it like this? For me, it would be more intuitive if `ndarray.tolist()` would be equal to `list(ndarray)`.

**Comment by rlabbe** [comment]
The advantage is that it converts data to native Python objects, so you can go ahead and use it in other places, like json. Other libraries, such as Pandas, do the same thing, convert to a Python scalar. How would you get this behavior otherwise without laborious hand coding it everywhere?

Note I am not a part of the dev team, my opinion counts for nothing. I was just pointing out the behavior is as defined.

**Comment by MartinThoma** [comment]
> The advantage is that it converts data to native Python objects, so you can go ahead and use it in other places, like json.

Sorry, I accidentially wrote it the wrong way. I think the behavior of `list(ndarray)` should probably be changed.

**Comment by rlabbe** [comment]
list() is part of Python. It cannot be rewritten to know about every type in existence. I go write the "RogerPy" module, introduce my own types, and list is supposed to know about it? Not possible.

list just iterates over an iterable: 'return [i for i in x]'

It doesn't know anything about the underlying type in `x`.

**Comment by MartinThoma** [comment]
Ah, I thought that there might be a special method similar to `__iter__()`. I guess changing `__iter__()` is not an option and probably this is what is used by `list()`?

**Comment by seberg** [comment]
Will close this, tolist is supposed to convert it down in a nested list with python type, list is upposed to convert using `__iter__` like the comments say, there is no reason to change either (unless you want to change the `tolist` methods name or improve its documentation).
