### ISSUE TITLE
Request: Multidimensional choose function

### ISSUE THREAD

**Issue by beojan** [numpy/numpy#10492]
A multidimensional analog to `np.choose`, where the index array is an array of tuples.
Does this already exist under some other name?

**Comment by seberg** [comment]
Going to close this, since it seems a bit obscure to me and I am not sure what this would look like, feel free to reopen with a bit more details.

We do have advanced indexing where you can do `arr_3_dimensional[dim1, dim2, dim3]` to choose in such a fashion (with a tuple of arrays rather than an array of tuples) from a single array.  (While choose works with a list of arrays internally.)
