### ISSUE TITLE
DOC: numpy.random.sample and numpy.random.random_sample

### ISSUE THREAD

**Issue by k-kapp** [numpy/numpy#10587]
I just noticed in the docs that the page for `numpy.random.sample` indicates that the function should be called as `numpy.random.random_sample`. I understand that this may just indicate that the function may be called as either `sample` or `random_sample`, but it does come across as a mistake when first viewing the page. Perhaps make it more explicit that `random_sample` is an alias of `sample`? Or is this the accepted practice for functions that have aliases?

**Comment by eric-wieser** [comment]
This is show this way because:
```python
>>> np.random.random_sample
<function RandomState.random_sample>

>>> np.random.sample
<function RandomState.random_sample>
```

I think flipping the alias would be reasonable

**Comment by rkern** [comment]
`sample` is just an old backwards-compatibility alias for `random_sample`, which is the authoritative name.

**Comment by godaygo** [comment]
@rkern isn't it better to deprecate `random_sample` in favor of `sample` the same way as it is done with `random_integers`? The `random` prefix seems excessive - they are already live in `random` module. And ше also I allows to achieve greater consistency in the names across `random` module.

**Comment by bashtage** [comment]
IMO it is almost never worth it to remove API to achieve consistency since this will break existing code and documentation (e.g., tutorials).  

If matching `randint` was the goal, the name would have to be something like `randfloat` which isn't very nice. `sample` and even `random_sample` are particularly clear that one will get a uniform random number on [0,1).  `uniform` is the probably the clearest, but already taken.

**Comment by bashtage** [comment]
xref #13163 . This is fixed in the randomgen branch, subject to dropping `sample` and `random` and `ranf`

**Comment by bashtage** [comment]
Also contains docstring pointers for ranf and sample.
