### ISSUE TITLE
Different behavior between __add__ and __iadd__ ?

### ISSUE THREAD

**Issue by tyohei** [numpy/numpy#10593]
- Python version: 3.6.3
- Numpy version: 1.14.0
 
The `__add__` and `__iadd__` operation are returning different results in `np.ndarry`.
This happens when the array sizes are different.

Tested a code below.

```python
import numpy as np

a = np.arange(2)
b = np.array([np.arange(2, 4), np.arange(4, 6)])
print(a.shape)  # (1, 2)
print(b.shape)  # (2, 2)

def iadd(a, b):
    a += b
    print(a)

def add(a, b):
    a = a + b
    print(a)

iadd(a, b)
# ValueError: non-broadcastable output operand with shape (1,2) doesn't match the broadcast shape (2,2)

add(a, b)
# [[2 4]
# [4 6]]
```

Perhaps these two operation should return a same result and not a ValueError.
Is there any reason that Numpy are doing such thing?

**Comment by njsmith** [comment]
Yes, this is intentional. When you call `__iadd__`, numpy insists on doing the operation in place, or else failing. In your example, you can't do the operation in place (the output array is the wrong shape), so you can't do it at all.

This is important to (a) avoid creating surprising copies, if `a` is a 10 gigabyte array then you don't want `a += b` to suddenly make a copy of `a` when you weren't expecting it, (b) avoid surprises with views and such; if `a` is a view on `a_base`, then `a += b` will always modify `a_base`.

**Comment by tyohei** [comment]
Thanks!
