### ISSUE TITLE
Regression: array2string breaks for some subclasses

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#10663]
EDIT: the below may not be complete; there seems to be other breakage for structured dtypes.

The guard against infinite recursion in array2string done in #10544 causes problems for subclasses that count on user-defined formatters to have access to items of their own class; see https://github.com/astropy/astropy/issues/7214.  In particular, astropy's `Angle` class assumed that inside array2print, any item selection would be done using its `__getitem__`, so that even scalars would be returned as array scalars with all the appropriate methods. This assumption broke by the introduction of an `asarray` in #10544. As noted in https://github.com/numpy/numpy/pull/10544#discussion_r170435274, it may be possible to solve this by doing `asarray` inside the numpy formatters, rather than upon entry in `array2print`.

Here's a minimal testcase:
```
import numpy as np

class DuckCounter(np.ndarray):
    def __getitem__(self, item):
        result = super(DuckCounter, self).__getitem__(item)
        if not isinstance(result, DuckCounter):
            result = result[...].view(DuckCounter)
        return result
            
    def to_string(self):
        # only on scalers in this example...
        return {0: 'zero', 1: 'one', 2: 'two'}.get(self.item(), 'many')
    
    def __str__(self):
        if self.shape == ():
            return self.to_string()
        else:
            return np.array2string(self,
                                   formatter={'all': lambda x: x.to_string()})


dc = np.arange(5).view(DuckCounter)
print(dc)
# [zero one two many many]
```

On numpy 1.14.1, this gives
```
AttributeError: 'numpy.int64' object has no attribute 'to_string'
```

**Comment by ahaldane** [comment]
This 0d array issue continues to be a 1000-piece puzzle! Different ndarray subclasses expect different behaviors.

What about this fixup:
https://github.com/ahaldane/numpy/commit/78a9a06042194e268a3e8cf5d7a868e7628cac6d

If fixes your example code. It uses the same solution as in this PR, but only uses `asarray` on 0d arrays. This fixes the 0d recursion issue for subclasses that return 0d arrays instead of scalars, yet still allows n-d arrays to pass 0-d-arrays to the formatters.

The downside is it breaks nested-subclassed-object array tests which this PR fixed. But those were already broken in 1.13, so I think it's better to leave them broken if we can undo the new breaks. I made those tests "knownfail".

**Comment by ahaldane** [comment]
By the way, I ran astropy tests with master and with the fixup above. Ony my system I already get 78 failed astropy tests using numpy master. I think a few are due to the recent fft changes, but also many due to infinite recursion in the doctest module for some reason I don't understand. 

But the fixup above does fix the 3 test failures that seem to be due to #10544.

**Comment by mhvk** [comment]
Just for the record: moving `asarray` inside the formatters as suggested by @eric-wieser is unlikely to solve all astropy regressions - we have one subclass that relies on its `__getitem__` being used for a structured dtype. So, @ahaldane's fix may be the best. I'd still like it better if we could use `asarray` only when it is clear we are actually recursing...
