### ISSUE TITLE
Unexpected difference between print and str for numpy.float64

### ISSUE THREAD

**Issue by abalkin** [numpy/numpy#10753]
With the latest numpy master (1.15.0.dev0+83c6699) and Python 2.7, I get

```python
>>> x = numpy.float64(0.1999999999999)
>>> str(x)
'0.1999999999999'
>>> print x
0.2
```

Apparently, tp_str has been reimplemented for the numpy.float64 type, but tp_print is still inherited from builtin float:

```c
(gdb) p PyDoubleArrType_Type
$2 = {
  _ob_next = 0x7ffff18fb8d0,
  _ob_prev = 0x7fffeedb1060,
  ob_refcnt = 102,
  ob_type = 0x7ffff7fb2600,
  ob_size = 0,
  tp_name = 0x7ffff144382c "numpy.float64",
  ...
  tp_print = 0x7ffff7bf25fc <float_print>,
  ...
  tp_str = 0x7ffff13c8b8f <doubletype_str>,
  ...
```

**Comment by mhvk** [comment]
cc @ahaldane

**Comment by ahaldane** [comment]
Huh interesting, I didn't realize `tp_print` even existed and was implemented for float.

It seems to be an obsolete feature, disabled in python3 and strongly discouraged/nearly deprecated in python2.

I'll take a look at how to fix. I'm not sure if this is worth a 1.14.3 release, but maybe it is. This may count as a bug since the python2 doc says "A type should never implement tp_print in a way that produces different output than tp_repr or tp_str would.", though that's a bit unclear since tp_repr and tp_str can output different things.
