### ISSUE TITLE
savez fails on large array of objects

### ISSUE THREAD

**Issue by pkomiske** [numpy/numpy#10776]
I'm getting a RuntimeError "File size unexpectedly exceeded ZIP64 limit" when using `savez` to save a few arrays to a file, the largest of which is an array of matrices each with a different number of rows (so that the top level array's dtype is object). As best I can tell, the condition used by numpy internally to decide whether or not to pass `force_zip64=True` to the zipfile open is checking if any of the arrays to be put into the archive has nbytes greater than 2^30. My array of matrices reports nbytes less than 2^30 but in reality the total number of bytes exceeds this (it's about 1.7GB). I'm using python 3.6 and numpy 1.14.2 on Ubuntu 16.04. 

The following code produces the error:
```python
test_data = np.asarray([np.random.rand(np.random.randint(50,100),4) for i in range(800000)])
np.savez('test', test_data=test_data)
```
whereas changing `np.random.randint(50,100)`->`75` produces no error.

**Comment by njsmith** [comment]
Sounds like it's not taking into account the size of the pickled objects.

I bet we could just set force_zip64 to true unconditionally. What's the
worst case, it wastes a few dozen bytes? (Or we could do this for object
arrays only. I doubt the complexity of special casing different types is
worth it though.)

**Comment by pkomiske** [comment]
Setting force_zip64 to True unconditionally seems fine. Another alternative would be to allow the user to change this flag.

**Comment by eric-wieser** [comment]
+1 from me on using it unconditionally

**Comment by charris** [comment]
Someone want to fix this?

**Comment by mattip** [comment]
I can try

**Comment by mattip** [comment]
Using the example and `force_zip64=True` unconditionally, I get a `MemoryError` on python3 at this [line](https://github.com/numpy/numpy/blob/v1.15.4/numpy/lib/format.py#L593)
```
pickle.dump(array, fp, protocol=2, **pickle_kwargs)
```. 
Increasing the protocol to 3, the test passes. Why do we limit ourselves to saving in protocol 2?
The pre-python3.6 path can write successfully.

**Comment by mattip** [comment]
Maybe we should just leave the protocol to `pickle.HIGHEST_PROTOCOL`, or leave the argument out entirely?

**Comment by charris** [comment]
> Maybe we should just leave the protocol to pickle.HIGHEST_PROTOCOL

We might want to wait until we drop Python 2.7.

- Protocol version 3 was added in Python 3.0. It has explicit support for bytes objects and cannot be unpickled by Python 2.x. This is the default protocol, and the recommended protocol when compatibility with other Python 3 versions is required.
- Protocol version 4 was added in Python 3.4. It adds support for very large objects, pickling more kinds of objects, and some data format optimizations. Refer to PEP 3154 for information about improvements brought by protocol 4.

**Comment by seberg** [comment]
I wonder how much we should worry about sharing of `npz` files breaking here? Python 2 is still used a bit, and this will break all npz sharing with python 2 (I would not be surprised if some of my colleagues still use it, so if I upgrade our experimental computer it will store incompatible `npz`s for the experiments, not a huge issue, but still).

I wonder a bit if we could get away with adding a `pickle_protocol` kwarg or similar (has to be long to not collide with user names)? Because then we could exchange the error message with a note that you can pass `pickle_protocol=3` or `-1` to fix it.

**Comment by seberg** [comment]
Well, I guess that is a bit silly, because the experiments obviously do not store object arrays, so do not have this issue in the first place. So I guess I am pretty much ok with this, since it is limited to objects.

**Comment by belltailjp** [comment]
Hi. I have reported #13153 and noticed that this issue is due to the same root cause.

The problem of current numpy is that `_savez` doesn't correctly get the actual size of the data in case it is either a dict or a list (of np arrays), so I think modifying this part so that it can properly identify the correct size would solve the issue, while keeping the current conditional force_zip64 behavior.

Let me propose the brief direction of this way below, as a modification of line 727-728. https://github.com/numpy/numpy/blob/d89c4c7e7850578e5ee61e3e09abd86318906975/numpy/lib/npyio.py#L727-L728

```
    if sys.version_info >= (3, 6):
         # Since Python 3.6 it is possible to write directly to a ZIP file.
         for key, val in namedict.items():
             fname = key + '.npy'
+            nbytes = 0
+            if isinstance(val, dict):
+                nbytes = sum(v.nbytes for v in val.values())
+            elif isinstance(val, list):
+                nbytes = sum(v.nbytes for v in val)
             val = np.asanyarray(val)
+            nbytes += val.nbytes
             force_zip64 = val.nbytes >= 2**30
             with zipf.open(fname, 'w', force_zip64=force_zip64) as fid:
```

Again, I know that this is totally incomplete and dirty, but just wanted to show a direction.

This would solve the both cases with list and dict (be noted that I didn't convert the list to np.array (first line) here for simplicity), although it sets `force_zip64` only when necessary.
```
np.savez('test', [np.random.rand(np.random.randint(50,100),4) for i in range(800000)])
np.savez('test', {'a': np.random.rand(1024, 1024, 256)})
```

**Comment by mattip** [comment]
I think #12428 would be a better choice, although it means we forego the ability to read some `npz` archives on python2.

**Comment by belltailjp** [comment]
I agree, that would be the simplest and the best.
I just felt like it's a bit too long to wait until np+py2 EOL (almost) indefinitely for this kind of a bug, but as you mention it'll ready in 1.17, that's OK for me too (of course I want this fix right now, though:) ).
