### ISSUE TITLE
Performance issue with np.concatenate

### ISSUE THREAD

**Issue by Windaway** [numpy/numpy#10823]
also with np.vstack np.r_ np.append
When I concat an array (b=np.concatenate([b,a],0)) many times, the performance goes down.

**Comment by jaimefrio** [comment]
Performance goes down because you are concatenating ever larger arrays that need to be copied into a new one. Do a single `np.concatenate([b] * n + [a], 0)` and you should get better performance than performing your operation `n` times.

I'm going to close this as "works as expected," but will be happy to reopen it if you can provide more details that show a performance degradation beyond normal expectations.
