### ISSUE TITLE
np.roll significantly slower than np.concatenate

### ISSUE THREAD

**Issue by ucyo** [numpy/numpy#10848]
I dunno the reasons, but `np.roll` is significantly slower than `np.concatenate`.

```python
In [1]: import numpy as np

In [2]: d = np.arange(99)

In [3]: %timeit np.roll(d, 1)
15 µs ± 250 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: %timeit np.concatenate([d[-1:],d[:-1]])
1.26 µs ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by seberg** [comment]
Which numpy version are you using, roll was notoriously slow, the difference should be pretty small nowadays.

The other possibility is that your array is so small that there is just so much overhead since the roll function is implemented in python and has to do extra checks and a few nano or even microseconds more just for the typical call overhead is nothing strange.

**Comment by ucyo** [comment]
It's `1.13.1` ... Might be that `1.14` fixed that ... :+1: 
I didn't check for other sizes, but shouldn't we build some kind of threshold then? Smaller than x and we use `np.concatenate` ... If it is still in `1.14` that is...

**Comment by seberg** [comment]
As I said, the overhead is only the python call overhead, you could implement `np.roll` in C to avoid some of it, but I doubt it is useful. 10µs is an expected slowdown for a function implemented in python. I will close this for now, feel free to protest though.

**Comment by seberg** [comment]
Maybe as another point: We have many many things like this where if you have small arrays and want most speed you can "specialize" those numpy utility type functions to skip checks, etc. and just be much faster.

In other words: We would have to argue that this is much more important then other python implemented type functions. There used to be a real performance issue in roll, but it is fixed in your version already I believe.
