### ISSUE TITLE
Possible optimization when multiplying memory-mapped array by mostly zeros

### ISSUE THREAD

**Issue by zietzm** [numpy/numpy#10852]
We are saving a large number of arrays to disk (in .npy format), which need to be loaded as quickly as possible to be multiplied by a vector (array). The arrays on disk vary in size but can be relatively large (~ several GB), and the vectors are mostly zeros.

When loading an array or matrix with memmap for the purpose of multiplying by another array, [we found](https://github.com/greenelab/hetmech/blob/6d135267ed4ec02fec3a3d976ea8751524c49be0/explore/matrix-io/02.sparse-and-dense.ipynb) that subsetting the array for nonzero rows of the vector can be significantly faster. To do so, we can subset both the in-memory vector and on-disk array for nonzero rows and then multiply. 

My question is, does or could numpy do similar optimization? That is, when an array is "loaded" as a memmap from a disk file and multiplied by a mostly-zero array, does/could numpy subset both for only the nonzero rows to increase speed?

Tagging @dhimmel

**Comment by dhimmel** [comment]
Here is some code to illustrate the issue:

```python
# Let's assume the matrix has many rows, but only 10 will be multiplied by a nonzero value
n_nonzero_indices = 10

# Load a memory-mapped matrix from disk
matrix = np.load('matrix.npy', mmap_mode='r')
n_rows, n_cols = mat.shape

# Create a vector with n_row values, where all but n_nonzero_indices are zero
vector = np.zeros((1, n_rows)).flatten()
nonzero_indices = np.random.randint(0, high=n_rows, size=n_nonzero_indices)
vector[nonzero_indices] = 1

# Dot product without subsetting (method 1)
output = vector @ matrix

# Dot product with subsetting (method 2)
output = np.ones(n_nonzero_indices) @ matrix[nonzero_indices]
```

@zietzm found that method 2 is generally much faster than method 1 (2-20 times faster in our case). However, it seems that an intelligent memory map implementation should be capable of natively doing method 2 (or something that provides similar efficiency gains). In other words, is memory-map reading in rows that will end up being multiplied by zero? If so, perhaps there is an possible optimization to multiplication of memory-mapped matrices/arrays, where rows that will be multiplied by zero do not have to be loaded?

**Comment by seberg** [comment]
I have to I disagree, it sounds like a more specialized optimization, note that numpy uses BLAS for matrix multiplication. For memory maps it might be more likely to be worth it, but you could just as well have only a penalty because you have no or only few zeros.

I would not be surprised if sparse matrices (if the vector is sparse here) will be do this though (not 100% sure for e.g. the scipy stuff because the matrix is still dense here, I do not need sparse matrices a lot nowadays).
Maybe even your matrices are sparse as well, then it definitely could be worth it for you. For a generic (dense) library like numpy it does not seem like the right thing.

**Comment by seberg** [comment]
Though one thing to note is maybe, that I am not sure `@` in the first implementation actually used blas always ("older" numpy versions) or if some BLAS might be doing such things possibly here.

**Comment by njsmith** [comment]
The great thing about using memmap to load arrays is that by using OS virtual memory tricks, you can use code designed for working with in-memory arrays directly on on-disk arrays.

The problem with using memmap to load arrays, is that you're using in-memory code directly on on-disk arrays, so it has no special tricks to handle the on-disk array more efficiently.

In this case, numpy doesn't even do the matrix multiply -- it just hands it off to whatever BLAS library you're using. It would increase the complexity quite a bit to add special cases to detect the combination of memmapped arrays and all-zero inputs and rewrite the BLAS call based on them...

**Comment by dhimmel** [comment]
> I would not be surprised if sparse matrices (if the vector is sparse here) will be do this

Ah. Great point, I don't think we tested whether doing "scipy.sparse @ memmap" acheives the same efficiency as the subset method. @zietzm let's see what happens to the runtime in the non-subsetted multiplication if we make `vector` a scipy.sparse matrix.

> The problem with using memmap to load arrays, is that you're using in-memory code directly on on-disk arrays, so it has no special tricks to handle the on-disk array more efficiently.

Good to know. We can run `numpy.show_config()` on our systems to see exactly which versions of BLAS implementation we're using.

Perhaps we should rephrase our suggested optimization as: If a row is being multiplied by zero, it's values don't need to be accessed. So the fact that subsetting mem-mapped arrays is faster shows that BLAS is not performing the multiplication in the most efficient way. In other words, regardless of whether the matrix is mem-mapped or not (BLAS has no awareness of this), the implementation shouldn't need to access values that will not matter (because they are being multiplied by zero).

Now I'm a novice in this realm and don't know much about BLAS. However, we'd be happy to bring this issue up in the appropriate repository. @seberg and @njsmith: do you think that makes sense, or that there is nothing here that the BLAS developers haven't already considered?

**Comment by njsmith** [comment]
Checking for zeroes and skipping those rows is a very common trick in optimized BLAS implementations, yes. (It's slightly notorious even, because it actually gives incorrect results in edge cases: in particular `0 * NaN = NaN`, but the "optimization" acts like `0 * NaN = 0`.)

However, in your case, you want the BLAS to check for zeroes only in the in-memory array, *not* the memmapped array (because even checking for zeroes will force it to be loaded from disk), but the BLAS doesn't know which array is in-memory!

**Comment by seberg** [comment]
Anyway, it is probably a valid and great optimization for many scenarios, but clutter and likely not even valid for a numpy, so I guess we can close this....
