### ISSUE TITLE
Feature request: numpy.random.normal with `dtype`

### ISSUE THREAD

**Issue by davidbp** [numpy/numpy#10892]
When constructing arrays it is useful to set the dtype. For some reason we can do it with some `np.random` methods such as random integers but not with random normal values. Could we have a consitent version across all methods that generate new np.arrays?

```python
>>> np.random.randint(10,dtype="Int16")
9
>>> np.random.normal(10,dtype="Float32")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 1547, in mtrand.RandomState.normal (numpy/random/mtrand/mtrand.c:20493)
TypeError: normal() got an unexpected keyword argument 'dtype'
```

This would be nice in order to avoid   `np.array( somearray, dtype=sometype )` every time we create a new random array. 

For example 
```python
np.array( np.random.normal(10), dtype="Float32")
```
could be simply written as
```python
 np.random.normal(10, dtype="Float32")
```

**Comment by bashtage** [comment]
This is implemented in randomgen for all of the core distributions (gauss, exponential, gamma, uniform). These are low level generators and so are implemented in float/uint32 rather than double/uint64.

https://github.com/bashtage/randomgen

A more general implementation for all distributions hasn't really been undertaken but would be easy to do by casting double to float for memory but not computational efficiency.

BTW,

np.float32(np.random.normal(10))

is shorter for scalar arrays, or 

np.random.normal(10,size=10).astype('f4')

for vectors.  

Sometimes it is a shame that the returned type is python native for scalars, since 

np.random.normal(10).astype('f4')

doesn't work, but it does work for arrays.  I'm not suggesting changing.

**Comment by bashtage** [comment]
FWIW I am sort of under the impression that non-trivial changes to RandomState are never going to happen, and that a new structure that will remove the guarantee but provide some backward compat is needed before pursuing these.

**Comment by davidbp** [comment]
I guess that the `.astype` is a solution.
When using this in the notebook I get:

```
 DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
```

**Comment by lucasb-eyer** [comment]
I would like to re-open the issue, as I keep bumping into wanting this almost weekly for over a year.
The conversion is **not** a solution, because most of the times I need this it is for memory purposes. It seems to be a somewhat common request, see for example [this SO question](https://stackoverflow.com/q/21999952/2366315) about it (not me), and the proposed workaround.

**Comment by bashtage** [comment]
Use [randomgen ](https://github.com/bashtage/randomgen) until the new PRNG infrastructure gets into NumPy (hopefully this year).  32 bit is supported for the most common types (normal, exponential, uniform and gamma).

**Comment by Tronic** [comment]
Even the new API apparently lacks `dtype` parameter on `normal` and a few other distributions, and I cannot find explanation for why this is the case, or whether future versions would add them.

**Comment by mattip** [comment]
The difference between the old and new API is documented [here](https://numpy.org/doc/1.17/reference/random/index.html#what-s-new-or-different) and [here](https://numpy.org/doc/1.17/reference/random/new-or-different.html#what-s-new-or-different), note especially the mention of "Optional dtype argument" including an example and much more information at the bottom of the second link. You will need NumPy 1.17 or later.

**Comment by bashtage** [comment]
@Tronic dtypes were only added for a small set of "core" generators.  There hasn'e been an effort to add them as a standard output.  It would be relatively simple to add them in the sense of supporting 
internal conversion from 64bit to 32bit floats which would save space but not computational effort. If anyone is interested, this could be added to the `cont` function.

**Comment by jakirkham** [comment]
FWIW this would be useful when dispatching between different array libraries using `__array_function__` 😉

**Comment by rgommers** [comment]
@jakirkham for `Generator` or `RandomState`? I'd hope the former (long-term, right now CuPy doesn't have that API yet). Opening a new issue would be useful
