### ISSUE TITLE
Identity check fails even if two ndarray objects referring to same integer

### ISSUE THREAD

**Issue by ratnaparkhivivek10** [numpy/numpy#10908]
Even if two ndarray objects are referring to the same integer object, the identity check between them produces incorrect output.
```
>>> a = np.array([1,2,3])
>>> b = np.array(a, copy=False)
>>> 
>>> id(a[0])
2384360040104
>>> id(b[0])
2384360040104
>>> 
>>> id(a[0]) == id(b[0])
True
>>> a[0] is b[0]
False
```

Expected Output:

```
>>> a[0] is b[0]
True
```

**Comment by eric-wieser** [comment]
Your test is misleading - the two objects are not the same. Because the two objects never exist at the same time, the allocation of the second one is using the memory location that was just freed by the first, causing the `id` test to pass. A better test is:

```python
>>> import numpy as np
>>> a = np.array([1,2,3])
>>> b = np.array(a, copy=False)

# ensure that both objects exist at the same time
>>> a0, b0 = a[0], b[0]

>>> id(a0), id(b0)
(2467169076304, 2467169076328)
```

I'm going to close this, but feel free to respond if you still think there is a problem here.

**Comment by ratnaparkhivivek10** [comment]
Thanks @eric-wieser for the clear explanation. It is making sense now.
