### ISSUE TITLE
DOC: Fix mistake in documentation of `*.npy` header.

### ISSUE THREAD

**Issue by vpatov** [numpy/numpy#11080]
The [documentation](https://docs.scipy.org/doc/numpy/neps/npy-format.html#format-specification-version-1-0) of the format contains the following paragraph:

> "The next HEADER_LEN bytes form the header data describing the array’s format. It is an ASCII string which contains a Python literal expression of a dictionary. It is terminated by a newline (‘n’) and padded with spaces (‘x20’) to make the total length of the magic string + 4 + HEADER_LEN be evenly divisible by **16** for alignment purposes."

In the code comments (and in the actual format), padding is done such that the sum of the length of the magic string, 4, and the HEADER_LEN, is evenly divisible by **64**, not 16, as shown [here](https://github.com/numpy/numpy/blob/master/numpy/lib/format.py#L105): 

This has caused me some headache while writing a custom .npy serializer..

Also, the wording "to make the total length of the magic string + 4 + HEADER_LEN" is a little confusing, as it makes it seem that the amount being referenced is equal to `total length of magic string` + `4` + `HEADER_LEN` as opposed to total length of `magic string + 4 + HEADER_LEN`.

**Comment by rkern** [comment]
This is something that changed since the initial release. Generally speaking, NEPs are proposal documents and, to the extent that they are documentation of code or formats, they document only what's being proposed. Once we do accept the NEP, whatever is useful long-term ought to be moved over into the official documentation, and the NEP should be frozen in place and not considered documentation of the released feature anymore.

It looks like we did move the documentation over into the docstrings, but we never added it to the numpy reference, and we're still [pointing to the NEP](https://docs.scipy.org/doc/numpy/reference/routines.io.html). Whoever wants to fix this, I would encourage them to expose the true documentation in `numpy.lib.format` and fix references to the NEP to this documentation.
