### ISSUE TITLE
Converting from datetime.datetime returns date without time

### ISSUE THREAD

**Issue by aluhamaa** [numpy/numpy#11106]
```
>>> import numpy as np
>>> import datetime
>>> print(np.array([datetime.datetime(2018, 5, 15, 6, 0),datetime.datetime(2018, 5, 15, 6, 30)]).astype('datetime64[us]'))
>>> print(np.array([datetime.datetime(2018, 5, 15, 6, 0),datetime.datetime(2018, 5, 15, 6, 30)]).astype('datetime64'))
['2018-05-15T06:00:00.000000' '2018-05-15T06:30:00.000000']
['2018-05-15' '2018-05-15']
```

shows that without specifying the unit, conversion from datetime.datetime object to numpy.datetime64 reduces the actual accuracy of initial data and there is no obvious reason why this should take place. Also, specifying units is not needed when converting directly from iso8601 strings, as snown in https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.datetime.html

```
>>> np.array(['2001-01-01T12:00', '2002-02-03T13:56:03.172'], dtype='datetime64')
array(['2001-01-01T12:00:00.000-0600', '2002-02-03T13:56:03.172-0600'], dtype='datetime64[ms]')
```

Tested with numpy 1.14.3 from Anaconda python 3.6.3

**Comment by shoyer** [comment]
This is pretty clearly a bug. I'm not sure what's going on here, but it's not intentional. I can reproduce it with the latest release.

The logic is somewhere in datetime.c if you want to take a look, likely somewhere in [`convert_pyobject_to_datetime`](https://github.com/numpy/numpy/blob/71962fcbb63ca7bf76c37f56379eaee917f05e7e/numpy/core/src/multiarray/datetime.c#L2415). Based on the code, it looks like only datetime.date objects should have a default precision of days.

Side note: please update your version of NumPy. We changed datetime64 in some significant way back in NumPy 1.11: https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.datetime.html#changes-with-numpy-1-11

**Comment by aluhamaa** [comment]
Thanks, I'll try to take a look at the C code.
