### ISSUE TITLE
Regression: np.ma.masked_values(..., shrink=True) no longer works

### ISSUE THREAD

**Issue by lpsinger** [numpy/numpy#11112]
The [documentation for `np.ma.masked_values()`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ma.masked_values.html) explains the role of the `shrink` option (which defaults to True) as follows:

> Whether to collapse a mask full of False to nomask.

In Numpy <= 1.13.3, this works correctly:

```
$ python -c 'import numpy as np; print(repr(np.ma.masked_values(np.arange(10.0), -1)))'
masked_array(data = [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.],
             mask = False,
       fill_value = -1.0)
```

In Numpy >= 1.14.0 and on master, it is broken:

```
$ python -c 'import numpy as np; print(repr(np.ma.masked_values(np.arange(10.0), -1)))'
masked_array(data=[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0],
             mask=[False, False, False, False, False, False, False, False,
                   False, False],
       fill_value=-1.0)
```

**Comment by charris** [comment]
@eric-wieser This looks like yours (and mine :), #10232.

**Comment by eric-wieser** [comment]
This looks like a bug in `np.ma.array(..., shrink=True)` that was never previously exposed.

**Comment by eric-wieser** [comment]
So, the `shrink` argument to `np.ma.array` is documented as:

> Whether to force compression of an empty mask. Default is True.

This is only used in exactly one case - when `shrink=True, keep_mask=False`, it means "don't expand `nomask` to an array of zeros"

This is super-specific, and not a reasonable interpretation of the documentation.

So I think that we can probably add back the shrinking to `masked_values`, but we should deprecate the argument to `MaskedArray.__new__`, since it's probably used only ever in error.

**Comment by charris** [comment]
We need to make a decision here. Just marking for future reference.

**Comment by charris** [comment]
@eric-wieser Could you make a PR with your suggestion here?

**Comment by charris** [comment]
Looks like this changed because the `keepdims` default value is `True`
