### ISSUE TITLE
Feature Request: Softmax 

### ISSUE THREAD

**Issue by ARudiuk** [numpy/numpy#11157]
Hello

I was wondering if there any plans to implement softmax in numpy? I seem to keep having to write it for myself, and I was wondering if anyone else is in the same situation.

**Comment by pv** [comment]
https://github.com/scipy/scipy/pull/8556

**Comment by eric-wieser** [comment]
Yep, I think this belongs in scipy

**Comment by rgommers** [comment]
I think we all agree on that. closing this. thanks @ARudiuk

**Comment by janosh** [comment]
I think `softmax` should be part of `numpy`. It's very commonly needed in many areas of machine learning, pretty much every time you're doing classification.

**Comment by rgommers** [comment]
Please get it from SciPy: `scipy.special.softmax`. We're not duplicating that, `scipy.special` is a better place for it.

**Comment by janosh** [comment]
I'm not trying to force a different decision here but would still like to voice my disagreement precisely because `softmax` is not special but very widely used. Plus it would be simple to maintain:

```py
def softmax(arr: np.ndarray) -> np.ndarray:
    exp_arr = np.exp(arr)
    return exp_arr / exp_arr.sum(axis=-1, keepdims=True)
```

**Comment by WarrenWeckesser** [comment]
Don't read too much into the "special" part of the name `scipy.special`.  Classically, [special functions](https://en.wikipedia.org/wiki/Special_functions) arose from problems in mathematical physics, often as solutions to certain linear second order ordinary differential equations.  Over time, more functions have been added to `scipy.special` that are not traditionally known as special functions, so now the scope of the `scipy.special` module is simply "useful functions".

(Also note that `logsumexp` has been in `scipy.special` for a while, and since `softmax` is the gradient of `logsumexp`, it seems natural to have them both in the same module.)
