### ISSUE TITLE
DEP: remove PyUFunc_SetUsesArraysAsData

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#11285]
As stated in the [code](https://github.com/numpy/numpy/blob/v1.14.4/numpy/core/src/umath/ufunc_object.c#L4424), this function should disappear since better alternatives exist. Need to check if it is used anywhere downstream.

**Comment by uds5501** [comment]
@mattip  If this is not taken already, I would love to work on it!

**Comment by mattip** [comment]
I'm not sure this is appropriate for a first contribution, as [deprecations](http://www.numpy.org/devdocs/reference/c-api.deprecations.html?highlight=deprecate#) can be tricky. You might want to start with an issue [labelled with doc](https://github.com/numpy/numpy/issues?q=is%3Aopen+is%3Aissue+label%3A%2203+-+Documentation%22), be sure to read about our [dev workflow](http://www.numpy.org/devdocs/dev/index.html) In any case, welcome and thanks for the offer of help.

If you do choose to work on this, the first task is verifying, as much as possible, that the function is not used by any code in the wild. There is a [tool to help you do this](https://github.com/njsmith/codetrawl) but will require some tweaking.

**Comment by seberg** [comment]
By now we have a DeprecationWarning in place for calling `PyUFunc_SetUsesArraysAsData` (not for its use as a singleton to flag that arrays should be passed).

Note that the comment is only half true: This is in principle useful for user defined loops (and there it is not yet deprecated). In practice I would be very surprised if anyone actually used it. Since user defined loops cannot (or at least should not) mess with the `TypeResolver`.

**Comment by seberg** [comment]
The function is disabled, so closing. One day maybe we can clear/repurpose the API table slot also.
