### ISSUE TITLE
WRITEBACKIFCOPY warning

### ISSUE THREAD

**Issue by charris** [numpy/numpy#11363]
```
.local/lib/python2.7/site-packages/numpy-1.16.0.dev0+387c089-py2.7-linux-x86_64.egg/numpy/core/tests/test_einsum.py::test_overlap
  /home/charris/.local/lib/python2.7/site-packages/_pytest/python.py:142: RuntimeWarning: WRITEBACKIFCOPY detected in array_dealloc.  Required call to PyArray_ResolveWritebackIfCopy or PyArray_DiscardWritebackIfCopy is missing. This could also be caused by using a nditer without a context manager
    testfunction(**testargs)
```
@mattip This looks like yours.

**Comment by charris** [comment]
Not sure why this doesn't fail with `runtests.py`, I see this with
```
charris@fc [~]$ python3 -c"import numpy; numpy.core.test()"
```

**Comment by mattip** [comment]
I needed to run tests like this `python2 runtests.py -vv -- -s` to make this show up. The  `-s` tells pytest to not wrap stderr, stdout

**Comment by charris** [comment]
@mattip IIUC, the error is written to stderr? If so, that seems easy to miss in tests. Any possibility of having `iter.close` do the writeback if needed?

**Comment by mattip** [comment]
The error is written to `stderr` since it is a warning that is upgraded to an error by the testing framework, and errrors cannot be raised inside `tp_dealloc`. There is a passing test for missed `NpyIter_Close` in `test_warn_noclose`, but it uses a `with_suppress_warnings`. Without that clause, normal testing "swallows" the output. Adding `runtests.py -- -s` (to pass the -s to pytest) makes the output visible.

The original design was to have two functions, `NpyIter_Close` which resolves all the buffered data, and `NpyIter_Deallocate` which frees the memory. We need both functions since the results of iteration may be stored in an operand allocated by the iterator, which will be destroyed once deallocated. 

With that, we could call NpyIter_Close unconditionally inside NpyIter_Deallocate. 

We could also detect the need to call NpyIter_Close inside NpyIter_Deallocate by checking the per-operand flag `NPY_OP_ITFLAG_HAS_WRITEBACK`, warn that `NpyIter_Close` was not called, and only then call it.

I think the warning sounds more reasonable. Then we could remove the bit in the warning inside `array_deallocate` about a missing `NpyIter_Close` as well.
