### ISSUE TITLE
BUG: accessing numpy array by list

### ISSUE THREAD

**Issue by yoonbo** [numpy/numpy#11420]
```
Python 2.7.15 (default, May  2 2018, 00:53:27)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.version.version
'1.14.3'
>>> x = np.zeros((50,2,64,24))
>>> x.shape
(50, 2, 64, 24)
>>> x[1,:,[4,2,10,50],:].shape
(4, 2, 24)
```

I expected (2,4,24) but it became (4,2,24)

**Comment by charris** [comment]
Try
```
In [11]: x[1,:,array([4,2,10,50]),:].shape
Out[11]: (4, 2, 24)
```
I am not sure what is going on with the list, I don't understand advanced indexing :( @seberg Thoughts?

**Comment by seberg** [comment]
Nothing special about the list, its just the transposing logic because the scalar might also be an array. Or rather the "not transposing" part of it, since transposing only works if scalar and list are next to each other. In other words @yoonbo, see also the documentation and the NEP stuff in gh-11414 (or that file). This example is one of the main "surprising to most people" examples...

**Comment by seberg** [comment]
I know the docs are not always easy to read (improvements welcome), but this part here:
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#combining-advanced-and-basic-indexing
