### ISSUE TITLE
Failed to Install NumPy with pip on Python 3.7.0

### ISSUE THREAD

**Issue by pfbuxton** [numpy/numpy#11447]
With Python 3.7.0 (no release candidate) I am having problems installing numpy.

pip install numpy     gives the message:
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

Note, this is not particularly specific to numpy as other packages which require compiling, such as pandas and jupyter also fail.

Please help!

Thanks,
Peter

**Comment by mattip** [comment]
Since we do not have binary wheels available yet, pip is downloading a source distribution and trying to compile it. You need a compiler, not the redistributable runtime. Microsoft changed the link, but more information is available [here](https://blogs.msdn.microsoft.com/vcblog/2017/11/02/visual-studio-build-tools-now-include-the-vs2017-and-vs2015-msvc-toolsets/). Be sure you get the one matching the cpython you are using.

In general we do not recommend building numpy from source. Wheels should be available soon on PyPI or wherever you get your packages.

Closing since this is not really a NumPy issue, reopen if you feel differently.

**Comment by Siecje** [comment]
Why don't you recommend building numpy from source? How do you get numpy to use `BLAS` and `LAPACK`?

**Comment by mattip** [comment]
NumPy as a binary package will usually include an implementation of OpenBlas. Compilation on windows is always a hit-or-miss game, and prone to errors due to environmental variables and compiler variations.

**Comment by pfbuxton** [comment]
Numpy for python 3.7 is now in the pip wheels. Thank you very much.

**Comment by Siecje** [comment]
@mattip Does the numpy wheel include OpenBlas? What about Lapack? Just to be clear, there is no performance benefit from compiling numpy? What about compiling Blas and Lapack and then installing the wheel?

**Comment by mattip** [comment]
On windows the wheels on PyPI currently provide and use OpenBlas. There are wheels that use MKL in Anaconda (last I looked) and in [gohlke's site](https://www.lfd.uci.edu/~gohlke/pythonlibs/).

NumPy can use OpenBlas without needing an additional Lapack interface. 

You should benchmark your setup to see if compilation gets you anything and is worth the bother, in general the answer will be "no", unless you really know how to tweak the compiler for your hardware. If you *do* find a simple way to make it faster, please let us or the OpenBlas people know.

There are methods to preload your own shard library in place of what NumPy provides without recompiling, but that goes way beyond the scope of this already-closed issue. Again, try it, let us know if you find it can be faster.

In any case you should be profiling the hot spots of your code to know if the `linalg`, `dot` or `matmul` routines are part of your bottlenecks
