### ISSUE TITLE
ENH: axis argument for fmin, fmax, minimum and maximum

### ISSUE THREAD

**Issue by attack68** [numpy/numpy#11465]
I had a use case yesterday where I needed to extract the minimum of two arrays but measured over an axis.

In the end I used,

    a_min = np.amin(a, axis =0)
    b_min = np.amin(b, axis=0)
    return np.minimum(a_min, b_min)
    # timeit gave 51.7 us for shape(1000,10)

or an alternative might have been,

    c_min = np.minimum(a, b)
    return np.amin(c_min, axis=0)
    # timeit gave 54.2 us for shape (1000,10)

But I wondered whether it would be a useful enhancement to have,

    return np.minimum(a, b, axis=0)

I think this would not conflict with any existing implementation since `axis=None` could be default, and a check for axis could evoke some code that might be faster than the workaround above?

Perhaps I missed a trick and this can already be done?

**Comment by mhvk** [comment]
@attack68 - an interesting suggestion, but you already found the two methods I would recommend (with a preference for the first, since there you end up with two generally much smaller result arrays, so it uses less memory).

The reason it is not easy is that `np.minimum` is a ufunc which strictly operates on each element (with the two arrays broadcast against each other); it has no concept of an axis, just like `np.add` (which is also a ufunc) has no concept of an axis. It can work on an axis with its `reduce` method - which uses the same elementary function in C but feeds it elements from a given array in sequence. Indeed, `amin` is just a very thin wrapper around `np.minimum.reduce` (see its definition in `fromnumeric.py`), just like `sum` is a thin wrapper around `np.add.reduce`.

Now your example is another one that effectively asks whether it wouldn't be nice to have the ability to construct chains of ufuncs, including ones that combine, e.g., comparison and reduction (`all_equal`). But we're not there yet.

Hope this explains things!

**Comment by seberg** [comment]
Yeah, the first version is both faster and uses less memory, the differences should be large as soon as the arrays are large enough to not fit into the (L2) cache anymore. Anyway, chaining ufuncs is a different issue, adding an axis argument into a ufunc itself seems not really a reasonable way here, how do you even know the a reduction of the result is meant? Also there is no real way to implement it straight forward anyway. That is except with ufunc chaining as suggested above (similar to what numexpr does, but it does not support reductions).

If you have very large arrays, we can show you how you can do something like such chaining in python (or even C) manually, but I do not think adding it in this way to the ufunc API is the right approach. I will close the issue, if we have a nicer approach or you want to discuss more we can reopen.

**Comment by eric-wieser** [comment]
I don't think ufunc chaining even offers any benefit there - there's not a more efficient way to implement this that the way used above, nor is there a clearer way to spell it.

**Comment by seberg** [comment]
Assuming the result of the intermediat reduction is larger then cache, it should be slightly more efficient. But, I had not really thought about it, and I agree that this will be a very very rare use case.

**Comment by attack68** [comment]
@mhvk @seberg @eric-wieser thanks for the comments and explanations. It clarifies things..

**Comment by eric-wieser** [comment]
@seberg: I see what you mean, I was only considering cases when the result was a scalar
