### ISSUE TITLE
Setting values in a slice fails

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#11486]
Just tracked down the nastiest bug in a while. Consider
```python
import numpy

a = numpy.array([[1], [2], [3]])
print(a[[1], 0])  # [2], looking good
a[[1], 0] = 4
print(a)  # [[1], [4], [3]], ok

a = numpy.array([[1], [2], [3]])
print(a[[1]][:, 0])  # [2], looking good
a[[1]][:, 0] = 5
print(a)  # [[1], [2], [3]] ?!
```
The first attempt at setting `a[1, 0]` to `4` works fine, everything as expected. The second one, not so much. I have no idea why, perhaps some temporaries created here or there? Nasty stuff, particularly since there's no warning or error.

**Comment by seberg** [comment]
Nothing strange here, `a[[1]]` has to create a copy since it is advanced indexing.

**Comment by seberg** [comment]
I suppose there is a tiny chance that one could check for reference counts and base arrays to guess if the change might be on a temporary array, but I have my doubts that will work reliably. But if someone wants to try it, be my guest.

**Comment by nschloe** [comment]
> a[[1]] has to create a copy since it is advanced indexing.

Yeah, this is really confusing. I mean, for some reason
```
a[[1], 0] = 4
```
works. Isn't that "advanced indexing" as well?

**Comment by seberg** [comment]
Yes, but not
```
tmp = a[[1]]
tmp[blah] = blup
```
Since numpy does no magic (or very little).

Note that the docs also discourage chained indexing, since there is rarely any benefit from it, plus you get confusing things like this. Exceptions are field access (which typically should go first IMO). Sometimes it is just more intuitive too, but then that advanced indexing should go last!

**Comment by nschloe** [comment]
> Note that the docs also discourage chained indexing, since there is rarely any benefit from it, plus you get confusing things like this.

Indeed. That's what I'll take home.

**Comment by njsmith** [comment]
A crucial thing to realize here is that in Python, there's a special case for `a[x] = y`. Even though it looks like a combination of `a[x]` and `x = y`, it's actually an entirely different third operation. Which makes sense, because otherwise `a[x] = y` couldn't work, and you couldn't assign into dicts or anything. But there's no similar special case for `a[x][y] = z`. It's expanded to `tmp = a[x]; tmp[y] = z`.
