### ISSUE TITLE
Bug:  Incorrect addition or subtraction involving column or row vectors in numpy & scipy

### ISSUE THREAD

**Issue by SchiffS** [numpy/numpy#11524]
As explained in greater detail in my repository https://github.com/SchiffS/Python.git, if A is an m x n array, even if cast as np.asmatrix() and B is either a column vector (shape 1xn) or row vector (shape mx1) then adding or subtracting A and B yields a result, instead of returning a ValueError.  According to the principles of linear algebra, two matrices A and B can be added or subtracted only if they are of identical order.  I have verified this bug exists with Python 2.7.10 (32 bit) and 3.6.2 (64 bit).  With 2.7 I have numpy version 1.3.2 and scipy version 0.16.  With 3.6 I have numpy version 1.31.1 and scipy version 0.19.1.
The attached code provides a partial demonstation of this bug.

#Error demonstration:  scipy & numpy (including with asmatrix() erroneously
#add and subtract matrices when one is a row or column vector

import numpy as np

A = np.array( [ [1,2,3] , [4,5,6] , [7,8,9] ] )  #3x3:  shape() = (3,3)
B = np.array( [ [1,2], [3,4] ] ) #2x2; Python behaves properly when adding A+B
C = np.array( [ [1], [2], [3] ] ) #3x1 column matrix; A+B or A-B should return ValueError
R = np.array( [ [1,2,3] ] ) #1x3 row matrix; A+R or A-R should return ValueError

print('A\n',A,'\nC\n',C,'\nA+C\n',A+C,'\n Wrong!\n')
print('R\n',R,'\nA-R\n',A-R,'\nAlso Wrong\n')
print('Order of A is',np.shape(A),'\n Order of B is\n',np.shape(B))
print('\Attempt to add A and B will result in ValueError as it should:')
A+B

**Comment by pv** [comment]
https://docs.scipy.org/doc/numpy-1.14.5/user/basics.broadcasting.html

**Comment by SchiffS** [comment]
Yes, I know about broadcasting, but nonetheless it is mathematically incorrect.  In experimenting with this, I was able to verify that according to the rules of broadcasting the n x n matrix with all 1s is equal to the nx1 column matrix with all 1s and the 1xn row matrix with all 1s.  This is an absurdity.  It might have utility in the broader sense of arrays, but when numpy or scipy is used in a linear algebra application, it can only lead to trouble.

I really do not care whether or not this is fixed, as, being aware of the problem, I can build functions to properly add or subtract matrices in my own code.  But when I showed this to a professor in the math department at MIT, he expressed amazement.

**Comment by mhvk** [comment]
@SchiffS - Thanks for reporting. `ndarray` are not meant to represent matrices, so certainly the example you give behaves exactly as it should; for most use cases, this is also what is wanted - N-D arrays have much broader use than matices.

With `asmatrix`, I think I agree with you that an error would be fairly logical, and it is in part because the `matrix` class is in many ways rather inconsistent that it is now considered a bad idea. The overall recommendation would seem to be that if you want to use `ndarray` to do linear algebra, one should take care of things like these oneself, and use routines from `linalg` where possible.

In any case, since for `ndarray`, the behaviour should stay the same, and we hope to get rid of `matrix`, I'll close this.

**Comment by seberg** [comment]
Well, not all of life is linear algebra, it is very convenient in many other things and a basic building block of how NumPy works...

**Comment by seberg** [comment]
Oh, didn't reload, was already closed :)

**Comment by eric-wieser** [comment]
One thing I've considered in the past is a way to enable stricter broadcasting rules, which a flag on each dimension indicating whether broadcasting is allowed (stored as an invalid/0 stride?), rather than just the size being 1. This would prevent people writing code that works only for N == 1 and not testing it for larger N

It would be easy to make `np.newaxis` work under this system, but I'm not sure how to express this through the `.resize` method.
