### ISSUE TITLE
Numpy delete

### ISSUE THREAD

**Issue by ameanijon** [numpy/numpy#11575]
Z.shape = (8, 240, 480)
(time, latitude, longitude)

Printing Z[4] outputs values, which I wasn't expecting for the shape of Z. Printing Z[10] gives the message `IndexError: index 10 is out of bounds for axis 0 with size 8`. 

Ultimately what I want to do is plot Z with basemap, but I don't want to plot each of the timesteps separately, which is what seems to be happening when I do Z[0], Z[1]. I have tried `np.reshape` and `np.delete`, none of which are working. If I do `np.delete(Z, 0, 0).shape` it prints `(7, 240, 480)`, when I was expecting it to become (240, 480).

I don't necessarily want to delete the time, but I'd rather not have to put it all in several different plots.

I'm using numpy 1.13.0 and python 2.7.3.

**Comment by seberg** [comment]
It sounds like your problem is with basemap. In any case, all of these things do exactly what they are supposed to do and what is documented for them, so I am not sure what surprises you. You may want to re-ask your question in another place and with more details on what you actually need, instead of what surprises you a bit.
