### ISSUE TITLE
numpy.random.choice may need to support more algorithms

### ISSUE THREAD

**Issue by HerculesJack** [numpy/numpy#11584]
From the source code,

```
if replace:
    if p is not None:
        cdf = p.cumsum()
        cdf /= cdf[-1]
        uniform_samples = self.random_sample(shape)
        idx = cdf.searchsorted(uniform_samples, side='right')
        idx = np.array(idx, copy=False) # searchsorted returns a scalar
    else:
        idx = self.randint(0, pop_size, size=shape)
```

It seems that numpy.random.choice currently uses the multinominal resampling algorithm. However, as pointed out by Roger R. Labbe in [Kalman and Bayesian Filters in Python](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python), section 12.8,

`
The performance of the multinomial resampling is quite bad... In practice both the stratified and systematic algorithms perform well and similarly across a variety of problems.
`

So I think we can make numpy.random.choice support more algorithms, like residual resampling, systematic resampling and stratified resampling.

**Comment by bashtage** [comment]
These other sampling methods are usually only directly applicable in 1 dimension and so may not be ideal candidates for a general purpose random infrastructure.

**Comment by rkern** [comment]
`choice()` already only samples in one dimension, no?

This is something that has been noticed before, and there are a number of PRs submitted to add better algorithms (e.g. #5911). They have all been stalled by our strict stream compatibility policy. But now NEP 19 resolves the issue, and a better default algorithm could be used in the new system that we're switching to (i.e. [`randomgen`](https://github.com/bashtage/randomgen)). I probably wouldn't involve a whole suite of algorithms. `randomgen` is better at allowing third-party packages implement efficient distribution algorithms on top of the same core generator, so I'd leave that to those third parties.

**Comment by rainwoodman** [comment]
bashtage may have been confused. The issue was only about `numpy.random.choice`, not about the general infrastructure. 

Here is the link to the text that described these different algorithms:

https://render.githubusercontent.com/view/ipynb?commit=0e43c1b9aef4242bf794fd5086319b1db496d057&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f726c616262652f4b616c6d616e2d616e642d426179657369616e2d46696c746572732d696e2d507974686f6e2f306534336331623961656634323432626637393466643530383633313962316462343936643035372f31322d5061727469636c652d46696c746572732e6970796e62&nwo=rlabbe%2FKalman-and-Bayesian-Filters-in-Python&path=12-Particle-Filters.ipynb&repository_id=19868085&repository_type=Repository#Choosing-a-Resampling-Algorithm

The author basically said the algorithm currently in numpy shall not be used; and we were convinced: multinomial sampling does tend to produce realizations that are very distant from the true distribution, when the size is small. 

The alternatives have less variance, and are all very simple, (just adding few lines in the current cython implementation). But it requires an additional argument on `choice` (API change), if we do want to reproduce the multinomial result by default. 

```
numpy.random.choice(a, size=None, replace=True, p=None, method='multinomial')
```

Nevertheless, it seems like the current plan is to freeze numpy.random and prefer to add improvements/fixes as something else?

**Comment by rkern** [comment]
We are freezing `RandomState`'s distribution methods and developing the new distributions under a different class, yes. Right now, @bashtage's `randomgen` is the candidate implementation for that new class. I'm not quite sure how we're going to manage that transition, yet, but I suspect that we'll try to implement as many of these distribution changes in `randomgen` first in its own repo, then merge it into numpy. I think it would be least disruptive to make sure that we get all of the algorithm changes that we know we want before the first release so that there is less churn thereafter.

@bashtage We should have a chat about how you'd like to handle that. That chat probably shouldn't be here. :-)

**Comment by rainwoodman** [comment]
Thanks. I just looked the choice function in randomgen is the same aa
numpy's. Shall we try to implement the improvements there?

**Comment by bashtage** [comment]
@rainwoodman PRs are welcome there.
