### ISSUE TITLE
np.copyto not working properly

### ISSUE THREAD

**Issue by chandanbiswas08** [numpy/numpy#11623]
```python
import numpy as np
import pickle
with open('testdata.pkl') as f:
    dst,d,d1,d2 = pickle.load(f)
np.copyto(dst[d1], -5555, where = np.greater(d[d1], d2)[0])
print(np.where(dst==-5555))
temp = dst[d1]
np.copyto(temp, -5555, where = np.greater(d[d1], d2)[0])
dst[d1] = temp
print(np.where(dst==-5555))
```

Output
```
(array([], dtype=int64),)
(array([   14,    34,    38, ..., 99941, 99958, 99978]),)
```

[testdata.pkl.zip](https://github.com/numpy/numpy/files/2232609/testdata.pkl.zip)

**Comment by eric-wieser** [comment]
Why are you adding the `[0]`?

**Comment by seberg** [comment]
That will not work, now that thing might be able to warn you, but I am sure `d1` is an array, so that `dst[d1]` is a new fresh array. So you are assigning to a temporary array.

I am not sure how practical a warning would be here, if you wish we can reopen the issue to read that we may want to look if a warning is good. Feel free to keep discussing/ask if you do not understand the explanataion!

**Comment by chandanbiswas08** [comment]
@seberg thank you for reply, but what should I do to reflect in original array without using temp variable.

**Comment by seberg** [comment]
Well, I do not know everything about what you got (such as what `d1` is, a boolean index or not?). You probably have to do something like you did in the second part, or something very similar. Or you create a `d1bad` and use that, such as `d1bad = d1[d[d1] > d2]; d[d1bad] = -5555`.
