### ISSUE TITLE
Where can I find the change record before the 1.12 version?

### ISSUE THREAD

**Issue by forbxy** [numpy/numpy#11654]
We try to upgrade numpy, Unfortunately，we have  a lot of programs written based on the old version of numpy.We have to know the incompatibility between versions. In the source code I only found the changelog after 1.20.
thanks

**Comment by seberg** [comment]
The main compatibility issues should be listed in the release notes mostly (and more readable). Those are also located in the docs under `release`.
When/before updating, make sure that you see/enable DeprecationWarnings. If you are unsure about it, it might even make sense to not jump more too many versions at once, just to see new FutureWarnings. That said, most code shouldn't really have problems with upgrading numpy.

**Comment by charris** [comment]
If you are talking about the changelogs in `doc/changelog`, they are new. I can generate entries for earlier releases, which is why they go back as far as 1.12. If you think they might be interesting for earlier than that I can add them.

That said, what @seberg said is a useful guide to upgrading. It should be generally safe, but it is always a good idea to have test coverage.

**Comment by mattip** [comment]
@forbxy closing this, please reopen if you have more a more specific question
