### ISSUE TITLE
Issue in numpy.pad

### ISSUE THREAD

**Issue by pawangeek** [numpy/numpy#11709]
When i run array.pad with [1,2] It is correct but when I run it with [None] array it shows dtype alongside result. 

I don't find any imformation of showing dytpe in documentation.

```python
import numpy as np

<< np.pad(np.array([1,2]),[0,0],'wrap') >>
<< array([1, 2]) >>

<< np.pad(np.array([None]),[0,0], 'wrap') >>
<< array([None], dtype=object) >>
```
### Numpy version information:
Numpy version - 1.14.0 in Anaconda and OS - Linux

**Comment by mattip** [comment]
You do not say what bothers you about seeing the dtype or why this is surprising. This is not unique to `np.pad`. Your call is returning an `ndarray`, which always has a `dtype` even if it is not printed. Any dtype except `int` and `float` (and their aliases) will be printed in the `repr`, by design.

If you wish, `str(np.pad(np.array([None]),[0,0], 'wrap'))` will print out something simpler, but will not change the returned object from the `np.pad` call, it will still be an `ndarray`
