### ISSUE TITLE
linalg.svd is slower than naive implementation

### ISSUE THREAD

**Issue by pierreablin** [numpy/numpy#11795]
Hi,

I have just figured out that for 2d arrays, `linalg.svd(X, full_matrices=False)` is slower than the following naive implementation:

### Naive SVD
```python
import numpy as np
from numpy.linalg import eigh

def my_svd(X):
    eps = np.finfo(np.double).eps
    n, p = X.shape
    if n < p:
        D, U = eigh(np.dot(X, X.T))
        D[D < eps] = eps
        d = np.sqrt(D)
        V = np.dot((1. / d[:, None]) * U.T, X)
    else:
        D, V = eigh(X @ X.T)
        D[D < eps] = eps
        d = np.sqrt(D)
        U = np.dot(X, V / d)
        V = V.T
    return U, d, V
```

For instance, on my computer:
```python
In [2]: X = np.random.randn(10, 1000)

In [3]: %timeit np.linalg.svd(X, full_matrices=False)
263 µs ± 4.27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [4]: %timeit my_svd(X)
68.1 µs ± 362 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

An it gets worse and worse as the matrices get flatter. Note that I observe the same behavior for `scipy.linalg.svd`.

**Comment by charris** [comment]
The problem is `eigh(np.dot(X, X.T))`, which is not as numerically accurate. That is not so much a problem with your example, as the rows are almost orthogonal to start with. That is why the normal equations are avoided when solving OLS problems. If you are familiar with the problem, need the speed, and are assured of sufficient accuracy, then your approach is generally faster. But it is a special case sort of thing.

**Comment by pierreablin** [comment]
Ok thanks for the quick answer, I was not familiar with this problem!
