### ISSUE TITLE
Providing Public Cython API within NumPy

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#11803]
Would it make sense for NumPy to provide `numpy.pxd` and `numpy/math.pxd` (currently [included in Cython]( https://github.com/cython/cython/tree/0.28.5/Cython/Includes/numpy ))?

Given NumPy already ships SWIG bindings, providing Cython bindings seems reasonable and is not too different in concept. Plus there are already [internal consumers]( https://github.com/numpy/numpy/blob/v1.15.1/numpy/random/mtrand/numpy.pxd ) of Cython bindings, which would likely benefit from having access to a single public API. Would add that other projects like SciPy have been adding a fair number of things in `*.pxd` files included in their public API making this a bit of a trend. This would certainly help build a framework for NumPy to [expose other things in the public API]( https://github.com/numpy/numpy/issues/11764 ). Finally would note that having the Cython bindings live in Cython complicates the process of keeping them up-to-date as they must provide support for [various versions of NumPy]( https://github.com/cython/cython/blob/62ed5b2c796d9ae3c622b2e26fd162d8b9813f53/Cython/Includes/numpy/__init__.pxd#L160 ), which should *hopefully* be less of a problem if Cython bindings were included in NumPy's public API.

Thoughts on this would be welcome. :)

**Comment by shoyer** [comment]
I think this would probably be a good idea.

**Comment by rgommers** [comment]
Makes sense I think. The Cython wrappers in SciPy have been popular and unproblematic.

**Comment by mattip** [comment]
Sounds reasonable, and there is even a start in `numpy/random/mtrand/numpy.pxd`, which is used as `include "numpy.pxd"` in `mtrand.pyx`. I see that most code  does not use the `include` statement rather the cython [cimport](http://docs.cython.org/en/latest/src/userguide/sharing_declarations.html#the-cimport-statement): `cimport numpy as np`. How we would get the latter to use our wrapper over cython's wrapper? Would it be enough to encourage use of `from numpy cimport numpy as np`?

Should we pin tests to a certain version of cython, or would it be better to test against a range of cython versions (with the associated complications)?

**Comment by bashtage** [comment]
Doesn't Cython already provide a lot of the NumPy API?

https://github.com/cython/cython/blob/master/Cython/Includes/numpy/__init__.pxd

**Comment by mattip** [comment]
@bashtage I think this discussion began as cython/cython#2498, and now we need to decide what is easier:
- depend on cython to ship the wrapper and stay consistent with NumPy API changes
- ship our own wrapper, and make sure we do not break with changes in cython

**Comment by scoder** [comment]
It seems totally right to me to have NumPy maintain and ship its own Cython declarations, rather than letting Cython do it. Above all, the C-API that they describe depends on the NumPy version and not on the Cython version, and it's not Cython's decision when and how to deal with additions or incompatible changes.

For a migration, Cython already searches the include path before its own standard include directories, so as long as users pass `numpy.get_includes()` into Cython's build, and NumPy keeps its `.pxd` files in that path, Cython should pick up NumPy's own `.pxd` files first. We'd still have to keep the files on our side for a while so that users can Cython-translate their code with older NumPy versions, but at least there'd be a layed-out path towards removing them somewhere in the 2020's.

**Comment by jakirkham** [comment]
This came up again recently in regards to whether certain NumPy functions require the GIL and whether that is reflected correctly in the Cython API. ( https://github.com/cython/cython/issues/2663 )

Side note: Some questions were raised regarding documentation of GIL use in NumPy's C API as well.
