### ISSUE TITLE
np.inner crashes with MemoryError on moderate-sized arrays

### ISSUE THREAD

**Issue by Felix-neko** [numpy/numpy#11839]
I have two sets of 3D vectors, each 500x1000 in size. I want to take their inner products, but numpy crashes with `MemoryError`.

Can you somehow fix it?

```
import numpy as np
a_vecs = np.zeros((500, 1000, 3), dtype=np.float64)
b_vecs = np.zeros((500, 1000, 3), dtype=np.float64)
scalars = np.inner(a_vecs, b_vecs)
```
MemoryError = (

OS: Windows 7x64
Python: 3.6x64
numpy: '1.14.2'

**Comment by charris** [comment]
Inner isn't doing what you think, the shape of the result will be (500, 1000, 500, 1000), i.e. 2000000000000 bytes.
```
In [3]: a = ones((5,4,3))

In [4]: np.inner(a, a).shape
Out[4]: (5, 4, 5, 4)
```
I think what you want is einsum
```
In [5]: einsum('...i, ...i', a, a).shape
Out[5]: (5, 4)
```

**Comment by seberg** [comment]
Sure, can be closed I guess. The only thing that we could discuss again at some point is whether we want to attempt a deprecation of `np.dot`/`np.inner` outer behaviour (`np.outer` is also a bit strange). This is all there for a very good reason I am sure, but it all seems a misfit for the rest of numpy, this bug report is a symptom of that.
But it seems likely there might be open issues for that even. I am sure we discussed it when `@` came around, since it does not inherit that logic from `np.dot` of course.

**Comment by charris** [comment]
It's old, old behavior, either came from Numeric or it was the easiest iterator to implement :)

**Comment by seberg** [comment]
Hehe, good reasons :).

Maybe a good time to think about such deprecations again will be when we drop python 2 support. Then the few places that might actually run into such things in `dot` could fix the manual broadcast and also switch to the `@` operator at the same time. The (probably) last function in this list is `np.vdot`...

**Comment by seberg** [comment]
As mentioned before, lets close this. I think this is even documented pretty well. inner/outer and firends of have some oddities, but that was not the issue here.
