### ISSUE TITLE
numpy arange includes right hand side

### ISSUE THREAD

**Issue by rshap91** [numpy/numpy#11913]
Not sure if this is a bug or not but i seem to be able to generate an array using `np.arange` that includes the right hand side...

### Reproducing code example:

```python
import numpy as np

np.arange(1,1.5,.1)
# array([1. , 1.1, 1.2, 1.3, 1.4])

np.arange(1,1.6,.1)
# array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6]) ???
```

is this the correct behavior?

### Numpy/Python version information:

1.14.5 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

**Comment by eric-wieser** [comment]
I think this is a bug - but not because it appears to contain `1.6`, but because:
```
>>> np.arange(1,1.6,.1)[-1] < 1.6
False
```

It seems to me that `np.all(arange(start, stop, step) < stop)` ought to be an invariant.

**Comment by charris** [comment]
Note also that '.1' and '1.6' are not true floating point numbers, they can not be exactly represented in IEEE floating point.

**Comment by charris** [comment]
@eric-wieser 
```
In [5]: floor((1.6 - 1.)/.1)*.1
Out[5]: 0.6000000000000001
...
In [13]: '%20.18f' % 1.6
Out[13]: '1.600000000000000089
```
 `arange` is simply unreliable for floating point, if "exact" numbers are wanted different methods need to be used.

**Comment by eric-wieser** [comment]
Representation of decimal numbers aside, I don't think `arange` should ever produce results beyond its end point

**Comment by seberg** [comment]
Well, I would agree that arange (while probably inherently annoying for floats) has pitfalls, call them bugs, that should not be there. But while fixing this one might not hit libraries hard, it could hit a lot of dirty scripts out there very hard.

**Comment by ncgeib** [comment]
This is behavior is [documented](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html): "For floating point arguments, the length of the result is `ceil((stop - start)/step)`. Because of floating point overflow, this rule may result in the last element of _out_ being greater than _stop_."

There was a [discussion on the mailing list](https://mail.python.org/pipermail/numpy-discussion/2018-February/077707.html) about the details of the arange calculation a while back.

If I remember correctly, the discussion boiled down to: don't use `arange` for floats. If you know number, spacing and start of the grid points use: `x0 + np.arange(N) * dx`. If you know number of grid points and the extent of the grid use `linspace`.

@eric-wieser This approach accumulates error. It is potentially inaccurate.

**Comment by eric-wieser** [comment]
Thanks for the archaelogy, @ncgeib

**Comment by Mikea1985** [comment]
I just ran into this bug for the first time and was extremely perplexed. Would it be worth having arange spit a warning message when used with floats (the warning could urge the user to use a more predictable method), because I'm sure that many people use it in this "dirty" fashion.

**Comment by tabaker99** [comment]
Just discovering this. It doesn't make it sound any better to say "it's okay that `arange` is buggy, because there is a warning in the documentation." If we shouldn't use `arange` for floats, then `arange` should reject floats. If it accepts parameters and gives a return value, then it should have stable behavior.
