### ISSUE TITLE
memoryview BufferError with F-contiguous arrays in python3

### ISSUE THREAD

**Issue by anwarnunez** [numpy/numpy#12006]
In Python3, accessing the memory-view of an F-contiguous array yields a `BufferError`. This behavior was supported in Python2. Is this an intended behavior change?

### Reproducing code example:

This fails in Python3 but it works in Python2
```python
import numpy as np
arr = np.asarray(np.random.randn(20, 10, 5), order='F')
from io import BytesIO
o = BytesIO(arr.data)
```

Here are the array flags:
```
>>> arr.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

### Error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
BufferError: memoryview: underlying buffer is not C-contiguous

### Numpy/Python version information:

Python3:
```
1.15.1 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]
```

Python2:
```
1.14.5, 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]
```

**Comment by seberg** [comment]
This is not related to numpy, note that:
```
mv = memoryview(arr)
BytesIO(mv)
```
fails with the same error message and pretty much takes numpy out of the equation. It seems BytesIO just expects a C-contiguous blob, and maybe that makes sense, since BytesIO is probably naturally 1-D and thus has to ravel, and if you do not have a contiguous memory block, things might be surprising.

Note that `o = BytesIO(arr.reshape(-1, order='F'))` and is explicite about the reshape part (although reshape will copy if it cannot reshape it without a copy).

**Comment by seberg** [comment]
I guess you are using the `.data` attribute, so that might have changed between the versions and maybe before it lost the shape/contiguity information. It has been very long, my first gut feeling is that it isn't bad to return a memoryview of the array as `.data` (which knows about shape) and that going back might just as well break things then fixing your regression.

**Comment by eric-wieser** [comment]
> that might have changed between the versions

Yep, on python 2.7 I get a `buffer`, whereas on 3 I get a `memoryview`. The `buffer` type was removed in python 3, so there's no sensible way to revert to the old behavior even if we wanted to.

In principle we could update the 2.7 behavior to also use a `memoryview` and fail in the same way - that would front-load the compatibility issues users upgrading to python 3 face, which may or may not be a good thing.

**Comment by anwarnunez** [comment]
I see. Thanks for the explanation!

**Comment by charris** [comment]
> In principle we could update the 2.7 behavior

I was trying to keep things separated. I expect that introducing an error in 2.7 would be somewhat disturbing. We could also switch to PyCapsule*, but I think that would also be bothersome.
