### ISSUE TITLE
Converting masked array from float to uint8 does not convert dtype of fill_value

### ISSUE THREAD

**Issue by jarlehr** [numpy/numpy#12070]
When a masked array of dtype float32 is converted to uint8, the dtype of the fill_value persists. When setting the fill_value to a uint8 value, the value is converted to float. Filling such an array yields an array of dtype object.

This was working in numpy==1.14.

### Reproducing code example:

```python
import numpy as np

foo = np.ma.masked_equal(np.arange(10, dtype="float32"), 5)
foo.fill_value = -1.0
bar = foo.astype("uint8")
print(bar.fill_value)
bar.fill_value = 255
print(bar.fill_value)
print(bar.filled().dtype)
```
### Error message:
with numpy==1.14.2 this yields:
```
255
255
uint8
```

with numpy==1.15.2 this yields:
```
-1.0
255.0
object
```

### Numpy/Python version information:
Tested with python 2.7 and 3.5.2
numpy==1.15

**Comment by charris** [comment]
@eric-wieser ISTR that you made some changes here.

**Comment by charris** [comment]
I think it is probably #10211 from @mhvk.

**Comment by mhvk** [comment]
I fear that this regression is indeed my fault...  I'll try to look at it, but as I am a bit overwhelmed right now, I fear it may be a while. The easiest would be to reintroduce the `astype` override, which just calls `super` for the main work, and then keeps the deleted part about `fill_value` (an alternative might add code to `__array_finalize__`). But this also needs to add some tests, since clearly our existing coverage did not catch this.

**Comment by charris** [comment]
I'll take care of it.

**Comment by charris** [comment]
> since clearly our existing coverage did not catch this.

@mhvk  Yes, we do a lot of refactoring these days and it exposes the lack of complete test coverage, especially in unloved packages like masked arrays. My experience with tests is that when I make them more complete they invariably turn up bugs.

**Comment by charris** [comment]
@mhvk see #12224, needs review.
