### ISSUE TITLE
Multiple axis indexing with array-like

### ISSUE THREAD

**Issue by futscdav** [numpy/numpy#12227]
When using multiple array-like objects to index into and ndarray, numpy returns what seems to me like an incorrect result. Built-in slice indexing works correctly, also one array-like plus slices works correctly. I actually ran into this issue in pytorch, but the bug seems to be consistent with numpy. Best shown with code:
### Reproducing code example:

```python
import numpy as np
a = np.random.rand(5,5,5,5)
a[:, 0:2, :, 0:2].shape
a[:, [0,1], :, [0,1]].shape
```
The issue persists with anything that isn't a slice - range, list, tuple, any array-like that I could think of.

### Output:
Expected output:
(5,2,5,2)
(5,2,5,2)
Actual output:
(5,2,5,2)
(2,5,5)

### Numpy/Python version information:
Python 3.6.5, numpy 1.15.2

**Comment by u55** [comment]
This is expected behavior, see the [docs on advanced indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#integer-array-indexing). By default, the non-slice indexes are iterated together, and therefore must be the same size.
```python
>>> a[:, [0,1], :, [0,1,2]].shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 
```
To do what you want, and imitate the behavior of slicing, you have to broadcast the integer index arrays against each other. The convenience function [`ix_`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ix_.html#numpy.ix_) can help with this.
```python
>>> indx = np.ix_(range(5), [0,1], range(5), [0,1])
>>> a[indx].shape
(5, 2, 5, 2)

```

**Comment by futscdav** [comment]
Ok, I must admit that I didn't expect this to be intended behavior. I can't see how someone could look at that code and expect that result without being intimately experienced with the quirk. Good to know, thanks, it solves my problem. Sadly I guess it would be almost impossible to change due to backwards compatibility anyway, then.
