### ISSUE TITLE
ENH: expose matmat, matvec, vecmat ufuncs

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#12348]
@charris [commented](https://github.com/numpy/numpy/pull/12219#issuecomment-436412360) on PR #12219 wishing to expose the vector-matrix matrix-vector loops function from the matmul ufunc. 

We would need two ufuncs with signature `(1,n),(n,p?)->(1,p?)` and `(m?,n),(n,1)->(m?,1)`, and could reuse the `@TYPE@_matmul` loops

**Comment by eric-wieser** [comment]
I'm not sure I understand those signatures - why the frozen 1 dimension?

**Comment by mhvk** [comment]
gh-25675 adds possible `matvec` and `vecmat` functions, though `vecmat` is not identical to what `matmul` does, since it conjugates complex vectors (which seems more logical, probably best to discuss in gh-25675 or on the relevant mailing list discussion: https://mail.python.org/archives/list/numpy-discussion@python.org/thread/LX36TEAENIDSSFAKS6YLXXLWVOBABSEC/
