### ISSUE TITLE
What does numpy do when np.transpose()?

### ISSUE THREAD

**Issue by yiran7324** [numpy/numpy#12436]
I know this question must be too simple for you but I really had a hard time understanding this.

For example:

```
import numpy as np
x = np.array([[[ 1,  2,  3],
                        [ 4,  5,  6]],
                       [[ 7,  8,  9],
                        [10, 11, 12]]])
y = np.transpose(x, (0, 2, 1))
# [[[1,  4],
#   [2,  5],
#   [3,  6]],
#  [[7, 10],
#   [8, 11],
#   [9, 12]]]
```

What does np.transpose() do when we add (0, 2, 1) or sth else, is it an axis change or other thing? May I have some direct and efficient way to understand this "transpose" operation?

Thanks!

**Comment by mhvk** [comment]
It is not so easy to understand, and best may be to just try many examples: here, you keep axis 0 first, and then swap the last two axis.  That is, `old[i,j,k] = new[i,k,j]`

Under the hood, all it does is change the strides of the arrays, i.e., it uses the same memory but interprets locations differently:
```
In [4]: x.strides
Out[4]: (48, 24, 8)

In [5]: y.strides
Out[5]: (48, 8, 24)
```

Hope this helps. Note that I will close this issue, since this forum is really meant for actual issues and improvements, not for help. Stackoverflow is better for that.
