### ISSUE TITLE
Remove Python 3.4, 2.7 from setup.py

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12480]
We have planned to support Python 2.7 and >=3.5 for the 1.16 release.

**Comment by charris** [comment]
We don't officially support 3.4, but it still works, so I don't see any reason to raise an error when one attempts to compile with it. I suppose PIP will attempt to install from source if someone running 3.4 attempts an install 1.16. However, we will be dropping 2.7 support in 1.17, so I am going to push this off to the next release.

**Comment by bashtage** [comment]
Hasn't this already been implemented in setup?

https://github.com/numpy/numpy/blob/master/setup.py#L31

**Comment by charris** [comment]
Yep, thanks for the heads up.

**Comment by Juanlu001** [comment]
Instead of making pip download the source and then fail with a `RuntimeError` in Python 3.4, wouldn't it be better to actually mark it in the `python_requires`? I was about to suggest the change after reading the 1.16.0rc1 release announcement, but then saw this issue.

**Comment by Juanlu001** [comment]
Also, what is this line supposed to do? https://github.com/numpy/numpy/blob/f4c497c768e0646df740b647782df463825bfd27/setup.py#L36

**Comment by bashtage** [comment]
This line also give the wrong idea to pip:

https://github.com/numpy/numpy/blob/f4c497c768e0646df740b647782df463825bfd27/setup.py#L374

**Comment by charris** [comment]
PR's welcome. I guess the intent is that Python 3.4  be rejected, but I don't know to make sure pip does that.  Are any of you actually hitting this problem?

**Comment by charris** [comment]
Note that 1.6 can still be compiled with Python 3.4, we just don't produce any wheels for that version.

**Comment by Juanlu001** [comment]
> Note that 1.6 can still be compiled with Python 3.4, we just don't produce any wheels for that version.

In that case, I guess it makes sense to not remove it from `python_requires`, but then this part is inconsistent:

https://github.com/numpy/numpy/blob/3d7e90c21f64e8905585c1e25f4fe64934171e7f/setup.py#L30-L31

As it stands now, after doing `pip install numpy` in a Python 3.4 environment, the source distribution will be downloaded (because there's nothing telling pip not to do so) but it will fail because of the checks above.

On the other hand, the `python_requires='>=2.7` part is clearly wrong, as Python 2 has already been dropped, and again Python 2 users will see that pip downloads NumPy 1.16 but fails to install it.

I am making a PR.

**Comment by Juanlu001** [comment]
_Edit: I misunderstood the Python 2 part_
