### ISSUE TITLE
Rename axis to "rowwise"

### ISSUE THREAD

**Issue by aamster** [numpy/numpy#12557]
The parameter "axis" should be renamed to a boolean parameter "rowwise" or something similar which is human understandable in all numpy functions which take axis as an argument. No one can remember in which direction "axis" computes something. Making the name human readable will be a good improvement.

**Comment by seberg** [comment]
Thanks for your interest in making numpy more userfriendly. I am not sure I like `rowwise` more, but understand that you want to highlight that the operation is *along* the axis which is good. However, such a change would be very disruptive and frankly I do not think that `axis` itself is such bad name that it warrants much disruption.

**Comment by eric-wieser** [comment]
This also would not generalize well to 3d arrays and beyond

**Comment by aamster** [comment]
It's possible the name `axis` can be kept, but it can default to the string `row` and also accept the string `column` or an int. This would address the "can't remember which direction axes 0 and 1 are along" frustration.

**Comment by eric-wieser** [comment]
Note also that the idea of a row (axis=-1) or column (axis=-2) only actually matter:
* When printing, which happens to show the last axis as rows due to the limitations of plain-text output.
* In linalg and matmul

Everywhere else, you're free to think of whichever axis you like as the row. For instance, in an rgb image the convention is to use axis=-2 as the row
