### ISSUE TITLE
standalone dtype kind set to "V" for shaped dtypes

### ISSUE THREAD

**Issue by danielhrisca** [numpy/numpy#12694]
The kind of a standalone dtype that contains shape information is set to "V" instead of the expected kind.

### Reproducing code example:

```python
import numpy as np

dt = np.dtype("(2,)f8")
print(dt.kind) # "V"

arr = np.array([], dtype="(2,)f8")
print(arr.dtype.kind) # "f"
```

### Numpy/Python version information:

1.15.4 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
There are two things you're seing here:

* subarray dtypes are weird, and have `.type == np.void`
* subarray dtypes are weird, and disappear when you construct arrays from them. Note that `np.array([], dtype="(2,)f8").dtype` has lost your shape information, which has moved into the array itself.

The first is an implementation quirk that may someday go away, I wouldn't go as far as calling it a bug, but it might be nice to improve.

The second is by design, and can be worked around by creating a wrapping structured type around the subarray type.

**Comment by danielhrisca** [comment]
Hello Eric,

thank you for the pointers. 

Is there a reason why the type is set to void for sub-arrays?

**Comment by eric-wieser** [comment]
`void` became a catch-all base type for compound data types, similar to how `object` is such a type in python. Structured types also have `type = np.void`.

I don't think this was a particularly good design, but it was a simple one. This might change as part of the planned dtype refactoring.

**Comment by danielhrisca** [comment]
It would be a nice improvement.

I will close this for now.
