### ISSUE TITLE
BUG: f2py shell behavior

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#12756]
Creating an issue / bookmark for the recent report from @embray in #11937, related to removal of `exec_command()` from `f2py` machinery, which reads:

> Unfortunately this seems to have broken the previously documented assumption that f2py would be called through a shell. In SageMath, this fact was used by using shell I/O redirection (e.g. > <filename>) to capture standard I/O from the f2py call. This have passed shell=True to subprocess.check_output in order to preserve that behavior, unless breaking it was intentional. This was also used to capture stderr, which I think the current code does not do.

> Also discussed at https://trac.sagemath.org/ticket/27000#comment:10

**Comment by tylerjereddy** [comment]
Should be careful to make sure that any fix applied for this does not interfere with the original objective of the set of changes, which was related to another shell configuration matter raised by some NASA engineers.

**Comment by embray** [comment]
Thank you for creating the issue.  I've already worked around it in sage by simply not using `f2py.compile()` in the first place, and making my own `subprocess.Popen` with the appropriate error capture.  Perhaps bizarre shell issues like #11824 are indeed better avoided by not using `shell=True`, which will always carry some danger like that.  

In [my workaround](https://git.sagemath.org/sage.git/diff?id=fabc18b1c13af0783a6e5af9faec747eed1a46c8) I just made it possible to capture stderr so that I could include it in any exception messages.  The only reason `shell=True` was needed in the first place was as a hack to capture the stdout and stderr, and really it shouldn't be needed in the first place.

**Comment by mattip** [comment]
Since the original reporter has a work-around, can we close this?

**Comment by embray** [comment]
@mattip @tylerjereddy please reopen.  Just because I have a workaround doesn't mean it's a good one or there isn't something to fix here.  My workaround would essentially form a basis for a patch to make this a little better (namely making it easier to get stderr from the FORTRAN call--currently this is now impossible with f2py.compile

**Comment by mattip** [comment]
Looking at your [changes](https://git.sagemath.org/sage.git/commit/?h=81cc6bf6686103a9f4717ac99913f447f90c1821), it seems `f2py.compile(x, name, ...)` used to write to a `name.log` file but no longer does? I don't see that documented in the [`f2py.compile` documentation](http://www.numpy.org/devdocs/f2py/usage.html?highlight=f2py%20compile#numpy.f2py.compile). The warning at the top of the  docstring does state the interface can change. What if we add an option to return a tuple of `(status, stdout, stderr)` from `compile`?

**Comment by mattip** [comment]
@charris should we remove this from 1.16.1? I don't think this should block the bug-fix release, as it seems a deeper analysis is needed.

**Comment by charris** [comment]
@mattip  Sounds reasonable, I'll move it to 1.16.2.

**Comment by charris** [comment]
Off to 1.19 this goes. Be nice to resolve it.@embray do you have a suggestion for a fix?

**Comment by embray** [comment]
It appears the original link to my alternative broken [so here it is again](https://gitlab.com/sagemath/sage/blob/develop/src/sage/misc/inline_fortran.py#L179).

If I recall correctly, the original code was calling `subprocess.Popen` with `shell=True`, and using non-portable shell constructs for I/O redirection, rather than using `Popen`'s built-in capabilities for that.

I think I like @mattip's suggestion to optionally return a `(status, stdout, stderr)` tuple, and maybe also include an option to disable writing to the log file.  Since the log file feature is also not even documented (and a bit superfluous) I might also leave that as the default behavior, but deprecate it.

**Comment by eric-wieser** [comment]
> What if we add an option to return a tuple of (status, stdout, stderr) from compile?

Rather than inventing our own return format, why not return a `subprocess.CompletedProcess` , by using `subprocess.run` instead (assuming we only target 3.x with the eventual fix here)

**Comment by embray** [comment]
It's not such an invention; such a tuple format is fairly common in other contexts.  But I certainly have no problem with using `subprocess.run` and returning `CompletedProcess`.  I think the important point here is there's nothing much fancy going on here other than running f2py in a subprocess with some arguments :)

**Comment by mattip** [comment]
@embray do you have any interest in making a PR with the proposed changes?

**Comment by embray** [comment]
Okay, I will offer a PR.
