### ISSUE TITLE
comparing divide performances

### ISSUE THREAD

**Issue by garanews** [numpy/numpy#12760]
Hello,
I'm trying to find which one is performing better:

1) maxPQ = np.sum(np.maximum(vector_a, vector_b))
    return np.sum(np.minimum(vector_a, vector_b))/maxPQ

2) maxPQ = np.sum(np.maximum(vector_a, vector_b))
    return np.divide(np.sum(np.minimum(vector_a, vector_b)) ,maxPQ)

3) return np.divide(np.sum(np.minimum(vector_a, vector_b)) ,np.sum(np.maximum(vector_a, vector_b)))

I did some test and it seems that 1 is the fastest. 
What do you think?
Thanks

**Comment by seberg** [comment]
I will close this, is there something really specific about it you wish to ask? Then go ahead although the mailing list or some other place may be better. Or do you expect a performance issue somewhere? Otherwise, the first may be faster since the division is for scalars, meaning `np.divide` adds some unnecessary overhead probably.
