### ISSUE TITLE
numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

### ISSUE THREAD

**Issue by simonm3** [numpy/numpy#12785]
Was all working until recently. Now I get this error when I try to import bcolz.

I have tried pinning numpy version to 1.14.2. I have tried installing numpy first. Tried uninstalling numpy and reinstalling which just gives me different errors - compile failed with error code 1. Tried adding --no-cache-dir.

Stuck as can't even go back to where I was!

**Comment by simonm3** [comment]
OK I found by installing bcolz last it then imported fine. However now I get similar error but the opposite way round for skimage.

numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject.

**Comment by mattip** [comment]
Are you using `cython>=0.29`? Are you getting a warning or an error?

**Comment by mattip** [comment]
A more complete explanation: You should use at least the version of numpy used by any of your dependencies, so you should be using what `scikiti-mage` uses or newer. If the `PyObject` is bigger than the C header, it should be a warning and you can ignore it (the warning has been quieted with cython 0.29 and later). The opposite situation, when the `PyObject` is smaller than what cython expected in the C header it was compiled with, is an error and cannot be recovered from. Since the numpy `PyObject`s are guaranteed to only grow in size, not shrink, by using a later numpy you should only see a warning. Once all the dependent packages move to cython 0.29 or later you shouldn't even see a warning.

**Comment by simonm3** [comment]
Got it working now. skimage released a new version so could be part of same pip install.
