### ISSUE TITLE
broadcasting is not associative

### ISSUE THREAD

**Issue by Verma-Rajat** [numpy/numpy#12840]
Broadcasting behavior is not associative. (a x b) x c != a x ( b x c)

### Reproducing code example:

```python
import numpy as np
data_0 = np.arange(120).reshape(2,3,4,5)
data_1 = np.arange(20).reshape(4,5)
data_2 = np.arange(5).reshape(5,)

# this one works fine
np.maximum(data_2, data_1, data_0)

# below does not works
# gives error "ValueError: non-broadcastable output operand with shape (5,) doesn't match the broadcast shape (2,3,4,5)"
np.maximum(data_0, data_1,data_2)
```

### Numpy/Python version information:

('1.16.0', '2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]')

**Comment by eric-wieser** [comment]
What you're seeing here is that `np.maximum(data_2, data_1, data_0)` is not associative, which is because you're using it incorrectly - the signature is `maximum(in1, in2, out)`!

As proof that when used correctly, it is associative - `np.maximum(np.maximum(data_0, data_1), data_2)` and `np.maximum(data_0, np.maximum(data_1, data_2))` are the same.
