### ISSUE TITLE
Bug: floor division of 0 returns -0.0

### ISSUE THREAD

**Issue by timb82** [numpy/numpy#12841]
Numpy returns a weird results of 
0//1 = -0.0, 
while python itself returns 0.0 as expected

```python
import numpy as np
0.0//1                    # returns 0.0  
np.float32(0.0)//1        # returns -0.0
```

I've asked about that on [stackoverflow](https://stackoverflow.com/questions/54331829/weird-result-of-floor-division-in-numpy/54332310#54332310), answer points to line 668 of  [npy_math_internal.h.src](https://github.com/numpy/numpy/blob/master/numpy/core/src/npymath/npy_math_internal.h.src)

Shouldn't it state
```
floordiv = (a / b>=0) ?  0.0@c@ : -0.0@c@;
```
instead of:
```
floordiv = (a / b>0) ?  0.0@c@ : -0.0@c@;
```

I've checked for Numpy 1.15.4  /  Python 3.6.7

**Comment by tlatorre-uchicago** [comment]
I looked into this a bit more and updated my answer on stack overflow. The greater than or equal to trick won't work since `-0.0 == 0.0`. The way that python's divmod handles this correctly is by using `atan2()` to distinguish between the two. In particular, the python implementation of `float_divmod` looks like:

```c
/* div is zero - get the same sign as the true quotient */
floordiv = copysign(0.0, vx / wx); /* zero w/ sign of vx/wx */
```

where `copysign()` is defined as:

```c
double
copysign(double x, double y)
{
    /* use atan2 to distinguish -0. from 0. */
    if (y > 0. || (y == 0. && atan2(y, -1.) > 0.)) {
        return fabs(x);
    } else {
        return -fabs(x);
    }
}
```
