### ISSUE TITLE
Memory Overflow when using numpy load to read .npy files in a loop

### ISSUE THREAD

**Issue by ghost** [numpy/numpy#12847]
This is reference to this particular closed [issue](https://github.com/numpy/numpy/issues/2640) and the related stack overflow [question](https://stackoverflow.com/questions/9244397/memory-overflow-when-using-numpy-load-in-a-loop) .

I am trying to load about 800K .npy files in a loop and appending them to a list. But either my machine restarts or freezes completely. By the way, I have 32 GB of RAM. 

The solution to the stack-overflow question is not working as there are no such attributes `f` or `close()` . `gc.collect()` isn't working as well. Deleting the variable which loads the .npy file or setting it to `None` isn't working as well.

I am using `numpy 1.15.4` installed by conda on Ubuntu 18.04.

Am I doing something wrong? Any suggestions/solutions are welcome.

**Comment by seberg** [comment]
@SRITANU could you try to create a code sample that reproduces this? maybe be creating some random npy's, or does keep loading the same one also work? How large are all the files you have in total?

As far as I can see, all of those issues only refer to `npz` files, which are quite a bit different from loading npy's.

**Comment by SRITANU** [comment]
@seberg The same code just with `.npy` files

    import numpy as np
   
    # generate a file for the demo
    X = np.random.randn(1000,1000)
    np.save('tmp.npy',X)
    
    # here comes the overflow:
    for i in range(1000000):
        print(i)
        data = np.load('tmp.npy')

Also I guess the `data.f` or `data.close()` is not available as a attribute anymore. However, I have to admit adding `gc.collect()` in the for loop works. But without it crashes the system completely.

But definitely when appending them to a list it even `gc.collect()` doesn't work. I guess the reason is beacuse the 800K .npy files each when loaded is of the `size` (32, 7, 7, 512) and of dtype `float32` which is about 3.2 MB each. Hence just overflowing pretty quick. I need to provide this entire array to a `VGG` network. Any suggestions for a workaround are welcome.

**Comment by yanxon** [comment]
Hi @SRITANU 

Do you find the solution to this problem? I'm facing the same issue.

Thanks

**Comment by nrasadi** [comment]
I had the same problem. But I came up with a pretty simple solution.    
Please refer to the link below. 
https://stackoverflow.com/a/65893798/14411354

**Note:** I think enabling/disabling mmap_mode is not really related to this problem. So in this case, feel free to do whatever you think is better for your particular situations.

**Comment by seberg** [comment]
Yeah, the original issue seems to be about a reference cycle and thousands of opened files, while the memory mapping mode is more relevant to few but large files.  I guess the original issue was largely a bug in the Python garbage collector, but there is likely still a use in cleaning this up, it may well be possible to just resolve the reference cycle (I have not looked into it, but with a weakref or otherwise) and avoid any garbage collection related issues.

Especially the simple `np.load` call that doesn't even load an `npz` should not have these issues.  I will reopen the issue.

**Comment by seberg** [comment]
I can't seem to reproduce the issue on Python 3.9 anymore, so I guess Python at some point made reference cycle resolution with objects defining `__del__` more robust.  If issues persist, please open a new comment!
(This doesn't mean that a PR to try to resolve the reference cyle manually wouldn't be accepted.)
