### ISSUE TITLE
Cannot import numpy with ArcGIS' Python 2.7

### ISSUE THREAD

**Issue by AndrewYinLi** [numpy/numpy#12938]
I'm having issues importing numpy using Python 2.7 supplied by ArcGIS. I've tried reinstalling numpy and ensuring it was the newest version, as specified by the error message, but with no luck.

### Reproducing code example:

```python
import numpy as np
```

### Error message:

```
Traceback (most recent call last):
  File "aggregate_tif.py", line 8, in <module>
    import numpy as np
  File "C:\Python27\ArcGIS10.4\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Python27\ArcGIS10.4\lib\site-packages\numpy\core\__init__.py", line 67, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['C:\\Python27\\ArcGIS10.4\\lib\\site-packages\\numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.
```

### Numpy/Python version information:

Using Python 2.7.10 (32-bit) and numpy-1.16.1

**Comment by mattip** [comment]
What `*.pyd` files are found at the location mentioned? There should be only one

**Comment by NWdrew81** [comment]
New-ish to Python and getting the same ImportError as AndrewYinLi with ArcGIS10.6. 
Running pip uninstall numpy and it uninstalls the v3.6 numpy, which I had installed before ArcGIS. 
Found 22 *.pyd files in C:\Python27\ArcGIS10.6\Lib\site-packages\numpy. Why is this an issue?

**Comment by mattip** [comment]
Sorry, I forgot about the test `*pyd` files we ship. Python can import `*pyd` c-extension modules or `*pyo`,`*pyc`, `*py` source files, in that order of precedence. Recently NumPy replaced a `multiarray*pyd` and `umath*pyd` file with a `multiarray*py` and `umath*py` file (respectively). Since the `*pyd` take precedence if present, a new installation of NumPy without removing the old will pick up the old `*pyd` files and emit the error you are getting.

By reinstalling NumPy, you probably got our recently released new version, which installed over the old one. Among your options are to either work out what was wrong with the original ArcGIS numpy installation, or remove all the old installation before installing a new NumPy

**Comment by AndrewYinLi** [comment]
Following mattip's suggestion above, I removed `"multiarray.pyd"` and `"umath.pyd"` after doing a search starting from the ArcGIS10.4 directory and now I can run `import numpy`! If this solution works for NWdrew81 as well, I recommend closing the issue.

**Comment by NWdrew81** [comment]
I tried deleting individual .pyd files but in the end I had to remove the entire Python27 directory and run a ArcGIS repair to reinstall Python. Works now, thanks.

**Comment by seberg** [comment]
If I understand correctly, there is nothing left to do for numpy here and the issue was solved for @AndrewYinLi and @NWdrew81, so closing. If there is still anything just comment/reopen.
