### ISSUE TITLE
Change __repr__ of np.bool_

### ISSUE THREAD

**Issue by sauln** [numpy/numpy#12950]
`np.bool_` causes lots of confusion because it does not compare with builtin `bool` intuitively. 

As mentioned in #5942, #7913 (maybe more as well), changing the `__repr__` from 
`[True, False]` 
to 
`[np.bool_(True), np.bool_(False)]` 
would prevent much of the confusion. 

### Reproducing code example:

```python
>>> import numpy as np
>>> t, f = np.bool_(True), np.bool_(False)
>>> t, f
(True, False)
>>> True, False
(True, False)
>>> t is True, f is False
(False, False)
```

They are identical. This can be very confusing if you don't know the type of  `t` and `f` ahead of time. 

### Numpy/Python version information:

This was tested with Python 3.7 and Numpy version '1.16.1'.

**Comment by sauln** [comment]
I would like to take this up as a first time numpy contributor. I assume the fix will be straight forward, but am unfamiliar with the testing and build processes.

**Comment by eric-wieser** [comment]
I'd probably favor `np.True_` over `np.bool_(True)`

**Comment by srkunze** [comment]
Why not using Python regular booleans?

I recently got a case where I needed to consume data from different sources through a common interface. It could either be a Python True/False or a Numpy True/False and handling this special case is quite strange.

**Comment by seberg** [comment]
@srkunze if we had a choice, I think that may be what we would do (or abolish the scalars completely effectively doing the same). But, we do not have a choice, at least not without gigantic headaches. The closest I can offer for "safely convert to bool" which is allowing a bit too much would be `operator.index(bool) == 0  # or 1`.
Btw. numpy itself has to resort to checking python bools and numpy bools specifically (mostly for the opposite case because numpy refuses to interpret booleans as integers in many cases).

In principle, I guess we could ask python to add something like `numbers.Bool`, but I am not sure that would be very convenient either. Theoretically, there could be a dunder method as well, but I doubt it will happen.

**Comment by srkunze** [comment]
:-(

**Comment by ganesh-k13** [comment]
@eric-wieser seems like it's still `True` and `False`, can I change it `np.True_` and `np.False_`? Although change of interface may not be perceived well, maybe add a flag of sorts to support both behaviors?

**Comment by eric-wieser** [comment]
If it's an easy change, I'd recommend:

* Making the change in a PR
* Emailing the mailing list to ask for confirmation that it's a good idea

We already have some inconsistency here - `np.void` is shown as `void(...)`, while `np.datetime64` is shown as `numpy.datetime64`. Using those as precedent, `True_`, `bool_(True)` or `numpy.True_` would be most consistent

**Comment by ganesh-k13** [comment]
Sure Eric, thanks for the info

**Comment by ganesh-k13** [comment]
Hi @eric-wieser , I have a few doubts on how to go about this. Here are my observations:
1. `np.bool_.__repr__` is a slot wrapper, so its implementation must be in C.
2. Closest to it's repr I found was `_void_scalar_repr` in scalartypes.c, but that calls a python function `numpy.core.arrayprint._void_scalar_repr`
3. Now `numpy.core.arrayprint._void_scalar_repr` is only for `void`.

I really cannot find where exactly is the repr being defined. Can you point me in the direction of where to look? Apologies if it's a basic question.

**Comment by seberg** [comment]
@ganesh-k13 to give you a hint of where this comes from:
https://github.com/numpy/numpy/blob/618456137a265d0dd84b85dd33a588bc69babc99/numpy/core/src/multiarray/scalartypes.c.src#L3940-L3949

Which is a code generator which uses `genint_type_str` and that in turn seems to use `.item()` (from python probably?!), which will convert to a plain Python object (in this case plain python `bool`).  This code is really a bit strange.  The fix is probably to add a specific `bool_str` function and use it for both `tp_repr` and `tp_str`  here instead.

**Comment by ganesh-k13** [comment]
Thanks a lot @seberg , can make changes to repr now. Yeah, `item` is a bit strange given they are doing `PyObject_GetAttrString` on item. Will read a bit more and test the changes before PR.

**Comment by seberg** [comment]
This is changed in main, let the chaos ensue!
