### ISSUE TITLE
numpy.delete None

### ISSUE THREAD

**Issue by ax3l** [numpy/numpy#12952]
It would be great if `numpy.delete` supported `None` as `obj`.
In that case, the array is returned as is.

### Code example:

```python
import numpy as np

x = [1, 2, 3, ]
np.delete(x, None)
# [1, 2, 3]
```

**Comment by seberg** [comment]
@ax3l can you give a use case or stronger argument for it? Because my first gut feeling it that it is not a good idea, because it breaks the similarity to indexing where `None is np.newaxis` and thus has a very specific meaning (which is not sensible for delete). So allowing `None` to mean that the similarity is a bit broken.

**Comment by ax3l** [comment]
Thanks for the feedback!
The use case I had today was a temporary variable that removes an element of an array if a value is present in another:
```py
import numpy as np

keys = ["a", "b", "c"]
vals = [1, 2, 3]
bad = "b"

i = keys.index(bad) if bad in keys else None  # urgh, iterates twice
np.delete(vals, i)
```

**Comment by seberg** [comment]
Well, I hope that you vals is actually a numpy array, because otherwise you should use `del vals[i]`.

I guess it is hard to judge with that code, since if it is a small amount of code, I would definitely go with the `try/except`:
```
try:
    i = keys.kindex(bad)
    del vals[i]
except:
   pass
```
or similarly for `np.delete` (although in that case `index` does not exist, and `np.delete` creates a copy, so you may or may not want to copy in the other branch). Actually, an empty slice (or list/indexing array, although that is slower probably) should already be neutral of course (such as `slice(0, 0)`). Although, I admit it might be a bit non-obvious even to readers if you are otherwise deleting elements.

**Comment by seberg** [comment]
Actually, lists also have the `remove` attribute, which already may do all you want in one go...

**Comment by eric-wieser** [comment]
You're looking for `np.delete(arr, np.intp([]))` - passing an empty list of indices to delete
