### ISSUE TITLE
numpy import error in Eclipse/PyDev on win 7 but it works in Anaconda prompt. 

### ISSUE THREAD

**Issue by usact** [numpy/numpy#12972]
I posted this in Anaconda. But, later, feel that I should post it here because it is about numpy and it is suggested by the warning messages when I tried to uninstall numpy.

I try to run python 3.7 script in Eclipse/pydev ion win 7.

Wheh I imported numpy, i got error:

```
    import numpy.core.numeric as _nx
    File "C:\My_Program\Anaconda3p7\Lib\site-packages\numpy\core\__init__.py", line 24, in <module>
raise ImportError(msg)
        ImportError: 
    Importing the multiarray numpy extension module failed.  Most likely you are trying to import a failed build of numpy.
     If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control). Otherwise reinstall numpy.
```

I installed Anaconda

```
 active environment : base
active env location : C:\My_Program\Anaconda3p7
    shell level : 1
    user config file : C:\Users\aName\.condarc
 ulated config files : C:\Users\aName\.condarc
    conda version : 4.6.3
  conda-build version : 3.17.8
  python version : 3.6.8.final.0
  base environment : C:\My_Program\Anaconda3p7  (writable)
   channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                  https://conda.anaconda.org/anaconda-fusion/noarch
                  https://repo.anaconda.com/pkgs/main/win-64
                  https://repo.anaconda.com/pkgs/main/noarch
                  https://repo.anaconda.com/pkgs/free/win-64
                  https://repo.anaconda.com/pkgs/free/noarch
                  https://repo.anaconda.com/pkgs/r/win-64
                  https://repo.anaconda.com/pkgs/r/noarch
                  https://repo.anaconda.com/pkgs/msys2/win-64
                  https://repo.anaconda.com/pkgs/msys2/noarch
  package cache : C:\ProgramData\Anaconda3p7\pkgs
                  C:\Users\aName\.conda\pkgs
                  C:\Users\aName\AppData\Local\conda\conda\pkgs
  envs directories : C:\ProgramData\Anaconda3p7\envs
                  C:\Users\aName\.conda\envs
                  C:\Users\aName\AppData\Local\conda\conda\envs
       platform : win-64
     user-agent : conda/4.6.3 requests/2.21.0 CPython/3.6.8 Windows/7 Windows/6.1.7601
  administrator : False
     netrc file : None
   offline mode : False
```
I have installed numpy 1.12.0 in Anaconda prompt.

If I imported numpy in Anaconda prompt, it works well.

But, if I import numpy in Eclipse/pydev, I got the above error.

If I import numpy in command-line but not in Anaconda prompt, I got error:

```
  >>> import numpy
  Traceback (most recent call last):
  File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
  from . import multiarray
  ImportError: DLL load failed: The specified module could not be found.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\__init__.py", line 142, in <module>
  from . import add_newdocs
  File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
   from numpy.lib import add_newdoc
  File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
  from .type_check import *
  File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
  import numpy.core.numeric as _nx
  File "C:\My_Program\Anaconda3p7\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
  raise ImportError(msg)
 
 ImportError:
   Importing the multiarray numpy extension module failed.  Most likely you are trying to import a failed build of numpy.
   If you're working with a numpy git repo, try `git clean -xdf` (removes all files not under version control).  Otherwise reinstall numpy.
```
I have tried most solutions online, but none of them work.

Could anyone help about this ?

thanks

**Comment by mattip** [comment]
Activating an anaconda environment changes the PATH environment variable so that numpy (and other packages like scipy) can find helper dlls. You should run your IDE **after** changing the path appropriately.

**Comment by rgommers** [comment]
The path `C:\My_Program\Anaconda3p7\lib\site-packages\numpy\lib\__init__.py` suggests that you installed numpy with pip. Is that correct?

Better to install with conda instead:
 ```
pip uninstall numpy
conda install numpy
```
If that still doesn't work from within Eclipse, please let us know

**Comment by jordannickerson** [comment]
> Activating an anaconda environment changes the PATH environment variable so that numpy (and other packages like scipy) can find helper dlls. You should run your IDE **after** changing the path appropriately.

I'm suffering a similar problem when trying to use IDLE. I can import numpy from the anaconda prompt, but not from IDLE. Can you clarify how to change the path appropriately?

**Comment by srt19170** [comment]
FYI for anyone who may have this same problem in the future:

The problem is caused because the PATH environment variable is not set correctly.  It does not contain all of the proper Anaconda directories.  Even if you set up your Python interpreter in Eclipse to point to the correct Anaconda environment and check the box to "Load conda envs before run?" the PATH will not be correctly set.

One solution is to use the Environment tab on the interpreter configuration to explicitly set the PATH to the correct value:
![image](https://user-images.githubusercontent.com/659972/81841364-5372af00-9518-11ea-9873-9b03b4dae631.png)
You can get the proper PATH value by opening up an Anaconda command window, activating the Anaconda environment you want to use, and then use 'set' to get the PATH value and copy it into Eclipse.

**Comment by garryyan2** [comment]
Thank you, srt19170, your answer was just posted 9 days ago. It solves my problem. I thought this kind of issue should have been solved long time ago. I am totally new here. Thank you all.

**Comment by rossbar** [comment]
@srt19170 , @garryyan2 - a section on PyDev has recently been added to [the troubleshooting docs](https://numpy.org/devdocs/user/troubleshooting-importerror.html). Would you mind taking a look at [the added section](https://numpy.org/devdocs/user/troubleshooting-importerror.html#using-eclipse-pydev-with-anaconda-conda-python-or-environments) and commenting on whether it would've helped you solve the issue? If not, any suggestions on how the doc could be improved would be much appreciated.

**Comment by garryyan2** [comment]
@rossbar, [the added section](https://numpy.org/devdocs/user/troubleshooting-importerror.html#using-eclipse-pydev-with-anaconda-conda-python-or-environments) doesn't help. What srt19170 suggested is a work-around. There seems to be a bug to pass the environment variable PATH to PyDev/Eclipse.

**Comment by srt19170** [comment]
@rossbar -- the reference in that section to check environment variables would be helpful.  I think it would be improved if (1) you document what directories PATH and PYTHONPATH should contain, and (2) mention that you might have to look up in your IDE documentation how to set an environment variable.  As @garryyan2 suggests, this problem is a bug in PyDev/Eclipse/Anaconda rather than a problem with numpy.

**Comment by rossbar** [comment]
Thanks, all, for the feedback! 

> I think it would be improved if (1) you document what directories PATH and PYTHONPATH should contain

#16306 attempts to improve code that users can run to try to better introspect their environment. Unfortunately, it's not possible to say what the PATH or PYTHONPATH *should* contain because this depends on each individual setup. Perhaps there's some way to improve the text while still keeping it general.

> (2) mention that you might have to look up in your IDE documentation how to set an environment variable.

This is a great point, and generally we just try to refer to the specific IDE documentation.

Thanks again @garryyan2 & @srt19170 for providing feedback on the troubleshooting doc.
