### ISSUE TITLE
Bug: tofile() function write data twice when the data has a size of (1024, 4096)

### ISSUE THREAD

**Issue by jiecaoyu** [numpy/numpy#13047]
When using the ```tofile()``` function, if the file is opened with ```'a+b'``` option (append) and the data has a size of (1024, 4096), then the data will be write twice.

### Reproducing code example:

```python
import numpy
import subprocess


# test data size of [1024, 4096] which reproduces the bug
subprocess.call('rm tmp', shell=True)
print('Wrong case:')

fp = open('tmp', 'a+b')
x = numpy.random.normal(size=(1024, 4096)).astype(numpy.float32)
print('Shape of x:', x.shape)
print('Elements in x:', x.size)
x.tofile(fp)
fp.close()

y = numpy.fromfile('tmp', dtype=numpy.float32)
print('Elements in x when read from the file:', y.shape)


# test data size of [1023, 4096] which gives correct result
subprocess.call('rm tmp', shell=True)
print('\nCorrect case:')

fp = open('tmp', 'a+b')
x = numpy.random.normal(size=(1023, 4096)).astype(numpy.float32)
print('Shape of x:', x.shape)
print('Elements in x:', x.size)
x.tofile(fp)
fp.close()

y = numpy.fromfile('tmp', dtype=numpy.float32)
print('Elements in x when read from the file:', y.shape)
```

### Numpy/Python version information:

('1.11.0', '2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]')

I tested on '1.12.0' and '1.15.0' and ```tofile()``` is working correctly.

**Comment by seberg** [comment]
Hmmm, thanks for the report. But I think we can probably just close it if it is working correctly on versions 1.12+? Numpy 1.11 is very old. We normally do not do bugfixes/releases for older versions since a version upgrade is encouraged (numpy 1.16 is/will be an exception due to python 2.7 support).

My guess is that this was fixed in gh-8339, so I will close this. If you feel there is something to discuss please do.
