### ISSUE TITLE
np.nan astype np.int32 gives -2147483648

### ISSUE THREAD

**Issue by kkonevets** [numpy/numpy#13101]
Converting nan to int32 succeeds

### Reproducing code example:

```python
import numpy as np
np.array([np.nan]).astype(np.int32) 
```
outputs 
array([-2147483648], dtype=int32)

### Numpy/Python version information:
np.__version__ == '1.16.1'

**Comment by eric-wieser** [comment]
Emitting a `RuntimeWarning` would probably be a good idea here

**Comment by kkonevets** [comment]
> Emitting a `RuntimeWarning` would probably be a good idea here

My suggestion is to convert np.nan to np.nan as with float32
```
np.array([np.nan]).astype(np.float32) 
```

**Comment by eric-wieser** [comment]
Integers can't store `nan` though? That's like saying `np.array(2).astype(bool)` should give 2.

**Comment by mxt3** [comment]
I've just ran into this. So `nan` is converted tot the smallest 32bit signed integer. I don't know if this is deliberate, but this behavior coincidentally suits my needs.

However, it does not seem to be a very deliberate design, because ` np.int32(np.nan)` throws a `ValueError`.

It feel it should be documented, at the least, under the form of a warning or deliberate design.

**Comment by seberg** [comment]
@mxt3 note that NumPy currently returns whatever `(int32)NaN` returns in C, and that is unfortunately "undefined", I think.  IIRC, there *are* machines where you may get a different result unfortunately, e.g. `0` (there should be an issue about that open somewhere).

**Comment by seberg** [comment]
This will now give a RuntimeWarning on `main` (will be a while until a release with it).  There is another issue about this open at gh-14412, which I will keep open as a point for discussing whether more than a warning (settable using `np.errstate(invalid="raise"/"ignore")` would be a nice further step.
