### ISSUE TITLE
numpy power command has errors with integer input

### ISSUE THREAD

**Issue by roelverh** [numpy/numpy#13102]
when raising an integer to a power and the answer gets large, enourmous errors result.

```python
import numpy as np
print(np.power(100,8)) #integer
print(np.power(100.0,8)) #float
```

### Error message:
this results in output:

1874919424
1e+16

**Comment by roelverh** [comment]
Numpy version 1.15.4

**Comment by subhrm** [comment]
The integer data type uses 32 bits , so it can effectively store values in range -2^31 to +2^31. Trying to put a higher value into the int32 field causes overflow. In this case this result is (100^8)%(2^31). See : [Wolfram Alpha Calculator](http://m.wolframalpha.com/input/?i=%28100%5E8%29+mod+%282%5E31%29)

**Comment by Kai-Striega** [comment]
To expand @subhrm's answer a little, the error you encountered occurs due to an [Integer Overflow](https://en.wikipedia.org/wiki/Integer_overflow). This does not occur for python integers, but, may occur in Numpy due to how they treat [integers](https://stackoverflow.com/a/38156630). 

Python's int size is flexible, meaning they may grow to accommodate any sized int. OTOH, NumPy's ints are of a fixed size to match the size of a C `long` (usually 32 or 64 bits) but this is system/compiler dependent. Comparing `np.int_` to `np.int64`/`np.int32` shows which your system uses.

    >>> import platform
    >>> platform.architecture()
    ('64bit', 'ELF')
    >>> np.int_ == np.int64
    True
    >>> np.int_ == np.int32
    False

To check the max/min values storeable by your dtype use [`np.iinfo`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.iinfo.html).

    >>> np.iinfo(np.int)  # The default value for your system.
    iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)
    >>> np.iinfo(np.int32)
    iinfo(min=-2147483648, max=2147483647, dtype=int32)
    >>> np.iinfo(np.int64)
    iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

If you're looking to use `np.int64` rather than `np.int32` you may set the `dtype` argument.

    >>> np.power(100, 8, dtype=np.int32)
    1874919424  # (100 ** 8) % (2 ** 31)
    >>> np.power(100, 8, dtype=np.int64)
    10000000000000000  # Correct answer.

Or, if you need to use *much* larger values, [`np.float_power`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.float_power.html#numpy.float_power) casts integer values to floats with a much larger, but inexact, range.

    >>> np.float_power(100, 8)
    1e+16
    >>> np.power(100, 100)
    0  # Incorrect answer for very large values
    >>> np.float_power(100, 100)
    1e+200

**Comment by mattip** [comment]
@Kai-Striega great answer. Since this comes up so often, perhaps you could add it to the [`quickstart`](http://www.numpy.org/devdocs/user/quickstart.html) or [`data types`](http://www.numpy.org/devdocs/user/basics.types.html) pages?

**Comment by Kai-Striega** [comment]
@mattip I'd be happy to. I'll be busy over the next few days but I'll have
time next week.

**Comment by roelverh** [comment]
Thanks for all your insightful answers! The fact remains though that very wrong answers can result from accidentally providing integer input. 
It would be better to get an error message on integer overflow rather than the wrong answer.

**Comment by Kai-Striega** [comment]
@mattip does  NumPy usually add warnings or errors for integer overflow? This could be useful in avoiding similar issues later.

**Comment by mattip** [comment]
NumPy does not warn on integer overflow. There are requests for this enhancement. However detecting overflow in the general case would add checks to the ufunc internal loops, and might affect performance. It certainly would be a breaking change with current behaviour and so would need to have some kind of opt-in mechanism

**Comment by Kai-Striega** [comment]
Okay. That's what I thought. My personal preference would be to avoid
having further in lieu of performance.

**Comment by Kai-Striega** [comment]
@mattip can we close this issue?
