### ISSUE TITLE
Slicing with negative step does not output 0th index element

### ISSUE THREAD

**Issue by mseth10** [numpy/numpy#13123]
When slicing with negative step, there is no way to include the 0-th index element.
end = 0 returns elements till index 1. end = -1 instead of returning elements till index 0 returns an empty array.

### Reproducing code example:

```python
>>> import numpy as np
>>> data = np.random.uniform(size=(4,))
>>> data
array([0.6677262 , 0.29855998, 0.32659663, 0.15015646])
>>> data[2:0:-1]
array([0.32659663, 0.29855998])
>>> data[2:-1:-1]
array([], dtype=float64)
```

Expected output:
```python
>>> data[2:-1:-1]
array([0.32659663, 0.29855998, 0.6677262])
```

### Numpy/Python version information:

1.14.3 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by clbarnes** [comment]
Your examples are consistent with python's slicing of lists. Breaking with that would be a bad idea for numpy.

Your second example is the correct behaviour - your expected output would be wrong. You start from element 2 (3rd, because of 0-base indexing) and go to element -1 (4th, because of negative indexing). But you want a negative step. There's no way to get from the 3rd to the 4th element by going backwards! So that rightfully returns an empty array.

Your first example is also showing the correct behaviour, although for slightly less transparent reasons. If you slice up to element 2 with e.g. `[0, 1, 2, 3][:3]`, you do not include element 3: you include the *first 3 elements*. To get element 3, you need to slice up to element 4 (e.g. `my_list[:len(my_list)]`) Therefore, if you slice *down* to element 0, you should not include element 0. To include element 0, slice down to `None`, or just omit that bound: `my_list[2::-1]`.

**Comment by mseth10** [comment]
> To include element 0, slice down to `None`, or just omit that bound: `my_list[2::-1]`.

Thanks for your response. I understand how numpy supports this edge case. Closing the issue.

**Comment by anirudh2290** [comment]
Thanks @clbarnes ! That was very quick and helpful.
