### ISSUE TITLE
ENH: Add keyword option to histogram in order to return bin centers

### ISSUE THREAD

**Issue by cagostino** [numpy/numpy#13194]
Not sure if this is already implemented in some other function but I often find myself needing to use the outputs of histogram and I often see quick little fixes on Github, stackexchange, etc. for getting the bincenters from the np.histogram/plt.hist outputs.
I think it would be useful to have an option to include the bincenters as an output so that one can easily utilize that info and plot with plt.bar

### Code snippet for doing this

```python
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(13)
arr_data = np.random.normal(0,1, 100)
yhist, binedges = np.histogram(arr_data)
bincenters = np.mean(np.vstack([binedges[0:-1],binedges[1:]]), axis=0)
plt.bar(bincenters, yhist)

```
with this as the output
![image](https://user-images.githubusercontent.com/5403925/55012173-61383e80-4fbd-11e9-87eb-890243d4794d.png)

If this seems like a good idea, I would be happy to begin a pull request.

**Comment by eric-wieser** [comment]
That plot looks pretty bad to me - you need to set the bin widths too.

Can't we just leave the user to do this? `(b[1:] - b[:-1])/2` is not hard to write, and it sounds like the real problem here is using `.bar` instead of `.hist`

**Comment by cagostino** [comment]
Since it is not hard to write, wouldn't it be fairly simple to then just include it as another option? Makes it easier for everyone (especially those who may not find it so straightforward) in the end to do that.
The point of the post was not the plot, just one example for how it can be useful.

**Comment by rabernat** [comment]
I agree that this would be useful in some cases.

However,  `(b[1:] + b[:-1])/2` (arithmetic mean) is not always a good approximation of the bin centers. What about logarithmically spaced bins? In that case, a better choice would be `np.sqrt(bins[1:] * bins[:-1])` (geometric mean).

**Comment by jtlz2** [comment]
It does indeed depend on the distribution of values within a bin - a median is another choice, but the troublesome point is that a choice always has to be made...

**Comment by eric-wieser** [comment]
> The point of the post was not the plot, just one example for how it can be useful.

Since it was a bad example, can you come up with another example to replace it?

**Comment by Mattyboi123** [comment]
having direct keyword access to the bin centers would be especially useful (more so that the edges?) when trying to combine the outputs of multiple calls to np.histogram and plot the result as a new histogram that retains the original bin widths of the originals but shows the new count. If there is already a straightforward way to do this that I have missed (after not a little searching) I apologise.

**Comment by eric-wieser** [comment]
@Mattyboi123, Can you give a motivating python example, showing how you'd like to be able to write it, and how you write it today?

**Comment by rossbar** [comment]
I'm -1 on this proposed feature. @rabernat identified the fundamental problem - the concept of "bin centers" doesn't generalize well. Non-linear binning schemes are quite common for many applications.

**Comment by cagostino** [comment]
why not also include the option to choose how the bin centering is done then?

**Comment by seberg** [comment]
I think it is more of a general issue that if you have a non-linear bins, you must retain the information about each bins width. Of course you could return `centers, widths`.

The question is more whether this has a super nice generic solution with a good API, or whether you want to rather add a tiny function into the `Examples` or `Notes` to encourage writing a minimal helper.

That is why Eric asked for motivating examples, this is purely about having a nice API and making sure that the API is clean and does not provide strings for users to hang themselves with. Any addition to the API also makes it more complicated, so there is a trade-off and examples of how it makes your code much cleaner are the best way to convince us.

**Comment by rossbar** [comment]
I don't see how you could possibly make this general. It would arguably be straightforward to handle a subset of cases (arithmetic mean, geometric mean, logarthmic binning, etc), but there are many powerful binning schemes that can result in irregular binning with no a-priori definition of where the center of the bin lies.

I certainly understand the convenience argument, but in the most common case computing the bin centers from the edges is a one-liner, and doing so explicitly is a plus from the perspective of readibility/grokability:

```python
h, bin_edges = np.histogram(data, bins=<binning>)
bin_centers = bin_edges[:-1] + np.diff(bin_edges)/2
```
is easier to understand and only slightly less convenient to write than
```python
h, bin_edges, bin_centers = np.histogram(data, bins=<binning>, bin_centers="linear")
```

As @seberg mentioned, if there is a generic solution with a good API that doesn't obfuscate how bin centers are computed then I'd be +1.

**Comment by eric-wieser** [comment]
From the descriptions so far, my hunch is that this is an "XY problem" - which is why I don't think we can move further without the motivating application.

**Comment by jtlz2** [comment]
Could a lambda be supplied to specify the binning-centre scheme? That would generalize well if so. It would allow the caller to neatly swap in different schemes.

**Comment by eric-wieser** [comment]
I don't understand why you'd want to write:
```
counts, centers = histogram(x, center_func=my_center_func)
```
instead of
```
counts, edges = histogram(x)
centers = my_center_func(edges)
```

**Comment by michaelaye** [comment]
I'd argue that the fact that users are forced to look up the `(b[1:] + b[:-1])/2` solution for the often used linear case is also an API issue. I would make the API simply return this solution in the linear case (when requested with a `center=True` switch), but throw an error for center requests for non-linear binnings.

This is so common a problem that there are even plotting routines written around this issue in the meantime (checking for arr.shape+1 and then assuming edges instead of centers).

**Comment by cagostino** [comment]
much agreed^

one wants to write:

`
counts, centers = histogram(x, return_center=True)
`
not 

`
counts, edges = histogram(x)
centers = my_center_func(edges)
`
I understand there are alternative centering and binning schemes but what fraction of them are genuinely not the simplest  
`
(b[1:] + b[:-1])/2
`
 solution? My guess is 10% at maximum. Most folks don't use more complicated schemes, and those who do use the more complicated ones are more likely to be the ones capable of developing their own centering functions

**Comment by eric-wieser** [comment]
> Most folks don't use more complicated schemes,

Its been two years, and no one replied to my question of why you need the bin centers in the first place. Even if 90% of people who want bin centering want a linear midpoint, it might be as low as 1% of people that want bin centering at all.

A minority interest still not an argument against it, but we shouldn't add a feature until we understand why people want it.

So I ask again; for what problem is "find the linear centers of the bins" a solution?

**Comment by michaelaye** [comment]
Every time I fit a function over a histogram I need the bin entries and their center positions as input for the fitting functions. I’d be surprised if only 1% of histogram creators do fits over the histograms?

**Comment by rkern** [comment]
When I fit a distribution function over histogrammed data, I want to evaluate the number of expected counts for each bin for the given distribution function. The best ways to do that use the bin edges, not the centers. When the bins are really small compared to the curvature of the distribution function, evaluating the distribution function at the bin centers sometimes works okay, but it's usually easy enough to do the rigorous thing.

**Comment by michaelaye** [comment]
> When I fit a distribution function over histogrammed data, I want to evaluate the number of expected counts for each bin for the given distribution function. The best ways to do that use the bin edges, not the centers. When the bins are really small compared to the curvature of the distribution function, evaluating the distribution function at the bin centers sometimes works okay, but it's usually easy enough to do the rigorous thing.

I must be missing something: all fit functions I am aware of in the Python ecosystem demand same length of the array for the independent and dependent variable. So, to be rigorous, I always assumed the best way to do this is to provide the independent variable at the bin centers, so that the can be "assigned" to the bin count of the respective bin. To leave out the last edge and simply use the remaining left edges and fit those to the bin counts I always considered to be "dirty" irrespective of the bin width, as that isn't really the correct relationship, and was thinking of the bin centers as the very best alternative to this process. 
I'm curious what way you indeed would fit the results of np.histogram rigorously, using all edges?
Sorry for being ignorant of what I must be missing...

**Comment by rkern** [comment]
I don't use "curve-fitting" routines for this purpose (e.g. `curve_fit()`, etc.) but rather express my problem as maximizing the likelihood of seeing those counts directly. So I form the negative log-likelihood function and use `minimize()` and friends. Inside of that negative log-likelihood, I'm integrating the distribution function (given the current parameter vector) over the bins to get the probability of a single count happening in each bin, then using a multinomial (Poisson also works, with slightly different assumptions) to evaluate the (negative log-)probability of seeing that configuration of counts for all of the bins. Besides avoiding the bin-center issue, it nicely handles the proper weighting of rare bins versus common bins as well as non-uniform bins (especially nice for dealing with power-law-ish distributions where you want to telescope out the bin widths).

So for example, fitting a normal distribution to `counts, edges`:

```python
from scipy import optimize, special, stats

def loss(params, counts, edges):
    # Use a log/exp transformation on the scale parameter to allow for unbounded optimization
    dist = stats.norm(loc=params[0], scale=np.exp(params[1]))
    cdf_edges = dist.cdf(edges)
    p = np.diff(cdf_edges)
    # Simple form of the multinomial.logpmf() with extraneous constant factors removed.
    nllh = -special.xlogy(counts, p).sum()
    return nllh

res = optimize.minimize(loss, [0.0, 0.0], args=(counts, edges))
fit_loc = res.x[0]
fit_scale = np.exp(res.x[1])
```

I found it particularly helpful for fitting distributions that decay down from 0, like certain areas of the Weibull distribution parameter space. Those first few bins are where a lot of the reliable data are, but that's also where the curvature is. I usually fit to histograms primarily for already-binned data (e.g. rounded arrival times), but I think there are some robustness advantages over just doing an MLE fit to the raw data.

This procedure is not exactly well-popularized (outside of particle physics, maybe), but you can see it recommended on [slide 17 of this ROOT tutorial](https://twiki.cern.ch/twiki/pub/Main/ROOTRioTutorial/ROOT_Rio2015_Fitting.pdf) for instance. I'm not the only person who does this! There are dozens of us!

**Comment by jtlz2** [comment]
> I'm not the only person who does this! There are dozens of us!

Exactly - and while I have also extensively used (fully) Bayesian approaches to histogram-fitting, "dozens" must be << 1 per cent of the population using numpy in that way.... I was surprised that you had a use case requiring one to vary the bin positions. Most people probably don't have enough experience to fully understand your algorithm (I mean that in the nicest possible way) :) [I'd be interested to see your maths if you have a paper on it.]

Speaking of Bayesian, we all seem to be very prior-dependent on the numbers of users (if that is even a criterion for inclusion, I don't know) - is there any way to get hard facts on this?

> Most folks don't use more complicated schemes, and those who do use the more complicated ones are more likely to be the ones capable of developing their own centering functions

> I must be missing something: all fit functions I am aware of in the Python ecosystem demand same length of the array for the independent and dependent variable.

> Every time I fit a function over a histogram I need the bin entries and their center positions as input for the fitting functions. I’d be surprised if only 1% of histogram creators do fits over the histograms?

These are precisely the points. Adding a kwarg for this would serve a huge majority (of that I am sure).

**Comment by jtlz2** [comment]
According to https://www.nature.com/articles/s41592-019-0686-2, scipy itself has "millions of downloads per year" which is a starting point.

**Comment by rkern** [comment]
There's nothing Bayesian about this procedure. This is pure maximum likelihood.

I joke about me being an oddball, but this _is_ fairly common in the particle physics literature due to intrinsic binning during measurement. Besides the ROOT tutorial I already linked, [here's an old one from the '80s](https://ui.adsabs.harvard.edu/abs/1984NIMPR.221..437B/abstract) and [here's a more recent overview ("3.13 Likelihood function for binned samples")](https://arxiv.org/abs/1609.04150). I learned about not passing bin centers to a least-squares routine in my sophomore physics lab. Unfortunately, I don't recall the title of the textbook we used, but anyways those were the days when they came with a floppy disk with the BASIC code examples glued inside the back cover, so I don't think it's in print anymore.

Adding a keyword argument to cause the function to return something different is mostly a non-starter. It's bad API design. We do it now and again in numpy/scipy, but we know we shouldn't. And then we try to only do it for things that you can't derive easily from the outputs already given.

There really is nothing special about the bin centers. Yes, a number of people make ad hoc procedures that use them, but ultimately they came up with those procedures themselves and thus can derive the centers from the edges themselves, too. Personally, I don't think it's worth complicating the interface to implement a one-liner.

**Comment by cagostino** [comment]
> So I ask again; for what problem is "find the linear centers of the bins" a solution?

As @michaelaye said, using the bin centers for fitting. As I said in my initial post, I like to have them similarly for fitting or for making plots with styles not accommodated by the default pyplot.hist styles. 

As @jtlz2  has pointed out, this would indeed serve a huge majority. Most people when starting out with programming do not think of terms of bin edges. The motivation for this post initially was when I was TAing for a course of undergraduate astronomy majors and they had to repeatedly do this bin centering on their own and were confused why the output was not the thing they wanted to use. It is not exactly intuitive to new users and having a kwarg is an easy fix that doesn't mess with any prior functionality. If you are worried about folks wanting centering functions that are not simply the arithmetic mean then also make that a default keyword argument so people can set it on their own.

**Comment by cagostino** [comment]
Doesn't necessarily have to return something different, could just return something extra.

**Comment by cagostino** [comment]
it wouldn't change the output unless specifically asked for it so wouldn't affect any existing code bases that do not request it.

**Comment by rkern** [comment]
As was demonstrated in the initial example, just having the bin centers is not enough to do a lot of the things you want. You need at least the bin width (or widths) too, even for the simple task of making a bar plot that represents the histogram faithfully, much less data fitting. That's why I say there is nothing special about the bin centers. There isn't much you can actually do with them in a principled manner. The edges contain all of the information about the bins, and you can derive everything you need from them, either ad hoc or principled.

> it wouldn't change the output unless specifically asked for it so wouldn't affect any existing code bases that do not request it.

I know. It's still bad design that we try to avoid. Not least, it makes documenting the function difficult with different conditionals. That complication is a cost we all pay even if we don't use that argument in our code.

I agree that there is a gap between doing `np.histogram()` and getting matplotlib to plot that histogram without recalculating the histogram via `plt.hist()`. But I think that's a gap in matplotlib. There's a hint how to do this buried in the [`plt.hist()`](https://matplotlib.org/3.5.1/api/_as_gen/matplotlib.pyplot.hist.html) docstring abusing the `weights=` argument, but it would be better to have something where one could pass in `counts` and `edges` more plainly. _That_ could well be done as a keyword argument, like `plt.hist(counts, bins=edges, precomputed=True)`.

**Comment by cagostino** [comment]
> There isn't much you can actually do with them in a principled manner. 
This is a value statement you're making for others. Some people want to use them and the fact that there is an obfuscated extra step--which may seem obvious to you or others with experience--makes it more difficult for new users.

> It's still bad design that we try to avoid.
"Bad" here is sort of arbitrary: who is it bad to? Is it not the point of open source software to increase utility for its users to simplify things for them?

**Comment by cagostino** [comment]
> A strong argument for me would be if the addition made best-practices easier, but that seems not the case.

Again, something you are deciding for others and you are actively ignoring me and another user who have said that having this would make things easier.

> So someone has to make a call on whether this convenience adds enough value to be included – right now that tends towards a "no", also because it seems like it may be misused easily.

@michaelaye and I have both presented cases for how we would find it useful. What exactly does "misused" mean here? Again a value judgment. As API designers, you cannot simply tell users they are "misusing" the product because they do things with the output that you may not agree with. That is ridiculous. It is up to them to decide how they want to use something. Besides, people will have no trouble "misusing" the current implementation and I would argue that more do so with the way it currently is by chopping off the first or last edge and just using the remaining ones for quick and dirty plots or fitting. 

> But NumPy can't add things opportunistically hoping it will be useful enough to be worthwhile.

It is not a matter of hoping, folks _will_ use this. A classmate of mine told me today that he literally searched this same problem yesterday and copied the code from my initial post. We are just keeping this more annoying by not implementing it. The way you are talking about this makes it seem like it has the potential to break things and will be difficult to implement but it's such a simple solution that would provide a nice convenient feature to many. Why are you so resistant to that? 

> Well, I described how it complicates the documentation of how the function works, and that applies to everyone.

Yes it adds another couple of lines to the documentation but will assuredly save people an extra google search of their own and could reduce extra errors that may be introduced when people have to do this on their own every single time. More things do not necessarily mean that it is more complicated if it is well explained. Those who are going through the documentation will pass over it unless they need it. They're not going to be tripped up by an extra keyword.

> Especially, when it alternatives like the suggested change to matplotlib have not been clearly rejected as a valid replacement.

This is not purely a plotting issue so switching it to being a keyword argument in plt.hist obfuscates the problem further and also results in the _plotting_ of the histogram which if you are computing many of is quite annoying.

**Comment by rkern** [comment]
> Again, something you are deciding for others and you are actively ignoring me and another user who have said that having this would make things easier.

We have not ignored you. We are engaging you extensively in our free time. We have not agreed to your proposed action, but not immediately consenting to your full proposal is not the same as ignoring you or your needs. We have suggested a few alternative actions that we think would address your needs while being consistent with our own needs as maintainers.

Concretely:

1. The examples in the `np.histogram()` should show how to calculate the bin centers (and I would suggest also bin widths) from the edges. This action is a no-brainer; essentially no cost and all up-side. I don't think we'll get much disagreement from the numpy team.
2. Add a function that converts edges to bin centers. This is more costly. At this stage of numpy development, we actively avoid adding more functions to the already-crowded namespace, especially for one-liner recipes that can be documented elsewhere. I don't think it's likely that we'll go this route given the availability of the former, but there is likely more receptiveness to this approach than modifying the returns of `np.histogram()`.
3. Ask matplotlib to consider letting `plt.hist()` take `counts, edges` more directly. This does not address all of the needs you have mentioned, but it does address one that [had been brought up](https://github.com/numpy/numpy/issues/13194#issuecomment-586211024_). It was not intended to be the _only_ action or as how one would _compute_ bin centers. I can't evaluate the likelihood of matplotlib taking this up.

> What exactly does "misused" mean here?

Using a histogram-fitting method that is demonstrably worse statistically and numerically, and is actually more _complicated_ to implement, to boot. For those who are interested, I've worked up a [notebook comparing the two main approaches](https://gist.github.com/rkern/583977b70fe3472677a2e53d60e12600) to fitting curves to histograms. If this thread produces nothing else than _one_ more person fitting histograms with the MLE approach rather than using curve fitting routines, I will have considered it all worthwhile.

> As API designers, you cannot simply tell users they are "misusing" the product because they do things with the output that you may not agree with.

Of course we can, and do so frequently. We have whole `Notes` and `.. warning::` sections for just that purpose.

But that's also no argument that we _must_ make any particular API choice because some user requests it. We are not our user's employees. They don't pay us enough to do what any one of them tells us. For that matter, my actual paying customers pay me _too much_ to just do what they tell me to do (they pay to tell them what _they should do_, not for my ability to transcribe feature requests into code).

> The way you are talking about this makes it seem like it has the potential to break things and will be difficult to implement but it's such a simple solution that would provide a nice convenient feature to many. Why are you so resistant to that?

We have given several reasons. I can try to collate them in one place if you do not want to reread the thread. Please be aware that we have made _exactly_ this kind of design decision before. We speak from _direct experience_ that we do not want to do it again if we can do something else that addresses the needs most of the way. We are not making up theoreticals.

> Yes it adds another couple of lines to the documentation but will assuredly save people an extra google search of their own and could reduce extra errors that may be introduced when people have to do this on their own every single time.

It seems to me that showing an example of computing the bin centers in the docstring would accomplish much the same thing. Do you agree that such an example would _help_ even if it does not go all the way that you would want?

> Those who are going through the documentation will pass over it unless they need it. They're not going to be tripped up by an extra keyword.

Before this thread started, I didn't think numpy users would be tripped up about how to find bin centers from edges, but here we are. I have learned otherwise and adjusted my beliefs and agree that _some_ kind of action should be taken. I am still unconvinced that allowing `np.histogram()` to return the bin centers is the appropriate action. I have heard you, I have learned from you, and I still disagree on the final action.

You are free to make the value judgement that the extra complication to the documentation (and the technical constraint on the type annotations) is _worth_ the benefit of feature, but please allow that others are allowed to make different value judgements. In the end, it's the numpy maintainers that are going to do the work and support it in perpetuity. They get to make the final judgement about what they spend their effort on.

We all have our own motivations for being here. No one can dictate to us what they _ought_ to be. We've been reasonably up front about what would convince to act and the balancing factors in play for us. That's an invitation to engage on those terms, not shutting you down. It's the numpy team's volunteer time you are bidding for, so it's those terms that finally matter.

**Comment by mattip** [comment]
Providing a viewpoint from another NumPy maintainer: I agree with @rkern that other alternatives are preferable to adding a kwarg.

**Comment by eric-wieser** [comment]
> 1. The examples in the `np.histogram()` should show how to calculate the bin centers (and I would suggest also bin widths) from the edges. This action is a no-brainer; essentially no cost and all up-side. I don't think we'll get much disagreement from the numpy team.

I was going to suggest this earlier, but wanted to understand the underlying motivation first. Certainly we should document this, but I think it would be great to phrase it as something like _"When plotting histograms, it can sometimes be useful to find the bin and edge centers, which can be done as [...]. Note that for fitting curves to histograms, a more principled approach than using the bin centers is [...]."_

**Comment by rkern** [comment]
Sometimes you want to plot the histogram with "lines and markers" (i.e. `plt.plot(bin_centers, counts, 'o--')`). That's a reasonable-enough use case for an example. I do see this more frequently with power-law-type data where logarithmic binning is used (and thus the geometric centers are better to visualize rather than the arithmetic centers), but I'm not too fussed about it.

Alternatively, we don't have to state a concrete use case (the "When plotting histograms" introduction). `(bin_centers, bin_widths)` is a complete, information-preserving, readily-interpretable representation of the bins, and that is justification enough for me for an example.

I don't care too much about warning people away from fitting histograms using `curve_fit()` in this docstring. It's a somewhat more expansive topic than the space permits.

By the way, for those looking for a more concrete reference in the literature for the benefits of an MLE approach over a `curve_fit()`-style approach, [Power-law distributions in binned empirical data](https://arxiv.org/abs/1208.3524) is a good one.

**Comment by rkern** [comment]
Another motivating example for demonstrating the `bin_centers, bin_widths` representation is to plot error bars.

```python
rng = np.random.default_rng(0xc1cebea89f7711c9bb74274cb2558e7c)
data = rng.standard_normal(400)
counts, edges = np.histogram(data, bins=20, range=(-3, 3))
bin_centers = 0.5 * (edges[:-1] + edges[1:])
bin_widths = np.diff(edges)
yerr = np.sqrt(counts)  # rule-of-thumb estimate for Poisson-distributed counts

plt.bar(bin_centers, counts, width=bin_widths)
plt.errorbar(bin_centers, counts, yerr=yerr, ecolor='black', fmt='none')
```

**Comment by mattip** [comment]
Closing. The general sentiment from the maintainers is that we cannot reach a reasonable kwarg that is not simply
```
counts, edges = np.histogram(data, bins=20, range=(-3, 3))
bin_centers = 0.5 * (edges[:-1] + edges[1:])
```

However, a PR to add documentation with this two-liner and some discussion of other ways to think about bin centers would be welcome.
