### ISSUE TITLE
Inconsistent testing `np.nan` in set

### ISSUE THREAD

**Issue by kykosic** [numpy/numpy#13195]
There are inconsistent behaviors when using np.nan in set membership tests. For all types of nan, it is true that `np.nan != np.nan`. However, only with the `np.float` type of nan does `np.nan in {np.nan}` set membership evaluate to `True`.

### Reproducing code example

```python
import numpy as np
print(np.nan == np.nan)
print(np.float64(np.nan) == np.float64(np.nan))
print(np.nan in {np.nan})
print(np.float64(np.nan) in {np.float64(np.nan)})
```
Output:
```
False
False
True
False
```
### Numpy/Python version information:
```
1.16.2 3.7.1 (default, Dec 14 2018, 13:28:58)
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by seberg** [comment]
This is not a property of numpy, but instead a property of python. NaN does not have the necessary property that `NaN != NaN` although `hash(NaN) == hash(NaN)` **can** be `True`. There is not just one `NaN` singleton, `np.nan` is just one `NaN` instance (it is an instance of python float and not `np.float64` which is what you see here in part), since `float(np.nan) is np.nan`.

This is an issue that is not even solvable. The only thing could be to simply not allow you to put `NaN` into a dictionary by making `hash(np.nan)` fail, and I believe Python has long ago decided against that.

Maybe to be clear, you can repeat your game just as well for example with `float("nan")`.

**Comment by seberg** [comment]
Sorry, the important thing of course is that `np.nan is np.nan` although `np.nan != np.nan`. Hash may play a minor role, but it is mostly that NaN (just like all floats) is hashable although it fails the equality property.

**Comment by kykosic** [comment]
Very enlightening, thank you for the detailed response!
