### ISSUE TITLE
BUILD: what is generate_mtrand_c.py ?

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#13315]
xref #13163 

Does anyone know what is ['numpy/random/mtrand/generate_mtrand_c.py'](https://github.com/numpy/numpy/blob/v1.16.2/numpy/random/mtrand/generate_mtrand_c.py) and why it is in ['MANIFEST.in'](https://github.com/numpy/numpy/blob/v1.16.2/MANIFEST.in#L11) ? Is it used by some downstream package? It does not seem to be used in [creating the wheels](https://github.com/MacPython/numpy-wheels)

**Comment by seberg** [comment]
It used to be around to generate the `mtrand.c` file. The reason was the not everyone had cython installed, and the `mtrand.c` file was actually checked into git. I am not sure that script does much except run cython on `mtrand.pyx` and I think nowadays the build process just does that. So I think it should be safe to delete it.
