### ISSUE TITLE
numpy.string_(x) returns empty string '' if x is int

### ISSUE THREAD

**Issue by ghost** [numpy/numpy#13427]
In python 3 / numpy 16, `numpy.string_(3)` returns an empty string `b''`.  Note that in python 2 / numpy 15, it returned a string representation of the number 3

### Reproducing code example:

```python
import numpy as np
print(np.string_(1))
# result:  b''
print(np.string_(1.0))
# result:  b'1.0'
```

### Numpy/Python version information:
1.16.2 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]

**Comment by ksunden** [comment]
Light testing shows that it is a Python 2 vs 3 thing, tried latest point releases of 1.15 and 1.14 on python 3, both had the result of `b''`, while my distro-provided numpy 1.16.0 on python 2 produced `'1'`

**Comment by ksunden** [comment]
Also, I will note that `np.str_(1)` returns `'1'` as expected, (note that `string_` is an alias of `bytes_`, not `str_`)

**Comment by seberg** [comment]
Seems strange I admit. It is actually documented as is, I suppose that `bytes` are a bit special, but this seems also to me too special probably. I am not sure where it comes from though. From the docs (`string_` is an alias to this):

> bytes(int) -> bytes object of size given by the parameter initialized with null bytes

**Comment by ksunden** [comment]
Being a length `n` bytes object of `b'x\00'` mirrors what raw builtin `bytes(n)` does, so there's at least an argument to be made there.

What added to my own confusion here, is that I hadn't realized that numpy strips trailing null bytes when printing strings.

```python
>>> np.bytes_(2)
b''
>>> np.bytes_(1)
b''
>>> np.bytes_(2) == np.bytes_(1)
False
>>> np.bytes_([2,0])
b'\x02'
>>> np.bytes_([0,2,0])
b'\x00\x02'
```

This differs from builtin byte's `__repr__` behavior

```
>>> bytes(1)
b'\x00'
>>> bytes(2)
b'\x00\x00'
>>> bytes([2,0])
b'\x02\x00'
```

**Comment by seberg** [comment]
Then that is where it comes from since it subclasses `bytes`, a bit strange, but just one strangeness to add to the others. As to the stripping, yes, it is necessary since numpy does not store a length information for string dtypes. Would be nice to have better strings in that regard, but that is a different issue.

I feel like we probably cannot do much about it, except create better string/bytes types, which we probably have plenty issues open about.

**Comment by dllahr-foghorntx** [comment]
Thank you everyone for looking into this - so would the recommendation be to use `np.str_` instead of `np.string_` ?

**Comment by seberg** [comment]
@dllahr-foghorntx they are two different beasts, so you cannot just switch from one to the other probably. One is byte strings, the other is unicode strings. I would probably recommend to simply not use the `np.bytes` or `np.string_` types directly for instanciation though (if you need an array, use `np.array(..., dtype=...)`. Otherwise, probably just make sure you put pass in a byte string to begin with and do not rely on numpy doing the coercion to byte string.

**Comment by bsipocz** [comment]
The discussion seems to be concluded above, so I go ahead and close this now. Please reopen if you think otherwise.
