### ISSUE TITLE
numpy.concatenate change '>f4' dtype to 'float32'

### ISSUE THREAD

**Issue by wang1943** [numpy/numpy#13444]
I've encountered some strange behavior of numpy.concatenate today. So I have two arrays of data type '>f4', but after concatenate, the combined array type changed to 'float32'. This is confusion and I thought all numpy function keep the byte order of the original ones. Could every let me know if I miss something? Thanks a lot!

```
array_A = np.array([0.5], dtype='>f4')
array_B = np.array([0.3], dtype='>f4')
array_C = np.concatenate((array_A, array_B))
print(array_A.dtype) # dtype '>f4'
print(array_B.dtype) # dtype '>f4'
print(array_C.dtype) # dtype 'float32'
```

I'm using numpy 1.15.4 on a windows 7 64bit environment.

**Comment by seberg** [comment]
This is because type promotion occurs when you have more then one element. And type promotion will always return a native type order. That said, I have to agree it seems wrong to have this occur in concatenate when all datatypes are identical. My gut feeling is, we could probably switch it over, although it would be a slight change in a corner case.

You could probably provide the `out` kwarg as a workaround.

**Comment by wang1943** [comment]
Thank you for respond. Yes, that work around works great.

**Comment by ganesh-k13** [comment]
@seberg , @eric-wieser is this still considered a bug? Is it good to change behaviour?

**Comment by seberg** [comment]
@ganesh-k13 I don't have serious ambition to fix this. I am not sure if I mentioned it here, but I think dask actually has `output_dtypes` which may or may not be the same thing. The `dtype` attribute has some strange behaviours if you look too closely at it, so my feeling is that I would rather add a new `output_dtypes` argument rather than modify that `dtype` really doesn't choose the exact instance.

But that is just my current angle basically, to me it feels like low priority compared to the fact that I need to look into rewriting all of the code surrounding it...

**Comment by seberg** [comment]
Just stumbled on this (due to the tag).  I have no plan on actually changing this its baked in deeply, and non-native byteorder is weird and not for day-to-day users.  So closing, it would need a serious proposal to convince me probably.
