### ISSUE TITLE
Azure no longer passes on 32 bit linux.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#13448]
See https://dev.azure.com/numpy/numpy/_build/results?buildId=3152. Probably related to the failing PR #13336. @mattip Could you take a look?

**Comment by mattip** [comment]
I wonder how it passed CI in the PR but not after merging. It seems that CI run does not have git, so the `subprocess.check_output` call fails with `FileNotFoundError` which is a sublcass of `OSError`. Before #13336 the call used `Popen` and caught only `OSError`. In #13336 I changed the call to `check_output` which, when run on an sdist (no git repo) raises `subprocess.SubProcessError`, so I switched the `except` clause to that one, dropping the `OSError`. In pr #13449 I catch both errors.

**Comment by tylerjereddy** [comment]
This happened because the reviewer assumed that green CI means it is safe to merge. That seems like a fair assumption, except that we only hard fail Azure CI entries when there are test failures, which means that test results have to be produced to record the failure in the next step of test publication.

But build failures are ignored when build + test are smushed into one Azure stage.

This is the tradeoff we implicitly accepted by allowing test results to be published even when the build / test stage fails.

I see PyPy3 was failing in that PR before merge too, for a different reason as well. I believe the longer-term solution is to separate the build and test stages to separate steps, and enforce a hard fail on build errors, but catch test failures only in the publication stage.

For the 32-bit job this is a little tricky because a docker container is used to do both build & test, but there should be a neat way around that with some thought / mounting of the build results.

Matti can perhaps comment on the PyPy3 job, but it should almost certainly be expanded in this way & same for all other azure jobs with fused build + test stages (also kind of makes runtests.py a little less useful).

Anyway, after Matti patches this specific issues, perhaps another should be opened with a short summary of this..

**Comment by mattip** [comment]
I think we should go back to a hard fail.

**Comment by tylerjereddy** [comment]
> I think we should go back to a hard fail.

-0.5; Azure has these things built in for a reason--we just have to separate the build from test so that we can summarize test failures when they happen

**Comment by mattip** [comment]
Even if we build separately from running tests, if a test segfaults or otherwise exits with a non-zero exit code we will think the test run succeeded.

**Comment by tylerjereddy** [comment]
We can always add a stage that probes for production of test results--if they're not there, hard fail at that stage.

**Comment by rgommers** [comment]
> Anyway, after Matti patches this specific issues, perhaps another should be opened with a short summary of this..

done in gh-13452
