### ISSUE TITLE
BUG: np.broadcast(1, **{}) raises ValueError: keyword arguments not accepted.

### ISSUE THREAD

**Issue by brilee** [numpy/numpy#13455]
https://github.com/numpy/numpy/blob/4b6b29afc06a639975d08f2e95dc3e1c36486188/numpy/core/src/multiarray/iterators.c#L1391 shouldn't be directly comparing to NULL; it should be checking that the kwargs dictionary is len 0 or something like that.

**Comment by seberg** [comment]
Seems like a simply enough fix. May want to wait for gh-13445 to avoid the possible merge conflict.

**Comment by mattip** [comment]
grep 'kw* != NULL' shows 7 occurrences in the source

**Comment by hdamron17** [comment]
Hello, I have fixed this issue, but I am not entirely sure where in the [test script](https://github.com/numpy/numpy/blob/master/numpy/core/tests/test_multiarray.py) to add tests for this since I am having a difficulty matching up the C code with the python.

Also, since gh-13445 has been merged, I assume this issue is ready to be fixed.
