### ISSUE TITLE
DOC: Documentation suggest `__array__` interface is used for `out` kwarg to ufuncs

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#13458]
The documentation at: https://www.numpy.org/devdocs/reference/arrays.classes.html#numpy.class.__array__

suggests that when `out=non_ndarray` is used as kwarg to ufuncs, `non_ndarray.__array__` is called and used as output. This is not the case, and does not make much sense, since `__array__()` often/usually(?) can even return a copy.

The documentation should thus be fixed. Issue originally filed as pull request: gh-7318

**Comment by hdamron17** [comment]
Hey, I am new to the community, but I am interested in getting started. I want to clarify that I am understanding the issue correctly before beginning to make changes to the documentation. 

Looking at [ufunc _set_out_array](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_object.c#L816), it seems the `out` parameter currently only checks that `out` is a writable array rather than calling `__array__` to produce a writable array as mentioned in pull request #7318.

The documentation seems to be inconsistent with the code both at https://www.numpy.org/devdocs/reference/arrays.classes.html#numpy.class.__array__ as @seberg mentioned but also at https://www.numpy.org/devdocs/reference/ufuncs.html#output-type-determination.

What I don't completely understand is the discussion of `__array_ufunc__` which #7318 says is the reason the documentation became inconsistent. Is `__array_ufunc__` called somewhere within the ufunc code so then `non_ndarray.__array_ufunc__` gets called as stated by ["one of the input or output arguments has a __array_ufunc__ method, it is executed instead of the ufunc"](https://www.numpy.org/devdocs/reference/arrays.classes.html#numpy.class.__array_ufunc__)?

**Comment by seberg** [comment]
Welcome, yes, please feel free to open a PR (some of the discussion can also go there). `__array_ufunc__` is the solution to the problem in the original issue/PR. So it does not have anything directly to do with the documentation fix here (and is not the reason for it becoming inconsistent, I would think).

**Comment by hdamron17** [comment]
So in the first instance (https://www.numpy.org/devdocs/reference/arrays.classes.html#numpy.class.__array__), it mentions essentially nothing else about what the `__array__` method does so everything that is there now would be removed. Should I add mention of that `__array__` essentially casts whatever object to an array type, often making a copy? I am confused because the page seems to only discuss `__array__` with respect to `ufunc`s even though the page is about `ndarray`s in general.

**Comment by seberg** [comment]
Array is a slot that has to return an equivalent array representation (usually with a copy I think, but I am not sure all projects confirm to that). With respect to ufuncs, it is specifically not used for the ou kwarg, though. am on phone now, so cannot check the exact docs easily though.

**Comment by rossbar** [comment]
Looking at this a bit, the description of `__array__` in the [docs in question](https://numpy.org/devdocs/reference/arrays.classes.html#numpy.class.__array__) contains *only* this blurb about `__array__` being used as the output of ufuncs (and, as noted, is incorrect in this regard) whereas the [docstring for `ndarray.__array__`](https://numpy.org/devdocs/reference/generated/numpy.ndarray.__array__.html) provides a more general description of how `__array__` works with `ndarray`.

Does the description in [`ndarray.__array__`](https://numpy.org/devdocs/reference/generated/numpy.ndarray.__array__.html) adequately capture what `__array__` is supposed to do for classes that define it?

**Comment by seberg** [comment]
Well, a reference to self does not make sense for array-likes, since this must return an array. The `dtype` part is true, but while we may not want to tell the user... We actually do not care about it, NumPy will happily force-cast no matter what the dtype is. The only thing `dtype` actually does is give the exporter the chance to avoid an unnecessary copy...
```
In [1]: class arraylike: 
   ...:     def __array__(self, dtype=None): 
   ...:         return np.array([True, False, True]) 
   ...:                                                                                                                 

In [2]: np.array(arraylike())                                                                                           
Out[2]: array([ True, False,  True])

In [3]: np.array(arraylike(), dtype=float)                                                                              
Out[3]: array([1., 0., 1.])
```
(dtype is passed, you can check with a print)

**Comment by rossbar** [comment]
> Well, a reference to self does not make sense for array-likes

Right, great point! I didn't mean to suggest directly copying the `ndarray.__array__` docstring over, but rather trying to port over the meaning: that `__array__` is supposed to give a numpy array (leaving out the details like whether it's a reference or a copy). Note I'm not entirely clear on whether this is what `__array__` is intended to do, but looking at how it is implemented in other libraries like `dask` and `torch`, this appears to be the case.
