### ISSUE TITLE
Azure config silently passes build issues and crashes

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#13452]
Follow-up to gh-13448. Summary of the issue by @tylerjereddy there:

"""
We only hard fail Azure CI entries when there are test failures, which means that test results have to be produced to record the failure in the next step of test publication.

But build failures are ignored when build + test are smushed into one Azure stage.

This is the tradeoff we implicitly accepted by allowing test results to be published even when the build / test stage fails.

I see PyPy3 was failing in that PR before merge too, for a different reason as well. I believe the longer-term solution is to separate the build and test stages to separate steps, and enforce a hard fail on build errors, but catch test failures only in the publication stage.

For the 32-bit job this is a little tricky because a docker container is used to do both build & test, but there should be a neat way around that with some thought / mounting of the build results.

Matti can perhaps comment on the PyPy3 job, but it should almost certainly be expanded in this way & same for all other azure jobs with fused build + test stages (also kind of makes runtests.py a little less useful).
"""

The Azure config issue isn't solved. I agree with Matti's comments on that issue, we should make Azure behave like all other CI. Build failures, segfaults, etc. should all result in a little red cross so the reviewer actually goes and has a look.

**Comment by rgommers** [comment]
> We can always add a stage that probes for production of test results--if they're not there, hard fail at that stage.

I don't quite understand this. Isn't there a mechanism to flag failures at the point where they occur? Anything that fails normally gives a nonzero exit code, so this should be easy .....

**Comment by mattip** [comment]
We have requested Azure to ignore the exit code so that the next step, publishing the test results, will run. That step will fail if there are test failures. However a crash produces no test failures, so the publishing step succeeds as well, making the build succeed.

The minor convenience of the extra [test results page](https://dev.azure.com/numpy/numpy/_build/results?buildId=3121&view=ms.vss-test-web.build-test-results-tab) does not seem worth the danger of missing out on test crashes. Maybe when Azure fails the build for empty test results we can reconsider.

**Comment by eric-wieser** [comment]
Is this comment relevant?

https://github.com/Microsoft/azure-pipelines-tasks/issues/1268#issuecomment-187240498

**Comment by tylerjereddy** [comment]
> I don't quite understand this. Isn't there a mechanism to flag failures at the point where they occur? 

Yes, and we've disabled it on purpose for build + test stage so that if a test fails in one stage, we can still publish a summary of the failure in the next stage. All other stages are still guarded by the usual exit code catch.

> The minor convenience of the extra test results page does not seem worth the danger of missing out on test crashes.

I don't understand this sentiment--DevOps is just coding and Azure docs contain a description of [custom conditions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml). There's a language with dependency graphs that we should be able to bend to whatever complex needs we might have. We tried using the defaults on the Publish Task and they weren't quite good enough, but that doesn't mean we should give up.

> Is this comment relevant?

I think so--`always` is mentioned in the docs I linked above. Seems like there are plenty of avenues to explore--can also do a generic `failed` stage that just hard fails if any previous stage failed as a safeguard, but not likely needed given we have a programming language we can use to control behavior.

> On each step and job, you can specify the conditions under which the step or job will run.
> - Only when all previous tasks have succeeded
> - Even if a previous task has failed, unless the build or release was canceled
> - Even if a previous task has failed, even if the build was canceled
> - Only when a previous task has failed
> - Custom conditions
