### ISSUE TITLE
TST, CI: drone.io for arm, x86 builds

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#13532]
@isuruf mentioned that conda-forge will soon start using [drone.io](https://cloud.drone.io/) for arm CI jobs. Apparently the service is quite good and [includes x86 as well](https://blog.drone.io/drone-cloud/), so if we need more slots this is a bookmark to look into that maybe.

Free for open source apparently / no time limits per month.

**Comment by mattip** [comment]
Did conda-forge end up using this service?

**Comment by isuruf** [comment]
Yes, all our aarch64 jobs are run on Drone CI.

**Comment by mattip** [comment]
@isuruf do you know how the service compares to travis? As far as I know travis is using qemu machines.

**Comment by isuruf** [comment]
Drone CI gives 1 hours instead of 50 mins in Travis CI
Drone and Travis are both using aarch64 servers by Packet.
Drone has less queueing time than Travis.
We've had issues with Drone sometimes dropping jobs, but I think that's because our API key was getting rate limited due to 9k repos on conda-forge.

**Comment by seberg** [comment]
Years old issue about CI setup, I don't think those age well enough to keep :).
