### ISSUE TITLE
Expected return value for mean/std/var on 0-length dimensions

### ISSUE THREAD

**Issue by pentschev** [numpy/numpy#13582]
I've recently ran into a case where `mean`/`std`/`var` return `nan` for arrays with 0-length dimensions, which seems inconsistent with behavior of functions such as `max`/`min`:

```python
>>> import numpy as np
>>> np.max(np.empty((0, 0)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pentschev/miniconda3/envs/dask/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2505, in amax
    initial=initial)
  File "/Users/pentschev/miniconda3/envs/dask/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
>>> np.var(np.empty((0, 0)))
/Users/pentschev/miniconda3/envs/dask/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3367: RuntimeWarning: Degrees of freedom <= 0 for slice
  **kwargs)
/Users/pentschev/miniconda3/envs/dask/lib/python3.7/site-packages/numpy/core/_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Users/pentschev/miniconda3/envs/dask/lib/python3.7/site-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
nan
```

It seems to me that this is a side-effect from the `ret / count` operation (in that particular case, `ret = 0.0` and `rcount = 0`), and perhaps there should be some check to prevent that from occurring.

Could anyone confirm if that's the expected behavior, and if not, what should be the correct one? I'd be happy to submit a PR to fix this if we can confirm the current result is incorrect.

The output is from NumPy 1.16.2, and happens also in 1.16.3.

**Comment by seberg** [comment]
This is intentional. the reason is that the sum over an empty set is defined (it is 0). The size of it is also defined (also 0), so the mean is 0/0. On the other hand, min/max of no numbers cannot be reasonably defined, so we have to error. In general we try to not error when there is an unambigious definition available. Note that you do get a warning, which you could set to an error (especially  for a chunk of code), if say you know your code should never produce NaN.

I will tentatively close, but feel free to discuss! (we can always reopen as well)

**Comment by pentschev** [comment]
What you say makes total sense to me @seberg, thanks for the detailed explanation!
