### ISSUE TITLE
Clarify array+scalar type promotion

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#13591]
There are already a few issues regarding the dtype of e.g. np.int64 + python.int (e.g. #7126), but I just realized that the dtype of adding an array of a certain dtype with a numpy scalar of another dtype is also far from clear.

### Reproducing code example:

```python
>>> (np.zeros(5, np.float64) + np.float32(0)).dtype
dtype('float64')
>>> (np.zeros(5, np.float32) + np.float64(0)).dtype
dtype('float32')
>>> (np.zeros(5, np.int64) + np.float32(0)).dtype
dtype('float64')
>>> (np.zeros(5, np.float32) + np.int64(0)).dtype
dtype('float32')
```
OK, so so far it looks like we try to match the width of the array type (which may make sense to not use more memory?  dunno)... but then
```
>>> (np.zeros(5, np.int8) + np.float32(0)).dtype
dtype('float32')
>>> (np.zeros(5, np.int16) + np.float32(0)).dtype
dtype('float32')
>>> (np.zeros(5, np.int32) + np.float32(0)).dtype
dtype('float64')
```
which is not really consistent(?!?) with the above.

### Numpy/Python version information:

1.16.3 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

**Comment by seberg** [comment]
The code is in `convert_datatype.c` around lines 1550. This all should get a nice cleanup. In any case, for integers it should be pretty clearly choose the a scalar (if it is not only scalars) will be demoted to the smallest type capable of holding the data.

For floats things get a bit stranger, because I think the ranges may be slightly arbitrary/not exact:
```
value > -65000 && value < 65000  # float16 is enough
value > -3.4e38 && value < 3.4e38  # float32 is enough
value > -1.7e308 && value < 1.7e308  # float64 is enough
```

After that normal promotion rules apply. Remember that float64 + int64 is float64 (which is slightly strange/wrong in a sense) and that this special case of "lets assume that `int64` fits into `float64`" is not used for `int32` fitting into `float32`.

I suppose it may make sense to write this down somewhere, but I also suppose it may make sense to think about how to morph/change this.

**Comment by anntzer** [comment]
The fact that the value is taken into account is curious, as, for the scalar+scalar case, @rkern stated in https://github.com/numpy/numpy/issues/7126#issuecomment-175571231:
> We can't really look at the value to determine the output type because the same logic needs to apply to arrays as well.

**Comment by seberg** [comment]
Well, I think general consensus is, that it probably was a bad idea (except probably for python scalars, which means the trickiness would somewhat remain). But yes, its there for years now and it is hard to judge how easy it is to change.

**Comment by seberg** [comment]
I think NEP 50 effectively clarifies it (although some additional docs would be nice, I don't think the issue here is helpful for that).
