### ISSUE TITLE
if __array_function__ is available, np.sum won't fallback to using __array__

### ISSUE THREAD

**Issue by pilkibun** [numpy/numpy#13759]
```python
import os
os.environ['NUMPY_EXPERIMENTAL_ARRAY_FUNCTION']='1'
import numpy as np
class MyArray1(object): 
    def __array__(self):
        return np.array([40,2]) 
        
        return NotImplemented

class MyArray2(object):
    def __array__(self):
        return np.array([40,2])

    def __array_function__(self, func, types, args, kwargs):
        print("__array_function__ called", func)

        return NotImplemented

In [38]: np.sum(MyArray1())
Out[38]: 42
        
In [39]: np.sum(MyArray2())
 
TypeError: no implementation found for 'numpy.sum' on types that implement __array_function__: [<class '__main__.MyArray2'>]

```

Not sure what the right thing here is, but this basically means that once I implement 
`__array_function__`, stuff that was working stops working, unless I reimplement them
inside `__array_function__`, which seems like it would lead to lots of boilerplate.

Am I missing something?

cc @shoyer

**Comment by shoyer** [comment]
I agree that this is annoying, but yes it was definitely intentional. We spent quite a while trying to develop a solution that would not require this, but for various reasons none of them were satisfactory. You can find a discussion of the issue in [this part of NEP-18](http://www.numpy.org/neps/nep-0018-array-function-protocol.html#partial-implementation-of-numpy-s-api).

**Comment by pilkibun** [comment]
Fair enough. Thanks.
