### ISSUE TITLE
np.abs does not invoke __array_function__ in 1.16.4

### ISSUE THREAD

**Issue by pilkibun** [numpy/numpy#13755]
Following [NEP 18](https://www.numpy.org/neps/nep-0018-array-function-protocol.html), and in relation to https://github.com/pandas-dev/pandas/issues/26730

I expected `np.abs(ar)` to invoke `__array_function__` like `np.round(ar)` does.

```python
In [29]: import os
    ...: os.environ['NUMPY_EXPERIMENTAL_ARRAY_FUNCTION']='1'
    ...: import numpy as np
    ...: class MyArray(object): 
    ...:     def __array__(self):  
    ...:         return np.array([])
    ...:     def __array_function__(self, func, types, args, kwargs):
    ...:         print("__array_function__ called", func)
    ...:         return np.array([])
    ...: ar=MyArray()
    ...: 

In [30]: np.round(ar)
__array_function__ called <function round_ at 0x7f1e84473ae8>
Out[30]: array([], dtype=float64)

In [31]: np.abs(ar)
Out[31]: array([], dtype=float64)
```

cc @shoyer

**Comment by shoyer** [comment]
`np.abs` is actually an alias to Python's built-in `abs` function, which in turn calls `numpy.ndarray.__abs__`, which I believe is implemented by the ufunc `np.absolute`. So it should be possible to override abs with `__array_ufunc__`, rather than `__array_function__`.

Let me know if that doesn't work, in which case we have a bug...

**Comment by pilkibun** [comment]
Yeah, overriding `__array_ufunc__` does  intercept abs and I see now that NEP-18 clearly states
```
This protocol is intended to be a catch-all for NumPy functionality that is not covered by the __array_ufunc__ protocol 
```
so all is well. Thanks for the help.
