### ISSUE TITLE
Output of savetxt does not indicate float precision 

### ISSUE THREAD

**Issue by YXXX** [numpy/numpy#13796]
i want to cast float64 array to float16 array, and then save the float16 array,but I find the result is still float64.

```python
import numpy as NP
init_array=NP.random.random(10)
cast_array=init_array.astype(NP.float16)
NP.savetxt("result",cast_array)
```

![image](https://user-images.githubusercontent.com/17949369/59576838-acad4500-90f3-11e9-836c-940c9eb49ecf.png)
but he result.txt is still float64 array
![image](https://user-images.githubusercontent.com/17949369/59576861-cd759a80-90f3-11e9-8c85-eaab57b1c32e.png)

**Comment by eric-wieser** [comment]
> but he result.txt is still float64 array

Those values are not "float16" or "float32" or "float64" - they're just a real number represented in exponential notation, stored as text. If you want the file to store the precision itself, you should probably use `np.save` to produce a binary file that can be restored exactly with `np.load`, rather than using `savetxt` which discards information about what type of float is saved.

**Comment by YXXX** [comment]
okay，thank u very much
