### ISSUE TITLE
DOC: mention that nan in an interp input is invalid

### ISSUE THREAD

**Issue by gabrielecalvo** [numpy/numpy#13919]
Possibly related to: https://github.com/numpy/numpy/issues/11439
When running np.interp with xp conatining NaN at the end the results seems to be "stuck" on NaN.

This is the correct behaviour that I'd expect:
```python
>>> np.interp([1,3,1], [0, 2, np.nan, np.nan], [10, 20, 30, 40])
#array([15., nan, 15.])
```

But if I add another np.nan in the second arguments:
```python
>>> np.interp([1,3,1], [0, 2, np.nan, np.nan, np.nan], [10, 20, 30, 40, 50])
#array([15., nan, nan])
```

### Numpy/Python version information (tried both):
1.16.2 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
1.16.4 3.7.1 |Anaconda, Inc.| (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
I think this might be fixed in 1.17

**Comment by seberg** [comment]
I just checked, it is not. My best guess is that the binary search fails with `np.nan` in the keys.

**Comment by zjpoh** [comment]
We get the above behavior because the binary search algorithm gets a guess index as input based on the previously found index. The previously found value is NaN, causing all the boolean conditions in the binary search algorithm to return false.

We can solve this with a couple different ways.
1. We can make sure that the guess index does not get updated when the found value is NaN so that the guess values never points to NaN values.
1. We can push this check to the user side such that the user needs to make sure that xp does not contain NaN values.

After some discussions with @seberg, we prefer the second option because we think that having xp as NaN is not a valid input and the user should be aware of that.

**Comment by eric-wieser** [comment]
Worth noting that interp requires it's input to be sorted, which implies it cannot contain nan

**Comment by zjpoh** [comment]
@mattip That makes sense. Do you think we should just emphasize it to the doc or do you think we should add a deprecation message and raise an error in the future version if nan is found in xp as implemented in #13975?

**Comment by seberg** [comment]
Probably it realliy best to just mention it in the docs very clearly, it seems like giving an error is either fairly complex and we specifically removed the check whether the input is sorted...

**Comment by zjpoh** [comment]
@seberg Sounds good. If you are okay, I'll close #13975 and open another PR to change the doc.

**Comment by seberg** [comment]
OK, lets do that then. Thanks @zjpoh
