### ISSUE TITLE
Why shouldn't all_null iterators be legal?

### ISSUE THREAD

**Issue by dcolascione** [numpy/numpy#13934]
Right now, numpy forbids the creation of an NpyIter with all-output operands. IMHO, it should just permit the creation of such an iterator as long as the iterator shape is specified. This kind of all-output iterator can occur as a special case in general code.

### Reproducing code example:

`np.nditer([None], itershape=(5,))`

### Error message:

ValueError: At least one iterator operand must be non-NULL

### Numpy/Python version information:

```
1.16.4 3.6.5 (default, Mar 31 2018, 05:34:57) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment]
As a workaround, can you pass `np.empty((5,), dtype=[])` as a dummy operand?

**Comment by seberg** [comment]
That seems a bit smarter then necessary on first sight? (i.e. why not a broadcasted array, with a reasonable default dtype).

In any case, I agree that if at least one dtype is passed in as well (so that dtypes can be inferred), there is no reason why it should not be valid. PRs welcome, the main difficulty is probably that some maintenance may be required to achieve it without making the code more complex.

**Comment by eric-wieser** [comment]
@seberg, is your comment aimed at my workaround or the original premise?

**Comment by seberg** [comment]
The too smart part at your workaround ;). Unless you are aiming for an empty dtype on the allocated arrays anyway.
