### ISSUE TITLE
How to convert np.float32 to Python float easily?

### ISSUE THREAD

**Issue by ringsaturn** [numpy/numpy#14150]
Hi, I try to convert `np.float32` to a Python float in my project, and I find it's not eaisly. I have to convert it to str and then convert to float.

Here is the code:

### Reproducing code example:

```python
import numpy as np
x = np.float32(1.9)
x.tolist()            # 1.899999976158142
x.item()              # 1.899999976158142
x.view()              # 1.9
str(x)                # '1.9'
float(str(x))         # 1.9
```

### Numpy/Python version information:

`'3.7.3 (default, Mar 27 2019, **:**:**) \n[Clang 10.0.1 (clang-1001.0.46.3)]'`

**Comment by seberg** [comment]
What you are seeing is perfectly expected. Floating point numbers are not exact in most cases and float32 has a lower precision than float64:

https://en.wikipedia.org/wiki/Single-precision_floating-point_format

`1.9` is never an exact number, the number which is closest to `1.9` is printed as `"1.9"`. But what is closest to `1.9` in single precision is not the closest anymore when you to double precision. You can round, or similar things, but generally... If you do not expect precision loss here, you may want to stick to 64bit floating point numbers, since 32bit floating point numbers have too little precision for many tasks.
