### ISSUE TITLE
corrceof method is counter-intuitive for practical application

### ISSUE THREAD

**Issue by tirthajyoti** [numpy/numpy#14175]
The `numpy.corrcoef()` method is coded counter-intuitively for practical applications in data science and machine learning.

The description says,

_**x : array_like**_
A 1-D or 2-D array containing multiple variables and observations. Each row of x represents a variable, and each column a single observation of all those variables...

**This is exactly opposite to how practical datasets are organized**. Each row is a single observation of all variables and each column is a variable in almost all datasets.

If I want to use Numpy methods after reading numeric arrays from a Pandas DataFrame, I will get the wrong result. 

I have to transpose the Pandas Data and then use the `corrcoef()` to get the proper correlation coefficient corresponding to that dataset.

Is there any deep reason it is coded so? Can it be changed?

**Comment by jwd0023** [comment]
It looks like `numpy.corrcoef()` has what you want built-in.

Try setting rowvar=False. 

> rowvar : bool, optional
If rowvar is True (default), then each row represents a variable, with observations in the columns. Otherwise, the relationship is transposed: each column represents a variable, while the rows contain observations.

**Comment by tirthajyoti** [comment]
Thanks. I tested it now with my DataFrame. I am closing it.
