### ISSUE TITLE
Add cummedian for arrays.

### ISSUE THREAD

**Issue by yupbank** [numpy/numpy#14258]
Cumulative median or stream median is a very widely used feature in a lot of areas. 

One of the efficient way to do so is to make min and max heap to save the data into two half.

While having a multiple dimension support is also very important.

**Comment by psimaj** [comment]
@eric-wieser I'd be interested in implementing this feature. Is it something you'd like to see included in the project, or do you feel like it is redundant?

**Comment by seberg** [comment]
@psimaj I think it is probably best if you start developing it outside of NumPy. SciPy may be a more likely candidate, or maybe already has it as a filter option? SciPy already has an N-D median filter, I am not sure about its performance, but improving that rather than adding something to NumPy would be better (if that is what you want).

I will close this issue for now. We can reopen it (and please keep discussing!), but I do not think it is currently a good TODO item, since my gut feeling is that while common, it is probably better housed outside of NumPy.

**Comment by rgommers** [comment]
Agreed with @seberg, and apologies we didn't reply to this issue sooner.

> Cumulative median or stream median is a very widely used feature in a lot of areas.

I think it's the first time I've seen this requested. Where is it used a lot? And is it just median, or are other cumulative statistics of interest as well?

There's an implementation here by the way: https://stackoverflow.com/questions/42765586/numpy-calculate-cumulative-median

**Comment by yupbank** [comment]
i had a cython implementation here https://github.com/yupbank/np_decision_tree/blob/master/decision_tree/np_stream_median.pyx
