### ISSUE TITLE
Chained selectors makes an unexpected copy

### ISSUE THREAD

**Issue by AdrienCourtois** [numpy/numpy#14292]
### Reproducing code example:

```python
import numpy as np
x = np.array([1,2,3])
s1 = np.array([True, False, True]) # or np.array([0,2])
s2 = np.array([True, False]) # or np.array([0])

x[s1][s2] # array([1])

x[s1][s2] = 42
x # array([1,2,3])
```

### Error:
It seems that the chaining of selectors creates an unexpected copy of the array and thus it doesn't modify the content of the array. 
I'm not sure it is a real issue, it could actually be a feature - though quite disturbing. If so, please don't mind my issue.

### Numpy/Python version information:
1.16.2 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]

And I have the same issue with:
1.16.4 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

**Comment by rsokl** [comment]
This is not unexpected behavior, you are using [advanced indexing](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/AdvancedIndexing.html#), which is makes a copy of the underlying array.

Thus when you perform `x[s1][s2] = 42`, you are first indexing into `x` and then you are setting items on the resulting array. I.e., you are effectively doing the following:

```python
>>> y = x[s1]  # y and x do not share memory
>>> np.shares_memory(x, y)
False
```
and then you are setting elements in `y`:

```python
y[s2] = 43
```

Because `x` and `y` do not share memory, this setitem operation had no impact on `x`, which is the appropriate behavior.

**Comment by AdrienCourtois** [comment]
Thanks a lot for your answer.
I mistakingly though it would behave as the "natural indexing", where it is possible to select an element and modifying it using:
```
x = np.zeros((2,2))
x[0][0] = 1
```

**Comment by mattip** [comment]
Since we cannot guarantee that advanced indexing will produce a ndarray that can be described by a single stride per dimension, we will always make a copy.
