### ISSUE TITLE
RFE: faster np.interp function for increasing x

### ISSUE THREAD

**Issue by parrenin** [numpy/numpy#14315]
np.interp(x, xp, fp) works for unsorted x values.
But if x is increasing, interp could be ~2 times faster by not rescanning every xp for every x.
So my request is to make a faster interp function when x is increasing.
This could be done either by writing a new function, or by setting some argument to the interp function.
This would be interesting for my own work since I make an heavy use of the interp function and this is a bottleneck for me in terms of computation time.

**Comment by seberg** [comment]
I am not immediately sure if it changed some time recently, but interp *does* use the previous value as a best guess for the starting point of the next. Now I think it may still always do a bisection search from that starting value, though, so it probably first try a linear or some other small jump ahead search.

**Comment by parrenin** [comment]
OK, thanks for letting me know.
So, nothing to gain here in terms of computation time?

**Comment by seberg** [comment]
@parrenin I am not immediately sure, if you want to have a look we always appreciate PRs. As I said, I am sure it uses the previous as a best guess, but that alone does not go very far, so I think you can probably improve that a lot with slightly more additional logic. (I am not quite sure what is typically done, maybe a first short look ahead/behind instead of a full bisection; and as I said I doubt that happens right now. Whether that actually is the speed limiting thing here, I do not know of course).

**Comment by seberg** [comment]
@parrenin I am going to close this. It should be attempting to optimize at least if the next value is within 8 values of the last one. I do not know if there is some much better algorithm, but it seems thought out. The code is here: https://github.com/numpy/numpy/blob/c8fdb4491b527fed144f7a88f3248a809f8ede4d/numpy/core/src/multiarray/compiled_base.c#L446 (and the branches before and after)
In general optimization PRs are welcome of course.
