### ISSUE TITLE
np.clip one element of uint64 array returns float in v1.17.0

### ISSUE THREAD

**Issue by pllim** [numpy/numpy#14334]
### Reproducing code example:

```python
import numpy as np
a = np.arange(1, 3, dtype=np.uint64)
a[0].clip(0, 34)
```

### Error message:

No error message, but the result is a `float` and not `uint64` anymore.

```python
>>> a.dtype
dtype('uint64')
>>> a[0].clip(0, 34)  # numpy.float64
1.0
>>> a.clip(0, 34)
array([1, 2], dtype=uint64)  # uint64 as expected
```

In an older version (Numpy 1.16.4):
```python
>>> a[0].clip(0, 34)  # numpy.uint64
1
```

### Numpy/Python version information:

```
1.17.0 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
```

**Comment by charris** [comment]
Probably a result of making `clip` a ufunc. @eric-wieser  Thoughts?

**Comment by seberg** [comment]
The old clip function used a custom casting logic (giving scalars very little priority, unless they are from a larger kind – not the more typical value based approach). The new will use the common value based logic for scalars, the issue is that the old logic always gave the first argument full priority, while now it gets scalar priority.

The old logic is thus just as bad if the clipping values are not scalars, but in the common case where they are scalars things is clearer.

This is all pretty unfortunate, the question is what to do. We could add TypeResolvers to give full priority to the initial array (which is sensible considering that this goes through a method), but even then we cannot fall back to the default minimum/maximum implementations.
The other options might be to simply force cast before calling into the ufuncs, but I am not quite sure how much that breaks the `__array_ufunc__` support.
Or maybe we can actually live with the change, but it does not feel very good either?

**Comment by pllim** [comment]
From a user's POV, it does seem surprising that `a[0].clip(0, 34)` would ever return a float when `a` is integer arrays. I am not familiar enough with Numpy's internals to favor one solution over the other.

**Comment by eric-wieser** [comment]
I'm not sure this is any different to the behavior that's been around for ever of:
```python
>>> np.maximum(np.uint64(1), 1)
1.0
```

**Comment by charris** [comment]
This needs to be resolved.

**Comment by eric-wieser** [comment]
Note this doesn't reproduce on windows unless you use `np.uint64` instead of `np.uint`

**Comment by eric-wieser** [comment]
@charris: Note that `np.maximum(a[0], 34)` is just as broken, and has been forever - if this affects your view on priority.

**Comment by charris** [comment]
I'm mostly concerned that it looks like a regression.

**Comment by eric-wieser** [comment]
It's a regression, but a regression of a special case towards the long-broken behavior that is used everywhere else (`uint64` <op> `int64` &rarr; `float`). Even the following returns float on 1.16:
```
a[0].clip([0], 34)
```
We could add back the special case in `_methods.clip`, but if we do so we should:
* Find a way to deprecate it and remove it in future (so that clip can become fast again) - perhaps via a deprecation warning requesting the caller perform the cast or pass a dtype argument
* Be careful not to introduce new special cases that are unwanted

As an example of just how un-reproducible the special case is:
```python
>>> np.__version__
'1.12.1'

>>> np.clip(np.int64(1), True, np.uint64(1))
1

>>> np.clip(np.int64(1), 1, np.uint64(1))
1.0
```

**Comment by seberg** [comment]
It would be better to fix, but might be a bit tricky to achieve without hacks? How much does this affect you @plim, does it affect a wider audience?

**Comment by pllim** [comment]
> How much does this affect you

@seberg , not much. We have patched it in our package to not use that code.

**Comment by seberg** [comment]
For now we came to the conclusion that we will not do anything here to solve this small change/regression. If anyone runs into this issue again, please do comment and we can reopen! This decision is based on the fact that there was only a single user who noted the change and they were OK with working around it.
