### ISSUE TITLE
numpy 1.16.4, numpy.load can't load multi tuple saved by numpy.save

### ISSUE THREAD

**Issue by looninho** [numpy/numpy#14363]
Hi,
numpy 1.16.4 can't load multi tuple data from file saved by numpy.save. But numpy 1.16.2 can do it.

### Reproducing code example:

```python
import numpy as np
filesave="myfile"
multi_tuple=(1,(2,3))
np.save(filesave,multi_tuple)
multi_tuple=np.load(filesave+'.npy')
```

### Error message:
ValueError: Object arrays cannot be loaded when allow_pickle=False

### Numpy/Python version information:
1.16.4

**Comment by mattip** [comment]
The default was [changed to False in 1.16.3](https://www.numpy.org/devdocs/reference/generated/numpy.load.html) in response to security concerns. You need to actively specify allow_pickle=True (assuming you are aware of the possible security problems with pickled files). Closing since this is known behaviour, please reopen if I misunderstood the problem.

**Comment by looninho** [comment]
Understand, thank you @mattip.
