### ISSUE TITLE
NaN not allow in int arrays

### ISSUE THREAD

**Issue by codeman101** [numpy/numpy#14451]
I raised an issue on the pandas github and was told the issue is because of how numpy is which is the fact that nan values are only allowed in float arrays not int arrays. Why is this? I was baffled when I noticed pandas showing this behavior.

**Comment by kurtamohler** [comment]
This page explains it: https://www.python-course.eu/dealing_with_NaN_in_python.php
Basically, NaN is specifically defined only for floating point numbers, not integers, by IEEE Standard for Floating-Point Arithmetic. Since Python follows that standard, it does not allow an integer to be set to NaN.
This page explains more about the history of NaN: https://en.wikipedia.org/wiki/NaN

**Comment by seberg** [comment]
Indeed, NaN does not make sense in the context of integers. Masks, or nullable are words used in this context, but only supported as Maskedarrays by numpy (with some limitations). There might be some changes there, but they are general limitations (and generally integers are simply not masked by themself).

These are bigger issues and disucssions though, which already have plenty of open issue and bandwidth.
