### ISSUE TITLE
ndarray.reshape((x, y)) acting differently from ndarray.reshape(x, y) 

### ISSUE THREAD

**Issue by Asa-Nisi-Masa** [numpy/numpy#14461]
### Reproducing code example:

```python
import numpy as np

arr = np.array([1, 2, 3])

A = arr.reshape(3, 1)
B = arr.reshape((3, 1))

foo = [A, B]

assert A in foo
assert B in foo

```

### Error message:

assert B in foo
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Numpy/Python version information:

numpy version: 1.17.0 
python version: 3.5.2

**Comment by seberg** [comment]
There is nothing wrong going on here. You are simply confused by the python `is` operator and the way lists use it. A list will say that something is inside it, if the `is` operator returns True. The question you are asking `A in foo` (where foo is a list), is **not** well defined, because arrays cannot use `arr1 == arr2` reasonably. However, lists will say something is inside them, if `A is foo[0]` is successful.

So what is going on here? The `in` check in this case translates to (this is how python works):
```
def is_inside_list(arr, foo):
    for elem in for:
        if arr is elem:
             return True
        if bool(arr == elem):  # the `bool` is implicit always
             return True
    return False
```
If you look closely. The first operation, will simply stop after the very first `is` check. The second one will *not*. It will hit the `==` check, which returns an array and then `bool(arr)` raises an error.

There is nothing numpy can do about it and there is nothing buggy about numpy. The only peculiar thing is that python does the `is` check first, and in some – rare – circumstances that is not really consistent.
