### ISSUE TITLE
PocketFFT missing LICENSE.md

### ISSUE THREAD

**Issue by sandrotosi** [numpy/numpy#14552]
Hello,
numpy/fft/README.md says

> License
> -------
>
> 3-clause BSD (see LICENSE.md)

but no LICENSE.md file is present in the repo (and thus the release tarball too).

Could you please include that file too? thanks!

**Comment by rgommers** [comment]
Thanks @sandrotosi.

Since none of this code is in an external package anymore, it may make more sense to remove the mention of a license from that README rather than add a separate license file. It can simply be covered by the NumPy BSD license. @mreineck would that be fine with you? If not, can you point me to the `LICENSE.md` file that's in the README?

**Comment by sandrotosi** [comment]
it still lives here: https://gitlab.mpcdf.mpg.de/mtr/pocketfft (included the LICENSE.md file)

**Comment by mreineck** [comment]
I'm fine with either change! Sorry, can't produce a patch right now, will be back at a decent computer in a few days.

**Comment by rgommers** [comment]
thanks @mreineck. I'll open a PR now.
