### ISSUE TITLE
Numerical Error

### ISSUE THREAD

**Issue by luisdiaz1997** [numpy/numpy#14551]
I am having this numerical error.
I am doing single value decomposition.
The problem is that after doing a matrix multiplication using 8+ eigenvectors, the first column of the multiplication product is different(They should be the same no matter what). Here I am summing the differences to show how much they differ by.

<img width="654" alt="Screen Shot 2019-09-19 at 3 04 35 PM" src="https://user-images.githubusercontent.com/14355706/65284589-dad56300-daee-11e9-9c18-61e254fed800.png">

**Comment by charris** [comment]
What platform? What NumPy version? What are `x` and `U`.

**Comment by luisdiaz1997** [comment]
> What platform? What NumPy version? What are `x` and `U`.
<img width="361" alt="Screen Shot 2019-09-20 at 2 37 00 PM" src="https://user-images.githubusercontent.com/14355706/65360316-48979280-dbb4-11e9-8944-d34fb461a477.png">

x and U are matrices of 1000 x 1000, x is my data, and U is my vectors from single value decomposition. Here I am using random matrices for matrix multiplication and seeing the same error.

**Comment by seberg** [comment]
@luisdiaz1997 Can you please answer the question about the platform? The NumPy version alone is not very useful here, because this is code that most likely calls BLAS. So please tell us:
 1. What is your platform, windows/linux/etc.
 2. How did you install numpy?
 3. Do you know which BLAS backend you are using?

If you are not on windows, maybe run: https://gist.github.com/seberg/ce4563f3cb00e33997e4f80675b80953 to help us out here. These type of issues are typically *not* issues with numpy, but instead are issues with the BLAS backend.
