### ISSUE TITLE
`np.concatenate` is super memory consuming.

### ISSUE THREAD

**Issue by zegzag** [numpy/numpy#14597]
### Description:

I found that `np.concatenate()` is super memory consuming for large np.array.
Here is the case:
If I create a big array:
`a1 = np.zeros((120000, 200, 200))`. When this code executed, the memory increased quite a little. 
And if I run the follow code, memory also increased by a tiny amount:
```
a2 = []
for i in range(12000):
    b = np.zeros((10, 200, 200))
    a2.append(b)
```
However, if I follow to run `a3 = np.concatenate(a2, axis = 0)`, memory will soar from about 24 GB to about 60 GB. And when this code finished, memory didn't drop and stay at 60 GB. I wonder there may be something wrong inside the function. Case remains the same for `np.stack()`, raising `MemoryError` for this case.

### Code example:

```python
0 import numpy as np
1 a1 = np.zeros((120000, 200, 200)) 
## run line 1 and check the memory (memory remains normal)
2 a2 = []
3 for i in range(12000):
4     b = np.zeros((10, 200, 200))
5     a2.append(b)
## run line 2-5 and check the memory (memory remains normal)
6 a3 = np.concatenate(a2, axis = 0)
## run line 6 and check the memory (could raise `MemoryError` or memory soaring very much and don't drop down when line 6 finished.
```

### Numpy/Python version information:
Version:
numpy: `1.16.3`
python: `3.6.4`
Linux: `Linux XXX 4.19.66-1-lts    x86_64  GNU/Linux`

**Comment by eric-wieser** [comment]
You'd expect the memory to at least double, because you just copied all of your other arrays into a single array.

**Comment by eric-wieser** [comment]
To me, your numbers don't make any sense. If I try and allocate the large array alone, I need more than 24GiB:
```
In [31]: np.zeros((120000, 200, 200))
MemoryError: Unable to allocate 35.8 GiB for an array with shape (120000, 200, 200) and data type float64
```

When you've constructed `a2`, you have a list of arrays, each 3.58GiB in size.

When you call `concatenate`, you create a _new_ array that is 35.8GiB in size.

So at the point of calling `concatenate`, your arrays by themselves are now consuming 71.6 GiB.

**Comment by LiuHao-THU** [comment]
me too!!!

**Comment by LiuHao-THU** [comment]
any solution?

**Comment by rkern** [comment]
`np.zeros()` will use system calls to allocate 0-initialized memory. On some systems (my Linux installation, for one), this is optimized to return very quickly with only virtual memory allocated (`VIRT` in `top`). The resident set size (`RES` in `top`) still remains tiny. If you uses `np.ones()` or something else to actually fill that memory with something other than 0, or you start manipulating the memory like allocating a larger array with `np.concatenate()` and copying the memory from the individual chunks (which are all still pointing to virtual pages), then the memory usage will shoot up as the memory for the returned array starts to get written to (and thus allocating "real" pages of memory).

At least in the original poster's case, what they were seeing was just an artifact of their OS's optimization of 0-initialized memory allocation, not a real unnecessary memory consumption by `np.concatenate()` itself.

@LiuHao-THU You are likely not doing something _exactly_ like the original poster, but do you think my explanation applies to your case? If not, and you think there is still an actual problem, you will have to provide an example. In order to avoid this OS optimization, use `np.ones()` or other non-trivial array constructor instead of `np.zeros()` in your example.
