### ISSUE TITLE
Can't import numpy

### ISSUE THREAD

**Issue by NathanielWh** [numpy/numpy#14722]
Every time I try to import Numpy I get the following error:

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:

I just uninstalled anaconda before this happened (most likely the problem)

**Comment by rubitry** [comment]
maybe trying 'pip install numpy' will help you get over with this issue.

**Comment by mattip** [comment]
Please post the entire error message, your python version, how you obtained python and numpy, and your operating system.

**Comment by kireetipydisetty** [comment]
Try "python -m pip install numpy"

**Comment by Ilin85** [comment]
Hi
I can not install any module including numpy using pip install command in cmd.
Whenever I try to run "python -m pip install numpy" on CMD, an error occurs.
![Error](https://user-images.githubusercontent.com/56653262/66951401-222c1200-f00f-11e9-888c-2fbb4fe05c31.jpg).
Can anyone help me fix this problem?

**Comment by rubitry** [comment]
Did you try reinstalling python? Because there seems to be an error in python.exe so reinstalling might help you. Try installing 3.7.4 or prior versions

**Comment by mattip** [comment]
When reporting here please:
- tell us your python version and operating system
- tell us where you got python and numpy
- use text copy-paste instead of grabbing screen shots where possible.

@Ilin85 you seem to be using python 3.8, which was only released this week and still is not well supported by downstream projects like numpy.

**Comment by Ilin85** [comment]
Thanks a lot for your attentions.
Special thanks to rubitry.
Your comment solved the problem.
I tried to install the last version (3.8) some times.
But after installing 3.7.4 the problem solved.
Regards

**Comment by Ilin85** [comment]
Hi to all.
I can not import anything from scipy module.
whenever i try to import from scipy.signal it returns DLL error.
> import scipy
is OK.
but 
> from scipy.signal import *
returns DLL error.
Please advice me.
Thanks

**Comment by rubitry** [comment]
Try using conda, that solved my error.

**Comment by Ilin85** [comment]
I did not familiar with conda.
How do I use conda?

**Comment by Ilin85** [comment]
I tried with anaconda.
Try to install using Anaconda prompt using "pip install scipy"
But the error still exists.

**Comment by biscuitlad** [comment]
kester@planetLoic:~$ sudo -H pip3 install --upgrade --force-reinstall numpy
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/0e/46/ae6773894f7eacf53308086287897ec568eac9768918d913d5b9d366c5db/numpy-1.17.3-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy
  Found existing installation: numpy 1.17.3
    Uninstalling numpy-1.17.3:
      Not removing or modifying (outside of prefix):
      /usr/bin/f2py3.6
      /usr/bin/f2py3
      /usr/bin/f2py
      Successfully uninstalled numpy-1.17.3
Successfully installed numpy-1.17.3
kester@planetLoic:~$ blender
Read prefs: /home/kester/.config/blender/2.82/config/userpref.blend
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/2.82/scripts/addons/mesh_tissue/__init__.py", line 56, in <module>
    from . import tessellate_numpy
  File "/usr/share/blender/2.82/scripts/addons/mesh_tissue/tessellate_numpy.py", line 48, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)


Saved session recovery to '/tmp/quit.blend'
Writing userprefs: '/home/kester/.config/blender/2.82/config/userpref.blend' ok

Blender quit
kester@planetLoic:~$ sudo update-alternatives --config python
[sudo] password for kester: 
There is only one alternative in link group python (providing /usr/bin/python): /usr/bin/python3.6
Nothing to configure.

**Comment by biscuitlad** [comment]
sudo -H pip3 install --upgrade --force-reinstall numpy
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/0e/46/ae6773894f7eacf53308086287897ec568eac9768918d913d5b9d366c5db/numpy-1.17.3-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy
  Found existing installation: numpy 1.17.3
    Uninstalling numpy-1.17.3:
      Not removing or modifying (outside of prefix):
      /usr/bin/f2py3.6
      /usr/bin/f2py3
      /usr/bin/f2py
      Successfully uninstalled numpy-1.17.3
Successfully installed numpy-1.17.3
kester@planetLoic:~$ blender
Read prefs: /home/kester/.config/blender/2.82/config/userpref.blend
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/2.82/scripts/addons/mesh_tissue/__init__.py", line 56, in <module>
    from . import tessellate_numpy
  File "/usr/share/blender/2.82/scripts/addons/mesh_tissue/tessellate_numpy.py", line 48, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)


Saved session recovery to '/tmp/quit.blend'
Writing userprefs: '/home/kester/.config/blender/2.82/config/userpref.blend' ok

Blender quit
kester@planetLoic:~$ sudo update-alternatives --config python
[sudo] password for kester: 
There is only one alternative in link group python (providing /usr/bin/python): /usr/bin/python3.6
Nothing to configure.

**Comment by mattip** [comment]
In general, `sudo pip install numpy` is not recommended. You should either do `sudo apt install python3-numpy` or `pip install --user numpy` (with no sudo). From the error message, you now have a mixture of two versions of numpy in `/usr/lib/python3/dist-packages/numpy`, a pre-16.0 version (since it fails to import `multiarray`, a newer numpy looks for `_multiarrary_umath`) and what seems like a 1.17.3 version. 

Perhaps you can clean up your system with `sudo pip uninstall numpy` two or three times until it cannot find a version to remove, then `sudo apt install python3-numpy` or `pip install --user numpy`

**Comment by charris** [comment]
If all else fails, directories can be deleted, but it can be tricky to know which ones to delete and where they all are.

**Comment by biscuitlad** [comment]
OK, many thanks. I can't resolve this and have had to resort to just downloading a older version of blender as a tz.bz2 archive with evnerything in it. I gave up Cura because of python module hell with distros and different versions, and now I'm getting the same thing with Blender. It's a total mess. Shouldn't be happening in 2019 - fair enough in the late '90s with M$ dlls, but not now. Not with a high level scripting language. There are literally a hundred incorrect solutions to this out there. Hugely frustrating for users.

**Comment by Ilin85** [comment]
Thank you guys for your attentions.
I have 2 systems with 2 different Operating Systems.
Python and its modules worked well on one but did not work correctly on the other.
Any attempts for correcting the above problem failed.

Eventually, I copied the module folder from 1st system to 2nd system.

Modules' folder in Python are in the following path (for Windows):
****  <<Your Installation Folder>>\Python37-32\Lib\site-packages  *****

This solved my problem. Every things were good.
I tried this solution for other miss-installed or uninstalled packages. Those work very good now.

Regrads

**Comment by Ilin85** [comment]
Of course, I worked with MATLAB before I work with Python.
These two languages are the same in some aspects.
- They are both open sources.
- The command (shell) and script windows are the same.
- They have so many command (functions) that makes programming easy.

But, in my opinion, MATLAB is more regular and powerful than Python. Because:
- All packages (commands) test by MATHWORKS and introduce with the new version of MATLAB.
- MATLAB has a very powerful help (inside package) with so many examples that describe the application of its commands.
- All commands (functions) and helps has been written in one style and format. So, every one can read the help very easily.

Of course, Python if free of charge and MATLAB is expensive and heavy (due to its volume) software.
Despite, I prefer programming with giant MATLAB.
Regards,

**Comment by mattip** [comment]
@Ilin85 python is not for everyone. If you are happy with MATLAB, by all means stick with it. Note that MATLAB is "source available" not [Open Source](https://opensource.org/osd) since you cannot legally distribute or copy the toolboxes or any of the MATHWORKS provided code.

Pointers to places where `help(np.function)` you find lacking, or places any of the python IDEs such as Spyder, PyCharm or Visual Code could use improvement would be probably be welcome, you can open issues on the respective project's repo pages. For NumPy, you might want to check out the documentation [here](numpy.org/doc/devdocs), for SciPy [here](https://docs.scipy.org/doc/scipy/reference/). Experience of new users and their frustrations is particularly valuable, since most of the contributors are python veterans.

Next time you try python, you might want to look at the [Anaconda distribution](https://docs.anaconda.com/), in particular Anaconda Enterprise (a non-free product) may provide the commercial support you seek. The [free Anaconda distribution](https://docs.anaconda.com/anaconda/) provides a unified framework for working with Python. (I am not affiliated with Anaconda, your mileage may vary).

**Comment by mattip** [comment]
Closing this. @NathanielWh if there are still problems importing numpy, please reopen and update the issue. New reporters, please open a new issue, and be sure to report:
- the entire error message,
- how you installed numpy and python
- your python and numpy versions

**Comment by kingsyard** [comment]
to keep it simple
1.     pip install numpy  

if then also you get the error  try with some particular versions that your work may need.

like pip install numpy==0.9  like this check clearly which version of numpy you need.

if you couldnt install it then try 

2.  pip install --user numpy 

second one is where you are providing permission.(granting user permission).

if you have got any other quarie you can contact us at  [www.smartaitechnologies.com](www.smartaitechnologies.com)   for more
