### ISSUE TITLE
Feature request: normalize

### ISSUE THREAD

**Issue by carlosgmartin** [numpy/numpy#14746]
Add functions `numpy.normalize` and `numpy.ndarray.normalize` which normalize a specified axis of an array. **This is a very common operation in scientific computing.** Adding these functions would make code more concise and less cluttered. It also voids the need to introduce an intermediate variable, which is useful in places like comprehensions.

### Reproducing code example:

```python
import numpy as np

def normalize(x, axis=None):
    return x / x.sum(axis, keepdims=True)
```

**Comment by shoyer** [comment]
The general consensus (e.g., as expressed in https://github.com/numpy/numpy/issues/10173) is that we do not want to add simple helper functions into NumPy at this point, since we already have more functions in `numpy` and methods on `np.ndarray` than anyone can keep track of.

In this particular case, there is the additional challenges that what it means to "normalize" is ambiguous and context-specific. For example, you might expect normalization to divide by a norm (e.g., with `np.linalg.norm`).

**Comment by rgommers** [comment]
Agreed with @shoyer, we don't want to do this. Closing. Thanks for the suggestion @carlosgmartin

**Comment by carlosgmartin** [comment]
@shoyer This is only somewhat related, but is there a reason why the existing functions [`numpy.square`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.square.html) and [`numpy.sqrt`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html) are not attached to `ndarray`?

**Comment by shoyer** [comment]
I’m not sure. Most NumPy universal functions aren’t methods, though.
