### ISSUE TITLE
Python 3.8 cannot find numpy.core._multiarray_umath when installing other modules

### ISSUE THREAD

**Issue by VoxelPrismatic** [numpy/numpy#14819]
Python 3.8 cannot find `numpy.core._multiarray_umath`, my issue occurs when installing modules that list numpy as one of its dependencies.

### Reproducing code example:

```bash
python3.8 -m pip install -U numexpr
```

### Error message:

`Original error was: No module named 'numpy.core._multiarray_umath'`

View the 12kb traceback [here](https://cdn.discordapp.com/attachments/339112602867204097/639504037284282389/txt_interpreter.txt) (ignore the first two lines, I did this remotely)

### Numpy/Python version information:

Numpy - latest [due to dependencies]
Python - 3.8

**Comment by mattip** [comment]
How did you install python3.8? It seems to be looking for numpy in `/usr/lib/python3/dist-packages`, but that should be reserved for OS-installed packages, not ones that are pip installed. I think your python is pip-installing to one place and then loading a numpy from another. This could be due to user environment variables like PYTHONPATH or PYTHONHOME or some script run by PYTHONSTARTUP

Could you report what `ls /usr/lib/python3/dist-packages/numpy/core/_multiarray_umath*.so` shows?

**Comment by VoxelPrismatic** [comment]
I installed python 3.8 with `sudo apt install python3.8`, and because I have py3.6 and py3.7, py3.8 has its own folder and command as `python3.8`
Also, my python home is in `/home/user/.local/lib/python3.8/site-packages`, just so you know.

```
/home/user/.local/lib/python3.8/site-packages/numpy/core/_multiarray_umath*.so:
_multiarray_umath.cpython-38-x86_64-linux-gnu.so
```

**Comment by VoxelPrismatic** [comment]
I tried just tried the below code and it worked perfectly fine.
```py
import numpy
import numpy.core._multiarray_umath
print(numpy.__version)
```
```py
import numpy
from numpy.core import _multiarray_umath
print(numpy.__version)
```

**Comment by VoxelPrismatic** [comment]
**NOTICE**
Running `python3.8 -m pip install -U numexpr` throws an error where `Python.h` isn't found, I most likely need to reinstall py3.8

**Comment by mattip** [comment]
You are trying to build numexpr from source code, rather than download a binary package. You can either wait a while until numexpr releases a binary package, or `apt install python3-dev` to get the header. 

Since NumPy imports, I think the original issue lies elsewhere, and we should close this issue

**Comment by mattip** [comment]
Closing. @VoxelPrismatic if there is something still not clear please reopen.
