### ISSUE TITLE
Add contribution guidelines for docs

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#14817]
We seem to have a bunch of people who want to contribute docs, but end up making readme changes of little significance:

* https://github.com/numpy/numpy/pull/14815
* https://github.com/numpy/numpy/pull/14810
* https://github.com/numpy/numpy/pull/14744
* https://github.com/numpy/numpy/pull/13228
* https://github.com/numpy/numpy/pull/13196

It would be great if we could direct these potential contributors to more valuable places for doc writing, and steer them away from the readme. For a start, a heading in [CONTRIBUTING.md](https://github.com/numpy/numpy/blob/master/.github/CONTRIBUTING.md) about writing documentation might be valuable.

**Comment by ananthan-123** [comment]
I want to do this..Can I put together a PR.

**Comment by rossbar** [comment]
:+1: to @eric-wieser 's idea; laying out a general policy for how to best propose/affect doc changes would be useful. Here are some ideas that I think the contribution guidelines for documentation should emphasize:
 - Correcting technical inaccuracies in the documentation are high priority. For example, if a docstring is missing a parameter or the description of a fuction/parameter/method etc. is incorrect.
 - Other "structural" defects like broken links are also high priority
 - Proposals for changes that improve the clarity of the documentation are welcome. However, "clarity" is a bit subjective, so such proposals are best made by raising issues that describe what could be improved in the current documentation. Proposals that include *specific* suggestions for the improvement are encouraged as the proposed changes helps frame the discussion.
 - Changes fixing grammatical/spelling errors are welcome but not necessarily the highest priority. "Grammatical correctness" often gets confused with "style" which can result in unfruitful discussions that don't necessarily improve anything.
 - Changes that modify wording or rearrange phrasing *without changing the technical content* are discouraged. If the user thinks that a different wording improves clarity, they should open an issue as noted above, but again, changes along these lines very often tend to be highly subjective and not necessarily do much to improve anything
 - Major *additions* to the documentation (e.g. new tutorials) should be proposed to the mailing list.

Based on the above characterization, "high-priority" changes (i.e. fixing technical inaccuracies, broken links, etc.) can be proposed via PR directly as they are straightforward to review. Other changes should be raised as issues first so that the discussion can happen *before* the user makes major modifications, which in principle saves the user from wasting their time on undesired changes.

Of course, documentation issues don't always fit neatly into categories like this, so the proposed distinctions are not a panacea. Nevertheless I do think something along these lines would be a valuable in the guidelines for contribution to the docs.

**Comment by rgommers** [comment]
This was done in gh-16069, closing. Thanks all.

**Comment by eric-wieser** [comment]
It might still be worth adding an explicit 'do not edit the readme' message to this page; we still get meaningless drive-by contributions of the style at the top of this post, and being able to link to a canned explanation of why these contributions are unhelpful would be useful.

**Comment by charris** [comment]
@eric-wieser My guess is the start of the school year accounts for this.
