### ISSUE TITLE
Unclear documentation and functionality of numpy.random.negative_binomial

### ISSUE THREAD

**Issue by piergiacomo75** [numpy/numpy#14887]
Dear all,
I am struggling to understand if numpy.random.negative_binomial can cope with a floating number of trials.

Looking at the documentation 
https://docs.scipy.org/doc/numpy-.14.1/reference/generated/numpy.random.negative_binomial.html
I see 
#########
n : int or array_like of ints
Parameter of the distribution, > 0. Floats are also accepted, but they will be truncated to integers.
#########

however if I look into the code of distributions.c line 591

RAND_INT_TYPE random_negative_binomial(bitgen_t *bitgen_state, double n,
                                       double p) {
  double Y = random_gamma(bitgen_state, n, (1 - p) / p);
  return random_poisson(bitgen_state, Y);
}

n is casted as double and used as such in 
double Y = random_gamma(bitgen_state, n, (1 - p) / p);

I have the impression that the codes can cope with double inputs "n" therefore the code can cope with Polya distributions as well. 
https://en.wikipedia.org/wiki/Negative_binomial_distribution#Poisson_distribution

If so I propose to update the documentation accordingly.

Could you please clarify?
Many thanks,

Piergiacomo

**Comment by adeak** [comment]
You posted a link to older documentation of numpy (version 1.14.1 if we fix the URL). The [current version](https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.mtrand.RandomState.negative_binomial.html#numpy.random.mtrand.RandomState.negative_binomial) as well as [the newer random installment](https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.Generator.negative_binomial.html#numpy.random.Generator.negative_binomial) mention float inputs for `n`.

This seems to have been fixed in https://github.com/numpy/numpy/pull/12937, so I think this issue can be closed.
