### ISSUE TITLE
How to call @FROMTYPE@_to_@TOTYPE@ in numpy/core/src/multiarry/arraytypes.c.src via python

### ISSUE THREAD

**Issue by xiegx94** [numpy/numpy#14885]
I want implement this function by using avx512 intrinsic. Does there any API I can use to test the new function performance via python?

**Comment by eric-wieser** [comment]
My guess would be `.astype` falls back to this function.

**Comment by seberg** [comment]
Most of the time, `astype` will not use those functions, but the ones defined in dtype transfer, I think (it depends on the dtypes).

There may be some corner in numpy that actually does make use of these, but top of my head I cannot think of them, although I may just need a bit to get my head back into this part of numpy.

@xiegx94 your goal is to patch numpy I assume? In that case, since I assume this is for simple types, I suggest you simply ignore the versions in `arraytypes.c.src` and look at the ones in `lowlevel_strided_loops.c.src` which are the ones that get used most of the time. Also keep in touch, about this, we currently use `PyArray_GetDTypeTransferFunction` (internally mostly), which should be reorganized a little, so there may be a good window right now to modify the parameters (which does not mean we cannot do that later at any time).

**Comment by seberg** [comment]
I will close this, we can continue to discuss here, but its not an issue. Or maybe move to the mailing list.
