### ISSUE TITLE
distutils/misc_util.py Configuration settings lead to ImportError DLL load failed

### ISSUE THREAD

**Issue by ilayn** [numpy/numpy#14923]
When building NumPy from the source on Windows 10, the resulting `.libs` folder is not added to the path.

### Reproducing code example:
The regular 

```bash
python setup.py build
python setup.py install
```
machinery succeeds however afterwards numpy import fails with the recently reported `ImportError`s elsewhere, say, #14896 and others.

This happens also on SciPy builds which were successfully working until I switched to Python 3.8. This is also reported on SciPy https://github.com/scipy/scipy/issues/11062

It seems like the generated `__config__.py` has the lines

https://github.com/numpy/numpy/blob/6e75b9ab7888e2d807893a8237811f97f605547e/numpy/distutils/misc_util.py#L2324-L2335

Somehow, .libs folder is not present on the `src.win-amd64-3.8` but it is created in `lib.win-amd64-3.8` and for reasons I have not yet understood, this if branch is not entered. On the linked SciPy issue, the file is modified manually to add the libs to the path.

Hence I am under the impression that it is not necessarily an Anaconda issue but something has changed along the way, that is maybe, Python3.8 related.

**Comment by mattip** [comment]
Python 3.8 on windows no longer searches `os.environ['PATH']` for DLLs, you must use the new [os.add_dll_directory](https://docs.python.org/3/library/os.html#os.add_dll_directory) function instead. 

The code in numpy (and very recently in scipy) works around this by [generating a `_distributor_init.py`](https://github.com/numpy/numpy/blob/v1.17.4/tools/openblas_support.py#L140) file that preloads dependent DLLs by name. We chose this solution since we needed to release a fix while CPython worked out the `os.add_dll_directory` interface. Now that version 3.8 is released, perhaps we should revisit the code you pointed to, and add a path for 3.8+ behaviour.

**Comment by ilayn** [comment]
Indeed changing to `os.add_dll_directory()` makes the SciPy import error vanish. I'll propose that on the SciPy side. NumPy side seems a bit more involved.
