### ISSUE TITLE
Implicit Evaluation not supported for arrays with multiple datatypes

### ISSUE THREAD

**Issue by 2manslkh** [numpy/numpy#14945]
### Reproducing code example:
```python
if np.array([1,'a']):
  print(1)
```
### Error message:

```cmd
ValueError                                Traceback (most recent call last)
<ipython-input-49-2a67bafa284b> in <module>()
----> 1 if np.array([1,'a']):
      2   print(1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
``` 

### Native Python
```python
if [1,'a']):
  print(1)
```
```
>> 1
```
### Numpy/Python version information:

1.17.2 3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]

**Comment by seberg** [comment]
This is not an issue with numpy, as the error states, the numpy arrays do not define a "truth" value (`bool(array)` is normally not defined).

This is necessary, because unlike lists, typical numpy operations work on _all elements_ at the same time. Lists have a completely different concept here, since they do not define elementwise operations.
