### ISSUE TITLE
BUG: `numpy.resize` returns wrong size when using `-1` syntax for axis length.

### ISSUE THREAD

**Issue by MaxTaggart** [numpy/numpy#15030]
When resizing an array with `numpy.resize` and passing `-1` for the size of one of the dimensions you will not always get a shape that is compatible with the original shape.

### Reproducing code example:

```python
import numpy as np

test = np.arange(0, 444)
print(test.shape)
print(np.resize(test, (4, -1)).shape)
print(np.reshape(test, (4, -1)).shape)
```
prints
```
(444,)
(4, 110)
(4, 111)
```
Note that the call to `np.resize` returned an array of shape `(4, 110)` which is not compatible with the original shape, `(444,)`.

I posted about this on [SO](https://stackoverflow.com/questions/59147217/numpy-resize-gives-an-unexpected-array-size-when-using-1-syntax) and someone pointed out that the `resize` *method* of an array forbids using `-1` syntax and gives the following error message
``` python
ValueError: negative dimensions not allowed
```
 Should this restriction also be enforced on `numpy.resize`? Also, just out of curiousity, why is `-1` forbidden on a `resize` but not on a `reshape`?

### Numpy/Python version information:

1.17.4 3.7.1 (default, Jan  6 2019, 15:33:42) 
[Clang 9.1.0 (clang-902.0.39.2)]

**Comment by seberg** [comment]
Yes, this should raise an error. Pull requests would be appreciated, this issue is in pure python code! The logic seems utterly broken for negative numbers, so I think we should just go to error directly.

Note that the use of `np.resize` (or the method) is not reallze encouraged. It uses realloc of the low-level buffer, which comes with issues to the memory model. I.e. it can break `views` into the same array data very badly. (If you use it, it might be good to stick to the method and try to limit it to tight loops that do array construction).

**Comment by agrahajigyasu** [comment]
Is this issue still open?
 I will like to work on it

**Comment by anchit1729** [comment]
Is the issue open? I'd like to try work on it.

**Comment by seberg** [comment]
There is an open PR, but it has been stale for a while. There were some thoughts on how to make the code a bit nicer which were hanging. I suppose you could look at it and pick it up if you want.

**Comment by gil2rok** [comment]
Is this issue resolved?

**Comment by mattip** [comment]
@gil2rok PR gh-15037, which will close this, is still open and waiting for review.
