### ISSUE TITLE
BUG: ufunc on ragged object array emits a warning

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#15045]
After merging gh-14794 this emits a DeprecationWarning

```
$ python3 -Werror

>>> import numpy as np
>>> arr = np.array(["a", "b"], dtype=object)
>>> objs = [arr, "foo", arr]
>>> np.sum(objs, axis=0)
```

xref gh-15041

**Comment by mattip** [comment]
Also, there is a [test](https://github.com/numpy/numpy/blob/master/numpy/core/tests/test_multiarray.py#L2288) that is creating a ragged array and emitting a warning, but the warning somehow slips under the radar of pytest, maybe because it is inside an `assert_raises`

**Comment by mattip** [comment]
The solution to the first problem is to pro-actively create the array with an `object` dtype:
``` python
>>> import numpy as np
>>> arr = np.array(["a", "b"], dtype=object)
>>> objs = np.array([arr, "foo", arr], dtype=object)  # HERE
>>> np.sum(objs, axis=0)

```

I am probably reacting to an overly-simplified example since this is a snippet from a more complex code base.

**Comment by seberg** [comment]
@jbrockmendel is using `np.sum(np.array(objs, dtype=object), axis=0)` in some way undesierable for you? (or even going further and using `arr = np.empty(len(objs), dtype=object); arr[:] = objs` to not rely on numpy guessing the right thing at all)

**Comment by jbrockmendel** [comment]
@mattip @seberg thanks for the quick feedback.  In the np.sum with strs case, the suggested workaround likely works.  To get an idea for where else this comes up in the pandas codebase, see https://github.com/pandas-dev/pandas/pull/30035

The change here https://github.com/pandas-dev/pandas/pull/30035/files?file-filters%5B%5D=.py#diff-d5ffc8f19bc8362967ce9ddd23026739R141 was needed to silence warnings caused by calling operator.mod (i dont remember what the inputs were off the top of my head)

**Comment by mattip** [comment]
Closing the correct fix is to explicitly create the ndarray before calling a ufunc.
