### ISSUE TITLE
np.clip: change in precedence between minimum and maximum when maximum < minimum

### ISSUE THREAD

**Issue by flexatone** [numpy/numpy#15061]
Greetings!

First, thanks to the NumPy community for your efforts.

Second, In NumPy 1.16.5 I observe the following:

```python
>>> import numpy as np
>>> np.clip(2, 3, 0)
3
```

In NumPy 1.17.4, I get a different result:

```python
>>> import numpy as np
>>> np.clip(2, 3, 0)
0
```
I see that the difference has to do with which constraint gets precedence. Was this an intentional change in precedence then?

### Reproducing code example:

```python
import numpy as np
assert np.clip(2, 3, 0), 3
```

### Numpy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.17.4 3.7.4 (default, Dec  3 2019, 11:37:16) 
[GCC 5.4.0 20160609]
```

**Comment by entruv** [comment]
As from the documentation of the function:
`No check is performed to ensure ``a_min < a_max``.`

**Comment by flexatone** [comment]
Thanks for your response. I did see that. But the docs also say that "Equivalent to but faster than `np.maximum(a_min, np.minimum(a, a_max))`" These are no longer equivalent:

```python
>>> np.maximum(3, np.minimum(2, 0))
3
>>> np.clip(2, 3, 0)
0
```

**Comment by eric-wieser** [comment]
Sounds like the doc is wrong.

Note that in the past the behavior was not as simple as you make it out to be - I believe the behavior swapped if you make the inputs arrays rather than scalars

**Comment by seberg** [comment]
Marking it as documentation, because at the moment I do not feel that we should undo the general clip changes. But if more concerns come up, I may change my mind.

**Comment by eric-wieser** [comment]
For reference, #12519 was the change to `clip`

**Comment by tylerjereddy** [comment]
We knew that some of this stuff was going to happen, right? I remember a lot of confusing back-and-forth with the `hypothesis` tests & it was just really hard to get everything perfect for pathological corner cases & move forward. 

Some people also wanted an `Exception` raised because it was a little crazy to deal with `min > max`, but then performance concerns & can't easily put the handling in the inner loops and so on.

Eric can correct me if I'm wrong, but I believe the broader motivation was Travis' proposal: https://github.com/numpy/numpy/issues/12514

So maybe change in behavior for pathological cases was considered "ok" on balance to empower that broader improvent to NumPy?

**Comment by flexatone** [comment]
Many thanks for considering this issue and providing the background to the change.

(FYI: I only noticed the change as I happened to have a StaticFrame test that was exercising the condition of maximum less than minimum.)
