### ISSUE TITLE
np.random.bit_generator broken at 1.18

### ISSUE THREAD

**Issue by zjjott** [numpy/numpy#15152]
### Reproducing code example:

```python
import numpy as np
AttributeError: module 'numpy.random' has no attribute 'bit_generator'
```

### Numpy/Python version information:

`numpy==1.18`

work fine at numpy==1.17.4, I have read release log,

> In addition to the usual bug fixes, this NumPy release cleans up and documents the new random C-API, expires a large number of old deprecations

at 1.17, `bit_generator` is not at deprecation?

I have read numpy code at 1.18,this module move to `np.random._bit_generator` ,cause this broken

**Comment by mattip** [comment]
It is not a deprecation, it is a code change. You need to update your code. We probably should have mentioned it in the release notes.

**Comment by rgommers** [comment]
This was done in gh-14608. The release note update would have been useful, we should probably still amend this since release notes get read for a long time. We don't often update those, but in this case it seems justified.

**Comment by jrounds** [comment]
I thought the point of depreciation was to not immediately break modules when there was a _code change_.  They don't seem mutually exclusive.

I also thought it was good package management practice in high profile projects that if a user upgrades one release to the next that nothing breaks immediately without depreciation warnings

When np.random.random_integers changed to np.random.randint random_integers spammed depreciation warnings until this day. That was useful because code still ran and I could migrate over as I touched code.  It is true that random_integer to randint changed the argument interpretation, so it was not just _"a code change", apparently, but the larger and more important thing to me actually using the interface, is you didn't just delete np.random.random_integer.  You could have!  But you didn't and I thank you for it!

**Comment by rkern** [comment]
Sometimes, we make mistakes. `bit_generator` should not have been exposed as a public module without a leading underscore to indicate that it was private. Given that this mistake was recently introduced and quickly fixed, simply fixing it was deemed the better option instead of letting the mistake exist for a longer time, even giving noisy warnings.

We should have more clearly signposted in the 1.17 release that we expected some mistakes of this nature given the size of this new subsystem and that we would simply fix them without a long deprecation period. We apologize for the inconvenience.

**Comment by iaakanksha** [comment]
Hello, at the time of using pandas-profiling it is showing me the error 
````
ModuleNotFoundError: No module named numpy.random.bit_generator
````
Please help!!

**Comment by rkern** [comment]
I don't see any code in `pandas-profiler` that refers to `bit_generator`, so I suspect this is from something else. Find out what it is and update that code accordingly.
