### ISSUE TITLE
ImportError: Unable to import required dependencies: numpy

### ISSUE THREAD

**Issue by anitatea** [numpy/numpy#15294]
Just importing Numpy on Atom Editor is giving me the error. I am able to import Numpy on Jupyter notebook. I'm pretty new to this but would appreciate any help!

### Reproducing code example:

```python
import numpy as np
```

### Error message:

ImportError                               Traceback (most recent call last)
<ipython-input-13-0aa0b027fcb6> in <module>
----> 1 import numpy as np

~\Anaconda3\lib\site-packages\numpy\__init__.py in <module>
    138 
    139     # Allow distributors to run custom init code
--> 140     from . import _distributor_init
    141 
    142     from . import core

~\Anaconda3\lib\site-packages\numpy\_distributor_init.py in <module>
     32 
     33 with RTLD_for_MKL():
---> 34     from . import _mklinit
     35 
     36 del RTLD_for_MKL

ImportError: DLL load failed: The specified module could not be found.

### Numpy/Python version information:

numpy=1.17.4
python 3.7.4

I am using anaconda
I tried to remove and reinstall numpy

**Comment by mattip** [comment]
I think you need to activate your ananconda environment before using it to initialize paths and other environment variables around the use of MKL. Not sure this is actually connected to NumPy, you may have better luck digging around atom or ananconda forums and issue trackers. Please get back to us here if you find a solution since this kind of question comes up here occasionally.

**Comment by rossbar** [comment]
I'm going to close due to inactivity. If the problem persists, please reopen/open a new issue with updated information about the system & installation procedure.
