### ISSUE TITLE
DOC: Is `default_rng` the recommended or a convenience constuctor?

### ISSUE THREAD

**Issue by fzeiser** [numpy/numpy#15391]
In the documentation of `Generator`, it currently says under the `See all` section that `default_rng` is the _recommended_ constructor. Is it really the recommended constructor, or just a _convenience_  function?
 
 In #15367 I attempt to fix some code in another example and used initially used `default_rng(PCG64())` instead of `Generator(PCG64())`. A simple suggestion for a replacement could be this one here:

```
See also

default_rng
    Convenience constructor for Generator with PCG64 BitGenerator.
```

_Originally posted by @rossbar in https://github.com/numpy/numpy/pull/15367_

**Comment by mattip** [comment]
Is there a reason to break this out of #15367 and not to simply add it there?

**Comment by rossbar** [comment]
I agree, since this is related to discussion in #15367 , I suggest closing this PR and making the recommended change in #15367

**Comment by rkern** [comment]
FWIW, `default_rng()` is the recommended constructor for most use cases, not just a convenience. It encapsulates good patterns for passing around the RNG state.

That said, if I wanted to explicitly specify and seed the `BitGenerator`, I would use `Generator`. E.g. `Generator(SFC64())` instead of `default_rng(SFC64())`. But I would just do that once at the top of a program, not down inside of a library.

**Comment by eric-wieser** [comment]
Why does `default_rng` even take an argument if the argument-ed form is equivalent to `Generator(...)`? Or is there some situation where it's distinct?

**Comment by rkern** [comment]
```
[~]
|2> np.random.Generator(None)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-832bc790a04a> in <module>()
----> 1 np.random.Generator(None)

generator.pyx in numpy.random.generator.Generator.__init__()

AttributeError: 'NoneType' object has no attribute 'capsule'

[~]
|3> np.random.default_rng(None)
Generator(PCG64) at 0x1074CC228
```

**Comment by rkern** [comment]
I don't expect that anyone will use `default_rng(SFC64(s))` or `default_rng(PCG64(s))` with those explicit, newly-constructed `BitGenerator`s, but it might be the case that functions are passing around the `BitGenerator`s. Or they might be passing around a `Generator`. So `default_rng(generator_or_bit_gen_or_seed_or_none)`. This expands the old `check_random_state()` use cases to the case where someone is passing around a `BitGenerator` rather than a `Generator`. Which people might do in cases where they have written their own Cython code that uses `BitGenerator`s more directly.

**Comment by rossbar** [comment]
Thanks for the info @rkern. Since `default_rng()` is indeed preferred, the wording here need not be changed (though I still like the addition of "with the PCG64 BitGenerator" as it's more explicit).

Either way, I'd still recommend closing this and making any changes (if any) as part of #15367

**Comment by rossbar** [comment]
I'm going to close this - feel free to re-open if you feel things were insufficiently addressed.
