### ISSUE TITLE
SystemError: Exception set without being reported?

### ISSUE THREAD

**Issue by jbrockmendel** [numpy/numpy#15502]
In troubleshooting https://github.com/pandas-dev/pandas/issues/30886 our best guess is that somewhere in numpy an exception is being set without being reported:

```
dti = pd.date_range('2000', periods=4).append(pd.Index([pd.NaT]))
df = pd.DataFrame({"A": dti, "B": [1, 2, 3, 4, 5]})

values = df.values
values[-1, 0] = 0   #  this is effectively done inside nanops.nansum, is necessary here

>>> values.flags["F_CONTIGUOUS"]
True
>>> values.sum(0)  
TypeError: unsupported operand type(s) for +: 'Timestamp' and 'Timestamp'

values2 = np.array(values, order="C")  # like the array produced by nanops._get_values

>>> values2.flags["F_CONTIGUOUS"]
False
>>> values2.sum(0)
SystemError: <class 'TypeError'> returned a result with an error set
```

We expect to get the TypeError in both cases, hoping the numpy folks have some insight into the SystemError

**Comment by seberg** [comment]
The error reporting machinery of ufuncs is pretty bad right now (ufuncs cannot indicate an error return). In particular, the outer loop does not check for error set after every single iteration IIRC, this could be done there, or at the top of the inner loop.
In either case, it will be reason, and is the reason for the long discussion in: gh-12518 which I think we must change as soon as we touch the ufuncs the next time... Which I hope is fairly soon, but...

**Comment by mattip** [comment]
We [check for an error](https://github.com/numpy/numpy/blob/v1.18.1/numpy/core/src/umath/ufunc_object.c#L3248) and [here](https://github.com/numpy/numpy/blob/v1.18.1/numpy/core/src/umath/ufunc_object.c#L3021) so this must be hitting a different path. It might need stepping through with a debugger to see what is actually happening.

**Comment by seberg** [comment]
Yeah, but we do not necessarily abort execution right away, if the inner loop is called multiple times here, execution would continue with an error already set. Which explains the strange result.

Since the contiguity is changed, the iteration order is different, F-contious input will prefer iterating along axis 0, and thus handle all additions in the same inner loop (the array is 2D):
```
In [5]: values                                                                                                          
Out[5]: 
array([[Timestamp('2000-01-01 00:00:00'), 1],
       [Timestamp('2000-01-02 00:00:00'), 2],
       [Timestamp('2000-01-03 00:00:00'), 3],
       [Timestamp('2000-01-04 00:00:00'), 4],
       [0, 5]], dtype=object)
```
So if you iterate axis 0, you end up with 1. initialize the reduce result, and 2. do a single loop which adds [1, 2, 3, 4, 5] to each of the initialized results. It will during the first iteration and the ufunc sets the error correctly.

If the contiguity is changed, it probably prefers iterating `axis=1` (even if it does not really make sense for a length of 1, after initialization). Since the strides are not compatible (the first element is already there, so it has to be skipped), the inner-loop probably ends up being called 5 times. Each time the loop returns with an error set, but execution continues anway, meaning `Timestamp(...) + 2` is called even though `... + 1` already set an error.
I did not check it exactly, but it is the only way I can see that the two operations are different (in this particular case, making it multiple calls to the inner-loop is not strictly necessary).

**Comment by seberg** [comment]
xref gh-15411 which is the same bug, except related to casting errors.

**Comment by brandtbucher** [comment]
I'm going to spend some time digging into this.

**Comment by seberg** [comment]
Object arrays should not have this issue anymore at all.  Other dtypes/loops still have similar issues, but the machinery is now there to fix it in the future at least.

Closing, since the original issue is fixed though.
