### ISSUE TITLE
Speed differences in different ways of doing the same thing

### ISSUE THREAD

**Issue by ParikhKadam** [numpy/numpy#15561]
Just a single task. And a few ways to do it. But still, I get speed differences. So, I am just curious why this happens and need to understand it in depth.

### Reproducing code example:

For a simple task like expanding dimensions of a numpy array.

Code in jupyter noteboook.

```jupyter-notebook
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

%timeit np.expand_dims(a, axis=1)
%timeit a[:, None, :]
%timeit a[:, None, ...]
```

Outputs are:

```
3.2 µs ± 16.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
253 ns ± 5.54 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
217 ns ± 3.24 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

Haven't tried `np.newaxis` still. But this is the thing I can't understand. Why is it taking less time in one and more in another?

Thank you..

**Comment by eric-wieser** [comment]
The first one is the slowest because:
* Function calls add overhead, which for very fast operations is significant. Try wrapping your 2nd and 3rd examples in a function that takes `a` to see.
* It goes on to just use your 2nd code internally anyway, so must be slower than 2.

I'm a little surprised 3 is faster than 2, but the difference is pretty marginal.

**Comment by ParikhKadam** [comment]
@eric-wieser  For 3 being faster than 2, I supposed as placing `...` was just like telling numpy to ignore the rest of dimensions. While in 2, it needs to iterate through all the dimensions and add a new one in between. Is this correct?

**Comment by ParikhKadam** [comment]
@eric-wieser  Wrapping it in a function is still `1000000 loops, best of 3: 297 ns per loop`.

**Comment by eric-wieser** [comment]
I think you're right about `...`, it looks like it expands to `a[:,None]` and not `a[:,None,:]`. Both are equivalent so it doesn't matter.

Adding an `axis` kwarg to the function and calling it with it (but ignoring it in the function) will slow it down even more - kwarg-parsing is slow in python too.

Perhaps we're hitting `__array_function__` here?

**Comment by seberg** [comment]
Well Ellipsis is a singleton, at the very least for a slice you have to look what is inside the slice and apply that (even if that turns out being nothing in the end). At least one-third of the function call is due `__array_function__` overhead. Note that slicing is generally a *very* fats operation due to view semantics.

**Comment by seberg** [comment]
Ah, and it got much slower recently due to supporting multiple axes. I do not think I feel there is too much to be done though.

**Comment by ParikhKadam** [comment]
Got it.. Thank you..

**Comment by seberg** [comment]
I will close this. One could move the function to C, but I do not think it is worth keeping an issue about it open. Since we do not have a coordinated effort to move such utility functions in principle. So it is best to just propose it, maybe with an example why it is relevant for that function specifically.
