### ISSUE TITLE
Intersphinx to Numpy gets 403 HTTP error on CircleCI

### ISSUE THREAD

**Issue by pllim** [numpy/numpy#15564]
Hello. Perhaps as a result of #15540, we start seeing 403 HTTP error when referring to Numpy doc via `intersphinx` in our own doc build on CircleCI. We do not see this locally, on Azure Pipelines, nor Travis CI.

The Numpy intersphinx is defined in https://github.com/astropy/sphinx-astropy/blob/040b7c8a92431e1a621e9261d6185ab704bbb33f/sphinx_astropy/conf/v1.py#L50-L51 .

Sphinx has its own default User Agent (see https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-user_agent).

It is not immediately clear why this failure only happens on CircleCI for us. Is there something you can do on your side, such as whitelisting?

Hope you can advise. Thanks!

xref astropy/astropy#9947
cc @saimn 

### Reproducing code example:

https://github.com/astropy/astropy

### Error message:

Example log: https://circleci.com/gh/astropy/astropy/59676

```
Warning, treated as error:
The following HTTP Error has occurred fetching https://numpy.org/doc/1.18/: 403 (Forbidden)
```

### Numpy/Python version information:

See log above.

**Comment by rgommers** [comment]
Hmm, the SciPy intersphinx config is `'numpy': ('https://docs.scipy.org/doc/numpy', None),` and that worked fine on CircleCI on a PR from today (`https://github.com/scipy/scipy/pull/11517`)

**Comment by rgommers** [comment]
Ah, looking at the linked AstroPy issue, the problem seems to be correctly identified there. https://docs.scipy.org/doc/numpy is an AWS server, while https://numpy.org/doc is hosted on GitHub Pages with Cloudflare in front of it. 

Changing user agent string or changing from `urllib` to `requests` on the Astropy end should fix it.

**Comment by saimn** [comment]
We can try to change Sphinx's user agent, but this issue is likely to affect other packages. Unless that's only Astropy's CircleCI that is filtered, which seems unlikely, but on the other hand the scipy doc build on CircleCI does not fail with https://numpy.org/devdocs/objects.inv

**Comment by pllim** [comment]
I tried setting `user_agent` for Sphinx but it didn't work. Did I do it wrong? Please see astropy/astropy#9952

**Comment by rgommers** [comment]
Your Sphinx version is not pinned: https://github.com/astropy/sphinx-astropy/blob/master/setup.cfg#L25. Looking at the CI logs, the very latest Sphinx (2.4.1) gets installed. Most packages pin Sphinx because it breaks stuff all the time, so that probably explains why you're seeing it and others don't.

I don't have time to look into this more right now, so I'll revert the redirect.

**Comment by rgommers** [comment]
Done, so closing this and will reopen gh-15540.

**Comment by pllim** [comment]
Thanks! I am sorry for any inconvenience caused.

**Comment by rgommers** [comment]
No worries. Same here, sorry for the inconvenience!

**Comment by eric-wieser** [comment]
Note that as a result of the redirect being absent, intersphinx links will point to old releases.

We should leave this issue open, projects using the up-to-date url will continue to have this problem, right?

**Comment by bsipocz** [comment]
A note from the side. When `https://numpy.org/doc/latest/` becomes the new canonical link to the latest docs for intersphinx purposes, we can certainly change the url to that one.

**Comment by rgommers** [comment]
> I think we should leave this issue open

gh-15540 is the issue for that, no point keeping two issues around for this one issue.

> When https://numpy.org/doc/latest/ becomes the new canonical link to the latest docs for intersphinx purposes

Yep that should be the goal. It's a matter of fixing the release procedure so that stable link gets updated each time. @mattip, I can't remember if we talked about this when you created https://github.com/numpy/doc/?
