### ISSUE TITLE
np.greater not casting properly

### ISSUE THREAD

**Issue by MaximilienLC** [numpy/numpy#15595]
### Code:

```python
np.greater([1,2,3], 2, dtype=np.float32)
```
returns
```python
array([False, False,  True])
```
rather than
```python
array([0., 0., 1.])
```

**Comment by charris** [comment]
The result is correct. NumPy booleans are not integers.

**Comment by MaximilienLC** [comment]
but shouldn't `dtype=np.float32` cast to a float array?

**Comment by seberg** [comment]
The result is correct, but it is also correct that we are not always consistent about what `dtype=...` means in ufuncs. I think it might even be best if it just error out here, because there is no float32 output for `np.greater` and in general I am not sure it makes sense to just upcast.

For example, say you take a general ufunc with a `float32, float32 -> float32` loop (but none for `float64`), then just casting with `dtype=float64` would not give the precision improvement that you may think it gives.

Technically, I think you should see dtype the opposite way even maybe: As a type requirement on the inputs, becuase I think that is more useful. (I have to double check, I do not think that currently happens, but currently dtype is just ignore in some cases, and is really a bit wonky otherwise too).

**Comment by seberg** [comment]
Note that if you pass an `out=...` array with a float32 dtype, NumPy will happily do what you want:
```
In [1]: np.greater([1,2,3], 2, out=np.empty(3))                                                                         
Out[1]: array([0., 0., 1.])
```

**Comment by MaximilienLC** [comment]
Alright, thanks for the quick reply!
Have a good day!
