### ISSUE TITLE
Numpy FFT calculation giving unexpected results.

### ISSUE THREAD

**Issue by ewan1983** [numpy/numpy#15655]
When a signal's frequency falls exactly on a FFT bin, the amplitude become 0!
But if I offset the signal frequency a little bit off, the result is ok.
### Reproducing code:

Here the signal's frequency is 30
```python
import numpy as np
import matplotlib.pyplot as plt
N = 1024
Freq = 30
t = np.arange(N)
x = np.sin(2*np.pi*Freq/N*t)
f = np.fft.fft(x)
plt.plot(t, x)
plt.plot(t, f)
```
I would expect the output to have a huge spike on the 30th bin, but it's flat, as in following figure.
![freq30](https://user-images.githubusercontent.com/6269369/75406627-e2c1ea80-594b-11ea-9328-2f75635a3cb0.png)

However, if just slightly change the frequency to 30.1 to not let it fall on the exact bin, 
```python
import numpy as np
import matplotlib.pyplot as plt
N = 1024
Freq = 30.1
t = np.arange(N)
x = np.sin(2*np.pi*Freq/N*t)
f = np.fft.fft(x)
plt.plot(t, x)
plt.plot(t, f)
```
The result is correct as in following figure:
![30 1](https://user-images.githubusercontent.com/6269369/75406850-7d222e00-594c-11ea-8349-4c1285197524.png)

WHY? Is this a numpy fft implementation issue? Or is it a limitation of standard FFT algorithm?

**Comment by rkern** [comment]
When you plotted the frequency, you should have seen the following warning printed:
`ComplexWarning: Casting complex values to real discards the imaginary part`

`f` is an array of complex numbers as the FFT of a signal is, in general, complex. Because you used `sin()` instead of `cos()`, the phase is such that the FFT was all imaginary (except for some numerical noise). Try plotting `abs(f)`.

**Comment by ewan1983** [comment]
WOW~! Thank you so much for solving the mystery. I am so dumb.
