### ISSUE TITLE
Tool doc/summarize.py does not work

### ISSUE THREAD

**Issue by mwtoews** [numpy/numpy#15708]
The command-line tool `doc/summarize.py` does not currently work:
```
Traceback (most recent call last):
  File "doc/summarize.py", line 16, in <module>
    from sphinxext.phantom_import import import_phantom_module
ModuleNotFoundError: No module named 'sphinxext.phantom_import'
```
the tool depends on `sphinxext.phantom_import` which was part of `numpy/doc/sphinxext/` back in numpy 1.7.x, but has since moved on. Either this tool should be revised to work again, or considered to be removed.

**Comment by rossbar** [comment]
The consensus seems to be that this script is very rarely used and not worth the effort to update.

Others have since gone through and identified missing/undocumented functions/attributes in, for example,  #12385 and #10106 . In these cases, `doc/summarize.py` was not used. #10106 contains a short script that has been used instead of `doc/summarize.py` to generate the list of undocumented functions.

A PR to remove `doc/summarize.py` is welcome.

**Comment by WarrenWeckesser** [comment]
> A PR to remove doc/summarize.py is welcome.

See https://github.com/numpy/numpy/pull/15745
