### ISSUE TITLE
RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

### ISSUE THREAD

**Issue by hongyi-zhao** [numpy/numpy#15748]
Hi,

When I running the test on seekpath's run_tests.py, I get some warnings as follows:

`RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject`

See here for detail:
https://github.com/giovannipizzi/seekpath/issues/78#issuecomment-596982713

I use the latest numby and numpy==1.16.1 for doing the tests, both cases will give the warnings.

Any hints on this issue?

Regards

**Comment by mattip** [comment]
One of the projects you depend on use numpy's C api. When they built that project, they used an older version of numpy then you are using. Something else in your project depends on Cython. When you import NumPy via Cython, there is a  check that everything is OK.  Cython notices that one of the c-structs used by numpy's size changed between what that project was expecting and what you are using now: it gained an extra field. Since NumPy is careful with backward compatibility, this should Just Work(™). For instance, the `spglib` your project depends on also depends on NumPy, and uses a c-extension that [includes NumPy headers](https://github.com/atztogo/spglib/blob/fcad9cd816c33dfd36e3b29a8482d7320bf24327/python/_spglib.c#L38). NumPy itself ships a `*.pxd` that [marks the struct](https://github.com/numpy/numpy/blob/master/numpy/__init__.pxd#L846) as "OK to grow". This `*.pxd`  is picked up by a more modern Cython, so if all dependent libraries would update their NumPy and Cython, the warning would go away.

Until that happens, you can just tell python to ignore this warning by adding [filters](https://github.com/numpy/numpy/pull/432/files) to your code.

**Comment by hongyi-zhao** [comment]
Thank a lot for your notes.
