### ISSUE TITLE
sum() should return +inf when it fails due to rounding errors 

### ISSUE THREAD

**Issue by PBarde** [numpy/numpy#15785]
This is related to the issue https://github.com/numpy/numpy/issues/13734
but in this example it is not a difference in term of the 7th significant number, the value returned by the sum is unusable and I think an error should be raised or the result should be +inf  

### Reproducing code example:

```python
import numpy as np
a = np.ones((3, 2000, 115), dtype=np.float16)
x = a[0].sum(0)[110]
y = a[0, :, 110].sum(0)

print(x)
# 2000.0

print(y)
# 2000.0

#########

a = np.ones((3, 3000, 115), dtype=np.float16)
x = a[0].sum(0)[110]
y = a[0, :, 110].sum(0)

print(x)
# 2048.0

print(y)
# 3000.0

#########

a = np.ones((3, 6000, 115), dtype=np.float16)
x = a[0].sum(0)[110]
y = a[0, :, 110].sum(0)

print(x)
# 2048.0

print(y)
# 6000.0
```
### Numpy/Python version information:
numpy version : 1.18.2
python version : 3.8.1

**Comment by seberg** [comment]
Thanks for the report.  Please note that you have to be careful when working with float16 unless you know that they are reasonable for your use case (I even would discourage float32 unless you know it is OK/would notice when it is not). Float16 has at best around 4 decimal digits of precision IIRC, it should be very clear that you have to expect huge errors when you are working in these ranges. For example the *actual* precision at 3000 is 2 and thus less then integers!

Yes, there is a fact that along the fast axis, the actual precision of the reduction (sum) uses `float32` and only rounds at the end, while it does not do so along the slow axis (similar but different to gh-13734). You should probably simply use `dtype=np.float32` or `dtype=float64` for all reductions, and possible rethink using float32 at all, it is really meant for storage. There may be reasons to use it, but remember that it has *very* limited precision.

I am going to close this for now, since I personally doubt we will be doing much about this any time soon. It would be more a larger question of using float32 in general for all operations on float16. But I am uncertain that is even feasible. The only true solution I currently see is for you as the user to be mindful of the extremely limited precision of float16. Please feel free to comment though, we can very much reopen.
