### ISSUE TITLE
Add documentation page on the internal representation of NumPy arrays

### ISSUE THREAD

**Issue by Irio** [numpy/numpy#15793]
In my understanding, based on the definitions in [NEP 44](https://numpy.org/neps/nep-0044-restructuring-numpy-docs.html), my proposal is to make an Explanation page around the topic.

I am aware about two places in the docs mentioning this topic for NumPy users: the [Quickstart tutorial](https://numpy.org/devdocs/user/quickstart.html#quickstart-copies-and-views) and [NumPy: the absolute basics for beginners](https://numpy.org/devdocs/user/absolute_beginners.html#how-to-create-an-array-from-existing-data). The former, starts with the following:

> When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners.

Sometimes, even after five years using NumPy, I have to go with my gut feeling to predict if an operation will trigger a copy in the underlying data. I'd love to have an official documentation page for helping people build a better mental model of this.

Some questions and ideas:

* What does an advanced user of NumPy needs to know about the underlying data structure?
* What are the operations that will cause data to be moved/copied in memory?
* How to tell if Numpy did or will copy data in an operation?
* When is recommended to choose between creating a view or making a copy?
* May include or link to a good overview of indexing
* Shallow copy vs deep copy
* Cite the classic [`SettingWithCopyWarning` exception in Pandas](https://stackoverflow.com/questions/20625582/how-to-deal-with-settingwithcopywarning-in-pandas), which I believe is caused by not having a good understanding of this very same subject

**Comment by rgommers** [comment]
Yes, this'd be great! Agree that this is an Explanation

**Comment by rossbar** [comment]
Just a quick addition: some of the proposed material is also covered in [NumPy Internals](https://numpy.org/devdocs/reference/internals.html) in the reference guide. This material is pretty dense so I definitely agree that a distillation to a NEP44-style Explanation with a more user-centric theme would be very nice. I mention it here so that it can be drawn upon (and hopefully kept somewhat synced with) if/when anyone undertakes the Explanation doc.

**Comment by mrityagi** [comment]
@melissawm @rgommers , I have tried to analyse it , this issue can be resolved if there is an FAQs section in the documentation , where we'll give a brief eplanation to the questions like these along with the ones which can be sourced from Stack overflow , these type of questions which may sound trivial or basic can sometime be a lot of pain in the workflow for even an experienced developer ,if we look upon this [link](https://stackoverflow.com/questions/tagged/numpy?sort=frequent) we'll see that issues of this type are widespread , I'll try to structure a FAQs demo page where questions of such nature can be documented so that we can resolve issues like this which may occur in future too

**Comment by melissawm** [comment]
Hi @mrityagi , I don't think we have considered a FAQ format for this, initially we thought about an ["Explanation"](https://numpy.org/neps/nep-0044-restructuring-numpy-docs.html#status-and-ideas-of-each-type-of-doc-content) document. However, I do think that the questions might be a good guide into which content to cover, and this might end up being an excellent guide to the internals of NumPy. How does that sound to you?

**Comment by mrityagi** [comment]
@melissawm  yeah I think Explanation/Questions sounds more reliable and a more trustworthy word for NumPy , infact we are on the same page with thought process to structure docs like an excellent guide to internals of NumPy . I have tried to give it a [structure](https://docs.google.com/document/d/1q-BYO-GqlBIsMizCzjbANORz6OOaC-6oEzuE1_HqJl4/edit#bookmark=id.2vkitb6djmq0) which can be useful for such issues . Infact I totally agree with you , the need to index them into which content to cover say there can be a topic named Copies and  Views , under this we can give explanations like No Copy vs Shallow Copy (ie Views) , Shallow Copy (ie views)  vs Deep Copy .
Similarly for arrays indexing and other stuff , i mean we need to order and Group(categorize) these Explanations like above .
This way we are basically answering questions , doubts whatever we choose to call them in a structured good guide , because a person coming to this page should know with just a glimpse whether we have an answer / explanation to his doubt  by merely looking at the names of the topics covered .
This way our objective of giving solutions for popular queries will surely be covered , What do u say ?

**Comment by melissawm** [comment]
Hello, @mrityagi - I think we talked about this in the documentation meeting but I'm not sure if you intend to follow up on this? If not maybe @Mukulikaa can pick this up. Thanks!

**Comment by Mukulikaa** [comment]
I think this issue can be closed by gh-19791 for now. There is also a separate tracking issue (gh-20112) for future work on this topic.

**Comment by melissawm** [comment]
Agreed, thanks for flagging!
