### ISSUE TITLE
a -= b and a = a - b inconsistency

### ISSUE THREAD

**Issue by apatsekin** [numpy/numpy#15820]
Operators `isub` and `sub` result to different data types under exactly same scenarios. Is it a feature or a bug?

### Reproducing code example:

```python
import numpy as np
a = np.asarray([10], dtype=np.float32)
a -= [1.0]
t3 = a.dtype
a = a - [1.0]
t4 = a.dtype
print(t3 == t4)
```

### Error message:

```
t3 -- np.float32
t4 -- np.float64
```

### Numpy/Python version information:

Tested on 1.14.5, 1.18.2

**Comment by rkern** [comment]
This is expected and by design. When you use `-=`, you are requesting an in-place modification of the left-hand-side object, as permitted by the Python language reference. The rules of numpy dtype promotion don't allow an array to change its dtype. When you modify it in-place, it remains the same dtype. `a -= [1.0]` can roughly be translated to `a[:] = a - [1.0]` to account for the in-place modification.

**Comment by rkern** [comment]
For an example where these semantics are very useful, consider image processing, where we sometimes have to deal with large floating-point images. For most image processing tasks, the input and output data has quite low precision. We usually take `uint8` or `uint16` pixels. `float64` is typically overkill, and the memory saved by restricting the floating-point intermediates to `float32` is substantial. However, because Python and numpy default to `float64` numbers so frequently, it is a constant struggle to keep intermediate arrays `float32`. Using in-place operations (that don't modify the dtype of the array) is an essential strategy to reduce intermediates and keep them from naturally popping up to `float64` unintentionally.
