### ISSUE TITLE
random.choice ignoring masked values

### ISSUE THREAD

**Issue by lanadaquenada** [numpy/numpy#15851]
I believe this is a bug, or if it isn't, I couldn't find anything in the documentation that says it should act this way. 

It seems like random.choice is ignoring the masked values. As you can see in the code below, the output of random.choice gives values that have been previously masked on the array.

### Reproducing code example:

```python
import numpy as np
x = np.linspace(0,100,100)
xmask = np.ma.masked_where(x>75,x)
print(np.nanmax(xmask))

random_choice = np.random.choice(xmask,50)
print(np.nanmax(random_choice))
```

Output:

> 74.74747474747475
> 96.96969696969697

I've tried this several times, and the maximum value of random_choice always seems to be between 90 and 100.

### Numpy/Python version information:

1.18.1 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]

**Comment by rkern** [comment]
Most functions implemented in C/Cython, like `choice()`, convert array-like inputs into plain `ndarray`s and operate on them using `ndarray` semantics. Taking masked arrays into account is not really the default. You can probably assume that if a function's docstring _doesn't_ mention masked arrays, it's probably ignoring the mask. That's why there are so many duplicate functions in the `numpy.ma` namespace to specifically take care of the mask.

**Comment by lanadaquenada** [comment]
I see. Thanks for the reply.

**Comment by rgommers** [comment]
Question was answered, so closing. Thanks @lanadaquenada and @rkern
