### ISSUE TITLE
Odd behavior of ufunc.reduce when arr is broadcast to match `where`

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15864]
I wouldn't say this behavior is broken, but it's surprising:

```python
>>> np.add.reduce([[1, 2]], where=np.ones((1, 2), dtype=bool), axis=())
array([[1, 2]])  # ok
>>> np.add.reduce([[1, 2]], where=np.ones((3, 2), dtype=bool), axis=())
array([[3, 6]])  # surprise
```

Essentially, it seems that if `where.ndim > arr.ndim`, then all the dimensions of `where` not present in `arr` are also summed over.

I was expecting one of these things

* The output to be broadcast, so the result would have been `array([[1, 2], [1, 2], [1, 2]])`
* An error, as `where` could not be broadcast to match `arr`
* This to be documented, if @mhvk intended it

Came up whilst reviewing #15852

**Comment by seberg** [comment]
I think it is a bit of fallout related to the whole way broadcasting currently works (i.e. the PRs me and Marten looked at a long time ago) that nditer really should list a few operands which do broadcast instead of generally enabling it.
Seems slightly related to gh-15139 in that regard. I would be for going to an error here. If easy enough through a deprecation.

**Comment by mhvk** [comment]
Definitely unintended! Agreed with @seberg that this probably can be fixed together with his work on broadcasting outputs.

**Comment by seberg** [comment]
Closing, the linked PR is merged a long time ago, and the second case now errors.
