### ISSUE TITLE
documentation of rollaxis

### ISSUE THREAD

**Issue by BruceMaggs** [numpy/numpy#15926]
Hi,

On the web page https://docs.scipy.org/doc/numpy/reference/generated/numpy.rollaxis.html, where you document the rollaxis function, you first say:

Roll the specified axis backwards, until it lies in a given position.

then you write:

start : int, optional
The axis is rolled until it lies before this position. The default, 0, results in a “complete” roll.

There seems to be a contradiction between "lies in a given position" and "lies before this position", or at least the wording is confusing.   Also, it's not clear what a "complete" roll means.  I would think that a complete roll meant a 360-degree roll, which would be equivalent to no roll at all, but I don't think that's what you mean here.

As far as I can tell, "lies in a given position" is what the function really does.

Thanks,

Bruce Maggs

### Reproducing code example:

import numpy as np

>>> a = np.ones((3,4,5,6))
>>> np.rollaxis(a, 3, 1).shape
(3, 6, 4, 5)
>>> np.rollaxis(a, 2).shape
(5, 3, 4, 6)
>>> np.rollaxis(a, 1, 4).shape
(3, 5, 6, 4)

**Comment by anirudh2290** [comment]
@BruceMaggs thanks for bringing this up ! The rolling backwards wording doesnt make much sense to me either.

```
>>> np.rollaxis(a, 1, 3).shape
(3, 5, 4, 6)
```

What I expected to happen
```
(3,4,5,6)
v
(4,3,5,6)
v
(6,3,5,4)
v
(6,3,4,5)
```


From the code, the provided axis seems to be removed from list of axis (axes) and inserted into the position start if start <= axis, and inserted into start - 1 pos if start > axis. The rolling backwards wording probably only applies if start <= axis. 

Maybe we should change the documentation to make it similar to moveaxis, to capture that we are "moving axis positions with source being the axis arg, and destination being start if start <= axis and start - 1 if start > axis. " One downside to this is that the rollaxis name may be confusing to users since this is very similar to moveaxis.

cc @charris

**Comment by guilhermeleobas** [comment]
Also, I think the statement `The default, 0, results in a "complete" roll.` is wrong.

```python
>>> np.rollaxis(a, 0, 0).shape
(3, 4, 5, 6)
>>> np.rollaxis(a, 1, 0).shape
(4, 3, 5, 6)
>>> np.rollaxis(a, 2, 0).shape
(5, 3, 4, 6)
>>> np.rollaxis(a, 3, 0).shape
(6, 3, 4, 5)
```

**Comment by eric-wieser** [comment]
Note that this was reported before in #9473, which motivated us to change the docs to recommend against using it.

**Comment by guilhermeleobas** [comment]
@eric-wieser, given that `np.moveaxis` exists, is it possible to deprecate this one now? `np.rollaxis` is not used internally on NumPy codebase.

**Comment by BruceMaggs** [comment]
Since people sometimes have to look at old code and/or might decide to replace an existing call to rollaxis with a call to moveaxis (as recommended) it would be helpful to have correct documentation for how rollaxis works...

**Comment by eric-wieser** [comment]
@guilhermeleobas: That was discussed but rejected in #9475

@BruceMaggs: Indeed.
