### ISSUE TITLE
Uninstall numpy

### ISSUE THREAD

**Issue by dc123k** [numpy/numpy#15956]
I'm running Anaconda3-2020.02 in Windows 10 and I have been having a lot of problems with numpy. At the end, installing it with pip instead of conda look to have work but when I tried to install matplotlib with conda (with pip it didn't work) the problem with numpy came back.

I'm tring to uninstall numpy with conda and pip and it says that numpy is not installed but with “conda list” it appears.

Many thanks

The error message

C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/0204752/Desktop/Python/Dias Tipo/graficar npy.py", line 3, in <module>
    import pandas as pd
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\ProgramData\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.
Original error was: DLL load failed: No se puede encontrar el módulo especificado.

**Comment by seberg** [comment]
You should probably use the conda version. Also since you are using pycharm, did you ensure that your conda environment is actived, IIRC that is a common mistake?
This is an issue with your anaconda, and specifically you seems to be using the intel version which gives an additional warning here (likely unrelated). I suggest you look for old issues of others using PyCharm, you may find something there, maybe someone here knows quickly as well, but I do not and it is not a NumPy issue as such.

**Comment by rossbar** [comment]
Since this error was originally reported, a new article has been [added to the documentation](https://numpy.org/devdocs/user/troubleshooting-importerror.html) to cover some common causes of this error.

I will close this now due to inactivity - if the issue persists, please see the linked document paying special attention to the sections on `conda` environment setup & management
