### ISSUE TITLE
Question about numpy ndarray documentation

### ISSUE THREAD

**Issue by anirudh2290** [numpy/numpy#15979]
This [document](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html) states the following : "It does not generally hold that self.strides[-1] == self.itemsize for C-style contiguous arrays or self.strides[0] == self.itemsize for Fortran-style contiguous arrays is true. Is this true only with the environment variable ?"

I am wondering when this statement will be False. 
I am guessing this has to do with point 1 in the doc:
```
If self.shape[k] == 1 then for any legal index index[k] == 0. This means that in the formula for the offset n_k = 0 and thus s_k n_k = 0 and the value of s_k = self.strides[k] is arbitrary.
```
which seems to be applied only when `NPY_RELAXED_STRIDES_CHECKING=1`. I haven't been able to reproduce such a scenario. Does the statement mean it resorts to undefined behavior and users should not count on this statement being True if NPY_RELAXED_STRIDES_CHECKING=1 ?

Raising this here, to see if there is a potential for doc improvement. If this is the wrong forum for such a question, please let me know.

**Comment by seberg** [comment]
`NPY_RELAXED_STRIDES_CHECKING` is pretty much always true, it still exists, but really I do not think anyone ever should be disabling it. (The documentation is already updated to that effect).

What this means is this:

```
arr = np.arange(100).reshape((10, 10))[::100, :]
print(arr.flags)
print(arr.strides)
# contiguity may suspect this is True, but here it is not:
arr.strides[-1] * arr.shape[-1] != arr.strides[-2]
```
in particular also for 1-D arrays with only one element (I am not quite sure if they would run into this before though).

This is a problem, because there is a more extreme case:
```
arr = np.arange(10).reshape((10, 1))[:, ::100]  # slicing still modifies the strides here
print(arr.flags)
print(arr.strides)
arr.strides[-1] != arr.itemsize  # This is True for a contiguous array!
```
In this case you can access all array elements correctly using `arr.itemsize` as stride, but this does not require that this is actually true.

**Comment by anirudh2290** [comment]
I understand now. Thank you for the detailed explanation ! Closing.
