### ISSUE TITLE
np.lexsort silently accepts illegal axis arguments

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#15999]
### Reproducing code example:

```python
import numpy as np
>>> np.lexsort((np.arange(1),), axis=3)
array([0], dtype=int64)

>>> np.lexsort((np.arange(2),), axis=3)
AxisError: axis 3 is out of bounds for array of dimension 1
```

### Numpy/Python version information:
52c9e6f

Introduced in the fix for #14228

**Comment by vrakesh** [comment]
Looked at this, 
```c
    /* Now we can check the axis */
    nd = PyArray_NDIM(mps[0]);
    if ((nd == 0) || (PyArray_SIZE(mps[0]) <= 1)) {
        /* empty/single element case */
        ret = (PyArrayObject *)PyArray_NewFromDescr(
            &PyArray_Type, PyArray_DescrFromType(NPY_INTP),
            PyArray_NDIM(mps[0]), PyArray_DIMS(mps[0]), NULL, NULL,
            0, NULL);

        if (ret == NULL) {
            goto fail;
        }
        if (PyArray_SIZE(mps[0]) > 0) {
            *((npy_intp *)(PyArray_DATA(ret))) = 0;
        }
        goto finish;
    }
```

Is it because there is no axis check when the array is empty or has one element?  
Should we check for axis when the element size is 1 ?

```python
 np.lexsort((np.arange(1).reshape(1,1,1),), axis=4)
array([[[0]]])
```

This also works

While it shouldn't. I guess this bug is older than the above mentioned issue. 

If the array is empy axis check do

Am I thinking about this correct?? Willing to work on a PR to fix.

**Comment by eric-wieser** [comment]
> Is it because there is no axis check when the array is empty or has one element?
> Should we check for axis when the element size is 1 ?

Yes and yes. Moving the current axis check to before that special case would likely fix the issue.
