### ISSUE TITLE
Change in bool type coersion?

### ISSUE THREAD

**Issue by LevN0** [numpy/numpy#16023]
In all past versions of NumPy dating back at least a decade, using astype(bool) on a str of '0' obtained False and on any other integer as True. Now the result is always True. 

### Reproducing code example:

```python
import numpy as np

np.asarray(['0', '1']).astype('bool')
```

Before 1.18.3:  
     array([False,  True], dtype=bool)

After 1.18.3: 
    array([True,  True], dtype=bool)

### Numpy/Python version information:

1.18.3 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]

### Other Thoughts

Seems to have been introduced by  #15929. The prior behavior was logical, and saved execution time doing multiple type conversions.

**Comment by eric-wieser** [comment]
Related to #9875.

**Comment by seberg** [comment]
Dang, yes, booleans are so hopelessly inconsistent here, and I did not think of them, too bad we did not have tests for this :(. Aside from the point release change, which is very unfortunate... 

I somewhat think we should probably just put a `FutureWarning` on it and change it as fast as reasonably possible. Being out of sync with ourselves and especially Python doesn't help anyone, because it seems like there may be good logic here, when the logic is just inconsistent.
