### ISSUE TITLE
Clarification about NEP 40: NumPy Scalars and Type Hierarchy

### ISSUE THREAD

**Issue by anirudh2290** [numpy/numpy#16035]
> As a side note to the above datatype implementation: unlike the datatypes, the NumPy scalars currently do provide a type hierarchy

Got a little confused by the statement above given that issubclass(np.int64, np.integer).
Did it mean to say `unlike the python datatypes` or `unlike the other datatypes` instead ?

**Comment by seberg** [comment]
Well, the `dtype` does not have a type hierarchy. `issubclass(np.int64, np.integer)` are the scalar types. `dtype` either uses `issubdtype` which effectively uses `issubclass(np.int64, np.integer)`, or the `dtyp.kind` argument, which is just a character signalinga "category" which is equivalent to `np.integer` for scalars.

I am not sure about how NEP 40 phrases this. Since it is possible to argue that it is a positive thing if the dtype does not have such a hierarchy.
Anyway, I am sure the text can use some clarification here.

**Comment by anirudh2290** [comment]
Thanks a lot @seberg for the quick response !

> Well, the dtype does not have a type hierarchy. issubclass(np.int64, np.integer) are the scalar types. dtype either uses issubdtype which effectively uses issubclass(np.int64, np.integer), or the dtyp.kind argument, which is just a character signalinga "category" which is equivalent to np.integer for scalars.

I guess my confusion stems from the fact that I considered scalar types to be dtype objects, which doesnt make much sense in hindsight (https://numpy.org/devdocs/reference/arrays.dtypes.html). 


> Anyway, I am sure the text can use some clarification here.

Will see if i can clarify better.

**Comment by seberg** [comment]
Well, its the conundrum... Of course from a type (theory, not class) point of view, the elements of an array of `>int8` and `<int8` *are* obviously of the same type `np.int8` scalars. Maybe you could say the dtype only describes the type (i.e. scalar type/class) to the array.
Which is also why you can argue that the dtype itself doesn't need to have a hierarchy. It doesn't actually need to serve the purpose of a type (with a hierarchy) since it is strictly associated to a scalar type/class that already has these properties.

Thats kind-of what my last email on the list is about... And no, I do not know for certain what is the "right" way to see it :).

**Comment by rossbar** [comment]
I had never understood the distinction between array scalars and dtypes (from the perspective as a user), so this was a nice clarification. Perhaps we could add an aside to NEP 40? Other than that, I think @seberg's explanation sufficiently answers the question so maybe we can close this.

**Comment by anirudh2290** [comment]
Agreed @rossbar ! Closing.
