### ISSUE TITLE
BUG: Creating polynomials from existing polynomial instances incorrectly sets coefficients

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#16071]
In the polynomial package (`np.polynomial`), if one attempts to create a new polynomial instance from an existing instance, the *entire* original polynomial instance is stored in the `coef` attribute of the new polynomial instance (in an object array) without any error or warning being raised:

### Reproducing code example:

```python
>>> p = np.polynomial.Polynomial([1, 2, 3])
>>> p # expected
Polynomial([1., 2., 3.], domain=[-1,  1], window=[-1,  1])
>>> p2 = np.polynomial.Polynomial(p)
>>> p2 # p2.coef is an object array containing p
Polynomial([Polynomial([1., 2., 3.], domain=[-1,  1], window=[-1,  1])],
      dtype=object, domain=[-1,  1], window=[-1,  1])
```

Some potential solutions come to mind to prevent this from happening:
 1. Disallow creating new polynomial instances from existing polynomial instances. This may break backwards compatibility
 2. Construct the new polynomial instance from the *state* (i.e. `coef`, `domain` and `window` attributes) of the original polynomial.

### Numpy/Python version information:

Python version: 3.8.2
NumPy version: 1.18.3

**Comment by charris** [comment]
Hmm, I'll need to think for a bit to decide if that is a bad thing :)  Multivariable polynomials can be regarded as polynomials in one variable having polynomial coefficients. That is how the multivariable evaluations take place conceptually. We also need object coefficients for such things as Fraction, Decimal, or extended precision floats, which is why floating point numbers, often unrepresentable, are avoided in favor of integers in the evaluations.

Thinking about it, object coefficients probably need to be dealt with for pretty printing.

**Comment by anirudh2290** [comment]
Thats a good point @charris . That makes me wonder if the np.polynomial.Polynomial in numpy was designed for the multivariable use case. 
```
>>> x = np.polynomial.Polynomial([1, 2, 3])
>>> x1 = np.polynomial.Polynomial([4, 5])
>>> x2 = np.polynomial.Polynomial(x, x1)
>>> x2 = np.polynomial.Polynomial([x, x1])
>>> x
Polynomial([1., 2., 3.], domain=[-1,  1], window=[-1,  1])
>>> x2
Polynomial([Polynomial([1., 2., 3.], domain=[-1,  1], window=[-1,  1]),
       Polynomial([4., 5.], domain=[-1,  1], window=[-1,  1])],
      dtype=object, domain=[-1,  1], window=[-1,  1])
>>> polyval(1, x2.coef)
Polynomial([5., 7., 3.], domain=[-1.,  1.], window=[-1.,  1.]) #assumes both polynomials functions of same variable
```

The above behavior makes it inconsistent with the behavior to create a polynomial from an existing polynomial.

I don't see anything from the docs for the polynomial api atleast, which indicates that a particular polynomial is a function of a particular variable. In absence of this information, at least from the docs it feels like it was designed for the single variable use case.

**Comment by rossbar** [comment]
Thanks for weighing in @anirudh2290 , those are good points. Re: multivariate polynomials, I agree that the docs for the polynomial package do no mention support for multivariable polynomials, though they don't specifically discount them either (unlike `np.poly1d` from the "old" polynomial API, which has `1d` in the name).

One thing to be careful of: the `polyval` that is in the main numpy namespace (i.e. `np.polyval`) is actually the `polyval` from the "old" polynomial module `np.lib.polynomial`. There is a `polyval` associated with the new polynomial package, i.e. `np.polynomial.polynomial.polyval`. In fact, after careful inspection, there are also 2d and 3d functions defined, e.g. `np.polynomial.polynomial.polyval[2,3]d`. *However* there is not currently any support for multivariable polynomials through the *convenience classes*, which are the preferred interface for the `np.polynomial` package. In other words, there is some support for evaluation of multivariable polynomial expressions, but it is not discoverable and has not been added to the preferred (class-based) interface.

If there are plans in the future to support multivariable polynomials with the convenience classes, then indeed some additional thought will be needed to define how the `coefs` will be stored and what the constructor and evaluation will look like. I don't know what the plans are for adding support for multivariable polynomial expressions to the `np.polynomial` package - maybe @charris has some insight on that front.

**Comment by anirudh2290** [comment]
> There is a `polyval` associated with the new polynomial package, i.e. `np.polynomial.polynomial.polyval`

Thanks @rossbar for the inputs. Yes, I used `from numpy.polynomial.polynomial import polyval` in above example.

**Comment by charris** [comment]
Note that there are easy ways to get copies
```
In [1]: from numpy.polynomial import Polynomial as P                            

In [2]: p = P([1,2,3])                                                          

In [3]: p1 = p.copy()                                                           

In [4]: p2 = copy(p1)
```
The idea for Polynomial coefficients was that they could be pretty arbitrary. Some things are specialized, roots (needs doubles), division requires a field, other basis require arithmetic with integers, but the idea was that folks who wanted restrictions, say to Fractions, would subclass.

**Comment by WarrenWeckesser** [comment]
The docstring of `ABCPolyBase` says this about `coef`, the first argument of the constructor:

```
coef : array_like
    Series coefficients in order of increasing degree, i.e.,
    ``(1, 2, 3)`` gives ``1*P_0(x) + 2*P_1(x) + 3*P_2(x)``, where
    ``P_i`` is the basis polynomials of degree ``i``.
```

The polynomial classes, however, are not array_like.  They have a length, but they cannot be indexed.  It looks like anything passed that is not actually array-like (and that doesn't cause an error with the constructor code) will be converted to a single coefficient stored in an object array, e.g.

```
In [68]: p = Hermite({3, 4, 'foo'})

In [69]: p.coef                                                                              
Out[69]: array([{'foo', 3, 4}], dtype=object)
```

I don't know if the constructor should be modified to handle polynomial instances as a special case, but these days special cases make me nervous (Zen of Python and all that).  It might be simpler to stick with the current behavior, and make clear that *anything* passed in will be treated as the coefficients of the newly created polynomial, even if the argument is another polynomial instance.

To use the constructor to create a new instance from an existing one, one can pass the attributes as the arguments...
```
In [131]: p = Polynomial([3, 4, 5])

In [132]: h = Hermite(p.coef, domain=p.domain, window=p.window)

In [133]: h                                                                                  
Out[133]: Hermite([3., 4., 5.], domain=[-1.,  1.], window=[-1.,  1.])
```
but this is probably not a good idea in general, because when the classes are different, the two objects do not represent the same polynomial:
```
In [134]: p(0.5)
Out[134]: 6.25

In [135]: h(0.5)
Out[135]: 2.0
```

As @charris noted, the `copy` method can be used to create a copy. However, I think the motivation for this issue is to eventually allow changing an attribute while making the new object (such as the not-yet-implemented `symbol` to be use by the polynomial).

Another existing method for creating a new polynomial from an existing one is to use the `cast` method, e.g.

```
In [136]: p = Polynomial([3, 4, 5])

In [137]: h = Hermite.cast(p)

In [138]: h
Out[138]: Hermite([5.5 , 2.  , 1.25], domain=[-1.,  1.], window=[-1.,  1.])
```
These objects represent the same function:
```
In [139]: p(0.5)                                                                             
Out[139]: 6.25

In [140]: h(0.5)                                                                             
Out[140]: 6.25
```

That's true even if, for example, the domain is changed:

```
In [141]: h2 = Hermite.cast(p, domain=[0, 1])                                                

In [142]: h2(0.5)                                                                            
Out[142]: 6.25
```

So if a future enhancement adds a symbol, I guess the way to create a new instance with a different symbol would be to add the `symbol` argument to the `cast` method. Then, for example, to convert a `Polynomial` instance `p` to a `Hermite` instance with symbol `t`, one would write

    h = Hermite.cast(p, symbol='t')

**Comment by rossbar** [comment]
Thanks so much @WarrenWeckesser & @charris for your detailed insights. @WarrenWeckesser , you are indeed right that this (along with #16108 and the associated issues) are inspired by thinking about what is the best way to change attributes other than the `coef` on the polynomial instance (i.e. the `domain`, `window`, or a proposed `symbol` for instance).

The point about `cast` is well-taken - other methods such as `convert` are intended to handle changing these attributes as well. These methods are entirely sufficient, but IMO are a little tricky because of how overloaded (in the general sense) they are. For instance, the `convert` method can be used to change the `domain` or `window` of a polynomial (and apply the corresponding transformation to the `coef`), linearly map the `coefs` from the `domain` -> `window` (if they differ), or to change the *kind* of polynomial, e.g. converting a `Chebyshev` instance to a `Hermite` instance (again, accounting for changes in the `coef` do to the change in basis). All that said, the point made above about being explicit (`p2 = Polynomial(p.coef, window=p.window, domain=p.domain)` instead of `p2 = Polynomial(p)`) is a good one.

The proposal in this PR also draws from the way `np.poly1d`, which has `isinstance` checks in `__init__` in order to handle creation of new instances both from `array-like`s and from `poly1d` instances; though perhaps the decision *not* to go that route with the `polynomial` package was intentional!

I think @WarrenWeckesser makes a strong case above for not modifying the constructor as a means for creating polynomial instances with different `domain` and `window` attributes, so I'm inclined to close this. Thanks again, all, for taking a close look at the proposal!

**Comment by rossbar** [comment]
I meant to close the PR associate with this (gh-16072), not the issue. Re-opening as a collection point for any future discussion.

**Comment by rossbar** [comment]
I think the arguments this were pretty strong, so I will close this now.
