### ISSUE TITLE
Unexpected behaviour when using dot-product 

### ISSUE THREAD

**Issue by canbooo** [numpy/numpy#16070]
For certain arrays, using dot-Product between a 'matrix' and a 'vector' is different than dot-product between the first row of the 'matrix' and the vector. I can demonstrate it in a specific example, but i have faced other arrays with the same behavior.  Not sure if related to [#9656](https://github.com/numpy/numpy/issues/9656#issue-255508280).

### Reproducing code example:
First unzip arrays.zip to get the arrays a and k1.
[arrays.zip](https://github.com/numpy/numpy/files/4531761/arrays.zip)
Now running the following code
```python
import numpy as np
a = np.load("a.npy")
k1 = np.load("k1.npy")
k2 = np.array([k1.ravel(), k1.ravel(), k1.ravel()])

print("diff k1 k2[0]", np.sum(k1 - k2[0,:]))
print("diff k1 k2",np.sum(k1-k2))
print("diff k1.dot(a) k2.dot(a)[0]",k1.dot(a) - k2.dot(a)[0])
print("diff k1.dot(a) k2.dot(a)", (k1.dot(a) - k2.dot(a)).ravel())

a_ld = np.array(a, dtype=np.longdouble)
k1_ld = np.array(k1, dtype=np.longdouble)
k2_ld = np.array(k2, dtype=np.longdouble)

print("diff k1 k2[0]", np.sum(k1_ld - k2_ld[0,:]))
print("diff k1 k2", np.sum(k1_ld - k2_ld))
print("diff k1.dot(a) k2.dot(a)[0]", k1_ld.dot(a_ld) - k2_ld.dot(a_ld)[0])
print("diff k1.dot(a) k2.dot(a)", (k1_ld.dot(a_ld) - k2_ld.dot(a_ld)).ravel())
```
outputs
```
diff k1 k2[0] 0.0
diff k1 k2 0.0
diff k1.dot(a) k2.dot(a)[0] [[1.1920929e-06]]
diff k1.dot(a) k2.dot(a) [1.1920929e-06 1.1920929e-06 1.1920929e-06]
diff k1 k2[0] 0.0
diff k1 k2 0.0
diff k1.dot(a) k2.dot(a)[0] [[1.1920929e-06]]
diff k1.dot(a) k2.dot(a) [1.1920929e-06 1.1920929e-06 1.1920929e-06]
```
where i would have expected to see 0 overall. The actual result is  -0.3178365230560303 with floating point arithmetic.

### Numpy/Python version information:
```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.18.1 3.8.2 (default, Apr 14 2020, 19:01:40) [MSC v.1916 64 bit (AMD64)]
```

But also when using

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.17.4 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
```

**Comment by seberg** [comment]
On computers `(a + b) + c` is not the same as `a + (b + c)` and linear algebra operations (in particular dot), but also most other NumPy functions will reorder the operations to ensure they are as fast as possible.
Thus, when you run such code on different machines or with input differing, e.g. in shape, you can typically only expect results that are identical *within the general numerical precision of the naive addition*.

This is almost certainly the case here, your arrays are probably just large. See also: https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html
In particular note that large errors can happen for example because `ver_large_number + tiny_number == very_large_number`, and you can sometimes get large numbers intermediate results.

Closing, if you think there is an actual issue beyond the normal limited numerical precision, please note so. But I doubt it.

**Comment by canbooo** [comment]
I was just surprised that changing the data type had no influence on the outcome which is why i discarded the idea of numerical precision error. Still thanks for the interesting link and your response.

**Comment by seberg** [comment]
Oh, I did not realize the question about `longdouble`. Chances are you are on windows and the C `long double` is actually identical to `double` on windows. I am not 100% sure whether it will hit the fast blas paths (which could lead to different results), but I assume so.

Yes, you should expect improved precision on most systems that are not windows/MSVC compiled (and thus have a long double that maps to some form of extended precision) linux systems.

**Comment by canbooo** [comment]
> 
> 
> Chances are you are on windows and the C `long double` is actually identical to `double` on windows.

This is indeed the case and now it all makes sense. Now I fully agree with closing the issue. Thanks again.
