### ISSUE TITLE
Cannot import numpy

### ISSUE THREAD

**Issue by ryan-j-hope** [numpy/numpy#16087]
I have Python and numpy installed through Anaconda. My operating system is OSX 10.14.6. I do appear to have multiple copies of Python installed, 3.7 and 2.7. 

I get an error for trying to import Pandas, stating that required dependancies (numpy) were unable to import. See code:
import pandas as pd

runfile('/Users/ryanjhope/.spyder-py3/temp.py', wdir='/Users/ryanjhope/.spyder-py3')
Traceback (most recent call last):

  File "/Users/ryanjhope/.spyder-py3/temp.py", line 1, in <module>
    import pandas as pd

  File "/Users/ryanjhope/anaconda3/lib/python3.7/site-packages/pandas/__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)

ImportError: Unable to import required dependencies:
numpy:

**Comment by ardianozi18** [comment]
same problem, nitip sendal bro

**Comment by seberg** [comment]
Please check your PATH, and PYTHONPATH as the import error should be asking you to do. Since you are within spyder, you may also need to check that setup I suppose. In general, for anaconda: Please make sure that you have activated your conda environment. See also the conda user-guide

If you find a solution not covered by that, please do comment here. This is not a NumPy issue as such, but it is good to know the common solutions so that others can find them easier.

**Comment by ryan-j-hope** [comment]
Okay, I ran the following:

`pip install --upgrade --ignore-installed --install-option '--install-data=/usr/local' numpy`

Then I could import numpy. When I re-ran my original code which called for a pandas import I received a number of other pandas dependancy problems. So I uninstalled and re-installed Anaconda and now my code works.

**Comment by mattip** [comment]
Glad it works now. Closing.
