### ISSUE TITLE
How can I contribute translations to the numpy project?

### ISSUE THREAD

**Issue by nokcharathae** [numpy/numpy#16103]
How can I contribute translations to the numpy project?

**Comment by eric-wieser** [comment]
I assume you're asking about documentation translations?

**Comment by nokcharathae** [comment]
YES! About documentation or comment

**Comment by rgommers** [comment]
Hi @nokcharathae. We will soon start accepting translations for the new numpy.org website: https://github.com/numpy/numpy.org/issues/55. We are not in a position to be able to accept translations for NumPy documentation unfortunately, that's way too much maintenance effort.

If you do have a separate translation of all or a good part of the NumPy docs, we could link to it from the numpy.org site (visible for people using the relevant language).

**Comment by rossbar** [comment]
@nokcharathae just a quick ping - there is a NumPy sprint happening this weekend and getting the translations for the website up-and-running is one of the topics. There is a lot of activity on this issue now in case you're interested in revisiting - the linked issue is a good place to start!

**Comment by rgommers** [comment]
Agreed, help at https://github.com/numpy/numpy.org/issues/55#issuecomment-657137777 would be great. We're starting with a few of the big languages (Chinese, Japanese, Korean, Portuguese, Spanish) and will open it up soon to other languages that have enough speakers and volunteers. 

I'll close this, because the question is answered and we're good to get started!
