### ISSUE TITLE
problem using complex() with arrays

### ISSUE THREAD

**Issue by andres-delosrios** [numpy/numpy#16117]
### I found an issue while using the method complex on arrays:

```python
import numpy as np
<< x=np.arange(5)
b=complex(x,x)                            # gives error below
b=x+ij*x                                       # works

 >>
```

### Error message:

TypeError: only length-1 arrays can be converted to Python scalars

### Numpy/Python version information:

1.18.1 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0]

**Comment by eric-wieser** [comment]
`complex` is not a method and is not from numpy - so we cannot control its behavior.

It expects `float`s as an argument, but you're giving it an array. Python is trying to convert that array into a `float` for you, but that's not possible, because you can't flatten `[0, 1, 2, 3, 4]` to a single number.

We could perhaps improve the error message, but that's probably tracked elsewhere.
