### ISSUE TITLE
Full_like type deduction

### ISSUE THREAD

**Issue by chris-hld** [numpy/numpy#16116]
Type deduction might be surprising when using `np.full_like`, as it is not consistent with `np.full`.
The question is if `np.full_like` should also deduce `dtype` from the `fill_value`, rather than from `a`.

I assume most people use the ..._like functions to create an array of a certain shape, and not necessarily dtype.

Just wanted to ask what the policy is here, before I create any PR.

### Reproducing code example:

```python
import numpy as np
a = np.zeros(3)
b = np.full(a.shape, False)
c = np.full_like(a, False)

In [2]: a.dtype                                                                                          
Out[2]: dtype('float64')

In [3]: b.dtype                                                                                          
Out[3]: dtype('bool')

In [4]: c.dtype                                                                                          
Out[4]: dtype('float64')
```
### Numpy/Python version information:

1.18.1 3.7.6 (default, Jan  8 2020, 13:42:34)

**Comment by seberg** [comment]
All `_like` arguments inherit everything that an array has except what is explicitly set. Since there is also a `dtype` keyword argument in both of these, I am not sure I agree that the fill value can be regarded as explicitly setting the dtype.

Note that if changed, it removes the equivalence of `np.ones_like(arr)` and `np.full_like(arr, 1)`.

**Comment by chris-hld** [comment]
> Note that if changed, it removes the equivalence of np.ones_like(arr) and np.full_like(arr, 1).

That is true, however, `np.full_like(arr, 1.)` (or `1.0`) would be equivalent again. Which also makes sense - it's either an array of `1` (int) or `1. `(floats). 

Either way, the safest way is as always stating the type explicitly. 

I just ran into this problem when dealing with bools, where negating an array of bool is not the same as on an array of numeric type (throwing an error).
That's why I assumed it's safer to deduce from `fill_value` than from `arr`.
Upcasting when necessary, as in your example, should always be safe anyway.

To make an example

```python
import numpy as np
a = np.arange(10)
b = np.full_like(a, True)   
c = ~b

# big surprise:
In [5]: c                                                                                                
Out[5]: array([-2, -2, -2, -2, -2, -2, -2, -2, -2, -2])

**Comment by seberg** [comment]
@chris-hld yes, but the question is how you use `full_like`. For example if I do a manual padding:
```
def pad_with_constant(arr, constant):
     new_shape = np.array(arr.shape) + 2  # two larger in all dims
     res = np.full_like(new_shape, constant)
     res[(slice(1, -1),) * res.ndim] = arr
     return res
```
I probably expect to inherit the `dtype` from `arr`, not constant. I definitely do *not* expect to cast `arr` to an integer, just because `constant` is.

**Comment by chris-hld** [comment]
Isn't your example also having this problem? Unfortunately it doesn't run on my machine (ValueError: couldn't broadcast), but if I understand correctly, `res.dtype` in line 2 is always `int`, right?

So what if you want to pad an `arr` of bool, your output `res` would be of type int, and have the same problem as in my example, wouldn't it? 

Looks like if `arr` was of type float, then assigning to `res` in line 3 would also upcast `res` from int to float.

Maybe I'm wrong here, but this seems also quite shaky to me...

**Comment by seberg** [comment]
Should have put arr first in the `full_like` call (updated). And if `arr` was type `float`, the assignment will downcast to integer, because if `constant=5`. That is just to say, there are obviously use-cases where you want to keep the `dtype` of array around.

I do agree that your reading makes senes (I still do not prefer it yet), but even if, I think changing this would be disruptive, because I am sure code will be assuming that `constant` does not matter. For example, constant may be a `float64` while the array is a `float32` and you do not want to upcast the array just because of that.

**Comment by chris-hld** [comment]
Ok, I was kind of anticipating that argument that a change might be disruptive in some circumstances.

Fortunately, the current behaviour is actually documented, so passing dtype explicitly takes care of potential errors.

Can be closed from my side, unless someone else has a perspective on this issue.
