### ISSUE TITLE
Inconsistent behavior when checking if a numpy array is inside a Python sequence potentially containing multiple arrays

### ISSUE THREAD

**Issue by jfaccioni** [numpy/numpy#16123]
Checking whether a numpy array is in a regular Python sequence (list, tuple, etc.) that may or may not contain a different numpy array is inconsistent. Namely:

- if the numpy array is also the first numpy array found in the Python sequence, `True` is returned;
- otherwise, a `ValueError` is raised.

I have no input on which outcome is preferred, other than it should either return `True`/`False` or raise a `ValueError` in both cases. 

### Reproducing code example:

```python
import numpy as np
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 
seq = ['dog', a, 1, True, b, 'hello'] 

a in seq  # returns True
b in seq  # raises ValueError

```

### Error message:

```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### Numpy/Python version information:

1.18.1 3.8.2 (default, Mar 28 2020, 14:09:06) 
[GCC 7.5.0]

**Comment by seberg** [comment]
There is nothing we can do about this, this is (somewhat) defined behaviour in Python which is used in these cases and uses the identity. See also: https://docs.python.org/3.5/c-api/object.html#c.PyObject_RichCompareBool
While at the same time assuming that `bool(obj == obj)` must always succeed, which is not reasonable for NumPy arrays, since we use `==` for elementwise comparisons.

The Python developers are very much aware of this, but fixing it would require probably awkward API, so quite honestly I do not think anyone will consider doing that. And since we cannot define `==` for two arrays, this is just a behaviour you will have to live with.

You will see similar issues if you use multiple `NaN` values: `np.nan in [float("nan")]` vs. `np.nan in [np.nan]`.

**Comment by jfaccioni** [comment]
I see, thanks for the clarification.
