### ISSUE TITLE
isnan and similar functions not supported by __array_function__?

### ISSUE THREAD

**Issue by maxnoe** [numpy/numpy#16137]
The new `__array_function__` protocol is not used for `np.isnan` and `np.isnat`.

### Reproducing code example:

```python
import numpy as np


def try_func(func, array):
    try:
        result = func(array)
        print(func, 'worked:', result)
    except Exception as e:
        print(func, 'failed:', e)


class MyArray:
    def __array_function__(self, func, types, args, kwargs):
        return 0


a = MyArray()

for func in (np.sum, np.std, np.isnan, np.isfinite, np.isnat):
    try_func(func, a)

```

### Error message:

```
<function sum at 0x7f02ef5c7d40> worked: 0
<function std at 0x7f02ef5ccd40> worked: 0
<ufunc 'isnan'> failed: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
<ufunc 'isfinite'> failed: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
<ufunc 'isnat'> failed: ufunc 'isnat' is only defined for datetime and timedelta.
```

### Numpy/Python version information:

```
1.18.1 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment]
Those last three functions are ufuncs, so are overriden with `__array_ufunc__` (which came first) not `__array_function__`.

**Comment by MaxNoe** [comment]
https://numpy.org/doc/1.18/reference/generated/numpy.sum.html 
does not mention anything to this regard.

https://numpy.org/doc/1.18/reference/generated/numpy.isnan.html only has a very small hint in the 
signature: ` = <ufunc 'isnan'>`

The docs of `__array_function__` here  are also not very clear on which functions trigger `__array_function`:
https://docs.scipy.org/doc/numpy/reference/arrays.classes.html#numpy.class.__array_function__

**Comment by seberg** [comment]
Note that the array function protocol explicitly states that you should assume functions may be converted to a ufunc if possible. An object implementing array-function, pretty much must also implement array-ufunc. Also since ufuncs support additional methods (even if that may be irrelevant for this).
Since this targets array-like authors, I am not sure this should be in the normal signature docstring, also realize that anyone can write ufuncs, not just NumPy (scipy, astropy, etc. do).

That said, it would be good to have some documentation noting these types of things.

**Comment by mattip** [comment]
We could probably add a listing of the top-level functions that support `__array_function__` and `__array_ufunc__` in the documentation for each version. If we go that route the page should be generated from a script, perhaps it could run in the documentation's `conf.py` and replace markers in the appropriate pages with the generated lists. The script would have to gracefully handle being called repeatedly.

**Comment by rgommers** [comment]
There's already a tracking issue for that: gh-15544

**Comment by mhvk** [comment]
@MaxNoe - for a quick check on anything, just `type(np.<whatever>` will give `np.ufunc` or `function` (if a function which takes an array as an argument is not covered, it's a bug!). Though admittedly some functions, like `np.sum` can be overridden with `__array_ufunc__` as well, since they just call `np.add.reduce` internally.

p.s.  Feel free to ping me via the astropy `Time` PR that I think led to this!

**Comment by seberg** [comment]
Closing, seems this could have been closed long ago.   Ufuncs are not included by `__array_function__`, and that is intentional.
