### ISSUE TITLE
Error Numpy: np.random.rand(3,2)

### ISSUE THREAD

**Issue by DanielaSenna** [numpy/numpy#16148]
### Reproducing code example:

```python
import numpy as np

<<
for i in range(20):
    print(np.random.rand(3,2))

#OR

i = np.random.rand(8, 4)
k = np.random.rand(8, 4)
l = np.random.rand(8, 4)

d = np.array([i,k,l])
print(d) 

>>
```

### Error message:
Bug: In the tenth execution it generated random numbers outside the range [0, 1).
![123](https://user-images.githubusercontent.com/32489661/80932404-a4a2d600-8d95-11ea-8594-597e2449b0f6.jpg)

Bug: The "for" was executed ten times. In the fifth run it generated random numbers outside the range [0, 1).
![1234](https://user-images.githubusercontent.com/32489661/80932417-ae2c3e00-8d95-11ea-8db5-9bcb8b04a080.jpg)

### Numpy/Python version information:
Python 3.8.2
Numpy 1.18.4

**Comment by WarrenWeckesser** [comment]
Those values are printed using exponential notation, e.g.:

    9.65616388e-01 = 9.65616388 × 10⁻¹ = 0.965616388

**Comment by WarrenWeckesser** [comment]
I'm closing the issue, but if you still have questions about this, don't hesitate to ask.

**Comment by DanielaSenna** [comment]
Suppose I write a program that checks if the random number generated in the range [0, 1) is greater than 0.5. So, in addition to checking if the number is greater than 0.5 I need to check if it is in exponential notation?

**Comment by WarrenWeckesser** [comment]
The exponential notation is just the convention that is used to *display* the numbers in certain cases.  It has nothing to do with the internal representation of the value (which, by default, is [64 bit (aka double precision) floating point](https://en.wikipedia.org/wiki/Double-precision_floating-point_format).  So you are fine to just compare the value to 0.5.

**Comment by DanielaSenna** [comment]
![test](https://user-images.githubusercontent.com/32489661/80935267-331d5480-8da2-11ea-8c85-87acc59d3fea.jpg)

**Comment by WarrenWeckesser** [comment]
That looks correct.  In the third example, the value is

    4.04316946e-01 = 4.04316946 × 10⁻¹ = 0.404316946

and that is less than 0.5.  It might help if you also print the value when it is less than 0.5 by changing the "No" line to

    print("No: ", l[0, 0])

In the example above, you would get something like

    No:  0.404316946

(but you'll probably see more digits).  For that particular value, when NumPy prints the *scalar* `l[0,0]`, it doesn't use exponential notation to display the value, but it is the same value as shown in the array output.

(FYI: `np.random.rand(6, 4)` returns a two-dimensional numpy array, for which it is more concise (and more efficient) to write `l[0, 0]` instead of `l[0][0]`.)

**Comment by DanielaSenna** [comment]
Okay. I understand now. Sorry for the questions. Thanks for the explanations.

**Comment by WarrenWeckesser** [comment]
> Okay. I understand now.

Great!

> Sorry for the questions. Thanks for the explanations.

No need to apologize, we all have to learn these arcane details at some point.
