### ISSUE TITLE
Why numpy savetxt can not save the right format of the array? 

### ISSUE THREAD

**Issue by Frank-Dz** [numpy/numpy#16176]
I know we can set the decimal by setting:
```
np.savetxt(cur_dir+"/imgs/V0_.txt",V,fmt='%1.6f')
```
But, the following code can not set the format "decimals = 6"
```
np.savetxt(cur_dir+"/imgs/V0_.txt", np.round(V,decimals=6))
```
Why?
Anyone can help?

**Comment by rossbar** [comment]
The reason is that the array values themselves are decoupled from the way that those values are represented as strings. The default value for the `fmt` keyword argument is `%.18e`, so `savetxt` will save values in that format by default no matter the type/precision of the underlying array elements. To save the values in a different string format, you must explicitly supply that format, e.g. `np.savetxt(my_filename, np.round(my_data, decimals=6), fmt="%.6f")`
