### ISSUE TITLE
improvements of np.random.choice

### ISSUE THREAD

**Issue by ggrrll** [numpy/numpy#16225]
Hi,

I have few sugestions for improvements of `np.random.choice`

* these are basically _combinations_ , so the part where it says 
> #This is equivalent to np.random.permutation(np.arange(5))[:3] 

might be a bit misleading 

* 'replacements' are actually called [repetitions](https://en.wikipedia.org/wiki/Combination#Number_of_combinations_with_repetition), so I would rename that parameter accordingly
* I would put by default `replace=False` , as I think that most of the times users need simple combinations, and not combinations with repetitions 

What do you think?

Thanks as usual for your work

**Comment by bashtage** [comment]
Sampling with replacement is completely standard in probability and statistics, so I don't see a good reason to differ from this language.

Moreover, I think neither of these can be changed since it would break any existing code that used the default values or keyword arguments.  Potentially breaking user code needs a very compelling case and then a long deprecation cycle.

**Comment by ggrrll** [comment]
fair enough – thanks for the feedback
