### ISSUE TITLE
Beta random number generator can produce values outside its domain

### ISSUE THREAD

**Issue by lucianopaz** [numpy/numpy#16230]
The `numpy.random.beta` function can generate samples that are either `0` or `1`, which is outside of the support of the Beta distribution.

We came across this issue over at [pymc3](https://github.com/pymc-devs/pymc3/issues/3898). I started to dig into it and found that [numpy's legacy implementation](https://github.com/numpy/numpy/blob/master/numpy/random/src/legacy/legacy-distributions.c#L174-L206) can in fact produce zeros and ones if the `a` and `b` parameters are both smaller than 1.

I read a bit of Johnk's method [here](https://link.springer.com/book/10.1007/978-1-4613-8643-8), and it seems acceptable to discard the generated sample if it is either 0 or 1. That way, you would always end with generated random number in the open (0, 1) domain.

### Reproducing code example:

```python
>>> import numpy as np
>>> a = np.random.beta(0.01, 0.01, size=1000000)
>>> print(np.any(a == 0), np.any(a == 1))
True, True
```

### Numpy/Python version information:

1.18.1 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]

**Comment by rkern** [comment]
Can you find an explicit reference that says that simply rejecting the exact 0s and 1s from Johnk's method is correct? I find that if I do that, then there is a bias. There are a lot more exact 1s than exact 0s, but with `a==b`, the two ends ought to be symmetric.

**Comment by WarrenWeckesser** [comment]
> There are a lot more exact 1s than exact 0s, but with a==b, the two ends ought to be symmetric.

Could that be because there are more floating point numbers near 0 than there are near 1?

**Comment by rkern** [comment]
I'm not particularly concerned by the mathematics of the current method. While some authors define it over `(0, 1)`, others define it over `[0, 1]`, even in the `a,b < 1` case. While the PDF asymptotes at the endpoints, it's a "friendly" kind of asymptote that still permits us to work with the CDF and random variate generation.

It's certainly possible that `pymc3` needs to define it over `(0, 1)` for the particular application to which you are applying it, but I'm going to recommend that you handle it over there. Consider clipping to `x[x > 0].min()` and `x[x < 1].max()` instead of rejecting exact 0s and 1s. The issue is that there are a lot more floating point numbers close to 0 than there are floating point numbers close to 1, so a lot of the near-0 density ends up being represented as not-0 numbers while a lot of the near-1 density ends up being represented as exactly 1 once the floating point calculations are done.

**Comment by rkern** [comment]
Or clip to `np.nextafter(0.0, np.inf)` and `np.nextafter(1.0, -np.inf)`.

**Comment by lucianopaz** [comment]
> Can you find an explicit reference that says that simply rejecting the exact 0s and 1s from Johnk's method is correct? I find that if I do that, then there is a bias. There are a lot more exact 1s than exact 0s, but with a==b, the two ends ought to be symmetric.

I haven't seen a reference that says that rejecting is correct. I hadn't thought of the bias I would introduce with the rejection, I'll look at that later today. If rejecting does cause bias, then I think that #16231 can be discarded.

**Comment by lucianopaz** [comment]
I've closed #16231 because it lead to a huge sampling bias. I'm hesitant on whether this issue should be closed too. I still think that the beta generated samples shouldn't touch the boundaries of the domain, but the Johnk's algorithms produces them simply due to rounding errors, and it doesn't seem worthwhile to try to come up with an alternative generator.

**Comment by VikrantReddy** [comment]
Could we check if it returns any number that's 0 or 1, and run the function again to replace those numbers?

**Comment by lucianopaz** [comment]
@VikrantReddy, that's what this PR did, it discarded the samples that were equal to zero or one, and resampled them. Unfortunately, that leads to a huge bias because there are many more values equal to one due to rounding errors than values equal to zero.

**Comment by bashtage** [comment]
It looks like there is a decision that retaining the current generation method is the best approach. Can this be closed?
