### ISSUE TITLE
fill() much slower than creating a new zeroed array

### ISSUE THREAD

**Issue by bje-** [numpy/numpy#16272]
### Reproducing code example:

I am a bit surprised at the performance gap. I can always re-create the zeroed array, but the code is perhaps a bit less clear. Why the difference?

```
In [10]: %timeit x = np.zeros((8760, 43, 43))                                                         
9.49 µs ± 45.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [11]: %timeit x.fill(0)                                                                            
943 µs ± 7.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

### Numpy/Python version information:

1.18.4 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]

**Comment by seberg** [comment]
This is because of kernel/operating system features. Filling with 0 actually writes zeros to it, but creating an array of zeros, does nothing until you actually use that array. Check also the `calloc` command in C.

If you think we should note that somewhere in the docs (and do not yet), a PR is very welcome!

**Comment by bje-** [comment]
That was my suspicion and I suppose I should have dug into the source to check. Thanks.

**Comment by seberg** [comment]
If you are up for it, I am pretty sure a PR adding a Note to the `zeros` and `empty` docs would be accepted.
