### ISSUE TITLE
np.polymul return type is np.float64 or np.complex128 when given an all-zero argument

### ISSUE THREAD

**Issue by roryyorke** [numpy/numpy#16354]
`np.polymul` returns an object with type `np.float64` when one argument is all zero, and both arguments have type `np.int64` or  `np.float32`.  Something similar happens with all zero `np.complex64` giving result type `np.complex128`.

This *doesn't* happen with non-zero arguments; there the result is as expected.

This bug isn't present in `np.convolve`.

### Reproducing code example:
```python
>>> import numpy as np
>>> np.__version__
'1.18.4'
>>> a = np.array([1,2,3])
>>> z = np.array([0,0,0])
>>> np.polymul(a.astype(np.int64), a.astype(np.int64)).dtype
dtype('int64')
>>> np.polymul(a.astype(np.int64), z.astype(np.int64)).dtype
dtype('float64')
>>> np.polymul(a.astype(np.float32), z.astype(np.float32)).dtype
dtype('float64')
>>> np.polymul(a.astype(np.complex64), z.astype(np.complex64)).dtype
dtype('complex128')
```

### Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.18.4 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
```

**Comment by rossbar** [comment]
This happens because `polymul` converts the input arrays to `poly1d` instances under-the-hood. The `poly1d` constructor has a special catch for all-zero coefficient arrays:

https://github.com/numpy/numpy/blob/ba5205c1b8a7bebdf37535c701ffcd8bd79362bb/numpy/lib/polynomial.py#L1170-L1172

All that said, it's not clear what should be done about it. It would be straightforward to make `np.array([0])` (see lines above) conform to the dtype of the input array, but this would be a backwards-incompatible change. Generally, user's are encouraged to use the newer `np.polynomial`, particularly the class-based interface (e.g. `np.polynomial.Polynomial`) which should (in principle) have more consistent behavior.

**Comment by eric-wieser** [comment]
I'd say this one is a clear bug that we should just fix.
