### ISSUE TITLE
np.arange sometimes gives an empty array instead of MemoryError

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#16426]
Possibly related to #16425

### Reproducing code example:

```python
>>> import numpy as np
>>> np.arange(0, 2**62, dtype=np.int8)  # error is expected
MemoryError: Unable to allocate 4.00 EiB for an array with shape (4611686018427387904,) and data type int8
>>> np.arange(0, 2**63-1, dtype=np.int8)  # max intp
array([], dtype=int8)  # huh?
>>> np.arange(0, 2**63, dtype=np.int8)  # out of range for intp
array([], dtype=int8)  # huh?
>>> np.arange(0, 2**63 + 2**10, dtype=np.int8)  # way out of range
array([], dtype=int8)  # huh?
>>> np.arange(0, 2**63 + 2**10 + 1, dtype=np.int8)  # finally
ValueError: Maximum allowed size exceeded
```

### Numpy/Python version information:

1.20.0.dev0+c4a1aef 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]'

**Comment by WarrenWeckesser** [comment]
The calculation of the  length of the result goes through an intermediate floating point calculation, and when the spacing (i.e. `np.spacing(value)`) is more than one, precision is lost and the length (in most cases) is wrong.  Even in a case where the expected memory error occurs, you can see that the amount that it tried to allocate is incorrect.  Here, the length should be 2**62+1 =  4611686018427387905, but it tried to allocate 4611686018427387904:
```
In [5]: np.arange(0, 2**62+1, dtype=np.int8)                                                                                                  
python(88829,0x7fffa26593c0) malloc: *** mach_vm_map(size=4611686018427387904) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```
This floating point calculation of the length is also why in some cases, `arange` "succeeds" and returns an array with length 0.  When `stop` is, say `2**63`, the floating point version of the length is `float(2**63)`.  Eventually this value is passed to the C function `_arange_safe_ceil_to_intp(value)`, a simplified version of which is

```
static npy_intp
_arange_safe_ceil_to_intp(double value)
{
    double ivalue;

    ivalue = ceil(value);
    if (!(NPY_MIN_INTP <= ivalue && ivalue <= NPY_MAX_INTP)) {
        printf("arange: overflow while computing length");
        return -1;
    }
    return (npy_intp)ivalue;
}
```
Because `ivalue` is `double`, the constants `NPY_MIN_INTP` and `NPY_MAX_INTP` in the `if` expression are promoted to `double`.  The loss of precision in this conversion means the inequality `ivalue <= NPY_MAX_INTP` is true, so the overflow is not detected.  Then the cast in the return statement `(npy_intp)ivalue` results in a return value of `-2**63`.  The code in `PyArray_ArangeObj` in `"ctors.c"` that calls `_arange_safe_ceil_to_intp` checks for a negative return value and converts the length to 0.

I suspect the proper way to fix this is to avoid using a floating point intermediate calculation when all the inputs to `arange` are integers.

**Comment by WarrenWeckesser** [comment]
> I suspect the proper way to fix this is to avoid using a floating point intermediate calculation when all the inputs to arange are integers.

Or perhaps it would be simpler to just reject any attempt to create a result with length greater than `2**52`.

**Comment by czgdp1807** [comment]
Hi, A small doubt, out of curiosity, if lengths are integer quantities then why floating point is used for intermediate calculations?

**Comment by eric-wieser** [comment]
@czgdp1807: There's probably not a particularly good reason. Ideally we'd do something like
```
# round up
length = -((stop - start) // -step)
```
Unfortunately, this fails quite nastily for cases when `start`, `stop` or `step` are `np.unsigned_integer`s.
