### ISSUE TITLE
[Feature Request] Make numpy scalar types JSON serializable

### ISSUE THREAD

**Issue by alanhdu** [numpy/numpy#16432]
Apologies if this feature request already exists -- I feel like it probably does, but I wasn't able to find it anywhere.

Most numpy scalars are not JSON serializable. For example:
```python
import numpy as np
import json
json.dumps(np.float32(3))
```
fails with `TypeError: Object of type float32 is not JSON serializable`.

This is especially irritating when you build Python dict/lists that retrieve items from numpy arrays -- in the `repr`, these numpy scalars are indistinguishable from Python scalars (and they duck-type almost perfectly as Python scalars), so you only know that something's "wrong" when you try to serialize things.

I don't know exactly how to implement this, but `np.float64` is JSON serializable which implies that it should be possible at least.

**Comment by seberg** [comment]
Float64 is serializable because it inherits it from the python float (it is a subclass), so you will get a normal python float when deserializing.
I am not sure if we can implement this easily, maybe there is a good way, in which case on it seems acceptable to me.  One side note: You can use `scalar.item()` to get a "python-type", which in most cases is serializable. (it will be just a python float, also for float32).

**Comment by rkern** [comment]
We can't do anything to make our objects automatically JSON-encodable, I don't think. The `json` module explicitly requires you to specify the [`JSONEncoder`](https://docs.python.org/3/library/json.html#json.JSONEncoder) if you don't just want the defaults. It's possible that we could provide one for people to use, but there are different tradeoffs that probably belong to the users to determine. For example, one application will need perfect round-trip accuracy; an encoded `float32` gets decoded as a `float32`. Another will need to convert `float32` scalars to plain-old JavaScript floats (i.e. `float64`) because the system on the other side only knows about JavaScript floats.

I would leave this to the applications themselves.

**Comment by seberg** [comment]
Yeah, there seem to be encoders out there, e.g. https://pypi.org/project/django-numpy-json-encoder/ but likely more that support NumPy. So I guess this is something best left untouched.  I guess at best we could start moving some such project under the NumPy organization umbrella, although I honestly doubt we would gain anything...

**Comment by rkern** [comment]
It's worth documenting in whichever parts of the documentation where we talk about serialization. Linking to projects as small as these is subject to linkrot, but that would at least give people a Google target. Giving a quick example of using `JSONEncoder` to convert `np.integer` scalars to `int`, `np.floating` scalars to `float`, `np.complexfloating` scalars to `complex` would be useful.

**Comment by alanhdu** [comment]
FWIW, I think the semantics should be "np.float32 gets cast to a Python float, and np.int* gets cast to a Python int". If someone really cares about round-trip accuracy, then I'd be surprised that they're using JSON instead of some other serialization format.

That said, after digging around I also don't see a good way to implement this by default, so it's probably a moot point.

**Comment by 2796gaurav** [comment]
Can we at least document this thing on NumPy's website?

**Comment by mdhaber** [comment]
@rkern it looks like the public documentation about serialization is [here](https://numpy.org/devdocs/user/how-to-io.html#write-or-read-a-json-file).

The RST is:
https://github.com/numpy/numpy/blob/040ed2dc9847265c581a342301dd87d2b518a3c2/doc/source/user/how-to-io.rst?plain=1#L303-L307
Do you think changing it to:
```
Write or read a JSON file
=========================

NumPy arrays and most NumPy scalars are **not** directly
`JSON serializable <https://github.com/numpy/numpy/issues/12481>`_.
Instead, use a custom `json.JSONEncoder`, which can be
found using your favorite search engine.
```
would resolve this issue, and this could be closed in favor of gh-12481?

(And do you know off the top of your head whether the `json` intersphinx reference will work since it's standard library, or do I need to add something to the mapping in [`conf.py`](https://github.com/numpy/numpy/blob/040ed2dc9847265c581a342301dd87d2b518a3c2/doc/source/conf.py#L335)?)

**Comment by rkern** [comment]
Yes, that would be fine.

I have no idea about the intersphinx.
