### ISSUE TITLE
Package updates on anaconda

### ISSUE THREAD

**Issue by Dan-Patterson** [numpy/numpy#16440]
I was told before that it isn't your problem, however, I put in a package request on the Anaconda Issues site at... 

[package request: update numpy #11806](https://github.com/ContinuumIO/anaconda-issues/issues/11806)

Given the current circumstances, this may be understandable, but just thought I would give you an FYI that packages are still at 1.18.1.

**Comment by rgommers** [comment]
Thanks for asking @Dan-Patterson. I think this isn't unexpected, although I wish bugfix release updates in `defaults` would be a little faster. Anaconda does a lot of testing and provides stability guarantees for its `defaults` channel. Hence it should be expected to be ~3 months behind. Often new NumPy minor releases come out much sooner than that because of NumPy's central place in the ecosystem. But ~3 months lead time is expected for a package there in general. For quick updates, one should use `conda-forge`.

I really wish this was documented better in a prominent place, but last time I checked it wasn't.

**Comment by rgommers** [comment]
https://numpy.org/install recommendations look reasonable, I don't think it makes sense to add this info there. So not sure there's much we can do. Hence I'll close this issue. Please feel free to continue the conversation though @Dan-Patterson
