### ISSUE TITLE
BUG: mgrid result sensitive to data type

### ISSUE THREAD

**Issue by cortwave** [numpy/numpy#16466]
Using `np.mgrid' depends on slice dtype

### Reproducing code example:
```python
import numpy as np

a = np.mgrid[[slice(np.float32(0.1), np.float32(0.3), np.float32(0.1)) for _ in range(1)]]
# returns array([[0, 0, 0]])

b = np.mgrid[[slice(np.float64(0.1), np.float64(0.3), np.float64(0.1)) for _ in range(1)]]
# returns array([[0.1, 0.2]])

np.testing.assert_allclose(a, b)
```

### Numpy/Python version information:

1.18.4 3.6.7 (default, Mar 27 2020, 15:56:09) 
[GCC 6.5.0 20181026]

**Comment by seberg** [comment]
Using tuple syntax is much simpler here:
```
np.mgrid[np.float32(0.1):np.float32(0.3):np.float32(0.1),]   # note the last comma
```
In any case, you are right. `mgrid` seems a bit funny, and could use some cleanup and refactor also. In particular, I think it should just call `np.arange` (or `np.linspace` for the complex step case) and then reshape/create a dense grid if necessary.

Maybe the float32 bug is so obvious, that we can simply make it work (by going through arange unfortunately, I guess)?

**Comment by cjblocker** [comment]
The problem seems to be that `isinstance(start, float)` returns False when `start` is a `np.float32`, so the output is initialized to use the default `int` instead. Oddly, `np.ogrid` avoids this problem because it outputs a list instead of an array, so the values just get overwritten, instead of coerced into `int` like `np.mgrid`.

I can fix this.
