### ISSUE TITLE
Numpy square does not acccept unsigned integer dtype

### ISSUE THREAD

**Issue by Llewyllen** [numpy/numpy#16488]
Exception when squaring a signed integer array

### Reproducing code example:

a = np.zeros(shape=(100,), dtype=np.int8)
b = np.square(a, dtype=np.uint32)

### Error message:

TypeError: No loop matching the specified signature and casting was found for ufunc square

### Numpy/Python version information:

Python 3.5, Numpy 1.17.5+mkl
Python 3.7, Numpy 1.18.2+mkl

**Comment by seberg** [comment]
As it says, the problem is the combination of signature *and* casting. In your case it is the casting. You cannot safely cast the int8 array to a uint32 array. If you use `casting="unsafe"` this will execute just fine (but if a contains negative numbers it will break). You may want to just cast before-hand, then you can also use the in-place operator: `a **= 2` or `np.square(a, 2).

I hope this clarifies your question.

**Comment by eric-wieser** [comment]
I suspect the confusion here is that `np.square` contains no `signed, signed -> unsigned` loops, and so the only candidates are `int8, int8 -> int8` and `uint32, uint32 -> uint32`.

Perhaps we should add some mixed-sign loops here?

**Comment by seberg** [comment]
Yes, except that until a larger scale refactor happens (as possibly part of https://github.com/numpy/numpy/pull/15271 currently), this is actually not how it works... Since in most cases it sets the input rather than the output dtype if you pass only one dtype.  This currently translates to `signature=(uint32, None, None)`, instead of `signature=(None, None, uint32)` as you might expect.

 There is a lot of maintenance needed in the ufuncs around this and general initial call, and while that chuck could e.g. be split of, it probably will remain big diffs...
