### ISSUE TITLE
DOC: Add an example of np.transpose(4d_array) to the docs

### ISSUE THREAD

**Issue by JUSTNIUB** [numpy/numpy#16497]
Content from @eric-wieser:

> The docs currently give an example of `np.tranpose(3d_array, axes)`, but it would aid understanding if we showed what a 1-argument invocation looked like too. It's probably most insightful on a 4 array.

**Comment by eric-wieser** [comment]
The docs for `np.transpose` could probably do with an extra example of `some_4d_array.T.shape`

**Comment by JUSTNIUB** [comment]
> The docs for `np.transpose` could probably do with an extra example of `some_4d_array.T.shape`

thank u very much

**Comment by eric-wieser** [comment]
Let's leave this open as a documentation task.

**Comment by JUSTNIUB** [comment]
could you give me a link of the document please?I don't know how to find it. thank you

**Comment by mattip** [comment]
The docstring for transpose in [`numpy/core/_add_newdocs.py`](https://github.com/numpy/numpy/blob/v1.19.0rc2/numpy/core/_add_newdocs.py#L3998) is [rendered](https://numpy.org/devdocs/reference/generated/numpy.ndarray.transpose.html) via sphinx. Please read [the developer docs](https://numpy.org/devdocs/dev/index.html) to get started with a PR. In order to test your changes, you should first build and install numpy (to get your docstring into the locally-installed numpy), then [build the docs](https://numpy.org/devdocs/dev/index.html#building-docs)

**Comment by JUSTNIUB** [comment]
> The docstring for transpose in [`numpy/core/_add_newdocs.py`](https://github.com/numpy/numpy/blob/v1.19.0rc2/numpy/core/_add_newdocs.py#L3998) is [rendered](https://numpy.org/devdocs/reference/generated/numpy.ndarray.transpose.html) via sphinx. Please read [the developer docs](https://numpy.org/devdocs/dev/index.html) to get started with a PR. In order to test your changes, you should first build and install numpy (to get your docstring into the locally-installed numpy), then [build the docs](https://numpy.org/devdocs/dev/index.html#building-docs)
thank you. I will learn it.

**Comment by faraz16iqbal** [comment]
Is this issue currently open?

**Comment by eric-wieser** [comment]
All issues marked "open" like this one are currently open.

If you don't see any PRs linked in a comment, then additionally no one else has published any attempt at working on it.

**Comment by faraz16iqbal** [comment]
I would like to work on this issue

**Comment by ruppysuppy** [comment]
This is my first contribution, so I am not very confident about how things are done. If there is any changes please let me know

**Comment by mattip** [comment]
Closed by gh-16581
