### ISSUE TITLE
New buffer interface is over 2x slower than old array interface

### ISSUE THREAD

**Issue by abalkin** [numpy/numpy#16518]
### Reproducing code example:

```python
In [1]: import numpy as np

In [2]: z = np.zeros(1000)

In [3]: %timeit memoryview(z)
534 ns ± 12.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [4]: %timeit z.__array_struct__
254 ns ± 2.13 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

### Numpy/Python version information:

```python
In [5]: import sys, numpy; print(numpy.__version__, sys.version)
1.20.0.dev0+c8a5ff0 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27)
[Clang 6.0 (clang-600.0.57)]
```

**Comment by abalkin** [comment]
Note that buffer interface is not inherently slow:

```python
In [7]: from array import array

In [8]: a = array('d', [0]*1000)

In [9]: %timeit memoryview(a)
165 ns ± 3.83 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

**Comment by eric-wieser** [comment]
My guess would be either that the slowdown comes from the dtype to `format` serialization, or the mess of buffer caching that @seberg can summarize.

**Comment by seberg** [comment]
A combination of both. There is actually one trivial thing that may give a decent performance boost, and that is the alignment check, which we can skip for base descriptors (the array alignment should be correct I think). We can probably also use the normal (power-of-two-assuming) alignment check in general, but overall almost all cases don't go there in any case.

The buffer caching mess is annoying, and adds a dict lookup+insertion, which will also be on the order of 1/3 or so of the overhead.

I will do a PR for the alignment thing, I had it as part of the larger cleanup. But that larger cleanup requires extending the array struct. I want to just do it, I feel that the hand-full of people who might run into crashes should be OK with recompiling, but it seems I may need to convince everyone that 1.20, should be a 2.0 release before I can do that and that still needs some work and nerve from my side...

**Comment by seberg** [comment]
Hmmm, the alignment is actually only ~5% improvement... My branch (with the extended ndarray struct) has a 40+% improvement. But I also converted a few `malloc`'s to `PyObject_Malloc` which may be half of the speed gain...

**Comment by seberg** [comment]
The situation is much better now.  This is still somewhat slower than `array.array` (around a factor of about ≤1.7, NumPy has to do a lot more work than `array` though).  A good chunk of it is likely still due to the formatting, which should be possible to optimize away for non-structured dtypes.

I am going to close this, since the situation is _much_ better now and the largest chunks of optimization have happened a longer time ago (this is quite nice for reduced overheads with typed memoryviews in cython).

But, happy if a new issue is opened, especially if it includes a bit of detail where the main overheads come from in newer NumPy versions.
