### ISSUE TITLE
Inconsistent indexing with torch.Tensor

### ISSUE THREAD

**Issue by Yura52** [numpy/numpy#16543]
Hi! Decided to report this, although I understand that this can be out of scope for numpy.

```python
import numpy as np
import torch

a = np.arange(10)
a[np.array([0])]  # array([0])
a[np.array([0, 1])]  # array([0, 1])
a[torch.tensor([0])]  # 0  <<< INCONSISTENCY
a[torch.tensor([0, 1])]  # array([0, 1])
```

Python==3.7.7
numpy==1.18.4
torch==1.5.0 (cpu version)

**Comment by seberg** [comment]
The first problem is that torch did not follow our lead and define `torch.tensor([0]).__index__()` as an error for non 0-d arrays.  Admittedly, we _do_ allow those things for `__int__` and `__float__` (I personally do not like that, but not sure anyone ever quite tried to change it).  There may be more issues even then though, since:
```
a[np.array(0), ...]  # returns a copy
```
while the same might return a view for a torch tensor.  Otherwise, we would have to check whether the input is an array-like earlier on in the indexing process. I am not immediately sure what the trade-offs are around that.  Checking for arbitrary array-likes is probably a bit slow, on the other hand maybe integer fast-paths can offset most of that.

So, I do think torch may want to change this, fixing this in NumPy might also be possible and would also remove the copy inconsistency for the 0-d special case... but I am not quite sure yet what is best there.

**Comment by seberg** [comment]
Going to close this, since I still think it is a torch bug unless convinced otherwise.
