### ISSUE TITLE
typedef npy_intp to Py_ssize_t  (cf. PEP353) (Trac #1056)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1654]
_Original ticket http://projects.scipy.org/numpy/ticket/1056 on 2009-03-15 by @sturlamolden, assigned to unknown._

arrayobject.h contains these typedefs:

typedef Py_intptr_t npy_intp;
typedef Py_uintptr_t npy_uintp;

From PEP 353: "Conceptually, Py_intptr_t and Py_ssize_t are different things: Py_intptr_t needs to be the same size as void*, and Py_ssize_t the same size as size_t. These could differ, e.g. on machines where pointers have segment and offset. On current flat-address space machines, there is no difference, so for all practical purposes, Py_intptr_t would have worked as well."

This would thus be preferred, although the difference will not be noticeable on most platforms:

typedef Py_ssize_t npy_intp;
typedef size_t npy_uintp;

**Comment by charris** [comment]
We no longer support Python 2.4, so reopen this issue.

**Comment by sturlamolden** [comment]
I am not sure about this anymore. i have seen cases where npy_uintp (or even worse: npy_intp) is used to store pointers, e.g. in sklearn. Then it would obviously be wrong to tupedef npy_uintp to size_t.

**Comment by charris** [comment]
Ah, OK, closing this again then. Yes, something like `npy_ssize_t` would be nice, but I suspect it is too late to change.

**Comment by sturlamolden** [comment]
On x86 the maximum segment length is 4 GB (32 bit size_t), but the address space could theoretically be much larger (up to 2**48 bytes, IIRC). That is e.g. why we can have 32 bit x86 servers with more than 4 GB RAM. But the OSes flattens the userspace address space by setting the size of the address space to the maximum segment length, and so we only get a 32 bit pointer. If they allowed userspace processes to exploit the architecture to its full potential, we could in the worst case segfault by indexing with npy_intp. 

But yes, since indexing with npy_intp is so pervasive it is probably too late to change.

**Comment by juliantaylor** [comment]
I don't really see a real problem, should for some inexplicable reason a relevant architecture reappears where the sizes of void* and size_t are different we can simply define it different on that arch only, there is no ABI to break. If numpy or any software written in the last 20 years even works at all.

for me npy_intp is the perfect type for indexing, correct size, signed and not reads better than Py_Ssize_t

**Comment by cournape** [comment]
it is indeed mostly pedantic with today architectures, though I would have prefered `npy_(s)size_t` to the `npy_(u)intp` when indexing. Given the history, may indeed not worth changing.
