### ISSUE TITLE
Scary strange behavior from zeros_like

### ISSUE THREAD

**Issue by lepmik** [numpy/numpy#16578]
Weird bug when using `zeros_like` 
### Reproducing code example:

```python
import numpy as np
rewards = np.array([0,0,1,1,0,1])
gamma = .8

returns = np.zeros_like(rewards)
for t in range(len(rewards)):
    returns[t] = rewards[t] + gamma * returns[t-1]
print(returns)
# array([0, 0, 1, 1, 0, 1])

returns = np.zeros(rewards.shape)
for t in range(len(rewards)):
    returns[t] = rewards[t] + gamma * returns[t-1]
print(returns)
# array([0.   , 0.   , 1.   , 1.8  , 1.44 , 2.152])
```

### Numpy/Python version information:

1.18.1 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]

**Comment by rossbar** [comment]
Hi @lepmik , turns out this isn't a bug - this is how things are designed to work! The main issue here is that `zeros_like` preserves not only the shape of `rewards`, but the `dtype` as well:

```python
>>> rewards = np.array([0, 0, 1, 1, 0, 1])
>>> rewards.dtype
dtype('int64')
>>> np.zeros_like(rewards).dtype
dtype('int64')
```

`zeros` on the other hand defaults to a dtype of float64, which is what you were expecting in this case (judging from the remainder of the example). The simplest way to get the behavior you were expecting with `zeros_like` is by explicitly supplying the desired dtype, i.e.

```python
>>> np.zeros_like(rewards, dtype=np.float64)
```

Hopefully this was sufficient to answer your question - feel free to re-open if not!
