### ISSUE TITLE
timedelta64 doesn't have the `abs` method

### ISSUE THREAD

**Issue by hmaarrfk** [numpy/numpy#16687]
### Reproducing code example:

```python
import numpy as np
arr = np.asarray(np.timedelta64(1, 's'))
print(arr.dtype)
arr.abs()
```
### Error message:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-685c953b3f2a> in <module>
----> 1 np.asarray(np.timedelta64(1, 's')).abs()

AttributeError: 'numpy.ndarray' object has no attribute 'abs'
```

### Numpy/Python version information:

```
1.18.5 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0]
```

**Comment by seberg** [comment]
Nothing to do with timedeltas itself. Abs *is* defined for timedeltas. `abs()` is and never was a method, `abs()` is a python operator, so you can use `abs(array)`.  This has been discussed before, obviously we _could_ add a method, I am personally not enthusiastic about that, since the operator `abs()` already exists as a builtin, and thus seems like the correct (also ducktyped) way.  Not that I want to empower spelling it `ndarray.__abs__()` though.

**Comment by hmaarrfk** [comment]
hmm, you are right. I guess I didn't realize that `.abs` didn't exist as a method in the API. thanks!
