### ISSUE TITLE
[FR] Sorting structured arrays should use only fields specified in `order` when `kind='stable'`

### ISSUE THREAD

**Issue by narfanar** [numpy/numpy#16701]
### Reproducing code example:

```python
import numpy as np
arr = np.array(
	[([], 1), ('a', 2), ([], 2)],
	dtype=[('obj', object), ('num', int)]
)

print(arr)

arrs = np.sort(arr, kind='stable', order=['num'])
#^ It errors here trying to use `obj` to "break ties",
#  but shouldn't need to.
```

**Comment by WarrenWeckesser** [comment]
I agree it would be useful to have this capability, and it would be useful whether or not `kind` is `'stable'`.  However, the [docstring](https://numpy.org/doc/stable/reference/generated/numpy.sort.html) says

```
order : str or list of str, optional

    When a is an array with fields defined, this argument specifies which fields
    to compare first, second, etc. A single field can be specified as a string, and
    not all fields need be specified, but unspecified fields will still be used, in the
    order in which they come up in the dtype, to break ties.
```
Changing the default behavior so that unspecified fields are ignored would break backwards compatibility.

To enable such a feature, we need some way to tell `sort` to use *only* the given field(s).  Perhaps something like `order=['num', None]`, where the value `None` acts like a sentinel, and tells sort to not use any other fields.  That's not a serious proposal at the moment. It is just an example to emphasize that we would need some additional API to enable ignoring unspecified fields.

**Comment by Dan-Patterson** [comment]
I agree with Warren.  If your intent is to sort on one field, just use argsort

```
import numpy as np
arr = np.array(
	[([], 3), ('a', 2), ([], 1)],
	dtype=[('obj', object), ('num', int)]
)
arrs = arr[np.argsort(arr['num'], kind='stable')]
arrs

array([(list([]), 1), ('a', 2), (list([]), 3)],
      dtype=[('obj', 'O'), ('num', '<i4')])

```

**Comment by rossbar** [comment]
I'm going to close for now as @Dan-Patterson 's answer shows how you can achieve the desired behavior without the need for adding new API. If there is interest in expanding the sorting API, please feel free to re-open the discussion (the mailing list is probably the most appropriate forum)
