### ISSUE TITLE
how numpy support slice ND array  efficiently?

### ISSUE THREAD

**Issue by littleDrew** [numpy/numpy#16727]
### Reproducing code example:
- here i thought numpy do good with flexiable index operation, like slice etc
```python
a = [[1,2,3],[4, 5, 6]]
a = np.array(a)

#do slice operation:
b = a[0:2, 0:2]

# obtain b = [[1, 2], [4, 5]]
# here how it do data value copy efficently in c++ layer? it must not copy element by element
# copy row by row? and caculate the begin address of each row element ?

```
- And want how this is supported in numpy source code
- which part of code can i refer? hope help to explain and figure out.

**Comment by seberg** [comment]
numpy does not do any copying here, it creates *views*. I.e. it changes `b.strides` (and the initial offset) to create a new view into the same data. Maybe check this also: https://numpy.org/doc/stable/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray

Also see that `b.base is a`, since there is no copy involved at all, the operation itself is fairly simply calculation of slides (this is defined in `mapping.c`: https://github.com/numpy/numpy/blob/7a91f538db4072e65efe12bd7b10a58ce7b87b75/numpy/core/src/multiarray/mapping.c#L915
