### ISSUE TITLE
Iterate through the data address of numpy, always the address of the first data.

### ISSUE THREAD

**Issue by wqcsim** [numpy/numpy#16853]
### Reproducing code example:
```python
s1 = np.arange(12).reshape(3,4)
s2 = np.arange(24,36).reshape(3,4)
print(s1.data, s2.data)
ss = [s1,s2]
for i, s in enumerate(ss):
    print(s.data)
    print(ss[i].data, i)     # bug here: The address printed twice is the same!
    print(ss[0].data, ss[1].data, "#####")
    print(s)
```
### Python 3.6.9  result:
```python
<memory at 0x7f148fdf7480> <memory at 0x7f148eedc558>
<memory at 0x7f148fdf7480>
<memory at 0x7f148fdf7480> 0
<memory at 0x7f148fdf7480> <memory at 0x7f148eedc558> #####
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<memory at 0x7f148fdf7480>
<memory at 0x7f148fdf7480> 1
<memory at 0x7f148fdf7480> <memory at 0x7f148eedc558> #####
[[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]
```

**Comment by rkern** [comment]
`.data` is a property that dynamically creates a new object each time it is accessed. The address that's printed is the address of the `memoryview` object, not the address of the actual data. Since you don't keep the `memoryview` objects around, they will get reclaimed at the end of each statement. Then the next time a `.data` property is accessed, Python may (or may not) reuse the same memory to allocate the `memoryview` object structure.
