### ISSUE TITLE
documentation for boolean indexing for both axes is not clear

### ISSUE THREAD

**Issue by gokhalen** [numpy/numpy#16885]
I'm looking at boolean indexing in the Quickstart Tutorial [here](https://numpy.org/devdocs/user/quickstart.html#indexing-with-boolean-arrays). I'm looking at the section which follows the Mandelbrot example, which you can get to by searching "The second way of indexing with booleans is more similar to integer indexing".

The last code snippet is problematic.

```
a[b1,b2]                                  # a weird thing to do
array([ 4, 10])
```

Based on the previous code examples in the Quickstart Tutorial, I would have expected this to construct the outer-product of `b1,b2` and return the entries in `a` corresponding to the `True `values in the outer-product.  That is, I would have expected the following output

`array([ 4,  6,  8, 10])
`
But clearly this is not what is happening. 
 Based on the previous code examples, I also expected the following behavior

```
a[[True,True,True],[True,True,True,True]]=array([[ 0,  1,  2,  3],
                                                                          [ 4,  5,  6,  7],
                                                                         [ 8,  9, 10, 11]])

```
However, what I get is a broadcasting error

`IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (4,) 
`
Is it possible to explain more clearly what is happening in boolean indexing especially when both axes use boolean indexing?  

This problem has been noticed [elsewhere ](https://scipy-cookbook.readthedocs.io/items/Indexing.html) too. Search "Finally, if you want to apply boolean conditions to the rows and columns simultaneously, beware:" to get to the right place.

**Comment by rossbar** [comment]
Thanks for raising, this is indeed a bit hairy. The more detailed documentation on [advanced indexing in the reference guide](https://numpy.org/devdocs/reference/arrays.indexing.html#boolean-array-indexing) describes what's happening here. Essentially, Boolean indexing works like advanced indexing with integer arrays constructed from `mask.nonzero()`. This works as expected when there is a *single* indexing mask but, as you note, might result in different behavior than expected when trying to use multiple masks along different axes.

To illustrate:
```python
>>> b1.nonzero()
(array([1, 2]),)
>>> b2.nonzero()
(array([0, 2]),)
>>> a[b1.nonzero(), b2.nonzero()]
array([[ 4, 10]])
```
The only reason `a[b1, b2]` works at all in the quickstart tutorial is because b1 and b2 both have the same number of `True` elements (2). This also explains why your all-true masks example fails (try applying the "advanced indexing with integer arrays" rules with `array([0, 1, 2])` and `array([0, 1, 2, 3])`). 

Re: the quickstart tutorial - maybe stronger wording and a link to the relevant section of the reference guide would help clear this up (perhaps a fix-up to the linked cookbook article as well!). Suggestions welcome!

**Comment by gokhalen** [comment]
Thank you very much.
