### ISSUE TITLE
Should we error on "not-recommended" behavior in static typing tests ?

### ISSUE THREAD

**Issue by anirudh2290** [numpy/numpy#16891]
This discussion stems from here : https://github.com/numpy/numpy/pull/16622#discussion_r455438073

The numpy documentation says the following about instantiating the dtype object using "{'field1': ..., 'field2': ..., ...}": 

"This usage is discouraged, because it is ambiguous with the other dict-based construction method. If you have a field called ‘names’ and a field called ‘formats’ there will be a conflict."

I think static typing is a good place to catch not just "wrong" types used, but also to catch early such discouraged usage in numpy. So, IMO we should have the type checker error on such behavior. WDYT ?

**Comment by rgommers** [comment]
I agree with this. I think we had a similar discussion before. Rather be strict in type annotations to signal the code we want people to write, than to provide typing for every bit of valid code.

**Comment by BvB93** [comment]
> I think static typing is a good place to catch not just "wrong" types used, but also to catch early such discouraged usage in numpy. So, IMO we should have the type checker error on such behavior. WDYT ?

I share your sentiment. 
At the end of the day type hints are a set of guidelines; not strict rules. Considering the relevant `dtype(...)` syntax is already officially discouraged in the documentation I feel it would be good to reflect this in aforementioned guidelines as well.

**Comment by person142** [comment]
> I think we had a similar discussion before.

Some previous discussion:

https://github.com/numpy/numpy-stubs/issues/12
https://github.com/numpy/numpy-stubs/issues/41
https://github.com/numpy/numpy-stubs/pull/66#issuecomment-617217204

So far we've come down on the side of strictness; though I imagine decisions will continue to be made on a case-by-case basis. I think the important thing is documenting the decisions so that we don't end up discussing the same points endlessly, so far I have been doing that here:

https://github.com/numpy/numpy/blob/master/numpy/typing/__init__.py#L25

**Comment by anirudh2290** [comment]
Thanks for the suggestion, I have added the doc changes here : https://github.com/numpy/numpy/pull/16917.
