### ISSUE TITLE
Checking for elements in a list raises ValueError if an array is present

### ISSUE THREAD

**Issue by onnoeberhard** [numpy/numpy#16981]
I am sorry if this has been mentioned before or is the intended behaviour, it is difficult to search for the operator `in`. In the code snippet below, I would expect the result `check = False`, because 3 is not an element of the list. Instead, I get a `ValueError`.

### Reproducing code example:

```python
import numpy as np
check = 3 in [1, np.array([1, 2, 3, 4, 5])]
```

### Error message:
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

### Numpy/Python version information:
1.19.0 3.8.3 (default, Jun  9 2020, 17:49:41) 
[GCC 8.3.0]

**Comment by onnoeberhard** [comment]
This seems to result from checking for equality with `==`. The same error gets raised, when implementing the `in` check like this:
```python
check = any(x == 3 for x in [1, np.array([1, 2, 3, 4, 5])])
```

One dirty workaround that only works for primitive types like int is the following:
```python
check = any(x is 3 for x in [1, np.array([1, 2, 3, 4, 5])])
```

**Comment by seberg** [comment]
Yes, but unfortunately there is no way to work around this issue.  As you note, `3 == np.array([1, 2, 3, 4, 5])` *is* well defined as `np.array([False, False, True, False, False])`, and cannot be a boolean value.  There are similar issues with `NaN` involved, and this gets discussed once in a while on Python as well.  But, in the end there is no simple solution, since I doubt anyone wants to create a "congruency" operator or so, which could allow NumPy to overload equality to have array-programming behaviour, but still allow a stricter definition of "equivalence" which is clearly `False` here.

The next thing is that, even if you do this... There are many shades of equivalence, is `3. == 3` (if you are strict about it)?  In the end. The `in` operator in python uses an "equivalence" definition of:

    x is elem or x == elem for x in sequence

And since `==` has elementwise syntax in NumPy, there is no clear solution to it.  And I believe any solution would have to start in Python.

I am going to close this, happy to reopen, but this is one of those issues that simply do not have a clear solution and would just stay open for years (or probably forever) without being touched.
