### ISSUE TITLE
"ValueError: operands could not be broadcast together with shapes" error on invalid boolean array index

### ISSUE THREAD

**Issue by asmeurer** [numpy/numpy#16997]
In some instances, when indexing an array with a boolean array index, instead of getting an `IndexError`, you instead get a `ValueError: operands could not be broadcast together with shapes ...` error.  It seems to happen when the product of the array and index shapes are the same (but the shapes to not match).

### Reproducing code example:

```python
>>> import numpy as np
>>> a = np.empty((3, 3))
>>> a[np.empty((1, 9), dtype=bool)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (3,3) (1,9)
```

Compare the usual case:

```py
>>> a = np.empty((3, 4))
>>> a[np.empty((1, 9), dtype=bool)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 1
```

Another example to back my theory that this only happens when the array sizes match

```py
>>> a = np.empty((2, 2, 4))
>>> a[np.empty((1, 4, 4), dtype=bool)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (2,2,4) (1,4,4)
>>> a[np.empty((1, 2, 4), dtype=bool)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 1
```

Obviously, `ValueError` is the incorrect error for an invalid index, but aside from this, an error mentioning broadcasting of the array shape and the index shape is very confusing since (unless I am mistaken), this never actually happens.

### Numpy/Python version information:

NumPy master:

```py
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.20.0.dev0+8f60522 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16)
[Clang 9.0.1 ]
```

**Comment by seberg** [comment]
The reason is that the above case goes into a boolean array fast path and fails there, instead of the general advanced indexing path (which uses the `nonzero` logic first).  I agree the error could and probably should be changed to IndexError, it is currently being raised by the iterator, so would need to be checked ahead of time or replaced.  Or maybe just fall back to the slow path to give the same errors.

**Comment by asmeurer** [comment]
I guess I'm confused about boolean indexing semantics. If the index array is all False, the indexing works with no errors. In every other case, it fails:

```py
>>> a.shape
(3, 3)
>>> a[np.full((1, 9), False)]
array([], dtype=int64)
>>> a[np.array([[False, False, False, False, False, False, False, False,  True]])]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (3,3) (1,9)
>>> a[np.full((1, 100), False)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 1
>>> a[np.nonzero(np.full((1, 9), False))]
array([], dtype=int64)
>>> a[np.nonzero(np.full((1, 100), False))]
array([], dtype=int64)
```

Is this intended behavior? It doesn't seem to be documented. I guess it's because `np.nonzero` gives empty arrays when there are no Trues, so that the shape doesn't matter? But why does it allow shapes that don't actually match (only the product matches)?

Also it doesn't work in every case:

```py
>>> np.empty((2, 4, 6))[np.full((2*2*2, 1, 6), False)]
array([], dtype=float64)
>>> np.empty((2, 4, 6))[np.full((2*2, 2, 6), False)]
array([], dtype=float64)
>>> np.empty((2, 4, 6))[np.full((2, 4*6), False)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: boolean index did not match indexed array along dimension 1; dimension is 4 but corresponding boolean dimension is 24
```

It seems to work as long as the array and index have the same number of dimensions and the same size, and the index is all False.

**Comment by seberg** [comment]
Sounds like a buggy fast path for the all-false case. I am a bit surprised as to why we would have such a fast path, but...

Note that all the weird cases completely bypass any "nonzero" logic, since all of them occur in the fast-path for a single boolean array of identical size as the input array (which should be identical shape).

Fixing that fast path to only accept identical *shape* should automatically also switch that behaviour you just note.  I think I would be fine with just doing it, it seems strange enough and more likely to flush out serious bugs then anything else.

**Comment by seberg** [comment]
If you are up for it, you could try modifying this line: https://github.com/numpy/numpy/blob/e20dded7c3bf28c5767c645f074920d8017eeba9/numpy/core/src/multiarray/mapping.c#L557

So that it compares the shape exactly, which will have the effect that I described, of just using the "slow" path (which gives all the errors you would like to see).

**Comment by asmeurer** [comment]
By the way, I found both this issue and https://github.com/numpy/numpy/issues/15753 using hypothesis to test my own library. I noticed NumPy already has a couple of hypothesis tests, but not very many. I would suggest adding a lot more, especially for things that don't rely on testing finicky floating point arithmetic (like indexing semantics).

**Comment by asmeurer** [comment]
Can you make any sense of the comment above that line? It seems to say to me that this is intentional, but I'm probably misreading it.

**Comment by seberg** [comment]
Sure, new tests are welcome.  The comment makes sense, but is outdated, since the paths which it intentionally lets through are now all errors, actually reversing the situation: Making it more strict ensures the same errors are raised.  But of course, as the comment states, you can also delete the shape line entirely, and instead raise the IndexError(s) you have been talking about explicitly in the boolean array case.

**Comment by asmeurer** [comment]
OK, I guess I'm missing the history of how indexing semantics used to work differently?

**Comment by asmeurer** [comment]
Changing `PyArray_SIZE` to `PyArray_SHAPE` on that line seems to fix it. I'm running the tests to see if anything else breaks.

**Comment by seberg** [comment]
@asmeurer the semantics had a huge amount of weird corner cases at some point, most are fixed, but as you see some corner cases of corner cases are still around.  You need to use `PyArray_CompareLists` (or delete the line and fix up/clarify the errors in the boolean fast path explicitly, which may even be a bit nicer).

**Comment by asmeurer** [comment]
Yeah, I figured out the comparelists thing (it's been too long since I've code in C).

I started https://github.com/numpy/numpy/pull/17010 which just changes the check. We can work on cleaning up the fast path code itself from there.
