### ISSUE TITLE
numpy.full_like returning array of integers even with floating-point fill values

### ISSUE THREAD

**Issue by liuyonghao156** [numpy/numpy#17035]
```python
import numpy
numpy.full_like([0,0,0], 0.1)
```

returns `array([0,0,0])`, whereas,

```python
numpy.full(3,0.1)
```

returns `array([0.1,0.1,0.1])`

Although this behaviour is mentioned in the official document, I don't think this should be as it is now.

**Comment by rossbar** [comment]
There is some related discussion in #16116 (and I think some other issues that I couldn't immediately find).

The issue arises from the fact that the type is determined from the array (or in this case, the array-like, which is converted to an array under-the-hood) rather than the `fill_value`. This behavior (inferring the dtype from the input array) is consistent with the other `_like` functions, and changing it would break backwards compatibility. Note that the dtype inference step can be avoided entirely by specifying the desired dtype explicitly::

```python
>>> np.full_like([0, 0, 0], 0.1, dtype=float)
array([0.1, 0.1, 0.1])
```

**Comment by liuyonghao156** [comment]
@rossbar Your explanation makes pretty good sense to me, thanks!

**Comment by liuyonghao156** [comment]
> There is some related discussion in #16116 (and I think some other issues that I couldn't immediately find).
> 
> The issue arises from the fact that the type is determined from the array (or in this case, the array-like, which is converted to an array under-the-hood) rather than the `fill_value`. This behavior (inferring the dtype from the input array) is consistent with the other `_like` functions, and changing it would break backwards compatibility. Note that the dtype inference step can be avoided entirely by specifying the desired dtype explicitly::
> 
> ```python
> >>> np.full_like([0, 0, 0], 0.1, dtype=float)
> array([0.1, 0.1, 0.1])
> ```

Your explanation makes pretty good sense to me, thanks!
