### ISSUE TITLE
Why is np.append so slow?

### ISSUE THREAD

**Issue by Rubix982** [numpy/numpy#17090]
### Reproducing code example:

`np.append` is extremely slow, why is that the case? [The docs](https://numpy.org/doc/stable/reference/generated/numpy.append.html) don't have anything on the performance part. 

With the below given code example, it took me more than 10 minutes to have some result. Does it not work like the regular list.append()?

```python
def get_data(filename):

    labels = np.array()
    images = np.array()
    
    with open(filename) as training_file:
        next(training_file)
        csv_file_contents = csv.reader(training_file)
        for row in csv_file_contents:
            labels = np.append(labels, float(row[0]))
            pixel_values = [float(value) for value in row[1:]]
            pixel_values = np.array(pixel_values)
            pixel_values_split = np.array(np.split(pixel_values, 28))
            images = np.append(images, pixel_values_split)
    return images, labels
```

As compared to the list version of this, it took me less than a minute.

```python
def get_data(filename):
    labels = list()
    images = list()
    
    with open(filename) as training_file:
        next(training_file)
        csv_file_contents = csv.reader(training_file)
        for row in csv_file_contents:
            labels.append(float(row[0]))
            pixel_values = [float(value) for value in row[1:]]
            pixel_values_split = np.split(np.array(pixel_values), 28)
            images.append(pixel_values_split)

    return (np.array(images)).astype(float), (np.array(labels)).astype(float)
```

For reference, I'm reading in a file with 32,627 rows, each with 785 columns and extracting the labels from the first place ( row[0] ), and the rest of values are the pixels ( row[1:] = 784 values, which is split between 28 arrays ).

The files can be found here. [One](https://ycozcamcoqgpaezjoywdtv.coursera-apps.org/edit/tmp2/sign_mnist_test.csv) is test file, the [second](https://ycozcamcoqgpaezjoywdtv.coursera-apps.org/edit/tmp2/sign_mnist_train.csv) is the training file. The total rows is the sum of rows from both the files.

**Comment by eric-wieser** [comment]
> [The docs](https://numpy.org/doc/stable/reference/generated/numpy.append.html) don't have anything on the performance part.

Not explicitly, but they do say:

> Note that append does not occur in-place: a new array is allocated and filled. If axis is None, out is a flattened array.

This means that a loop over `N` elements is `O(N**2)`, as you reallocate a larger and larger array each time.

We should probably add a warning about this in the docs.

**Comment by eric-wieser** [comment]
Doing this efficiently relates to the discussion in #14479 about `np.fromiter`

**Comment by Rubix982** [comment]
Hmm, interesting, which basically means that numpy itself has a module to handle and return a new np array every single time. Can we not make this a method for the `numpy.array()`? That is, make `append` and `insertion` a method of `numpy.array()` so that it does not have to deal with the creation of a new np array every single time.

**Comment by rkern** [comment]
The reason that `list.append()` is "fast" is because `list` over-allocates memory for the items it contains, roughly 1/8 extra items than there are in the list. While there are still free slots at the end of the over-allocated memory, `list.append()` just puts the new item into a free slot. It only has to re-allocate memory once those over-allocated slots are used up. Because the size of the over-allocated memory grows with the size of the list `list.append()` is roughly constant-time, on average, for building a long list.

`numpy` does not over-allocate memory. It represents an N-D array, not just a 1-D list, so it can't really over-allocate in all axes. This isn't a matter of whether `append()` is a function or a method; the data model for `numpy` arrays just doesn't mesh with the over-allocation strategy that makes `list.append()` "fast".

There are a variety of strategies to build long 1-D arrays quickly. If you know the target length, you can create the array up-front using `np.empty()` and then filling it in. If you don't know the target length, accumulating values in a `list`, then using `np.array()` at the end to convert it to an array is a good option.

**Comment by Rubix982** [comment]
Valuable information, @rkem. I think I've got the whole idea. Thank you. 

I believe I should contribute to the docs now? Would it be fine. Anyways, thank you!

**Comment by seberg** [comment]
@Rubix982 sure, if you have some time and an idea/proposal of how to improve the documentation that is very welcome!
