### ISSUE TITLE
have a basic question about numpy matrix

### ISSUE THREAD

**Issue by yapifu** [numpy/numpy#17170]
I have one var, scaled_y , it's from a dataset column 'price'. so it's n*1 matrix

y=precess.fit_transform(data[['price']])

![image](https://user-images.githubusercontent.com/67816810/91388144-590cb000-e7fc-11ea-9b06-45df2160a076.png)

I thought the scaled_y.T should be same as 
scaled_y.reshape(scaled_y.shape[0])

However, they are not.
![image](https://user-images.githubusercontent.com/67816810/91388291-9cffb500-e7fc-11ea-9481-cf6ab0515c8b.png)

Anyone can tell me the difference between the two. What does [[   ]] mean? is [ [    ] ] same as  [  ]
why would my transformation will have this [ [   ] ] rather than   [  ] single bracket ?

**Comment by bashtage** [comment]
`scaled_y` is a 20 by 1 array. So the first is a 2-dimensional array with shape (1,20) (1 row, 20 columns). The latter is a 1-dimensional array with shape (20,), which means that it has 20 elements. The 1-d array is created because you ask NumPy to reshape you array to have the shape (20,), in other words, to have 1 dimension. 

Arrays are not matrices in general and can have any number of dimensions.  Matrices always have 2-dimensions (in NumPy-land).

**Comment by yapifu** [comment]
thanks basically one is 1*20 matrix, one is array with 20 elements

**Comment by bashtage** [comment]
Could you close this?
