### ISSUE TITLE
np.full() sometimes become vey slow

### ISSUE THREAD

**Issue by bxhandhxb** [numpy/numpy#17206]
### Reproducing code example:

```python
import time
import os
import psutil
import numpy as np

if __name__ == '__main__':
    ss = [2700]
    for i in range(100):
        for s in ss:
            t1 = time.time()
            img4 = np.full((s * 2, s * 2, 3), 114, dtype=np.uint8)
                        # del img4
            #info = psutil.virtual_memory()
            print('memory use：', psutil.Process(os.getpid()).memory_info().rss)
            p = psutil.Process(os.getpid())
            #print(p.name(), p.exe(), p.cwd(), p.status(), p.create_time(), p.uids(), p.gids())
            print(p.cpu_times())
            #print(p.memory_percent(), p.memory_info())
            print(p.num_threads())
            print(time.time()-t1)

```

### Error message:

I run the above code in docker container. But its time varies greatly sometimes. 
![1](https://user-images.githubusercontent.com/26036453/91811547-4104b880-ec62-11ea-9bc9-bf9bb7fc6eb9.png)

 

My server is training some deep learning models.

### Numpy/Python version information:
the python version is 3.7.7 and numpy version is 1.18.5
<img width="946" alt="截屏2020-08-31 下午1 46 48" src="https://user-images.githubusercontent.com/26036453/91705240-46ed9180-ebaf-11ea-907a-83d5d928e5d8.png">

But when  I  degrade the numpy to 1.16.2. It 's fine.  
<img width="946" alt="截屏2020-09-01 下午2 45 39" src="https://user-images.githubusercontent.com/26036453/91811332-ee2b0100-ec61-11ea-9058-ee5bd9054fdf.png">

although I slove the problem by degradation , I 'm very confused.

**Comment by mattip** [comment]
Maybe connected to the change in support for hugepages, see the [release note](https://numpy.org/doc/stable/release/1.19.0-notes.html#ability-to-disable-madvise-hugepages)? The detection mechanism can be tricked by docker. You can try with  `NUMPY_MADVISE_HUGEPAGE=0` or `NUMPY_MADVISE_HUGEPAGE=1` and see if that solves the problem.

**Comment by bxhandhxb** [comment]
@mattip    unfortunately, it doesn't work. 😂

**Comment by bxhandhxb** [comment]
@mattip  I don't find notes about np.full.  The system cpu time is very long. Do different version numpys use different system call for np.full? I'm running 32 threads to transform images by numpy in another container. Can they influence each other?

**Comment by seberg** [comment]
@mattip I guess 1.18.5 may not include that the `NUMPY_MADVISE_HUGEPAGE` "fix"?  @bxhandhxb upgrading NumPy may thus help you, since 1.19 does include the switch.  Otherwise you could also disable hugepages system-wide.  I am not sure if that may make some other things less fast, but OTOH, it seems like kernels had some serious speed issues with hugepages, so it may just as well make things better?

**Comment by seberg** [comment]
@bxhandhxb to clarify: NumPy uses a different systemcall to allocate memory, namely the madvise hugepages feature.  That would seem like the right thing for large arrays, but on kernels (probably version 4.6 and older), there were performance issues with hugepages and memory fragmentation.

This is almost certainly the issue you are seeing, since there is no reason why NumPy should have sometimes a slow call and usually fast allocation calls.  Now we changed the default usage of hugepages to encompass a few more cases in 1.18 (I think) which caused a slowdown on such old kernels.

1.19 (I guess, I am not 100% sure), tries to undo that change for the kernels where we are sure it leads to bad performance.  In many cases it doesn't matter anyway: You can set up a system to always use huge-pages, or never use them (and thus ignore what NumPy says).

So: especially if the kernel is 4.6 or lower, that is almost certainly your issue and disabling hugepages system-wide or upgrading NumPy should fix it as well.

**Comment by bxhandhxb** [comment]
@seberg  @mattip  you are right. 
when I use echo "never > /sys/kernel/mm/transparent_hugepage/enabled" to disable THP, the code is ok!!
THANK YOU!

**Comment by bxhandhxb** [comment]
BTW,  cause its great influence for numpy(I guess), is there any guidance to open/close the hugepages??

**Comment by seberg** [comment]
Honestly, I do not know, it may be system dependent beyond just kernel versions, and probably also use-case dependent. We have received complaints about slowdowns because of it, but only for old kernels. I expect that you should use hugepages on most systems with new kernels and avoid it on most systems with an old (pre 4.6) kernel.
