### ISSUE TITLE
Numpy logo in new theme links to an undesirable page

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#17211]
It goes to https://numpy.org/devdocs/contents.html instead of the index.

**Comment by Chandu-4444** [comment]
Can I work on this issue? And I'm a first-timer so can I get help in case I'm stuck ?

**Comment by mattip** [comment]
In general: We don't really assign issues, help is welcome. We do appreciate that getting started with NumPy can be challenging, so please feel free to submit a PR, even if it is clearly wrong, and ask for help. 

We have a general overview of how to contribute [here](https://numpy.org/doc/stable/dev/index.html). Since this is a documentation issue, you will want to also read about [building the docs](https://numpy.org/doc/stable/dev/index.html#building-docs) locally.

This specific issue may be challenging if this is your first encounter with sphinx and theming.

**Comment by mattip** [comment]
Thanks for looking at this. Could you link to the PR here so we can track it?

**Comment by leonarduschen** [comment]
Here it is: pandas-dev/pydata-sphinx-theme#246

**Comment by eric-wieser** [comment]
My reading of this is that our `master_doc` value is wrong: I'd argue the top-level webpage and top-level toctree should be one and the same.

**Comment by mattip** [comment]
Maybe, but then there needs to be a way to specify which documents we want on the top navbar. Currently that is taken from the toctree of `master_doc`.

**Comment by eric-wieser** [comment]
What is the toctree of index right now?

**Comment by mattip** [comment]
It is not a toctree, it is a pre-formatted html document `_templates/indexcontent.html`. I had played with turning this into a rst document with a toctree, which led me to the conclusion above.

**Comment by eric-wieser** [comment]
Can we make it an rst document with an `.. html::` directive and a hidden toctree?

**Comment by leonarduschen** [comment]
> Maybe, but then there needs to be a way to specify which documents we want on the top navbar. Currently, that is taken from the toctree of `master_doc`.

Yeah it looks like this is what's going to be done in `pydata-sphinx-theme` (i.e. provide an option).

That said, I'd like to think NumPy's method to change `master_doc` to `contents` in order to create a custom landing webpage is not entirely outlandish. For example, this documentation uses the same method https://fairlearn.github.io/about/index.html and has the same problem as well (i.e. logo links to `contents` instead of `index`).

**Comment by mattip** [comment]
Just when I thought I knew a lot about sphinx: what is an `.. html::` directive?

**Comment by eric-wieser** [comment]
A misremembering... I mean `.. raw:: html`

**Comment by mattip** [comment]
Ahh, cool. Although [the admonition in the docs](https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through) is not encouraging, it would provide a path forward until the theme has an option for the top navbar.

**Comment by eric-wieser** [comment]
I think that admonition would be equally against what we're already doing of having a standalone html page - it's just that what we're using today is a Sphinx not docutil feature.

**Comment by Chandu-4444** [comment]
Is there something I need to learn as I don't completely understand most of the discussion above ?. Help me please. Thank you.
