### ISSUE TITLE
BUG: Calling nanstd with dtype=object fails with a cryptic error message.

### ISSUE THREAD

**Issue by domdfcoding** [numpy/numpy#17343]
I don't know whether doing this is supposed to be supported, but if it isn't the error message could be improved to alert the user that `nanstd` and `dtype=object` are incompatible.

### Reproducing code example:

```python
import numpy
numpy.nanstd(numpy.array([71, 98.0, 80, 93, 57, 46], dtype=object))
```

### Error message:

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    numpy.nanstd(numpy.array([71, 98.0, 80, 93, 57, 46], dtype=object))
  File "<__array_function__ internals>", line 5, in nanstd
  File "/home/domdf/.local/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 1664, in nanstd
    var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
  File "<__array_function__ internals>", line 5, in nanvar
  File "/home/domdf/.local/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 1548, in nanvar
    if var.ndim < cnt.ndim:
AttributeError: 'float' object has no attribute 'ndim'
```
### NumPy/Python version information:

Python 3.8.2

Numpy 1.19.1 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

**Comment by seberg** [comment]
Thanks for the report, I agree it should be considered a bug. We try to support `object` where ever possible (in cases such as here there are some tricky things to remember unfortunately).

The problem here is that `var` is 0-D and gets unpacked to a bare float (instead of remaining an array). xref gh-14489 which would make fixing this more humane.

I checked with 1.16.x and it fails as well, so it seems not to be a regression.

**Comment by BvB93** [comment]
This issue seems to have been fixed as of https://github.com/numpy/numpy/pull/19821.
