### ISSUE TITLE
ties in argsort

### ISSUE THREAD

**Issue by javadnoorb** [numpy/numpy#17371]
Sorry if this is a duplicate (I wasn't able to find any reference to it). It seems to me that the ties in argsort are sometimes reported incorrectly. For example for the code below shouldn't the result be either [2,0,1] or [2,1,0]? Instead I get [1, 2, 0]

### Reproducing code example:

```python
import numpy as np
np.argsort([1, 0, 0])
```

### NumPy/Python version information:

1.19.2 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by charris** [comment]
Why would you expect  [2,0,1] or [2,1,0]? The first looks incorrect in any case.

**Comment by rossbar** [comment]
I agree with @charris , the result you are seeing is correct. From the argsort docstring:

  > [argsort] returns an array of indices of the same shape as
  > `a` that index data along the given axis in sorted order.

So from the result `[1, 2, 0]` means that, to get a sorted array, the value at `a[1]` -> the 0th position, `a[2]` -> first position, and `a[0]` -> last position.

This is illustrated when using argsort in combination with advanced indexing, i.e. using the result of argsort directly as indices of the array (resulting in a sorted array):

```python
>>> a = np.array([1, 0, 0])
>>> I = np.argsort(a)
>>> I
array([1, 2, 0])
>>> a[I]
array([0, 0, 1])
```

Hopefully this is sufficient to answer the question. Since there is no bug, I will close this - feel free to reopen if this wasn't addressed sufficiently!

**Comment by javadnoorb** [comment]
Ah! I see. I thought that the indexing was following the ordering in the original array. Sorry for the confusion and thanks for clarification!
