### ISSUE TITLE
saved npy is 752M (on disk), and arr.nbytes = 701289568 (~669M); but np.load take 2.7g memory, i.e. 4x time the actual memory needed

### ISSUE THREAD

**Issue by mingwugmail** [numpy/numpy#17461]
### Reproducing code example:

```
$ cat npmem.py 

import numpy as np

print(np.__version__)   # 1.19.2

fn = 'data.npy'
arr = np.load(fn, allow_pickle=True)

print(arr.nbytes)

input("Press Enter to continue...")


# output:
$ du -sh data.npy
752M	data.npy

$ python npmem.py 
1.19.2
701289568
Press Enter to continue...
```

### Error message:

When the program pause for input, in another terminal, run `top`: and it shows:
```
PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND 
20   0    3.1g   2.7g   0.0g S   0.0  19.5   0:04.65 python npmem.py 
```

### NumPy/Python version information:

```
$ python -c 'import sys, numpy; print(numpy.__version__, sys.version)'
1.19.2 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
```

The data file is big, (752M	data.npy) do you need me to upload this file?

**Comment by seberg** [comment]
Since you are using `allow_pickle=True`, I presume the array contains arbitrary Python objects.  That means each object is pickled individually, and it is entirely possible that pickling an object makes it smaller.

The array itself will only hold *pointers* (references) to those objects, not the objects itself, just like a Python list, so since the dtype is `object` here, there size only represents the size those references require, not the size of the objects themselves.

There is one more effect that we often see confusion about, which may be another reason for what you are seeing.  NumPy or Python may require more memory temporarily.  In that case `top` may show the use of memory that is actually still available.  I.e. memory that was once used will be reused by the process, but `top` may still show it as in-use.

If your array is numeric, you should probably switch to one of the numeric dtypes provided by NumPy.

I hope this explains what you are seeing.

**Comment by mingwugmail** [comment]
For a given numpy array, Is there a way to print recursively the type of each element/subarray?

**Comment by mingwugmail** [comment]
And that numpy array only contains string and numbers, I still don't understand why it take 4x space in memory than on the disk.

**Comment by seberg** [comment]
No, I do not think so.  But it is only relevant if you have an `object` dtype array. You can probably just write code like:
```
def _vectorized_type_or_arr_type(element):
    if isinstance(element, np.ndarray):
        return arr_to_type_or_dtype(element)
    else:
        return type(element)

_vectorized_type_or_arr_type =  np.frompyfunc(_vectorized_type_or_arr_type, 1, 1)

def arr_to_type_or_dtype(arr):
    if arr.dtype == np.object_:
         return _vectorized_type_or_arr_type(arr)
    else:
         return f"array[{arr}]"
```

Strings and numbers means those are Python objects. There are likely multiple things going on. First, it may be you are overestimating the amount of space needed (i.e. there may be space free, but you do not see that). Second, it is entirely possible that a string is for example stored as 4-byte per character unicode string after being loaded, but stored as UTF8 with 1-byte when saved.

**Comment by rkern** [comment]
Can you show us `arr.dtype`, `arr.shape`, and `arr.strides`? That may help understand how your array is constructed without having to see the actual file.

**Comment by mingwugmail** [comment]
```
print(arr.shape, arr.dtype, arr.strides, arr.nbytes)

(121079, 724) object (5792, 8) 701289568
```

only the first 2 columns are simple strings, all the other columns are numbers.

**Comment by mattip** [comment]
`121079 * 724 * 8 = 701289568`. But each of those 8-byte locations points to a python object, and that object takes at least 24 bytes plus either space for the number or the string. The pickle serialization to disk saves the data in a compact way, but when it is in memory as PyObjects, all that is expanded.

**Comment by mingwugmail** [comment]
I see, now it explains, (8-byte pointer + 24-bytes) ~= 4x times of mostly 8-byte (double number) in the file.

And I just converted those two string columns to some sort of number (double), and run the program again, here is `top` shows

```
PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND  
20   0 1092.2m 697.5m  13.6m S   0.0   5.0   0:01.08 python npmem.py
```

now the memory usage matches the disk file size:

```
$ du -sh data.npy 
669M	data.npy
```

@mattip  thank you so much for the explanation; and thank all too.

**Comment by mingwugmail** [comment]
> Edit: python is smart enough to not create new objects for small ints, so if your data is repetitive you may save some space.

But I definitely see in my case, Python is not doing this; otherwise, my original version with mixed (small amount of) strings and (large amount of) numbers should take ~1x disk file space.

Should this be a Python improvement or np.load() can do some improvement? i.e. if it's detected that a whole column is all numbers, only allocate 8-byte numbers for each item, instead of a pointer to a PyObject (which then contains the actual number)?

**Comment by mattip** [comment]
> if it's detected that a whole column is all numbers, only allocate 8-byte numbers for each item

You can do this by using a structured dtype or by using pandas. There are JITting interpreters like PyPy and GraalPython that do optimize more aggressively than CPython where they can detect patterns, but in general the best optimization is one you avoid by using the appropriate data structures.

**Comment by mingwugmail** [comment]
I use pandas already, and have to convert to np.array to interface with some other library.

What I mean is np.save() and np.load() is not symmetric:

-- np.save() save the numeric type as scalar data, hence the disk file size is consistent with data size user have in mind, and is small
-- np.load() load the numeric type as PyObject, and inflate the memory usage 4x than the user expected.

That is the confusion that cause this issue.

**Comment by rkern** [comment]
Is the other library really expecting a `dtype=object` array mixing strings and numbers?

`np.load()` isn't converting everything to a `dtype=object` array; it must already `dtype=object` by the time it goes into `np.save()`. Data in the pickled format often does not take as much space as the same data does in-memory due to data structure overhead.

In any case, I recommend delaying any conversion until the last moment. Keep the data in a `DataFrame` as long as you can, and use its HDF5 format for saving/loading it. For this kind of data, `DataFrame` and its HDF5 format are doing the right thing.

**Comment by mingwugmail** [comment]
The other library (eventually calls tensorflow, model.fit(data)) only need the numeric columns.

I'm converting to numpy as the last step (of data preparation), and saved to disk to avoid re-computation again.

When I load the training data file, I noticed the 4x memory space needed.

It's a typical usage pattern.

Thus, I strongly suggest `np.load()` can do such space optimization.

**Comment by rkern** [comment]
`np.load()` is representing the data that was saved. If it's coming out as a `dtype=object` array from `np.load()`, then you passed a `dtype=object` array to `np.save()`. Take a closer look at that code and ensure that the array that you are saving is of an appropriate `dtype` for efficient saving. If indeed it only needs to be `np.float32` data for Tensorflow later, explicitly convert it to `dtype=np.float32`.
