### ISSUE TITLE
Suggest the the shape of the array of one dim

### ISSUE THREAD

**Issue by huangyebiaoke** [numpy/numpy#17477]
### Incurrent of one dim array's shape:
for example
```python
import numpy as np
X=np.array([1,2])
print(X.shape)
# the output is (2,)
Y=np.array([[1],[2]])
print(Y.shape)
# the output is (2,1)
```
so I suggest to output `(1,2)` when the np array is `[1,2]` when we use `shape` function
### Error message:
``` bash
(2,)
```

### NumPy/Python version information:
``` bash
1.16.2 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
```
think you for listen to me and appreciate the useful tool.

**Comment by ksunden** [comment]
To get an array of shape (1, 2), you would do `np.array([[1, 2]])`, note the double brackets which make it have `ndim` of 2.

Not all arrays are 2D (they are, after all _nd_ arrays). 

Changing this behavior would break much downstream code.

**Comment by rkern** [comment]
Thank you for the suggestion, but the current behavior is by design. One of the explicit design choices from the very beginning of NumPy was to be able to represent arrays of (nearly) arbitrary dimension, not just matrices. @ksunden points out the idiomatic way to explicitly construct a `(1, n)`-shaped array using literals.
