### ISSUE TITLE
Inconsistent handling of missings in np.mean when using pandas.Series as input

### ISSUE THREAD

**Issue by om-hb** [numpy/numpy#17470]
I'm not completely sure if this is really a bug, but I noticed that the handling of missing by the np.mean function seems to be inconsistent when used in conjunction with pandas Series. It seems like missings (np.nan) in the Series are ignored when calculating the mean, so the function outputs a numeric result instead of the (in this case) usual np.nan. 

### Reproducing code example:

```python
import numpy as np
import pandas as pd

a = [1,2,np.nan]
b = pd.Series([1,2,np.nan]

print(np.mean(a))
# returns np.nan
print(np.mean(b))
# returns 1.5
```

### NumPy/Python version information:

1.19.1 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]

pandas Version: 1.1.2

**Comment by rkern** [comment]
Objects that aren't `ndarray` (i.e. a subclass of `ndarray` or other array-like object) are allowed to implement a method named `mean()`. `np.mean()` will call that method instead of converting the array-like to an `ndarray` and calling `ndarray.mean()`. `Series.mean()` does indeed ignore the NaNs. The main thing is that `np.mean(a)` does the same thing as `a.mean()`, if it exists.

**Comment by om-hb** [comment]
> 
> 
> Objects that aren't `ndarray` (i.e. a subclass of `ndarray` or other array-like object) are allowed to implement a method named `mean()`. `np.mean()` will call that method instead of converting the array-like to an `ndarray` and calling `ndarray.mean()`. `Series.mean()` does indeed ignore the NaNs. The main thing is that `np.mean(a)` does the same thing as `a.mean()`, if it exists.

Ah okay, I see - that makes sense! Thank you very much for your quick reply!
