### ISSUE TITLE
NaN works inconsistently when converting arrays to sets

### ISSUE THREAD

**Issue by Sseziwa** [numpy/numpy#17488]
Depending on the dtype of an array, NaN either gets treated as a single or a unique value.
```
In [78]: set(np.array(['a', 'b', np.nan, np.nan]))
Out[78]: {'a', 'b', 'nan'}

In [79]: set(np.array([1.0, 2.0, np.nan, np.nan]))
Out[79]: {nan, 1.0, 2.0, nan}
```
The behavior is the same whether np.nan or math.nan is used.

**Comment by eric-wieser** [comment]
Your second snippet matches the python behavior:
```
In [147]: {math.nan, math.nan}
Out[147]: {nan}

In [148]: {0+math.nan, 0+math.nan}
Out[148]: {nan, nan}
```
Set membership is done first by identity, then by equality. `math.nan` is always identity equal to itself because of how names work, but after you do a computation you get a new nan.

Your first snippet is uninteresting, because the `nan` is converted to the string `"nan"` immediately.

**Comment by Sseziwa** [comment]
But where's the computation in the second case?  Why aren't the element of the array treated by identity?

**Comment by eric-wieser** [comment]
The "computation" is the act of converting from a C `PyFloat_Object *` to a `double` and back. Assembling the array does the forward conversion, and calling `set` does the backwards conversion. `+` is exactly the same - it unpacks the `PyFloat_Object *` objects, does an addition in C, and then packs the result into a brand new `PyFloat_Object *`.
