### ISSUE TITLE
DOC: mark np.testing.dec functions as not recommended for future use

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#17566]
Given that

> ... the [`np.testing.dec`] decorators are only retained for folks using the old nose framework and will be removed as some point, nose doesn't work with recent Python without modification. Most distros no longer provide nose, but rather nose2.
> 
> _@charris in https://github.com/numpy/numpy/pull/16370#r494495147_

I think we should update the docs at https://numpy.org/devdocs/reference/routines.testing.html#decorators to make this clear.

We might also want to consider deprecating them fully with `DeprecationWarning`s

**Comment by rpolley** [comment]
Going to take a stab at this.

**Comment by rpolley** [comment]
From what it looks like the docstrings from submodules don't actually get pulled in anywhere. Should I just deprecate the entire np.testing module, since it looks mostly nose based? Or is there some other way I should document submodules of np.testing?

**Comment by mattip** [comment]
The [rendered documentation](https://numpy.org/devdocs/reference/routines.testing.html) does included the public functions from that module. that.This issue is about deprecating only the `np.testing.dec` functions, not the whole module. With that, the module structure could be simplified (but that is a different issue).

**Comment by rpolley** [comment]
Ah, I see. So put it on the individual functions then?

**Comment by mattip** [comment]
The original ask was just to add a blurb in the docstring of [the module](https://github.com/numpy/numpy/blob/master/numpy/testing/_private/decorators.py#L1) to discourage the use of these functions. Deprecation warnings will be noisy, since the warning will be emitted during test collection. If you want to add the deprecations, please follow the pattern of 
```
# Numpy 1.21.0, 2020-12-20
warnings.warn("msg" DeprecationWarning, stacklevel=2)
```

and make sure tests pass cleanly. The relevant tests of the deprecated functions should move to `numpy/core/tests/test_deprecations`

**Comment by mattip** [comment]
Now that the decorators are deprected we need to update the docs at https://numpy.org/devdocs/reference/routines.testing.html#decorators to make this clear.

**Comment by melissawm** [comment]
Closing as the warnings are visible now.
