### ISSUE TITLE
SIMD: The --cpu-baseline is not correctly configured in benchmark system.

### ISSUE THREAD

**Issue by Qiyu8** [numpy/numpy#17716]
I'm trying to use the newest benchmark system to test the performance, but found out that the option is not working. here is the command that used for benchmarking.
```
python runtests.py --cpu-baseline="avx2" --bench-compare master bench_linalg.Einsum.time_einsum_multiply
```
in this case, the macro `NPY_SIMD `should be 256 because my machine support `avx2 `intrinsics, but the actual value is 128, which is the default minimal settings.

**Comment by seiko2plus** [comment]
my bad, I confirm it. we should pass the same exect build options to `setup.py build` and `pip wheel`
otherwise the build cache will be cleared while creating the wheel package which leads to fully rebuild
the source without passing the provided build options.

#17284 was verified through `asv --verbose` by checking the `CCompilerOpt` final report but I didn't check
the log of `pip` because option `-V` was missing from `asv`'s custom `build_command`.

#17736, should fix this issue.
