### ISSUE TITLE
bfloat16 (Brain Floating Point) when available?

### ISSUE THREAD

**Issue by mingwugmail** [numpy/numpy#17809]
Hi,

I saw NEP 41 Status: | Accepted

https://github.com/numpy/numpy/blob/master/doc/neps/nep-0041-improved-dtype-support.rst

I'm just wondering when will bfloat16 be available in numpy?

For some ML problems, this will reduce the memory requirement by half (or process 2x more data), can we give this high priority?

Thanks.

**Comment by mattip** [comment]
`bfloat16` will start out as a user-defined dtype. NEP 41 will make it easier, but it is not impossible now. It should start as an external project like [quaternions](https://quaternion.readthedocs.io/en/latest/). To move this forward, someone should either start such a project or sponsor someone else to do the work.

**Comment by seberg** [comment]
Tensorflow has already some experimental stuff included: https://www.tensorflow.org/api_docs/python/tf/experimental/numpy/float16

But this uses the old system, so there are shortcomings. The new one is still a work in progress. If someone really wants to work on it, you could experiment with parts using NumPy master (but you have to use private API at this time, and there are likely still some things that may just not work).

**Comment by mingwugmail** [comment]
@seberg that's float16, not Bfloat16

there is no typo in my post, (in case you mis-read), it's (Brain Floating Point)

https://en.wikipedia.org/wiki/Bfloat16_floating-point_format

**Comment by seberg** [comment]
@mingwugmail wrong link, because I tried to not link to the code and never looked at anything else. So here is a code link instead: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/python/bfloat16.cc

I am going to close this. Its just not a TODO item to work on right now. At least not within NumPy.

Some notes:

1. I realize that others in the numpy core team (who have overlap with deep learning libraries) are more friendly towards including bfloat16 in NumPy itself. I am not opposed as such, but I don't think it is the right starting point at the moment. *Eventually it may be good to have a "canonical" bfloat16, so I think that could live in the NumPy org (as opposed to NumPy itself), or move into numpy once established, but I just don't see it as a good first step, and from my side would only be a huge hassle with very little payoff for actually implemeting NEP 41/42/43.*
2. NumPy master (with my next upcoming PR) include most things necessary for trying NEP 41/42 (not 43) DTypes (with *private* API). I am not focusing on trying that out/making that partially public, because there are more important things that are more urgent (i.e. NEP 43/ufunc work).  But if you are interested, you can try to use it very soon! It would be a melange of new and old API for certain functionality (but the first public API will probably have to be such a melange as well). And ufuncs have to use the old API (which has significant shortcomings).

So happy to engage with anyone who tries to work on such a thing and help/chat/meet. But I just can't prioritize it myself, and I certainly won't prioritize a specific DType such as `bfloat16` (from my perspective, it is not even a very interesting DType, even if it might be a widely used one).

**Comment by mingwugmail** [comment]
I found it here: 

```
import jax.numpy as np
```

https://github.com/google/jax/blob/master/jax/dtypes.py#L42

```
# bfloat16 support
bfloat16 = xla_client.bfloat16
_bfloat16_dtype = np.dtype(bfloat16)

```

**Comment by maruel** [comment]
For those curious, in JAX the definition moved to https://github.com/jax-ml/jax/blob/main/jax/_src/dtypes.py and also includes 5 kinds of float8.

**Comment by rgommers** [comment]
Canonical issue for `bfloat16` support is gh-19808.
