### ISSUE TITLE
travis-ci  no longer running.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#17824]
Looks like travis.ci has run out it's monthly quota.

**Comment by mattip** [comment]
Indeed, the [ppc, arm64, and s390x builds](https://travis-ci.com/github/numpy/numpy/builds/203319848) still left on travis stopped [two days ago](https://travis-ci.com/github/numpy/numpy/builds). When I login and go to the build page, I see "Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the [Plan page](https://travis-ci.com/organizations/numpy/plan) (which is empty) to replenish your credit balance or alter your [Consume paid credits for OSS](https://travis-ci.com/organizations/numpy/plan?anchor=oss-consumption) (which is also empty) setting." I admit I have little desire to deal with this: IBM and travis should work out an exclusion for NumFocus (at least) projects if IBM wishes us to continue maintaining software for their hardware. We still have a [job running on shippable](https://app.shippable.com/github/numpy/numpy/dashboard/history) for arm64.

**Comment by mattip** [comment]
Note we should really verify we support Apple silicon by running a native build there as well.

**Comment by seberg** [comment]
Until now, none of the NumFOCUS projects seem to have any reasonable experience with keeping those things running.  If we need very few resources for something, it may be possible. But aside from that, we probably have to assume that Travis is a lost cause right now.

**Comment by tylerjereddy** [comment]
Yeah, SciPy and MDAnalysis are both facing the same problem. For SciPy, it is a double hit because the wheels repo still has a massive Travis matrix as well.

A few people were talking about chipping in to hold things over for a bit, but when I look at the options it is **really** bad. Even if I'm like "ok, I'll shell out $70 in the main repo and $70 in the wheels repo to get SciPy 1.6.0 out", it would still be at least 5x slower than the previous 5-concurrent free plan.

![image](https://user-images.githubusercontent.com/7903078/100040265-27d45980-2dc4-11eb-9ed2-ea393d21f391.png)

I emailed Leah and Andy at NumFOCUS; Andy said they might be able to work something out with CircleCI or Azure, but I've heard no indication that NumFOCUS projects have propsects with Travis CI arragements at this time.

I emailed Travis CI support on Sunday and have not heard anything back..

**Comment by charris** [comment]
NumPy needs something to build arm64 wheels on, apart from that I think we can get by without travis. At some point I expect azure to support arm64, not least for Windows on arm64.

$279 doesn't seem too bad for a month. i was thinking of chipping in ~$1000 if it could be targeted. Or go for a slower build and just spend time. We could all use more sleep :)

**Comment by ayush1300** [comment]
Hello everyone,
Can someone guide me to understand the workflow of the code. It was really difficult for me to figure out as to how are different functions are called. For example in the npysort folder, there were files named as mergesort.c, selection.c, radixsort.c, and many more, but I could not figure out that where were these files imported or the functions called. So I just want a little bit of help, as to how to proceed in understanding the working of the code so that I could also make some useful contribution in the project. Looking forward to getting some help. Thank you

**Comment by mattip** [comment]
@ayush1300 you are commenting on an issue about using travis ci. You can reach out on the mailing list or come join one of our [community meetings]().

@tylerjereddy would you like help migrating scipy to github actions/azure? As for arm64: NumPy can get away with using shippable instead of travis, but I think the scipy build times out, it needs the more powerful graviton machines only available on travis.

**Comment by ilayn** [comment]
Can someone from the NumPy twitter account ping again e.g., https://twitter.com/neoscms/status/1330829574054273025 They seem to be active.

**Comment by mattip** [comment]
@ilayn it might be more effective for NumFocus to reach our to  support@travis-ci.com and negotiate for all their sponsored projects.

**Comment by ilayn** [comment]
Yes also true

**Comment by edelsohn** [comment]
Travis CI replied to IBM that they provide free credits to Open Source projects that request more credits.  Has anyone actually asked Travis CI?  Not even the "sponsored project" designation.  Just ask for more credits.

**Comment by seberg** [comment]
@edelsohn, thanks. As far as I am aware, astropy tried that and ran out of credits within about a week.  Now I am not sure about their CI setup/what type of jobs. It might be very hungry compared to NumPy.  Ping @bsipocz.  But I guess some discussions may still be ongoing.

**Comment by edelsohn** [comment]
The statement from Travis CI was:

> We are still providing free open source credits to anyone who requests them. They should be able to continue building as usual

I don't know if one needs to request more credits incrementally or one needs to request a larger block of credits once one has determined the monthly need.  I don't know that the Travis CI support team investigates in detail to estimate the necessary amount.  An initial request of additional credits is an initial request.  I'm not suggesting that Travis CI is making this easy, but the response seems like an overly quick declaration that no additional credits are available and the process is unworkable.

**Comment by bsipocz** [comment]
> @edelsohn, thanks. As far as I am aware, astropy tried that and ran out of credits within about a week. Now I am not sure about their CI setup/what type of jobs. It might be very hungry compared to NumPy. Ping @bsipocz. But I guess some discussions may still be ongoing.

astropy might indeed relied more on travis than other projects, mainly due to the ecosystem nature of the project, it wasn't just the core package building on travis but a lot of other repos in the organisaion. We have already evaluated transitions to pipelines or actions previously, but not all the features we used were available, and anyway, we were operated from the POV of not fixing things that are not broken (travis was always a very well understood CI providers with which many of our contributors are familiar). 

Anyway, at the beginning of the month, when the announcement came out, we put together a plan to migrate and keep only the unique stuff on travis, while we were also exploring the possibilities of getting credit or paying for the services. We asked for a monthly credit allowance based on our past usage, and indeed got a fraction of it, as a one of credit, that promply run out in a few days even though some repos has already been migrated away. 
Now most of our repos have migrated to Actions, and a few have still broken CI while avaiting migration.

Some numbers are here: https://github.com/astropy/astropy-project/issues/164

**Comment by bsipocz** [comment]
Oh, and to the opening comment:

> @charris: Looks like travis.ci has run out it's monthly quota.

I believe it's an overall, rather than a monthly quota.

**Comment by muizzk** [comment]
Hello folks, please note that I have added additional credits to this project as directed. Thank you

**Comment by mattip** [comment]
Hi @muizzk thanks! How can we see the current state of our account?
