### ISSUE TITLE
BUG: Wrong version in nightly wheels / pip 0.20.3 + python 3.9

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#17885]
Not sure if NumPy or pip is to blame but things are okay with pip 20.2.4:
```
$ python3.9 -m pip install --progress-bar off --upgrade "pip!=20.3" setuptools wheel
...
Successfully installed pip-20.2.4
$ python3.9 -m pip install --progress-bar off --upgrade --pre --only-binary ":all:" -i "https://pypi.anaconda.org/scipy-wheels-nightly/simple" numpy
...
Successfully installed numpy-1.21.0.dev0+d0a457f
```
But broken with pip 20.3:
```
$ python3.9 -m pip install --progress-bar off --upgrade pip setuptools wheel
...
Successfully installed pip-20.3
$ python3.9 -m pip install --progress-bar off --upgrade --pre --only-binary ":all:" -i "https://pypi.anaconda.org/scipy-wheels-nightly/simple" numpy
...
Collecting numpy
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/numpy/1.21.0.dev0%2Bd0a457f/numpy-1.21.0.dev0%2B20201129040310_d0a457f-cp39-cp39-manylinux2010_x86_64.whl (15.4 MB)

ERROR: Requested numpy from https://pypi.anaconda.org/scipy-wheels-nightly/simple/numpy/1.21.0.dev0%2Bd0a457f/numpy-1.21.0.dev0%2B20201129040310_d0a457f-cp39-cp39-manylinux2010_x86_64.whl has different version in metadata: '1.21.0.dev0+d0a457f'
```

**Comment by charris** [comment]
What if you don't upgrade setuptools?

**Comment by charris** [comment]
Hmm, pip 20.3 was tagged 7 hours ago, very suspicious. The question is, bug or feature?

**Comment by larsoner** [comment]
> What if you don't upgrade setuptools?

Sorry I should have pasted more output -- the only relevant change is `pip`.

> The question is, bug or feature?

Indeed -- no idea :) Should I open an upstream bug report to see what they conclude?

**Comment by mattip** [comment]
strange, I wonder if pip is now more pedantic about matching various pieces of the metadata, version, file name and other bits.

**Comment by larsoner** [comment]
https://github.com/pypa/pip/issues/9186

**Comment by charris** [comment]
See #17885 for one possible fix.

**Comment by charris** [comment]
Working now. Note that the `_` is converted to `.`, Anaconda nightly directory has a problem though, it now lists every wheel as a different version due to the changing build times. @asmeurer, anyone have a better idea of timestamp placement.

**Comment by asmeurer** [comment]
I have no idea how the new pip works, but I use versioneer for a lot of projects, and it uses versions like `1.21.0+11.g9ba2624` (the 11 is the number of commits from the tag, like `git describe`).  Hopefully the new pip still supports versions that are formatted like that. I would use the number of commits rather than the timestamp as timestamps won't actually order correctly if you build commits out of order.

**Comment by asmeurer** [comment]
I just looked at the NumPy repo and it's very odd. Are the release tags not actually merged into master? `git describe` can't work if they aren't.

**Comment by charris** [comment]
@asmeurer It is not really different than it was, but it worked before. The difference is that we used to rename the files, adding a timestamp, while leaving the `numpy.__version__` with just the extra git hash of the head commit. That no longer works because pip 20.3 requires the file name and the internal wheel version to match. So we have put the timestamp into the internal version (which seems to be what pip looks at) and consequently every build is now it's own version because build times vary. There seems to be no way to automate this, and because all the nightly builds go into the same directory and generally have the same short numpy version short form (numpy-1.21.0.dev0+<hash>) we need some way to give them priority since the git hash won't serve. One possibility would be to drop the hash and overwrite files in the nightly repository, but that doesn't hold a lot of appeal for me. Maybe using the timestamp as a build tag would work, I suppose we could try that.

**Comment by mattip** [comment]
I think using a commits-since-last-something approach has a certain appeal over the timestamp approach and may be more reproducible.  But ...

> Are the release tags not actually merged into master?

Indeed, `git describe` currently shows `pre-removal-numpybook-13079-g68b06ce36`, so it seems `pre-removal-numpybook` is the last tag on master. Tags live on the maintenance branches:
```
$ git fetch origin maintenance/1.19.x
...
$ git branch --contains "v1.19.3"
* maintenance/1.19.x
```

@asmeurer this seems "normal" to me. We don't want to merge the release branches back to master, they live and grow independently, changes are cherry-picked from master into the branches. We could add a tag on `master` at the point the last release was branched off it, for instance this would add a `m1.20.x` tag where `maintenance/1.20.x branched off master. 
```
# the first two commands are needed to get git to "see" the branch,
# git experts may find a better way to do that
$ git fetch origin maintenance/1.20.x
...
$ git checkout maintenance/1.20.x
...
$ git merge-base master maintenance/1.20.x
4635c9966f9f9a1bbb775fafc4096fddee8160dd
$ git tag -a m1.20.x 4635c9966f9f9a1bbb775fafc4096fddee8160dd -m"tag 1.20 branch off master"
$ git checkout master
$ git describe
m1.20.x-37-g33dc7bea2
```

which would then properly describe master `HEAD` as 37 commits ahead of the 1.20.x split. (Of course the tag name `m1.20.x` could be different, I just wanted to describe the technique).

**Comment by asmeurer** [comment]
I don't really know what the common workflows for dealing with backports, since I don't really do that myself for any of the software that I maintain. I usually expect tags and release branches to be merged into `master` (with the merge conflicts resolved in master's favor obviously), so that all released commits are in the `master` git history. But that may be skewed by my primarily only working with repos that have a single development branch. It may be possible to compute a "git describe-like" number of commits from a tag manually even without the commit being merged into master (I'm not sure).

By the way, you can use `git describe --match='v*'` to only match version tags (but again, this won't actually work for NumPy with the present git history).

**Comment by asmeurer** [comment]
Actually, looking at cpython, their `master` branch only has some tags. It may be sufficient to always make sure the "most recent" tag is merged in, but tags from maintenance backport branches do not necessarily need to be merged (and any commits from those backport branches will have their own `git describe` that is based off the distance from the latest backport tag).

**Comment by charris** [comment]
> I think using a commits-since-last-something approach

I did toy with the idea of year and day-of-year, which should both be stable during the weekly builds. It is only the pre-releases that have a problem, and if they do change it should not be much of a problem. I put up #17890 that puts the timestamp and hash in the build_number slot. Note that `bdist_wheel` replaces underscores and dashes with periods in the version string, so don't use any of those.

**Comment by jorisvandenbossche** [comment]
As a sidenote: in pandas we are also using release branches that are not merged back into master (so the same as numpy, i.e. final release tag is only in that branch), but we are also using versioneer and its "number-of-commits-since-last-tag" approach for development versions. 
The way we solve that is by tagging master just after we branch with a `.dev0` version, so we get development versions like `'1.2.0.dev0+1402.g8554ebf64a'`

**Comment by mattip** [comment]
`1.20.0-dev0` seems like a better name than `m1.20.x` indeed. @charris thoughts?

**Comment by jorisvandenbossche** [comment]
Note that at the moment a 1.20.x maintenance branch gets created, we would tag master with `1.21.0.dev0` on the next commit in master (so using the number of the "next" version, to ensure correct ordering according to PEP-440: 1.20.0 < 1.20.1 < 1.21.0.dev0 < 1.21.0 < ...)

**Comment by charris** [comment]
@mattip LGTM, tags are cheap and that way both the local and wheel versions would work similarly.

**Comment by charris** [comment]
One possible issue is that we would want to make sure the tags are fetched in the build forks. We might also want to automate branching with a script so as to make sure that tags are made and pushed.

**Comment by charris** [comment]
Note the you don't really need a tag
```
charris@fc [numpy.git (master)]$ git rev-list --count maintenance/1.20.x..master
37
```

**Comment by charris** [comment]
Note that multibuild `clean_code` doesn't provide the new tags/branches by default.

**Comment by charris** [comment]
I tagged the first commit in the master after the 1.20.x branch with `v1.21.0.dev0`. Pandas seems to make an empty commit for that purpose, so we will be off by one for a while.
