### ISSUE TITLE
linalg.qr returns wrong signs (+ -) in the Q matrix

### ISSUE THREAD

**Issue by samirjabbar7** [numpy/numpy#18177]
### Reproducing code example:

#python
import numpy as np
A=array([ [4,2,1],[2,0,1],[2,0,-1],[1,2,1]])
print(np.linalg.qr(A)[0])

#It returns wrong signs (+ -) in the Q matrix.

**Comment by rkern** [comment]
The QR decomposition is not unique all the way down to the signs. One can flip signs in `Q` as long as you flip the corresponding signs in `R`. Some implementations enforce positive diagonals in `R`, but this is just a convention. Since we defer to LAPACK for these linear algebra operations, we follow its conventions, which do not enforce such a requirement.
