### ISSUE TITLE
generator.choice producing different results with p=None and p=uniform

### ISSUE THREAD

**Issue by HUN-Harlequin** [numpy/numpy#18172]
### Reproducing code example:

```python
import numpy as np
generator = np.random.Generator(np.random.PCG64(3))
print(generator.choice(4, 7, replace=True, p=[0.25, 0.25, 0.25, 0.25]))
generator = np.random.Generator(np.random.PCG64(3))
print(generator.choice(4, 7, replace=True))
```

### Error message:
```
[0 0 3 2 0 1 1]
[3 0 0 0 0 3 3]
```
### NumPy/Python version information:

1.18.5 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]

**Comment by rkern** [comment]
This is expected. `p=None` triggers a (faster, more accurate) codepath for specifically for unweighted sampling. When you give it an explicit `p`, we use a different algorithm for weighted sampling. There is not a good way to test the explicit `p` that it is equivalent to being unweighted because of floating point inaccuracies.

I can understand the desire that these two give the same answers, but I don't see a good way to reconcile the two except to abandon the faster and more accurate algorithm for unweighted sampling, which I don't think would be a good idea.

**Comment by HUN-Harlequin** [comment]
Thank you for your detailed explanation, I totally understand and agree with you! 
I assumed that they are equivalent and so this caused a bit of a headache when I was writing unit tests.
Would it be possible to highlight this behaviour somehow in the documentation?
