### ISSUE TITLE
DOC: better document `__array__`

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#18249]
## Documentation
The documentation for the [`__array__` function](https://numpy.org/devdocs/reference/arrays.classes.html#numpy.class.__array_priority__) is not very descriptive. It describes what the ufunc *will not* do if `__array__` is present. It should describe what the prospective `__array__` user *is expected to do* with `self` and optional `dtype`. 

Copied from [PR 18238](https://github.com/numpy/numpy/pull/18238#issuecomment-768074889)

**Comment by rgommers** [comment]
That makes very little sense. `__array__` is supposed to simply return an `ndarray` with either a view or a copy of the data.

**Comment by mattip** [comment]
By "that" I assume you mean the current documentation that states:
```

class.__array__([dtype])

    If a class (ndarray subclass or not) having the __array__ method is used as the output object of an 
ufunc, results will not be written to the object returned by __array__. This practice will return TypeError.

```

**Comment by rgommers** [comment]
Indeed.

**Comment by mhvk** [comment]
Note that [in 1.10 at least](https://docs.scipy.org/doc/numpy-1.10.1/reference/arrays.classes.html), the description is different:
```
If a class (ndarray subclass or not) having the __array__ method is used as the output object of an ufunc, results will be written to the object returned by __array__. Similar conversion is done on input arrays.
```

Checking with `git blame`, the change was made last May, in #16130.

**Comment by rgommers** [comment]
I'm not sure if the change in gh-16130 is correct or not, but either way that's a very niche detail. The docstring doesn't explain at all what `__array__` is actually for.

It is one of the protocols with which other array-like object can achieve interoperability with numpy. When numpy functions encounter a foreign object, it will try (in order):

1. the buffer protocol
2. `__array_interface__`
3. `__array__`

in order to turn the object into an `ndarray`. For (1) and (2) the object describes its memory layout and numpy does everything else (zero-copy if possible). For (3) the object itself is responsible for returning an `ndarray` from `__array__()`.
