### ISSUE TITLE
Error building in 32-bit PyPy 3.7

### ISSUE THREAD

**Issue by radarhere** [numpy/numpy#18297]
Over at https://github.com/python-pillow/pillow-wheels, I've found a problem when trying to install numpy 1.20.0 in 32-bit PyPy 3.7. The problem doesn't occur with numpy 1.19.5. From the errors, I would think it relates to 'multi-platform SIMD compiler optimizations' in the changelog.

Let me know if this isn't clear enough.

### Reproducing code example:

Here is the failing GitHub Actions job - https://github.com/radarhere/pillow-wheels/runs/1813058801?check_suite_focus=true#step:4:7359

### Error message:

I won't include the full log, but this should be enough to demonstrate

```
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/immintrin.h:45:0,
				 from build/src.linux-i686-3.7/numpy/distutils/include/npy_cpu_dispatch_config.h:64,
				 from numpy/core/src/common/npy_cpu_dispatch.h:36,
				 from numpy/core/src/common/npy_config.h:6,
				 from numpy/core/include/numpy/npy_common.h:10,
				 from numpy/core/src/_simd/_simd.h:16,
				 from numpy/core/src/_simd/_simd.dispatch.c.src:2,
				 from build/src.linux-i686-3.7/numpy/core/src/_simd/_simd.dispatch.avx512_skx.c:21:
/usr/lib/gcc/i686-linux-gnu/5/include/avx512fintrin.h:9538:1: note: expected 'long long int *' but argument is of type '__vector(8) long long int *'
 _mm512_mask_i64scatter_epi64 (long long *__addr, __mmask8 __mask,
 ^
cc1: all warnings being treated as errors
```

### NumPy/Python version information:

3.7.9 (7e6e2bb30ac5, Nov 18 2020, 10:58:15)
[PyPy 7.3.3-beta0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

**Comment by mattip** [comment]
@seiko2plus thoughts?

**Comment by seiko2plus** [comment]
@mattip, It a GCC bug fixed by https://github.com/gcc-mirror/gcc/commit/9cdd568036ada33c6cd7649c6f55e4359f1ca5a5 (GCC 5.5.0). I think it would better to remove `$werror` policy from the dispatch-able sources of `_simd` module and only enable it through CI. treating warnings as errors for production wasn't a good idea from the beginning. What do you think?

https://github.com/numpy/numpy/blob/7a18e4ac4f0b9f0933a190ac25cd75729bcdd146/numpy/core/src/_simd/_simd.dispatch.c.src#L1

**Comment by seberg** [comment]
> treating warnings as errors for production wasn't a good idea from the beginning

I gree warnings as errors should only happen in CI (or alternatively development version).

**Comment by mattip** [comment]
The problem here is that
- pillow-wheels was using gcc5.4 from an Ubuntu 16.04 docker image.
- they were installing NumPy 1.20 from source.

I  think on HEAD they have moved on to use a manylinux2010 image that includes gcc 8.3.1, and now that NumPy 1.20 is released, they can use the wheel.

<details>

According to the log, Pillow used `multibuild/xenial_i686`, to both build and test. When I set up the multibuild/xenial_* docker images, I imagined they would only be used for testing, not for building (the test image can be specified via the `DOCKER_TEST_IMAGE` directive like in [numpy-wheel builds](https://github.com/MacPython/numpy-wheels/blob/master/azure-pipelines.yml#L58)). So the "official" fix for this is to build with the manylinux2010_i686 docker image (gcc 8.3.1).

**Comment by radarhere** [comment]
Thanks for the explanation. A few questions.

> I think on HEAD they have moved on to use a manylinux2010 image that includes gcc 8.3.1

I'm not following this comment at all. Which project's HEAD? pillow-wheels?

> and now that NumPy 1.20 is released, they can use the wheel.

https://pypi.org/project/numpy/1.20.1/#files only lists one PyPy wheel, and it is 64-bit.

> According to the log, Pillow used `multibuild/xenial_i686`, to both build and test. When I set up the multibuild/xenial_* docker images, I imagined they would only be used for testing, not for building (the test image can be specified via the `DOCKER_TEST_IMAGE` directive like in [numpy-wheel builds](https://github.com/MacPython/numpy-wheels/blob/master/azure-pipelines.yml#L58)).

The error is occurring during the testing phase. We're not installing numpy to distribute, but to test.

**Comment by mattip** [comment]
pillow-wheel's HEAD [passes tests](https://github.com/python-pillow/pillow-wheels/runs/1893164128?check_suite_focus=true) with PyPy-32 bit. I was wrong: both the older log you linked to and the passing log use the same docker image. I wonder what changed and why it started passing?

**Comment by radarhere** [comment]
Because the newer run contains https://github.com/python-pillow/pillow-wheels/pull/187 pinning to numpy 1.19.5 - see https://github.com/python-pillow/pillow-wheels/runs/1893164128#step:4:4983 in the run you linked to

**Comment by mattip** [comment]
Ahh. OK. So my original claim (that the wheel-building apparatus does not hit this since it uses the manylinux2010 gcc 8.3.1, where the pillow-wheel is building numpy from source with xenial's gcc 5.4) would seem to be correct. There is a binary wheel for CPython, but none for PyPy, so installing pillow's wheel needs numpy which triggers a build from source.

In any case. dropping the `-Werror` flag for sdist builds would seem to be the best way to work around this.

**Comment by charris** [comment]
I removed the milestone. If someone proposes a fix on the NumPy side, feel to add it back in.
