### ISSUE TITLE
Misleading explanation of input variable for numpy.random.poisson

### ISSUE THREAD

**Issue by liangchen1ceeee** [numpy/numpy#18314]
The original documentation is: https://numpy.org/doc/stable/reference/random/generated/numpy.random.poisson.html
The references for correction are: 
* Weisstein, Eric W. “Poisson Distribution.” From MathWorld–A Wolfram Web Resource. http://mathworld.wolfram.com/PoissonDistribution.html
* Wikipedia, “Poisson distribution”, https://en.wikipedia.org/wiki/Poisson_distribution

The original documentation for numpy.random.poisson explains parameter ***lam*** (short for lambda) as `Expectation of interval, must be >= 0. A sequence of expectation intervals must be broadcastable over the requested size.` However, ***lam*** is not the expected interval (or at least not the expected time interval of an event), but the expected number of event occurrences in a fixed time interval. 

The explanations of ***lam*** throughout this API documentation is misleading.

***lam*** in numpy is identical to ***v*** in the MathWorld reference and ***lambda*** in the Wikipedia reference.

**Comment by rkern** [comment]
You are correct.

**Comment by mattip** [comment]
PR welcome. As this is a bugfix, I think we should fix both [mtrand.pyx](https://github.com/numpy/numpy/blob/master/numpy/random/mtrand.pyx#L3514) and [_generator.pyx](https://github.com/numpy/numpy/blob/master/numpy/random/_generator.pyx#L3015)

**Comment by KamaljeetSahoo** [comment]
I would like to take a shot at this issue. 
@mattip, please help me contributing to this PR, I am a beginner to open source contribution.

**Comment by mattip** [comment]
Welcome. Information about helping with documentation is in our [documentation docs](https://numpy.org/doc/stable/dev/howto-docs.html). There are a few skills you will need to complete this task.
- Being able to use git and github to create a pull request. There are many tutorials for beginners, ours is in the [developer documents](https://numpy.org/doc/stable/dev/index.html). Please notice the PR and commit formatting style.
- Understaning how the lines I pointed to above get turned into the documentation. Those files are source files for [cython](https://cython.readthedocs.io/en/latest/), a python-like language that is processed and turned into C which is compiled into a c-extension module. The [docstrings](https://www.python.org/dev/peps/pep-0257/) of the functions and methods are parsed by [sphinx](https://www.sphinx-doc.org/en/master/) when building the documentation, and these are turned into HTML pages. To do this at home, see our [building the docs](https://numpy.org/doc/stable/docs/howto_build_docs.html) guide.
- Figuring out why there are two places that need fixing. This is due to [NEP 19](https://numpy.org/neps/nep-0019-rng-policy.html). We have two implementations of random number generation: one legacy in `mtrand` and the one you should be using in `_generator`. The latter copied the docstring from the former. While the legacy version is under a bugfix-only restriction for changes, I think this counts as a bugfix so both should be fixed.
