### ISSUE TITLE
Centering/alignment of heading in documentation seems strange

### ISSUE THREAD

**Issue by madphysicist** [numpy/numpy#18321]
## Documentation

Here is an example of a page where the heading is right-aligned:

![image](https://user-images.githubusercontent.com/4617010/106909818-43ae8280-66c6-11eb-88fb-2edc794fb548.png)

If this is a deliberate design choice, please ignore. It just looks really strange to me.

**Comment by eric-wieser** [comment]
This style was introduced deliberately in #17382 by @bjnath.

https://github.com/numpy/numpy/blob/9f12028b9453c17b72b26355fd503e512af96a5d/doc/source/_static/numpy.css#L20-L29

I also think it looks a bit odd, and personally would have diverged from the pydata theme only when it came to numpy colors and/or fonts - but I don't feel strongly enough to back those lines out.

**Comment by charris** [comment]
Looks odd to me also.

**Comment by eric-wieser** [comment]
I brought this up here:

https://github.com/numpy/numpy/pull/17382#discussion_r498226765

**Comment by seberg** [comment]
I don't mind the right alignment. But if it trips anyone, lets just undo it? Maybe one thing is that it works best only at the very top of a page and not in the middle of a long text. (Think like a chapter start in a book.)

**Comment by madphysicist** [comment]
@seberg Even then, centered would make sense, left-aligned would look good, but right-aligned is weird. I think it's legible either way, but I'll leave the issue open until the maintainers come to a consensus.

**Comment by seberg** [comment]
I honestly think chapter beginning/top of the page is simply artistic freedom. Of the few books I looked into (only 4-5 or so were a bit more fancy styled): one used right alignment (incidentally, one of the most styled ones), one used "weird" alignment (left, but multi-line was heavily indented), one did have at least an exception to left alignment in the index.
Sure most were left alignment, but most were not really styled anyway. Center seemed only/mainly a thing if the chapters were just numbers; which feels right to me).

Admittedly, the fancier ones usually offset the title by more than just bold text, e.g. a different background, which is a bit more like a website header.

I don't want to step on Ben's feet, so happy to be corrected, but I doubt you will get much more opinion/consensus. Most of us probably don't care much: so a few slight nudges toward changing it to left alignment is enough for me.

I just mention the "top vs. inline", because for me the fact that this is not limited to the top is enough to overcome my "when in doubt, stick with the status-quo" preference; simply because my working hypothesis is that Ben probably mainly looked at that when styling :).

**Comment by MarsBarLee** [comment]
I rather like the right-alignment.

I personally see right aligned headings on websites and brands as a way to purposely and artistically stand out (visually represent going 'against the grain', haha).

For documentation, I would expect it to look professional and not flashy, but the more I compare it to left-aligned, the more I like the little bit of flair, the character it adds.

Here's a preview of how it would look left-aligned, with the top two images from [Ben's PR](https://github.com/numpy/numpy/pull/17382).
![NumpyHeadingsIssue](https://user-images.githubusercontent.com/46167686/107080690-a2a3f280-67bf-11eb-8685-9ea4b9eece94.png)

I also don't feel strongly either way, unless it affects someone's ability to read or access the documentation, or if another person brought it up as an issue?

**Comment by madphysicist** [comment]
The more I look at it, the more awkward the right alignment looks. When I read the docs, I do so to get the most information in the shortest amount of time. I read English from left to right. It takes an extra moment to adjust to the weird alignment. My personal feeling is that these docs should be all about utility: form follows function and all that.

**Comment by eric-wieser** [comment]
>  my "when in doubt, stick with the status-quo" preference

My preference is the slightly different "when in doubt, stick with the default someone else chose". One benefit of doing so is that style arguments like this can be dismissed as an upstream problem.

**Comment by seberg** [comment]
One thing I just realized: The original example here is mostly a problem with the docs rather than the styling.  The `np.polynomial` module (just like `np.fft`) should have a title in its *docstring*.
That would make the "Convenience classes" a level 2 instead of level 1 header. And a level 2 header is intentionally styled in a way that it won't "disrupt" the reading flow as much.

So as long as each page has a level 1 heading at its top (which it should I assume), my argument actually becomes moot :).

I admit, the invisible paragraph symbol is slightly ugly for some long titles.  Anyway, I still think its mostly about whatever someone who cares enough prefers, and I don't care enough myself :).  Someone else in this case was Ben for me :).

**Comment by rajpratyush** [comment]
I believe instead of adding an alignment we can add a line underneath the topic so as to make it eye catching.

**Comment by madphysicist** [comment]
My overall point is that this is a technical document. Form must necessarily follow function, not the other way around. "Looking Professional" is an important consideration only as long as "Useable" has been satisfied first. Slow loading times and strange behavior on mobile are some of the unpleasant side effects the new scheme has.

**Comment by mattip** [comment]
In the latest documentation community meeting we discussed this and there was a loose consensus to move to left-aligned. PR welcome.

**Comment by madphysicist** [comment]
@mattip. Unfortunately this is not something I can currently do (assuming it involves HTML/CSS in some form, rather than just C or Python), and probably won't have the bandwidth to learn for a while.

**Comment by eric-wieser** [comment]
@madphysicist, I already opened A PR to do this, #18418

**Comment by madphysicist** [comment]
@eric-wieser 18 days ago no less. I'm not sure how I missed that given that it was right in front of me. Thank you for taking care of it.

**Comment by mattip** [comment]
Closing. #18418 was merged.

**Comment by madphysicist** [comment]
Thanks!
