### ISSUE TITLE
Incorrect result when computing 0^{complex number}

### ISSUE THREAD

**Issue by anjali411** [numpy/numpy#18378]
```py
>>> (0)**np.array([1-1j])
array([nan+nanj])
>>> (0)**torch.tensor([1-1j])
tensor([0.+0.j])
```

The correct answer here can be worked out by using limits and comes out to be 0 in the case Re(z)> 0, where z is the complex exponent. Please check out this stack exchange answer: https://math.stackexchange.com/questions/2087100/is-zero-to-the-power-of-an-imaginary-number-still-zero which explains this in detail.

**Comment by eric-wieser** [comment]
For what it's worth, Python simply refuses to compute this,
```
>>> 0**(1-1j)
ZeroDivisionError: 0.0 to a negative or complex power
```

**Comment by eric-wieser** [comment]
Although `std::pow(std::complex<double>(0), std::complex<double>(1, -1))` does give `0` as you suggest.

**Comment by seberg** [comment]
It seems we explicitly handle this here: https://github.com/numpy/numpy/blob/4b1cd4e118e543260cbe9c7fba51a1de37e03618/numpy/core/src/npymath/npy_math_complex.c.src#L455-L470

I wonder if we can get away with less special casing within NumPy here these days (and maybe avoid dealing with all these subtleties to begin with).

**Comment by seberg** [comment]
Might be good to check with python folks, but I guess raising indiscriminately is a bit different from our warning.

**Comment by prithvitewatia** [comment]
Hello, @seberg @eric-wieser I would like to try and fix this issue. But before I start working I need to know about few things.
Implementation details for case:
```
1) 0 to the power 0: Do we keep it undefined (Not a number) or 1?
https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero#Mathematical_and_scientific_software
```
```
2)  0 to the power complex: As discussed in this answer?
https://math.stackexchange.com/questions/2087100/is-zero-to-the-power-of-an-imaginary-number-still-zero
```

**Comment by seberg** [comment]
If IEEE says 0^0 is best defined as 1, we probably should just use that.

**Comment by eric-wieser** [comment]
> I wonder if we can get away with less special casing within NumPy here these days (and maybe avoid dealing with all these subtleties to begin with).

Yeah, I can't help feeling we could just use C99 complex in a lot of places now.

**Comment by prithvitewatia** [comment]
@seberg I have made the changes but could not find the tests file. Can you please help me?

**Comment by seberg** [comment]
Cool, `numpy/core/tests/test_umath.ph` and potentially also `test_scalarmath.py` are probably the best places to add them.

**Comment by seberg** [comment]
I am honestly still not quite sure what we actually want.  The wikipedia link is clear for real input, but not so much on complex. I agree that complex is somewhat defined, but how standard is that actually?

I tried just using the `cpow` as provided by C99 as I had mentioned on the PR. And as Eric says, the result is 0, but:

1. This is only the case for a real part `>0`, `0j^(0+a*1j)` gives NaN (raising to a power with a negative real part gives `inf+NaNj` which is also a NaN).
2. The example Eric gave above *does* give floating point warnings on GCC, but not ICC: https://godbolt.org/z/GsE5Msvhr  (godbold won't run MSVC, I added `-fp-model strict` for ICC since I don't trust ICC not to do bad optimizations, but not sure anyway).

@anjali411 do you have insights into what the correct error flags are, before we start working around `glibc` behaviour incorrectly (again), its super hard to get this stuff right.

**Comment by seberg** [comment]
So one thing to note that for positive real, the result is equal to 0, but the sign may switch:
```
In [39]: np.power(0-0j, 1-1j)
<ipython-input-39-4592e7f77c06>:1: RuntimeWarning: divide by zero encountered in power
  np.power(0-0j, 1-1j)
Out[39]: 0j

In [40]: np.power(0-0j, 1+1j)
<ipython-input-40-a7fd9d0e2031>:1: RuntimeWarning: divide by zero encountered in power
  np.power(0-0j, 1+1j)
Out[40]: -0j
```

I am not sure whether that is a problem or not.

**Comment by h-vetinari** [comment]
> Yeah, I can't help feeling we could just use C99 complex in a lot of places now.

I checked the current status of visual studio for this, and it's unfortunately [not even](https://developercommunity.visualstudio.com/t/Support-for-C99-Complex-numbers/1409049?space=8&q=complex) on their roadmap yet.
