### ISSUE TITLE
Result of (A - b) differs from (A - b.reshape(1)) when A,b have different float types

### ISSUE THREAD

**Issue by dkirkby** [numpy/numpy#18399]
I expected that subtracting a constant `b` from an array, `A - b`, would give identical results to `A - b.reshape(1)`.  However, I am noticing a roundoff error difference when `A` and `b` have different floating dtypes.

### Reproducing code example:

```python
import numpy as np

# EDIT (seberg) adding some seed/size:
seed = 1
size = 100

rng = np.random.RandomState(seed)
X1 = rng.uniform(size=size).astype(np.float32)
X2 = X1.copy()
    
dX = np.array([0.1, 0.2], np.float64)
  
X1 -= dX[0].reshape(1)
X1 -= dX[1].reshape(1)
    
X2 -= dX[0]
X2 -= dX[1]
    
print(X1 - X2)
```

### Error message:

There is no error message, but I expected the last line to print `[0,0]`.  Commenting out `.reshape(1)` does indeed print `[0,0]`.

### NumPy/Python version information:

1.18.1 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by seberg** [comment]
Well, this is a fun one (going for the explenation of "why" here, not really a "this is a bug/feature"):  The short answer can be found by rewriting `X1 -= dX[0].reshape(1)]` as `np.subtract(X1, dX[0].reshape(1), out=X1, casting="safe")` (which will error).

What you find is that `dX[0]` (unlike `dX[0].reshape(1)`) is considered a "scalar" because it is 0D (by NumPy). For the scalar case, NumPy will effectively subtract `np.float32(dX[0])` (see `np.result_type`, which tries to explain the behaviour).
For the "array" case, it will upcast `X1` to float64, perform the operation and then _downcast_ the result to float32 and write it back.  Which explains the error in my "replacement", since the downcast step is not "safe".  NumPy considers this `same_kind`.

The fact that this uses in-place operations, makes this all a bit more weird to be honest.

**Comment by dkirkby** [comment]
Ok, I was afraid it was something like that, but thank you for the clear explanation!

Feel free to close since it sounds like this falls in the category of unavoidable surprises.

**Comment by seberg** [comment]
> Feel free to close since it sounds like this falls in the category of unavoidable surprises.

Closing, hopefully we get a shot at fixing the "scalar" logic soon, but there is nothing very explicit to be done, i guess.
