### ISSUE TITLE
numpy.random.choice not work as expect

### ISSUE THREAD

**Issue by showkeyjar** [numpy/numpy#18533]
I use numpy.random.choice to sampling normal distribution integer number, but found it not work as expect.

### Reproducing code example:

```python
import numpy as np
import scipy.stats as ss

x = np.arange(-100, 101)
xU, xL = x + 0.5, x - 0.5
prob = ss.norm.cdf(xU, scale = 3) - ss.norm.cdf(xL, scale = 3)
prob = prob / prob.sum()
print(prob)
nums = np.random.choice(x, size = 100, replace=False, p = prob)
nums.sort()
print(nums)
```

### Error message:

you can see the output:

[-74 -73 -72 -71 -70 -69 -68 -67 -66 -65 -64 -63 -62 -61 -60 -59 -58 -57
 -56 -55 -54 -53 -52 -51 -50 -49 -48 -47 -46 -45 -44 -43 -42 -41 -40 -39
 -38 -37 -36 -35 -34 -33 -32 -31 -30 -29 -28 -27 -26 -25 -24 -23 -22 -21
 -20 -19 -18 -17 -16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3
  -2  -1   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
  16  17  18  19  20  21  22  23  24  25]

it's not normal distribution described by `prob`

when I change np.random.choice size parameter to 50, it return the correct distribution

I guess, when set `replace=False`, numpy generate a number, 
if this number has been choose, then numpy use the smallest index number, so, the results became strange. 

dose numpy.random.choice can recursively choice right number?

### NumPy/Python version information:

numpy 1.19.2 
python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

**Comment by rkern** [comment]
`replace=False` means that it will sample without replacement, which means that each draw is not independent. If you make enough draws (like half the total), then the distribution of the result won't look much like the desired weight distribution.

You can think about a degenerate situation, where you have almost all of the probability weight on one item and a very small number on the others (e.g. `p=[1-eps] + [eps/(n-1)] * (n-1)`). Once you draw `x[0]`, with `replace=False`, you can never draw it again, so you are forced to draw `i>0` for all of the remainder, which will overweight them compared to the original `p` distribution.

If you need unique values (`replace=False`), you cannot expect the result to be close to the `p` distribution except when you draw a much, much smaller number than there are in the input.

**Comment by showkeyjar** [comment]
> so you are forced to draw i>0 for all of the remainder, which will overweight them compared to the original p distribution.

why not use highest `p` score to calculate size of slider window,  and choose different number from each window?

so what ever the `size` is, it could choose like `p` distribution.

**Comment by rkern** [comment]
Ah, I think I misunderstood what you were saying was wrong. It's not that you are expecting the draws to follow the `p` distribution in detail. Rather, you were commenting on how odd it was that something that was supposed to be symmetric around 0 was so skewed towards one side of the distribution.

The answer here is that most of the `p` values are extremely tiny. With `scale=3`, your endpoints are 33 stdevs away from the mean. `prob` is being formed from subtracting _very_ close-together CDF values that are almost 0.0 on the left and almost 1.0 on the right. Because of the way the floating point number system is architected, there are a lot more distinct floating point numbers close to 0.0 than there are close to 1.0. So most of the CDF values on the right-hand side are rounded to exactly 1.0 while the CDF values on the left are distinct. Thus most of the `prob` values on the right-hand side are _exactly_ 0.0:

```
>>> prob == 0.0
array([False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True])
```

This is why you see samples down to -75 but not above 25: `p==0` for the latter, but not the former.

**Comment by rkern** [comment]
So as to your guess that the algorithm we use is intrinsically biased towards earlier entries, this isn't true. The algorithm just trusts that `p[i]==0` means that `x[i]` should never be sampled.

**Comment by showkeyjar** [comment]
ok, I got it, but it looks very strange that CDF result when `p` values are extremely tiny.

**Comment by rkern** [comment]
Floating point math just doesn't work very well at those extremes. Everything is going to look strange.

It's possible that we should extend `choice()` to allow one to pass `log(p)` instead, then we can use the [Gumbel-max trick](https://timvieira.github.io/blog/post/2014/07/31/gumbel-max-trick/) to sample. You'll still have to compute the CDF differences accurately. You could not just compute `log(prob)` since even the `cdf()` has already lost the necessary precision.

However, in the `replace=False` case for these regimes, I'm not sure what the benefit is. All of these results are kinda degenerate. If we correctly construct the weights, we'll only ever draw the same set tightly clustered around the mode, which one can compute more easily without any randomness.
