### ISSUE TITLE
Documentation of arange - format inconsistency with the rest of the documentation?

### ISSUE THREAD

**Issue by hengzhan** [numpy/numpy#18563]
## Documentation

Hi, I have some question about the [documentation page of `np.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html). Apologies if they are dumb ones.
![image](https://user-images.githubusercontent.com/50187355/110212191-4b905b00-7eee-11eb-9d18-d257a91fc2bd.png)

1. Why BNF is used in this page, i.e. why are there square brackets in the function signature? I think this only happens to `arange()`
2. Why are `dtype` and `like` not labelled as optional? How are they different from the other arguments?

Thanks!

**Comment by rkern** [comment]
1. `arange()` is an odd function.  `arange()` is like `range()` in that it just interprets 1, 2, or 3 positional arguments in different ways (i.e. `stop`, `start, stop`, and `start, stop, step`). Using these brackets is a conventional way to mark optional arguments that are intended to be provided positionally (you can see them used lots in the [Python documentation](https://docs.python.org/3/library/functions.html)). We don't usually use them because most optional arguments follow the required arguments, and we usually just rely the keyword representation to show that they are optional (it's also easier for the auto-generated docs to extract). But because `arange()` has this unique set of calling conventions, we use the bracket convention for those arguments.
2. They should be marked as optional.

**Comment by rkern** [comment]
For example, [Python 2.6 and previous](https://docs.python.org/2.6/library/functions.html#range) used to document `range()` in the same way (so this was the style we copied). However, since then, they moved to providing [2 signatures](https://docs.python.org/2.7/library/functions.html#range):

```
range(stop)
range(start, stop[, step])
```

This is easier to interpret, but may require changes to our docstring extraction system.

**Comment by hengzhan** [comment]
Wow thanks for the quick reply Robert! But in this case we are mixing 2 styles of notation to describe optional arguments. Don't you think `dtype` and `like` should also be in square brackets? Also out of curiosity, where's the doctring for `arange()`? Since it's written in C there's no def for it, and I couldn't find the docstring in its C implementation either..

**Comment by rkern** [comment]
The mixing is somewhat intentional, to convey that we expect the `start, stop, step` arguments to be provided positionally while the others really ought to be passed as keywords. `arange()` is a unique function, so it can be a little inconsistent. It could perhaps use a little more explanation of the 3 different ways to call it, though, since this is an odd convention.

The docstring is added [here](https://github.com/numpy/numpy/blob/main/numpy/core/_add_newdocs.py#L1337-L1402).

**Comment by hengzhan** [comment]
Thanks @rkern ! It does make sense to me now that you have explained it to me. I guess some work could be done to make the doc clearer. However, just by looking at the signature, I don't really think the mixing can somehow indicate "we expect the start, stop, step arguments to be provided positionally while the others really ought to be passed as keywords." The square brackets only mean optional arguments right? Also I think the default values could be included in the signature, regardless of the inclusion of the square brackets.

**Comment by rkern** [comment]
Marking `start=0` in the signature would be even more confusing, IMO, because keyword arguments can't be followed by required positional arguments. The defaults are explained in the `Parameters` section.

I wouldn't try to spend time making the signature line exactly consistent with the others. `arange()` is a unique function; it breaks the normal rules about how functions process arguments, so it's only fitting that its documentation breaks the rules for documenting the arguments, too.

If we can get the API documentation generator to accept a two-line version like the more recent Python docs for `range()`, I think that would be an improvement. The docstring could also add a paragraph to the description explicitly explaining the 1-, 2-, and 3-parameter calling conventions.
