### ISSUE TITLE
floatmode=unique sometimes giving wrong rounding

### ISSUE THREAD

**Issue by levbishop** [numpy/numpy#18609]
Let `a` be a special float64:
```python
In [26]: a = np.float64.fromhex('-1p-97')

In [27]: a
Out[27]: -6.310887241768095e-30
```

It has `uniquestra`, a shortest decimal string that uniquely identifies it (thus can be eval-ed to reproduce it exactly):
```python
In [33]: uniquestra = np.format_float_scientific(a, unique=True)

In [34]: uniquestra
Out[34]: '-6.310887241768095e-30'

In [35]: eval(uniquestra)==a
Out[35]: True
```

Because `a` is a special float, unlike most other floats, it has a correctly-rounded precision=15 decimal string _that is different from `uniquestra`_:
```python
In [36]: roundedstra = np.format_float_scientific(a, unique=False, precision=15)

In [37]: roundedstra
Out[37]: '-6.310887241768094e-30'

In [38]: eval(roundedstra)==a
Out[38]: False
```
So far, so good. This kind of thing is why `format_float_scientific` has the `unique` flag, to choose between these two cases depending on which is needed in a given situation.

The problem comes with `array2string`, who takes a `floatmode=unique` option that should give `uniquestr` and instead gives `roundedstr`. The problem is that internally `array2string` uses `FloatingFormat` which in `floatmode='unique'` mode effectively uses format_float_scientific twice: Once with `unique=True, precision=None` to figure out how many digits of precision are enough to uniquely represent the float, and then a second time with `unique=False, precision=foo` to actually do the formatting. Most of the time this correctly gives a unique representation of the float, but for a special float like `a` it fails and gives `roundedstra` instead of `uniquestra`. 

### Reproducing code example:

```python
import numpy as np
a = np.float64.fromhex('-1p-97')
assert eval(np.array2string(a, floatmode='unique'))==a
```

### NumPy/Python version information:
```
1.20.1 3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ]
```

**Comment by seberg** [comment]
Looks like a bug, probably/possibly with `dragon4` itself?  Ping @ahaldane do you know where to fix this and if we should report it "upstream"?

**Comment by ahaldane** [comment]
I think @levbishop found the problem, it is in arrayprint/FloatingFormatter rather than in dragon4.

It happens because although we use unique mode to determine the element length, when actually printing the values we switch to non-unique mode to make sure all the floats printed in scientific mode in an array have the same length (i.e, same number of digits after the decimal point) , which evidently unintentionally causes a different kind of rounding to occur.

I remember thinking about this when we updated that code, but it seems the current code solution doesn't work for these cases.

Probably we need to do is add some kind of "digits_right" or "min_digits" option to `np.format_float_scientific` (and  np.format_float_positional for symmetry), which adds extra unnecessary digits when printing in unique mode. Easiest to implement would be to just add 0s to the end, but maybe more satisfying to try to add computed digits somehow.

I'll take a deeper look later.

**Comment by seberg** [comment]
Ah, right. I thought it was weird that with identical number of digits the result depends on `unique`.  But it actually does, since `unique=True` has to find the representation actual closest, while without `unique` it has to do correct decimal rounding. Simple, but tricky :).  Probably repeating the initial report, but if anyone wonders, this sums up the fact nicely that ending in  ending in `94` is the correct decimal rounding, but is actually closer to the next smaller float:
```
In [18]: np.format_float_scientific(np.float64.fromhex('-1p-97'), 17, unique=False)
Out[18]: '-6.31088724176809444e-30'

In [19]: np.format_float_scientific(np.nextafter(np.float64.fromhex('-1p-97'), 0), 17, unique=False)
Out[19]: '-6.31088724176809374e-30'

In [20]: np.format_float_scientific(np.nextafter(np.float64.fromhex('-1p-97'), -1), 17, unique=False)
Out[20]: '-6.31088724176809584e-30'
```
