### ISSUE TITLE
The `__all__` list needs updating in numpy/lib/stride_tricks.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#18627]
It is missing `sliding_window_view`, possibly other functions.

**Comment by seberg** [comment]
Its "missinig" on purpose, because otherwise it would end up in the main namespace currently.  Although, you can add it and then remove it from the main namespace again.

The other alternative that i was thinking of was, to use the `@set_namespace` decorator to add things to the main namespace.  (The few exceptions we can set manually)
