### ISSUE TITLE
Exception not Thrown when Allocating an Array Requiring More Memory than Exists

### ISSUE THREAD

**Issue by jtquisenberry** [numpy/numpy#18621]
When allocating an array that would contain more memory (physical + virtual) than my machine has, `numpy` does not throw an exception. 

My machine has 32 GB physical memory and 64 GB virtual memory. If I run `numpy.random.randn(13 * 1024 * 1024 * 1024)`, the result should be a 104 GB array, which is bigger than the 96 GB I have. `numpy` does not throw an exception. If I run `numpy.random.randn(14 * 1024 * 1024 * 1024)`, the result should be a 112 GB array, and `numpy` does throw the `MemoryError` I expect. 

### Reproducing code example:

```python
import numpy as np
np.random.randn(13 * 1024 * 1024 * 1024)
# The machine running the code has 32 GB physical memory and 64 GB virtual memory.
# The above code fails to result in an exception.
```

### Error message:

None. There is not an error message, even though `MemoryError` is expected.

### NumPy/Python version information:

1.18.5 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]

**Comment by seberg** [comment]
This is defined by the behaviour of `malloc`.  As far as I understand, on linux, a single `malloc` can usually allocate as much as virtual memory exists, I think. If you actually use that memory, the out of memory killer will come for you unfortunately.

On windows, I am not sure. I assume the situation is largely the same.  Although windows uses a swap-file by default I thought (I very rarely use windows), is that the hardwired 64 GiB you mention?  Otherwise, I might guess that the windows swap-file makes the virtual memory size larger than you think.

In either case, I don't think we can do anything much about it, aside maybe from OS specific commands.  I tried to use `madvise` with `MADV_WILLNEED` yesterday for my system (linux), but that doesn't seem to cause page-faulting or notify that page-faulting wouldn't be possible.  So I don't know if there is anything we can change here, I somewhat doubt it.  Overcommiting memory is very common after all.

**Comment by jtquisenberry** [comment]
@seberg , the 64 GiB I mentioned is the "Virtual Memory: Max Size:" reported by `systeminfo`. I have recently observed on other machines that Windows does increase Max Size.

Thank you for confirming that the behavior is a behavior of `malloc`. In order to understand the behavior I reported, I should examine the `malloc` source.
