### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by piskvorky** [numpy/numpy#18709]
Hi, I maintain a Python library that depends on Numpy: https://github.com/RaRe-Technologies/gensim

We distribute binary wheels for Gensim, built against `oldest-numpy-version`.

Recently we started receiving a bunch of tickets from users, complaining about Numpy errors when importing Gensim: https://github.com/RaRe-Technologies/gensim/issues/3097#issuecomment-811561829, https://github.com/RaRe-Technologies/gensim/issues/3095 or https://github.com/RaRe-Technologies/gensim/issues/3092#issuecomment-811298627.

Did something happen to Numpy compatibility recently, is this expected? Are we doing something wrong?

We tried to follow [Numpy's official instructions](https://numpy.org/devdocs/user/depending_on_numpy.html#adding-a-dependency-on-numpy). Many thanks for any pointers!

Let me know if / what other info might help.

**Comment by piskvorky** [comment]
Following up: looks like our Windows build on Appveyor wasn't configured to use `oldest-numpy-version`.

So that might be the culprit, sorry for the noise.

We'll fix Appveyor & re-release. If the problem is gone, I'll close this ticket.

**Comment by llunn** [comment]
Hi folks.  

[hdbscan](https://github.com/scikit-learn-contrib/hdbscan) is also experiencing this issue.

Problem occurs in both Windows (python 3.8.8) and macOS (python 3.8.5).

Relevant stack:
```console
  File "C:\Users\Brent\AppData\Local\Programs\Python\Python38\lib\site-packages\hdbscan\__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "C:\Users\Brent\AppData\Local\Programs\Python\Python38\lib\site-packages\hdbscan\hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
  File "hdbscan/_hdbscan_linkage.pyx", line 1, in init hdbscan._hdbscan_linkage
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by seberg** [comment]
@llunn the same as for @piskvorky applies here. You have to compile NumPy with the oldest version you wish to support. The `pip` package https://github.com/scipy/oldest-supported-numpy will pick the oldest one for the specific Python version (although I am not sure it has support for Python versions that SciPy dropped as of now, that could be added easily).

Basically: If you see that error you are importing `hdbscan` on an _older_ NumPy version than it was compiled/packaged with.  But we are only forward compatible, you can run it on a newer version than it was compiled with, but not on an older one.

**Comment by bashtage** [comment]
I went through this a lot recently in a number of windows releases. 1.20 extended the struct by an int and so if you somehow build. On 1.20 you will get this later. I only fixed it be carefully pinning in my pyproject.toml file.

**Comment by bashtage** [comment]
https://github.com/bashtage/linearmodels/blob/main/pyproject.toml

**Comment by seberg** [comment]
Did these fixes percolate through the ecosystem (hopefully smoothly) by now?  I hope the new documentation is sufficient of a "fix" from our side or is there anything else we can do to smoothen out the wrinkles?

**Comment by piskvorky** [comment]
Haven't heard of any further trouble from our side (Gensim), so closing. Thanks @seberg

**Comment by cchd0001** [comment]
Instead of using pip, I use conda and solved this problem.

**Comment by piskvorky** [comment]
@seberg the same problem happened again, so let me reopen here.

Could you please look at the investigation here https://github.com/RaRe-Technologies/gensim/issues/3226#issuecomment-917344306 and let us know if we're doing something wrong? Why the compatibility cutoff at numpy 1.17.0, versus `oldest-supported-numpy`?

**Comment by mattip** [comment]
I commented there. While you can build and test against NumPy 1.14.5 if you wish, then your code cannot use any python or C functions that appeared later. I think you are using `numpy.random.default_rng()`, which first appeared in NumPy 1.17

**Comment by seberg** [comment]
The only thing I know that would help is improving that error message or removing under certain conditions which apply here: [Cython Issue](https://github.com/cython/cython/issues/4366)

I am actually unsure what will happen if Cython would remove the error here.  Things should still fail since the NumPy API version changed (not ABI!), but at least it is more informative.

**Comment by MaartenGr** [comment]
Hi all, for a while now the Github Actions workflow for [BERTopic](https://github.com/MaartenGr/BERTopic) has been running without any issues. However, after merging a very minor change (a [spelling error](https://github.com/MaartenGr/BERTopic/actions/runs/1649121335) in documentation), the pipeline suddenly gives the well-known error of:

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

From what I could gather in this issue, I needed to set `oldest-supported-numpy` in `pyproject.toml` to compile NumPy with the oldest version to prevent any ABI issues. Unfortunately, it did not seem to work for me as I continue getting the error. Between the most recent workflow and the one before that, I believe that NumPy 1.22.0 was released which might be related. 

As you might have guessed, I am grasping at straws here and not entirely sure which next steps to take. Any help is highly appreciated! 

A few things to note:
* BERTopic requires numpy>=1.20.0
* This issue appeared before somewhere in February but was fixed by setting numpy>=1.20.0
* The branch in which I am currently working can be found [here](https://github.com/MaartenGr/BERTopic/tree/workflow-fix)

What I have tried so far in a [PR](https://github.com/MaartenGr/BERTopic/pull/391) for this issue:
* Fix and install numpy==1.20.3 before installing BERTopic
* Since the 1.22.0 release of numpy was released only a few days ago, it might be an issue with updated wheels
    * So I tried to install numpy with `pip install numpy==1.20.3 --no-cache-dir` before installing BERTopic
* Created a `pyproject.toml` and included `oldest-supported-numpy` to make sure that an older numpy version is installed to that it is compatible with newer versions

**Comment by bashtage** [comment]
It appears that the culprit is [hdbscan](https://github.com/scikit-learn-contrib/hdbscan). Can you tell what they build their wheels using?

**Comment by MaartenGr** [comment]
@bashtage Thanks for the quick reply! I am not that familiar with wheels, so I am not entirely sure but reading through the [logs](https://github.com/MaartenGr/BERTopic/actions/runs/1648340427) it seems to be following:

`Created wheel for hdbscan: filename=hdbscan-0.8.27-cp38-cp38-linux_x86_64.whl size=3858131 sha256=363e9074efe1c66e27274480f7937dd6d1e187e62119602cae0193bb17c82989`

A previous, succesful run: 

`Created wheel for hdbscan: filename=hdbscan-0.8.27-cp38-cp38-linux_x86_64.whl size=3858252 sha256=c6374409ee84bd660a0d57054ba750cd7f63adb35baf9ba72a81f66369112e22`

Out of curiosity, why does it appear that the culprit is hdbscan?

**Comment by bashtage** [comment]
The error comes from `hdbscan/_hdbscan_linkage.pyx`
```
ImportError while loading conftest '/home/runner/work/BERTopic/BERTopic/tests/conftest.py'.
tests/conftest.py:1: in <module>
    from bertopic import BERTopic
bertopic/__init__.py:1: in <module>
    from bertopic._bertopic import BERTopic
bertopic/_bertopic.py:21: in <module>
    import hdbscan
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/hdbscan/__init__.py:1: in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/hdbscan/hdbscan_.py:21: in <module>
    from ._hdbscan_linkage import (single_linkage,
hdbscan/_hdbscan_linkage.pyx:1: in init hdbscan._hdbscan_linkage
    ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by bashtage** [comment]
You should be able to pin your tests to the latest successful run packages and have it pass. This might not help your users who install newer versions though.

**Comment by roy-sr** [comment]
pip uninstall bertopic
pip install numpy==1.20.3 --no-cache-dir
pip install bertopic
pip uninstall hdbscan
pip install hdbscan --no-cache-dir --no-binary :all:

**Comment by bashtage** [comment]
Maybe also 
```
pip install hdbscan --no-cache-dir --no-binary :all: --no-build-isolation
```

**Comment by MaartenGr** [comment]
I think I narrowed down the issue. If I install  `HDBSCAN` in isolation, it runs without any problems. However, when I add `umap-learn`, it starts failing because it seems that UMAP has the tendency to take a lower version of numpy than was already downloaded by HDBSCAN. 

If I have the following requirements:
```
numpy>1.20.0
hdbscan>=0.8.27
umap-learn>=0.5.0
```
HDBSCAN starts collecting `numpy-1.22.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` but for some reason then starts collecting `numpy-1.20.2-cp38-cp38-manylinux2010_x86_64.whl` even though numpy 1.22.0 is fully supported by all of the above packages. Note that python 3.7 passes without issues and python 3.8 gives the error. 

However, if I install it with the following:
```
numpy>1.20.3  # This is set a bit higher compared to the reqs above
hdbscan>=0.8.27
umap-learn>=0.5.0
```

HDBSCAN start again collecting `numpy-1.22.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` and does not start gathering any other numpy version, passing without any issues! 

Any idea why this is happening?

**Comment by seberg** [comment]
A workaround may be to use `--no-build-isolation` in pip?  My guess is the problem here is `hdbscan`. `hdbscan` should use something like [`oldest supported numpy`](https://pypi.org/project/oldest-supported-numpy/) in its install requirements, rather than NumPy itself.

**Comment by MaartenGr** [comment]
That's the thing, `hdbscan` is using `oldest-supported-numpy` in its [pyproject.toml](https://github.com/scikit-learn-contrib/hdbscan/blob/master/pyproject.toml) which should have resolved this issue quite a while ago. To me, this seems to be related to the recent Numpy 1.22.0 release as it suddenly started happening after that. Likewise, if BERTopic is also build against `oldest-supported-numpy` the issue still persists. Does anybody have any idea why this does not work? 

For now, it seems that setting `numpy>1.20.3` solves the issue but I am a bit afraid of what happens whenever numpy releases a new minor version.

**Comment by seberg** [comment]
Seems the reason is simple: `hdbscan` uses old-supported-numpy, but it is not part of the released version published on pip.  That one just uses `numpy`.

**Comment by MaartenGr** [comment]
Ugh, you have got to be kidding me 🤣 Spend an enormous amount of debugging only to find out that simply using the master branch fixes the issue... Thanks all for the help, I'll relay this to the `hdbscan` package and see if they can release a new pip version.

**Comment by seberg** [comment]
Seems this could have been closed again a long time ago, even if (of course) projects will occasionally run into these issues due to compiling against a newer NumPy version.
