### ISSUE TITLE
mixed indexing transposes arrays

### ISSUE THREAD

**Issue by HeikoSchuett** [numpy/numpy#18730]
I recently tried to use mixed indexing, i.e. using both a boolean index and a normal index slicing in an array and this surprisingly transposed the resulting array. 
This does not happen when I slice in steps or when I select the same rows using their indices. This appears to be wrong.

### Reproducing code example:

For example if I take a 3D array and index the first and last slices I get the effect:

```python
import numpy as np
x = np.random.rand(10, 11, 12)
print(x[3, :, 6:].shape) 
# (11, 6) as expected
print(x[3, :, np.arange(12) > 5].shape) 
# (6, 11) wrong way around 
print(x[3][ :, np.arange(12) > 5].shape) 
# (11, 6) correct again
```

### Error message:

no error messages are produced

### NumPy/Python version information:

1.19.2 3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ]

**Comment by shoyer** [comment]
This is expected behavior, although many of us agree that it's not intuitive.

See "Combining advanced and basic indexing" in the NumPy indexing docs:
https://numpy.org/doc/stable/reference/arrays.indexing.html#combining-advanced-and-basic-indexing

Indexing like `x[3, :, np.arange(12) > 5]` triggers the case of "The advanced indexes are separated by a slice"

**Comment by seberg** [comment]
Indeed, going to close the issue as there is nothing to be done about this exactly (aside possibly making it clearer in the docs, but its one of those things that are pretty niche until you happen to run into it).  (There is the [NEP 21 draft](https://numpy.org/neps/nep-0021-advanced-indexing.html) which offers some way forward, but its a bigger issue.)
