### ISSUE TITLE
CI: towncrier if failing for release notes

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#18788]
The release note creation is currently failing due to: https://github.com/twisted/towncrier/pull/341

We can fix this by calling `towncrier build` instead of `towncrier`, which I will probably just do in a bit unless over at `towncrier` they decide it was a bad change.

**Comment by altendky** [comment]
I do think it's a bad change as is.  I also think the default subcommands should probably be used as a transitional tool, not a permanent cli.  Sorry for tripping you up here.

Side note, are you using towncrier from git due to the long break in releases?  I can't go guaranteeing future timely releases, but at least there's 21.3.0 from recently if you wanted to get back to a regular version.

**Comment by seberg** [comment]
We just switched to the PyPi version and stopped using the dev version anymore.  I suppose that would have been enough then, but its fine, just change back at some point (its just 3 lines, two of which are docs).

Back in the day, I had made a few changes in towncrier to make it work for NumPy at the time.  The current release was simply the first that included those (and I had missed it until now).  I doubt we need new features/changes timely anytime soon.  Thanks for taking care of towncrier and making releases though!
