### ISSUE TITLE
verbosity argument help text in runtests.py is not clear

### ISSUE THREAD

**Issue by chtrac** [numpy/numpy#18804]
## Documentation
I was struggling a bit to get the verbosity level I wanted when running runtests.py.

The correct way to get e.g. verbosity level 3 passed to pytest is by sending -vvvv to runtests (4 v, which then subtracts one before passing it along to pytest). My initial attempt was --verbose 3, and I had to dig into the code to understand what was going on.

The help text simply says _"more verbosity"_, which I don't think really explain how to use it. Perhaps the help text could be made more clear? E.g. "adds one verbosity level to pytest".

**Comment by mattip** [comment]
Thanks, this is helpful since the numpy core team does not really use the `--help` anymore. Would you like to make a PR? I wonder why we have a default of 1 in the `test` function
https://github.com/numpy/numpy/blob/cffb693566360e33c76ef6d9981ced15dbebacff/numpy/testing/_private/nosetester.py#L326

**Comment by cdahlin** [comment]
>I wonder why we have a default of 1 in the test function

It seems like the verbosity works this way:
1. runtests has a verbosity starting at 1, and each -v adds 1 to this.
2. If runtests verbosity is > 1, it sets pytest verbosity level to [runtests verbosity level] - 1:
https://github.com/numpy/numpy/blob/cffb693566360e33c76ef6d9981ced15dbebacff/numpy/_pytesttester.py#L180-L181

A -vv flag to runtests then gives pytest a -vv flag as well, as would be expected. (I got this wrong in my original comment).

Having verbosity starting at 1 works. But since it just passes along the verbosity to pytest , which has a verbosity starting at 0, I think it makes it more difficult to read and understand the code.

Do you think it would make sense to refactor the code to make verbosity starting at 0 for runtests?

> Would you like to make a PR?

Certainly. I'll just await the opinion on whether to refactor or just change the help text, and then get started.

**Comment by mattip** [comment]
> Do you think it would make sense to refactor the code to make verbosity starting at 0 for runtests?

Unfortunately this would break possible existing code that uses `--verbosity=2", so it would need to be done carefully. One thought that pops to mind is to add an additional `--legacy-verbosity` argument to `PytestTester.test`. If that is missing, we would begin emitting a `DeprecationWarning`, saying that at some future point the default behavior will change. If it is `True` (the default for now), use 1-based verbosity. If it is `False` (the default in the future), use 0-based verbosity.

I wonder about the added value of going down that path.

**Comment by reshamas** [comment]
@mattip 
Should this issue be closed?  Or is there more work to do on it?

**Comment by mattip** [comment]
I think the complications of trying to change the value of the verbosity argument outweigh the advantages. A case could be made for making the help more descriptive, since the "Default is 0" actually refers to pytest's value, the value of this argument is 1.
https://github.com/numpy/numpy/blob/b2e7534466abd6eded6b4d154fa0ea2a74369607/runtests.py#L80-L81

**Comment by seberg** [comment]
Runtests doesn't really exist anymore, so closing.
