### ISSUE TITLE
np.isreal(None) is True

### ISSUE THREAD

**Issue by gyu-don** [numpy/numpy#18814]
`np.isreal(None)` returns `True`.
It is not an expected result, it should return `False` or be described in the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.isreal.html).

### Reproducing code example:

```python
import numpy as np

print(np.isreal(None)) # => True
```

### NumPy/Python version information:

- 1.20.1 3.7.8 | packaged by conda-forge | (default, Jul 23 2020, 03:54:19) [GCC 7.5.0] 
- 1.19.2 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]

**Comment by seberg** [comment]
The problem is that `array.imag` is poorly defined for object arrays.  The function itself is more of an is-not-complex check right now that doesn't generalize to object arrays at all.  We probably should figure out a solution for object arrays (maybe even deprecating `arr.imag` for them!), but until then a tweak of the documentation might make it a bit more clear.  Although, I am not exactly sure how.

**Comment by amrit110** [comment]
Hi, can I take this up as first issue? I can add a clarification to the docstring to be more explicit that the return val is True when input is non-numeric array_like.
