### ISSUE TITLE
AWS Lambda (SAM) Fails to Build Since the 1.20.3 release

### ISSUE THREAD

**Issue by zachl123** [numpy/numpy#18988]
If we add 'numpy==1.20.2' requirements.txt, it resolves the following issue

2021-05-10 20:35:16,558 | Final missing wheels: {numpy==1.20.3(wheel)}
2021-05-10 20:35:19,015 | PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {numpy==1.20.3(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {numpy==1.20.3(wheel)}

Build Failed

**Comment by mattip** [comment]
Something is weird with the wheel naming. [The files](https://pypi.org/project/numpy/1.20.3/#files) for manylinux have names with the glibc-based name like the `manylinux_2_12_x86_64` in
```
numpy-1.20.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl 
```

I wonder where that came from? The comparable 1.20.2 wheel is
```
numpy-1.20.2-cp37-cp37m-manylinux2010_x86_64.whl
```

**Comment by charris** [comment]
I did notice that `main` and `v1.20.x` are using different submodule versions.

**Comment by charris** [comment]
Rechecking more carefully, the only difference between 1.20.2 and 1.20.3 is the BUILD_COMMIT, the submodules are the same.

**Comment by charris** [comment]
No, Travis didn't work either. Hmm, maybe the docker files?

**Comment by charris** [comment]
The Windows and Mac files are good.

**Comment by charris** [comment]
So maybe a pip upgrade is needed.
```
charris@fc [~]$ python -mpip download numpy
Collecting numpy
  Downloading numpy-1.20.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.4 MB)
     |████████████████████████████████| 15.4 MB 3.5 MB/s 
Saved ./numpy-1.20.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Successfully downloaded numpy
charris@fc [~]$ python -mpip --version
pip 21.1.1 from /home/charris/.local/lib/python3.9/site-packages/pip (python 3.9)
```

**Comment by rgommers** [comment]
Having both seems like an abuse of the platform tag, and wheel filenames are getting a bit ridiculous. If this was on purpose upstream, it'd be nice to reconsider.

**Comment by mayeut** [comment]
The platform tags `manylinux_2_12_x86_64.manylinux2010_x86_64`  comes from the auditwheel upgrade in the manylinux images.
auditwheel now follows [PEP600](https://www.python.org/dev/peps/pep-0600/) which states that the platform for such a wheel is `manylinux_2_12_x86_64`.
For backward compatibility with older tools, it should also be aliased `manylinux2010_x86_64`.

And indeed, pip 19.0 works with such a wheel. pip 9.0 doesn't know either one of those tags:
```
[root@a32c3f5d5529 ~]# ./pip9/bin/python -m pip download numpy
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/f3/1f/fe9459e39335e7d0e372b5e5dcd60f4381d3d1b42f0b9c8222102ff29ded/numpy-1.20.3.zip (7.8MB)
    100% |████████████████████████████████| 7.8MB 179kB/s 
  Saved ./numpy-1.20.3.zip
Successfully downloaded numpy
You are using pip version 9.0.0, however version 21.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@a32c3f5d5529 ~]# ./pip19/bin/python -m pip download numpy
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/cc/7f/0d414a6826b626c6fea98d98336e1f62cf9dd387c776da8dc83ce2a082b6/numpy-1.20.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.4MB)
    100% |████████████████████████████████| 15.4MB 1.4MB/s 
  Saved ./numpy-1.20.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Successfully downloaded numpy
You are using pip version 19.0, however version 21.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@a32c3f5d5529 ~]# ./pip21/bin/python -m pip download numpy
Collecting numpy
  File was already downloaded /root/numpy-1.20.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Successfully downloaded numpy
```

Those names are perfectly valid names that follow [PEP427](https://www.python.org/dev/peps/pep-0427/)
It's not an abuse of the platform tag at all.
This kind of tag has been used for a long time, mostly on the implementation tag where we are (were) used to see `py2.py3`.
It's also been used on the platform tag on macOS because of the intel/ppc/universal/arm64/universal2 compatibility.
e.g. if you create a universal2 wheel that should be downloaded by all pip versions, whatever your platform, you have to use the platform tag `macosx_10_9_x86_64.macosx_10_9_universal2.macosx_11_0_arm64.macosx_11_0_universal2` (`macosx_10_9_universal2 ` being the one you created)
Yes, in this specific case they mean the same thing but it should not matter.

I'd rather see the following piece of code from AWS fixed to follow [PEP427](https://www.python.org/dev/peps/pep-0427/) than undo things in auditwheel that do follow this almost 10 year old spec:
https://github.com/aws/aws-lambda-builders/blob/b663326079c871e50f1545f36f9695f6958cfaa2/aws_lambda_builders/workflows/python_pip/packager.py#L342-L366

I'm nevertheless open to other proposals than just "revert" over at auditwheel.
If a quick fix must happen for numpy, then pinning the manylinux2010+ images to `2021-05-05-1ac6ef3` and manylinux1 images to `2021-05-05-b64d921` will fix things for now (commit before auditwheel update).

**Comment by charris** [comment]
@mayeut Looks like the relevant AWS problem is up at line 153:
```
    _MANYLINUX_COMPATIBLE_PLATFORM = {
        "any",
        "linux_x86_64",
        "manylinux1_x86_64",
        "manylinux2010_x86_64",
        "manylinux2014_x86_64",
    }
```

**Comment by rgommers** [comment]
> If a quick fix must happen for numpy,

I don't think that's the case (yet), this is the first problem that's reported, and it seems like it can be fixed on the AWS side - and we can always pull the wheels or put out a 1.20.4 if needed.

> This kind of tag has been used for a long time

Well, you changed tags for manylinux1/2010/2014 very recently for no good reason. The old naming scheme worked and was much more human-readable than the new duplicate-tag names. When introducing PEP 600 support, I don't see that should necessarily have included changing behavior for the older PEPs.

PEP 600 talks about aliases (https://www.python.org/dev/peps/pep-0600/#legacy-manylinux-tags), not to use both.

**Comment by mayeut** [comment]
@charris, in fact the problematic line is L346:

```diff
--- a/aws_lambda_builders/workflows/python_pip/packager.py
+++ b/aws_lambda_builders/workflows/python_pip/packager.py
@@ -343,7 +343,7 @@ class DependencyBuilder(object):
         wheel = filename[:-4]
         implementation, abi, platform = wheel.split("-")[-3:]
         # Verify platform is compatible
-        if platform not in self._MANYLINUX_COMPATIBLE_PLATFORM:
+        if self._MANYLINUX_COMPATIBLE_PLATFORM.isdisjoint(platform.split(".")):
             return False
 
         lambda_runtime_abi = get_lambda_abi(self.runtime)
```

**Comment by mattip** [comment]
@mayeut what is the motivation to use both aliases?

**Comment by mayeut** [comment]
@mattip,

There was feedback to get the PEP600 platform tag in the repaired wheel because:
- Some people found that the PEP600 platform tag conveys more meaning than the old one
- PEP600 is the only active manylinux spec

Replacing the old platform tag by the new one would just have break the whole ecosystem so, to answer the 2 points raised above, risk assessment was done on using both the PEP600 platform tag & the old platform tag in the filename (& in the metadata as well) in order to present the new platform tag. Given that it respects PEP427 and that pip [8.1, 21.0.1] could install those wheels, the risk was considered low enough.

Nevertheless, being a major behavior change, the major version of auditwheel was bumped from 3 to 4.

**Comment by rgommers** [comment]
Thanks for the explanation @mayeut. Can you link to that discussion?

**Comment by rgommers** [comment]
Also a note on the macOS similarity: that's not actually the same. We are compiling against an SDK there, so those `macosx_10_6...`, `macosx_10_6...` indicate differences in builds. That we had to add `10_9` to indicate compatibility with two SDKs is unfortunate, but that doesn't make them aliases. Wheels compiled against `10_9` will crash when you run them on <10.9.

**Comment by mayeut** [comment]
> Can you link to that discussion?

Unfortunately, as is the case with this thread, most discussions happen in other places than the auditwheel repo and I forgot (my bad) to link the relevant discussion in the PR in auditwheel...
We were not planning on changing the behavior at first (this I can find a discussion for: https://github.com/joerick/cibuildwheel/pull/595#issuecomment-780151594) but had my mind changed elsewhere, proposed a PR which was reviewed and accepted.

> Also a note on the macOS similarity ... but that doesn't make them aliases.

Yes I did mention that, maybe poorly: 
> Yes, in this specific case they mean the same thing but it should not matter.

The specific case being `manylinux_2_12_x86_64.manylinux2010_x86_64`.

If only looking at active specifications and trying to achieve a single platform tag, we should have:
- `manylinux_2_12_x86_64` for the NumPy manylinux wheel
- `macosx_10_9_universal2` for the macOS wheel sample

In both cases, the added platform tags serve the same purpose (even if they don't have the same meaning), allow those wheels to be installed with tools not supporting the new tags yet (and/or working around bugs in an implementation of the new platform tag which is the case for `macosx_11_0_universal2` presence).

**Comment by rgommers** [comment]
Okay, thanks @mayeut. I don't think this was a good decision, but also I don't see a reason to ask for a temporary revert - that would just include the workload on `auditwheel`. 

If more problems show up here, we'll anyway have to do a numpy 1.20.4, and then we can pin to `auditwheel < 4.0`

**Comment by mattip** [comment]
I opened an issue in multibuild to figure out how to pin the docker image there to a specific version.

**Comment by rgommers** [comment]
I think we're good on wheel naming here, we didn't have more problems.

Regarding the original bug report about a build issue on AWS Lambda: I assume that has been resolved, since there are no more complaints. Note that there was a time when Amazon Linux wasn't compatible with manylinux (should be fixed now) and also that there are pre-made Lambda Layers available in multiple places: https://github.com/keithrozario/Klayers

I'll close this, since we should be good here.
