### ISSUE TITLE
REL: Names needed.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#19015]
The NumPy 1.21.x branch is coming up. Could the folks pinged below reply with their preferred name and mailing address so that they can be properly credited in the changelog.

- [ ] @DWesl
- [ ] @EvaJau
- [ ] @Illviljan
- [x] @Mukulikaa
- [x] @Neil
- [ ] @Patrick
- [ ] @Scian
- [x] @alize-papp
- [x] @daaawx
- [x] @drhpc
- [ ] @h6197627
- [ ] @jbCodeHub
- [x] @lbogula
- [ ] @legoffant
- [x] @mdubravski
- [x] @mecopur
- [x] @pmav99
- [ ] @sfolje0
- [ ] @tautaus
- [x] @yetanothercheer
- [x] @zolboo1024

**Comment by Mukulikaa** [comment]
Preferred name - Mukulika
Email - ***@***.***

Thanks!

**Comment by neil** [comment]
Sorry, you’ve got the wrong neil there

**Comment by drhpc** [comment]
Am 14. Mai 2021 18:22:39 MESZ schrieb Charles Harris ***@***.***>:
>The NumPy 1.21.x branch is coming up. Could the folks pinged below
>reply with their preferred name and mailing address so that they can be
>properly credited in the changelog.
>
>- [ ] @drhpc

Dr. Thomas Orgis ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by pmav99** [comment]
pmav99: Panos Mavrogiorgos pmav99@gmail.com

**Comment by mecopur** [comment]
mecopur: 	Meltem Eren Copur 
			***@***.***

**Comment by alize-papp** [comment]
Alizé Papp 68250865+alize-papp@users.noreply.github.com

**Comment by daaawx** [comment]
Dario Mory
***@***.***

**Comment by rgommers** [comment]
@charris could you please manually add @lkopf (`Laura Kopf 60775505+lkopf@users.noreply.github.com`). Her co-authorship got lost, see https://github.com/numpy/numpy/pull/18959#issuecomment-836277809.

**Comment by charris** [comment]
@rgommers Laura Kopf already shows up in the trial changelog:
```
* Kulin Seth +
* Laura Kopf +
* Laura Martens +
```

**Comment by charris** [comment]
@neil Sorry about that, github lowercased the capitalized Neil, I should have caught it.

**Comment by zolboo1024** [comment]
Hello!

Thanks for reaching out!
zolboo1024- Zolboo E ***@***.***)

Best,
Zolboo
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Charles Harris ***@***.***>
Sent: Friday, May 14, 2021 12:22 PM
To: numpy/numpy
Cc: Erdenebaatar, Zolboo; Mention
Subject: [numpy/numpy] REL: Names needed. (#19015)

Caution:This email originated from outside of the College. Do not click links or open attachments unless you recognize the sender and know the content is safe. Report anything suspicious to the HelpDesk.


The NumPy 1.21.x branch is coming up. Could the folks pinged below reply with their preferred name and mailing address so that they can be properly credited in the changelog.

  *    @DWesl<https://github.com/DWesl>
  *    @EvaJau<https://github.com/EvaJau>
  *    @Illviljan<https://github.com/Illviljan>
  *    @Mukulikaa<https://github.com/Mukulikaa>
  *    @neil<https://github.com/neil>
  *    @patrick<https://github.com/patrick>
  *    @scian<https://github.com/scian>
  *    @alize-papp<https://github.com/alize-papp>
  *    @daaawx<https://github.com/daaawx>
  *    @drhpc<https://github.com/drhpc>
  *    @h6197627<https://github.com/h6197627>
  *    @jbCodeHub<https://github.com/jbCodeHub>
  *    @lbogula<https://github.com/lbogula>
  *    @legoffant<https://github.com/legoffant>
  *    @mdubravski<https://github.com/mdubravski>
  *    @mecopur<https://github.com/mecopur>
  *    @pmav99<https://github.com/pmav99>
  *    @sfolje0<https://github.com/sfolje0>
  *    @tautaus<https://github.com/tautaus>
  *    @yetanothercheer<https://github.com/yetanothercheer>
  *    @zolboo1024<https://github.com/zolboo1024>

**Comment by yetanothercheer** [comment]
yetanothercheer
yetanothercheer@protonmail.com

Thanks! 🥳

**Comment by lbogula** [comment]
Lbogula 81459927+lbogula@users.noreply.github.com

**Comment by mdubravski** [comment]
Hi,

Michael Dubravski 
mdubravski@gmail.com

Thanks,
Michael Dubravski
