### ISSUE TITLE
Warning in refguide check

### ISSUE THREAD

**Issue by charris** [numpy/numpy#19076]
In numpy.core `Warning: overflow encountered in short_scalars`. There isn't enough information in the output to pin it down further. Can we add an option to the refguide check to make its output more verbose and better formatted?

**Comment by mattip** [comment]
It is coming from https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/_ufunc_config.py#L93 when no error handler is set. 

The default is to print directly to stderr. I am not sure how we can expose this since refguide_check.py works hard to buffer the stdout (but not stderr), we would either have to add stderr to refguide_check or have a mode like `pytest -s` to not capture any output. Rather than touch refguide-check, I think we should move to https://github.com/astropy/pytest-doctestplus, xref issue #15845

**Comment by charris** [comment]
@mattip Looks like the warning is intended? Perhaps it should be included in the example as intended output.

**Comment by charris** [comment]
Maybe something like
```
>>> np.int16(32000) * np.int16(3)
<stdin>:1: RuntimeWarning: overflow encountered in short_scalars  # may vary
30464
```

**Comment by mattip** [comment]
>The problem is that doctest doesn't capture the output.

Should we really be writing directly to c-level `stderr`? If this line wrote to `sys.stderr.fileno()` instead we would capture it
https://github.com/numpy/numpy/blob/f9a1f3199623d48a4aeaacdcbae6a1851e125cb4/numpy/core/src/umath/extobj.c#L85

There is also the same problem in `arraydescr_dealloc`

https://github.com/numpy/numpy/blob/f9a1f3199623d48a4aeaacdcbae6a1851e125cb4/numpy/core/src/multiarray/descriptor.c#L1849

and many places in the code when we use ` printf(...)` for debugging which also could be converted to use `sys.stdout.fileno()`.

There is some [trickery we could use](https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/) (a windows version is in the [gist at the end](https://gist.github.com/natedileas/8eb31dc03b76183c0211cdde57791005)) to duplicate c-level stderr in refcheck_guide, but I think the energy would be better spent converting the doctests to use pytest-doctestplus or to fix that line to write to `sys.stderr.fileno()`

**Comment by seberg** [comment]
Very sure I fixed this in the drive to use doctestplus.
