### ISSUE TITLE
CPU feature detection is broken/incorrect when using Intel compilers 2021 update 2

### ISSUE THREAD

**Issue by boegel** [numpy/numpy#19084]
When compiling numpy 1.20.3 with Intel compilers 2021 update 2 (latest release to date) with `--cpu-baseline native` (because `-xHost` is used in `$CFLAGS`), the detection of CPU features isn't being done correctly.
I'm not seeing this problem when compiling with GCC 10.3.0 on the same system.

On an Intel Skylake X system (Xeon Gold 6140), the compiler crashes (only) when compiling the `cpu_avx512_knm.c` C test program which uses intrinsics to check for the support of a specific feature. That's probably a compiler bug, but it breaks the detection mechanism used by numpy...
One way around this is to compile with `-O0`, but I'm not sure if that makes sense?

I used `-O0` to work around that issue, but even then the detection seems to be done incorrectly.

There are no errors mentioned in the output when testing for supported features, and this is reported at the end:

```
  CPU baseline  :
    Requested   : 'native'
    Enabled     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
    Flags       : -xICELAKE-CLIENT
    Extra checks: AVX512F_REDUCE AVX512BW_MASK AVX512DQ_MASK

  CPU dispatch  :
    Requested   : 'max -xop -fma4'
    Enabled     : none
    Generated   : none
```

Several of these CPU features, like `AVX512_KNL`, are not supported by Intel Skylake X (although the Intel compiler does support them).

When compiling with `GCC` 10.3.0, the output is correct w.r.t. CPU baseline vs dispatch:

```
CPU baseline  :
  Requested   : 'native'
  Enabled     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX
  Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq
  Extra checks: AVX512F_REDUCE AVX512BW_MASK AVX512DQ_MASK

CPU dispatch  :
  Requested   : 'max -xop -fma4'
  Enabled     : AVX512_KNL AVX512_KNM AVX512_CLX AVX512_CNL AVX512_ICL
  Generated   : none
```

The [documentation](https://numpy.org/devdocs/reference/simd/simd-optimizations.html) mentions that CPU features that are not supported by the host platform or the compiler should be skipped, but that doesn't seem to be the case...

I took a quick look at the code in `numpy/distutils/ccompiler_opt.py`, and it seems that the `feature_is_supported` method only checks for compiler support via `feature_test`, it doesn't try to run the compiled test programs at all?
That doesn't match the `"Check if a certain CPU feature is supported by the platform and compiler."` docstring in `feature_is_supported`, but perhaps I'm interpreting that incorrectly, or I'm missing something.

Trying to run the compiled test program `cpu_avx512_knl.c` manually results in a failure, as expected:

```
$ ./cpu_avx512_knl
Illegal instruction
```

Isn't the intention to also *run* these (rather than just compile them) to detect whether the CPU features are actually supported?

It's not clear to me why the current mechanism works as expected when using GCC 10.3.0...
How is the discrimination between baseline and dispatch CPU features done?

The installation actually completes, but the result doesn't work at all, it leads to trouble on `import numpy`, which triggers an error reporting that `AVX512_KNL` is not supported (see traceback below).

### Reproducing code example:

* build numpy from source with Intel compilers 2021 update 2 using `--cpu-baseline native`, and install it;
* try to `import numpy` using that installation;

### Error message:

* internal compiler error when checking for support for `AVX512_KNM` feature:

```
CCompilerOpt.feature_test[1444] : testing feature 'AVX512_KNM' with flags (-xKNM)
C compiler: icc -fPIC -fp-model strict -O3 -fomit-frame-pointer -qopenmp

compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/software/Python/3.9.5-GCCcore-10.3.0/include/python3.9 -Ibuild/src.linux-x86_64-3.9/numpy/core/src/common -Ibuild/src.linux-x86_64-3.9/numpy/core/src/npymath -c'
extra options: '-xKNM -Werror'
CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[711] : Command (icc -fPIC -fp-model strict -O3 -fomit-frame-pointer -qopenmp -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/software/Python/3.9.5-GCCcore-10.3.0/include/python3.9 -Ibuild/src.linux-x86_64-3.9/numpy/core/src/common -Ibuild/src.linux-x86_64-3.9/numpy/core/src/npymath -c /tmp/numpy-1.20.3/numpy/distutils/checks/cpu_avx512_knm.c -o /tmp/eb-5n40d3vl/tmpx45c9w98/tmp/numpy-1.20.3/numpy/distutils/checks/cpu_avx512_knm.o -MMD -MF /tmp/eb-5n40d3vl/tmpx45c9w98/tmp/numpy-1.20.3/numpy/distutils/checks/cpu_avx512_knm.o.d -xKNM -Werror) failed with exit status 4 output ->
": internal error: IERROR_MODULE_ID_1102

compilation aborted for /tmp/numpy-1.20.3/numpy/distutils/checks/cpu_avx512_knm.c (code 4)
```

* runtime error on `import numpy`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/eb-5n40d3vl/tmp5mog6hw4/lib/python3.9/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/tmp/eb-5n40d3vl/tmp5mog6hw4/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/tmp/eb-5n40d3vl/tmp5mog6hw4/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/tmp/eb-5n40d3vl/tmp5mog6hw4/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
RuntimeError: NumPy was built with baseline optimizations:
(SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL) but your machine doesn't support:
(AVX512_KNL).
```

### NumPy/Python version information:

* OS: CentOS 7.9
* compiler: Intel compilers 2021 update 2 ("classic" commands, so using `icc`, `icpc`, `ifort`)
* compiler flags: `-O1 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC`
* numpy 1.20.3, Python 3.9.5

**Comment by mattip** [comment]
If I understand correctly:
1) At compile time, check if the compiler supports various intrinsics by checking success/failure of compilation, with no regard to the capabilities of the host CPU. This give us the largest set of intrinsics we can use in the code. If the tests fail due to an internal compiler error, that is a compiler bug and should be reported to the compiler vendor. We cannot really help here.
2) At compile time, use the `--baseline` and `--dispatch` flags to select from the intrinsics in step 1. 
3) Any intrinsics in the baseline will be required to be present at runtime. Any intrinsics in the dispatch will be tested for at runtime, and possibly used if they are found.

Somehow the compiler bug in (1) is causing `AVX512_KNL` to be added to `--cpu-baseline native`, but at runtime the detection for it is failing.

@seiko2plus thoughts?

**Comment by seiko2plus** [comment]
@boegel,

> I'm not seeing this problem when compiling with GCC 10.3.0 on the same system.

My bad. Thanks to you, I just realized that ICC has a different behavior when it deals with native/host flags, GCC/CLANG only exposes intrinsics that belong to the enabled CPU features while ICC always defines all those intrinsics no matters they belong to the host/native CPU features or not and that's why all tests are passed on ICC which leads to break the validation mechanism.

> One way around this is to compile with -O0, but I'm not sure if that makes sense?
I used -O0 to work around that issue, but even then the detection seems to be done incorrectly.

No that wouldn't fix the issue, the only way is to test compiler definitions of each CPU feature since as I mentioned above ICC always provides and exposes all possible intrinsics.

> it seems that the feature_is_supported method only checks for compiler support via feature_test, it doesn't try to run the compiled test programs at all?

Yes, that's true, `CCompilerOpt` doesn't execute any of these tests only compile them. when option `native` is enabled its fires all tests and passes native/host flag e.g. `-march=native` to the compiler and once the compiler is able to compile the feature then it considered supported by the host.

> Isn't the intention to also run these (rather than just compile them) to detect whether the CPU features are actually supported?

That's the compiler job, not ours. native/host flags suppose to fire internal checking procedures handled by the compiler that should lead at the end to enable only intrinsics/#defentions of the supported features by the host.

>  How is the discrimination between baseline and dispatch CPU features done?

Through build options `--cpu-baseline` and `--cpu-dispatch`. e.g.
```Bash
python setup.py build --cpu-baseline="avx2" install --user
```
`CCompilerOpt` changes the default value of `--cpu-baseline` to `native`, if native flags been detected whether specified by env var `CFLAGS` or through python config var.

> The installation actually completes, but the result doesn't work at all, it leads to trouble on import numpy, which triggers an error reporting that AVX512_KNL is not supported (see traceback below).

NumPy has an internal guard for baseline features that suppose to raise runtime error if the running machine doesn't support any of the baseline features to avoid `Illegal instruction` errors that may happen هى the late stages of the process's life.

Eventually, I wonder if you could verify #19098?

Thank you!

**Comment by boegel** [comment]
@seiko2plus Thanks a lot for the detailed feedback!

I've tested the changes in #19098, and I can confirm they fix the reported issue.
I also see this in the output, as expected:

```
  CCompilerOpt.feature_test[1452] : testing feature 'AVX512_KNL' with flags (-xHost)
  C compiler: icc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -O1 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC -I/software/imkl/2021.2.0-iimpi-2021.03/mkl/2021.2.0/include -fPIC

  compile options: '-DDETECT_FEATURES=1 -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/software/Python/3.9.5-GCCcore-10.3.0/include/python3.9 -Ibuild/src.linux-x86_64-3.9/numpy/core/src/common -Ibuild/src.linux-x86_64-3.9/numpy/core/src/npymath -c'
  extra options: '-xHost -Werror'
  CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[711] : Command (icc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -O1 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC -I/software/imkl/2021.2.0-iimpi-2021.03/mkl/2021.2.0/include -fPIC -DDETECT_FEATURES=1 -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/software/Python/3.9.5-GCCcore-10.3.0/include/python3.9 -Ibuild/src.linux-x86_64-3.9/numpy/core/src/common -Ibuild/src.linux-x86_64-3.9/numpy/core/src/npymath -c /tmp/eb-9kx9wgi3/pip-req-build-k1qn7y2_/numpy/distutils/checks/cpu_avx512_knl.c -o /tmp/eb-9kx9wgi3/tmpg0frz54b/tmp/eb-9kx9wgi3/pip-req-build-k1qn7y2_/numpy/distutils/checks/cpu_avx512_knl.o -MMD -MF /tmp/eb-9kx9wgi3/tmpg0frz54b/tmp/eb-9kx9wgi3/pip-req-build-k1qn7y2_/numpy/distutils/checks/cpu_avx512_knl.o.d -xHost -Werror) failed with exit status 2 output ->
  icc: command line warning #10148: option '-Wno-unused-result' not supported
  icc: command line warning #10121: overriding '-march=native' with '-march=native'
  icc: command line warning #10121: overriding '-march=native' with '-xHost'
  icc: command line warning #10121: overriding '-xHost' with '-xHost'
  /tmp/eb-9kx9wgi3/pip-req-build-k1qn7y2_/numpy/distutils/checks/cpu_avx512_knl.c(10): error: #error directive: "HOST/ARCH doesn't support Knights Landing AVX512 features"
            #error "HOST/ARCH doesn't support Knights Landing AVX512 features"
             ^

  compilation aborted for /tmp/eb-9kx9wgi3/pip-req-build-k1qn7y2_/numpy/distutils/checks/cpu_avx512_knl.c (code 2)

  CCompilerOpt.feature_test[1468] : testing failed
```

I now see a handful of `linalg` tests failing due to `nan` issues, but that's not directly related to the problem reported here.
