### ISSUE TITLE
Inconsistent behavior of np.mean of an empty array of timedelta64

### ISSUE THREAD

**Issue by vmarkovtsev** [numpy/numpy#19379]
### Reproducing code example:

```python
import numpy as np
np.seterr(divide="raise")

np.mean(np.array([], dtype=int))  # does not raise

np.mean(np.array([], dtype="timedelta64[s]"))  # raises
```

### Error message:

The first mean prints
```
/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Out[*]: nan
```

The second mean raises:
```
/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
<ipython-input-5-8ce52cda21b2> in <module>
----> 1 np.mean(np.array([], dtype="timedelta64[s]"))

<__array_function__ internals> in mean(*args, **kwargs)

/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py in mean(a, axis, dtype, out, keepdims, where)
   3438             return mean(axis=axis, dtype=dtype, out=out, **kwargs)
   3439 
-> 3440     return _methods._mean(a, axis=axis, dtype=dtype,
   3441                           out=out, **kwargs)
   3442 

/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py in _mean(a, axis, dtype, out, keepdims, where)
    187             ret = arr.dtype.type(ret / rcount)
    188         else:
--> 189             ret = ret.dtype.type(ret / rcount)
    190     else:
    191         ret = ret / rcount

FloatingPointError: divide by zero encountered in true_divide
```

### NumPy/Python version information:

```
1.21.0 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0]
```

**Comment by debnathshoham** [comment]
Hi,

I am new to open source contribution. Can I work on this issue? 
Of the two above errors, which one is the expected?

Regards,
Shoham

**Comment by seberg** [comment]
Lets ignore the empty-slice warning (we could modify/remove that, but its distinct).  The two paths raise different floating point errors.  The reason is that `0. / 0.` gives an invalid warning, while `1. / 0.` (which creates infinities) gives division by zero.  The timedelta path always sets division by zero manually.  Not 100% sure whats best here, in practice timedelta's always produce NaT in _both_ cases in division anyways, and their math does not quite match floating point math...

**Comment by melissawm** [comment]
Is there a way forward here, or can this be closed? From @seberg 's comment I'm getting that these different messages are accurate.

**Comment by seberg** [comment]
Happy with a proposal of how to move forward, but it is not obvious to me, and it is not _really_ incorrect anyway.

The new ufunc-machinery could allow to set a custom warning, but that would not be easily modifiable by `np.errstate`.  So, since I also do not see a clear path forward here and neither do I think it is a big issue, so I agree with closing.

Happy to reopen/have a new issue if anyone disagrees.

**Comment by vmarkovtsev** [comment]
My proposal would be to catch the FloatingPointError and show the RuntimeWarning. That's what my workaround is, anyway, because returning nat is the desired behavior.
