### ISSUE TITLE
Segmentation fault for np.empty_like(a).astype(bool) for an object array a

### ISSUE THREAD

**Issue by Horstage** [numpy/numpy#19373]
Using **Python 3.8.9** on linux with **numpy 1.21.0** I get an Segmentation fault when typecasting an object array to bool which was created by np.empty_like.

Minimal working example:
```python
import numpy as np

class Foo:
    pass

a = np.array([Foo(), Foo()], dtype=Foo)
b = np.empty_like(a)
b.astype(bool)
```

To replicate environment use docker container [python:3.8-slim](https://hub.docker.com/_/python) and pip install numpy.
e.g.
```bash
docker run -it --entrypoint=/bin/bash python:3.8-slim
pip install numpy==1.21.0
```

Workaround for those who still have to work with this:
```python
b = np.copy(a)
b[:] = None
b.astype(bool)
```

**Comment by cbodenst** [comment]
Also reproducible with
`np.empty_like([None]).astype(bool)`

**Comment by seberg** [comment]
Ugly :/. I am wondering if 1.20 also does random stuff here, but for some reason doesn't run into the crash.  Anyway, the fix is easy, the problem why this slipped past is that `empty_like` may well be the only reasonable way to create a half-initialized object array (an object array filled with NULL rather than None – we consider NULL and None to be equivalent).
