### ISSUE TITLE
Natively support Rust-like shorthands for the data types such as `i32` and `f32`

### ISSUE THREAD

**Issue by rnarkk** [numpy/numpy#19424]
## Feature

It should be so much nice and helpful both for reading and writing code if there exist Rust-like shorthands of the data types as they're heavily repetitive in code bases.
Though there are manually type-alias adding functionalities, Numpy's native support of them will naturally be a trigger of wide adoption across Python's ecosystem, especially by TensorFlow.

### Examples

| Existing | New |
| ------------- | ------------- |
| `int8`  | `i8` |
| `int16` | `i16` |
| `int32` | `i32` |
| `int64` | `i64`  |
| `uint8` | `u8` |
| `uint16` | `u16` |
| `uint32` | `u32` |
| `uint64` | `u64`  |
| `float16` | `f16` |
| `float32` | `f32` |
| `float64` | `f64` |

**Comment by eric-wieser** [comment]
I strongly believe this is a bad idea. Numpy already has far too many ways to spell types; for instance `'i2'`, `'int16'`, `'short'`, `'h'` are all treated the same as `np.int16`.

**Comment by seberg** [comment]
I agree, we and the struct module already have byte-sized one letter shorthands with `"i2"`, etc.  Adding bit-sized one letter shorthands will just make things even more confusing.

Thanks for the suggestion, but I am going to close this, since I doubt you will get any buy in from a core-dev.  You could try proposing it on the mailing list.
