### ISSUE TITLE
`np.clip()` is inconsistent with the `minimum`/`maximum` equivalent

### ISSUE THREAD

**Issue by Zac-HD** [numpy/numpy#19457]
```python
def test_clip_inconsistency():
    arr  = np.zeros(shape=1, dtype=np.int8)
    amin = np.float16(0)
    amax = np.full(shape=(), dtype=np.float64, fill_value=-16777217.0)

    result   = np.clip(arr, amin, amax)
    expected = np.minimum(amax, np.maximum(arr, amin))
    assert_array_equal(result, expected)
```

fails with 

```
AssertionError: Arrays are not equal

Mismatched elements: 2 / 2 (100%)
Max absolute difference: 1.
Max relative difference: 5.96046448e-08
 x: array([-16777217., -16777217.])
 y: array([-16777216., -16777216.], dtype=float32)
```

This was found using Hypothesis, and @mattip [asked me to open an issue](https://github.com/numpy/numpy/pull/19450#discussion_r667646253).  Because property-based tests make it natural to vary things like this I often find strange small inconsistencies or bugs in the interaction between rarely used features - such as narrow dtypes, nan, structured dtypes, zero-dimensional arrays, dimensions of size zero, and so on.

Once fixed, we can generalise the original test: https://github.com/numpy/numpy/compare/main...Zac-HD:tidy-clip-test

**Comment by seberg** [comment]
To be honest, this a "logical" fall-out from current value-based casting to me.  `np.maximum(arr, amin).dtype` is float16 and 1-d.

`np.maximum(arr, amin)` gives a 1-d float16 array, which enables value-based casting involving `amx` (which is 0-D).  If the operation is re-ordered, both `amin` and `amax` are 0-D (but trump the integer `arr`), so normal promotion is used and the `float64` wins clearly.

Most of the fix is to get rid of value-based casting.  Even then you can design funny corner cases. NumPy promotion is not associative when it comes to signed and unsigned integers.

**Comment by seberg** [comment]
With respect to the test: If you want to test everything, the correct thing is to write `dtype = np.result_type(arr, amin, amax)` and then use `dtype=dtype` in the first `np.maximum` call (or all calls).  That would be the right thing to do, even if we "fix" the value-based casting inanity that makes this so surprising.

**Comment by seberg** [comment]
I guess I can close this as a generic "value based casting/promotion is weird" issue.  gh-19457 is a pretty good one (although it focuses a bit on comparisons, which are arguably particular...
