### ISSUE TITLE
Division by zero error while registering internal types float_128 and float_80, despite blocking instructions.

### ISSUE THREAD

**Issue by makshimik** [numpy/numpy#19508]
On the embeddable version of Python, the file "...\python\Lib\site-packages\numpy\core\getlimits.py", despite blocking, causes a division by zero error when trying to register the types "float_128" and "float_80". It's because "very large number" is generated by dividing by "very small number", which is effectively 0.0. This error manifests itself in very various versions of numpy and python when embedding into C ++ and Delphi applications. At the moment I have replaced the denominator with the one used earlyer in code when registering "float_64", thus decreasing the maximum values for float_128 and float_80. Obviously, one should either choose a different method of obtaining a "very large number", or somehow more reliably block the appearance of an error. It needs to be said that this issue is quite important because end-users will be facing with it and there're very few of them who can deal with it.

**Comment by charris** [comment]
What numpy version?

**Comment by makshimik** [comment]
> What numpy version?

I've tried  from 1.19 to 1.21 and Python from 3.7 to 3.9

**Comment by charris** [comment]
The reason I ask is that windows doesn't support either float128 or float96, I believe mingw32 supports it, but msvc doesn't. Embedded is also suspicious.

**Comment by makshimik** [comment]
So the point is that when importing a library from the console or from IDE, everything goes well, the error is suppressed, as intended, judging by the code. Namely, when embedding it, for some reason, it arises.

**Comment by seberg** [comment]
@makshimik I expect Chuck is right and it has something to do with mingw and msvc using a different long-double,?

Just to get the complete picture, since I don't really know where we could start understanding it better.  Could you paste:
* The exact error?
* `np.nextafter(np.longdouble(0), 1.)`
* `np.geterr()`?
* `np.exp2(np.longdouble(-16382)`
* `np.finfo(np.float64).tiny / 8` (subnormal, created by a division)

The error suppression in the file may not be perfect, but it seems sufficient...

**Comment by makshimik** [comment]
![image](https://user-images.githubusercontent.com/87600574/126225715-ceadef44-bdcc-47c5-969e-ee4e957008a1.png)
Here is a screenshot from the {python_root}\Lib\site-packages\numpy\getlimits.py file.
On the left you can see the specific line numbers.
The red arrows mark the lines where division by zero occurs, directly throwing an exception. There you can see my "emergency" edits. The green arrows indicate the reason for the error - the variable goes to zero. I understand that division by zero itself is expected and the error should simply be ignored, but for some reason, when embedding python into a Windows application, the error still appears.

**Comment by seberg** [comment]
What is the exact error you are seeing?

**Comment by makshimik** [comment]
without my edits of getlimits.py:
![image](https://user-images.githubusercontent.com/87600574/126262689-ed8f0f29-c70f-4eab-bb52-d9bae9b32b41.png)
with edits:
![image](https://user-images.githubusercontent.com/87600574/126263004-5605f959-dcaf-4bdb-99eb-28754cbea0d4.png)
This what I saw. And I found that exactly place that cause that exactly error. What is behind I can't know. And, let's be honest, I'm not even interested. But if you ask me, I think that using division for this purpose isn't a very good idea. Or at least you could check if it zero instead of just blocking it (not reliably enough as I saw), or may be check what system is. You know, it can be that people not that frequenly report that kind of issues because they don't want to deal with all  "show me your proofs, dude!" things.

**Comment by mattip** [comment]
> And, let's be honest, I'm not even interested.

> You know, it can be that people not that frequently report that kind of issues because they don't want to deal with all "show me your proofs, dude!" things.

People frequently report issues, so far there have been almost 10,000 issues reported just in this repo. The guidance when opening an issue tries to clearly state what is expected when opening an issue, by following that you might have avoided this "please show us" ping-pong. 

The way this works is that we (you and us, together) are  trying to figure out what went wrong. You are part of the solution: your use case is unique and your help is needed  to understand exactly what went wrong. Very few of the people you are conversing with use windows on a regular basis, even fewer try to embed an interpreter, and windows7 is no longer supported in python. Since the problem is so unique, you will probably have to be involved in tracking this down. This is the way Open Source progresses: people who are passionate about something go ahead and contribute, following their passion.

We now see the problem is around the `numeric.errstate` call which is not correctly setting up the embedded interpreter to ignore errors. Until you posted the screen shots that showed where in the code the error is generated we could only guess that was where the problem was. Since this is specific to your setup, the answers to @seberg's questions would help try to figure out why `numeric.errstate` does not seem to be doing what it is supposed to, as would answers to what compiler you are using.

**Comment by seberg** [comment]
@makshimik the reason I ask, is that I need to be able to follow what you were doing to help you.  And this little piece of information actually allows that...
The point is: From what you told us, it did not really make sense what to look for in NumPy.  The information you gave makes me realize that this was the wrong place to look for an issue in the first place.

NumPy would print:  `FloatingPointError: divide by zero encountered in true_divide`, Python normally sets: `ZeroDivisionError: float division by zero`.  And both NumPy and Python should give more information (such as the line number).

---

Since nothing quite matches, and you are not showing us line numbers, it is getting more and more clear that the issue is in your program:

In compiled languages, you can usually set up callbacks when floating point errors occur.  Usually, they are just ignored and you have to check them explicitly, but say in C++, you may have "trapping math" and depending on the compile flags/setting that may probably raise a C++ exception.  *Your* program must be doing this and affecting NumPy.

NumPy can't generally *avoid* setting the warning flags, we just *ignore* them if you use `np.errstate`.  You can avoid the error on startup here, but you really need to disable your error handling (which may be a compiler option) when NumPy is running.  Because general NumPy code can always generate such errors.

**Comment by makshimik** [comment]
@seberg 
You behave as I expected. :D 
When you can't realize what to do you saing "See on your side!")))
Of course, it's not a Python error message! Because python is embedded. Thus it throws the error to parent code! But it must not be doing this! This is the point!  
My side huh? But why the error apears only on numpy importing? Why it disapears after my "emergency" edits of getlimits.py? 
My side, huh!
Ok. Be happy! :D

**Comment by seberg** [comment]
> But why the error apears only on numpy importing?

It doesn't, it is just one place where it always happens.  We could probably avoid it there, but we *can't* avoid it in general.  If you want to understand it, this will probably trigger a similar thing and does not even call NumPy (whether this works or not may be system dependend). 
```python
float("nan") > 0
```

Otherwise, I suggest calculating `1. / 0.` in your program (not with hardcoded values to be sure the compiler does no weird things), and then see what happens.

**Comment by makshimik** [comment]
Oh, I just checked! None of my code, none of even libraries it uses has text 'Floating point division by zero'. But CPython files has:
![image](https://user-images.githubusercontent.com/87600574/126369133-434a1b08-77ca-4348-bd41-db8218ad0495.png)
But yeah! It's my stupid compiler doing weird things.

**Comment by eric-wieser** [comment]
"Floating point division by zero" is almost certainly coming from part of your C++ or Delphi runtime, or the operating system itself.

Are you creating the message box in your own code? Or is Delphi doing that?

**Comment by eric-wieser** [comment]
None of those files you reference are part of Python or NumPy - they're part of scipy, which your screenshot indicates you are not even using
