### ISSUE TITLE
numpy.seterr not working for numpy.log10 on windows (Trac #1360)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1958]
_Original ticket http://projects.scipy.org/numpy/ticket/1360 on 2010-01-12 by trac user Andrew MacKeith, assigned to unknown._

On Windows, seterr(all='raise') does not raise exceptions when Overflow occurs in numpy.log10. The following uses numpy-1.4.0.

```
Python 2.6.4 (r264:75708, Oct 26 2009, 08:23:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>  import numpy
>>>  numpy.seterr()
{'over': 'ignore', 'divide': 'ignore', 'invalid': 'ignore', 'under': 'ignore'}
>>>  numpy.int16(32000) * numpy.int16(3)
30464
>>>  numpy.log10(0.0)
-inf
>>>  numpy.seterr(all='raise')
{'over': 'ignore', 'divide': 'ignore', 'invalid': 'ignore', 'under': 'ignore'}
>>>  numpy.int16(32000) * numpy.int16(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in<module>
FloatingPointError: overflow encountered in short_scalars
>>>  numpy.log10(0.0)
-inf
>>>  numpy.log10(-1.0)
nan
>>>  numpy.seterr()
{'over': 'raise', 'divide': 'raise', 'invalid': 'raise', 'under': 'raise'}
>>>
```

**Comment by seberg** [comment]
I agree with Warren, tested on an admittedly random but newer windows.  Lets close this, NumPy usually inherits the math libs behaviour, and it feels likely enough that got fixed along the way.

Since the issue also mentions an old MSVC version, I will assume it was an old compiler (or mathlib) bug on windows.  If it crops up again/is still present, lets open a new one.
