### ISSUE TITLE
TST: cygwin git is flaky

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#19603]
[CI is failing](https://github.com/numpy/numpy/pull/19593/checks?check_run_id=3228399509) with
```
/usr/bin/git
Fetching origin
C:/tools/cygwin/usr/libexec/git-core/git-remote-https.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
error: Could not fetch origin
```

@DWesl any ideas?

**Comment by DWesl** [comment]
It doesn't include the shared library it can't find, so I can't backtrack from there.  My installation doesn't show any missing dependencies.

There are a few recent updates to cygwin packages (in [July](https://cygwin.com/pipermail/cygwin-announce/2021-July/date.html) or [August](https://cygwin.com/pipermail/cygwin-announce/2021-August/date.html)), but none of them seem to be relevant.  I can run `git fetch upstream` and `git fetch origin` just fine locally, and installed updates twice in the last week.

I'll try reproducing it in another repo, then see if I can fix it.  It seems to happen most of the time, which helps.

**Comment by DWesl** [comment]
From experimentation [here](https://github.com/DWesl/setup-cygwin-ci/pull/1/checks), it appears that the recent libidn upgrade obsoleted a package it should not have (effectively replacing `cygidn-11.dll` with `cygidn-12.dll`, or, in Linux terms, `libidn.so.11` with `libidn.so.12`).  Manually creating a link from the file needed to the file present doesn't work (that tends to be why the package starts providing `cygidn-12.dll` instead of `cygidn-11.dll`), so probably the best solution is turning the Cygwin tests off until libidn gets fixed.

**Comment by mattip** [comment]
Cool, thanks for checking

**Comment by mattip** [comment]
It seems the update works and [the CI run](https://github.com/numpy/numpy/runs/3130963678) is now successful. Closing.
