### ISSUE TITLE
Negated booleans return negative numbers for cumulative sums

### ISSUE THREAD

**Issue by Esfo** [numpy/numpy#19611]
### Reproducing code example:

```python
bools = np.array([True, True, True, False, False, True, False])

~bools.cumsum()
Out[187]: array([-2, -3, -4, -4, -4, -5, -5])

(~bools).cumsum()
Out[188]: array([0, 0, 0, 1, 2, 2, 3])
```

Seemed odd in general, but also because the negated values start accumulating at -1 instead of 0. It's counting False values as -1.

 I couldn't find anything that directly describes this behavior being present. Wasn't sure if this was intended or not.

Using 1.20.3

**Comment by rkern** [comment]
`~bools.cumsum()` is evaluated by Python as `~(bools.cumsum())`. That is, the cumulative sum is done first, which returns an `int` array, on which `~` is a bitwise operation, not a boolean one. Signed integers are implemented with the so-called [two's complement](https://en.wikipedia.org/wiki/Two%27s_complement) representation, so `~` shows up as the negatives of the positive inputs, but off by one. This is all expected behavior.

```
[~]                                                                                                                                                                                                  
|2> bools.cumsum()                                                                                                                                                                                   
array([1, 2, 3, 3, 3, 4, 4])

[~]                                                                                                                                                                                                  
|3> ~np.array([1, 2, 3, 3, 3, 4, 4])                                                                                                                                                                 
array([-2, -3, -4, -4, -4, -5, -5])
```
