### ISSUE TITLE
ValueError becomes SystemError for in-place exponentiation (nightly build)

### ISSUE THREAD

**Issue by effigies** [numpy/numpy#19634]
### Reproducing code example:

This issue is breaking tests where we expect to throw `ValueError`s and are now getting `SystemError`s.

```Python
import numpy as np

a = np.array([0, 1], dtype='int64')
try:
    a ** -3
except Exception as e:
    print(repr(e))
try:
    a **= -3
except Exception as e:
    print(repr(e))
```

### Error message:

With numpy 1.21.1:

```
ValueError('Integers to negative integer powers are not allowed.')
ValueError('Integers to negative integer powers are not allowed.')
```

With nightly build `'1.22.0.dev0+679.g261a769dd'`:

```
ValueError('Integers to negative integer powers are not allowed.')
SystemError("<ufunc 'power'> returned a result with an error set")
```

Full IPython traceback:

```
ValueError                                Traceback (most recent call last)
ValueError: Integers to negative integer powers are not allowed.

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-4-359753e44972> in <module>
----> 1 a **= -3

SystemError: <ufunc 'power'> returned a result with an error set
```

### NumPy/Python version information:

```
1.22.0.dev0+679.g261a769dd 3.9.6 (default, Jul 30 2021, 16:35:19) 
[GCC 7.5.0]
```

**Comment by seberg** [comment]
Thanks for the report.  I had not realized we had manual error setting in any ufunc that doesn't already use the Python API/work with Python objects...

A bit annoying: the only very straight forward fix right now is to always check for errors again.  But, the proper thing would be to rewrite the power loop(s) as a new-style loop, but that may be a bit more involved, since it would be a first.
