### ISSUE TITLE
can_cast behaves oddly on unusual datetime units

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#19631]
### Reproducing code example:
I would expect these two to give the same result, since 1000ns = 1us:
```python
import numpy as np
np.can_cast('M8[1000ns]', 'M8[us]', casting='safe')  # False
np.can_cast('M8[us]', 'M8[us]', casting='safe')  # True
```

### NumPy/Python version information:

* 1.19.4
* 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]

**Comment by shubham11941140** [comment]
` ` `
np.can_cast('M8[1000ns]', 'M8[1us]', casting='same_kind') 
` ` `  will return True.
` ` `
np.can_cast('M8[1000ns]', 'M8[1us]', casting='unsafe') 
` ` ` will also return True.

Both are in the same kind of units of second, so the behaviour should be correct.

Unfortunately, multiplying with 1000 gives the same mathematical value in magnitude but will not change units and size of the value (with respect to the length)

You are considering the option of 'safe' cast. In the case of safe cast (‘safe’ means only casts which can preserve values are allowed) (Refer: https://numpy.org/doc/stable/reference/generated/numpy.can_cast.html)

It is written that in version 1.9.0: 

Changed in version 1.9.0: Casting from numeric to string types in ‘safe’ casting mode requires that the string dtype length is long enough to store the maximum integer/float value converted.

The issue is that ns will be longer than us (being a smaller unit will need more digits to store). This violates the above statement as you are casting long to short, so it will return False.

If you try this: 
` ` `
np.can_cast('M8[ms]', 'M8[us]', casting='safe') 
` ` ` it gives True as short is converted to long resulting in a safe casting.

Probably your version is old (1.19.4), but this holds in accordance with the latest version and it's description in the documentation.

The behaviour is correct, but I still feel that it could be made better. In such as case a conversion of units because of the equivalence of magnitude. 
If I could make a table that would automatically couple the conversion in different units before running the can_cast then this will also work with a 'safe' option.
To fix this, I would have to make the necessary changes in the code.

Please can you guide me to the particular file where the description is written so I can probably build the table.

I can make a pull request and you can help me verify the correction and merge it.

**Comment by eric-wieser** [comment]
> Changed in version 1.9.0: Casting from numeric to string types in ‘safe’ casting mode requires that the string dtype length is long enough to store the maximum integer/float value converted.

This is irrelevant, as I am not working with string types.

> The issue is that ns will be longer than us (being a smaller unit will need more digits to store). 

This is untrue, as my unit is `1000ns` not `1ns`.
