### ISSUE TITLE
floating point issue / inconsistency

### ISSUE THREAD

**Issue by suuuehgi** [numpy/numpy#19664]
There is a floating point issue / inconsistency (at least) with `numpy.linspace`. 

I expect `print` to display whats actually there. So either to print 0.30..04 or linspace containing .3.

### Reproducing code example:

```python
>>> import numpy as np
>>> 0.3 in (a := np.linspace(0,1,11))
False
>>> a
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
>>> a.tolist()
[0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0]
```

### Error message:

See above.

### NumPy/Python version information:

1.17.4 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]

**Comment by charris** [comment]
Use the `np.printoptions` context if you want to see all the digits. In general, comparing floating point numbers for equality is asking for trouble and should be avoided, the numbers are usually approximate due to the inherent limitations of floating point.

**Comment by ishikkkkaaaa** [comment]
Hey!
You can simply round off the list while iterating through the loop
Here's how
`
list=[0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0]
round_off = [round(num, 1) for num in list]
print(round_off)`

**Comment by rkern** [comment]
I think @suuuehgi wants the array to show what the list shows, not vice versa.

@charris I think the `0.3 in a` test was more of a demonstration that the printed representation was not round-tripping as they expected rather than an operation that they wanted to do in real code.

@suuuehgi If you use `np.set_printoptions(precision=17)` or `with np.printoptions(precision=17):` you will see the full floating-point precision numbers that will round-trip. The default precision of 8 was a very early decision at a time when even Python itself made a distinction between `float.__str__` and `float.__repr__` such that `print(0.30000000000000004)` would show `0.3`. Part of the reason we keep the default precision to 8 is that the full 17ish digits would make showing general floating point arrays quite unwieldly, and it is generally not needed to round-trip these string representations. However, we do expose the tools to change that when you do need it.

As this is a specific design decision that I don't think we are going to change (not without a long discussion elsewhere), I am going to close this issue. Please feel free to ask any followup questions here or on the mailing list, though.

**Comment by suuuehgi** [comment]
@rkern Your assumptions are completely correct. And I can see your point - thank you very much for the thorough answer!
