### ISSUE TITLE
Divide by zero runtime warning

### ISSUE THREAD

**Issue by bje-** [numpy/numpy#19723]
Numpy emits a runtime warning when dividing by zero and it's not easy to silence these without silencing all runtime warnings, which is really undesirable. I am not sure why this warning is produced, given that the division produces an `inf` result. For consistency with Python natural types, is it not possible to have Numpy raise a ZeroDivisionError exception?

### Reproducing code example:

```python
import numpy as np
x = np.ones(10)
x / 0
```

### Error message:

```
<stdin>:1: RuntimeWarning: divide by zero encountered in true_divide
array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])
```

### NumPy/Python version information:

```
1.21.2 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
```

**Comment by prathyu3122** [comment]
NumPy errors cannot be excepted using `try:` and `except:` block of code.

Getting `inf` while dividing a non-zero by 0 is defined and it is a part of [IEEE Floating point standard](https://en.wikipedia.org/wiki/IEEE_754). 

Solution for this is to raise **FloatingPointError** after a numpy error. To raise an error in Python we use `try` and `except`. In this way we can use `np.seterr()` to raise **FloatingPointError**.

Here in your code there is a warning generated and you can change its behaviour by generating an exception.

The issue which you have raised can be solved by this code:
```
import numpy as np
np.seterr(divide = 'raise')
try:
    x = np.ones(10)
    x / 0
except:
    print("Error has been raised")
```

Output:
`Error has been raised`

Warning and error resolved.

**Comment by as0wanth** [comment]
use np.errstate using with clause
import numpy as np
with np.errstate(divide='ignore'):
    x=np.ones(10)
    y=x/0
y
output:
array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

**Comment by phetdam** [comment]
> Getting `inf` while dividing a non-zero by 0 is defined and it is a part of [IEEE Floating point standard](https://en.wikipedia.org/wiki/IEEE_754).

Yes. @bje-, if you think sufficient, maybe close the issue?

**Comment by bje-** [comment]
I understand that that the IEEE standard defines this behaviour. I just think that having a library produce diagnostic output is not desirable and the proposed solutions above are a bit clunky, IMHO. Why doesn't Numpy mimic  Python behaviour for native types?

**Comment by rkern** [comment]
The Python native types are scalars. The operation with the division by 0 is only happening to one number, so dealing with that condition through exceptions is relatively straightforward. I can do alternate behavior in an `except` clause. But when we have large arrays of numbers, it might only be one number out of the many that is causing the issue. If we raise an exception, there's no way for me to handle the alternate path for just that one element. I have to start from scratch. So usually, I want the calculation to carry through, and then maybe I'll deal with the infs and NaNs in the output array afterwards. The default to issue warnings will let me know that this is happening, and where, so I can go back and deal with it. Often, looking at the result will give me a better idea of how to fix things than just the inputs, so defaulting to warnings instead of exceptions helps me get to the correct fix faster.

[`numpy.errstate()` and friends](https://numpy.org/doc/stable/reference/generated/numpy.errstate.html) give you a full range of ways to control how these floating point errors are handled, including silencing the warnings or raising exceptions. Each is useful in different contexts.

**Comment by phetdam** [comment]
> I understand that that the IEEE standard defines this behaviour. I just think that having a library produce diagnostic output is not desirable and the proposed solutions above are a bit clunky, IMHO. Why doesn't Numpy mimic Python behaviour for native types?

I personally consider conformation to IEEE to be more important than conformation to Python standards. Also, from a technical standpoint, NumPy types *aren't* native Python types, which of course are all `PyObject *`. I definitely understand your frustration with the warnings however (my experience as well), but @rkern does give a good explanation as for why a `ZeroDivisionError` wouldn't be desirable in many actual use cases.

**Comment by bje-** [comment]
Fair enough.
