### ISSUE TITLE
In some cases numpy arrays can't  be expandable

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [numpy/numpy#19757]
## Documentation
<p>I  just want to point out  why numpy arrays  can't be expandable </p>

**Comment by Sulagna-Dutta-Roy** [comment]
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print(np.reshape(a, (2, 5)))

Output: Valuerror: new array size can be unchanged.

I expected some output. I tried resize() too,it gives output.

**Comment by rossbar** [comment]
I think there may be some fundamental misunderstanding of some basic terms like "shape" and "size" in the context of NumPy arrays. I'd recommend taking a look at the [beginner's tutorial](https://numpy.org/devdocs/user/absolute_beginners.html#more-information-about-arrays) for a refresher; the sections on [adding/removing elements from an array](https://numpy.org/devdocs/user/absolute_beginners.html#adding-removing-and-sorting-elements) and [reshaping arrays](https://numpy.org/devdocs/user/absolute_beginners.html#can-you-reshape-an-array) may help address your question.

I'm going to close this as it seems to be more a question about arrays that the tutorials already address, rather than a specific problem with the documentation.
