### ISSUE TITLE
Random `choice` first choices affected by requested size

### ISSUE THREAD

**Issue by david-cortes** [numpy/numpy#19760]
From https://stackoverflow.com/questions/68927829/how-to-use-use-numpy-random-choice-to-get-progressively-longer-sequences-with-th

When generating random numbers with `np.random.Generator.choice` and having probabilities, the chosen elements in the first positions will depend on the number of elements to generate, leading to inconsistent results if one tries to replicate results but with varying input lengths:
```python
import numpy as np
n = 100
prob = np.random.choice(100, n)
prob = prob / np.sum(prob)
for i in np.arange(10, 40, 10):
    rng = np.random.default_rng(seed=123)     
    selected = rng.choice(n, size=i, replace=False, p=prob)
    print(str(i) + ': ' + str(selected))
```
```
10: [71  5 20 16 81 92 26 82 88 52]
20: [71  5 20 16 81 92 26 82 88 52 24 19 75 65 22 80 53 25 13 48]
30: [71  5 20 16 81 92 26 82 88 52 24 19 75 65 22 80 53 15 50 60  1 48 74 91 94 87 18 73 31 79]
```

Which is quite unexpected and does not happen in e.g. R's `sample`.

I would assume the optimal algorithm for drawing these random numbers amounts to having some binary tree saving weights of its left and right subtrees, and then drawing random numbers in the tree's range and passing down the tree until reaching the bottom and removing that weight, which should not make any choice at position `n` depend on what's going to happen at position `n+1`.

**Comment by Tanu1201** [comment]
Can I take this issue?

**Comment by david-cortes** [comment]
@Tanu1201 I do not plan to work on this, but I'd wait for the opinion of someone from NumPy.

**Comment by rkern** [comment]
@Tanu1201 Hi! Welcome to NumPy! We have gotten a recent influx of people asking for permission work on issues like you do here. Would you mind telling us who told you to ask for permission in this way? It is generally not the way we work here, you don't have to ask for permission to work on an issue here, so this stands out. I'm wondering if there is a common source suggesting that this is common etiquette.

This would likely not be a good first issue to work on as a first-time contributor. We try to keep the random number algorithms relatively stable, so this will involve a significant amount of discussion.

The reason this happens is that in the `replace=False` and `p is not None` case, [we run a loop](https://github.com/numpy/numpy/blob/v1.21.2/numpy/random/_generator.pyx#L781-L792) where we sample with replacement from the remaining candidates for the remainder of the request that we need to fulfill (i.e. drawing `size - n_uniq` uniform numbers), uniqifying what we get, adding the unique items to the return list, then repeating until we have `size` unique values to return.

So when `size=10`, `sample()` requested 10 uniform random numbers, and you lucked out and all 10 happened to be unique so you never had to go through the loop. When `size=20`, `sample()` requested 20 uniform random numbers, the first 10 of which happened to be the same as the previous thanks to the consistent seeding. But there were only 17 unique items from that 20, so the second iteration requested 3 uniform random numbers to pick items from the remaining candidate set. When `size=30`, the first iteration requested 30 uniform random numbers, the first 20 of which were the same as before (giving 3 duplicates) but then at least 3 more unique values (`15, 50, 60`) were found in the remaining 10 numbers pulled in that first iteration. So they got added to the result list before the second iteration came through to fill up the remainder to return the full 30 items.

To me, this is a feature request rather than a bug. In general, if there are differences in the arguments, we allow differences in the output even if there are ways of thinking about the two requests that you might consider them to be related. For example, we might switch over to different algorithms for performance reasons at certain cutoffs. But if there are use cases to maintain certain views of consistency between different arguments, and there are available algorithms to implement it, then we will take the feature request seriously. The benefit of the use case will be balanced against other considerations like performance, maintainability, and the general cost of changing behaviors (we are more conservative here than in other parts of numpy, but [no longer perfectly strict](https://numpy.org/neps/nep-0019-rng-policy.html#implementation)).

Did you have a particular use case that requires this kind of consistency, or was this just a surprising behavior?

**Comment by david-cortes** [comment]
@rkern  I do not (yet) have any use case for this, but I do find it quite surprising and potentially troublesome if one wants to make reproducible experiments in a loop like in the SO question.

I BTW tested it against a different algorithm (adapted from here https://stackoverflow.com/questions/57599509/c-random-non-repeated-integers-with-weights) and I see the algorithm in that SO answer can be faster when the number of elements to sample is large relative to the lenght of the input (more details at the end).

I did some quick experiments with an input of length 100k and sampling a varying number of elements (probabilities defined just like in the first message here) comparing the current implementation against the algorithm above and a modified less-precise version of it:

Sample fraction = 15%
* time curr: 6.52ms
* time SO: 5.56ms
* time SOv2: 2.51ms

Sample fraction = 50%
* time curr: 20.7ms
* time SO: 17.1ms
* time SOv2: 7.91ms

Sample fraction = 95%
* time curr: 48.2ms
* time SO: 33.8ms
* time SOv2: 14.5ms

(The timings for SO and SOv2 do not include input validation, and use the mersenne-twister engine from the C++ random header)

The algorithm in the SO question is basically as follows:
* It first constructs a balanced binary tree in which the sample weights are the terminal nodes, and each non-terminal node will contain the sum of the weights of its left and right sub-trees.
* In order to sample an element, it draws a random number between zero and the total weight in the tree. If the drawn number is greater than that of the left subtree, moves to the right node, otherwise to the left node, repeating the process recursively until reaching a terminal node, which is the element to sample.
* Once it reaches a terminal node, it simply sets its weight to zero and updates all the nodes upwards.

The SOv2 that I timed would sample just one random number at the beginning of each draw (from zero to the tree total) and then subtracts the weight of the left node every time it moves to a right node, while the SO answer would re-sample a random number at each step for better precision.

IMO the algorithm traversing a binary tree and removing weights along the way has advantages over the current choice:
* It's faster.
* Choices are not dependent on the requested size (the issue seen here).
* Would be less prone to encountering a situation in which summing an extra probability to a cumulative total gives the exact same number as before (which would prevent a given element from being chosen at certain earlier positions).

**Comment by rkern** [comment]
> I do not (yet) have any use case for this, but I do find it quite surprising and potentially troublesome if one wants to make reproducible experiments in a loop like in the SO question.

Yeah, that's the thing I want to interrogate because I don't understand what trouble this actually causes anyone in practice. If you're changing the number of requested items, you're no longer reproducing the previous run. The SO question doesn't really say why they want this property. The example is minimal and contrived (after all, it's only purpose is to demonstrate the current behavior concisely).

**Comment by bashtage** [comment]
This is the correct behavior in the sense that the only guarantee is that the same inputs produce the same output stream, which is the case. An implementation that had the properties discussed here would likely be less efficient than the current one. One can always get randomly ordered sets with subsets preserved by sampling integers with largest size required, and then taking the first `n` elements from this run-once array.

This isn't efficient, but it makes the minimal changes to the SO example to show how easy it is to random subsets that preserve the previous selections. In practice, one would not redraw the initial index.

```python
subsets = {}
import numpy as np
n = n_max = 100
def test_random(nr_selections, n, prob):
    idx = np.random.choice(n_max, n_max, replace=False, p=prob)
    selected =  np.arange(n_max)[idx[:nr_selections]]
    print(str(nr_selections) + ': ' + str(selected))
    subsets[nr_selections] = list(selected)

np.random.seed(123)        
prob = np.random.choice(100, n) + 1
prob = prob / np.sum(prob) #only for demonstration purpose
for i in np.arange(10, 100, 10):
    np.random.seed(123)        
    test_random(i, n, prob)

for key in subsets:
    for other_key in subsets:
        if other_key > key:
            print(f"Number of elements in set {key} not in set {other_key}: {len(set(subsets[key]).difference(subsets[other_key]))}")
```

**Comment by bashtage** [comment]
@david-cortes I think there might be an old issue that suggested a similar approach.  It wasn't actionable since `RandomState` cannot be changed, in general.  One could consider a new algorithm for `choice` in `Generator` if you wanted to submit a PR (acceptance would likely depend on whether the performance gains were meaningful).

**Comment by rkern** [comment]
> This is the correct behavior

This is _a_ correct behavior. :-) The requested behavior would also be a correct behavior. I'm not quite sure that the workaround is trivial. I'm not entirely sure how numerically sound our re-weighting scheme is going to work near the end when `n_max == len(probs)` and some of the `probs` are small. You would also have to know that you can't just set `n_max=len(probs)` but rather `n_max = (probs > 0).sum()`.

@david-cortes We still would consider a new algorithm for other reasons (or if anyone can state a concrete use case for the behavior reason). Your performance numbers are promising. I would like to see more testing to ensure that small-input performance is not (overly) hindered.

But I think I agree that this issue per se should be closed. We can still discuss it, here or on the mailing list. Or in a new PR!
