### ISSUE TITLE
Importing the numpy C-extensions failed (Amplify)

### ISSUE THREAD

**Issue by mcnamara-charles** [numpy/numpy#19774]
I'm working with AWS Amplify and pipenv for my python 3.9 lambda. I'm attempting to use pandas to create a dataframe, do some processing and write it back to CSV for sagemaker inference. 

### Reproducing code example:

```python
import pandas as pd
```
(Code immediately fails after this)

### Error message:

Here's the full error message:
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'index': 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/var/lang/bin/python3.9"
  * The NumPy version is: "1.21.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

```

I first downloaded with `pipenv install pandas` which automatically installs numpy

To solve I've tried:
- `pipenv install numpy / pipenv uninstall numpy`
- `pipenv uninstall pandas / pipenv install pandas`
- `pipenv uninstall setuptools / pipenv install setuptools`

**Comment by mattip** [comment]
The error message should mention which numpy is being loaded, please make sure this it a numpy that is compatible with `var/lang/bin/python3.9`. Are you sure that is the python that you should be using after you use `pipenv` ?

Please help others out by reporting how you solved this, preferably with a PR to update https://numpy.org/devdocs/user/troubleshooting-importerror.html

**Comment by rahulservicemax** [comment]
i am facing same issue. I am getting this issue on AWS lambda function. Getting following error:


[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': Unable to import required dependencies:numpy: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!Importing the numpy C-extensions failed. This error can happen formany reasons, often due to issues with your setup or how NumPy wasinstalled.We have compiled some common reasons and troubleshooting tips at:    https://numpy.org/devdocs/user/troubleshooting-importerror.htmlPlease note and check the following:  * The Python version is: Python3.9 from "/var/lang/bin/python3.9"  * The NumPy version is: "1.21.2"and make sure that they are the versions you expect.Please carefully study the documentation linked above for further help.Original error was: No module named 'numpy.core._multiarray_umath'Traceback (most recent call last): | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': Unable to import required dependencies: numpy: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.9 from "/var/lang/bin/python3.9" * The NumPy version is: "1.21.2" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: No module named 'numpy.core._multiarray_umath' Traceback (most recent call last):
-- | --

**Comment by mattip** [comment]
Again: you have cut off the part of the traceback from the error message that showed the location of NumPy, and whether it is appropriate for `/var/lang/bin/python3.9`. How did you build your lambda? Where did you obtain NumPy? Did you try any of the hints available in the link?

**Comment by rgommers** [comment]
No further follow-up, so closing.
