### ISSUE TITLE
load() with non-binary file-like object fails when checking magic

### ISSUE THREAD

**Issue by igg** [numpy/numpy#19872]
### Reproducing code example:

```python
import numpy as np
fid = open ('foo.npz', 'r')
np.load(fid)
```

### Error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/igg/Projects/viqi/src/venv/lib/python3.8/site-packages/numpy/lib/npyio.py", line 428, in load
    if magic.startswith(_ZIP_PREFIX) or magic.startswith(_ZIP_SUFFIX):
TypeError: startswith first arg must be str or a tuple of str, not bytes

### NumPy/Python version information:

1.21.2
3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]

### Comments:

The issue is that when a non-binary file is read, magic is a string, while _ZIP_PREFIX and _ZIP_SUFFIX are hard-coded as binary. The documentation on npz makes it seem that the encoding param will be used to read the file, but that is not the case when checking the magic number, which is always checked.

Work around seems to be to reopen the file as binary before calling load(). The reason for doing this was to avoid accidentally dropping a lock from calling close() on the file within numpy.

**Comment by rkern** [comment]
The file object must always be opened in binary mode. This is not explicitly mentioned in the `file` argument, so that would be an improvement. Both `.npy` and `.npz` files are both truly binary formats.

The `encoding` argument say that it is "Only useful when loading Python 2 generated pickled files in Python 3, which includes npy/npz files containing object arrays." It's for interpreting the "`str`" array data inside which was ambiguous in Python 2 and needs to be disambiguated to be read in Python 3. It does not affect the file format itself, which is defined in bytes. Unless if you are in a rare situation with really old files, you can ignore this argument. It does not work together with opening the file objects in text mode.

**Comment by dini-rockz93** [comment]
@rkern I would like to update the doc, with reading the file in binary version, can I go ahead !?

**Comment by rkern** [comment]
@dini-rockz93 We do not assign work. If you would like to work on something and feel like you have a firm grasp on what needs to be done, you may go ahead and do so without asking for permission.

We have had a lot of requests like this recently. Would you mind telling us what resource told you that you ought to interact with open source projects like this?

**Comment by dini-rockz93** [comment]
This is the first thing time I am contributing in open source , wasn't sure of the communication part apologies for the ignorance!

I started reading the guidelines and got the gist of it I am picking up this issue

**Comment by rkern** [comment]
No apologies necessary! You didn't do anything wrong.

We're just a little curious since we have suddenly gotten a lot of requests for permission like this in the past couple of months and never had before. We are wondering if there is a common resource that is recommending that new contributors approach open source projects with this style of etiquette. If we can give them some feedback about how this particular project accepts new contributions, we can streamline some of this back-and-forth and get new contributors contributing without pausing for a go-ahead.

**Comment by seberg** [comment]
The docs were actually updated and there was no bug, closing.
