### ISSUE TITLE
Linux flang + clang build support

### ISSUE THREAD

**Issue by DaveWK** [numpy/numpy#19930]
## Feature
Currently it seems flang is only supported for win32 systems:
https://github.com/numpy/numpy/blob/main/numpy/distutils/fcompiler/__init__.py#L744

It would be nice to use the AMD AOCC packages for building to be able to take advantage of the hardware-optimizations:
https://developer.amd.com/amd-aocc/
as well as other use cases where there are flang/clang optimizations on linux, such as AMD's ROCM OpenMP packages. 

I saw this ticket here:
https://github.com/numpy/numpy/issues/13462
but also wanted to request a way to specify clang as well as flang, or if there might be a way to do it via pip that just isn't in the documentation

**Comment by HaoZeke** [comment]
It seems unlikely that the https://github.com/numpy/numpy/commit/3ff922786efcfbee29ae2636be8b381f5e376f69 `flang` included there would work for the current LLVM Flang "F18". Classic `flang` which was based off of `pgifortran` is unmaintained so I wouldn't count on it being used, and it should be removed to avoid confusion. The `flang/clang` optimizations are all `F18` based.

Also since `np.distutils` are deprecated and `distutils` will be removed in Python 3.12.0 in October 2023, it might not be an area worth exploring.

`clang` is very well supported already, so I'm not sure what needs to be done for it.  Another issue (or an edit) with a focus on AOCC would be good. :)

**Comment by rgommers** [comment]
We won't be accepting new features for `numpy.distutils` anymore - I suggest switching to either Meson or CMake. Closing, thanks all
