### ISSUE TITLE
incorrect conversion of pointer in shuffle()

### ISSUE THREAD

**Issue by vorfol** [numpy/numpy#19941]
There are incorrect conversions of pointer in _generator.pyx and mtrand.pyx in shuffle() like:
... = <char*><size_t>np.PyArray_DATA(...)
Therefore pointer will be truncated if size_t is less then char*

### Reproducing code example:

The issue is reproducing on the systems where sizeof(size_t) < sizeof(void*)

```python
import numpy as np
arr = np.arange(10)
np.random.shuffle(arr)
```

### Error message:

Python is crashed with "Bus error"

**Comment by vorfol** [comment]
Do we need this <size_t> in the middle? Can we simply remove it?

**Comment by rkern** [comment]
What platforms are those?

**Comment by seberg** [comment]
Probably OpenVMS, seeing gh-17682?

A bit confusing that it fails, but I guess the `<size_t>` works around some cython stuff not liking `void *`, and `size_t` is not quite guaranteed to be `pointer

In any case, the solution is to use `PyArray_BYTES` instead, which is a `char *` and better anyway.

**Comment by vorfol** [comment]
Platform is OpenVMS, right
I removed <size_t>, built and it worked.
I found a lot of places in code where np.PyArray_DATA(...) is converted to appropriate pointer without <size_t> and it worked well.

**Comment by seberg** [comment]
@vorfol not sure you are still interested in this.  But, I changed the definition for `npy_intp` on the main branch for NumPy 2.0.  That will mean that it isn't possible to downstream binaries for both NumPy 1.x and 2.x on OpenVMS (I assume it is so niche, that this is acceptable, since there are no normal wheels).

That also may have created new bugs here.  OTOH, I think that this should mean reducing the number of subtle bugs a lot.
