### ISSUE TITLE
Broadcasting error when last index is integer

### ISSUE THREAD

**Issue by PeterTillema** [numpy/numpy#19998]
I think I found a broadcasting error when the last index is a single integer.

### Reproducing code example:

```python
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10], [11]])
a[0:2, 2] = b
```

### Error message:

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: could not broadcast input array from shape (2,1) into shape (2,)
```

I expected the output to be `[[1, 2, 10], [4, 5, 11]]`.

### NumPy/Python version information:

1.21.2 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]

**Comment by bashtage** [comment]
Your slice is 1d with shape (2,).   B is 2d with shape (2,1).  You can't reshape a by broadcast since it is immutable on assignment.  You can only broadcast b, but you can't use the rules of broadcasting to reshape (2,1) to (2,). 

```python
a[0:2, 2]
Out[2]: array([3, 6])
```

On the other hand,
```python
a[:2,[2]] = b
```

works fine because `a[:2,[2]]` is (2,1).  

This is the expected and correct behavior from what I can see.

**Comment by PeterTillema** [comment]
I guess that works yeah, thanks!
