### ISSUE TITLE
DOC: flags["WRITEABLE"] = False is cleared upon copy

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#20035]
### Issue with current documentation:

ndarray.copy(), copy.copy(), and copy.deepcopy() all clear a previously set WRITEABLE=False flag:
```
In [1]: t = np.arange(3); t.flags["WRITEABLE"] = False; print(t.copy().flags["WRITEABLE"], copy.copy(t).flags["WRITEABLE"], copy.deepcopy(t).flags["WRITEABLE"])
True True True
```
That's reasonable (as the new arrays are each the only owners of their respective underlying buffers) but not obvious, and could be documented, e.g. at https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html and/or https://numpy.org/doc/stable/reference/generated/numpy.copy.html.

**Comment by sistaseetaram** [comment]
Hey, this seems like a good issue to start with. can I work on this?

**Comment by melissawm** [comment]
@sistaseetaram we don't assign issues, feel free to submit your PR :)

**Comment by seberg** [comment]
I would personally lean towards putting it into the flags documentation.  Setting the writable flag to False is pretty rare: it mainly happens for read-only arrays which are read-only because they have to be (mapping read-only data, and some tricks where data is repeated), so I am not sure it needs "advertising" in a common command (i.e. very few users will set it).  Just my 2 cents, though.  We may also have a preference of `arr.flags.writeable` vs. `arr.flags["writeable"]`?

**Comment by sistaseetaram** [comment]
>I would personally lean towards putting it into the flags documentation

Hi @seberg, do you suggest, I make the above changes?

And what do you mean by 
> We may also have a preference of `arr.flags.writeable` vs. `arr.flags["writeable"]`?
