### ISSUE TITLE
BUG: np.roll tuple in shift argument

### ISSUE THREAD

**Issue by vinith2** [numpy/numpy#20263]
### Describe the issue:

Np.roll shifts the vectors by same amount even if different values are given.

### Reproduce the code example:

```python
x = np.array([[1,0,0,0],[2,0,0,0]])
y = np.roll(x,(2,1),axis=(1,1))
print(y)
```

### Error message:

```shell
[[0 0 0 1]
 [0 0 0 2]]
```

### NumPy/Python version information:

1.21.2 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

**Comment by melissawm** [comment]
Because you are selecting axis=(1, 1), the shift is happening over axis 1 twice, first with a step of 2 and then with a step of 1. The tuple is applied one axis at a time, so you are not supposed to see different shifts in the same axis. We could use an example of a tuple in the axis argument in the documentation, though.

**Comment by vinith2** [comment]
Now I get it. So, There is no functionality for shifting each rows or columns with different shifts. Thank you

**Comment by vinith2** [comment]
I have added the examples as a new pull request. The request id is #20267.
