### ISSUE TITLE
v.1.21.3 wheel missing for python 3.10 32 bit

### ISSUE THREAD

**Issue by FrancescElies** [numpy/numpy#20277]
### Steps to reproduce:

In [Release v1.21.3 · numpy/numpy](https://github.com/numpy/numpy/releases/tag/v1.21.3) one finds the following:

> The NumPy 1.21.3 is a maintenance release the fixes a few bugs
> discovered after 1.21.2. It also provides 64 bit Python 3.10.0 wheels.
> Note a few oddities about Python 3.10:
> 
>   - There are no 32 bit wheels for Windows, Mac, or Linux.

I could not find the reason why is this like this, before I opened an issue here I tried to find an answer in [gitter](https://gitter.im/numpy/numpy?at=6177f8efcd4972068b6d58e6), [stackoverflow](https://stackoverflow.com/questions/69805894/will-numpy-wheels-for-python-3-10-32-bits-be-available/69806586#69806586).

Is stackoverflow, Nils mentioned that azure does not python 3.10 32bits any more, is this the reason for not providing 32bit wheels?

Could you clarify if no longer 32bit wheels will be provided for future versions too?
`pip install/download` is much more convenient than building the wheel orselves or downloading it from [Python Extension Packages for Windows - Christoph Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy)

Related https://github.com/actions/virtual-environments/issues/4400

**Comment by mattip** [comment]
Please take a look at this [mailing list thread](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/6B3VJZ3I5JV4PFJUSRPTN4ABZE7UPAEI/#3O37HETOD637FIH5FWR53QP3ROWHAXHE), where the desire to drop 32-bit builds was discussed. According to that thread, the intent was to continue offering 32-bit windows wheels. Restoring those wheels may need to wait until we finish transitioning to github actions + cibuildwheel, see issue #20262 since that CI service can install any version of python available in the [setup python action](https://github.com/actions/setup-python#available-versions-of-python).

**Comment by FrancescElies** [comment]
Thanks for your answer. I missed #20262 when opening this issue, thanks for the clarification.
As this will be solved as part of that issue I am closing this one.
