### ISSUE TITLE
DOC: The examples for numpy.mat do not demonstrate numpy.mat

### ISSUE THREAD

**Issue by hhoppe** [numpy/numpy#20522]
### Issue with current documentation:

On the doc page https://numpy.org/doc/stable/reference/generated/numpy.mat.html, the examples use `np.asmatrix` but not `np.mat`.

**Comment by WarrenWeckesser** [comment]
Thanks @hhoppe, you're right, the docstring for `mat` actually refers to `asmatrix`.

But that is because `mat` is simply an alias for `asmatrix`.  `mat` is defined here:
https://github.com/numpy/numpy/blob/a81535a364ca2d5aa277977e53c4e2302cae8ea2/numpy/matrixlib/defmatrix.py#L1113

I haven't dug into the history here, so I don't know why it is done this way.  I'd recommend that we deprecate `mat`, but I don't know if there is interest in that code churn now, because the entire `matrix` class is destined for deprecation.

**Comment by melissawm** [comment]
Should we just add a note in the docstring about this being an alias, while these are not deprecated? 

@hhoppe would you be interested in submitting a pull request for this?

**Comment by melissawm** [comment]
numpy.mat has been removed (see https://github.com/numpy/numpy/pull/24376) so this issue is not applicable anymore.

By the way, if you want to always look at the latest version of the docs @linus-md make sure you are looking at the devdocs by selecting "dev" in the upper right-hand corner of the documentation pages. Cheers!
