### ISSUE TITLE
BUG: np.random.choice() truncates bytes elements

### ISSUE THREAD

**Issue by danijar** [numpy/numpy#20532]
### Describe the issue:

The `np.random.choice()` and `np.random.RandomState().choice()` functions truncate trailing zero bytes of elements in the of provided options without raising a warning.

### Reproduce the code example:

```python
import numpy as np
element = bytes('Hello World!'.encode()) + bytes(10)
selected = np.random.choice([element])
print(len(element))  # 22
print(len(selected))  # 12
assert len(element) == len(selected)  # Fails.
```

### NumPy/Python version information:

1.19.5 3.9.7 (default, Oct 19 2021, 19:27:03) 
[GCC 10.3.0]

**Comment by WarrenWeckesser** [comment]
Like most function in NumPy, the `choice` method converts its argument into a NumPy array.  The problem is that NumPy arrays of strings and bytes have a known limitation: the strings cannot contain trailing zeros.  See my comment in https://github.com/numpy/numpy/issues/20118 for more details.

If you *must* use the `choice` method on a sequence of strings while preserving trailing null bytes, you can create the array of choices as an `object` array.  Then, instead being packed into NumPy's internal string array format, the choices remain the original Python objects, and these are the objects that will be returned by `choice`. E.g.:
```
In [16]: element = bytes('Hello World!'.encode()) + bytes(10)

In [17]: choices = np.array([element], dtype=object)

In [18]: rng = np.random.default_rng()

In [19]: selected = rng.choice(choices)

In [20]: selected
Out[20]: b'Hello World!\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

In [21]: len(selected)
Out[21]: 22
```
