### ISSUE TITLE
TYP: subtracting two np.ndarrays is of type NoReturn

### ISSUE THREAD

**Issue by twoertwein** [numpy/numpy#20568]
### Describe the issue:

Subtracting two np.ndarrays is infered to "return" `NoReturn`.

See https://github.com/microsoft/pyright/issues/2696#issuecomment-991751261 for @erictraut's analysis into why pyright infers `NoReturn`.

### Reproduce the code example:

```python
import numpy as np

reveal_type(np.zeros(1) - np.zeros(1))
```

### Error message:

```shell
pyright: Type of "np.zeros(1) - np.zeros(1)" is "NoReturn"
```

### NumPy/Python version information:

1.21.4, 3.9.6

**Comment by a-reich** [comment]
FWIW, with mypy I got Any for this instead of NoReturn.
But with np 1.22.0rc2, I get ` 'numpy.ndarray[Any, numpy.dtype[numpy.floating[Any]]]'`, which is almost fully accurate (except for not having the 64Bit part).

**Comment by BvB93** [comment]
The root of this issue lies in how overload ambiguity is handled (xref https://github.com/microsoft/pyright/issues/2521). The difference between mypy and pyright is that the former will return `Any` in such a situation (as was noted in @a-reich's comment), while the latter will pick the first overload, _i.e._ the `np.bool_`-based one that returns `NoReturn`. 

With the way pyright handles overload ambiguity it effectively means that the arrays dtype _must_ be known, lest you'll end up with inro. This can be accomplished either via explicitly specifying the dtype yourself or via improving the dtype-typing support in numpy itself. 

The good news is that the numpy 1.22 should help quite a bit here, and the specific example that you showed is now successfully inferred as returning an array with a `np.floating`-based dtype. The bad news is that dtype-typing is, quite frankly, non trivial and I expect that a significant number of gaps will remain for the foreseeable future (xref https://github.com/numpy/numpy/issues/19252), gaps that will be filled in with `Any`.

**Comment by twoertwein** [comment]
Great to hear that 1.22.0rc2 resolves this almost perfectly!
