### ISSUE TITLE
ENH: Posting wheels to PyPI for more platforms

### ISSUE THREAD

**Issue by louisabraham** [numpy/numpy#20573]
### Proposed new feature or change:

I'm using https://github.com/pypa/cibuildwheel for some project of mine (https://github.com/louisabraham/pydivsufsort).

Whereas on most platforms it's relatively fast, some linux builds take a LOT of time (15 minutes) because there are no wheels for that configuration.

I'm also using `oldest-supported-numpy` during build.

Examples of platforms where there is no wheel for `oldest-supported-numpy` but there is for `numpy`:
- cp310-manylinux_x86_64
- cp310-manylinux_i686 
- cp310-musllinux_x86_64
- cp310-musllinux_i686

Examples of platforms where there is no wheel at all:
- cp36-musllinux_x86_64
- cp37-musllinux_x86_64
- cp38-musllinux_x86_64
- cp39-musllinux_x86_64
- cp36-musllinux_i686
- cp37-musllinux_i686
- cp38-musllinux_i686
- cp39-musllinux_i686

I believe that uploading those wheels is a relatively easy and one time process that will save a lot of computation for a lot of people (at least those using or building for those platforms). I could probably provide the wheels without too much effort if somebody wants to upload them.

**Comment by charris** [comment]
Last time I looked, there were problems with musl. Do you have success building NumPy with it?

**Comment by mattip** [comment]
I disagree with the statement 
> uploading those wheels is a relatively easy and one time process

Help is welcome maintaining the infrastructure that produces these wheels. I think once you become involved in the process you will discover that producing numpy's wheels is not that simple and certainly not a one-time process. Platforms and CI systems change. We hold our wheels to a high standard and expect they will pass tests. This sometimes requires digging into inconsistencies in OS-provided-runtime's math routines, compiler flags, and more.

I don't understand this row in your list.
- cp310-manylinux_x86_64

[oldest-supported-numpy](https://github.com/scipy/oldest-supported-numpy/blob/c2f8dda2ef992d87e88cd543be0be17800720833/setup.cfg#L53) has this line
```
numpy==1.21.4; python_version=='3.10'
```

and we provide a wheel `numpy-1.21.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`. Which wheel were you expecting to be found?

We have dropped support for 32-bit linux wheels. If you feel strongly there is a use case for them, please open a separate issue specifically for this so we can discuss it in more depth. If you do open the issue, please clearly state what the use case is.

We have dropped support for python3.6 and python3.7 and will not be producing wheels for them, in accordance with [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html).

`mussllinux` is being discussed in #20089 and in the mailing link thread there. To start with, we will need a musslinux-compatible BLAS library, so first we would need a PR to https://github.com/MacPython/openblas-libs. The next step would be a PR to add musllinux to the CI test matrix, to prove that it works (as @charris said: there were some concerns about how to version libc since musllinux does not provide a way to get the version when compiling).

**Comment by louisabraham** [comment]
Weird, I don't see the answer I made before. 

> Last time I looked, there were problems with musl. Do you have success building NumPy with it?

Numpy compiles but the resulting wheel doesn't contain musl in the name. So it's probably not uploadable to PyPI.

@mattip it looks like pip needs to be upgraded else the wheel on `cp310-manylinux_x86_64` is not found. I can provide logs if you want to investigate that.

I guess my issue can be closed!

**Comment by mattip** [comment]
> it looks like pip needs to be upgraded else the wheel on cp310-manylinux_x86_64 is not found

That is weird. Python 3.10 should [bundle pip 21.2.4](https://github.com/python/cpython/tree/3.10/Lib/ensurepip/_bundled) which supports manylinux2014. Where are you getting your python3.10 pip from?

**Comment by mattip** [comment]
> Actually you provide wheels for numpy on `cp310-manylinux_i686`

Which wheel do we provide? Can you provide the complete file name?

**Comment by louisabraham** [comment]
I was wrong about both points. Pip doesn't need to be upgraded, I misread the logs. For cp310-manylinux_i686, pip was just using the wheels from oldest supported numpy that I had compiled before because for that specific python version, they resolve to the same numpy version.

Sorry for the confusion!
