### ISSUE TITLE
BUG: numpy 1.22rc is default build dependency for 'numpy>=1.20.0,<2' in a `pyproject.toml`

### ISSUE THREAD

**Issue by ackagel** [numpy/numpy#20615]
### Describe the issue:

Not sure if this is a pip issue or a numpy issue.  Installing cython modules often requires a numpy build dependency for the C ABI, which takes the form of a `pyproject.toml` file eg:
```
[build-system]
requires = ["setuptools", "numpy>=1.20,<2", "Cython>=0.29.24,<1"]
...
```

Since numpy is often used with compiled cython modules, a matching versioning is used in a requirements file:
```
...
numpy>=1.20,<2
...
```

However, with this configuration, pip currently installs numpy 1.22rc for the build, and then installs numpy 1.21.4 as the required dependency:

<img width="947" alt="Screen Shot 2021-12-17 at 11 11 31 AM" src="https://user-images.githubusercontent.com/36260163/146595984-e7a9ead1-b843-4b12-91d6-d330d4836197.png">

<img width="605" alt="Screen Shot 2021-12-17 at 11 14 19 AM" src="https://user-images.githubusercontent.com/36260163/146596241-739baa3f-8e67-4215-9452-2381f26cbe45.png">

This causes conflicts between the C ABIs.

### Reproduce the code example:

```python
import my_cython_module
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "my_cython_module.pyx", line 1, in init my_cython_module
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

### NumPy/Python version information:

```
1.21.4 3.8.12 (default, Oct 12 2021, 06:23:56)
[Clang 10.0.0 ]
```

**Comment by ksunden** [comment]
https://numpy.org/devdocs/user/depending_on_numpy.html#build-time-dependency

Consider putting a more restrictive limit because it matters at build time.

I don't think there is much numpy can do here, which version is selected would actually be on pip (or possibly the build backend like setuptools)

In general for install you want "most recent that is fully released", but for build you want "oldest that is currently supported by the build". The easiest way to do that is to pin it yourself (or use e.g. the [oldest-supported-numpy](https://numpy.org/devdocs/user/depending_on_numpy.html#build-time-dependency) metapackage as the numpy docs suggest.)

**Comment by ackagel** [comment]
Cool, using `>=1.20.0,<1.22` as the build dep worked fine, but I'll try out the metapackage solution too.  My b for not reading the docs there.

**Comment by seberg** [comment]
It does seem like a bug that it finds a pre-release for installing (unless you passed `--pre` somewhere).  Although in this case that only means you see a real issue earlier.

In general, you must ensure you compile for a version older or equivalent to the one you run it.  This is/was a somewhat common issue, because often you get away with ignoring it for a while and then it ends up annoying/confusing when problems suddenly kick in.

Going to close, since I don't think there is anything to be done on our side, but please feel free to comment or ask to reopen!
