### ISSUE TITLE
BUG: Binning functions give unexpected results for floats between 0 and 1

### ISSUE THREAD

**Issue by annegambrel** [numpy/numpy#20610]
### Describe the issue:

Binning functions (eg.: np.histogram, np.digitize) return non-equal counts per bin for data that is evenly distributed within bins. This may only be an issue for values between 0 and 1. There is an off-by-one issue in which values that match the bin edge value seem to be randomly assigned to the left or right bin, despite (eg, for np.digitize with right=False, or by default for np.histogram) the right bin edge supposedly being excluded from the bin.

### Reproduce the code example:

```python
import numpy as np

scores = np.arange(0, 1, 0.01)

bins = np.arange(0, 1.1, 0.1)

np.histogram(scores, bins=bins)
```

### Error message:

```shell
(array([10, 10, 11,  9, 10, 11,  9, 10, 10, 10]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

Where I expect all of the first array values to be 10, given my evenly distributed data.
```

### NumPy/Python version information:

1.21.2 3.9.5 (default, May 18 2021, 12:31:01)
[Clang 10.0.0 ]

**Comment by WarrenWeckesser** [comment]
@annegambrel, this is not actually a bug.  It is a consequence of imperfect representation of real numbers by finite precision floating point values.  

If you print `bins`, you get:

```
In [2]: bins = np.arange(0, 1.1, 0.1)

In [3]: print(bins)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
```

But the default precision for printing a numpy array is 8 digits, so we're not seeing the full representation of these numbers.  If we change the precision to, say, 17, we'll see a better representation of the actual values in `bins`:

```
In [4]: with np.printoptions(precision=17):
   ...:     print(bins)
   ...: 
[0.                  0.1                 0.2
 0.30000000000000004 0.4                 0.5
 0.6000000000000001  0.7000000000000001  0.8
 0.9                 1.                 ]
```
Another way to see a floating point array displayed with full precision is to convert the array to a Python list. Python always displays floating point values with full precision:
```
In [5]: bins.tolist()
Out[5]: 
[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

```
As you can see, `bins[3]` is not exactly equal to 0.3 [†].  This is the result of "normal" floating point error in the calculation performed by `np.arange`.

Now look at the relevant values in `scores`:

```
In [9]: scores = np.arange(0, 1, 0.01)

In [10]: scores[20:31].tolist()
Out[10]: [0.2, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3]
```
There are the 11 values that end up in the third bin, because `scores[30]` is 0.3, which is less than `bins[3]`.

-----
[†] Note that the 64 bit floating point value that displays as `0.3` is also not equal to the value 3/10; the actually value is 0.299999999999999988897769753748434595763683319091796875, but `0.3` is the shortest string representation of the value that will give us that 64 floating point value.
