### ISSUE TITLE
BUG: matching with comparison using indexed array values

### ISSUE THREAD

**Issue by jddmartin** [numpy/numpy#20627]
### Describe the issue:

Python 3.10 match does not work as expected using indexed numpy array.

### Reproduce the code example:

```python
"""Demonstrate problem with python match involving
indexed numpy array
"""

import sys
import numpy as np

print("python: ", sys.version)
print("numpy: ", np.__version__)

x = np.arange(-3, 4)
#x = list(range(-3, 4)) # uncomment and the code works!

for i in range(len(x)):
    match (x[i] >= 0):  # using float(x[i]) works
        case True:
            print("got true match")
        case False:
            print("got false match")
        case _:
            raise RuntimeError
```

### Error message:

```shell
python:  3.10.1 (main, Dec  8 2021, 04:50:03) [GCC 7.5.0]
numpy:  1.21.4
Traceback (most recent call last):
  File "/home/jddmartin/dynamic/code/rstark/crazy_match.py", line 22, in <module>
    raise RuntimeError
RuntimeError
```

### NumPy/Python version information:

python:  3.10.1 (main, Dec  8 2021, 04:50:03) [GCC 7.5.0]
numpy:  1.21.4

**Comment by WarrenWeckesser** [comment]
This is not a bug; it is a consequence of NumPy having its own boolean type.
`x[i] >= 0` returns a `numpy.bool_` instance, not a Python  `bool`:
```
In [15]: x = np.arange(-3, 4)

In [16]: p = x[0] > 0

In [17]: p
Out[17]: False

In [18]: type(p)   # p is an instance of numpy.bool_, not a Python bool.
Out[18]: numpy.bool_

```


  In the section [`Matching specific values`](https://www.python.org/dev/peps/pep-0636/#matching-specific-values) of PEP 636, it says

> Literal values are compared with the == operator except for the constants True, False and None which are compared with the is operator.

so the attempt to match `x[i] > 0` with the literal values `True` or `False` will fail:
```
In [19]: p is False  # p is a numpy false value, but it is not identical to the built-in False object.
Out[19]: False

In [20]: p == False
Out[20]: True
```
Any change that results in the match expression evaluating to a Python `True` or `False` (instead of a `numpy.bool_`) will fix your code.  That includes using a list of Python integers for `x` or converting `x[i]` to a Python `float` before comparing it to 0, as you discovered.  You could also wrap the exression in `bool`:

```
    match (bool(x[i] >= 0)):
```

**Comment by jddmartin** [comment]
Thank you very much for your detailed explanation.  Apologies for posting as bug.

**Comment by WarrenWeckesser** [comment]
No need to apologize!  It is not an obvious issue.
