### ISSUE TITLE
ENH: SVD could be faster by using covariance matrices

### ISSUE THREAD

**Issue by hugorichard** [numpy/numpy#20716]
### Proposed new feature or change:

When you perform an SVD of a matrix X of size (p, n) with p >> n, the current implementation is slower than if the SVD is done on the covariance matrix X.T.dot(X) .
Here is a synthetic experiment to illustrate this phenomenon:

In [1]: import numpy as np

In [2]: X = np.random.randn(int(1e5), int(1e3))

In [3]: %time A = np.linalg.svd(X, full_matrices=False)
CPU times: user 1min 49s, sys: 11.1 s, total: 2min 1s
Wall time: 17.2 s

In [4]: %time A = X.T.dot(X)
CPU times: user 5.91 s, sys: 782 ms, total: 6.69 s
Wall time: 840 ms

The SVD of A takes a very small time and given the SVD of A we can recover the one of X efficiently.

My suggestion is to use this to speed up the SVD. If this sounds interesting, I can work on a PR.

**Comment by charris** [comment]
Using the covariance matrix can be faster due to its smaller size, but it is also less accurate due to the squaring.

**Comment by charris** [comment]
There are also several methods of linear least squares where there are similar tradeoffs. The naive method introduced in elementary texts may be the fastest for some problems. The QR method is not quite as fast, but is more accurate. And the SVD method is preferred these days because it better handles ill posed problems.
