### ISSUE TITLE
BUG: concatenate looses byteorder

### ISSUE THREAD

**Issue by vttrifonov** [numpy/numpy#20767]
### Describe the issue:

Concatenating arrays in big-endian produces array in little-endian (on my machine).

### Reproduce the code example:

```python
import numpy as np
x = np.array([1], dtype='>i4')
y = np.array([2], dtype='>i4')
z = np.concatenate([x, y])
print(x.dtype, y.dtype, z.dtype)

# >i4 >i4 int32
```

### NumPy/Python version information:

1.20.3 3.7.0 (default, Jun 28 2018, 07:39:16) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by seberg** [comment]
This is currently probably (still) necessary, because the same decisions that does this, is used in some cases where native byteorder is required.  Most of those cases are being phased out.

But I am sure we are better of if we actually did change it at some point:  In general non-native byte-order is extremely slow and unwieldy to use.  Changing the byte-order to native here is actually doing you a favor in most things you end up doing with the result (unless you are aiming to export a buffer with big-endian numbers) since the step is copying the data anyway already and non-native byte order would just be very slow to use for everything.

If you actually want to force `>i4` for the result, you can do so on newer NumPy versions using `dtype=np.dtype(">i4")`

**Comment by vttrifonov** [comment]
Thanks. This makes sense. I do not care very deep about byteorder in general and stick to the machine order, as you suggest. This came up as an edge case of a data storage project which cares more about this kind of stuff. At the moment, I went around this by doing what you suggested, but it stuck me as odd. Convenience aside, it it unexpected... I will let you decide if you want to call this a feature and close or keep it open for the future to decide.

**Comment by seberg** [comment]
I don't disagree that it feels a bit inconsistent, but I the unexpected "inconsistency" only affects projects that are sensitive about data storage as opposed to data content.  The vast majority of users will not care about data storage details though.

NumPy is consistent about the values stored (usually...), but not necessary how they are stored (memory order is not always preserved and here dtype is not as well; another example that sometimes surprises is that scalars do not have a byte-order at all).  And since most users do not care about those, I think that is probably a pragmatic and likely better choice.

That is debatable, but feels like a bit of an uphill battle: You need to argue that modifying it would do more good than harm.  So I am going to close, but happy if anyone disagrees and reopens/asks to reopen.
