### ISSUE TITLE
ENH: np array with variable number of dimensions and internal indexing

### ISSUE THREAD

**Issue by LFBJC** [numpy/numpy#20782]
### Proposed new feature or change:

Today when we create a numpy array from a list of array_likes with different dimensions we get a numpy array of objects with the elements of the list inside, I don't know how many people might benefit from it, but, if it's worthy the effort, my suggestion is the following: Suppose we have a list with differently shaped array_likes for example with shapes (10,4), (10,), (10,255,255,255,3) and maybe something different on the first dimension like (5,3,2) we would than create an array that could be indexed like a 2D array with indexes ranging from 0 to 3 on the first dimension (as there are for array_likes in the example) and from 0 to the last index of the element that has the smaller second dimension (in this case 0 to 5 as 5 is the smaller 2nd dimension)

**Comment by mattip** [comment]
[NEP 34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html) is a first step in the opposite direction: disable creating "ragged" arrays at all. I think you might be more interested in the [awkward array](https://github.com/scikit-hep/awkward-1.0) project, which I think has the feature you seek.

**Comment by seberg** [comment]
I am going to close this, I agree with Matti:  This is not a core feature of NumPy, and it is not on our road-map, nor likely to land on it anytime soon.
Personally, I doubt this will ever.  What can happen is that NumPy can try to make more of its internal machinery available to other projects that try to implement this type of thing (but frankly, this is only likely if some influx of devs interested in this).  I.e. so that these projects can work together seamlessly.
