### ISSUE TITLE
numpy/random/mtrand.pyi didn't give the docstrings

### ISSUE THREAD

**Issue by Vincent0706** [numpy/numpy#20809]
### Describe the issue:

I use vscode as my IDE. And vscode provide the type information and docstrings come from numpy itself. I found the `numpy/random/mtrand.pyi` didn't give any docstrings. It makes the vscode can't give the the type information and docstrings.

![image](https://user-images.githubusercontent.com/82581024/149274297-ea6f4551-2b6a-4ec8-8770-c32e18f8bcfb.png)

### Reproduce the code example:

```python
np.random.choice
```

### NumPy/Python version information:

1.22.0 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

**Comment by bashtage** [comment]
I think this is a VS code bug.  pyi files don't usually (ever?) contain doc strings.

**Comment by Vincent0706** [comment]
I found the old version(1.20.3) have the different situation.

![image](https://user-images.githubusercontent.com/82581024/149313337-ac88f999-dd98-4657-a238-6f1bddd34daa.png)

**Comment by bashtage** [comment]
This is happening because pylance is all or nothing with typing.  As of 1.22, NumPy has complete typing information, and so pylance is using the information in the pyi files for typing. In earlier versions, it was using a fallback mechanism. This issue can only be fixed by pylance, because it isn't sensible to relocate docstrings to pyi files.

**Comment by BvB93** [comment]
Vscode seems to be rather inconsisstent for which functions it can and can't display docstrings. For example, with `np.array` it does not display a docstring but for `np.bincount` (which is located in the same module) it does.

Anyway, as @bashtage previously noted this issue is better suited for the vscode repro.

**Comment by seberg** [comment]
Closing, it seems indeed an issue for another issue tracker.  It sounds like there is nothing NumPy can (or should) do about it.
