### ISSUE TITLE
DEV: Merge the `static typing` and `component: numpy.typing` labels

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#20837]
There are currently two typing-related labels with so much overlap that I'm even sure where one begins and the other ends. Would it be worthwhile to merge the two? Based on how the labels are structured I feel that keeping `component: numpy.typing` would be the most apropriate here.

**Comment by mattip** [comment]
Makes sense, especially since you are the owner for much of this content. Do you have the needed permissions to change the labels? 

I did find the secret to querying multiple labels is to add a comma, so this search works [`label:"component: numpy.typing","static typing"`](https://github.com/numpy/numpy/issues?q=label%3A%22component%3A+numpy.typing%22%2C%22static+typing%22+)

**Comment by seberg** [comment]
Closing, added the "static typing" label to the 2 remaining issues, and will delete the component one now.
