### ISSUE TITLE
BUG: np.linalg.eig() returns wrong eigenvectors on some instances

### ISSUE THREAD

**Issue by Kidara** [numpy/numpy#20961]
### Describe the issue:

The code below should print the matrix m, as it rebuilds m from its eigenvalues and eigenvectors, but it does not.
The error appears to be in the result of np.linalg.eig().

### Reproduce the code example:

```python
import numpy as np

m = [[ 1, 0,-1, 0],
     [ 0, 1,-1, 0],
     [-1,-1, 3,-1],
     [ 0, 0,-1, 1],]

evalues, evectors = np.linalg.eig(m)

print(np.matmul(np.matmul(evectors,np.diag(evalues)),evectors.T))
```

### Error message:

```shell
Expected result:
[[ 1, 0,-1, 0],
 [ 0, 1,-1, 0],
 [-1,-1, 3,-1],
 [ 0, 0,-1, 1],]

Actual result:
[[ 1.024  0.095 -1.    -0.119]
 [ 0.095  0.881 -1.     0.024]
 [-1.    -1.     3.    -1.   ]
 [-0.119  0.024 -1.     1.095]]
```

### NumPy/Python version information:

1.19.5 3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]

**Comment by WarrenWeckesser** [comment]
Because your matrix has a repeated eigenvalue (λ = 0 has multiplicity 2), the matrix `evectors` computed by `eig` is not orthognal, so you cannot form its inverse as `evectors.T`.  If you replace that with `np.linalg.inv(evectors)`, you will get the expected result (with small errors that are the result of normal numerical imprecision).

`eig` doesn't "know" that your matrix has a repeated eigenvalue. When I run the code,  `eig` returns two values, 0.9999999999999993 and 1.0.  For `evectors` to be orthogonal, `eig` would have to choose two orthogonal vectors from within the two-dimensional eigenspace associated with the eigenvalue λ = 0.  But as far as `eig` is concerned, there are two distinct eigenvalues, so the eigenvectors it computes for these values will not, in general, be orthogonal.

**Comment by WarrenWeckesser** [comment]
Note that for a matrix that you know is symmetric, you can use `np.linalg.eigh` to compute the eigenvalues and eigenvectors.  With `eigh`, your original calculation works as you expected:

```
In [28]: np.set_printoptions(suppress=True)  # Display tiny values such as 1.23e-16 as 0.0

In [29]: evals, evecs = np.linalg.eigh(m)

In [30]: evecs @ np.diag(evals) @ evecs.T
Out[30]: 
array([[ 1.,  0., -1.,  0.],
       [ 0.,  1., -1.,  0.],
       [-1., -1.,  3., -1.],
       [ 0.,  0., -1.,  1.]])
```
