### ISSUE TITLE
BENCHMARK: einsum is slower than explicit chained multiplications

### ISSUE THREAD

**Issue by catkira** [numpy/numpy#21019]
### Describe the issue:

I have replaced the last 3 lines in this code
```python
A = np.ones((150000,3,3))
j = np.ones((150000))
s = np.ones((150000))
jDuplicated = np.repeat(j, 3**2).reshape((len(elements), dim, dim))
sDuplicated = np.repeat(s, 3**2).reshape((len(elements), dim, dim))
res= sDuplicated * A @ np.swapaxes(A,1,2) * jDuplicated
```
with
```python
res = np.einsum('i,i,ijk,ilk->ijl',s,j,A,A)
```
The single line looks much better than duplicating a lot of data so that I can perform element-wise multiplication. However the top version is around 10% faster on my pc.

I would expect einsum to be faster, since it does not replicate a lot of data. Does anybody have an idea why this is not the case? Maybe the repeated data causes less cache misses?

### Reproduce the code example:

```python
import numpy as np

A = np.ones((150000,3,3))
j = np.ones((150000))
s = np.ones((150000))
# the numbers might need to be random to avoid simplification
res = np.einsum('i,i,ijk,ilk->ijl',s,j,A,A)
```

### NumPy/Python version information:

1.22.1 3.10.2 (main, Jan 15 2022, 18:03:19) [GCC 7.5.0]

**Comment by catkira** [comment]
"BUG" is the wrong label, it should be "BENCHMARK". How can I change that?

**Comment by seberg** [comment]
Going to close this, it amounts to "optimizations may be possible" IMO, which is always true and 10% is really not much at all.

linear algebra `@` can be much faster because it uses BLAS in the background which is typically super hand-optmized coded, that einsum simply can't compete with.  It is expected.

Einsum however, *does* have `optimize=True`, which you can try for larger inputs and it may be much faster as it _may_ use `@` internall _and_ optimize iteration order.
