### ISSUE TITLE
BUG: mean() and std() of a masked_array ignore dtype and return result as float64

### ISSUE THREAD

**Issue by mashatarasevich** [numpy/numpy#21023]
### Describe the issue:

Functions `ma.mean()` and `ma.std()` return result of dtype `np.float64` when the array has `np.float32` type. This is inconsistent with `numpy.mean()` and `numpy.std()` behavior. Moreover, if dtype is explicitly given as an argument to the function, it is ignored.

### Reproduce the code example:

```python
import numpy as np
import numpy.ma as ma

def test1():
    x = ma.masked_array([[1, 2],[2, 4]], dtype=np.float32, mask=[[True, False], [False, True]])
    y = x.mean(axis=0)
    print(f'Type of result is {y.dtype}')

def test2():
    x = ma.masked_array([[1, 2],[2, 4]], dtype=np.float32, mask=[[True, False], [False, True]])
    y = x.mean(axis=0, dtype=np.float32)
    print(f'Type of result is {y.dtype}')

test1()
test2()

# Expected output
# Type of result is float32
# Type of result is float32

# Actual output
# Type of result is float64
# Type of result is float64
```

### NumPy/Python version information:

1.20.1 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]

1.21.2 3.9.5 (default, Jun  4 2021, 12:28:51) 
[GCC 7.5.0]

**Comment by soma2000-lang** [comment]
Working on this@

**Comment by Adarshsng** [comment]
Hello @mashatarasevich,

This is happening because incase of the masked array the mean gets calculated using sum/count, where the sum's dtype 
is based on your given input at `x.mean(axis=0, dtype=np.float32)` but the count's dtype is always fixed with `np.int64`
Therefore, when the mean is calculated the result also becomes `np.float64`, irrespective of your given input.

Do check line #5253
https://github.com/numpy/numpy/blob/v1.22.0/numpy/ma/core.py#L5217-L5262

**Comment by mattip** [comment]
#20914 was merged, which should fix this. Closing. Please reopen or open a new issue if I am mistaken.
