### ISSUE TITLE
macos wheels don't work on macos < 10.14

### ISSUE THREAD

**Issue by justvanrossum** [numpy/numpy#21066]
### Describe the issue:

As of numpy 1.22.2, the macos wheels require macos 10.14 or later. 1.22.1 provides wheels that work back to 10.9. Is this a conscious decision? It seems a bit odd for a micro version bump to change os requirements so drastically.

### Reproduce the code example:

```python
`pip install numpy` fails on macos 10.13.
```

### NumPy/Python version information:

1.22.2

**Comment by charris** [comment]
For some reason, Python 3.8 didn't work with 10.9. OS X 10.14 is the oldest Apple supported version.

**Comment by rgommers** [comment]
@charris the change may be fine (and IIRC there are other projects already using >= 10.13 anyway), but it's a significant change for a bugfix release and it's not mentioned in the release notes as far as I can tell (https://github.com/numpy/numpy/releases/tag/v1.22.2). 

Can we edit the release notes to include this change? And do you have a link to the relevant issue or PR?

**Comment by rgommers** [comment]
ah, this is gh-20893

**Comment by rgommers** [comment]
I think we should edit the release notes, and leave it at that.

**Comment by charris** [comment]
I did mention it in the mailing list post, but it does also belong in the release notes. I think the problem was that azure recompiled the latest Python 3.8 source release with 10.14 at some point. There was an environment number that changed when azure would no longer build against 10.9. We have been getting hit by a lack of stability in azure. Note that we could use 10.9 with Python 3.9 and 3.10, so it was extra annoying.

We can hope that github workflows are more stable.

**Comment by justvanrossum** [comment]
This problem seems to have been resolved: the provided wheels for numpy 1.24.0 seem to works just fine on macOS 10.10.
