### ISSUE TITLE
DOC: typo on website for numpy.argpartition

### ISSUE THREAD

**Issue by JosephMPedersen** [numpy/numpy#21093]
### Issue with current documentation:

I believe that there is a typo at:

https://numpy.org/doc/stable/reference/generated/numpy.argpartition.html

accessed 2/19/2022

Returns:	index_array : ndarray, int
Array of indices that partition a along the specified axis. If a is one-dimensional, a[index_array] yields a partitioned a. More generally, np.take_along_axis(a, index_array, axis=a) always yields the partitioned a, irrespective of dimensionality.

I think the code in np.take_along_axis( ) should have axis=-1

When I tried the code with axis=a, I got an error, but when I tried with axis=-1 it worked as desired.

**Comment by Adarshsng** [comment]
I suppose you are correct over here as incase :

if 'a' (array) is 1D it must be written as 
`np.take_along_axis(a, index_array, axis=-1) `
or
`np.take_along_axis(a, index_array, axis=0)`

Since both of them 0 or -1 point to the same dimension.

Whereas in the case of 2D arrays :
```
a = np.array([[10, 30, 20], [60, 40, 50]])
ai = np.argpartition(a, 2, axis=1)
print(np.take_along_axis(a, ai, axis=1))
```
the axis given to  `np.argpartition` must be equal to the axis given to `np.take_along_axis`

Do le me know if I am understanding it correctly .

**Comment by JosephMPedersen** [comment]
Yes, you are understanding me correctly.  The website currently has ```axis=a```, where ```a``` is the name of the array, which must be a typo.  But, whereas I said that I thought it should be ```-1```, I agree with your reply that it should actually be the same ```axis``` given in ```np.argpartition```, as in:
```
a = np.random.randint(0,100,size=210).reshape((5,6,7))
ax = 0 # or 1, or 2, or -1, or -2, or -3
ai = np.argpartition(a, kth=2, axis=ax)
print(np.take_along_axis(a, indices=ai, axis=ax))
```
