### ISSUE TITLE
BUG: long integer modulus bug

### ISSUE THREAD

**Issue by Ruws99** [numpy/numpy#21112]
### Describe the issue:

When using np.floor_divide() on long integers the results are sometimes wrong.

### Reproduce the code example:

```python
import numpy as np

print(np.mod(10888869450418352160,10))
>>8.0
```

### NumPy/Python version information:

numpy version 1.22.2

**Comment by rossbar** [comment]
I think this is an unfortunate consequence of value-based casting - the first value is cast to a floating point value prior to the operation, which is what leads to the unexpected result.

It's not a solution (nor would I even necessarily recommend it), but just note that if you know you're working with very large integers, you can explicitly use `object` dtype to avoid the cast:

```python
>>> np.mod(np.asarray(10888869450418352160, dtype=object), 10)
0
```

**Comment by seberg** [comment]
Yeah, it is the old `uint64` thing.  That Number does fit into `np.uint64(10888869450418352160)`, but not `np.int64(10888869450418352160)`.  The 10 is then considered `int64` though (because you know, value-based casting only truly kicks in if there are some non-scalars around).

The `uint64` and `int64` promotes to `float64` (because that is how it is right now).

xref gh-20905 and many others  (we can probably close this as a duplicate).

**Comment by rossbar** [comment]
Thanks @seberg  - I agree let's close as duplicate. Thanks for reporting @Ruws99 , IMO this is a particularly compelling example of how this promotion can bite users.
