### ISSUE TITLE
BUG: Unexpected behaviour of (arg)?(min|max) on non-arrays

### ISSUE THREAD

**Issue by namednil** [numpy/numpy#21129]
### Describe the issue:

When objects that are neither arrays (or alike) are passed to `np.min`/`np.max`, these functions seem to behave as identities, which is surprising if objects of that type are not even comparable. Consistent with that but also surprisingly, `np.argmin`/`np.argmax` return 0; since 0 has the right type, it makes it hard to spot the mistake down the line.

I think the desired behaviour would be to throw an exception.

### Reproduce the code example:

```python
import numpy as np
class T:
  pass

print(np.min(T()))
print(np.argmin(T()))

print(np.max(T()))
print(np.argmax(T()))

#Can lead to bugs that are hard to spot:
print(np.argmin((-i for i in range(10))))
```

### NumPy/Python version information:

1.22.2 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]

**Comment by BvB93** [comment]
Due to the input being cast into an object array, the behavior you're seeing is (more or less) equivalent to the likes of `max([object()])`, which also evaluates to `True`. It is only when a sequence with multiple arbitrary objects is passed that the exception that you initially expected is observed:

``` python
In [1]: import numpy as np

In [2]: max([object()])
Out[2]: <object at 0x21967ffd740>

In [3]: max([object(), object()])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
  ...
TypeError: '>' not supported between instances of 'object' and 'object'

In [4]: np.max([object(), object()])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
  ...
TypeError: '>=' not supported between instances of 'object' and 'object'
```


> ``` python
> #Can lead to bugs that are hard to spot:
> print(np.argmin((-i for i in range(10))))
> ```

As a generator is not a sequence, the input will be interpreted as an object array with a single element (_i.e._ the generator object). Simply put: `np.min` and the likes are not drop in replacements for their `builtins` counterpart as it is not designed to work on arbitrary iterables. This becomes especially apparent when not working with more conventional array-like objects, such as a list of integers or an array thereof.

**Comment by namednil** [comment]
Thank you for the explanation for why this happening. Are you saying because the builtin `max` and `min` behave like this, numpy should so too? I'm struggling to see a use case, and even if there is one, not throwing an exception might encourage code that is hard to read.

**Comment by seberg** [comment]
Closing, this is just generic behavior of coercing to NumPy arrays, we could try to be stricter for iterators, see gh-15625 for that.
