### ISSUE TITLE
No module named _multiarray_umath - BeagleBone Black

### ISSUE THREAD

**Issue by rcherrey** [numpy/numpy#21172]
I am receiving an import error from numpy that says "Importing the multiarray numpy extension module failed.  Most likely you are trying to import a failed build of numpy... Original error was: No module named _multiarray_umath." Python and numpy came preinstalled on my BeagleBone Black, but I changed the default Python version to 3.7 (there are multiple version of Python installed).  I'm using Linux to write commands to the BeagleBone. I tried "pip install --upgrade --force-reinstall numpy" Any help would be incredibly appreciated!!! Thank you.

**Comment by charris** [comment]
Use `python -m pip install ...`. There is no way to know what python version bare `pip` installs to.

**Comment by seberg** [comment]
Going to close the issue.  I hope the suggestion to use `python -m pip` to make sure you got the right `pip` helped.  If there are more problems, it may also make sense to ask in a BeagleBone related forum.
Otherwise, please feel free to follow-up, and we may reopen.  But please do provide the complete traceback, since it contains some additional information.
