### ISSUE TITLE
BUG: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by HoangTienDuc** [numpy/numpy#21179]
### Describe the issue:

• Hardware Platform GPU RTX 2080ti
• DeepStream Version 6.0 [triton](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/deepstream)
• Python Version: 3.6.15

Successful to install NumPy (1.19.5, 1.19.4, 1.19.3, 1.19.2) on Deepstream triton 6.0. However, these NumPy versions are still the cause of the code dumps.
Alternatively, I also tried python3-numpy, but it still doesn’t work.
Hope to get help! Thanks

### Reproduce the code example:

```python
n_frame = pyds.get_nvds_buf_surface(hash(gst_buffer), frame_meta.batch_id)
frame_copy = np.array(n_frame, copy=True, order='C')
rgb_frame = cv2.cvtColor(frame_copy, cv2.COLOR_RGBA2RGB)
```

### Error message:

```shell
I0311 07:45:17.484594 10848 plan_backend.cc:859] Created instance detector_0_0_gpu0 on GPU 0 with stream priority 0 and optimization profile default[0];
I0311 07:45:17.484653 10848 model_repository_manager.cc:1212] successfully loaded 'detector' version 1
INFO: infer_trtis_backend.cpp:206 TrtISBackend id:1 initialized model: detector
Decodebin child added: source 

Now playing...
Starting pipeline 

Decodebin child added: decodebin0 

Decodebin child added: rtph264depay0 

Decodebin child added: h264parse0 

Decodebin child added: capsfilter0 

Decodebin child added: nvv4l2decoder0 

In cb_newpad

gstname= video/x-raw
Decodebin linked to pipeline
Segmentation fault (core dumped)
```

### NumPy/Python version information:

1.19.5, 1.19.4, 1.19.3, 1.19.2, python3-numpy

**Comment by mattip** [comment]
Before you call `rgb_frame = cv2.cvtColor(frame_copy, cv2.COLOR_RGBA2RGB)`, can you verify that `frame_copy` is valid? I don't know what `pyds` is, perhaps it is holding data on the GPU. The call `np.array(n_frame, copy=True, order='C')` can take many different paths, some of them use protocols that can return incompatible arrays. So try iterating over `frame_copy` to see if the values make sense.

**Comment by seberg** [comment]
Which lines does this crash on?  I assume the last one?  In that case `np.array` succeeded and should have created a copy and it seems very unlikely (but not impossible) that there is anything wrong with `frame_copy`:  As Matti said, it would be good to confirm that `frame_copy` behaves OK.  If it behaves OK (prints out, does normal math) it would seem to be an issue with `cv2.cvtColor`.

If the `np.array` call already fails, the issue is probably in [`get_nvds_buf_surface`](https://docs.nvidia.com/metropolis/deepstream/5.0DP/python-api/Methods/methodsdoc.html#get-nvds-buf-surface) – assuming that is the documentation for it; since it is says it returns a NumPy uint8 array already.

[Running GDB](https://numpy.org/devdocs/dev/development_environment.html#debugging) may help with getting a better idea of what is going on:
```
gdb --args python reproducer.py
```
Then type:
```
run
```
After things crash, use `bt` to get the backtrace and paste it here (or have a look yourself), you may need a `q` for quit or just an enter in there.

**Comment by HoangTienDuc** [comment]
Thank all of you! My bad. This error does not come from numpy.

**Comment by vipingautam1906** [comment]
@HoangTienDuc Did you solve this? I am also stuck. I think there is some issue with n_frame because when I try to print(n_frame) it causes segmentation fault so it's certainly not a numpy issue.

**Comment by Rm1n90** [comment]
@PonyPC, @mattip, @seberg, @mfoglio, @HoangTienDuc, @vipingautam1906 Did you able to solve? I'm facing the same error...

**Comment by mattip** [comment]
This issue is closed. Please open a new one if there is anything NumPy-related that we can discuss.
