### ISSUE TITLE
BUG: _percentile_dispatcher() got an unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by pEtienn** [numpy/numpy#21184]
### Describe the issue:

The np.percentile function does not recognize the "method" argument. This can be reproduce with the code below or the example code in the doc page.

### Reproduce the code example:

```python
np.percentile(np.arange(100),np.arange(100),method='linear')
```

### Error message:

```shell
TypeError                                 Traceback (most recent call last)
c:\Users\Etienne\Documents\GitHub\tensorflow_testing\npyTest.ipynb Cell 2' in <module>
----> 1 np.percentile(np.arange(100),np.arange(100),method='linear')

File <__array_function__ internals>:4, in percentile(*args, **kwargs)

TypeError: _percentile_dispatcher() got an unexpected keyword argument 'method'
```

### NumPy/Python version information:

My computer:
1.21.5 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
and Google colab default env:
1.21.5 3.7.12 (default, Jan 15 2022, 18:48:18) 
[GCC 7.5.0]

**Comment by seberg** [comment]
Thanks for the note, but the method kwarg is [new in NumPy 1.22](https://numpy.org/devdocs/release/1.22.0-notes.html#add-new-methods-for-quantile-and-percentile) and you are using 1.21.5.
If you are on earlier NumPy versions (or want compat) `"linear"` is alwasy the default, so no need to pass it.  Otherwise, `interpolation=` may work, but is more limited in features.

I am a bit surprised that the `TypeError` mentioned `_percentile_dispatcher` and not `percentile`, but that seems unrelated to the issue at hand.
