### ISSUE TITLE
DOC: inconsistency at numpy.random.normal.html

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#21195]
### Issue with current documentation:

https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html says:

`
New code should use the normal method of a default_rng() instance instead; please see the [Quick Start](https://numpy.org/doc/stable/reference/random/index.html#random-quick-start).`

However, at the linked page, the method is called `standard_normal,` not `normal`.

**Comment by rkern** [comment]
No, there is still a [`normal()` method](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.normal.html).

**Comment by keithbriggs** [comment]
There may be a `normal` method, but it's not mentioned at `https://numpy.org/doc/stable/reference/random/index.html#random-quick-start,` which the link given on the doc page, so this is confusing.

**Comment by rkern** [comment]
This note is boilerplate. It's on all of the `np.random` convenience methods, not just `np.random.normal()`. The intention is to tell you to use `default_rng()` to get a `Generator` instance and use its methods. The linked text does say that the methods on `Generator` are a drop-in replacement for these old methods, with the noted exceptions. We can't have an explicit example for every single method. While the wording of the boilerplate note could stand to be improved to help give context for what the link is going to be about (i.e. how to get a `Generator` rather than a line-by-line replacement for this specific method), I don't think the linked text is the issue.

**Comment by keithbriggs** [comment]
ok.
