### ISSUE TITLE
BUG: Subtraction of uints that should result in negative number overflows without warning

### ISSUE THREAD

**Issue by cwestc** [numpy/numpy#21237]
### Describe the issue:

When subtracting uints that would result in a negative number, the result is an overflowed unsigned int without warning.

Subtracting two uint16 arrays:

[1,1,1] - [2,2,2] = [65535,65535,65535]

OS: Windows 10

### Reproduce the code example:

```python
import numpy as np

print(np.array([1,1,1], dtype='uint16') - (np.array([2,2,2], dtype='uint16'))
```

### NumPy/Python version information:

NumPy: 1.20.3
Python:  3.9

**Comment by charris** [comment]
NumPy uses modular arithmetic for integers, that is documented. The reason is that modern processors don't have hardware support for detecting integer overflow, so doing so would slow things down. This has been a complaint about processors for the last 30 years :) We may come up with a solution at some point, but we don't want to slow down normal computations.

**Comment by seberg** [comment]
Closing, the behavior is correct and while warnings might be nice, we have generic issues about integer warnings, for example gh-8987.
