### ISSUE TITLE
BUG: numpy.array(sample_python_list) and numpy.array(sample_python_list, dtype=numpy.float64) have different running time.

### ISSUE THREAD

**Issue by salehmontazeran** [numpy/numpy#21259]
### Describe the issue:

`numpy.array(sample_python_list)` and `numpy.array(sample_python_list, dtype=numpy.float64)` have different running time.

### Reproduce the code example:

```python
import time

import numpy as np

a = list(range(100000000))
start = time.time()
np.array(a)
end = time.time()
print("Without dtype:", end - start)

start = time.time()
np.array(a, dtype=np.float64)
end = time.time()
print("With dtype:", end - start)
```

### NumPy/Python version information:

1.22.3
3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0]

**Comment by rkern** [comment]
Sure, you're asking it to do two different things with two different resulting objects (note that the final dtypes of the resulting arrays differ). It's not a bug for them to have two different running times.

**Comment by rkern** [comment]
It does for me, at least on average. Note that running just one timing is prone to error. There's lots of stuff going on in your system that can cause fluctuations. Sometimes I have the former running faster and sometimes slower. Never a very large difference; all well within the natural variation I get when running each one multiple times.

Regardless, when you give a function different arguments, you are asking it to do two different things. It will take different codepaths, and those can take different amounts of time, even in the case when the final result is the same.

**Comment by bashtage** [comment]
This is pretty much as expected. When you tell NumPy the type, it will get on with filling the array with your requested type and only raise if there is a problem coercing.  Otherwise, it has to constantly check whether the types of each object you passed can fit into a specific type.  

```python
%timeit np.array(a, dtype=float)
3.89 ms ± 41.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit np.array(a, dtype=int)
3.28 ms ± 56.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
float and int are the fastest.

```
%timeit np.array(a)
5.45 ms ± 36 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
detecting is slower because it has to check each vale when deciding the array type.

```
a[0] = 0.0

%timeit np.array(a)
7.58 ms ± 55 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Slower even when double again because the the required checks.


Make the final element complex to show that it is checking every element
```
a[-1] = 3.0+2.0j

%timeit np.array(a)
9.19 ms ± 40 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Even worse, make the penultimate element a string so that the array has to be `object` dtype.
```
a[-2] = "apple"

%timeit np.array(a)
22.7 ms ± 45.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Much slower, mostly because it has to store objects.

**Comment by salehmontazeran** [comment]
@bashtage Thank you so much, pretty good explanation.
