### ISSUE TITLE
ENH: Provide the cnpy API with numpy

### ISSUE THREAD

**Issue by picca** [numpy/numpy#21268]
Hello, It would be great if numpy could provide a C API [1]  in order to open/save the .npy and .npz files.
This way it would have the garanty that this API is following closely the .npy and .npz implementations.

My use case is a C program which need to read .npy files without all the Python.h imports.

thanks for considering

Frederic

[1] https://github.com/rogersce/cnpy/

**Comment by seberg** [comment]
I'll close this for now, since I think we lean towards not including such a project into NumPy and there seems not much reason to absorb the project into NumPy proper.
I suspect we could mention projects like this somewhere in the docs (although not sure where).
One thing (if the maintainers of the project are interested in it), we could discuss is moving such a project to the numpy github organization.
