### ISSUE TITLE
BUG: Indexing with single-value pytorch tensors can remove dimension

### ISSUE THREAD

**Issue by felixdivo** [numpy/numpy#21279]
### Describe the issue:

In the interplay with *pytorch*, some indexing behaves very unexpected. I'd expect both pieces of indexing code to produce the exact same output. If this should be moved to https://github.com/pytorch/pytorch, please just tell me.

### Reproduce the code example:

```python
import numpy
import torch

assert numpy.array ([0]).shape == torch.tensor([0]).shape, "this is expected"

assert numpy.array([[1,2],[3,4]])[numpy.array ([0]), :].shape == (1, 2), "this is expected"
assert numpy.array([[1,2],[3,4]])[torch.tensor([0]), :].shape == (2,), "this is surprising"
```

### Error message:

```shell
No traceback or real error message
```

### NumPy/Python version information:

`1.21.2 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]`

(And `torch.__version__` is `1.10.1`.)

**Comment by felixdivo** [comment]
It also occurs on these versions (currently the most recent ones):
- Numpy: `1.22.3 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]`
- Pytorch: `1.11.0`

**Comment by seberg** [comment]
Thanks for the report.  This is the same issue as gh-17348 (well, a different side of the same one).  Which is the torch issue at: https://github.com/pytorch/pytorch/issues/45125
Your issue adds to that torch issue, that torch also does the wrong thing for non 0-D integer arrays/tensors, rather than just be more lenient for booleans.  (Python bools do implement `__index__`, but they are easy enough to special case...)

Torch has to make their `__index__` implementation more strict (just like NumPy did many years ago).  There is general agreement on those stricter semantics as far as I am aware.  So this is a torch issue, unless they float it to us with a good argument.
I suppose work-arounds could be possible, though, if necessary.

**Comment by felixdivo** [comment]
Okay, thank you @seberg for this insight. So I'll comment on this aspect over there 🙂.
