### ISSUE TITLE
BUG: abs(np.int8(-128)) should arguably give an OverflowWarning

### ISSUE THREAD

**Issue by hujie369** [numpy/numpy#21289]
### Describe the issue:

The range of np.int8 is -128 to 127. 
The ideal range of np.abs(np.int8) is -127 to 128. 
But apparently 128 overflow. 
So np.abs(-128, dtype=int8) = -128, while the rest of the cases are all correct. 
This error is hard to detect and is also found in np.int16.

### Reproduce the code example:

```python
import numpy as np
a = np.array([-128, -127], dtype=np.int8)
print(a)
# [-128 -127]

print(np.abs(a))
# [-128, 127]
```

### NumPy/Python version information:

numpy: 1.18.5 
sys: 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0]

**Comment by HJ-WHU** [comment]
Thanks for your response!

**Comment by alonme** [comment]
Hey @charris,

This behavior is a bit confusing, what do you think about printing a warning in cases like these?
Or maybe adding a parameter to abs to do the type promotions if needed?

otherwise - is there an easy way to check if an array contains the `max`/`min` of the `dtype`

**Comment by seberg** [comment]
Yeah, this is mainly a duplicate of e.g. gh-21237 (which is very similar).  The basic thing, is that this issue is part of a long list of issues around the fact that it would be good if NumPy was able to give (maybe optional) integer overflow/rollover warnings.

However, we do give warnings for _scalar_ operations.  That may be slightly strange, but for scalar operations the check does not impose any significant performance cost.

In that sense, the following arguably *should* already give a warning:
```python
abs(np.int8(-128))
```
but does not.  I think this is a nice easy thing to fix, although would prefer it happening after gh-21188 is merged.
