### ISSUE TITLE
BUG: Getting numpy error while installing pycaret

### ISSUE THREAD

**Issue by rajatscibi** [numpy/numpy#21309]
### Describe the issue:

Im installing pycaret on a windows vm (aws). But getting this error again and again.
![python_error](https://user-images.githubusercontent.com/74652470/162144582-b17a39a6-e75f-4be5-98cd-200a2cac844c.png)

![python_error1](https://user-images.githubusercontent.com/74652470/162144588-c404cfa2-13f2-49f4-9e3e-af189b1a2a0c.png)

### Reproduce the code example:

```python
its during installation
```

### NumPy/Python version information:

3.10

**Comment by mattip** [comment]
Please use text copy-paste and not screenshots when reporting issues here.

Since [pycaret requires](https://github.com/pycaret/pycaret/blob/master/requirements.txt#L2) scipy < 1.5.4, I would strongly recommend you use python3.9 or less since there are precompiled binary wheels for that combination. If you use python3.10 you must compile from source, which is not easy.

**Comment by rajatscibi** [comment]
Thanks for the input, ill try it.

Sorry my bad, its my first time reporting a bug at numpy. For future purpose I will not use screenshot.

**Comment by rajatscibi** [comment]
A friend of mine tried with Python 3.8 and pycaret installed from him. 
The pycaret community itself said it wont work with python 3.10. 
Sharing the link to pycaret response and closing the issue. 
Thank you again!!
