### ISSUE TITLE
PERF: Improvement for linalg._multi_dot_three

### ISSUE THREAD

**Issue by Leengit** [numpy/numpy#21333]
### Describe the issue:

If we divide both costs by `a1b0 * b1c0 * c1` in
https://github.com/numpy/numpy/blob/5ffb84c3057a187b01acdeaa628137193df12098/numpy/linalg/linalg.py#L2747-L2750
then the relative costs become
```python
    # relative_cost1 = cost((AB)C)  / (a1b0 * b1c0 * c1) = (a0*a1b0*b1c0 + a0*b1c0*c1) / (a1b0 * b1c0 * c1)
    relative_cost1 = a0 / c1 + a0 / a1b0
    # relative_cost2 = cost(A(BC))  / (a1b0 * b1c0 * c1) = (a1b0*b1c0*c1 + a0*a1b0*c1)  / (a1b0 * b1c0 * c1)
    relative_cost2 = a0 / b1c0 + 1
```
... which is only 5 arithmetic operations instead of 6 arithmetic operations.  Is it faster?

### Reproduce the code example:

```python
See above.
```

### Error message:

```shell
See above.
```

### NumPy/Python version information:

This is in commit 5ffb84c3057a187b01acdeaa628137193df12098.

**Comment by mattip** [comment]
> Is it faster?

In general, division is more expensive than multiplication. I doubt the cost of this operation shows up at all in the overall cost of `_multi_dot_three`.

You can benchmark it if you put your changes on a branch off main and then run
```
python runtests.py --bench-compare main bench_core
```

(which will run all the benchmarks to compare the two branches)

More information about benchmarking can be found at https://numpy.org/devdocs/benchmarking.html

**Comment by Leengit** [comment]
I couldn't get the `runtests.py --bench-compare` to run.

However, my separate loops of 1,000,000,000 each of the old code (compute `cost1`, `cost2`, and `(cost1 > cost2)`) and the new code (compute `relative_cost1`, `relative_cost2`, and `(relative_cost1 > relative_cost2)`) gives timings of about 215  and 180 nanoseconds per iteration, respectively, on my fairly quiet computer.  That is about a 20% speed up for this small part of the overall computation.

Should I go ahead and make a pull request with the change?

**Comment by seberg** [comment]
Going to close this, I agree with Matti.  We might accept a PR, but basically, the 20% speed increase sounds like the speed increase of the *complexity calculation* itself.

However, the call to `dot` (twice!) should be at least around 10 times slower than that complexity calculation.  So the actual expected speed-up would be more around 3% for very small arrays.
That does not seem worthwhile to me (especially since this is called from functions with much more overhead).
If there is any evidence of real-world improvement, we can apply the change.
