### ISSUE TITLE
BUG: indexed numpy array is compatible with list according to mypy

### ISSUE THREAD

**Issue by dchu1991** [numpy/numpy#21334]
### Describe the issue:

Dear community,

I came across this bug-ish behavior when trying to utilize numpy array's index and pass it into a function expecting a list.
I expected mypy would catch this kind of usage and report a error for passing in a numpy array instead of list, but instead I don't get any error message.

I don't think this is an intended behavior...?
Or, it is me abusing the python type hints?

thanks,

### Reproduce the code example:

```python
import numpy as np


def foo(mylist: list[int]) -> None:
    ...


if __name__ == "__main__":
    a = [1, 2, 3]
    foo(a) # mypy happy
    foo(np.array(a)) # expected fail: ...incompatible type "ndarray[Any, Any]"; expected "List[int]"
    foo(np.array(a)[a]) # NOT COMPLAINING
```

### NumPy/Python version information:

python: 3.10.4
numpy: 1.21.5
mypy: 0.942

**Comment by BvB93** [comment]
Hi @dchu1991 , the reason why this is not behaving as expected is that the typing of numpy was very much an ongoing progress, and as such `ndarray.__getitem__` was still lacking annotations back in 1.21. This was changed in the 1.22 release though and your code snippet will now successfully produce a mypy error.

**Comment by dchu1991** [comment]
Hi @BvB93, after reading your answer I went ahead and have mypy check it on numpy 1.22.3, however the nehavior is still the same for me.  Could you perhaps point me to where the annotations are implemented?

**Comment by BvB93** [comment]
Ah hang on, I see what's going on here. The first overload is intended for catching normal indexing with scalars, which must return `Any` for now as the output type is strongly dependent on the array dimensionality (and we lack shape typing for now, so that's a no-go). 

The problem is that integer lists (and subtypes of `_ArrayLikeInt_co ` in general) really shouldn't be in this overload as fancy indexing always produces an array. That, and `SupportsIndex` should already adequate for catching all indexing operations with scalar types.

https://github.com/numpy/numpy/blob/ae13307732b430daa56c6a85ab56006611a5b6ba/numpy/__init__.pyi#L1548-L1566
