### ISSUE TITLE
invalid values encountered in double_scalars using numpy

### ISSUE THREAD

**Issue by Petros626** [numpy/numpy#21341]
Hello guys,

I want to use a python script from a repo (https://github.com/beltransen/lidar_bev/blob/master/scripts/max_points_map.py), but I always get the warning that the variable x contains invalid values. I have already tried with functions of special libraries and a self IF statement before executing this line. 

I tried changing line 41` if y_min !=0 else 0` to ` else np.pi/2` to see which condition seems to always be true. Somehow the else case is always selected, but I don't want to change it, because the code was written by other people. I would like to know how to create a workaround so that line 41 doesn't give a warning anymore.

Here's a snippet of the code:
![Unbenannt](https://user-images.githubusercontent.com/62354721/163338980-8b2dcf1d-1c72-4a1e-8671-285e735c689c.PNG)

Thank you for an suggestion

**Comment by seberg** [comment]
I don't think anyone can help you in this state, and it seems unlikely to be a NumPy issue to begin with.  So please isolate the issue more (e.g. check exactly where the issue comes from, what the inputs e.g. to the numpy function/comparisons are exactly (if possible) or reduced to smaller array if necessary.  Then create a **copy pastable** chunk of code to reproduce it.

Most likely, you will realize what is going on at that point, but if not feel free to post and maybe someone will help.  At this time, the only tip I can give is to use `import warnings; warnings.simplefilter("error")` to turn the warning into an error, which will give you a clear traceback (and a way to break the debugger for example).

**Comment by Petros626** [comment]
Hey Sebastian,

the fault was that:
` if y_min !=0 else 0` must be` if x_max !=0 else 0`, like the lines before. Always the denominator must be checked.
