### ISSUE TITLE
Parallel build / test options have very little effect

### ISSUE THREAD

**Issue by Apteryks** [numpy/numpy#21359]
### Describe the issue:

Even when exporting the environment variable `NPY_NUM_BUILD_JOBS` to N (e.g., 24), the build of the C sources (Cythonization) occur on a single core.

Even when invoking the test suite via `./runtests.py -j24`, the test suite still runs on a single core.

This is with the latest 1.22.3 release.  Am I doing something wrong?

### Reproduce the code example:

```python
See description.
```

### NumPy/Python version information:

Python 3.9.9
Numpy 1.22.3

**Comment by Apteryks** [comment]
Actually, I've just seen multiple `gcc` processes while building numpy, but only for a very brief period.  Perhaps the build is inherently sequential and can't be parallelized much for some reason?

**Comment by Apteryks** [comment]
The same happen with the test suite.  It very rarely make use of multiple cores, for a very brief period of time.

**Comment by seberg** [comment]
The test suite doesn't run in parallel, unless you use a pytest plugin like [pytest-xdist](https://pypi.org/project/pytest-xdist/) explicitly (with runtests that means adding `-- -n auto`).  As for the parallel build, it is probably fairly limited as to what can be parallelized.  I am not sure how much can be improved, eventually moving to meson may improve it a bit.  I do feel a few cores should help, but I am not surrpsised if it saturates far before 24 cores.

**Comment by Apteryks** [comment]
I have `pytest-xdist` installed and I run the test suite via the `runtests.py` launcher, which supports `-j` with the number of processes/workers to use.

**Comment by eli-schwartz** [comment]
setuptools is extremely difficult to parallelize due to (ad-hoc) design, and numpy.distutils can't do much there.

Improving parallelization is explicitly one of the main benefits that @rgommers described for porting SciPy to meson: https://labs.quansight.org/blog/2021/07/moving-scipy-to-meson/

Meson is designed from day 1 to be enough of a general-purpose build system to be extremely parallelizable, in fact everything that isn't explicitly marked as a build ordering dependency is fully decoupled. ;) So the planned move to Meson will solve this ticket, saturation of cores obviously notwithstanding.

**Comment by Apteryks** [comment]
Good to know improvements are on the way, thanks for the answer/information!

**Comment by seberg** [comment]
You still need to pass `-- -n auto` to use `pytest-xdist`.  It needs to be enabled manually, the `-j` is _not_ passed to pytest.

Going to close the issue, since I doubt there is any TODO for distutils.  I guess `runtests` could try to forward things to `xdist` but that would require checking that xdist is installed first I think?  So happy to reopen, or PRs that improve it in any case, of course.

**Comment by Apteryks** [comment]
> It needs to be enabled manually, the `-j` is _not_ passed to pytest.

Oh, that's surprising!  Especially since the behavior I expected exists in scipy, which seemed like it shared the same build infrastructure: https://github.com/scipy/scipy/blob/main/runtests.py#L119.
