### ISSUE TITLE
ENH: Add ndarray.mode method and numpy.mode function

### ISSUE THREAD

**Issue by MechanicPig** [numpy/numpy#21363]
### `ndarray.mode` method to get mode for any axis:

Numpy has `ndarray.mean` method and `ndarray.median` method, but lacks `ndarray.mode` method, which is very **counterintuitive**.

At present, I know three alternative ways, but they are not satisfactory:
1. Using `collections.Counter` to obtain the mode is fast enough, but the vectorization operation cannot be performed.
2.  Using `scipy.stats.mode` function, but very slow.
3.  Using `numpy.unique` function and parameter `return_counts`, but it is slightly slower than `Counter` maybe because it needs sorting, and using parameter `axis` for multi-dimensional array can not get the result I want.

I want the parameters to be consistent with the `ndarray.mean` method. Its behavior may be as follows:
```
>>> a = np.eye(3, 4)
>>> a.mode()
0.
>>> a.mode(axis=1)
array([0., 0., 0.])
>>> a.mode(axis=0)
array([0., 0., 0., 0.])
```

**Comment by bashtage** [comment]
I think the best solution would be to improve the performance of `scipy.stats.mode`.

Mode is too specialized for NumPy, and API expansion is generally frowned upon.  I also think it isn't easy to define an uncontroversial array mode that operates along columns since the mode can be multivalued.  The scipy stats implementation returns a particular implementation defined as min(mode(a)), which is presumably done for performance reasons and simplicity of the returned value.

FWIW, `scipy.stats.mode` implemented both 1 and 3 depending on the dtype of the array.

https://github.com/scipy/scipy/blob/0c4f42d8c32fa9a1a9ea0680f952b163c08eb756/scipy/stats/_stats_py.py#L493-L501

**Comment by rkern** [comment]
Indeed. `mode` has been relegated to `scipy.stats` intentionally and deliberately. While mean, median, and mode are often presented together during introductory descriptive statistics for small, "pen-and-paper" datasets, mode is much more complicated than the other two from a computational and API design perspective. For numpy, the latter concerns dominate.

I don't think there is any appetite among the numpy developers to add `numpy.mode()` much less `ndarray.mode()`. It was not an accidental omission.

**Comment by seberg** [comment]
I agree that `mode` already exists in SciPy and should probably be improved there, it doesn't seem common enough to warrent adding to NumPy in a prominent way (another good reason is that SciPy has e.g. the `nan_policy` now).  Thus, I am going to close the issue.  It may make sense to push it to SciPy.

SciPy's version does use `unique` internally, so improving `unique` may help SciPy.  It also is written in Python and needs to a do a lot more checks and work, so it is not surprising that it may not be fast compared to a custom solution using `Counter` if arrays are not fairly large (this can be on the order of 1000 elements fairly typically).

**Comment by adityaraute** [comment]
But why should numpy users have to rely on Scipy as a dependency to cover such a ubiquitous function.
I feel it is really necessary for numpy to add a `mode` function, even if it exists in Scipy
