### ISSUE TITLE
BUG: can't register cast functions between datetime64 and user dtype

### ISSUE THREAD

**Issue by alexhsamuel** [numpy/numpy#21365]
### Describe the issue:

I'd like to register (unsafe) cast functions between `datetime64` and a custom dtype.  Per [the docs](https://numpy.org/devdocs/user/c-info.beyond-basics.html#registering-a-casting-function), I use `PyArray_RegisterCastFunc` to register these.  Essentially this logic:
```c
// ...
PyArray_RegisterDataType(descr);
// ...
npy_datetime = PyArray_DescrFromType(NPY_DATETIME);
PyArray_RegisterCastFunc(npy_datetime, descr->type_num, cast_from_datetime);
PyArray_RegisterCastFunc(descr, NPY_DATETIME, cast_to_datetime);
```
These return no error state, and in fact `PyArray_GetCastFunc` returns the functions I set.

My actual code is [here](https://github.com/alexhsamuel/ora/blob/master/python/ora/ext/np_time.hh#L241-L249) and happy to provide additional details about what I'm trying to do.

Until 1.20, this worked as expected (`Time` is my custom dtype):
```py
>>> np.can_cast(np.dtype("datetime64[ns]"), Time, casting="unsafe")
True
>>> np.can_cast(Time, np.dtype("datetime64[ns]"), casting="unsafe")
True
>>> a
array([ora.Time(2022, 4, 20, 4, 3, 8.82545807, UTC)], dtype=Time)
>>> a.astype("datetime64[ns]")
array(['2022-04-20T04:03:08.825458080'], dtype='datetime64[ns]')
```

Starting in 1.21, 
```py
>>> np.can_cast(np.dtype("datetime64[ns]"), Time, casting="unsafe")
False
>>> np.can_cast(Time, np.dtype("datetime64[ns]"), casting="unsafe")
False
>>> a.astype("datetime64[ns]")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast array data from dtype(Time) to dtype('<M8[ns]') according to the rule 'unsafe'
```

I assume this has something to do with NEP 42, though I don't understand it well enough to understand whether there is now a different mechanism available for adding conversions to/from datetime64.

### Reproduce the code example:

```python
import numpy
import ora

numpy.array([ora.now()]).astype("datetime64[ns]")
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast array data from dtype(Time) to dtype('<M8[ns]') according to the rule 'unsafe'
```

### NumPy/Python version information:

```
>>> print(numpy.__version__, sys.version)
1.21.0 3.8.13 (default, Apr 19 2022, 21:32:23)
[GCC 11.2.0]
```
Also tested in current main 55aacc70c.

**Comment by seberg** [comment]
> I assume this has something to do with NEP 42, though I don't understand it well enough to understand whether there is now a different mechanism available for adding conversions to/from datetime64.

That is becuase the new API is not yet available, but it *is* available experimentally in the main branch.  See https://github.com/seberg/unitdtype

As to the change, it is related to NEP 42, but more indirectly than directly.  I simply didn't realize this was even plausible and rejected the use-case [here](https://github.com/numpy/numpy/blob/bdb19d23131c10d9640e86a70dc5b5a8156058b5/numpy/core/src/multiarray/convert_datatype.c#L110-L112).

Seems like that was silly, and should be removed.  But the whole way this works for datetimes is pretty terrible and it would be greta to have the replacement available sooner rather than later if this is used...

**Comment by alexhsamuel** [comment]
I see!  So just tried commenting out these three lines in `convert_datatype.c` and conversions to/from datetime64 work again.  Yeah, could we remove them?

I'm mildly interested in parameterized dtypes for my lib as well, but I'm not sure it would be a win.  I worked around it long ago using C++ templates and registering each template instance as a separate dtype.  It was a fair amount of work, but it's done already and has a few advantages.  The scalar type behaves like a normal Python type, without any extra parameterization.  (Ideally it would be usable without NumPy at all, though I don't think this is possible because a custom dtype's scalar type needs to inherit from a NumPy base.  Or at least that used to be the case.)  Also using a C++ template allows for compile-time optimizations that are not available for a parametrized type.

But in any case, I am happy to hook in to whatever scheme you provide for registering casts to/from datetime64.  In fact, I'd prefer to be able to register casts for some datetime64 units and not others.

**Comment by alexhsamuel** [comment]
Thanks for the response, by the way.

**Comment by seberg** [comment]
Yeah, opened a PR to remove them.  Not sure there will be another 1.21.x release, though, unless this is very important.  Currently, I limited the registration of casts to the DType functions (in the experimental API).  That is just an intentional limitation though, not a technical one.

I guess the interesting part is whether the scalar type is parametrized or not.  And if the scalar one is, how to best make a parametrized DType work (this is actually possible, but you need a family of DTypes that are not really used right now, which could probably be relaxed).

> In fact, I'd prefer to be able to register casts for some datetime64 units and not others.

You will be able to (when the stuff is made public in a way you can use it easily), but not as a registration for some units.  The way casts now work, is that there is a `resolve_descriptors` function additionally.  So when you cast from `MyTime -> Datetime`, that function can say that it should use, say, `ns` by default but always reject `us` (or say make that an "unsafe" cast, rather than a "safe" one).
