### ISSUE TITLE
ENH: A shell script to automatically setup the numpy environment on a Unix system

### ISSUE THREAD

**Issue by bhavukkalra** [numpy/numpy#21508]
### Proposed new feature or change:

Note - Developer Only change
I have been working with Gitpod maintenance for a while now and It often requires me to test the builds with different dependencies types and configurations.
For safe measure I create myself a new Unix host and do my testing there.

It always requires me to do the setup steps documented here over and over again.
[Link for the Setup Steps](https://docs.google.com/document/d/17KTUal0EfhhRsZdg5snPyTPu5ifC4b3aoQDk24fvFqA/edit)

It would be great if the setup process could be automated with all the software dependencies that will be required.

I wanted suggestions from the community if this is a good idea  (To have an automated shell script) to have this? 

**Secondly**

To have a shell script for numpy `redevelopment only` , having the steps of
1) `git clean -xdf`
2) `python setup.py build_ext --inplace`
3) `pip install -e .`
[OPTIONAL BUILDING DOCS]
4) `cd doc`
5) `make html`

It would be great to have the community opinion on this, If this is worth pursuing and having.

**Comment by rossbar** [comment]
I'm -1 on adding platform-specific scripts to the repo. In principle, this is the exact problem the gitpod instance is intended to solve - give potential contributors a development environment out-of-the-box without requiring any system/environment setup. Personally I'd prefer to focus on improving the gitpod testing/validation, as discussed elsewhere.

Additionally, the information about setting up and building is already all contained in the [developer guide](https://numpy.org/devdocs/dev/index.html#contributing-to-numpy) - adding *more* info/scripts would inevitably be duplicating info that already exists. Rather than add *more* information, I think the best approach here would actually be to review and work on the developer guide to make the information more digestible and remove redundant or extraneous info. This is obviously a much bigger task than what is proposed here, but in the long run I think this would have a bigger positive impact for new/potential contributors than adding more info!

**Comment by bhavukkalra** [comment]
This makes sense Ross, Seeing from the long term perspective. 
Closing!
