### ISSUE TITLE
BUG: Make building docs with missing python3 easier

### ISSUE THREAD

**Issue by bsipocz** [numpy/numpy#21563]
### Describe the issue:

I've spent quite a few minutes trying to decrypt why I cannot build the docs locally, when local testing, etc all work fine, dependencies are installed, etc. Naturally, I should have started with grepping for the error message to discover that I should do `make PYTHON=python html` instead.

Ideally, it would be nice if the machinery wouldn't assume python3 as the name of the executable (are there any other python in these days?), or at minimum would give a useful error message (similar to the one given with mismatching version number).

### Reproduce the code example:

```shell
make  html
```

When no `python3` executable is available, or it's outside of the current virtualenv/pyenv

### Error message:

```shell
numpy not found, cannot build documentation without successful "import numpy"
make: *** [version-check] Error 1
```

**Comment by charris** [comment]
I actually don't follow the directions, as the Makefile doesn't set up the path correctly (I have many numpy versions installed) and easy_install doesn't work with Python 3.10 anyway. What I do is install the numpy I want to document using `--user`, check that it is the default, and edit the Makefile to remove the `dist-build` in `real-dist: dist-build html-build`. I've always had to do a local install because of the path problem, getting rid of `dist-build` makes it work with Python 3.10. I'd try to fix all that, but the long range plan is build the release documentation using the CI.

**Comment by bsipocz** [comment]
`pip install -e .` and then `make PYTHON=python html` in `doc` worked for me, though in this env I manually nuked all previous numpy installs from `site-packages`. 

But having this direction about PYTHON would indeed saved me going into irrelevant directions and double checking of dependencies, reverse engineer from CI setups etc. Obviously, I could have checked the narrative docs, but that just simply not the first place I try when I look for solutions.
