### ISSUE TITLE
BUG: Creating array with `dtype=object` changes the dtype of a subarray

### ISSUE THREAD

**Issue by zldrobit** [numpy/numpy#21598]
### Describe the issue:

When creating a numpy array of only one subarray with `dtype=object`, the subarray's dtype is overwritten with `object`. Is this the expected behavior?  I observed that in arrays with more than one subarray, it does not change the dtypes of subarrays.

### Reproduce the code example:

```python
import numpy as np
a = np.array([np.array([0, 1], dtype=int)], dtype=object)
print(a)
a[0].dtype
```

### Error message:

```shell
[[0 1]]
dtype('O')
```

### NumPy/Python version information:

1.21.6 3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0]

Python 3.7.13
numpy==1.21.6

**Comment by seberg** [comment]
Going to close.  This is a question, because it is what we do with any embedded subarray passed into `np.array`, it gets converted to the requested dtype (which is object).

If you want to have an array within an array, you have to jump through some hoops for that reason, one way that works is:
```
a = np.empty(1, dtype=object)
a[...] = [np.array([0, 1])]
```
since in that case NumPy knows when to "stop".  I.e. it knows that the result array should be one dimensional (and not encompass the full 2 dimensional that you get when including the nested array).
