### ISSUE TITLE
BUG?:  `loadtxt` is now stricter with integers

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#21652]
Scikit-image noticed this (not sure if it is in a particularly important part): https://github.com/scikit-image/scikit-image/issues/6397  CC @hmaarrfk

There is a point that `np.savetxt` doesn't pair well (because it defaults to storing floats with `%e18`, which is a bit weird).  But we also had a good reason to try it:  The old parser used `int(float(value))` which is pretty terrible, as it for example loses bits for large numbers.

We could probably try to make it a deprecation instead, at least if it comes up more.  Working around it is pretty easy for end-users IMO (in most cases `converters=float` works on new NumPy versions non older you would have to use casting probably `np.loadtxt(...).astype(int)`).

**Comment by seberg** [comment]
To be clear, I am ambivalent:  I removed it with the move, because nobody ever voiced a large concern about trying to remove it.  And there are other things like `_` support which now require converter use as well.

**Comment by seberg** [comment]
I am happy to at least add path that tries parsing with float and gives a `DeprecationWarning` when that works (but allows it for now).

What I am unsure about is, what your main worry is.  Is it the *transition* being painful, the fact that `savetxt` probably has bad defaults and doesn't pair well, or a feeling that `loadtxt` should be lenient about weird inputs (in which case how lenient, should we parse `0.5` to int)?

**Comment by hmaarrfk** [comment]
I personally, i'm not really considering code that saves 'float32' and tries to load it as 'int', that seems like a misunderstanding of general computer science and scientific computing.

What I believe is a numpy bug is that the following looks like sensible code, but that 1.23 is suggesting that it will no longer work

```python
import numpy as np
a = np.arange(-128, 128, dtype='int8')
np.savetxt("a.txt", a)
a_loaded = np.loadtxt("a.txt", dtype='int8')
from numpy.testing import assert_array_equal
assert_array_equal(a, a_loaded)
```

While "a.txt" here looks like it is trivial, I think that many users might be using it save important parameters as "txt files" for ease of "reading".

I'm not sure that this code should be allowed to break (ever?). 
In my opinion, definitely not without warning.
In my opinion, definitely with a longer deprecation cycle.

saved files are tricky. Users expect them to be portable, and to stay for much longer than their software. They want to share them, save them for archival. And reload them. Forward compatibility is often a must. Backward compatibility, is definitely a very nice to have.

I'm not sure what the cost is to numpy in maintaining the `savetxt` and `loadtxt` functions as they are today.

**Comment by rkern** [comment]
> There currently isn't a good way to "just save my stuff".

`np.save()` is the "just save my stuff" option. Text formats are "just corrupt my stuff, please".

**Comment by hmaarrfk** [comment]
> Text formats are "just corrupt my stuff, please".

maybe so, but let me give a few advantages:
1. Text files get versioned, and reviewed more appropriately in git.
2. Text files are more readily opened by spreadsheet software.
3. Text files are often easier to use as teaching material since users can read the numbers without writing code.

In either case, please just take this as one user story of people that are running release candidates and reporting unexpected integration challenges. 

Our logs are showing errors at import time due to the fact that we were "preloading" some coefficients that we saved.

**Comment by rkern** [comment]
Oh, for sure, text formats have their own advantages. But those are well beyond "just save my stuff" (and _conflict_ with "just save my stuff" because of the failure to robustly roundtrip). And without some kind of documented standard, no format should be considered safe for long-term storage. Both `savetxt()` and `loadtxt()` were designed as convenient tools as ways to write and read a variety of tabular text formats that could be configured by the user as appropriate to achieve their specific goals. They were not particularly designed to _define_ a round-trippable format (contrastingly, `np.save()/np.load()` on the other hand very much did).

The root ill is that we decided to provide a single default `fmt=` argument in `savetxt()`, regardless of `dtype`. That sort of worked given the semantics of `loadtxt()` at the time, for small-valued integers. But if you consider "code that saves 'float32' and tries to load it as 'int'" to be a "misunderstanding of general computer science and scientific computing", then I'd suggest that saving 'int' data in a 'float' format to be just as much so. But because we left that as the default, we trapped people. We should have left the default as something that would autodetect separate defaults for integer and floating data. We can do that now if we want to restore concurrent `savetxt()/loadtxt()` pairing going forward.

**Comment by seberg** [comment]
> Our logs are showing errors at import time due to the fact that we were "preloading" some coefficients that we saved.

I had misread the skimage issue and though this only kicks in for a fairly specific feature (because I thought the data was loaded more lazily).
This is indeed loaded on `from skimage import feature`, so it seems safe to assume that it is disruptive.

---

As to the rest of the discussion, I still feel this is mainly pointing at `savetxt` being strange?  
Note that "round-tripping" can be fixed on either side.  Fixing it on the loading side can (usually) be done with:
* `np.loadtxt(..., converters=float)`  (only on new NumPy)
* `np.loadtxt(...).astype(np.uint8)`  (on all NumPy versions)

And I actually do believe the error:
```
E   ValueError: could not convert string '8.000000000000000000e+00' to int8 at row 0, column 1.
```
is a pretty good pointer into how to fix it?  Now we had the idea of continuing that message with:
> For more information on text loading see <url>.

And that URL could note some of the transition "issues" as well.  I still prefer such a documentation addition to more lenient parsing.  I hope that end-users won't hate us, so long they can figure out a workable solution in less than 5 minutes.

---

The other point is improving `savetxt`, maybe even right now.  There is no reason why it shouldn't save integers as `%r`?  It also comes with backcompat concerns, but they seem even more esoteric.
