### ISSUE TITLE
BUG: NumPy auto conversion to avoid overflow sometimes didn't work

### ISSUE THREAD

**Issue by yasirroni** [numpy/numpy#21671]
### Describe the issue:

NumPy auto conversion from `int32` to avoid overflow sometimes didn't work.

It should always convert to `int64` or always not convert.

### Reproduce the code example:

```python
import numpy as np

a = np.array([100, 125])
print(a, type(a), a.dtype) # int32
a_ = a * 1_000_000
print(a_, type(a_), a_.dtype) # int32
a_ = a * 30_000_000
print(a_, type(a_), a_.dtype) # int32 overflow
a_ = a * 1_000_000_000
print(a_, type(a_), a_.dtype) # int32 overflow
a_ = a * 10_000_000_000
print(a_, type(a_), a_.dtype) # int64
a_ = a * 10_000_000_000_000_000_000
print(a_, type(a_), a_.dtype) # float64
```

### Error message:

```shell
[100 125] <class 'numpy.ndarray'> int32
[100000000 125000000] <class 'numpy.ndarray'> int32
[-1294967296  -544967296] <class 'numpy.ndarray'> int32
[1215752192  445948416] <class 'numpy.ndarray'> int32
[1000000000000 1250000000000] <class 'numpy.ndarray'> int64
[1.00e+21 1.25e+21] <class 'numpy.ndarray'> float64
```

### NumPy/Python version information:

```
import sys, numpy, platform; print(numpy.__version__, sys.version, platform.platform())

# 1.20.3 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] Windows-10-10.0.19041-SP0
```

**Comment by yasirroni** [comment]
Bug also occurs in unsigned

```python
a = np.array([100, 125], dtype=np.dtype('uint'))
print(a, type(a), a.dtype) # int32
a_ = a * 1_000_000
print(a_, type(a_), a_.dtype) # uint32
a_ = a * 30_000_000
print(a_, type(a_), a_.dtype) # uint32
a_ = a * 1_000_000_000
print(a_, type(a_), a_.dtype) # uint32 overflow
a_ = a * 10_000_000_000
print(a_, type(a_), a_.dtype) # int64
a_ = a * 10_000_000_000_000_000_000
print(a_, type(a_), a_.dtype) # uint64 overflow (because float is signed)
```

**Comment by yasirroni** [comment]
Bug did not occur on [google colab](https://colab.research.google.com/)

```
import sys, numpy, platform; print(numpy.__version__, sys.version, platform.platform())
```

**Comment by seberg** [comment]
You are simply running into gh-19146 and gh-20905.

There is strange behavior here, but there is no bug that NumPy's auto-conversion doesn't work.  It is rather the opposite:  You are sometimes getting a result that *looks* a like an auto-conversion exists, but really no auto-conversion exists!

NumPy integers *do not auto-convert*, if you have a fixed precision integer type, operations on it will generally behave just like in C.  There are some cases that look like they do, because when confronted with Python integers, you currently get:
```
long -> int64 -> uint16 -> Python object
```
depending on the input value.  And on windows `long` is `int32` (on linux it usually is `int64`, thus the difference).  So the *input* is interpreted differently by NumPy, but NumPy does not really try to be smart about preventing overflows.
Everything else follows that oddity here.  Plus the additional oddity that mixing `int64` and `uint64` gives `float64` unfortunately.

---

Going to close this, this *is* confusing, but all of this is known confusions (with open issues).  Feel free to continue the discussion though.
