### ISSUE TITLE
DOC: incorrect source link for vectorize

### ISSUE THREAD

**Issue by jsdodge** [numpy/numpy#21708]
### Issue with current documentation:

The API reference documentation for [`vectorize`](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html) points to the top-level [`__init__.py`](https://github.com/numpy/numpy/blob/v1.22.4/numpy/__init__.py) file, which does not include any information about `vectorize`. The source code is locate in the [`numpy/lib/function_base.py`](https://github.com/numpy/numpy/blob/main/numpy/lib/function_base.py) module.

### Idea or request for content:

Update the link to point to the source code.

**Comment by seberg** [comment]
Thanks.  The problem is that we override the `__module__` of vectorize.  It is not defined in the main `__init__`, but we want it to look like that.
However, it seems that for clases there is no better way to find the "source", so sphinx uses that (and fails).

I suspect, sphinx could double check and remove the `[source]` link, but I doubt we can do anything about it.  So I am going to close.  However, @rossbar can you confirm that that we have no direct way to "hide" the source link here?

**Comment by bhavukkalra** [comment]
Researched upon this a bit and the assessment by @seberg is correct. There isn't really something we can do from our end to fix this. 
Link for a tutorial on how `source` is rendered - [Sphinx Tutorial](https://www.youtube.com/watch?v=5s3JvVqwESA)
