### ISSUE TITLE
DEP: Deprecate `find_common_type` which is broken e.g. for datetimes

### ISSUE THREAD

**Issue by rabernat** [numpy/numpy#21703]
### Describe the issue:

When I call `np.find_common_type` with multiple identical `datetime64` types, I would expect to get the same type back, since all the inputs are identical. Instead, I always get `dtype('O')`.

### Reproduce the code example:

```python
import numpy as np
dt = np.dtype('datetime64[ns]')
dt1 = np.find_common_type([dt], []) 
# this works; both dtype('<M8')
assert dt1 == dt
dt2 = np.find_common_type([dt, dt], [])
# this fails; dt2 is dtype('O')
assert dt2 == dt
```

### NumPy/Python version information:

1.21.2 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:37) 
[Clang 11.1.0 ]

**Comment by seberg** [comment]
Hmmmpff... Thanks for the report!  I suspect that function has even more problems (It also seems plausible that there are duplicate issues open, but I did not check yet).

My preference would be to just deprecate it entirely.

If at all possible, I *strongly* encourage to always use `np.promote_types` or `np.result_type` (which also supports array inputs and some of that weirder "scalar" logic).

(And if not possible, please tell me, because that deprecation may just happen otherwise :)).

**Comment by rabernat** [comment]
Thanks! `np.promote_types` does what I hoped.

Deprecate away! 🚀

**Comment by mattip** [comment]
This might be a nice task for a sprint

**Comment by seberg** [comment]
Yeah, there is a small rabbit hole that we use it for `np.r_` (and maybe one other place).  I think that can be replaced there without breaking too much.  So it should be doable, but needs a bit of care.

**Comment by isVoid** [comment]
This API states that scalars cannot upcast the dtype of an array. 
```
>>> np.find_common_type([np.int8], [np.int16])
dtype('int8')
```
But in fact:
```
>>> (np.array([1, 2, 3], dtype="int8") + np.int16(256)).dtype
dtype('int16')
```
I think it's yet another reason to deprecate.
