### ISSUE TITLE
DOC: Mention that save requires all directories in path to exist

### ISSUE THREAD

**Issue by aiqc** [numpy/numpy#21774]
### Issue with current documentation:

It would be good to mention that `.save()` will not create any missing directories in the path

https://numpy.org/doc/stable/reference/generated/numpy.save.html

It's kind of weird because one specifies a file name that does not exist yet, so it feels like you should be able to specify any path

**Comment by seberg** [comment]
Thanks.  My gut feeling would be that this is not necessary.  The reason is that I can't really remember ever having a "save" dialogue/function that created directories automatically.
I can see that it can be confusing coming in with that expectation, but I don't quite see that the majority of users should have the expectation?

`os.makedirs` is the right tool for the job, if necessary together with `os.path.split`.

**Comment by seberg** [comment]
Closing, I don't think it makes sense, the behavior is mentioned and the error should be clear enough.
