### ISSUE TITLE
BUG: Data is not changed when writing to array indexed with bool array _and_ slicing

### ISSUE THREAD

**Issue by mpsdskd** [numpy/numpy#21775]
### Describe the issue:

When trying to change data of a part of a ndarray, the array data is not changed when using slicing and a bool array in that order.
In the example provided below, only the following commands do not change _array_ as expected
```
mask=numpy.ones(array.shape,dtype=numpy.bool8)
array[mask][::1]+=1
```
while all other indexing combinations change _array_.

### Reproduce the code example:

```python
import numpy

array = numpy.zeros(2)
print(array, "\n\n")
array += 1
print(array, "\n\n")
array[::1]+=1
print(array, "\n\n")
mask=numpy.ones(array.shape,dtype=numpy.bool8)
array[mask][::1]+=1
print(array, "\n\n")
print(array[mask][::1]+100, "\n\n")
array[mask]+=1
print(array, "\n\n")
array[::1][::1]+=1
print(array, "\n\n")
array[::1][mask]+=1
print(array, "\n\n")
array[::2][mask[::2]]+=1
print(array, "\n\n")
```

### Error message:

```shell
[0. 0.] 


[1. 1.] 


[2. 2.] 


[2. 2.] 


[102. 102.] 


[3. 3.] 


[4. 4.] 


[5. 5.] 


[6. 5.]
```

### NumPy/Python version information:

1.21.5 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]

**Comment by rkern** [comment]
Boolean masking always makes a copy. When you have `array[mask][::1]+=1`, Python's syntax breaks that down into something like the following:

```python
tmp_copy = array[mask]  # copy
tmp_copy[::1] += 1
```

Or more expanded:

```python
slc = slice(None, None, 1)
tmp_copy = array[mask]  # copy
tmp_view = tmp_copy[slc]  # view of the copy
tmp_copy.__setitem__(slc, tmp_view.__iadd__(1))
```

Note that there is never an assignment back to `array[mask]` to modify the original `array`. When you have multiple subscripts `[][]` on the left-hand side of an assignment, only the rightmost one actually participates in the assignment. Any others are just the expression that forms the object that participates in the assignment.

In the other cases with a double subscript `[][]`, the leftmost subscript is a slice, which makes a view object. Modifications to the _view_ happen to modify the original `array` because they share memory. But `array[mask]` is a copy, not a view, so modifications to it don't propagate back to `array`.

There isn't a whole lot we can do about this. Python syntax does not tell our objects when you are doing a double subscript on the left-hand side of an assignment.

**Comment by seberg** [comment]
Right, on first sight, I thought we could potentially warn in this *very specific* case.  Similar to `arr_a + arr_b + arr_c` reusing some temporary arrays as an optimization.

Giving a warning here would require the same "magic", though  (that magic is inspecting the C stack).  And the "magic" we currently have only works on some platforms.  That is fine for an optimization, but not reliable enough for a warning.

So possible?  Maybe... but probably too much hassle for little gain.

**Comment by seberg** [comment]
Closing, since there should be nothing to do here.
