### ISSUE TITLE
ENH: Automatically convert the domain of polynomials after fit

### ISSUE THREAD

**Issue by axil** [numpy/numpy#21782]
### Proposed new feature or change:

In order to enhance numerical stability of the fit, polynomials are normalized before fitting.

After the fit is done, they are not denormalized resulting in somewhat unexpected

``` python
import numpy as np
x = np.arange(10)
y = 5 * x + 1 + np.random.randn(10)
np.polynomial.Polynomial.fit(x, y, 1)
```
![image](https://user-images.githubusercontent.com/170910/174139161-59b11553-5717-436a-96e9-baf8d3e3f3f6.png)

Opening the parentheses when displaying the result can lead to unexpected results of `f.coeffs` being different from `str(f)`:

``` python
>>> f.coef
array([23.94747689, 21.55327469])
```

As I was advised in slack, the proper way of presenting the result is running `f.convert()`:

``` python
>>> f.convert()
𝑥 ↦ 0.26377794+5.08309969𝑥
>>> f.convert().coef
array([0.26377794, 5.08309969])
```

I would suggest running `f.convert()` automatically after the fit to make the results look less awkward for the unwary:

``` python
import numpy as np
x = np.arange(10)
y = 5 * x + 1 + np.random.randn(10)
np.polynomial.Polynomial.fit(x, y, 1)
```
![image](https://user-images.githubusercontent.com/170910/174140449-b61b9ccb-ac86-438f-9277-f1aa6ac4d06c.png)

Is there any downside in it? Maybe there should be a dedicated flag to `fit` function to keep the original 'unconverted' version if it is of any use?

**Comment by jsdodge** [comment]
I'd like to reopen this issue, since it should be possible to display the coefficients for the original domain while internally retaining the coefficients in the scaled domain. It's unnecessarily confusing to use the scaled domain as the default representation for the user.

**Comment by charris** [comment]
> It's unnecessarily confusing to use the scaled domain as the default representation for the user.

But not as accurate. You can lose a lot of precision doing that.

**Comment by jsdodge** [comment]
I understand that it's potentially less accurate. But that does not excuse the following behavior:

```python
In [3]: x = np.linspace(0, 100)

In [4]: y = 2 * x + 17

In [5]: p = np.polynomial.Polynomial.fit(x, y, 1)

In [6]: p
Out[6]: Polynomial([117., 100.], domain=[  0., 100.], window=[-1.,  1.], symbol='x')

In [7]: print(p)
117.0 + 100.0·x

In [8]: print(p.convert())
17.0 + 2.0·x
```

My point is that the output of `In [7]` is bad and the output of `In[8]` is good.

There's a related point here, which is that a very common use case of any polynomial fit routine is to fit a polynomial model to data, which has *inherently* limited accuracy. I get that the scaled representation is better for numerical work, but it gets in the way when you just want to know the slope and intercept of a linear fit to your data. And since it's a class anyway, why not expose the coefficients in the original representation by default, and keep the scaled representation internally to maintain accuracy in behind-the-scenes computation?

For now, it seems to me that `numpy.polynomial.polynomial.polyfit` is preferable to `Polynomial.fit` for this kind of application—although as noted in #20889 , this version of `polyfit` no longer returns the covariance matrix, which is essential information for evaluating the fit. Would it be possible to mention these tradeoffs in the [Transition Guide](https://numpy.org/doc/stable/reference/routines.polynomials.html#transition-guide)? Currently, it just says, "In the old module, fitting was done via the [polyfit](https://numpy.org/doc/stable/reference/generated/numpy.polyfit.html#numpy.polyfit) function. In the polynomial package, the [fit](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.Polynomial.fit.html#numpy.polynomial.polynomial.Polynomial.fit) class method is preferred."
