### ISSUE TITLE
BUG: AttributeError: `MachAr` object has no attribute `_str_smallest_normal`

### ISSUE THREAD

**Issue by podsvirov** [numpy/numpy#21827]
### Describe the issue:

I'm just wanted to use [h5py](https://packages.msys2.org/base/mingw-w64-python-h5py) package from [MSYS2](https://www.msys2.org/) distro.
```console
$ python3 -c "import h5py"
D:/msys32/mingw32/lib/python3.10/site-packages/numpy/core/getlimits.py:492: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\xe2\x04' for <class 'numpy.float96'> does not match any known type: falling back to type probe function
  machar = _get_machar(dtype)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:/msys32/mingw32/lib/python3.10/site-packages/h5py/__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5t.pyx", line 278, in init h5py.h5t
  File "h5py/h5t.pyx", line 273, in h5py.h5t._get_available_ftypes
  File "D:/msys32/mingw32/lib/python3.10/site-packages/numpy/core/getlimits.py", line 485, in __new__
    obj = object.__new__(cls)._init(dtype)
  File "D:/msys32/mingw32/lib/python3.10/site-packages/numpy/core/getlimits.py", line 512, in _init
    self._str_smallest_normal = machar._str_smallest_normal.strip()
AttributeError: 'MachAr' object has no attribute '_str_smallest_normal'. Did you mean: 'smallest_normal'?
```
Looks like problem with `float96` type.

### Reproduce the code example:

```python
import numpy as np
np.core.getlimits.finfo(np.float96)
```

### Error message:

```shell
D:/msys32/mingw32/lib/python3.10/site-packages/numpy/core/getlimits.py:492: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\xdc\x04' for <class 'numpy.float96'> does not match any known type: falling back to type probe function
  machar = _get_machar(dtype)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:/msys32/mingw32/lib/python3.10/site-packages/numpy/core/getlimits.py", line 485, in __new__
    obj = object.__new__(cls)._init(dtype)
  File "D:/msys32/mingw32/lib/python3.10/site-packages/numpy/core/getlimits.py", line 512, in _init
    self._str_smallest_normal = machar._str_smallest_normal.strip()
AttributeError: 'MachAr' object has no attribute '_str_smallest_normal'. Did you mean: 'smallest_normal'?
```

### NumPy/Python version information:

1.22.4 3.10.5 (main, Jun 18 2022, 01:33:07)  [GCC 12.1.0 32 bit]

**Comment by seberg** [comment]
While this should not fail (see also gh-21813) it does indicate that `long double` support is broken.  That is probably currently simply true on `msys2` (i.e. you have to live with a warning about that) even if we fix the error.

I am not sure what else to do about it... It might be nice to disable `long double` when it is clearly unsupported, but overall the issue here is that at compile it supposedly *is* supported, but then at runtime is not, so I am not sure if there is an easy solution.

Did `h5py` change recently?  I don't really remember users running into this issue this much before.

**Comment by seberg** [comment]
The PR has been backported.   I believe `longdouble` is broken on `msys2`, and now it will give a bit of a scary warning (rather than just failing) in this situation.

So the solution is somewhat fixed, and maybe we can close the issue even.  But the situation is clearly not ideal.  There probably is not an ideal solution, but maybe there is still a better one...

**Comment by m3lab-zzl** [comment]
@seberg Similar warning shows up on WSL ubuntu https://github.com/h5py/h5py/issues/2357

**Comment by seberg** [comment]
Well WSL is sometimes/often/always(?) broken with longdouble support, so dunno what to do about it.  Maybe you can open a new issue, I don't rally recall... if you get the first warning, I would suspect that your longdouble is very broken and the test suite would show more failures related to it.

**Comment by m3lab-zzl** [comment]
> Well WSL is sometimes/often/always(?) broken with longdouble support, so dunno what to do about it. Maybe you can open a new issue, I don't rally recall... if you get the first warning, I would suspect that your longdouble is very broken and the test suite would show more failures related to it.

Thank you for your information. I thought it was related to `numpy` version, but your comment pointed out a right way. No wonder why on real linux platform, I never encounter similar warning.
