### ISSUE TITLE
BUG: Type of "array" is partially unknown in Pyright

### ISSUE THREAD

**Issue by colinfang** [numpy/numpy#21821]
### Describe the issue:

At the moment, numpy & pyright do not work nicely together.

This apply to many other functions e.g. `np.linspace`

### Reproduce the code example:

```python
import numpy as np
import numpy.typing as npt

x: npt.NDArray[np.float64] = np.array([2.55, -1], dtype=np.float64)
```

### Error message:

```shell
This gives error " Type of "array" is partially unknown" from "pylance[reportUnknownMemberType]"
```

### NumPy/Python version information:

NumPy v1.22.3, Pyright v1.1.254.

**Comment by colinfang** [comment]
The same issue was reported in Pyright repo, but the author claimed it is better to fix it in NumPy

> Next, let's look at why the type of the array function is considered "partially unknown". The second parameter of this function has a declared type of DTypeLike. This is a type alias that includes the type dtype. The dtype class is generic and expects to receive a single type argument, but no type argument is provided in this case. I'm guessing that the numpy maintainers mean for it to be dtype[Any]. The correct fix is to add that missing type argument in the numpy/typing/_dtype_like.py file. I recommend filing a bug or a PR with numpy.

**Comment by BvB93** [comment]
`npt.NDArray[np.float64]` currently expands to `np.ndarray[Any, np.dtype[np.float64]]`, so my guess is it is the `Any`-based array-shape in there that causes pyright to complain. Until shape-typing is fully implemented (which I expect to take a while, xref https://github.com/numpy/numpy/issues/16544) the `Any`'s won't be going anywhere I'm afraid. 

For now I'd recommend to either disable or locally suppress the particular pyright setting, since I don't believe it's enabled by default anyway.

**Comment by colinfang** [comment]
I don't know what has changed but once I upgraded into numpy 1.23 the error went away...

I am not seeing any changes in array types in `multiarray.pyi` though

**Comment by BvB93** [comment]
Huh... To be quite frank: I've no clue why the error disappeared, but I'm glad it did.
