### ISSUE TITLE
BUG: np.average with keepdims=True broadcasts weights incorrectly

### ISSUE THREAD

**Issue by jakevdp** [numpy/numpy#21850]
Reproduction:
```python
import numpy as np

x = np.array([2, 3, 4]).reshape(3, 1)
w = np.array([4, 5, 6]).reshape(3, 1)

print(np.average(x, weights=w, axis=1, keepdims=False))
# [2. 3. 4.]


print(np.average(x, weights=w, axis=1, keepdims=True))
# [[2.         1.66666667 1.42857143]
#  [3.6        3.         2.57142857]
#  [5.6        4.66666667 4.        ]]
```
I would expect the output with `keepdims=True` to be this:
```
[[2]
 [3]
 [4]]
```

**Comment by postmalloc** [comment]
The problem seems to be here:
https://github.com/numpy/numpy/blob/cafec60a5e28af98fb8798049edd7942720d2d74/numpy/lib/function_base.py#L545

The `keepdims` property needs to be applied during normalization as well. Changing it to the following solves the problem:
`scl = wgt.sum(axis=axis, dtype=result_dtype, **keepdims_kw)`
