### ISSUE TITLE
BUG: `hstack` / `vstack` / `dstack` returns a different datatype than its inputs for input datatypes >u2, >u4, and >u8

### ISSUE THREAD

**Issue by LaurentRDC** [numpy/numpy#21914]
### Describe the issue:

The functions `numpy.hstack`, `numpy.vstack`, and `numpy.dstack` return an array with a different datatype than its inputs, when the inputs are of certain datatypes. See the example below.

This occurs for an iterable of arrays of type `np.dtype('>u2')`, `np.dtype('>u4')`, and `np.dtype('>u8')`, but curiously not for arrays of type `np.dtype('>u1')`

### Reproduce the code example:

```python
import numpy as np

arrays = [np.zeros(shape=(2,3,4), dtype=np.dtype('>u2')) for _ in range(3)]
first, *_ = arrays
print('Initial dtype: ', first.dtype) # np.dtype('>u2')

stacked = np.dstack(arrays)
print('Stacked dtype: ', stacked.dtype) # np.dtype('uint16')
```

### NumPy/Python version information:

This bug occurs with at least two versions:

numpy=1.22.4 python=3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50) 
[GCC 10.3.0]

numpy=1.23.0 python=3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50) 
[GCC 10.3.0]

**Comment by LaurentRDC** [comment]
Not sure if this is a related issue: https://github.com/numpy/numpy/issues/19059

**Comment by rkern** [comment]
#19059 is unrelated. `'>u1'` doesn't change because `'>u1'` and `'<u1'` are equivalent, there being no order to a single byte.

See my comment here: https://github.com/numpy/numpy/issues/15088#issuecomment-707773062

As I mentioned, there is a case to be made that these kinds of "merely rearranging the data" functions ought to preserve endianness, but in general, most numpy operations that create new arrays will convert to the native endianness ASAP.

**Comment by LaurentRDC** [comment]
Ok I understand. I was thrown off because some tests I have, which rely on endianness, started failing somewhat recently.
