### ISSUE TITLE
BUG: Build of numpy 1.23.0 fails on debian-stretch

### ISSUE THREAD

**Issue by mkoeppe** [numpy/numpy#21920]
### Describe the issue:

On `debian-stretch` (gcc-6_6.3.0-18+deb9u1_amd64), building numpy 1.23.0 from source fails, see details in https://trac.sagemath.org/ticket/34110#comment:4
This is a regression from numpy 1.22.4.

### Reproduce the code example:

```python
pip install .
```

### NumPy/Python version information:

1.23.0

**Comment by mattip** [comment]
The error seems to be a slight differences in SIMD compilation. @seiko2plus is there a known problem with gcc 6?:
```
In file included from numpy/core/src/common/simd/avx512/avx512.h:75:0,
                   from numpy/core/src/common/simd/simd.h:50,
                   from /sage/local/var/lib/sage/venv-python3.10.3/var/tmp/sage/build/numpy-1.23.0/src/numpy/core/src/npysort/x86-qsort.dispatch.cpp:17,
                   from build/src.linux-x86_64-3.10/numpy/core/src/npysort/x86-qsort.dispatch.avx512_skx.cpp:21:
  numpy/core/src/common/simd/avx512/arithmetic.h: In function 'npy_uint32 npyv_reducemax_u32(npyv_u32)':
  numpy/core/src/common/simd/avx512/arithmetic.h:387:89: error: invalid conversion from 'int' to '_MM_PERM_ENUM' [-fpermissive]
           npyv_u32 a3 = _mm512_max_epu32(a2, _mm512_shuffle_epi32(a2, (1<<6 | 0<<4 | 3<<2 | 2)));
                                                                       ~~~~~~~~~~~~~~~~~~~~^~~~
...
 In file included from build/src.linux-x86_64-3.10/numpy/core/src/npysort/x86-qsort.dispatch.avx512_skx.cpp:21:0:
  /sage/local/var/lib/sage/venv-python3.10.3/var/tmp/sage/build/numpy-1.23.0/src/numpy/core/src/npysort/x86-qsort.dispatch.cpp: In function 'npy_int partition_vec(type_t*, npy_intp, npy_intp, zmm_t, zmm_t, zmm_t*, zmm_t*)':
  /sage/local/var/lib/sage/venv-python3.10.3/var/tmp/sage/build/numpy-1.23.0/src/numpy/core/src/npysort/x86-qsort.dispatch.cpp:654:64: error: there are no arguments to '_knot_mask16' that depend on a template parameter, so a declaration of '_knot_mask16' must be available [-fpermissive]
       vtype::mask_compressstoreu(arr + left, _knot_mask16(gt_mask), curr_vec);
      
```

**Comment by rgommers** [comment]
It looks like we don't have a CI job with the lowest-supported GCC version; we should probably fix that.

**Comment by mkoeppe** [comment]
Related to that, https://numpy.org/doc/stable/user/building.html#prerequisites could probably be made clearer. There's still talk about GCC 4.x. https://docs.scipy.org/doc/scipy/dev/toolchain.html#c-compilers is much better

**Comment by seiko2plus** [comment]
@mattip,
> is there a known problem with gcc 6?

Regards to the current build error, here are some:

- limited support for AVX512 mask operations

  *  synonyms intrinsics `_k[and, or, xor, not]_mask16` don't exist, we usually use `_mm512_[and, or, xor, not]` since its widely supported even on old versions of MSVC.
  * `AVX512BW` mask operations aren't supported at all, usually we fall down to integer registers
  * `AVX512DQ` same as `BW`, as workaround we cast around `__mmask16`.
  * most of these cases are handled in https://github.com/numpy/numpy/blob/75ae7be9fc053c8b8c2187b7ca170183da370ba2/numpy/core/src/common/simd/avx512/operators.h#L146

- On C++ only, the type of the second operand of shuffle intrinsics requires to be staticly cast to `_MM_PERM_ENUM`.

**Comment by mkoeppe** [comment]
Thanks all!
