### ISSUE TITLE
BUG: a vectorize function run twice for an scalar input (expected to only run once)

### ISSUE THREAD

**Issue by zlispositive** [numpy/numpy#22054]
### Describe the issue:

For an vectorized function, the number of times the pre-vectorized method is run is not the same as the length of the input array. 

Running the `func_v1` in the sample code shows **2** "Computation started". 

Running the `func_v2` in the sample code shows **4** "Computation started". 

### Reproduce the code example:

```python
import numpy as np
import logging

logging.basicConfig(level=logging.DEBUG)

def func(x):
    logging.debug(f"Computation started")
    return x

func_v1 = np.vectorize(func)
func_v2 = np.vectorize(func_v1)
func_v1(1)
func_v2(1)
```

### NumPy/Python version information:

1.22.3 3.8.13 (default, Mar 28 2022, 06:16:26) 
[Clang 12.0.0 ]

**Comment by MatteoRaso** [comment]
I think I found the source of the bug. On line 2355 of function_base.py, it says that the program calls the function to find the outputs. This causes problems when the function that's supposed to be vectorized also prints information out. I'm not entirely sure how to fix this, since it seems impossible to figure out what the outputs of a function are supposed to be without calling it. That being said, the vectorize function is basically a glorified for-loop, so you don't really need to use it if it causes any problems.

**Comment by rossbar** [comment]
@MatteoRaso hit on an important point - the purpose of the "first" function call is to determine the output types. There are two ways to "fix" the multiple calls:
 1. Explicitly specify the output dtype via `otypes` so `vectorize` doesn't have to determine it on-the-fly
 2. Use `cache=True` to cache the first function call.

See [the docs](https://numpy.org/devdocs/reference/generated/numpy.vectorize.html) for more info on these parameters.
