### ISSUE TITLE
BUG: Using `min` with `axis` on empty array sometimes works?

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#22063]
### Describe the issue:

Noticed recently that some case where `min` is called on an empty array work depending on how `axis` is specified. In particular if the `axis` specified is non-zero it will work (even when the array is still empty).

### Reproduce the code example:

```python
import numpy

numpy.zeros((0, 3)).min(axis=0)  # raises ValueError
numpy.zeros((0, 3)).min(axis=1)  # array([], dtype=float64) ?
numpy.zeros((0, 3)).min()        # raises ValueError
```

### NumPy/Python version information:

```
1.22.4 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:52) 
[Clang 13.0.1 ]
```

**Comment by leofang** [comment]
I believe in all cases NumPy should raise the same error for consistency
```
ValueError: zero-size array to reduction operation ... which has no identity
```

**Comment by WarrenWeckesser** [comment]
That looks correct to me.  You can't apply min along an axis of length 0, but otherwise, there is nothing special about such an axis.  When an integer axis is given, the invariant is that the axis of reduction is removed (unless keepdims is True), leaving the rest of the shape the same.
```
In [12]: np.zeros((5, 3)).min(axis=1).shape
Out[12]: (5,)

In [13]: np.zeros((0, 3)).min(axis=1).shape  # This is consistent with the previous example.
Out[13]: (0,)

In [14]: np.zeros((8, 0, 9, 10)).min(axis=2).shape  # Same invariant with more dimensions.
Out[14]: (8, 0, 10)
```

**Comment by leofang** [comment]
The problem is the reduction identity (as noted in the error messages in some cases) is ill defined for zero-size arrays. Consistency of shapes is just one minor factor IMHO.

**Comment by WarrenWeckesser** [comment]
When an axis given, the overall *size* of the array does not matter. All that matters is the length of the axis being reduced.

There is a clear interpretation for these cases, too.

* `np.zeros((0, 3)).min(axis=0)` can be interpreted as "Compute the minimum of 3 collections of numbers, each with length 0".  The minimum of a collection with length 0 not defined, so an error is appropriate.
* `np.zeros((0, 3)).min(axis=1)` can be interpreted as "Compute the minimum of 0 collections of numbers, each with length 3".  This does *not* mean a minimum is computed on a collection of length 0.  It means there are *no* collections to which the minimum is applied.  So the returned shape `(0,)` is correct.

**Comment by leofang** [comment]
I went back and forth about this and think the status quo is acceptable. Essentially, it involves whether the chosen axis would lead to "reducing an empty slice", which, depends on the reduction op, could be ill-defined.

But it doesn't mean the other (2nd) case _cannot_ raise -- we can make it raise if we want, which is why this issue was opened for discussion. The error message `ValueError: zero-size array to reduction operation ... which has no identity` can be equally applicable to this case, because indeed the input _is_ a zero-size array, and we do not know what identity to use here.

That said, I suspect changing the NumPy behavior to always raise could be breaking a lot of downstream code, given that the shape consideration alone makes sense to, perhaps many, applications.

**Comment by seberg** [comment]
The current behavior is correct, it correctly generalizes the following:
```
for i in range(10):
    arr = np.zeros((N, 3))
    res = arr.min(0)

    expected = np.zeros(N)
    assert np.array_equal(res, expected)
```
You *can* reduce a length 3 array, there is always a result defined.  If we have a stack of 0 length 3 arrays, the result is thus perfectly well defined and generalizes to arbitrary `N` (including 0).

I do not agree the error can be applied to this case, because the reduction is *not* empty, the result is.

**Comment by leofang** [comment]
Thanks for the prompt Friday discussion, everyone!

**Comment by jakirkham** [comment]
Indeed thanks everyone 🙏

Think this captures the essence of the feedback above.

```python
In [1]: min([(), (), ()])
Out[1]: ()
```
