### ISSUE TITLE
DOC: API reference for numpy.random.randint is wrong

### ISSUE THREAD

**Issue by abdusemiabduweli** [numpy/numpy#22066]
Issue with current documentation:

https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html?highlight=random%20randint#numpy.random.randint
Now:

Parameters

    low: int or array-like of ints

        Lowest (signed) integers to be drawn from the distribution (unless high=None, in which case this parameter is one above the highest such integer).

    high: int or array-like of ints, optional

        If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None). If array-like, must contain integer values

It should be:

Parameters

    low:  int or array-like of ints, optional

        If provided, one above the Lowest (signed) integer to be drawn from the distribution (see below for behavior if low=None). If array-like, must contain integer values

    high: int or array-like of ints

         Highest(signed) integers to be drawn from the distribution (unless low=None, in which case this parameter is one under the highest such integer).

**Comment by rkern** [comment]
The documentation is correct. I see what you are trying to do with your proposed change, but it is strictly speaking incorrect. `low` can never be `None`, for instance. We chose to document the arguments close to how it is implemented. It's not the only way that we could have documented this odd case (`np.arange()` chose something closer to your proposal), but this choice is valid and more correct in how the arguments are processed. For example, your documentation suggests that `randint(high=10)` would work, but it won't because `low` actually is a required argument. Similarly, `np.arange(stop=10)` doesn't work, though its documentation's wording suggests it should.

**Comment by abdusemiabduweli** [comment]
Thank you so much for your response. I now understood what was going on.
