### ISSUE TITLE
ENH: Numpy.rint should return dtype as int

### ISSUE THREAD

**Issue by jpmorr** [numpy/numpy#22131]
### Proposed new feature or change:

`numpy.rint` should return a scalar/array of `dtype` `int` - isn't that the whole point of the function? I round values of floats to the nearest `int` using the function and then I still have to change the type manually to an integer to prevent:
```
*** TypeError: 'numpy.float64' object cannot be interpreted as an integer
```
 when passing to a function that is expecting `int`. 

Is there a reason why it's not a good idea to do the conversion automatically given the purpose of this function?

**Comment by rkern** [comment]
Not for the integer dtypes that we currently have, no. `np.float64` values can have magnitudes much, much larger than `np.int64`. That's why `np.rint()`, named after the [C function that it wraps](https://linux.die.net/man/3/rint), maintains the floating-point dtype of its input.

For a long time, even Python's `round()` function returned floats. It only made the change to returning integers long after Python made the switch to having unbounded integers. Unfortunately, we do not have the luxury of unbounded integers in numpy.
