### ISSUE TITLE
BUG: Overloaded return types with np.cross NoReturn leads to type-checking issues

### ISSUE THREAD

**Issue by danielpmorton** [numpy/numpy#22146]
### Describe the issue:

np.cross appears to have a return type of `NoReturn` when dealing with `_ArrayLikeBool_co` type, and this `NoReturn` type is incompatible with type checking in Pylance, and VSCode determines that all code after a call to np.cross is unreachable. 

This has been mentioned in a Pylance issue here (https://github.com/microsoft/pylance-release/issues/3195), but they recommended mentioning it with NumPy. 

### Reproduce the code example:

```python
import numpy as np

x = np.array([1,2,3])
y = np.array([2,3,4])

z = np.cross(x, y)
# This code is determined as unreachable by VSCode due to a NoReturn type
print(z)
```

### NumPy/Python version information:

1.23.2 3.9.12 (main, Jun 12 2022, 13:39:05)
[GCC 9.4.0]

### Context for the issue:

My code uses np.cross in many places, as well as extensive type-checking. It would be very nice if the return types could be cleaned up to improve compatibility with VSCode/Pylance/Pyright, because right now all of my code is grayed-out

**Comment by LeonaTaric** [comment]
![image](https://user-images.githubusercontent.com/92495067/185723208-de088fbd-7a15-4441-97f7-fb94b56fb1e4.png)
in the code, only type ArrayLikeBool will noreturn, ArrayLikeInt or ArrayLikeFloat will return type Array correctly

**Comment by wzy-99** [comment]
I have the same problem, and i just commented out the NoReturn function.

**Comment by nimagitac** [comment]
I have also the same problem. Pylance marked some lines as unreachable. (The temporary remedy could be the usage of "dtype" in numpy.cross function)

**Comment by danielpmorton** [comment]
Yeah, I would prefer to not have to manually modify my own installation of NumPy to adjust this, and this should be a relatively quick fix for the development team

**Comment by wolfrayet** [comment]
I also have the same problem. I cannot solve it even if I specify the array type.

**Comment by ShapingView** [comment]
Reopen this issue?

--> https://github.com/numpy/numpy/pull/22359#issuecomment-1734577701

**Comment by Liquidmasl** [comment]
> @Liquidmasl please tell us a bit more: how are you seeing this? Is it exactly like in the original description? What version of NumPy are you using?

i use 1.36.3
I do not use pylance but pycharm, but the issue is (i believe) the same. 
although you did make me less sure about it

![Screenshot 2024-01-31 185613](https://github.com/numpy/numpy/assets/10048306/edb8ac42-4efa-4b8b-9b31-d63c8984bebf)

when checking the overloads there is this one overload:

```py 
@overload
def cross(
    a: _ArrayLikeBool_co,
    b: _ArrayLikeBool_co,
    axisa: int = ...,
    axisb: int = ...,
    axisc: int = ...,
    axis: None | int = ...,
) -> NoReturn: ...
```
which seams to be the issue. although i dont quite understand why the arrays are assumed to be dtype bool

even declaring dtypes on the input arrays does not help
![image](https://github.com/numpy/numpy/assets/10048306/2fe54de7-142d-46b5-bf2e-0ac0cd5630b6)

But maybe this is a completely different issue?

maybe i should comment there? https://github.com/numpy/numpy/pull/22359#issuecomment-1734577701

(sorry i am somewhat new to the open source world.)
