### ISSUE TITLE
BUG: divmod delivers wrong result

### ISSUE THREAD

**Issue by juergsch** [numpy/numpy#22145]
### Describe the issue:

If the remainder is close to the resolution limit, the result seems to be wrong due to a numerical problem. I wonder how this function can be used in practice, even if there is an explanation for result.
Maybe my proposal is a bit naive, but istn't it possible to round the result considering the actual resolution, like .. see in the code?

### Reproduce the code example:

```python
import numpy as np

# numpy.divmod with strange result
a=3.333
b=5.0*a
print(np.divmod(b,a)) 
# delivers: (4.0, 3.3329999999999984), while expected: (5.0, 0.0)

# pragmatic approach with correct result
c = b/a
divisor = round(c)
remainder = 0.0 if abs(c-d)<np.finfo(np.float).resolution else c-d
# delivers: divisor = 5, remainder = 0.0
```

### NumPy/Python version information:

numpy 1.23.0

**Comment by rkern** [comment]
In general, we tend to expose the basic floating point semantics rather than try to paper over them with rounding after the fact. Whether or not you want that rounding is application-dependent. When you know that it is desirable, then you are able to implement it because we expose the basic floating point semantics relatively unadorned. When it is undesirable, it is harder to work around if we always do that kind of convenience rounding.

**Comment by juergsch** [comment]
Ok, I see the point. Having a consistant principle everywhere is certainly a good idea. I was quite surprized, though, as this sporadically crashed my program depending on the inputs. Thanks!
