### ISSUE TITLE
Multidimensional and one-dimensional solutions are inconsistent

### ISSUE THREAD

**Issue by shantzhou** [numpy/numpy#22196]
### Describe the issue:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/48147228/188078703-07e0172e-caf5-4214-8887-f03312454c18.png">

### Reproduce the code example:

```python
import numpy as np
k = np.random.rand(3,64).astype(np.float32)
n1 = k/np.linalg.norm(k, 2, axis=1, keepdims=True)
n2 = k[0]/np.linalg.norm(k[0])
n3 = k[1]/np.linalg.norm(k[1])
print(n1[1]-n3)
```

### NumPy/Python version information:

1.22.4

**Comment by seberg** [comment]
This is expected.  The results are identical up to numerical precision limits.  Different ways (including order) of calculation can give different results.
There is one subtlety that different order can give more than the naive expected difference, because NumPy often gives _better_ than naive results.  See also the notes for [`numpy.sum`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html).

Similar considerations will also matter for other functions (such as linear algebra), though `norm` itself may just be due to `sum` also.

**Comment by shantzhou** [comment]
> This is expected. The results are identical up to numerical precision limits. Different ways (including order) of calculation can give different results. There is one subtlety that different order can give more than the naive expected difference, because NumPy often gives _better_ than naive results. See also the notes for [`numpy.sum`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html).
> 
> Similar considerations will also matter for other functions (such as linear algebra), though `norm` itself may just be due to `sum` also.

ok，thank u very much
