### ISSUE TITLE
BUG: RuntimeWarning inconsistent between uint16 and uint32

### ISSUE THREAD

**Issue by phofl** [numpy/numpy#22209]
### Describe the issue:

Having negative floats when casting to ``uint32`` raises a ``RuntimeWarning`` but ``uint16`` silently overflows. This occurred in the pandas test suite

### Reproduce the code example:

```python
x = np.array([-2.9792401]).astype("uint32")

[0]

x = np.array([-2.9792401]).astype("uint16")

[65534]
```

### Error message:

```shell
RuntimeWarning: invalid value encountered in cast
  x = np.array([-2.9792401]).astype("uint32")
```

### NumPy/Python version information:

1.24.0.dev0+703.gb2fbc4349 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:14) 
[Clang 12.0.1 ]

### Context for the issue:

I am not sure if there is something I am missing, but I think both should show the warning?

**Comment by seberg** [comment]
Did the release note clear this up mostly/partially?  I believe what is happening is that compilers do slightly different things for these casts, i.e. they may compile them to byte code that effectively does:
```
float64 -> int64 -> uint16
```
rather than using an instruction that does the conversion directly.  If the conversion is done "directly", the CPU may give an undefined result but should set the warning flag.  But if the conversion is done "indirectly", the "bad" integer cast does not flag the warning.  I suspect that you always get the "correct" integer overflow result when no warning is given, but I chances are that there are compilers and/or hardware that do not do it correctly.

Of course we *could* add manual checks for these cases.  I am not sure if that would have an effect on speed.  Right now the warnings are new, but it is indeed surprising that they only occur for the undefined cases but not for those badly defined ones.

**Comment by phofl** [comment]
Partially, it pointed me into the right direction, but what confused my was the difference between ``uint16`` and ``uint32``. I would have expected that this would be consistent. But I am not expert by all means. If this is expected, then you can close this. Just wanted to ensure that there isn't anything strange going on,

**Comment by seberg** [comment]
I agree that it is inconsistent, but it arises from how compilers do the casts.  There may be ways to fix this (I am not sure how easy it is), but at the moment we are inheriting the behavior of C casts directly.
Additionally, we could always improve the behavior to be fully predictable (e.g. always an error/warning).  Right now, I think the warning is a small improvement (even if "incomplete"), but if you disagree, maybe we should follow up more.

Closing for now, but happy to reopen if anyone wants to make sure we follow up.
