### ISSUE TITLE
BUG: `delimiter` of np.loadtxt cannot be a newline (`\r` or `\n`)

### ISSUE THREAD

**Issue by braniii** [numpy/numpy#22320]
### Describe the issue:

My goal is to read non-quadratic files, e.g.
```
file.dat
--------
1 2 3 4 5
6 7 8
9
10 11
```
as a list of ndarrays via
```python
[
    np.array(row.split()).astype(int)
    for cluster in np.loadtxt('file.dat', delimiter='\n', dtype=str)
]
```
The reason I am using not the pure python `open` is my laziness. But I guess that's what I should do now.

In #22311 it was stated that starting from v1.23.0 the `'delimiter'` parameter of `np.loadtxt` requires a single unicode character. But it can be only selected unicode characters, the control character cannot be a newline.

I am not sure if this should be mentioned in the documentation. If not feel free to close this issue directly.

### Reproduce the code example:

```python
import numpy as np

# create test file
filename = 'test.dat'
dat = np.arange(20).reshape(10, 2)
np.savetxt(filename, dat, fmt='%.0f')

# this works fine
np.loadtxt(filename)

# this does not work anymore
np.loadtxt(filename, delimiter='\n')
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/user/numpy_loadtxt.py", line 12, in <module>
    np.loadtxt(filename, delimiter='\n')
  File "/home/user/anaconda3/envs/numpy/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1313, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/user/anaconda3/envs/numpy/lib/python3.10/site-packages/numpy/lib/npyio.py", line 979, in _read
    arr = _load_from_filelike(
TypeError: control character 'delimiter' cannot be a newline (`\r` or `\n`).

shell returned 1
```

### NumPy/Python version information:

1.23.3 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0]

### Context for the issue:

Useful for loading files containing different number of numbers on each row, so non-quadratic. So I guess the priority is very low.

**Comment by seberg** [comment]
@braniii that is true, although it just rejects something that is marginally meaningful to begin with?  Loadtxt "starts" by splitting lines, so there should not be any newline characters left to.
I suppose rather than rejecting `\n` we could effectively replace it with "no delimiter in use".

Now, there is no way to spell "no delimiter" in the new NumPy version (which `\n` was admittedly a fun way to use :)).  The closest thing may be to use the `\0` character, which is unlikely to be included in your file.

If this is a nuisance for you, that could be good enough on its own to turn it into a deprecation-warning, though.  No matter whether we want to actually allow (ignore) newline here.

**Comment by braniii** [comment]
@seberg I was not aware that there is an character for null. `\0` is indeed a smart solution to my issue, thx a lot :)

**Comment by seberg** [comment]
Going to close, the docs now mention it.  But if anyone else feels it might be good to roll back (or provide "nothing" as a valid character), please don't hesitate to open a new issue (it is very hard to judge how tricky such changes are for downstream).
