### ISSUE TITLE
i have no idea what's meaning of this error, when i put it into one dimintional array..it worked!! , but when it more this error appear to me!?

### ISSUE THREAD

**Issue by salamahalaa** [numpy/numpy#22335]
### Describe the issue:

i have no idea what's meaning of this error, when i put it into one dimintional array..it worked!! , but when it more this error appear to me!?

### Reproduce the code example:

```python
import numpy as np
b=np.array([[2,3,4.0,5],[2,3,41,5,4,2,2]])
print(b)
```

### Error message:

```shell
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[2,3,4.0,5],[2,3,41,5,4,2,2]])
```

### NumPy/Python version information:

sadf

### Context for the issue:

I am student ,  so i wanna learn whats the solution

**Comment by matthew-brett** [comment]
Are you trying to make a "ragged" array  - one that has unequal numbers of columns across the rows?   You can do this in Numpy, but the warning is trying to tell you that this may not be what you want, because ragged arrays are much less efficient for computation than not-ragged arrays (arrays where every row has the same number of columns).

As the message implies, if you really do want to do this, you can write:

```python
b=np.array([[2,3,4.0,5],[2,3,41,5,4,2,2]], dtype=object)
```

**Comment by tylerjereddy** [comment]
For certain types of work with ragged data structures, see also: https://awkward-array.readthedocs.io/en/latest/

**Comment by seberg** [comment]
NumPy doesn't support arrays that are "ragged", each dimension has to have a fixed length.  The solution may be to figure out how to deal with this using a non-ragged array.  Maybe a list of arrays is also an option.

Or you can check out awkward array as tyler suggested.  For certain use-cases of data, it may also be that `pandas` (or similar) is a solution.  It would store data 1-D, but then has operations like `group_by` which might just be what you need.

In any case, I suspect the question was sufficiently answered and will close the issue. You can follow-up if ou like.

**Comment by salamahalaa** [comment]
Sir nothing changes at all!! , Its says to me , object is not defined. Did
u mean :'object?'... What's means of that?!

في الأحد، ٢٥ سبتمبر ٢٠٢٢ ٩:٢٢ م Matthew Brett ***@***.***>
كتب:

**Comment by matthew-brett** [comment]
`object` means you are telling Numpy that it should store each row of the array as its own object, rather than trying to make a full 2D array.  `object` is always defined in Python, it's the basic type for all objects.

Specifically, if you start a new Python session, then you will find that this code works, copy / pasted exactly as-is:

```python
import numpy as np
b=np.array([[2,3,4.0,5],[2,3,41,5,4,2,2]], dtype=object)
```
