### ISSUE TITLE
DOC: Docstring for Function intersect1d shows a wrong result in example 

### ISSUE THREAD

**Issue by DannyIbo** [numpy/numpy#22378]
### Issue with current documentation:

In Version 1.18.1 for the function intersect1d the docstring gives an example at its very end. The very last line of the example is referring to the expected output but it is wrong, possibly because of a copypaste mistake.

Originally it says:

>>> x = np.array([1, 1, 2, 3, 4])
>>> y = np.array([2, 1, 4, 6])
>>> xy, x_ind, y_ind = np.intersect1d(x, y, return_indices=True)
>>> x_ind, y_ind
(array([0, 2, 4]), array([1, 0, 2]))
>>> xy, x[x_ind], y[y_ind]
(array([1, 2, 4]), array([1, 2, 4]), array([1, 2, 4]))

### Idea or request for content:

Actually right is the output as in the last line here:

>>> x = np.array([1, 1, 2, 3, 4])
>>> y = np.array([2, 1, 4, 6])
>>> xy, x_ind, y_ind = np.intersect1d(x, y, return_indices=True)
>>> x_ind, y_ind
(array([0, 2, 4]), array([1, 0, 2]))
>>> xy, x[x_ind], y[y_ind]
(array([1, 2, 4]), array([0, 2, 4]), array([1, 0, 2]))

**Comment by DannyIbo** [comment]
I would like to fix it but it's my first time and I don't know what's the next step. Could somebody advice me please?

**Comment by rossbar** [comment]
The current docstring example is correct. The outputs you are proposing for the last line would be correct for `xy, x_ind, y_ind`, but notice that the last line actually says `xy, x[x_ind], y[y_ind]`. In other words, the last line of the example demonstrates how you can recover the intersected values from the original arrays via indexing.

I'll go ahead and close this since the example is correct in its current form, but thanks for taking a look!
