### ISSUE TITLE
Is it Possible to Build a Completely Statically Linked Numpy

### ISSUE THREAD

**Issue by gnodipac886** [numpy/numpy#22600]
### Steps to reproduce:

I'm trying to compile a static python binary using cython and run it on a baremetal RISC-V CPU. And since numpy uses shared objects like multiarray_umath.so it won't be possible to just use pip to install numpy. So the question is, are there ways to statically build numpy so that it's completely contained?

### Additional information:

I am on a RISC-V VM on qemu running Ubuntu 22.04.
Please let me know if additional information is needed.

Cheers

**Comment by mattip** [comment]
This is a niche that I have not heard about before (or have forgotten). I think you will need
- to figure out how to avoid any `-shared` flags in the linking stages of the build, for both cython and numpy
- do the importlib hacks needed to avoid importing from files

Do you have any of this already in place, say for a simple module with a single function that returns the sum of two ints?

**Comment by gnodipac886** [comment]
yeah, I have this running on python2.7 and it can do just that.

if you look at here, they were able to get it running on numpy 1.16, I'll give this one a shot first
https://github.com/Nuitka/Nuitka-Python-packages/tree/master/packages/np27-linux/numpy

**Comment by mattip** [comment]
Cool. As this is not NumPy specific, and it seems you have found what you are looking for, I will close this. Please reopen if there is something NumPy can do to support this model better.

**Comment by aeltorio** [comment]
Hi @mattip ,
I’m not sure whether it’s better to reopen this issue or start a new one, but here is my situation:

I’m developing a Rust‑based laser spectroscopy application. Most processing modules are written in Rust, but because I can’t anticipate every possible processing need, I embedded Python inside my monolithic Rust application. This allows users to write their own custom processing routines in Python, and so far this approach has worked well.

However, our main deployment platform is very specific, and I recently switched to a fully static Python build (libpython3.13.a). The static interpreter works — at least partially — but NumPy cannot be used in this setup. When attempting a simple installation, NumPy tries to build shared modules such as multiarray_umath.so, which is incompatible with a 100% static Python environment.

What I would like to explore is whether it is technically feasible to embed NumPy’s core directly into libpython3.13.a, or otherwise build NumPy in a way that avoids generating shared objects entirely.

If there is any guidance, prior work, or architectural constraints that could clarify whether this is achievable (or fundamentally impossible), I would greatly appreciate it.

Thanks!
