### ISSUE TITLE
BLD: Move some builds to Cirrus CI

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#22640]
Broken out from #22636. Scipy is using [cirrus ci](https://cirrus-ci.org) for linux aarch64 macos arm64, and musl CI runs. The config file is [here](https://github.com/scipy/scipy/blob/main/.cirrus.star), and the CI runs are [here](https://cirrus-ci.com/github/scipy/scipy). They are happier with it than with travis, which has proven flaky. We will still need travis if we wish to keep the ppc64le CI runs.

Looking at the SciPy PR #17029 I think the steps are
- [x] Start a thread on the mailing list and [link it here](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/BGZRCPGMRZ3EAHN75X6BXVKNLWCBXYEZ/).
- [x] Sign up for an account and add the app to the repo. Can we join the SciPy one or do we need our own?
- [x] Create [some tokens](https://github.com/scipy/scipy/pull/17029#issuecomment-1253139344)
- [x] Create a workflow
- [x] Set up a cron job for the weekly wheels
- [ ] Document it somewhere: we should have some "maintainer tasks" documentation somewhere with a table of all the CI runs and what they do, and how to update dependencies like OpenBLAS and cibuildwheel

**Comment by andyfaff** [comment]
I'd like to have a go at this (unless someone has already started on it)

- You need to follow https://cirrus-ci.org/guide/quick-start/ to add cirrus-ci on Github Marketplace for the *numpy* organisation.
- Setting up cron is easy.

**Comment by charris** [comment]
@andyfaff Do we want cirrus ci, cirrus action, or both?

**Comment by andyfaff** [comment]
I've not used the Action, just the cirrus-ci App

**Comment by andyfaff** [comment]
From a quick view of the *action* it seems to be a way of using the [`cirrus-cli`](https://github.com/cirruslabs/cirrus-cli). "Cirrus CLI is a tool for running containerized tasks reproducibly in any environment".

One would still have to have the cirrus-ci *app* from the marketplace because we need their CI provision to use aarch64/arm64. To run the CI one needs to create those cirrus yml files anyway. 

IIUC all the Action does is start them running. It's just as easy to write a [.cirrus.star](https://cirrus-ci.org/guide/programming-tasks/) file, and I think it's probably less complicated.

**Comment by charris** [comment]
@andyfaff If you run into permissions problems, let me know.

**Comment by andyfaff** [comment]
This can probably be closed now? If it's decided to add generalised test runs to cirrus the git clone may need to be adjusted. It doesn't merge PR into main by default, it tests the branch instead.
