### ISSUE TITLE
pass hermitian=True to svd call in multivariate_gaussian

### ISSUE THREAD

**Issue by bernstei** [numpy/numpy#22664]
I'm having an issue with `multivariate_gaussian` giving the error
```
  File "/home/cluster2/bernstei/src/work/HAL/HAL_lib/lsq.py", line 93, in fit
    comms = np.random.multivariate_normal(c, sigma_reg, size=ncomms)
  File "mtrand.pyx", line 4120, in numpy.random.mtrand.RandomState.multivariate_normal
  File "<__array_function__ internals>", line 5, in svd
  File "/home/cluster2/bernstei/python/mkl/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 1660, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/cluster2/bernstei/python/mkl/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
```
I played around with it, and I discovered that if you pass `hermitian=True` to the SVD call, it works fine, at least for this particular ill-conditioned example. Since `multivariate_normal` already requires the covariance to by symmetric, is there any reason not to pass `hermitian=true` to the `svd` call here https://github.com/numpy/numpy/blob/8d61ebc25a117337d148f1e3d96066653bd6419a/numpy/random/mtrand.pyx#L4219
I suspect it'll always be as or more stable than a general routine.

**Comment by Kai-Striega** [comment]
@seberg how do you fell about this? I'd be interested in fixing it. It looks pretty straight forward to implement

**Comment by seberg** [comment]
The new `Generator.multivariate_normal` has a `method=` arguments which maybe covers this already? (I am not sure.)
If it doesn't I guess that may be expandable.  I feel there was also discussion at some point to allow passing in the result of the calculation rather than `cov` somewhere, which may be relevant.

**Comment by Kai-Striega** [comment]
I've done some digging, it looks like using ``svd(...,hermitian=True)`` has already been considered (see below). It looks like we should be using `eigh` instead.

https://github.com/numpy/numpy/blob/6615d6bc26c30bf618538230ded86c09381a3e28/numpy/random/_generator.pyx#L3737-L3747

**Comment by mdhaber** [comment]
@Kai-Striega that code is for the `multivariate_normal` method of `Generator`, but the issue seems to be about the legacy `np.random.multivariate_normal`. (If it were about `Generator`, then it looks like switching to `method='eigh'` would be equivalent to `svd` with `hermitian=True` because `svd` calls `eigh` in that case.) 

If updates to `numpy.random.multivariate_normal` are allowed, I don't think there would be much harm in putting the call to `svd` in a `try-except`. If there is a `LinAlgError`, it could try `eigh` (or probably `svd` with `hermitian=True` for simplicity). 

@rkern in https://github.com/numpy/numpy/issues/17007#issuecomment-1529747064 you wrote that "legacy is frozen for fixes like this." Does that include fixes like this? If so, is this a wontfix?

**Comment by rkern** [comment]
Yes.

**Comment by mdhaber** [comment]
Closing since the desired solution is available via `Generator` and the legacy RNG code shouldn't be changed for this sort of thing.
