### ISSUE TITLE
ENH: Allow automatic detection of dtype parameters for NEP 42 user dtypes

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#22756]
### Proposed new feature or change:

Currently it's not possible to pass in e.g. the DType class to `np.array` and allow the dtype machinery to auto-determine the dtype instance necessary to represent the input array data. For example, currently if I do:

```python
import numpy as np
from asciidtype import ASCIIDType

dtype = ASCIIDType

arr = np.array(["hello", "this", "is", "an", "array"], dtype=dtype)

print(arr.dtype)
```

I get back that the dtype is object (e.g. passing in the dtype class is ignored inside numpy). It works as expected if I pass in a dtype instance.

Perhaps there could be an optional method on the dtype that is passed in the input data if the method is defined, and returns a dtype instance that can represent the data (or bails and/or errors if that's not possible).

This example uses `asciidtype` from the [`numpy-user-dtypes` repo](https://github.com/numpy/numpy-user-dtypes).

cf. @seberg's comment about this issue: https://github.com/numpy/numpy-user-dtypes/pull/10#discussion_r1042069754

**Comment by seberg** [comment]
Note that the core machinery has everything for this read already, you don't need any additional functionality on the `DType`!  The only problem is that:
```
np.array(..., dtype=something)
```
is always equivalent to:
```
np.array(..., dtype=np.dtype(something))
```

Which means that only dtype *instances* reach the core implementation of `np.array()`.  But, the core implementation very much supports `dtype=DType` (where DType is the class/type of the instance).

You can already try this actually:
```
from numpy.core._multiarray_umath import _discover_array_parameters
_discover_array_parameters([1, 2], dtype=type(np.dtype("S")))
```
(note that the type is passed there, which `np.array()` will not like and decide that its `object`)

So we can fix the thing by passing through the dtype instances *or* class.  Alternatively, we could introduce abstract _instances_ also.  I always tried to avoid that, also because it doesn't translate perfectly to ufunc loop dispatching.  But it might be pretty pragmatic to have it.

**Comment by ngoldbaum** [comment]
Ah I see, thanks for clarifying that!

Maybe it would be useful if parametric dtypes were required to provide an abstract instance for this use? Currently they're required to provide a singleton with some sort of null or default parameter, and I can see cases where that might be annoying to deal with, or provide a suboptimal user-facing API. For example, right now, `ASCIIDType()` is equivalent to `ASCIIDType(0)` because of the need to create a singleton at initialization, but I'd probably prefer to *require* the size.

**Comment by seberg** [comment]
@ngoldbaum the length 0 is something I don't like and strings have, because a length 0 string is not unreasonable.  However, we could (ab)use `elsize == -1` or so to signal such an "abstract" instance.

If that is seen, array-creation would have to try to convert it to an actual dtype or raise an error when it doesn't work.
Conceptually, I prefer to think of this as a/the DType class, though.  Because then the *instance* is clearly defined as what you can attach to an array (with an element size, etc.).  But I am not sure if that is always pragmatic (mainly, when there a DType may have multiple parameters, say encoding and length, and you want to say "utf8" but infer the length, in that case handling that via DType classes is probably possible but likely inconvenient).

We should not required to provide a default singleton.  You can define a `default_descr()` that always sets an error like "must provide a unit!", although I suspect that is rarely the pragmatic path.

**Comment by mattip** [comment]
I think it is fine to limit this mechanism to parametric (flexible?) dtypes to signal "please calculate the dtype specific parameter for me". In numeric cases, I am not sure we need to allow passing in a type.

**Comment by ngoldbaum** [comment]
I was able to get an ASCIIDType instance out of `astype(ASCIIDType)` and `np.array(..., dtype=ASCIIDType)` with the following change:

```diff
diff --git a/numpy/core/src/multiarray/descriptor.c b/numpy/core/src/multiarray/descriptor.c
index ecaa6834c..7767f8c1e 100644
--- a/numpy/core/src/multiarray/descriptor.c
+++ b/numpy/core/src/multiarray/descriptor.c
@@ -1429,6 +1429,9 @@ _convert_from_type(PyObject *obj) {
     else if (typ == &PyMemoryView_Type) {
         return PyArray_DescrFromType(NPY_VOID);
     }
+    else if (PyObject_IsInstance(typ, &PyArrayDTypeMeta_Type)) {
+        return NPY_DT_CALL_default_descr((PyArray_DTypeMeta*)typ);
+    }
     else if (typ == &PyBaseObject_Type) {
         return PyArray_DescrFromType(NPY_OBJECT);
     }
```

However, from this code path we don't have access to the array data, so it's not possible to do value-based promotion on the result.

One thing I could do is add a `default_descr` function to my dtype (right now it uses `use_new_as_default`) so that the default descriptor is invalid (e.g. `ASCIIDType(-1)`, or maybe with a flag so I'm not semantically overloading the size of the dtype). Then, later, we can check if the dtype is invalid and do value-based-promotion before the array is returned to the user.

This is more or less the abstract type solution outlined above.

Is there another way to do this that might be better? I was forced into abstract instance path because input dtypes are validated via `PyArray_DescrConverter`, which is ultimately why the solution I arrived at doesn't have access to the array data.

**Comment by seberg** [comment]
Well, we can create a new `PyArray_DescrAndDTypeConverter` which returns either a dtype instance or class.  Something like that was always my plan to avoid abstract instances.  But I don't _hate_ abstract instances, just felt the class is probably enough to do this.
(If we add an abstract instances, `resolve_descriptors` will have to learn about it though.)

**Comment by ngoldbaum** [comment]
#23404 fixed most of this, although there are still several places in the numpy API where it probably makes sense to accept dtype classes: https://github.com/numpy/numpy/pull/23404#issuecomment-1472365800

**Comment by ngoldbaum** [comment]
Now that `empty`, `empty_like`, and `zeros` take dtype classes I’m closing this. We can follow up if we find other places it’s natural to pass a dtype class.
