### ISSUE TITLE
BUG: polynomial string options setting is not context safe

### ISSUE THREAD

**Issue by h-vetinari** [numpy/numpy#22825]
While [building](https://github.com/conda-forge/numpy-feedstock/pull/285) numpy 1.24.0 for conda-forge, we ran into the following errors. All three errors seem to be related to perhaps overzealously prettifying the serialization of polynomials, so for now we skipped those tests on osx+pypy. Details below.

```
=================================== FAILURES ===================================
__________________________ TestPrintOptions.test_str ___________________________
[gw2] darwin -- Python 3.8.13 $PREFIX/bin/python

self = <numpy.polynomial.tests.test_printing.TestPrintOptions object at 0x00007f9c0008d600>

    def test_str(self):
        p = poly.Polynomial([1/2, 1/7, 1/7*10**8, 1/7*10**9])
>       assert_equal(str(p), '0.5 + 0.14285714 x + 14285714.28571429 x**2 '
                             '+ (1.42857143e+08) x**3')
E       AssertionError:
E       Items are not equal:
E        ACTUAL: '0.5 + 0.14285714·x + 14285714.28571429·x² + (1.42857143e+08)·x³'
E        DESIRED: '0.5 + 0.14285714 x + 14285714.28571429 x**2 + (1.42857143e+08) x**3'

p          = Polynomial([5.00000000e-01, 1.42857143e-01, 1.42857143e+07, 1.42857143e+08], domain=[-1,  1], window=[-1,  1], symbol='x')
self       = <numpy.polynomial.tests.test_printing.TestPrintOptions object at 0x00007f9c0008d600>

[...]/lib/pypy3.8/site-packages/numpy/polynomial/tests/test_printing.py:483: AssertionError
_____________________ TestPrintOptions.test_switch_to_exp ______________________
[gw2] darwin -- Python 3.8.13 $PREFIX/bin/python

self = <numpy.polynomial.tests.test_printing.TestPrintOptions object at 0x00007f9c0008d0c0>

    def test_switch_to_exp(self):
        for i, s in enumerate(SWITCH_TO_EXP):
            with printoptions(precision=i):
                p = poly.Polynomial([1.23456789*10**-i
                                     for i in range(i//2+3)])
>               assert str(p).replace('\n', ' ') == s
E               AssertionError: assert '1.0 + (1.0e-... (1.0e-02)·x²' == '1.0 + (1.0e-...1.0e-02) x**2'
E                 - 1.0 + (1.0e-01) x + (1.0e-02) x**2
E                 ?                ^             ^ ^^^
E                 + 1.0 + (1.0e-01)·x + (1.0e-02)·x²
E                 ?                ^             ^ ^

i          = 0
p          = Polynomial([1.23456789, 0.12345679, 0.01234568], domain=[-1,  1], window=[-1,  1], symbol='x')
s          = '1.0 + (1.0e-01) x + (1.0e-02) x**2'
self       = <numpy.polynomial.tests.test_printing.TestPrintOptions object at 0x00007f9c0008d0c0>

[...]/lib/pypy3.8/site-packages/numpy/polynomial/tests/test_printing.py:517: AssertionError
_______________________ TestPrintOptions.test_non_finite _______________________
[gw2] darwin -- Python 3.8.13 $PREFIX/bin/python

self = <numpy.polynomial.tests.test_printing.TestPrintOptions object at 0x00007f9c0008cf00>

    def test_non_finite(self):
        p = poly.Polynomial([nan, inf])
>       assert str(p) == 'nan + inf x'
E       AssertionError: assert 'nan + inf·x' == 'nan + inf x'
E         - nan + inf x
E         ?          ^
E         + nan + inf·x
E         ?          ^

p          = Polynomial([nan, inf], domain=[-1,  1], window=[-1,  1], symbol='x')
self       = <numpy.polynomial.tests.test_printing.TestPrintOptions object at 0x00007f9c0008cf00>

[...]/lib/pypy3.8/site-packages/numpy/polynomial/tests/test_printing.py:521: AssertionError
```

@mattip speculated:
> Weird. So PyPy is prettifying the polynomial where CPython does not? Perhaps some terminal discovery routine is behaving differently, so PyPy renders a utf-8 terminal and CPython renders ascii?

**Comment by charris** [comment]
@rossbar  Ping.

**Comment by eric-wieser** [comment]
The only unicode switch I was able to find was

https://github.com/numpy/numpy/blob/2b9851ba4f8cc436266d913eb5db75fc702e1eed/numpy/polynomial/_polybase.py#L108

**Comment by eric-wieser** [comment]
Ah, I would guess this is a test parallelization problem: some test-cases modify global state via:

https://github.com/numpy/numpy/blob/2b9851ba4f8cc436266d913eb5db75fc702e1eed/numpy/polynomial/__init__.py#L180

This should probably be replaced with a `ContextVar` so that different threads/coroutines can have different settings.

**Comment by rossbar** [comment]
> Ah, I would guess this is a test parallelization problem: some test-cases modify global state via:

After messing around with various pytest extensions, I think this particular issue is actually cause by randomizing test order similar to #17954 rather than parallelization. I can reproduce the error with `pytest-randomly` installed (without `pytest-xdist`). Fortunately I think this can be fixed with another fixture to reduce crosstalk between the test classes similar to #17957.

However @eric-wieser's point is also valid - it *is* possible to break the polynomial print style w/ threading. The fix for this is less obvious to me - I think context vars are the right thing to try but I haven't had success yet. FWIW I think a working solution here might also map to `np.set_printoptions` as well.

I'm going to split this into multiple PRs so the contextvars exploration doesn't block the bugfix.

**Comment by seberg** [comment]
Lets close this, @rossbar could add a new one if you like (or add it to the fact that the array print options are also not context safe)
