### ISSUE TITLE
BUG: (1.24.0) np.array(np.nan).astype(str) warns RuntimeWarning: invalid value encountered in cast

### ISSUE THREAD

**Issue by corynezinstitchfix** [numpy/numpy#22843]
### Describe the issue:

Since 1.24.0, `np.array(np.nan).astype(str)` warns `RuntimeWarning: invalid value encountered in cast` when I believe it should not. 

### Reproduce the code example:

```python
import numpy as np
np.array(np.nan).astype(str)
```

### Error message:

```shell
/.../test.py:2: RuntimeWarning: invalid value encountered in cast
  np.array(np.nan).astype(str)
```

### NumPy/Python version information:

1.24.0 3.9.10 (main, Jun 28 2022, 22:06:41)
[Clang 13.1.6 (clang-1316.0.21.2.5)]

### Context for the issue:

 I noticed this because the built-in Pandas functionality to convert a categorical series to a string, `pd.Series(["a", "b", "c", "a"], dtype="category").astype(str)`, has started giving the same warning (I believe from [this](https://github.com/pandas-dev/pandas/blob/main/pandas/core/arrays/categorical.py#L542) line of code)

Note to anyone else experiencing the same, it can be worked around by casting to an object first: `pd.Series(["a", "b", "c", "a"], dtype="category").astype(object).astype(str)`

**Comment by charris** [comment]
Seems reasonable, I marked it for 1.24.1, but don't regard it as a blocker.

**Comment by seberg** [comment]
Heh, fun... our scalar formatting functions are used for casting and can cause float errors: https://github.com/numpy/numpy/blob/88b1ba2c15ef6da94932502da5f2bbdc9cd26d3c/numpy/core/src/multiarray/scalartypes.c.src#L895-L911

The cast itself isn't marked as not caring about float errors (although in principle it is anyway better to not cause them when we don't care about them!): https://github.com/numpy/numpy/blob/708e1bf52175da1edfd658d5a93946b6452e717d/numpy/core/src/multiarray/convert_datatype.c#L2883

The latter should be a good enough hot-fix.  The former can also be fixed by using the C99 functions `isgreater`, etc. (although compiler support may vary, so the first fix is the more important one in practice anyway probably, even if only 90%).

Will do it tomorrow probably, but if anyone wants to open a PR also happy!  I am surprised we have no test for this.

**Comment by the-matt-morris** [comment]
Thanks for raising this issue and addressing it!  FWIW I ran into the same problem today but with converting from categorical variables (`numpy==1.24.0`):

```python
import pandas as pd

df = pd.DataFrame({"column": ["foo", "bar", "baz"]}).astype("category")
df["column"].astype(str)
```

```
/usr/local/lib/python3.9/site-packages/pandas/core/arrays/categorical.py:549: RuntimeWarning: invalid value encountered in cast
  np.array(self.categories._na_value).astype(dtype)
0    foo
1    bar
2    baz
Name: column, dtype: object
```
