### ISSUE TITLE
BUG: Not able to build Numpy 1.24.1 for AArch64

### ISSUE THREAD

**Issue by sprasad14** [numpy/numpy#23035]
### Describe the issue:

The following errors are reported while generating numpy/core/_multiarray_umath.cpython-38-aarch64-linux-gnu.so using aarch64-buildroot-linux-gnu-gcc.
Is there a way to avoid including AVX512 .s files from the compilation?

numpy/core/src/umath/svml/linux/avx512/svml_z0_acos_d_la.s:19: Error: unknown mnemonic `pushq' -- `pushq %rbp'
numpy/core/src/umath/svml/linux/avx512/svml_z0_acos_d_la.s:21: Error: unknown mnemonic `movq' -- `movq %rsp,%rbp'
numpy/core/src/umath/svml/linux/avx512/svml_z0_acos_d_la.s:24: Error: unknown mnemonic `andq' -- `andq $-64,%rsp'
numpy/core/src/umath/svml/linux/avx512/svml_z0_acos_d_la.s:25: Error: unknown mnemonic `subq' -- `subq $192,%rsp'
numpy/core/src/umath/svml/linux/avx512/svml_z0_acos_d_la.s:26: Error: unknown mnemonic `vmovups' -- `vmovups __svml_dacos_data_internal(%rip),%zmm7'
numpy/core/src/umath/svml/linux/avx512/svml_z0_acos_d_la.s:27: Error: unknown mnemonic `vmovups' -- `vmovups 64+__svml_dacos_data_internal(%rip),%zmm8'
numpy/core/src/umath/svml/linux/avx512/svml_z0_acos_d_la.s:30: Error: unknown mnemonic `vmovups' -- `vmovups 128+__svml_dacos_data_internal(%rip),%zmm11'
.......

### Reproduce the code example:

```python
I do not have any code since the build itself is a failure.
```

### Runtime information:

1.24.1

### Context for the issue:

I am building python-numpy package for buildroot linux for ARM 64-bit platform

**Comment by mattip** [comment]
I seem to recall buildroot is a cross-compilation system, right? So you have to "fake out" the cpu detection routines with the information about the target CPU, otherwise it is trying to use host features. The [documentation](https://numpy.org/devdocs/reference/simd/build-options.html#having-issues-with-avx512-features) has some hints about doing this, we may want to explicitly mention cross-compiling there. Since you are the best source for information about what works (once you get it going), please let use know how to improve documentation.

**Comment by andyfaff** [comment]
Please note that the numpy CI matrix has `linux_aarch64` native build entries, so it's likely the issue you're experiencing are with buildroot itself.

**Comment by sprasad14** [comment]
@mattip I tried your suggestion to exclude AVX512 targets. Still the issue is not resolved. I am attaching full logs for your reference. If I remove the lnux folder inside numpy/core/src/umath/svml/, the build is successful! But I am not sure that is not the way to fix it.
[numpy_build_log_4.txt](https://github.com/numpy/numpy/files/10462992/numpy_build_log_4.txt)

**Comment by sprasad14** [comment]
@andyfaff   I understand it could be an issue with buildroot. I have contacted buildroot support team. Waiting for their response.

**Comment by rgommers** [comment]
If it's only `svml` sources that are the problem here, then you can set the `NPY_DISABLE_SVML` environment variable to get past that.

> The [documentation](https://numpy.org/devdocs/reference/simd/build-options.html#having-issues-with-avx512-features) has some hints about doing this, we may want to explicitly mention cross-compiling there. Since you are the best source for information about what works (once you get it going), please let use know how to improve documentation.

We're going to have proper cross-compiling support for the next release, and all the mechanisms will change. So doing this for the `numpy.distutils` build now is a bit wasteful of energy probably. So maybe best to just post a comment here with whatever ended up working.

**Comment by sprasad14** [comment]
@rgommers  Thanks a lot. setting the NPY_DISABLE_NVML=1 helped to resolve the issue.

**Comment by rgommers** [comment]
Thanks for confirming @sprasad14. 

I double checked, cross-compiling support is done correctly in the meson build for this case. The `setup.py` has multiple issues when cross-compiling, not worth messing with anymore now that there's a workaround. So let's close this.
