### ISSUE TITLE
Cygwin CI job fails with `f2py` errors

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#23070]
See for example [this CI log](https://github.com/numpy/numpy/actions/runs/3981840176/jobs/6825839167). Failures:

 =========================== short test summary info ============================
FAILED ../../f2py/tests/test_compile_function.py::test_f2py_init_compile[extra_args0]
FAILED ../../f2py/tests/test_compile_function.py::test_compile_from_strings[program test_f2py\nend program test_f2py0]
FAILED ../../f2py/tests/test_compile_function.py::test_compile_from_strings[program test_f2py\nend program test_f2py1]
FAILED ../../tests/test_public_api.py::test_import_lazy_import[testing] - Blo...
ERROR ../../f2py/tests/test_character.py::TestMiscCharacter::test_gh18684 - B...
ERROR ../../f2py/tests/test_character.py::TestMiscCharacter::test_gh6308 - Bl...
ERROR ../../f2py/tests/test_character.py::TestMiscCharacter::test_gh4519 - Bl...
ERROR ../../f2py/tests/test_character.py::TestMiscCharacter::test_gh3425 - Bl...
ERROR ../../f2py/tests/test_character.py::TestMiscCharacter::test_character_bc[new]
ERROR ../../f2py/tests/test_character.py::TestMiscCharacter::test_character_bc[old]
ERROR ../../f2py/tests/test_crackfortran.py::TestCrackFortran::test_gh2848 - ...
ERROR ../../f2py/tests/test_string.py::TestDocStringArguments::test_example
= 4 failed, 27912 passed, 203 skipped, 1306 deselected, 35 xfailed, 1 xpassed, 8 errors in 546.40s (0:09:06) 

Cc @DWesl have you seen this before? May be due to the 22 Jan Cygwin release, not sure.

**Comment by DWesl** [comment]
I've seen fork() failures a bunch; I was hoping the rebase script would fix those.  It might be that there's too many test modules imported and they're starting to overlap with each other.  I can try to create a list of compiled extension modules and rebase them withing the tests; I've made that work once, but have had problems the last few years (I think my first CI PR here might have included this, and removing it fixed some test problems).  The other option is to try to split the NumPy tests into two runs that each have few enough extension modules imported to avoid problems, or to use `pytest-forked` to run each of the tests that import a compiled extension module in a separate process.  I'll try moving the F2PY tests to a separate runtests call and see if that does anything.

The recent updates: https://cygwin.com/pipermail/cygwin-announce/2023-January/date.html
don't indicate many relevant things in the last few days (`getent` and `dash` might be relevant, but I don't think we use the rest), and the [Cygwin bugfix on Thursday](https://cygwin.com/pipermail/cygwin/2023-January/252900.html) seems to have had passing tests since the mirrors would have grabbed it.

**Comment by seberg** [comment]
I wonder a bit if vfork use might be safer than fork in cygwin, but it seems even newer Python's (which can use it) wouldn't since they guard using `__linux__`.

There isn't any chance that the rebase script started failing, I guess?  It would be nice if it was more verbose in CI to know that it did something.

**Comment by DWesl** [comment]
> I wonder a bit if vfork use might be safer than fork in cygwin, but it seems even newer Python's (which can use it) wouldn't since they guard using `__linux__`.

https://cygwin.com/cygwin-api/std-notes.html

> There isn't any chance that the rebase script started failing, I guess? It would be nice if it was more verbose in CI to know that it did something.

I tried adding more debug information in #23073; I'm still waiting on results.
