### ISSUE TITLE
Numpy 1.24.1 crash/reboot   Intel i9-10900KF 

### ISSUE THREAD

**Issue by jacopomoi** [numpy/numpy#23082]
I have a machine with the intel I9 and ubuntu 22.04.

I have set a conda environment for scientific production, but when i try in python 3.11:

```
import numpy as np

```
the machine crash and reboot like every time. I've tried to find something in journalctl but it doesn't seem to be a kernel related problem. I have also tried without conda environment and the same behavior is reproducible every time i call numpy.

So i have downgraded numpy several times and i found that 1.23.4 seems more stable, but anyway sometimes it crash.

The strange thing is that if i was successful to import numpy i can re-run the same script but if the time between the two calls is too tiny the system crash and reboot.
i have the sensation that is something related to openBLAS library, just to make a bet.

**Comment by seberg** [comment]
gh-22516 was experiencing a hard computer crash, it also includes a few settings to attempt to mitigate.  However, that issue was with load.  Nothing should just crash the machine, but if you suspect openblas is involved, the issue should give some things to try (i.e. reduce threads/pick a different kernel type).
Similar changes (picking other instructions) can be done within NumPy by setting an environment variable like `NPY_DISABLE_CPU_FEATURES="SSE3,SSSE3,SSE41,POPCNT,SSE42` (this has nothing to do with openblas) see also [here](https://numpy.org/devdocs/user/troubleshooting-importerror.html#segfaults-or-crashes).

I am not sure where to point at exactly, since even if buggy, NumPy shouldn't be able to crash your machine...

**Comment by mattip** [comment]
Is this running inside a VM or other emulation software?

**Comment by jacopomoi** [comment]
> Is this running inside a VM or other emulation software?

Nope, it is running on Ubuntu 22.04. Conda is just a virtual environment for various python packages.
I can provide more details on motherboard ecc. if is needed.

@seberg thank you! I will try some workaround and i'll communicate the results

**Comment by jacopomoi** [comment]
i updated the BIOS microcode and everything is REALLY FINE. I close this issue
