### ISSUE TITLE
BUG: Behavior changes when input changes from scalar np.float32 to ndarray of np.float32

### ISSUE THREAD

**Issue by REASY** [numpy/numpy#23085]
### Behavior changes when input changes from scalar np.float32 to ndarray of np.float32
Provided repro script produces the following output:
```
Python version: 3.9.15
numpy version: 1.23.4
two_pi:              6.283185307179586
num_cyl_rings:       2048
pixels_per_radian:   325.94932345220167

As primitive np.float32
x: 1.5715285539627075, typeof(x): <class 'numpy.float32'>
y: -7.423318862915039, typeof(y): <class 'numpy.float32'>
azimuth_angle       = 4.9210103193866175
proj_x         = 1603.9999843053708
proj_x_floored = 1603.0

As np.array of np.float32
x: [1.5715286], typeof(x): <class 'numpy.ndarray'>
y: [-7.423319], typeof(y): <class 'numpy.ndarray'>
azimuth_angle       = [4.9210105]
proj_x         = [1604.]
proj_x_floored = [1604.]
```

As you can see `proj_x_floored` changes from 1603 to 1604. To me this is very unexpected behavior. The type is the same, `numpy.float32`, the only difference whether it is passed as scalar or as np.ndarray

### Reproduce the code example:

```python
import struct
import numpy as np
import platform

horiz_angular_res = 0.087890625 * 2
two_pi = 2 * np.pi
num_cyl_rings = np.floor(360 / horiz_angular_res).astype(int)
pixels_per_radian = num_cyl_rings / two_pi

def hex_to_double(hex):
    bytes = bytearray.fromhex(hex.lstrip('0x').rstrip('L'))
    d = struct.unpack('>d', bytes)[0]
    return d
def calculate(x, y):
    print(f"x: {x}, typeof(x): {type(x)}")
    print(f"y: {y}, typeof(y): {type(y)}")
    azimuth_angle = np.arctan2(y, x)
    azimuth_angle += two_pi
    print(f"azimuth_angle       = {azimuth_angle}")

    proj_x = azimuth_angle * pixels_per_radian
    proj_x_floored = np.floor(proj_x)
    print(f"proj_x         = {proj_x}")
    print(f"proj_x_floored = {proj_x_floored}")

if __name__ == "__main__":
    print(f"Python version: {platform.python_version()}")
    print(f"numpy version: {np.version.version}")
    print(f"two_pi:              {two_pi}")
    print(f"num_cyl_rings:       {num_cyl_rings}")
    print(f"pixels_per_radian:   {pixels_per_radian}")
    print("")

    # Very precise way to define 1.5715285539627075
    x = hex_to_double("0x3ff924fb20000000")
    # Very precise way to define -7.423318862915039
    y = hex_to_double("0xc01db17a80000000")


    print("As primitive np.float32")
    calculate(np.float32(x), np.float32(y))
    print("")

    print("As np.array of np.float32")
    calculate(np.array([np.float32(x)], dtype=np.float32), np.array([np.float32(y)], dtype=np.float32))
    print("")
```

### Runtime information:

Python version: 3.9.15
numpy version: 1.23.4

**Comment by rkern** [comment]
`two_pi` and `pixels_per_radian` are regular Python `float`s (equivalent to `np.float64`). [numpy's type promotion logic](https://numpy.org/doc/stable/user/basics.ufuncs.html#type-casting-rules) is such that when arrays are mixed with arrays or scalars with scalars, the two arguments will be converted to the "larger" dtype with greater precision. So when you pass `float32` scalars, they will get combined with the `float` constants and promote up to `float64` and do arithmetic at that higher precision.

However, when arrays are combined with scalars, the scalar is just converted to the dtype of the array (at least when both are floating point types; other things happen when integers are combined with floats). This is because one typically uses `float32` in large arrays to save space, while it can be incredibly inconvenient to cast all of the scalars down to `float32`. Keeping `float32` arrays as `float32` would be nearly impossible as they work their way through most code. It's a pragmatic compromise.

[These rules are under revision](https://numpy.org/neps/nep-0050-scalar-promotion.html) and are moving towards making the `numpy_scalar+python_scalar` behavior more consistent with the `array+python_scalar` behavior. Namely, in `proj_x = azimuth_angle * pixels_per_radian`, where `azimuth_angle` is a `float32` scalar or array and `pixels_per_radian` is a plain Python `float`, the result will follow the numpy object's explicit dtype `float32` (whether it is a scalar or array) even though the Python `float` is equivalent to a `float64`. This preserves the robustness of `float32` arrays while making the behavior of explicit numpy scalars more consistent with arrays.

Since the code is exhibit documented-and-designed behavior and the requested different behavior is on its way, I am going to go ahead and close this.
