### ISSUE TITLE
BUG: Empty array broadcast rules

### ISSUE THREAD

**Issue by AndPuQing** [numpy/numpy#23100]
### Steps to reproduce:

Hello, I am trying examples as:

```python
import numpy as np
x1 = np.array([]).reshape([0])
x2 = np.array([]).reshape([0, 0, 1])
print((x1-x2).shape)  # (0, 0, 0)

x1 = np.array([]).reshape([0])
x2 = np.array([]).reshape([0, 1, 1])
print((x1-x2).shape)  # (0, 1, 0)

x1 = np.array([]).reshape([0, 0])
x2 = np.array([]).reshape([0, 1, 1])
print((x1-x2).shape)  # (0, 0, 0)
```

The above case does not seem to conform to the description in the [general-broadcasting-rules](https://numpy.org/devdocs/user/basics.broadcasting.html#general-broadcasting-rules).I don't know if this is a bug.

So is there any relevant discussion or documentation about empty broadcast rules?

### Additional information:

- numpy version: 1.23.2

**Comment by class255** [comment]
In my opinion, your examples follow the broadcasting rules well.
let
`sh1 = (       0,)`
`sh2 = (0, 0, 1)`
First, since `sh1.ndim` is smaller than `sh2.ndim`, the broadcasting process appends (0,0) to (0,) at the font: then `sh1 = (0, 0, 0)`
Next, for each axis with `sh1[axis]==n and n != n` and `sh2[axis]==1`, the broadcasting process changes as `sh2[axis]=n`.
`0` is also a multiplier of `1`, so `n` can be `0`. Then we finally get the broadcasted shape `(0, 0, 0)`

For nother examples,

sh1 = (       0,) -> (0, 1, 0)
sh2 = (0, 1, 1) -> (0, 1, 1)
since `sh1[2] != 1 and sh2[2] == 1`, do `sh2[2] = sh1[2]` then the final shape is `(0, 1, 0)`

sh1 = (    0, 0) -> (0, 0, 0)
sh2 = (0, 1, 1) -> (0, 1, 1)
since `sh1[axis] != 1 and sh2[axis] == 1` for `axis in [1, 2]`, do `sh2[axis] = sh1[axis]` then the final shape is `(0, 0, 0)`

**Comment by rkern** [comment]
Minor correction: broadcasting prepends `1`s to the shorter shape, never `0`s. So the three pairs of broadcasted shapes are

```
sh1 = (1, 1, 0)
sh2 = (0, 0, 1)

sh1 = (1, 1, 0)
sh2 = (0, 1, 1)

sh1 = (1, 0, 0)
sh2 = (0, 1, 1)
```

The observed results follow from that expansion.
