### ISSUE TITLE
DOC: Add N-dimensional array example to argmax and other similar functions

### ISSUE THREAD

**Issue by pmvz** [numpy/numpy#23162]
### Issue with current documentation:

There is very little information on how to find the index of the maximum value for each (N-1)-dimensional array in an N-dimensional array. This is for example useful when wanting to find the position of the brightest pixel for each image in a sequence of images stored as a 3D array.

### Idea or request for content:

This is solved by first reshaping the array to a 2D array, using `np.argmax` with `axis=1` and unravelling the indices to retrieve the position of the elements. I think this situation is common and useful enough to be added as an example to the relevant functions in the following way:

```python
>>> x = np.arange(2*2*3).reshape(2,2,3) % 7
>>> x
array([[[0, 1, 2],
        [3, 4, 5]],
       [[6, 0, 1],
        [2, 3, 4]]])
>>> x_2d = np.reshape(x, (x.shape[0], -1))
>>> indices_2d = np.argmax(x_2d, axis=1)
>>> indices_2d
array([5, 0])
>>> np.unravel_index(indices_2d, x.shape[1:])
(array([1, 0]), array([2, 0]))
```
This result means that the maximum value in `x[0]` is `x[0,1,2]` and in `x[1]` is `x[1,0,0]`.

I can provide a pull request, but I wanted to test the waters first.

**Comment by Mukulikaa** [comment]
Hi, @pmvz. Thanks for your suggestion! Since examples in the function docstrings are usually kept specific to that function, I think this use case would be a good addition to [How to index ndarrays](https://numpy.org/devdocs/user/how-to-index.html). Putting it in a how-to doc allows you to give just enough context for the example and makes it more visible to users as well.

Please feel free to reach out if you need any help!

**Comment by InessaPawson** [comment]
I'm closing this issue as it was addressed by https://github.com/numpy/numpy/pull/23167.
