### ISSUE TITLE
BUG: Casting a NaN in an array to an int doesn't raise a warning

### ISSUE THREAD

**Issue by CompRhys** [numpy/numpy#23166]
### Describe the issue:

Casting a NaN in an array to an int doesn't raise a warning. Raising a warning in this case may aid with debugging code not functioning as intended.

### Reproduce the code example:

```python
>>> np.array([1, np.nan]).astype(int)
array([                   1, -9223372036854775808])
```

### Runtime information:

Python 3.10.8 (main, Nov 24 2022, 08:09:04) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.23.5
3.10.8 (main, Nov 24 2022, 08:09:04) [Clang 14.0.6 ]

### Context for the issue:

In a GA I am developing I encounter a stochastic bug that if I sampled for too long I would get zero like vector suggested which in turn would create NaNs. It took longer than expected to find the source of this error as it happened very far upstream from the place the code later crashed. A warning when casting NaNs would have allowed me to identify the source of the problem much more quickly.

**Comment by seberg** [comment]
Just to note, unfortunately (due to how compilers do this), the warnings are currently not always reliable for out-of-bounds values (basically, you may be getting "correct" integer overflow behavior instead without a warning).  I believe we may have an issue about it, but if not, happy to reopen!

(This is complicated, because compilers optimize casts to behave like `arr.astype(np.int64).astype(np.int32)` effectively, and we never warn for out-of-bounds for int to int casts)
