### ISSUE TITLE
BUG: np.copyto() fails silently with slices

### ISSUE THREAD

**Issue by nrkarp** [numpy/numpy#23242]
### Describe the issue:

np.copyto() does not appear to support slicing. No problem if that's the design decision, but it should then throw a warning if slices are supplied as inputs.

Appears much like Issue #11623, which was closed with a brief explanation about assigning to temporary arrays. I have no doubt that that answer is technically correct, but to someone who is not intimate with numpy's source code it's not obvious why copyto() shouldn't be able to do what "A[my_slice] = B[my_slice]" does.

### Reproduce the code example:

```python
import numpy as np

A = np.arange(16).reshape(8, 2)
B = np.ones((8, 2), dtype=int)
my_slice = [1, 3, 5]
np.copyto(A[my_slice], B[my_slice])

A  # remains unchanged by np.copyto()
```

### Error message:

```shell
(There is no error message: that is the problem.)
```

### Runtime information:

import sys, numpy; print(numpy.__version__); print(sys.version)
1.22.3
3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0]

### Context for the issue:

This no longer affects my work: there are many workarounds. But it took many, many hours of debugging to figure out why my code was failing, since numpy is normally pretty good at complaining when it can't handle inputs.

**Comment by mattip** [comment]
There are a few things going on here, it is confusing to mash them all into one command. Let's try to take it apart:
```
Aslice = A[my_slice]    # uses advanced indexing, creates a copy
Bslice = B[my_slice]    # uses advancde indexing, creates a copy
np.copyto(Aslice, Bslice)
```

Since you are using advanced indexing, Aslice and Bslice will not refer to the original data, rather they will copy. This is fully described in the [indexing howto](https://numpy.org/devdocs/user/basics.indexing.html#advanced-indexing) . So by the time you call `np.copyto`, the arguments already do not reference the original arrays. The information that you wish to copy into A is not available to `np.copyto`.

If you really wish to copy the data, you must be sure to use simple indexing, like:
`np.copyto(A[1:6:2, :], B[1:6:2, :])`.

**Comment by nrkarp** [comment]
OK, that makes sense -- thank you for taking the time to explain my error so clearly.
