### ISSUE TITLE
ENH: int128 and uint128

### ISSUE THREAD

**Issue by NavisGames** [numpy/numpy#23243]
### Proposed new feature or change:

Hello. i want to be able to have a bigger number than uint64, now im  thinking is there a way to add an uint128 and int128 to NumPy?

**Comment by rgommers** [comment]
Hi @NavisGames, there's a new API to make it easier to define your own dtypes. There are examples in https://github.com/numpy/numpy-user-dtypes to get you started.

I'll close this issue, because we won't be adding these dtypes to numpy itself. However, if you do go down the route of creating your own, questions on that repo are of course welcome.

**Comment by 2sn** [comment]
I find it very unfortunate for Numpy to not fully support (the rather short list of) Fortran data types such as 16 byte integer and floats.  It makes Numpy even unsuitable for some numerical applications, e.g., analysing output from high-precision calculations, e.g., in dynamics (e.g., long-term evolution of planetary systems on secular time scales).  You recommend to dump Python/Numpy and switch to Julia?

**Comment by rgommers** [comment]
@2sn I'll note that there was significant progress on a quadruple-precision dtype recently: https://labs.quansight.org/blog/numpy-quaddtype-blog

If you're interested in helping this forward or providing a nontrivial use case, I suspect that @SwayamInSync and @ngoldbaum will be happy to collaborate.

**Comment by 2sn** [comment]
@rgommers Thanks.

For me, use cases are 
- being able to read data files from Fortran that use 16 byte floats.  Some benchmark codes use that to determine the effect of numerical precision.  Also see next point.  The data files of these can currently not be read using NumPy.
- use 16 byte float for higher precision in numerical applications (in my case, some astrophysical problems do have a very large dynamical range, so use of 8 by floats fails - e.g., timescale of evolution of star going from billions of years to fractions of milliseconds when they explode as supernova)
- high-precision calculation in dynamics (butterfly effect).  These may run for many billion or trillion of steps.
- f2py integration would be needed; that would require an enhancement as there as it seems float*16 is not covered by default C type mapping.  (Otherwise this would need to be patched in bad way using raw memory operations.)
- int128 I would use for flag fields, IDs, etc., (where I currently am about to hit the limit of int64)

**Comment by SwayamInSync** [comment]
Hi @2sn thanks for the input
As @rgommers mentioned that we have an experimental cross-platform float-128 (backed by sleef) and we did test it on some of the applications, you can read more about it in the mentioned blog-post. Given its currently experimental so some operations are not supported yet (like matmul) so yeah feedbacks are always welcome.
For f2py as far I know sleef does not have any fortran bindings yet (rust and julia are supported) but it can be used via ISO_C_BINDING in fortran

**Comment by 2sn** [comment]
@SwayamInSync I am not sure how this could be used in `f2py`.  It would need to recognise the data type to wrap it.  The only way to get around that at this time my be to do low-level raw data transfer in Fortran to a type supported by f2py, and the map raw data into a numpy array on the python side?  Worse things have been done (by me).  It is, of course, great to have 128 bit support available at all. and I hope the numpy core developers can be convinced to put it into the core library in the long run.  I fail to understand why this would not be on the top of the priority list for a numerical package.
