### ISSUE TITLE
BUG: clearing of array data too aggressive after gh-22924

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#23277]
### Describe the issue:

#22924 introduced failures in astropy (and likely in pandas). It is almost certainly to do with zero-length object dtype arrays; pure numpy example below.

### Reproduce the code example:

```python
import numpy as np
np.recarray((0,), dtype="O") 
# rec.array([],
#           dtype=|V8)
exit()
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Internal error, tried to fetch clear function for the user dtype '' without fields or subarray (legacy support).
```

### Runtime information:

1.25.0.dev0+802.g5f04e748b
3.11.1 (main, Dec 31 2022, 10:23:59) [GCC 12.2.0]

### Context for the issue:

See https://github.com/numpy/numpy/pull/22924#issuecomment-1444854769 and below.

**Comment by pllim** [comment]
Thanks for investigating! 🙇‍♀️

**Comment by seberg** [comment]
Thanks, didn't realize I went into that branch here.  I guess the point is voids without fields that still have `dtype.hasobject` set (due to view).  That last thing is more of a hack than anything, but a hack it shall remain, and replacing the error with a no-op should be OK (at least for our void).

It seems like pandas probably hits something else unfortunately.
