### ISSUE TITLE
Make SupportsDtype public

### ISSUE THREAD

**Issue by headtr1ck** [numpy/numpy#23308]
### Proposed new feature or change:

It would be nice if `numpy._typing._SupportsDType` would be a public interface, i.e. exposed as `numpy.typing.SupportsDtype`, such that other projects can use it in their type definitions.

**Comment by charris** [comment]
@BvB93 Thoughts?

**Comment by BvB93** [comment]
I must say that I'm somewhat lukewarm to the suggestion. 

The `_SupportsDType` protocol is rather small and minimalistic one (with all types referenced therein being public: [link](https://github.com/numpy/numpy/blob/857c64a95339bd937fbcc5398246fd2dcf78f3ab/numpy/_typing/_dtype_like.py#L80-L84)), combined with the fact that protocols following a structural rather than nominal subtyping hierarchy means that anyone can define their `SupportsDType` protocol and, as far as type checkers are concerned, it will be completely indistinguishable from our own definition.

If there's significant demand for it then it'd be another story, though thus far I more so had the impression that it's just another niche protocol used internally in NumPy.

**Comment by headtr1ck** [comment]
Now that I think about it more I have to say that I agree with this conclusion.

This rather minimalistic protocol can be easily copied and will be indistinguishable from numpys definition.

The only benefit would be that the definition might change in the future, but given the simplicity it's first of all unlikely and second eazy to update third Partys definition.
