### ISSUE TITLE
Is .github/workflows/docker.yml still a thing?

### ISSUE THREAD

**Issue by charris** [numpy/numpy#23334]
The last time `docker.yml` ran was five months ago in a backport to 1.23. It is very similar to `gitpod.yml`, which I suspect is a replacement. If it is no longer used, we should remove it. @trallard Thoughts?

**Comment by rgommers** [comment]
It should be a thing, but it only runs when we change dependencies (that's why it triggers on `path: environment.yml`). It sets up a base environment with dependencies. The `gitpod.yml` job build `numpy` itself, so has to run much more often.

**Comment by trallard** [comment]
Correct, this should be a thing since we build a base image first (only on changes to `environment.yml` and then the Gitpod one more frequently. 

Though the base image has not been built in a while, even though there have been changes to the env file recently, can we mark this as a bug, and I can have a look at why this is not working as expected this week?
(this issue's title might also need updating)

**Comment by rgommers** [comment]
We decided to remove support for Gitpod (and Docker Hub), so I'll clean this up and then it'll no longer be a thing. PR coming; I'll close this already.
