### ISSUE TITLE
DOC: Clarify usage of the np alias for numpy

### ISSUE THREAD

**Issue by mdehoon** [numpy/numpy#23373]
### Issue with current documentation:

The NumPy user guide says

"We shorten the imported name to `np` for better readability of code using NumPy. This is a widely adopted convention that you should follow so that anyone working with your code can easily understand it."

This can be interpreted as

- If you use an alias for `numpy`, you should use `np`.

or as

- You should always use an alias for `numpy`, and the alias should be `np`.

If it's the latter, users may feel that this is at odds with the "explicit is better than implicit" rule in Python, as `numpy` is more explicit than `np`. In any case, it would be good to clarify what is meant here.

**Comment by MatteoRaso** [comment]
> You should always use an alias for numpy, and the alias should be np.

I'm pretty sure that this is what the guide meant, but this isn't a rule that the user absolutely has to follow, just a good recommendation.

**Comment by seberg** [comment]
As Matteo says, I would say it is a suggestion/recommendation, but the first part is more important:  if you use an alias, use `np`.

I don't think it is at odds with "explicit is better than implicit" unless you work in an area where numpy is used rarely (i.e. not well known).  And if that is the case and others in the area are likely to not recognize `np`, then yes, maybe just stick with `numpy`.

Not sure we need to clarify this though?  I am comfortable with it being a bit fuzzy, if you don't like abbreviating, its fine if you don't.  If you use numpy a lot every day, you might just start to abbreviate quickly :).

**Comment by rkern** [comment]
If you are importing and using numpy APIs in your documentation, use `np`. Your users will be users of numpy and will need to get familiar with the alias convention sooner or later as they will encounter it frequently in the ecosystem.

If numpy were just used locally as a mere implementation detail inside of one module (e.g. wrangling image data in an otherwise non-numerical application), then that's where someone might forgo the alias.

**Comment by seberg** [comment]
Yeah, I suppose it would be fair to just strengthen it to be a clearer general recommendation to use `np` (there are cases where it probably makes sense to use `numpy`, but they may be limited enough).  That said, I am just as happy with how it is, even if it is a bit fuzzy.

**Comment by Mike-gag** [comment]
would "we strongly recommend to those familiar with aliases to use np as the alias" be okay? The full message would look something like this:

_"We shorten the imported name to np for better readability of code using NumPy. This is a widely adopted convention that you should follow so that anyone working with your code can easily understand it.We strongly recommend to those familiar with aliases to use np as the alias"_

I'd like to make the change

**Comment by seberg** [comment]
Thanks for the suggestion please do go ahead and make a PR to suggest a change.  I am not sure about the exact proposal, to me it feels the user is familiar with aliases (if not, they just learned :)).
One thought: maybe we can tweak the sentences a bit so that we can insert (in the sentence or as a new one) something along "we recommend to always use `import numpy as np`"?

**Comment by MatteoRaso** [comment]
> sat down now to do it, where exactly can i find the phrase in question?

I'm not sure if you use Linux, but if you do, `grep` is great for finding obscure files based on keywords.

https://github.com/numpy/numpy/blob/main/doc/source/user/absolute_beginners.rst
