### ISSUE TITLE
ENH: Finding Eigenvectors by Eigenvalues

### ISSUE THREAD

**Issue by metroproxyn** [numpy/numpy#23446]
### Proposed new feature or change:

For problems like this one:
<img width="634" alt="Screenshot 2023-03-24 at 4 21 35 PM" src="https://user-images.githubusercontent.com/39808040/227520245-13af85d9-6f4a-4821-93cf-77a4cb9b69f0.png">

This is also related with characteristic polynomial. Is there a reason to create methods for calculating characteristic polynomial and eigenvectors by eigenvalues? As far as I know, _linalg.eig_ does not provide this possibility.
Maybe I can try to implement it.

**Comment by charris** [comment]
Inverse iteration is the usual method for this. There can be problems when the eigenvalues have multiplicity greater than one.

**Comment by Adesoji1** [comment]
@metroproxyn @charris 

Do this below using numpy version 1.23.3

```
import numpy as np

# Define your matrices A and B
A = np.array([[4, 1], [2, 3]]) 
B = np.array([[3, 1], [1, 2]]) 

# Calculate the product of A and B
AB = np.dot(A, B)

# Calculate the eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(AB)

print("Eigenvalues: ", eigvals)
print("Eigenvectors: \n", eigvecs)

Result

Eigenvalues:  [18.26208735  2.73791265]
Eigenvectors: 
 [[ 0.75182561 -0.50473582]
 [ 0.659362    0.86327385]]


# Find the index of the desired eigenvalues in the list of eigenvalues
index_v1 = np.where(np.isclose(eigvals, 18.26208735))[0][0]  # Replace 18.26208735 with your actual eigenvalue
index_v2 = np.where(np.isclose(eigvals, 2.73791265))[0][0]  # Replace 2.73791265 with your actual eigenvalue

# Select the corresponding eigenvectors
v1 = eigvecs[:, index_v1]
v2 = eigvecs[:, index_v2]

print("v1-->", v1)
print("v2-->", v2)

v1--> [0.75182561 0.659362  ]
v2--> [-0.50473582  0.86327385]

```

The eigenvalues and eigenvectors are inherent properties of a matrix and are calculated based on the contents of the matrix. If you want to get whole number eigenvectors for the product of two matrices, you would need to carefully select your input matrices A and B such that their product gives you the desired eigenvalues and eigenvectors.

That being said, it's not easy to construct matrices A and B with specific eigenvectors for their product because the eigenvalues and eigenvectors of A.B do not directly relate to the eigenvalues and eigenvectors of A and B.

However, If you want to get the eigenvalues and eigenvectors for a single matrix with integer eigenvectors, you can use a diagonal matrix, where the diagonal values are the eigenvalues, and the eigenvectors are the standard basis vectors.

**Comment by mattip** [comment]
@Adesoji1 while your comment may be correct as a stand-alone commentary, it does not relate to the real question here: should NumPy provide a way to get eigenvectors from eigenvalues. Sure, you can get both from `np.linalg.eig`, but I don't tink that was the intent of the original question.

**Comment by Adesoji1** [comment]
@mattip I don't think that was the intent of the original question. What is it?

**Comment by mattip** [comment]
> Is there a reason to create methods for calculating characteristic polynomial and eigenvectors by eigenvalues? As far as I know, `linalg.eig` does not provide this possibility. Maybe I can try to implement it.

So the question is "is it worthwhile to submit a PR to implement a function that takes eigenvalues as input and creates characteristic polynomial and eigenvectors as output?"

**Comment by goblegrayson** [comment]
Hi @mattip, I'd like to have a go at implementing this function if there's no disagreement!

**Comment by rkern** [comment]
There is disagreement. No one has cited an actual use case. The OP posted a screenshot of a quiz, presumably from an introductory linear algebra course testing the student's skill in manually doing operations on hand-crafted, super-low-dimensional examples, which is not a use case for numpy.

If we did want some kind of inverse iteration implementation, it would probably be for `scipy.sparse` for implicitly-defined linear operators, not the explicit dense matrices that `np.linalg` handles.

I think I'm going to close this issue as I think it's attracting more attention than it's worth.
