### ISSUE TITLE
BUG: Insonsistent behaviour of NaNs in sets

### ISSUE THREAD

**Issue by atrejut** [numpy/numpy#23609]
### Describe the issue:

Converting a list of three `np.nan`s into a set returns a set with one element.
Converting a `np.array` with three `np.nan`s into a set returns a set with three elements.

Given that NaNs compare as unequal, I think either behaviour is sort of ok for me -- but the inconsistency seems odd?

### Reproduce the code example:

```python
import numpy as np
set([np.nan, np.nan, np.nan])  # returns {nan}
set(np.array([np.nan, np.nan, np.nan]))  # returns {nan, nan, nan}
```

### Runtime information:

1.22.4
3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:28:27)
[Clang 11.1.0 ]

**Comment by seberg** [comment]
This is a known Python language issue and not a NumPy issue.  We could try to return always the same NaN singleton, but `float("nan")` also always returns a new value...  The reason is that for `NaN` the `==` operator has by definition untypical behavior (always False) that leads to NaNs fundamentally being incompatible with sets.

**Comment by atrejut** [comment]
thanks for the explanation :)
