### ISSUE TITLE
BUG: Cannot run certain tests due to error importing numpy: you should not try to import numpy from its source directory

### ISSUE THREAD

**Issue by Sarah-Yifei-Wang** [numpy/numpy#23618]
### Describe the issue:

I noticed one test failed from the main branch. I was trying to debug the failed test. However, I got the error message stating "Error importing numpy: you should not try to import numpy from 

its source directory; please exit the numpy source tree, and relaunch your Python interpreter from there."

I used environment.yml to set up my virtual environment. So I think package numbers should not be the problem.

### Reproduce the code example:

```python
conda env create -f environment.yml
conda activate numpy-dev
Click Run test_umath.py -> Launching pytest with arguments test_umath.py::TestComplexFunctions::test_loss_of_precision --no-header --no-summary -q in /Users/sarahwang688/PycharmProjects/numpy_project/numpy/numpy/core/tests
```

### Error message:

```shell
ImportError while loading conftest '/Users/sarahwang688/PycharmProjects/numpy_project/numpy/numpy/conftest.py'.
../../__init__.py:130: in <module>
    raise ImportError(msg) from e
E   ImportError: Error importing numpy: you should not try to import numpy from
E           its source directory; please exit the numpy source tree, and relaunch
E           your python interpreter from there.
```

### Runtime information:

numpy: 1.24.2
sys.version: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:42:20)

**Comment by rossbar** [comment]
This is not particular to numpy, but is a general feature of Python packages. For NumPy specifically, some solutions include:
 1. Use editable installs (i.e. `pip install -e`)
 2. Use the `--pyargs` flag of `pytest` to run the tests on the installed package
 3. Use the `runtests.py` helper script to launch the tests.

Option 3 is recommended, though it likely won't integrate well with your IDE which seems to be where the error originates. You might want to investigate option 2 if you want to get things working with your IDE. Option 1 is generally not recommended, but will work (though it probably doesn't fit your use case w/ conda).

Hoepfully this helps! I will close this since it's anything specific to numpy.
