### ISSUE TITLE
Supposedly symmetric matrix isn't actually symmetric

### ISSUE THREAD

**Issue by kasparthommen** [numpy/numpy#23672]
### Describe the issue:

A symmetric matrix (by construction) minus its own transpose should yield a zero matrix, but it produces a matrix with non-zero entries.

### Reproduce the code example:

```python
import numpy as np

f = 0.9543045982971616
v = np.array([[43.718971769528025, 43.71898318065794]]).T
X = f * v @ v.T  # this should be symmetric
print(X - X.T)   # but it's not
```

### Result:

```shell
[[ 0.00000000e+00  2.27373675e-13]
 [-2.27373675e-13  0.00000000e+00]]
```

### Runtime information:

1.23.5
3.11.2 | packaged by Anaconda, Inc. | (main, Mar 27 2023, 23:35:04) [MSC v.1916 64 bit (AMD64)]

### Context for the issue:

A similar piece of logic is part of the recursive least squares (RLS) algorithm. Unfortunately, because of the above issue, a upposedly symmetric matrix turns non-symmetric, and those errors start accumulating, making the overall algorithm unstable.

**Comment by rkern** [comment]
There are many places in real, infinite-precision arithmetic where reordering operations has no effect. When real arithmetic is reduced to floating point arithmetic for computations, rounding happens on those operations and thus you get different results depending on the ordering. This is a fundamental fact of life for numerical computing.

In this case, you can change the ordering to get the result that you want. Note that `*` and `@` have the same binding priority, so `f * v @ v.T` is done left-to-right; i.e. `X = (f * v) @ v.T`. The scalar multiplication introduces some rounding error making the outer product no longer symmetric. You can reorder the computation to do the outer product first `X = f * (v @ v.T)` where, since the entries of `v` are the same, this is symmetric by construction, even in floating point arithmetic.

Sometimes you can't just change the ordering, and you will have to code your algorithms to be tolerant of this error (e.g. forcing symmetrization occasionally). The field of study that deals with the coding of algorithms that deal with this kind of numerical error is called numerical analysis. You will need to become familiar with some of its basic principles if you are running into problems of accumulating errors. Unfortunately, there is no way to escape this.

**Comment by kasparthommen** [comment]
Thanks  @rkern for the explanation, that makes perfect sense. I will pay more attention to operator binding priority in future!
