### ISSUE TITLE
BUG: f2py is failing on 32-bit windows on main

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#23675]
I am seeing 6 failures on a merge to main in f2py on 32-bit windows in [this run](https://dev.azure.com/numpy/numpy/_build/results?buildId=29243&view=logs&j=d02055d6-a30d-5402-19aa-ca2310eeee52&t=3b8a6fc4-0b0a-5f32-7dd9-04a675f63363&l=1692) and [this run](https://dev.azure.com/numpy/numpy/_build/results?buildId=29241&view=logs&j=d02055d6-a30d-5402-19aa-ca2310eeee52&t=3b8a6fc4-0b0a-5f32-7dd9-04a675f63363&l=1873). The actual compilation error seems to be swallowed, or lost somewhere in the verbose log. So there are two problems:
- where is stderr going: did we change something in the logging?
- why did the tests start failing?

**Comment by charris** [comment]
I think a bunch of these tests used to be skipped, see lines near 209 in https://tinyurl.com/445emzjt.

**Comment by charris** [comment]
You can see a summary of the failing tests at https://dev.azure.com/numpy/numpy/_test/analytics?definitionId=5&contextType=build. They are all in two files, `test_compile_function.py` and `test_compile_function.py`

**Comment by charris** [comment]
Reopened, the 32 bit wheels for Windows are failing.

**Comment by charris** [comment]
@rgommers Can meson build 32 bit wheels for Windows? If not, do we want to stop supporting them in 1.25?

**Comment by charris** [comment]
Looks like the proper workaround is at https://github.com/r-windows/install-rtools. Rtools 4.0 stopped being installed by default in github actions in April.

**Comment by charris** [comment]
@andyfaff The workaround might interest you.

**Comment by rgommers** [comment]
> @rgommers Can meson build 32 bit wheels for Windows? If not, do we want to stop supporting them in 1.25?

Meson itself has no problem with 32-bit Windows. What is needed is a set of compatible compilers. The problem there is, of course, Fortran. For NumPy we can easily do 32-bit builds without Fortran with MSVC (or Clang-cl, or MinGW-w64 - any reasonable C/C++ compiler works). For Fortran we still do not have a 32-bit compiler that does the job. A full mingw-w64 based build is close, but we haven't really tried it much yet.

The other question of course is if 32-bit Windows wheels are still worth supporting. My sense is that for now it's good to upload them, but longer term of course it's a dead end and we need the remaining users to move anyway if they want a complete working SciPy stack.

> EDIT: I note that the meson builds for Windows don't look to be tested with Fortran.

Yeah, there's a bunch of gaps like that, right now CI coverage is only such that it's unlikely that we break the build. We haven't aimed for completeness, since I don't want to have a double set of jobs for meson and setup.py

**Comment by mattip** [comment]
See also this [two year old thread](https://discuss.python.org/t/dropping-32-bit-packages) about dropping 32-bit windows builds for CPython. I revived the thread with a link to this issue.
