### ISSUE TITLE
DOC: good-first-issue label missing from issue labels

### ISSUE THREAD

**Issue by DuanBoomer** [numpy/numpy#23692]
### Idea or request for content:

Please add a good-first-issue label.

**Comment by mattip** [comment]
Hi, and thanks for joining. We don't really have many issues that are "good-first-issue", we use the "sprintable" label instead. This was after we discovered that issues we marked as "good-first-issue" turned out to be way too complicated for first-timers to work on alone. If you are familiar with the intricacies of sphinx and numpydoc, you can take a look at the issues labeled "Documentation" as well. Please look at [this page](https://numpy.org/contribute/) for ways to contribute.

**Comment by DuanBoomer** [comment]
Thank you so much 🐶 for taking the time to reply to my issue and the clarification. I would surely look at the documentation labelled issue.
