### ISSUE TITLE
DOC: Document first argument to `numpy.typing.NDArray`

### ISSUE THREAD

**Issue by dstansby** [numpy/numpy#23722]
### Issue with current documentation:

`numpy.typing.NDArray` takes two arguments when used as a type hint: https://numpy.org/doc/1.21/reference/typing.html#numpy.typing.NDArray

```python
numpy.typing.NDArray = numpy.ndarray[typing.Any, numpy.dtype[+ScalarType]]
```

The second argument seems to be the `dtype` (but isn't documented explicitly), and I'm not sure what the first argument is. 

### Idea or request for content:

The type hint arguments should be clearly documented on both `numpy.ndarray` and `numpy.typing.NDArray`.

**Comment by BvB93** [comment]
Fair point, the example section does show a few examples that allude to the second parameter being bound to `np.generic`, but it's still rather vague and too open for interpretation. 

The first argument on the other hand? It's currently more of a placeholder slot for a shape-related type, introduced back when `np.ndarray` was made generic. The concern was that if this were to be introduced in two stages (_i.e._ first adding a dtype parameter and adding the shape parameter add a later date) it would result in some notable backwards compatibility issues due to the sudden appearance of an extra required generic parameter within existing annotations. In any case, the first parameter is currently more of an implementation detail and firmly falls into the category of "do not touch; leave it at `Any`".

**Comment by BvB93** [comment]
In any case, PRs are welcome here. The [`ndarray.__class_getitem__`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.__class_getitem__.html) documentation already mentions that `npt.NDArray` is parameterized w.r.t. `dtype.type`, so putting something similar in the `npt.NDArray` docs itself would already go a long way.

**Comment by ellaella12** [comment]
hi can i give this a go?

**Comment by Mukulikaa** [comment]
@ellaella12, you can work on any issues you like, without asking for permission.

**Comment by ellaella12** [comment]
Hi I have made a pr to add reference to dtype following `[ndarray.__class_getitem__](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.__class_getitem__.html) documentation
