### ISSUE TITLE
BUG: floating point errors with np.cos

### ISSUE THREAD

**Issue by neutrinoceros** [numpy/numpy#23773]
### Describe the issue:

#23695 affects the precision of `cos` (and presumably `sin`), in a way that may break downstream code: `np.cos(0) == 0.9999999999999999` on the dev branch. I've tested this on Linux and MacOS

Here's a real life example https://github.com/SAIL-Labs/AMICAL/blob/97dffe6671babdfc71ac830610c0b7b8c5093f25/amical/analysis/fitting.py#L54-L60

This function relies on `np.cos(0)` being exactly `1.0` because its job is to invalidate inclination angles that have `np.cos(angle) < 1.0`.

I'm aware this function is intrinsically sensitive to floating point errors (arguably it shouldn't) and I would be okay with having to fix the regression on the user side, but I thought I would first open a discussion here as I imagine this could affect many downstream packages.

### Reproduce the code example:

```python
import numpy as np
assert np.cos(0) == 1.0
```

### Error message:

```shell
AssertionError
```

### Runtime information:

1.25.0.dev0+1456.g0200e4a00
3.11.0 (main, Nov 13 2022, 10:50:04) [Clang 14.0.0 (clang-1400.0.29.202)]

**Comment by seberg** [comment]
The fun part is, that this was quite for off even before if a machine at AVX512 (typically one less ULP, but that if would be *randomly* wrong on such a machine in a range where it should round to 1!

The linked PR is the wrong one, that just fixes a small unrelated issue, gh-23399 is the relevant one and has more discussion, also ping @Mousius.

TBH, I would prefer higher precision around these special values, and that includes the old SVML fallback (which not super many users end up with anyway).  This is all very hard to make clear cut calls on though, since I also think a check like the one you said is dubious.

(I also am surprised that the functions are non-monotenous, TBH. For these fast vectorized algorithms at least, results fluctuate randomly by 1-2 ULPs in regions where they should be numerically constant.)

**Comment by neutrinoceros** [comment]
> The linked PR is the wrong one

For closure, I identified https://github.com/numpy/numpy/pull/23695 as the cause using `git bisect`, which lead to c43ae85bdd44174c0f2867adc85fe94cbc626873

**Comment by neutrinoceros** [comment]
#23399 indeed provides much more context, thank you !
Seeing that astropy and SciPy already adapted to the change and that, even on already released versions of numpy `np.sin(np.pi) != 0`, I'm all the more tempted to just handle it downstream.

**Comment by seberg** [comment]
I am not sure that `np.sin(np.pi) != 0` happened before in any context.  However `np.sin(np.pi+eps) != 0` did happen for sure, which isn't any better probably :).

**Comment by seberg** [comment]
The question is whether a pattern of a decent fraction of large scientific downstream packages noticing this (most will only test after the release), should worry us...

**Comment by neutrinoceros** [comment]
> I am not sure that np.sin(np.pi) != 0 happened before in any context.

I'm getting `1.2246467991473532e-16` with numpy 1.23.4 on macOS. This was also noted in https://github.com/numpy/numpy/pull/23399#issuecomment-1527638542

**Comment by rkern** [comment]
@bb-ssaxena99 It's more of a policy discussion, not a work item at this time. Check the `sprintable` label for issues that are better for new contributors to work on.

**Comment by seberg** [comment]
I guess the discussion may not be over, but for this specific issue it is (its precise in 1.25 for the moment and maybe its more likely we go the context manager opt-in route, or maybe not...).
