### ISSUE TITLE
BUG: TypeError with float128 operations and native int's >2^64

### ISSUE THREAD

**Issue by jorenham** [numpy/numpy#23783]
### Describe the issue:

Operations like add and multiply on float128 values and python integers larger 2^64 raise a TypeError, while this works correctly for the float64 and float32 dtypes. 

### Reproduce the code example:

```python
>>> import numpy as np

>>> np.float32(1e-16) * (1<<63)
922.3372192382812

>>> np.float64(1e-16) * (1<<63)
922.3372036854776

>>> np.float128(1e-16) * ((1<<63) - 1)
922.3372036854775614

>>> np.float128(1e-16) * (1<<63)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'numpy.float128' and 'int'
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'numpy.float128' and 'int'
```

### Runtime information:

```pycon
>>> sys.version
'3.11.3 (main, Apr  5 2023, 14:14:37) [GCC 11.3.0]'

>>> np.__version__
'1.24.3'

>>> np.show_runtime()
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Prescott',
  'filepath': '/home/joren/.local/lib/python3.11/site-packages/numpy.libs/libopenblas64_p-r0-15028c96.3.21.so',
  'internal_api': 'openblas',
  'num_threads': 32,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
```

### Context for the issue:

It doesn't matter whether e.g. `+` or `np.add` is used, nor does the order; the error is the same.

**Comment by Jay-sanjay** [comment]
Hello , Sir I am a fresher towards contributing for open source.
can you suggest me some beginner friendly issues

**Comment by seberg** [comment]
This is not an easy issue to work on.  It is effecitvely related to implementing [NEP 50](https://numpy.org/neps/nep-0050-scalar-promotion.html) and fixed by it.  The behavior is actually somewhat equivalent, because these out-of-bounds values currently go to `object` dtype for the integer.
NumPy (indirectly) allows `float32/float64 + object` to work by casting to a Python float, this is not possible for longdouble (float128, but float128 is a misleading/incorrect name) since it would lose precision.

Note that certain operations on huge integers may get trickier with NEP 50 becoming the default (this one will just work).

Any comments on the proposed changes are appreciated, though!

**Comment by seberg** [comment]
As I mentioned above, this is fixed on main by NEP 50 implementation.
