### ISSUE TITLE
BUG: Inverse Being Calculated for a Non-Invertible Matrix.

### ISSUE THREAD

**Issue by TejoVK** [numpy/numpy#23793]
### Describe the issue:

I tried to find the inverse for a 3x3 singular matrix using the numpy library, and suprisingly numpy gives it's inverted matrix in return. On analyzing this issue further I came out with an error in the numpy.linalg.det() method, if given a singular matrix to this function it returns a non zero value which is small and close to zero, this results in the numpy.linalg.inv() function in generating an inverse for a singular matrix too.

### Reproduce the code example:

```python
import numpy as np
array = np.array([[2,4,6],[2,0,2],[6,8,14]])
print('the det of matrix: ',np.linalg.det(array))
print(array)
resultInverse= np.linalg.inv(array)
print(resultInverse)
```

### Runtime information:

![image](https://github.com/numpy/numpy/assets/98254482/22ff879e-0858-4af9-bb85-48bab39e1e45)

### Context for the issue:

![image](https://github.com/numpy/numpy/assets/98254482/e5f78e0e-3995-47b5-93e6-30aa4509f16e)

the det for the above matrix is given by:
2(0-16)-4(28-12)+6(16-0)=(-32-64+96) = 0

but numpy gives a different det close to 0. This thereby causes error in the inverse function:
Now if I use this code to find the inverse of the Rotation Matrices in case of robotic arms it wouls create a lot of confussion in determining the inverse/forward kinematics of it, being a non invertible matrix it cannot give it's inverse.
please look into this @mattip

**Comment by rkern** [comment]
Welcome to numerical computing with floating point arithmetic. One is not guaranteed to get exact answers even in contrived examples where the exact answer in real arithmetic is precisely on these edge cases. The results you get are pretty much in line with what we expect and are not bugs.

Instead of trying to test for precise non-invertibility, we instead look at things like the [condition number](https://en.wikipedia.org/wiki/Condition_number) with [`np.linalg.cond()`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.cond.html). If the condition number is too high, as it is here, then we know that the result of `inv()` will be unreliable. We rely on the condition number rather than precise non-invertibility is that even with _near_-non-invertibility, the inverse will still be unreliable. Testing the condition number catches all of these problems, not just the exact-non-invertible cases.
