### ISSUE TITLE
BUG: Rounding error

### ISSUE THREAD

**Issue by provinzio** [numpy/numpy#23870]
### Describe the issue:

The numpy round function returns a wrong number when rounding `9.90005` to 4 decimal places.

### Reproduce the code example:

```python
import numpy as np

# Python rounds correctly
round(9.90005, 4) = 9.9001

# Numpy returns wrong number
np.round(9.90005, 4) == np.round(np.float64("9.90005"), 4) == 9.9
```

### Runtime information:

Tested on different versions:

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.23.5
3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
```

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.3
3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
>>> print(numpy.show_runtime())
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'D:\\workspace\\tr10-standortguete\\.pyenv\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]
None
```

### Context for the issue:

The calculation is wrong. I cannot use np.round for my calculations and have to fall back to the python round function.

**Comment by provinzio** [comment]
I am currently upgrading my system to numpy 1.24.3 and will report back if this changes anything.

**Comment by provinzio** [comment]
Bug still occurs on latest release.

**Comment by rkern** [comment]
There's no bug. We deliberately choose a different implementation than the builtin `round()`, [as documented](https://numpy.org/doc/stable/reference/generated/numpy.around.html). Though I would argue that `9.9` is the more correct answer as both `np.around` and the builtin `round` claim to round to the nearest even in the 0.5 case rather than rounding up.

In any case, when we're dealing with rounding to decimal places in a binary representation, there are a number of edge cases where there are several different valid ways to do it that gives different answers. We picked one way and `round()` picked another. If your use case really does depend on a particular choice, consider if you actually need to use `Decimal`s instead of floats.
