### ISSUE TITLE
BUG: creating an integer scalar from a string does not warn about overflow

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#24066]
This behavior is deprecated:

```
in [3]: np.int32(2147483648)
<ipython-input-3-cd4bcbe47c5d>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2147483648 to int32 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.int32(2147483648)
Out[3]: -2147483648
```

But this doesn't warn and probably should for consistency:

```
In [4]: np.int32('2147483648')
Out[4]: -2147483648
```

**Comment by seberg** [comment]
Hmmmpf, I agree.  Maybe we can just disallow that completely (in sync or not in sync with the deprecation warning).

Maybe I just don't want to worry about syncing the two warnings up, but overflow in string conversion seems a lot worse to me (at least the other had known use-cases).  And it also seems like it should be very niche.

(But would want some :+1: on that, since it is jumping a deprecation mainly based on how niche something is.)
