### ISSUE TITLE
BUG: ufuncs with uint64 and python int error on anything other than 2^64-1

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#24106]
### Describe the issue:

Ufunc selection for `uint64` with a python integer seems to depend on the value of the integer in an illogical way, mostly because the cast from python int to numpy int gets done before the ufunc can tell which one is best.

### Reproduce the code example:

```python
import numpy as np
np.uint(1) & 0xffffffffffffffff
# 1
np.uint(1) & 0xfffffffffffffff
# TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Runtime information:

1.24.2
3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.2.0]

### Context for the issue:

I'm trying to write code that is agnostic to whether the input is a python int or a numpy array of `np.uint64`.

**Comment by seberg** [comment]
NEP 50 would force the Python int to `uint` here effectively making the above valid.  I want that in main soon, but it needs a few things still:
* It would be nice to change the scalar repr (because scalars become more important)
* We won't get all python side function behavior clean (more so for things like units) but may need a new helper for things like `np.select()` to figure out the correct `result_type` (`result_type` works, but is a bit hacky).
* Need to implement a solution for making `np.add(1, 2., dtype="int64")` fail because the Python `2.0` cannot be "same-kind" cast to the integer.

There is no regression here so I will not look into resolving it for a 1.25.x release.

**Comment by mhvk** [comment]
@seberg - ah, somehow I thought we already had NEP 50 for a few releases and this was a side effect!  Good to know I was totally wrong!  So, I'll close this and happily await NEP 50 -- feel free to ping me for reviews...
