### ISSUE TITLE
BUG: Numpy Typing does not recognize a deque as a valid input for np.max

### ISSUE THREAD

**Issue by chacabuco** [numpy/numpy#24265]
### Describe the issue:

When running mypy on the example code one gets the following message:

error: No overload variant matches argument type "deque[int]"  [call-overload]

Nonetheless, the code executes correctly. Should collections' deques be a valid input for both np.min and np.max?

When trying to convert a deque to a numpy array the conversions is successful; therefore, shouldn't deques be considered as array_like?

### Reproduce the code example:

```python
import numpy as np
from collections import deque

a = deque([0])
np.max(a)
```

### Error message:

```shell
error: No overload variant matches argument type "deque[int]"  [call-overload]
```

### Runtime information:

1.23.2
3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]

**Comment by BvB93** [comment]
The issue here stems from `deque` failing to properly implement the interface as specified by the `Sequence` abstract base class (which we rely on in our typing definition of array-like), the former lacking support for `slice`-based indexing. Loosening the `__getitem__` annotations down below via removal of the `slice`-based overload might be worth a shot here:
https://github.com/numpy/numpy/blob/7e806a1267a3712aa59e2ed60e2fce8e57ce0986/numpy/_typing/_nested_sequence.py#L65-L72
