### ISSUE TITLE
 Build Failure On Windows using meson.

### ISSUE THREAD

**Issue by Nitin-Gahlawat** [numpy/numpy#24317]
### Build Failure on Windows using meson.
**Summary:**
Build failure when attempting to compile the project on Windows platform.

**Description:**
Upon attempting to build the project on Windows using Visual Studio (v17.3.1), cpython(v3.0.0), python (3.10.4), meson (1.1.0) getting a build failure error.

**Environment:**
Operating System: Windows 10 
Build Tool: Visual Studio 2022(Version 17.3.1)
cpython: Version 3.0.0
python: Version 3.10.4
meson: Version 1.1.0

**Steps to Reproduce:**
1. Open developer command prompt.
2. Navigate to the NumPy Repository.
3. Run "meson setup builddir".

**Actual Result:**
The build process fails with the following error message:
_**meson.build:42:22: ERROR: <PythonExternalProgram 'python3' -> ['C:\\Program Files\\Meson\\meson.exe', 'runpython']> is not a valid python or it is missing distutils**_

**Additional Notes:**
- For building the project using meson we have to create the build directory using "meson setup builddir" command.

**Additional Resources:**
[Include links to external resources or documentation that may help to better understand the issue.]
https://mesonbuild.com/Tutorial.html
https://github.com/numpy/numpy/pull/24236

**Screenshot:**
**![numpy_fail](https://github.com/numpy/numpy/assets/101346709/f5462c41-fe1a-4d87-8fec-489dd07f92d5)**

**Comment by ngoldbaum** [comment]
Can you share the `meson_log.txt` file?

**Comment by ngoldbaum** [comment]
I would also try building with `pip`:

```
pip install -e .
```

**Comment by ngoldbaum** [comment]
The error at the end of the log indicates the actual problem
is this meson issue: https://github.com/mesonbuild/meson/issues/11689

I'm not sure offhand if that's made it into a meson release yet.

**Comment by eli-schwartz** [comment]
> I'm not sure offhand if that's made it into a meson release yet.

This bug report was opened with meson 1.1.0, and the fix for python_info.py in the MSI installer was in meson 1.2.0.

Note that you probably do NOT want to build numpy against the embedded python contained inside the PyInstaller-generated meson MSI installer. Using `'C:\\Program Files\\Meson\\meson.exe'` as the python to build modules against is probably not going to be of much use.

`pip install -e .` handles this fine because it writes out a machine file telling meson which python to build numpy for. The alternative is to `pip install meson` instead of using the MSI installer, since a meson that was installed with pip will fall back to the same python.

**Comment by rgommers** [comment]
We now depend on Meson >=1.2.99, so this should be fixed. I'll close this issue - please comment if something is still not working with latest `main`. Thanks all!
