### ISSUE TITLE
DOC: clarify if astype is meant to be called on numpy.ma.MaskedArray

### ISSUE THREAD

**Issue by natmokval** [numpy/numpy#24392]
### Issue with current documentation:

Seems like there is no mention of `astype` in the documentation (https://numpy.org/doc/stable/reference/routines.ma.html) for `Masked array operations`.
Is `astype` meant to be called on `numpy.ma.MaskedArray`?  When we call it the return type is typed to be `ndarray`, even though if we print it we see it's `numpy.ma.MaskedArray`.

This isn’t clear from the documentation (ver. 1.25) for `numpy.ma.MaskedArray.astype` (https://numpy.org/doc/stable/reference/generated/numpy.ma.MaskedArray.astype.html), but it looks exactly the same as doc for `numpy.ndarray.astype `(https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html).

Reproducible example(mypy 1.4.1):

```
import numpy as np

data = np.ma.MaskedArray([1,2,3], mask=[False, False, True])
reveal_type(data) 
# Revealed type is "numpy.ma.core.MaskedArray[Any, Any]"

reveal_type(data.astype('int64', copy=True)) 
# Revealed type is "numpy.ndarray[Any, numpy.dtype[Any]]"
```

### Idea or request for content:

Can it be more clear from the documentation is `astype` meant to be called on `numpy.ma.MaskedArray` or not?

**Comment by seberg** [comment]
Thanks, looks like a real issue, but a typing one only.  The returned value at runtime is a masked array.

**Comment by BvB93** [comment]
This is mostly a limitation introduced by the lack of higher order type variables, meaning the affected methods would have to be explicitly redeclared with the correct `ndarray` subclass as return type (yes, this affects all `ndarray` subclasses and extends to many other methods beyond `astype`). To put it simply: with aforementioned limitation this is a highly tedious and non-trivial task, especially since `MaskedArray` in general is largely unannotated.

**Comment by InessaPawson** [comment]
@natmokval @BvB93 @seberg  Since it’s a wontfix, I will close the issue.
