### ISSUE TITLE
BUG: Cumsum for float16 gives the wrong result

### ISSUE THREAD

**Issue by AlephAlpha** [numpy/numpy#24443]
### Describe the issue:

When the size of the input array is large, `cumsum` sometimes gives the wrong result.

### Reproduce the code example:

```python
import numpy as np

np.random.seed(1)
data = np.random.uniform(0,1,100000).astype(np.float16)
print("sum =", np.sum(data))
print("cumsum in float16 =", np.cumsum(data))
print("cumsum in float32 =", np.cumsum(data.astype(np.float32)))
```

### Error message:

```shell
sum = 49950.0
cumsum in float16 = [4.170e-01 1.137e+00 1.137e+00 ... 2.048e+03 2.048e+03 2.048e+03]
cumsum in float32 = [4.1699219e-01 1.1372070e+00 1.1373215e+00 ... 4.9920969e+04 4.9921535e+04
 4.9922148e+04]
```

### Runtime information:

1.21.5
3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

### Context for the issue:

The last term of the cumsum should be close to the sum.

**Comment by jakevdp** [comment]
This is an interesting question! However, I think this behavior expected due to normal float16 roundoff error. Observe the following:
```python
print(np.nextafter(np.float16(2048), np.float16(np.inf)))
# 2050.0
```
What this tells you is that in float16, the next representable number larger than `2048.0` is `2050.0`. All of the numbers in your array are between zero and one, so there's no way to bridge that gap, and `2048.0 + val` will round to `2048.0` for all values in your array.

If you want more accurate cumulative sums for numbers between zero and one, you'll have to use a floating point representation with more precision.

**Comment by Demetrio92** [comment]
@jakevdp @charris this is indeed a very interesting learning! 

However, for me it silently broke a package that was doing weighted quantiles on top of pandas. And took me quite a while to properly root-cause this.

Why do you think this behavior should not be a "bug"? E.g. I compute an `np.cumsum` and in some conditions get a ridiculously wrong answer. In my opinion, instead of bugging out like this `np.cumsum` should throw an error. 

I do not see how current behavior could be useful to anyone and why is it better than raising an error.

**Comment by jakevdp** [comment]
> I do not see how current behavior could be useful to anyone and why is it better than raising an error.

I'm curious how you'd imagine deciding when an error should be raised?

**Comment by Demetrio92** [comment]
Inaccuracy of floating point computation is generally accepted as it is usually in a margin of error that is not relevant to a task at hand. The result of `cumsum` due to a round-off error can easily go into magnitudes of what it should be without requiring the user to be working with astronomically large or small numbers that would trigger a reflex "i probably need a double precision for that". 

It also can easily be shown to be inconsistent. E.g. `numpy.cumsum(data)[-1] != numpy.sum(data)`. And, again, by a large margin that is not just accumulation of individual imprecisions.

Here is an example: 
```python
import numpy as np

N = 130_000_000
x_f32 = np.linspace(0, 10, num=N).astype(np.float32)
x_f64 = np.linspace(0, 10, num=N).astype(np.float64)

print(x_f32.cumsum()[-1]/x_f32.sum())  # 0.4129777
print(x_f64.cumsum()[-1]/x_f64.sum())  # 1.0000000000000002
```

I think here it is fairly obvious that `x_f32.cumsum()` should be raising an error. While in `x_f64` example I can totally justify the result with "every floating point operation will be subject to some inaccuracy".

We can also see that round-off error eventually leads to `numpy.cumsum()` plateauing, which is also inconsistent and can be easily checked: 

```python
print((np.diff(x_f32.cumsum()[-100:-1]) == 0).all() & (x_f32[-100:-1] != 0).any())  # True -- broken
print((np.diff(x_f64.cumsum()[-100:-1]) == 0).all() & (x_f64[-100:-1] != 0).any())  # False -- not broken
```

So, 
1. I could check `x_f32.cumsum()[-1]/x_f32.sum()` against some threshold. The latter would be quite tricky to define very generally, although, I'd argue for arrays above 1000 length, getting this ratio below 0.99 deserves a warning, and below 0.9 a straight out error. At least the user would become aware. 
2. I could check last `n_plateau_issue` entries and if it looks like we're experiencing a round-off-to-plateau phenomenon, throw. 
3. I understand that at some length of an array, the round-off to plateau will inevitably happen, unless the array is sparse. So, this could also trigger a warning. Again, 100 mil entries in fp32 are perfectly fine in if I do `sum`, `mean`, `std`, `max`, `diff` etc, but are absolutely not fine for `cumsum` and will almost certainly lead to a massive error. So, a warning is justified. 

Neither will cover all possible cases exhaustively. 1. depends a lot on magnitude and variance of values in the array, and regardless will suffer from sensitivity/specificity trade-off. 2. can easily coincide with the last values of the array being zero, but we can't simply scan the entire output for every plateau and cross-check it. 3. would unjustifiably warn for large but sparse arrays. 

No perfect solutions so far, but those are my initial proposals. For the weights re-normalization that I was debugging, I will certainly implement 1. I'd rather error out than return an arbitrarily inaccurate number.

**Comment by Demetrio92** [comment]
Was implementing the above checks, and figured that numpy has built-ins for handling floating point errors: https://numpy.org/devdocs/reference/routines.err.html

**Comment by Demetrio92** [comment]
More digging through docs and past PRs. Someone already broke their implementation of weighted percentiles in 2017. https://github.com/numpy/numpy/issues/9329
