### ISSUE TITLE
ENH: Introduce `inspection` module

### ISSUE THREAD

**Issue by mtsokol** [numpy/numpy#24474]
Parent issue https://github.com/numpy/numpy/issues/23999

Hi!
[NEP 52](https://numpy.org/neps/nep-0052-python-api-cleanup.html), that covers cleanup of the Python API, gives opportunity to simplify and reduce number of items present in the main namespace. 
One group of items available in `np.*`, that could be moved to a separate module, is:
```
- is_busday
- iscomplex
- iscomplexobj
- isfortran
- isreal
- isrealobj
- isscalar
- min_scalar_type
- datetime_data
```
They could be placed in a new `inspection` or `inspect` module (as a top namespace submodule, or inside `lib` module), as they all provide information about live objects or dtypes (analogously to Python's `inspect`). 
Items from the list could be then accessed with `np.lib.inspect.iscomplex(arr)`

Please share your feedback!

**Comment by rgommers** [comment]
Hmm, this group of functions isn't yet something I'd be excited about as a submodule - this is all very niche or legacy/obsolete.

I think there were other functions that where introspection-like, e.g. `byte_bounds` comes to mind (and IIRC there were at least a couple of others - one about memory overlap?). So my sense is that a module under `np.lib` may be useful. But we may need to think a bit more about what goes there.

**Comment by ngoldbaum** [comment]
I think this and #24166 are describing the same namespace, although @seberg's list and your list are disjoint.

I think `isreal`, `isrealobj`, `iscomplex`, `iscomplexobj` and `isfortran` all belong in the top-level namespace as-is, they're used extensively according to github search and I don't think there's a succinct way to spell them. Some of them are used less often than the others, but I think they all belong together.

`is_busday` is being deprecated and merged into numpy-financial as I understand, so it doesn't need to have a permanent place to live.

I think `min_scalar_type` and `datetime_data` could both be moved, although they both need to be public and have docs. `min_scalar_type` is nontrivial to implement, but `max_scalar_type` isn't, so that justifies removing the latter but not the former.

As always, the above is just my opinion and reading of github searches and might not align well with the opinions of more experienced maintainers.

**Comment by mtsokol** [comment]
> `is_busday` is being deprecated and merged into numpy-financial as I understand, so it doesn't need to have a permanent place to live.

I think currently, business-days related functions (`is_busday`, `busday_count`, `busday_offset`, `busdaycalendar`) aren't deprecated and weren't moved to `numpy-financial` (available functions are [here](https://numpy.org/numpy-financial/latest/#functions)). But I think it would make sense to move them there - I will start discussion in an issue there.

**Comment by mtsokol** [comment]
Closing in favor of https://github.com/numpy/numpy/issues/24166.
