### ISSUE TITLE
BUG: Inaccurate left tail of `random.Generator.dirichlet` at small `alpha`

### ISSUE THREAD

**Issue by Gattocrucco** [numpy/numpy#24475]
The Dirichlet generator produces too many small values or outright zeros when the concentration parameter is low. In the following example, I compare it to a way of generating the values that I presume to be accurate, which is representing the Dirichlet as normalized Gamma variables, but doing the calculation in logarithm space. This requires an up to date scipy, since `stats.loggamma` was made accurate for low values only recently.

Although the problem only affects values less than machine epsilon, the Dirichlet variable is often used to represent a probability distribution, and sometimes probabilities matter multiplicatively. That said, I don't know of use cases where this would be a problem. I encountered it myself only because I was using numpy's generator as a reference for unit tests of a PPL.

```python
import functools

import numpy as np
from scipy import stats, special
from matplotlib import pyplot as plt

nsamples = 100000
alpha = 0.005
dim = 2

alpha = np.repeat(alpha, dim) / dim

def accurate_dirichlet_rvs(alpha, size=(), random_state=None):

    # scaffolding
    random_state = np.random.default_rng(random_state)
    alpha = np.asarray(alpha)
    assert alpha.ndim >= 1
    size = np.broadcast_shapes(alpha.shape[:-1], size)
    alpha = np.broadcast_to(alpha, size + alpha.shape[-1:])

    # actual computation
    lny = stats.loggamma.rvs(alpha, random_state=rng)
        # scipy's loggamma is the distribution of the logarithm of a gamma var
    norm = special.logsumexp(lny, axis=-1, keepdims=True)
    return np.exp(lny - norm)

fig, axs = plt.subplots(2, 1, num='dirichlet', clear=True, figsize=[6.4, 8], layout='constrained')

rng = np.random.default_rng([2023, 8, 21, 13, 50])

samples_numpy = rng.dirichlet(alpha, size=nsamples)
samples_accurate = accurate_dirichlet_rvs(alpha, size=nsamples, random_state=rng)

def plot_empirical_cdf(ax, samples, **kw):
    edges = np.sort(samples)
    values = np.linspace(0, 1, len(samples))[1:]
    return ax.stairs(values, edges, **kw)

for i, ax in enumerate(axs):
    plot_empirical_cdf(ax, samples_numpy[:, i], label="numpy")
    plot_empirical_cdf(ax, samples_accurate[:, i], label="presumed accurate")
    ax.set(
        xlabel=f'Component {i} of a Dirichlet variate',
        ylabel='CDF',
        xscale='log',
    )
    ax.axvline(np.finfo(float).eps, color='black', linestyle='--', label='machine epsilon')

axs[0].legend(title=rf'$\alpha = {alpha.tolist()}$')
axs[0].set(title="Numpy's Dirichlet generator left tail at small alpha")

plt.show()
```

![image](https://github.com/numpy/numpy/assets/9684110/efd7eaaf-ca98-4446-94f9-a81128eb3db1)

### Runtime information

```
1.25.2
3.11.2 (v3.11.2:878ead1ac1, Feb  7 2023, 10:02:41) [Clang 13.0.0 (clang-1300.0.29.30)]
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.25.2',
  'python': '3.11.2 (v3.11.2:878ead1ac1, Feb  7 2023, 10:02:41) [Clang 13.0.0 '
            '(clang-1300.0.29.30)]',
  'uname': uname_result(system='Darwin', node='ghijkl.local', release='22.5.0', version='Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}}]
None
```

**Comment by maissa-gallah** [comment]
Hello, is it possible for me to take care of doing an MR to resolve this issue?

**Comment by Gattocrucco** [comment]
I mention @WarrenWeckesser in the hope he pops up

**Comment by melissawm** [comment]
@maissa-gallah we don't assign issues, so if you believe you have a solution for this problem please check our [Contributing guide](https://numpy.org/devdocs/dev/index.html) and go for it. Cheers!

**Comment by WarrenWeckesser** [comment]
@Gattocrucco, thanks for the creating the issue and analyzing the problem. I was away from numpy for the much of the last year; sorry this didn't get more of a response sooner.

You are correct that when the parameters are sufficiently small, the left tail of the Dirichlet distribution is too heavy.  With those small parameters, the code uses a method that is based on the beta distribution.  It turns out that the underlying problem is in the beta distribution.  When the beta parameters are both less than 1, Johnk's algorithm is used:

https://github.com/numpy/numpy/blob/128490c2f926c36a05fe09f3f639cac66707b0e8/numpy/random/src/distributions/distributions.c#L429-L451

This is a rejection method; given the beta distribution parameters a and b, with 0 < a < 1 and 0 < b < 1, a simplified version of the algorithm is

    while (1):
        X = Uniform(0, 1)**(1/a)
        Y = Uniform(0, 1)**(1/b)
        if X + Y < 1:
            return X/(X + Y)

However, when a and b are sufficiently small, there is a non-negligible probability that the expression for X or Y or both will underflow to 0. Currently the numpy code considers this possibility (as can be seen above); the simplified version is:

    while (1):
        X = Uniform(0, 1)**(1/a)
        Y = Uniform(0, 1)**(1/b)
        if X + Y < 1:
            if X + Y > 0
                return X/(X + Y)
            else:
                # Compute X/(X + Y), but work with logarithms
                [...]

Note that it only goes into the logarithm-based calculation if *both* X and Y are 0 (i.e. if `X + Y == 0`).  If X has underflowed to 0 but Y has not, the code still returns `X/(X + Y)`, even though X is not really valid.  This results to too many values being 0.

I found that if I change that code so that the logarithm-based calculation is used if *either* X or Y is 0, the problem with the heavy left tail of the beta distribution is fixed.

I'll submit a pull request with a fix soon.
