### ISSUE TITLE
BUG: array.tolist() conversion recursion failure with list of lists

### ISSUE THREAD

**Issue by snowman2** [numpy/numpy#24546]
### Describe the issue:

There is a strange bug going on when a numpy array of arrays sometimes works and sometimes doesn't. I found that if I construct the array manually, there isn't a bug, but when reading it in from a parquet file, there is a bug.
[time_period.zip](https://github.com/numpy/numpy/files/12443327/time_period.zip)

### Reproduce the code example:

```python
>>> import pandas
>>> pdf = pandas.read_parquet("time_period.parquet")
>>> pdf.values
array([[array(['2018-01-01', '2018-12-31'], dtype=object)],
       [array(['2018-01-01', '2018-12-31'], dtype=object)],
       [array(['2018-01-01', '2018-12-31'], dtype=object)],
       [array(['2020-01-01', '2020-12-31'], dtype=object)],
       [array(['2018-01-01', '2018-12-31'], dtype=object)]], dtype=object)
>>> pdf.values.tolist()
[[array(['2018-01-01', '2018-12-31'], dtype=object)], [array(['2018-01-01', '2018-12-31'], dtype=object)], [array(['2018-01-01', '2018-12-31'], dtype=object)], [array(['2020-01-01', '2020-12-31'], dtype=object)], [array(['2018-01-01', '2018-12-31'], dtype=object)]]
>>> numpy.array(pdf.time_period.values.tolist()).tolist()
[['2018-01-01', '2018-12-31'], ['2018-01-01', '2018-12-31'], ['2018-01-01', '2018-12-31'], ['2020-01-01', '2020-12-31'], ['2018-01-01', '2018-12-31']]
>>> from numpy import array
>>> manual_array = array([[array(['2018-01-01', '2018-12-31'], dtype=object)],
...        [array(['2018-01-01', '2018-12-31'], dtype=object)],
...        [array(['2018-01-01', '2018-12-31'], dtype=object)],
...        [array(['2020-01-01', '2020-12-31'], dtype=object)],
...        [array(['2018-01-01', '2018-12-31'], dtype=object)]], dtype=object)
>>> manual_array.tolist()
[[['2018-01-01', '2018-12-31']], [['2018-01-01', '2018-12-31']], [['2018-01-01', '2018-12-31']], [['2020-01-01', '2020-12-31']], [['2018-01-01', '2018-12-31']]]

```

### Runtime information:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.23.5
3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]

**Comment by rkern** [comment]
I can't tell from the example what you are expecting. You mention two possible ways of constructing the array but only show one of them.

**Comment by snowman2** [comment]
> I can't tell from the example what you are expecting. You mention two possible ways of constructing the array but only show one of them.

Updated

**Comment by rkern** [comment]
Take a look at `manual_array` and note its difference between it and `pdf.time_period.values`. It's not the same array. The behavior of `.tolist()` is a distraction; it's doing the right thing given the two different arrays.

`array()` as a constructor will basically try to infer as much structure as possible. If it encounters a set of sequences at a given depth that are all uniform in length, it will make a new axis for it. So `manual_array.shape == (5, 1, 2)` of strings, not a `(5, 1)` array of `np.ndarray` objects.

But that's not what the Pandas/Parquet data model is modeling. `pdf.values` is a `ndim=2` array of objects, all of which happen to be `np.ndarray` objects, which all happen to have the same length in this dataset, but could be different in principle. It won't round-trip through `np.array(pdf.time_series.values.tolist())` because the information about the original shape is lost. It seems like you don't want the Pandas/Parquet behavior, though, but that's just a limitation on their side. They deal with columns of `ndim=1` arrays of things, which may themselves be `ndarray` objects.

**Comment by rkern** [comment]
I think the main thing is that the `repr` of `pdf.values` looks like it ought to be executable and therefore round-trip, but that's just not possible in this instance, given the many shape-and-dtype inference tasks that `np.array()` is asked to do (and it's far from our most egregious lack-of-`repr`-executability sins).

I hope this gets you closer to understanding the issue and the options to get the behavior that you want. I don't think there is a bug to fix, though, so I will close this. Please do feel free to continue to ask any more clarification questions on the closed issue, though, and I will try to respond helpfully.
