### ISSUE TITLE
DOC: numpy serialization through pickle

### ISSUE THREAD

**Issue by KommuSoft** [numpy/numpy#24557]
### Issue with current documentation:

The documentation discusses the specifications of the [`.npy` format](https://numpy.org/devdocs/reference/generated/numpy.lib.format.html), but I can not find the specifications regarding pickle, when I create a pickle, it seems that these are two different formats, is there a section in the documentation regarding the pickle serialization of a numpy array?

**Comment by rkern** [comment]
There will likely never be the same kind of specification since it relies on the Python standard library pickle mechanism. We don't control the precise format at the level of the bytes, we just use the `pickle` API, which is then free to make a number of choices with respect to how the information we provide it is serialized as bytes.

There is probably some documentation worth writing about the strategy behind the choices that we make about the data that we pass to and receive from the `pickle` API, but I'm guessing that's not what you're after. Can you be more precise about the scope of the information that you want, and for what purpose?

**Comment by KommuSoft** [comment]
Well the main use-case is writing a binding for pickle in Haskell, which is near-ready (strings, ints, lists, dictionaries, etc.).

It would be nice to write the Haskell equivalent of numpy (`masiv`) to a pickle stream that numpy can read (or at least a subset of it), and vice-versa. While some of the pickle format can be guessed, by trail and error (like trying with an array with one zero, with one one). Some fast scanning seems to suggest that the pickle does *not* first create a list with the objects to then pass it to the numpy constructor, it seems like there is some sort of binary blob by using a `SHORT_BINBYTES` opcode likely the long one if the binary stream is longer. I tried following the code to the `_reconstruct` method, but it was a bit of a maze where things seem to make calls to modules that reexport making it hard to find the methods eventually involved.

**Comment by rkern** [comment]
`ndarray` objects expose a [`__reduce_ex__(protocol)` method](https://github.com/numpy/numpy/blob/185915bf7c6c0208541c684c65bcaa8f2f4e92a0/numpy/core/src/multiarray/methods.c#L2005-L2032), which provides the reconstruction function and arguments that are then given to the pickling machinery. Depending on the selected `pickle` protocol and the dtype and contiguity of the array, you'll get different choices made here. With the current best `protocol=5` and contiguous arrays of native dtypes, you'll get the bytes conveniently stored as a `BYTEARRAY8` opcode or similar which will then get passed to `numpy.core.numeric._frombuffer()` with shape and dtype arguments (and `'C'` or `'F'` for C- or Fortran-contiguity, depending on the original array).

Failing that, we fall back to a less efficient method which uses the [3-element option](https://docs.python.org/3/library/pickle.html#object.__reduce__) for `__reduce__/__reduce_ex__` which consists of the reconstruction function (`numpy.core.multiarray._reconstruct`), its arguments (currently the array type and some dummy arguments to make an empty `ndarray` object), and then an object that get passed to the [`__setstate__()` method](https://github.com/numpy/numpy/blob/185915bf7c6c0208541c684c65bcaa8f2f4e92a0/numpy/core/src/multiarray/methods.c#L2034-L2321) after the object is reconstructed. This is where the actual data is, and `__setstate__()` is where all of the logic is. You can read the `__setstate__()` logic for all of the gory details (including the backwards compatibility logic for very old versions of numpy), but what is currently output is commented on in the [`__reduce__` implementation](https://github.com/numpy/numpy/blob/185915bf7c6c0208541c684c65bcaa8f2f4e92a0/numpy/core/src/multiarray/methods.c#L1864-L1878), namely:

```c
    /* Now fill in object's state.  This is a tuple with
       5 arguments


       1) an integer with the pickle version.
       2) a Tuple giving the shape
       3) a PyArray_Descr Object (with correct bytorder set)
       4) a npy_bool stating if Fortran or not
       5) a Python object representing the data (a string, or
       a list or any user-defined object).


       Notice because Python does not describe a mechanism to write
       raw data to the pickle, this performs a copy to a string first
       This issue is now addressed in protocol 5, where a buffer is serialized
       instead of a string,
    */
```

I encourage you to look at `x.__reduce_ex__(protocol)` for various `x` arrays and for `protocol in (4, 5)` as `protocol=5` is the only place where we switch things up. In particular, take a look at the `dtype=object` case, if you are interested in those. When arrays are C-contiguous or entirely discontiguous (e.g. `x[::2]`), then that "npy_bool stating if Fortran or not" is `False` and the data is a C-contiguous copy of the data, regardless of the contiguity of the original. But if the array is Fortran-contiguous (e.g. `x.T` will be Fortran-contiguous if `x` is C-contiguous and multidimensional), then the data recorded here will reflect the original array's memory order and set that flag to `True` to let the reconstruction machinery know, to avoid unnecessary copying and reordering of actual bytes.

Exactly how those `__reduce_ex__()` tuples get turned into pickle opcodes is up to `pickle` itself, including the `protocol` choice, but if your goal is to port `pickle` itself, you probably have a handle on that. I hope this has helped at least signpost your way through the code. I wish you luck!

I think I'm going to close this issue since I don't think there is going to be much appetite to document these implementation details in our documentation per se. If you have a few followup questions, particularly if something I wrote here is unclear, please feel free to continue to comment on this closed issue, and I will try to respond. If you have more extensive or wider ranging questions, it will likely be best to ask on the mailing list. Thanks!
