### ISSUE TITLE
BUG: array_api.Device is confusing

### ISSUE THREAD

**Issue by aaronmondal** [numpy/numpy#24641]
### Describe the issue:

At the moment numpy.array_api defines `Device` as a literal:

https://github.com/numpy/numpy/blob/dc2ff125493777a1084044e6cd6857a42ee323d4/numpy/array_api/_typing.py#L51

This is confusing and doesn't directly translate well to an implementation-agnostic an `Array` protocol.

It gets more confusing when one considers that [`__dlpack_device__`](https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.__dlpack_device__.html) actually talks about *Device types* and not about a specific *Device* and that the type of the `device` property in the spec is unspecified (and could be generic).

I guess this should be an anonymous `Any`?

### Reproduce the code example:

```python
from typing import Literal, Protocol

from numpy import array_api as xp

Device = Literal['cpu']

class Array(Protocol):
    @property
    def device(self) -> Device:
        ...

class GPUArray(Array):
    @property
    def device(self) -> Device:
        return 'gpu' # Error: Expression of type "Literal['gpu']" cannot be
                     # assigned to type "Device"

def identity(array: Array) -> Array:
    return array

identity(xp.asarray([1]))
identity(GPUArray())
```

### Runtime information:

1.25.1
3.11.4 (main, Jun  6 2023, 22:16:46) [GCC 12.3.0]

### Context for the issue:

This was already mentioned in https://github.com/data-apis/array-api/issues/626#issuecomment-1644446307

**Comment by BvB93** [comment]
> I guess this should be an anonymous Any?

Perhaps if numpy's array API was a set of protocols representing the API interface, but it's not; it is a concrete implementation thereof and returning a literal string is as such perfectly valid as a global fixed default.

**Comment by seberg** [comment]
Going to close, the version in NumPy is really just an implementation (mainly useful for testing) and may not even stay in NumPy.  You can't use our types to type your own object.

I may be misunderstanding and maybe @asmeurer can point to a different resource?  The standard itself is effectively typing stubs I think, although I am not sure how useful it is for this purpose.

**Comment by asmeurer** [comment]
Actually, this is related to another issue, which I guess I never actually opened in the NumPy tracker. I think numpy.array_api using `"cpu"` for its device is problematic. Since it's supposed to be a minimal implementation that people can use to check their array_api usage, it gives the impression that "cpu" is always a supported device. But that isn't the case. There's some discussion to possibly change that in the spec https://github.com/data-apis/array-api/issues/626, but unless that change is made, I would suggest changing numpy.array_api to just use something like 

```
device = object()
```

so that the "device" object used by the APIs is a more abstract device object. 

Of course, the base numpy namespace, if it implements these APIs, should probably just use `"cpu"`.
