### ISSUE TITLE
DOC: what does the first argument to `np.typing.NDArray` mean?

### ISSUE THREAD

**Issue by Czaki** [numpy/numpy#24686]
### Issue with current documentation:

THe documentation of [`numpy.typing.NDArray`](https://numpy.org/devdocs/reference/typing.html#numpy.typing.NDArray) provides information that it could accept two arguments. Unspecified first and dtype. 

It is unclear the purpose of first field. It could be used to provide information about dimensionality or array size, but there is no information about this in the documentation. Or may be reserved for future usage. 

### Idea or request for content:

Clear what is the purpose of this field to. If annotation `data: npt.NDArray[(3, 3), np.float]`  for 3D transformation is a good idea/proper way to think about it?

**Comment by BvB93** [comment]
The first parameter of `np.ndarray` (`npt.NDArray` only has a single parameter: the datatypes' underlying `np.generic` type) was introduced as a placeholder slot for a future shape-type, as at the time we were concerned that going from a dtype- to a dtype- & shape-generic type would be a backwards compatibility problem due to the addition of yet another parameter slot. With [PEP 646](https://peps.python.org/pep-0646/) now accepted it's questionable to what extent our concerns turned out to be valid, but at the time this was simply an unknown and the more cautious approach was preferred.

In any case, `npt.NDArray` was specifically introduced as a more compact _size- & shape-agnostic_ type alias for `np.ndarray`, and without implementation of PEP 646 in the likes of mypy and the ability to specify default typevar values ([PEP 696](https://peps.python.org/pep-0696/)) this won't change in all likelihood.

**Comment by jorenham** [comment]
In the upcoming `2.1` release this shape-type parameter will be bound to `tuple[int, ...]`.

So your example would look like this: `data: npt.NDArray[tuple[Literal[3], Literal[3]], np.float]`.

We're currently working to use the shape-type parameter more in the typing stubs, see https://github.com/numpy/numpy/pull/27171 and https://github.com/numpy/numpy/pull/27177 for example.
