### ISSUE TITLE
BLD: ERROR: features.test takes at least 1 arguments, but got 0 with new CPU dispatcher

### ISSUE THREAD

**Issue by matoro** [numpy/numpy#24731]
### Describe the issue:

With numpy-1.26.0, which contains the new CPU dispatcher, when `-mcpu=native` is set in `CFLAGS` for platforms not in the list with explicit support (tested on alpha), configure fails with the below messages:

```
Message: Appending option "detect" to "cpu-baseline" due to detecting global architecture c_arg "-mcpu=native"
 
../numpy-1.26.0/meson_cpu/meson.build:163:35: ERROR: features.test takes at least 1 arguments, but got 0.
```

In this case, `CFLAGS` were set to `-mieee -O3 -pipe -mcpu=native -mtune=native`.  Works fine on 1.25.2.  Complete log:  [build.log](https://github.com/numpy/numpy/files/12643399/build.log)

I offer [FREE shell access to test machines for all of the architectures I validate on](https://static.matoro.tk/isa-sandbox-faq.html).  If testing on the hardware I used to reproduce this is helpful, just include a desired username.

### Reproduce the code example:

```python
N/A
```

### Runtime information:

N/A

**Comment by rgommers** [comment]
Thanks for the report @matoro. @seiko2plus could you have a look at this one?

**Comment by seiko2plus** [comment]
My bad gh-24733 should fix this issue, as workaround rather than avoid passing `-mcpu=native -mtune=native` you can instead disable feature detection through passing argument `-Ddisable-optimization` through `spin`, e.g. `spin build -- -Ddisable-optimization=true` or through `pip >= 23.1` `pip install numpy -C-Ddisable-optimization=true`

My bad, PR gh-24733 should resolve this bug.
In the meantime, instead of avoiding `-mcpu=native -mtune=native`, you can disable feature detection:
- Using `spin`: `spin build -- -Ddisable-optimization=true`
- With `pip` (v23.1+): `pip install numpy -C-Ddisable-optimization=true`
