### ISSUE TITLE
DOC: "Example NumPy ufunc for one dtype" from Using Numpy C-API doesn't work

### ISSUE THREAD

**Issue by andsmi97** [numpy/numpy#24760]
### Issue with current documentation:

I'm trying to repeat https://numpy.org/doc/stable/user/c-info.ufunc-tutorial.html guide and it seems like this doesn't work.

First part "Example Non-ufunc extension" is working exactly as described, however, first and second ufunc example does not run, when i try to call function.

Firstly, I create both files as in documentation (single_type_logit.c, setup.py). Then I install extension with python setup.py install or python setup.py build_ext --inplace. Both install extension without any errors.
After that I try to run example provided below files in debug mode:

>>>import numpy as np
>>>import npufunc
>>>npufunc.logit(0.5)

Both libraries imports with no errors, however on logit function, program crashes without any message.

My numpy version is 1.21.2
Python version 3.9.12
gcc version is 11.3.0
OS: Ubuntu 16.04.6

**Comment by WarrenWeckesser** [comment]
I can reproduce this on a Linux machine with Python 3.9.16 and numpy 1.21.2 or 1.21.5.  I can build the extension module, but then calling the `logit` function results in a seg. fault.

With Python 3.11.5 and numpy 1.26.0, the example works as expected, so I don't think this is a documentation issue.  It is likely a bug that has been fixed in later versions of the software.
