### ISSUE TITLE
DOC: `numpy.linalg.svd` appears to use LAPACK routine `_gesvd` but is documented as using `_gesdd`

### ISSUE THREAD

**Issue by raj-magesh** [numpy/numpy#24784]
### Issue with current documentation:

The documentation for [`numpy.linalg.svd`](https://numpy.org/doc/1.24/reference/generated/numpy.linalg.svd.html) mentions:

> The decomposition is performed using LAPACK routine _gesdd.

However, when I compared the results of SVD from `numpy.linalg.svd`, `scipy.linalg.svd`, `torch.linalg.svd`, and `jax.numpy.linalg.svd`, `numpy`'s results matched 

- `scipy`'s results with `lapack_driver="gesvd"` in [`scipy.linalg.svd`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html)
- `torch`'s results with `driver="gesvd"` in [`torch.linalg.svd`](https://pytorch.org/docs/stable/generated/torch.linalg.svd.html).

This suggests that `numpy.linalg.svd` uses the `_gesvd` routine, but I'm not familiar enough with LAPACK to dig into numpy's code and check what it's actually doing.

If someone with expertise could verify that the actual driver used is `_gesvd`, I can raise a PR to update the docs.

#### The SVD comparisons I ran

The first column shows `numpy.linalg.svd` vs the rest. I performed SVD on a large data matrix using each of these methods and plotted the values of `np.diag(U1.T @ U2)` (i.e. how similar the left singular vectors are for two methods 1 and 2). If the values are all ones, the two methods yield identical results.

![numpy_svd_comparisons](https://github.com/numpy/numpy/assets/28287009/4c7e71a8-044b-41b6-909c-e726d463731d)

**Comment by mdhaber** [comment]
@ilayn I thought you might know this off the top of your head. If not, I can look into it.

**Comment by ilayn** [comment]
NumPy indeed uses GESDD. In fact when you don't ask for singular vectors they use the same algorithm.

However SVD algorithms are known to be inaccurate as the size increase and conditioning worsen; especially with order of magnitudes different singular values, pretty much should be expected to have inaccuracies. Dot products won't make a good candidate for measuring success since easily one singular value can swap places with another one when they are accumulated down around zero. 

The implementation starts here https://github.com/numpy/numpy/blob/241d67678189872a25ebc0e56a07ad4254bcef9b/numpy/linalg/umath_linalg.cpp#L2564

And if you want the gory details of error bounds you can start from here https://www.netlib.org/lapack/lug/node96.html

**Comment by mdhaber** [comment]
Thanks @ilayn. It looks like that part of the documentation is correct as written @raj-magesh, so I think this issue can be closed.
