### ISSUE TITLE
DOC: Need a FAQ about `inv()` and `cond()`

### ISSUE THREAD

**Issue by rkern** [numpy/numpy#24882]
### Issue with current documentation:

We've had a number of bug reports this year ([#24881](https://github.com/numpy/numpy/issues/24881), [#24132](https://github.com/numpy/numpy/issues/24132), [#23793](https://github.com/numpy/numpy/issues/23793)) concerning `np.linalg.inv()` and its behavior with singular matrices, with different kinds of expectations.

### Idea or request for content:

We should probably have a few examples in the `np.linalg.inv()` docstring showing a (near-)singular matrix being inverted without raising a `LinAlgError`, show that the resulting inverse matrix looks terrible and fails to recover an identity matrix, then show how examining the condition number with `np.linalg.cond()` is a good idea for troubleshooting and the basic rules of thumb for working with condition numbers. The main reader persona would be someone new to floating point who expects the result of `M @ inv(M)` to be close to the identity matrix or else raise an exception. Someone who expects that if they construct a matrix that would be exactly singular in real arithmetic, then it would be necessarily detected by `inv()` to raise a `LinAlgError`.

The wording for the documentation of the `LinAlgError` could also be expanded a little to forewarn that some matrices might be (near-)singular and not trigger this exception.

**Comment by melissawm** [comment]
OOooh that sounds right up my alley, let me put a draft together.

**Comment by ilayn** [comment]
I would use eigenvalues for showing an eigenvalue very close to zero closer to what singularity means. Condition number is actually a tricky concept to get around for people who are not well versed in linear algebra. We can still use `cond` in the later examples but to drive things home I think eigenvalues should be mentioned. 

By the way, the quickest singular matrix example is `np.arange(n**2).reshape(n, n)` for any `n` to make the example generation compact. 

```python
>>> A = np.arange(9).reshape(3, 3)
>>> np.linalg.eigvals(A)
array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16])
```

The key here is that 

```
some numerical noise such as -2.48477279e-16 == 0.
```

is almost always False hence singularity is virtually always missed (internally LU is used instead of eigvals).

**Comment by ilayn** [comment]
Also current docs are using `(multiplicative)` word which is not needed and array word should be used instead of matrix in my opinion.
