### ISSUE TITLE
BUG:  module 'numpy' has no attribute 'object'. 

### ISSUE THREAD

**Issue by yamihn** [numpy/numpy#24948]
### Describe the issue:

I'm not able to use the package pySCENIC. everytime I run it, I encounter this error. I'm not able to fix it by command line or jupyter notebook

### Reproduce the code example:

```python
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

### Error message:

```shell
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

### Runtime information:

print(sys.version)
3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]

numpy version 1.26.1

**Comment by ngoldbaum** [comment]
Oh oops, I'm sorry, I said you could downgrade to 1.26, that's wrong. The latest release you can downgrade to in NumPy 1.23.5 and you won't have this issue.

> which object do you mean

`object` is built in to the python language, you don't need to import it:

```
$ python
Python 3.10.9 (main, Mar  2 2023, 11:31:32) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> object
<class 'object'>
```

It looks like this is already fixed in pySCENIC: https://github.com/aertslab/pySCENIC/issues/477#issuecomment-1588982581

However, there hasn't been a release since last November, so you won't be able to get that fix easily until they do a release.
