### ISSUE TITLE
BUG: test_cython in core/tests/examples/cython assumes only singular Python interpreter

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [numpy/numpy#24956]
### Describe the issue:

While building NumPy for openSUSE, the test looks for Python 3 and does not seem to allow overriding that for systems that contain multiple Python interpreters installed. Meson grabs python3, (which is Python 3.11) calls it good, and then falls over when that doesn't find the numpy module, since we're (for example) testing under Python 3.9.

### Reproduce the code example:

```python
Included in source tree.
```

### Error message:

```shell
[  352s] ---------------------------- Captured stdout setup -----------------------------
[  352s] 1.2.2
[  352s] The Meson build system
[  352s] Version: 1.2.2
[  352s] Source dir: /home/abuild/rpmbuild/BUILDROOT/python-numpy-1.26.1-0.x86_64/usr/lib64/python3.9/site-packages/numpy/core/tests/examples/cython
[  352s] Build dir: /tmp/pytest-of-abuild/pytest-49/popen-gw0/test_abstract_scalars0/build
[  352s] Build type: native build
[  352s] Project name: checks
[  352s] Project version: undefined
[  352s] C compiler for the host machine: cc (gcc 13.2.1 "cc (SUSE Linux) 13.2.1 20230912 [revision b96e66fd4ef3e36983969fb8cdd1956f551a074b]")
[  352s] C linker for the host machine: cc ld.bfd 2.40.0.20230412-5
[  352s] Cython compiler for the host machine: cython (cython 3.0.2)
[  352s] Host machine cpu family: x86_64
[  352s] Host machine cpu: x86_64
[  352s] Program python3 found: YES (/usr/bin/python3.11)
[  352s] 
[  352s] ../../../../../../home/abuild/rpmbuild/BUILDROOT/python-numpy-1.26.1-0.x86_64/usr/lib64/python3.9/site-packages/numpy/core/tests/examples/cython/meson.build:12:19: ERROR: Command `/usr/bin/python3.11 -c 'import os; os.chdir(".."); import numpy; print(os.path.abspath(numpy.get_include()))'` failed with status 1.
[  352s] 
[  352s] A full log can be found at /tmp/pytest-of-abuild/pytest-49/popen-gw0/test_abstract_scalars0/build/meson-logs/meson-log.txt
```

### Runtime information:

Numpy 1.26.1 (but also 1.26.0)

**Comment by ngoldbaum** [comment]
It looks like the `meson.build` just does `import('python')`. I'm not sure offhand how meson can know which version of python its getting invoked by, but presumably we'd need to know that or the tests would need to pass a path to the python executable to the cython build.

**Comment by s-t-e-v-e-n-k** [comment]
The gross idea I just thought of was replacing `import('python')` in the examples `meson.build` with `sys.executable`, but I think the cleaner option is some `-D` option to `meson setup` in the test code.

**Comment by rgommers** [comment]
This is an issue that occurs:
- only in the test suite,
- in the situation with multiple interpreters on the path, and
- when the `meson` executable is not run by the same interpreter as the one in which the `numpy` install being tested is installed for.

The last situation is unique to Linux distros I think. The `meson` Python package is a test requirement for numpy's test suite, but it can't be installed properly into a non-default system-wide Python install because the `meson` executable name clashes with that for the default Python interpreter on the same machine.

This is something that ideally shouldn't happen, but unfortunately we're stuck with distros packaging multiple Python versions without using virtualenvs or another some such activation mechanism. So we have to make the tests work with this - and I think we can so without needing manual flags. It's the same problem as running `pytest` or `pip`; in such situations the fix is to not invoke the bare executable but rather `python -m pytest` or `python -m pip` (or in this case `python3.9 -m pytest`). The one hiccup is that while `meson` _is_ a Python package, it is by design agnostic to that - it is a design goal of Meson to be able to reimplement it completely in a different language without any user-facing change - and hence `python -m meson` is not a thing.

The way `meson-python` solves this issue is to pass a `meson-python-native-file.ini` to `meson setup` with contents:
```ini
[binaries]
python = '{sys.executable}'
```
That's probably a nicer solution that the two alternatives, which are (a) amending the `meson.build` file as @s-t-e-v-e-n-k suggested above, or (b) using `meson-python` for the test rather than calling `meson` directly.

**Comment by rgommers** [comment]
Related issue: https://github.com/mesonbuild/meson-python/issues/233.

**Comment by rgommers** [comment]
gh-25839 should address this. I verified locally that that fixes the test when I manually alias `meson` to a meson executable in a Python 3.10 env, with the numpy test env being Python 3.11. It's a little tricky to test the exact distro setup here of course. @s-t-e-v-e-n-k if you could verify that it fixes the problem for you, that would be helpful.

**Comment by s-t-e-v-e-n-k** [comment]
Sorry for taking so long to circle back to this, I can confirm the linked PR fixes this issue. Thanks!

**Comment by rgommers** [comment]
Great, thank you for confirming @s-t-e-v-e-n-k, I appreciate it.
