### ISSUE TITLE
BUG: strange phenomemum with multi-variate Gaussian sample generator

### ISSUE THREAD

**Issue by zhangtj1996** [numpy/numpy#25038]
### Describe the issue:

numpy = 1.21.6

I found a strange bug when implementing with `np.random.multivariate_normal`. I used the above sample generator to get a bunch of samples, and used the ML estimator to compare the KL divergence with the ground truth. I found that no matter what ground truth dataset (change mus1 in the attached code) I used, the reported KL always has a similar value. (as long as the seed is fixed)

I believe it is related to the sample generation process. Can anyone help to answer or resolve this issue?

### Reproduce the code example:

```python
import numpy as np
from scipy.linalg import inv, det
def KL(muq,Sigmaq,mup,Sigmap):
    d = len(muq)  
    det_Sigmaq = det(Sigmaq)
    det_Sigmap = det(Sigmap)
    inv_Sigmap = inv(Sigmap)
    kl_divergence = 0.5 * (np.log(det_Sigmap / det_Sigmaq) - d + np.trace(np.dot(inv_Sigmap, Sigmaq)) + np.dot(np.dot((mup - muq).T, inv_Sigmap), (mup - muq)))
    return kl_divergence

seed = 0
mus1  = np.array([10,10]) #mus1 = np.array([22,18])
cov = np.eye(2)
num_samples = 1000
np.random.seed(seed)
samples = np.random.multivariate_normal(mus1, cov, num_samples)

x = samples[:,0]
y = samples[:,1]


mux,muy = np.mean(x),np.mean(y)

mu_e = np.array([mux,muy])
cov_e = np.array([[np.mean((x-mux)**2),0],[0,np.mean((y-muy)**2)]])
KL(mus1,cov,mu_e,cov_e)
```

### Runtime information:

1.21.6
3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

**Comment by HaoZeke** [comment]
Thanks of the report. I can't seem to reproduce this on `1.26.0`

```ipython
In [1]: import numpy as np
   ...: from scipy.linalg import inv, det
   ...: def KL(muq,Sigmaq,mup,Sigmap):
   ...:     d = len(muq)
   ...:     det_Sigmaq = det(Sigmaq)
   ...:     det_Sigmap = det(Sigmap)
   ...:     inv_Sigmap = inv(Sigmap)
   ...:     kl_divergence = 0.5 * (np.log(det_Sigmap / det_Sigmaq) - d + np.trace(np.dot(inv_Sigmap, Sigmaq)) + np.dot(np.dot((mup - muq).T, inv_Sigmap), (mup - muq)))
   ...:     return kl_divergence
   ...: 
   ...: seed = 0
   ...: mus1  = np.array([10,10]) #mus1 = np.array([22,18])
   ...: cov = np.eye(2)
   ...: num_samples = 1000
   ...: np.random.seed(seed)
   ...: samples = np.random.multivariate_normal(mus1, cov, num_samples)
   ...: 
   ...: x = samples[:,0]
   ...: y = samples[:,1]
   ...: 
   ...: 
   ...: mux,muy = np.mean(x),np.mean(y)
   ...: 
   ...: mu_e = np.array([mux,muy])
   ...: cov_e = np.array([[np.mean((x-mux)**2),0],[0,np.mean((y-muy)**2)]])
   ...: KL(mus1,cov,mu_e,cov_e)
Out[1]: 0.001328829076640488

In [2]: KL(mus1,cov,mu_e,cov_e)
Out[2]: 0.001328829076640488

In [3]: mus1 = np.array([22,18])

In [4]: KL(mus1,cov,mu_e,cov_e)
Out[4]: 109.3952594154957

In [5]: KL(mus1,cov,mu_e,cov_e)
Out[5]: 109.3952594154957

In [6]: mus1 = np.array([22,13])

In [7]: KL(mus1,cov,mu_e,cov_e)
Out[7]: 80.81113176258343

In [8]: np.__version__
Out[8]: '1.26.0'
```

Could you check if it is present after updating `numpy`?

**Comment by rkern** [comment]
`multivariate_normal` works by generating standard-normal numbers (i.e. mean of 0 and variance of 1), then scaling them by the specified covariance and shifting them by the specified mean. The maximum likelihood estimates of the final data's mean and covariance will be off from the specified mean and covariance by amounts determined by the precise details of the standard-normal numbers generated by the RNG itself. In particular, the ML mean of the final data will just be the specified mean vector plus that ML mean of the standard-normal data generated internally.

When you use the same seed, the underlying standard-normal numbers are always the same, regardless of what the specified mean and covariance parameters were. Because the KL divergence between two Gaussians is only sensitive to the difference between the mean vectors, keeping the same seed fixed while changing only the specified mean vector will get you the same KL divergence because only the difference shows up in the formula. Same seed ==> same difference ==> same KL divergence.

**Comment by zhangtj1996** [comment]
Yes, this issue should be closed.
