### ISSUE TITLE
ENH: Argmax boolean arrays optimalization

### ISSUE THREAD

**Issue by tintin10q** [numpy/numpy#25046]
### Proposed new feature or change:

I wrote this rough test to compare the argmax implementation on boolean arrays to a for loop implementation over an array of booleans.

```python
def measure(iterations: int, f: Callable, *args, **kwargs):
    """Measure how long a function takes to execute. The average time of iterations."""
    times = np.empty(iterations, dtype=np.float64)
    for i in range(iterations):
        now = time.time()
        f(*args, **kwargs)
        times[i] = time.time() - now
    return np.mean(times)

state_size = 384

def random_state(length: int = state_size, true_probablity=0.5, seed=None) -> Vector:
    """ Generate a random state """
    return np.random.choice([True, False], size=length, p=[true_probablity, 1 - true_probablity])

state = random_state()

print("dtype of state is", state1.dtype) # dtype('bool')

def for_test():
    """ Find  """
    for i in range(state_size):
        if state:
            break
    return i

def arg_test():
    return np.argmax(state)

for_faster = 0
argmax_faster = 0
iterations = 200

for i in range(iterations):
    f = measure(10000, for_test)
    m = measure(10000, arg_test)
    if f > m:
        argmax_faster += 1
    else:
        for_faster += 1

print(f"{for_faster=}/{iterations}\n{argmax_faster=}/{iterations}")
```

For me the for loop is faster every time.

I was thinking that this maybe happens because argmax does not take advantage of the fact that the dtype here is bool. That means you can just return when you find a True value because you are never going to find a higher value than that.

So the for loop implementation has the advantage of stopping at the first truth value. Does the armax function do the same?

I guess this optimization for boolean arrays could also be done for argmin. But then you could stop with the first False value.

**Comment by ngoldbaum** [comment]
First, when you share code in an issue, please make sure that it's runnable after copy/pasting it, including all imports needed.

NumPy's ufuncs currently don't have any support for what is sometimes called short-circuit or early-exit evaluation. We could probably add support, but it will take a nontrivial amount of work to get there. There's an active discussion on the mailing list about this topic at the moment: https://mail.python.org/archives/list/numpy-discussion@python.org/thread/3LW7HPLM3SONY4EKJ7GIU3CWJVKKB7PZ/

For now, you can get most of the way there if you write your own early-exit argmax in e.g. numba, which in practice just requires applying an `@numba.njit` dectorator to your for loop implementation, see: https://gist.github.com/ngoldbaum/d7d3c5e99df16bf1adffdec24d525660. Note I also fixed a bug in your implementation - you were treating an array as truthy when you really wanted to index into the array in your `for_test`.

I'm going to close this since this isn't really actionable. I don't see a larger issue about adding early-exit or short-circuiting support in numpy ufuncs, so opening an issue along those lines would probably gain more traction; particularly if it came with an offer to work on it.
