### ISSUE TITLE
BUG: OpenBSD/amd64 7.4 doesn't build from source due to missing `-lcblas`

### ISSUE THREAD

**Issue by DavidAlphaFox** [numpy/numpy#25041]
### Describe the issue:

Can't install numpy through pip, because the meson can't detect the blas and lapack correctly.
And I find there aren't any blas.pc and lapack.pc under the /usr/local/lib/pkgconfig.

### Reproduce the code example:

```python
pip install numpy==1.26.1
```

### Runtime information:

OpenBSD/amd 7.4
 Python 3.10

### Context for the issue:

The meson can't detect the blas and lapack in OpenBSD.

**Comment by rgommers** [comment]
Thanks @DavidAlphaFox, but we'll need a bit more info than that to be able to help. Questions:
- You do want/need to build with BLAS/LAPACK support, right?
- What BLAS and LAPACK are you using, and where are they installed?
- If it's a system package manager install, are there really no .pc files or can they only not be found?

**Comment by DavidAlphaFox** [comment]
@rgommers 
Yes I need build with BLAS/LAPACK.
BLAS and LAPACK comes from OpenBSD's pkg and the are all installed under /usr/local.
The system package manager doesn't generate the .pc under /usr/local/lib/pkgconfig

**Comment by rgommers** [comment]
Thanks for the details. I'm working on a fix for this.

We don't have an OpenBSD CI job, but we do have a FreeBSD one since recently ([here](https://github.com/numpy/numpy/blob/42c33f3651c8d48636807c8a7b12991ef53448ec/tools/ci/cirrus_arm.yml#L120)). That doesn't use BLAS though, so I guess we should add that. 

Could you please share the exact `pkg` invocation for how to install BLAS and LAPACK, including headers if there's a separate -dev package? That would save some trial and error in CI.

**Comment by DavidAlphaFox** [comment]
on OpenBSD
pkg_add blas cblas lapack
