### ISSUE TITLE
looking to contribute to numpy -- wondering where to start

### ISSUE THREAD

**Issue by K-DEL1999** [numpy/numpy#25224]
Hello !

This is my first time trying to get involved in open source. Would anyone be able to help me get started with an issue ? 

Thank you,
K-DEL

**Comment by melissawm** [comment]
Hi @K-DEL1999 ! NumPy is a volunteer-run project and we don't assing issues - if you feel like you are interested in a topic and want to work on it, feel free to send in a PR 😄 

In general, we would recommend:
- Reading our [contributing guide](https://numpy.org/doc/stable/dev/index.html)
- If you can, attending [Newcomer's hour](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/PZ3NEFVRY74UPHPXFWZIZOX3N54XP5VN/) - a bi-weekly meeting dedicated to newcomers to NumPy contribution
- Finding [issues](https://github.com/numpy/numpy/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) that interest you. I would recommend starting with something you are already familiar with as a user, for example. It's hard to recomment issues because it depends on your knowledge, experience and interest.

We don't have a "good first issue" label, but we don have a [sprintable label](https://github.com/numpy/numpy/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Asprintable) to mark issues that are maybe not good first issues if you're totally inexperienced, but may be a small project for someone willing to put in the time.

Let us know if you need extra help and explore the other ways to [connect with the project](https://numpy.org/contribute/).

Cheers!

**Comment by melissawm** [comment]
I am going to close this issue as it's not really a question for the repo, but feel free to engage with us in any of the other communication channels mentioned above.

**Comment by K-DEL1999** [comment]
Thank you, this was very helpful !
