### ISSUE TITLE
ENH: Adding additional assert tests to numpy.testing

### ISSUE THREAD

**Issue by alex-rakowski** [numpy/numpy#25241]
### Proposed new feature or change:

I was thinking of adding additional testing functions that test array properties either for a single array or between two arrays. These tests can be helpful for non-deterministic code and possibly in other use cases. Some are kind of trivial and may be best written as normal one line assert statements. 

Some examples are:

#### Single array properties of the values, the functions should probably take 'any' or 'all' as args to change behaviors
---
- assert_is_finite 
- assert_is_real
- assert_is_nan_free
- assert_is_complex
- assert_is_real
- assert_is_non_zero

#### Statistical comparisons between two arrays 
---
- assert_means_are_close/equal
- assert_std_are_close/equal
- assert_medians_are_close/equal
- assert_norms_are_close/equal

#### Property comparisons between two arrays these are more trivial to check with one-line assert statements, so might not be as useful
---
- assert_same_sizes
- assert_same_shapes
- assert_same_dtypes

**Comment by seberg** [comment]
Thanks, but considering nobody else has spoken up, I am confident that the main dev's would pretty much agree with me that all of these are one-liners and just create a zoo of functions that doesn't help anyone to have available (since anyone can write it themselves).

Even worse, these are already 13 functions, but I am sure I can easily triple that numbers with similar ones that are just as logical.
