### ISSUE TITLE
BUG: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject

### ISSUE THREAD

**Issue by JY231** [numpy/numpy#25258]
### Describe the issue:

I am trying to import libraries from a python package 'climada' and getting this error. I checked the compatibility of the numpy version for this package with 'pipdeptree' and it is compatible. I am using numpy = 1.21.1 and tried a few other previous/later versions. But none of them worked. Here are the screenshots of the error.
![pic3](https://github.com/numpy/numpy/assets/54965731/90825df2-be9c-41db-b49e-787754f19067)
![pic2](https://github.com/numpy/numpy/assets/54965731/0d3a081b-9746-41e7-a2e2-1ae8c483c5df)
![pic1](https://github.com/numpy/numpy/assets/54965731/9ecdfba5-06de-4baf-afe0-b04dba14b4e9)

### Reproduce the code example:

```python
from climada.hazard import Hazard
from climada.util.constants import HAZ_DEMO_FL
```

### Error message:

```shell
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject
```

### Runtime information:

1.21.1
3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]

### Context for the issue:

This is highly important as the functioning of my algorithm is dependent on this package.

**Comment by andyfaff** [comment]
Instead of posting screenshots it's better if the entire stacktrace was posted as text. You can use the triple backtick at the start and end to achieve that.
In this particular case it's not a numpy bug. Rather the installed netcdf4 package looks as if its not compatible with the version of numpy you have installed. As such, it's a downstream issue for netcdf4 (or possibly xarray).
