### ISSUE TITLE
BUG: Cannot run pandas compiled against numpy nightlies with older numpy

### ISSUE THREAD

**Issue by lithomas1** [numpy/numpy#25275]
### Describe the issue:

In the pandas nightlies, we are compiling against numpy 2.0 nightlies, and testing on an older version of numpy (numpy 1.26) but we are hitting an error from Cython saying
```
  ValueError: numpy.broadcast size changed, may indicate binary incompatibility. Expected 816 from C header, got 560 from PyObject
```

I think we are setting ``NPY_TARGET_VERSION`` corrrectly, we do

```
# Allow supporting older numpys than the version compiled against
# Set the define to the min supported version of numpy for pandas
# e.g. right now this is targeting numpy 1.21+
add_project_arguments('-DNPY_TARGET_VERSION=NPY_1_21_API_VERSION', language : 'c')
add_project_arguments('-DNPY_TARGET_VERSION=NPY_1_21_API_VERSION', language : 'cpp')
```

in our meson build file.

Note: This build was passing until yesterday. The failing build
https://github.com/pandas-dev/pandas/actions/runs/7027650127/job/19122374976

### Reproduce the code example:

```python
N/A
```

### Runtime information:

Numpy nightlies
Pandas main

**Comment by ngoldbaum** [comment]
I think this might be the same as what scikit-learn ran into in https://github.com/scikit-learn/scikit-learn/issues/27867#issuecomment-1831851413, which was fixed by https://github.com/numpy/numpy/pull/25271. And indeed the last wheel builder workflow passed: https://github.com/pandas-dev/pandas/actions/runs/7041640867.

I'm going to close this, please let us know if you see any more instability compiling against numpy dev.
