### ISSUE TITLE
BUG: Segfault on `np.random.set_state(())`

### ISSUE THREAD

**Issue by Jasha10** [numpy/numpy#25402]
### Describe the issue:

When I call `np.random.set_state(())` (passing in a tuple `()`, which is not an expected argument) I get a segfault

### Reproduce the code example:

```python
$ python
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0] on linux
>>> import numpy as np
>>> np.random.set_state(())
Segmentation fault (core dumped)
```

### Python and NumPy Versions:

```python
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.22.4
3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
```

**Comment by ngoldbaum** [comment]
I can reproduce this. It looks like it's segfaulting inside of tuple getitem when it tries to access `state[0]` [here](https://github.com/numpy/numpy/blob/08e6252fc38d3b463879afce733c889df2af1d34/numpy/random/mtrand.pyx#L371). Since it's an empty tuple that item doesn't exist.

I'm a little surprised cython doesn't raise a ValueError instead.

A quick fix would be to check for a sequence of the correct length with the types we expect.

That said, this is in the legacy RNG interface. I'm not sure if we're still updating it. But we should probably avoid seg faults in the python API, even if it is a legacy API.

**Comment by ngoldbaum** [comment]
Ah, another thing we could do is wrap just that one line in a `with cython.boundscheck(True)`. I see at the top of the file bounds checking is disabled. This is one reason it's a really bad idea to do that.

@rkern would a one-line change to `mtrand.pyx` to avoid a seg fault when someone hands it invalid input be OK?

**Comment by eendebakpt** [comment]
@ngoldbaum The problem is causes by the second line in `mtrand.pyx`:
```
#!python
#cython: wraparound=False, nonecheck=False, boundscheck=False, cdivision=True, language_level=3, binding=True
import operator
...
```
If compiled with `boundscheck=True` an `IndexError` is generated.

**Comment by ngoldbaum** [comment]
Right, but this is the legacy RNG interface which we're not supposed to make major changes in. Turning on bounds checking for the whole file might be a serious performance degradation for some workflows. Turning it on for one line in the input validation is less likely to impact users.

**Comment by rkern** [comment]
> @rkern would a one-line change to `mtrand.pyx` to avoid a seg fault when someone hands it invalid input be OK?

Yes, preventing segfaults is in-bounds (no pun intended, but appreciated after the fact).

I do prefer the one-line change rather than the whole-file change for the reasons you give.
