### ISSUE TITLE
DOC: using IPython wants the pickleshare library when building docs

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#25502]
I am seeing multiple warnings in the doc build like
```
/home/circleci/repo/venv/lib/python3.11/site-packages/IPython/core/magics/osm.py:761: \
    UserWarning: using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks',{})
/home/circleci/repo/venv/lib/python3.11/site-packages/IPython/core/magics/osm.py:795: \
    UserWarning: using bookmarks requires you to install the `pickleshare` library.
  self.shell.db['bookmarks'] = bkms
/home/circleci/repo/venv/lib/python3.11/site-packages/IPython/core/magics/osm.py:761: \
    UserWarning: using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks',{})
UsageError: %bookmark -d: Can't delete bookmark 'ipy_savedir'
```

Apparently this is known ipython/ipython#14237 and requires us to install pickleshare. I am not sure what doc page is causing this, but it should be an easy fix to [`doc_requirements.txt`](https://github.com/numpy/numpy/blob/main/doc_requirements.txt)

**Comment by rkern** [comment]
We only use the `.. ipython` directive in two places:

https://github.com/numpy/numpy/blob/main/doc/source/reference/routines.polynomials.rst
https://github.com/numpy/numpy/blob/main/doc/source/reference/random/new-or-different.rst

The first might be easy to replace with a plain-old preformatted doctest. The latter will be harder because it is showing off the `%timeit` magic to show the timings.
