### ISSUE TITLE
CI: Azure jobs are aborting after running for 60 minutes

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#25577]
Yesterday azure jobs running for longer than 60 minutes started getting canceled. Currently the pypy and python 3.11 tests are going over that limit.

The azure docs say free open source runners should have a 360 minute build time limit. I'm not sure why we're getting killed after an hour. Maybe we need to set a configuration variable somewhere?

**Comment by charris** [comment]
I suspect a policy change for the public repos. The PyPy tests on windows usually take about 90 minutes, we might want to move them to github actions.

**Comment by rgommers** [comment]
The problem was that the install of `rtools` seems to take over 30 minutes after the tarball is downloaded. Not sure if that's an rtools or an Azure issue, but we need to remove rtools from those jobs. We don't need `gfortran`, since `f2py` tests anyway need to be disabled in general CI and treated like Mypy.
