### ISSUE TITLE
ENH: numpy.random.default_rng() should generate an array of rngs when given an array of seeds

### ISSUE THREAD

**Issue by bramgrooten** [numpy/numpy#25666]
### Proposed new feature or change:

I wish to create an array of rngs such that I can vectorize this code without a for loop (which should exactly reproduce the same random_noise every time a particular idx is selected from a replay buffer):
```
for i, idxs in enumerate(idxs):
    random_noise[i] = self.rngs[idx].normal(0, self.noise_std, num_features)     
```

As of now, if I'm not mistaken, numpy.random.default_rng() returns one rng, even if provided with an array of seeds.
```
>>> import numpy as np
>>> seeds = np.array([10, 20, 30, 40])
>>> rngs = np.random.default_rng(seeds)
>>> rngs
Generator(PCG64) at 0x10274A040
>>> for rng in rngs:
...     print(rng.random())
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy.random._generator.Generator' object is not iterable
```

Providing an array of rngs doesn't need to be the default, but it should be an option.

**Comment by rkern** [comment]
We won't be doing this. As you saw, we accept a sequence of integers as a (single) seed value. [This is intentional design that provides useful constructions.](https://numpy.org/devdocs/reference/random/parallel.html#sequence-of-integer-seeds) Avoiding an idiomatic list comprehension (`rngs = [np.random.default_rng(seed) for seed in seeds]`) isn't a significant enough improvement over the status quo to motivate a new feature.
