### ISSUE TITLE
DOC: `ufunc.reduceat` doc for `dtype` inaccurate?

### ISSUE THREAD

**Issue by eliegoudout** [numpy/numpy#25752]
### Issue with current documentation:

Hi,

Currently, the doc of [`ufunc.reduceat`]() describes the optional keyword `dtype` effect as follows:
![image](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduceat.html)

But on the other hand:
```pycon
>>> np.add.reduceat([True, True], [0])
array([2])
>>> np.add.reduceat([True, True], [0], dtype=bool)
array([ True])
```

As you can see, `dtype` doesn't default to the data type of the input array as it should, otherwise both results would be the same.

Do you agree that the doc should be updated? I would suggest something like:
> **dtype** _data-type code, optional_
 The type used to perform the intermediate operations. Defaults to the data type of the output array if this is provided, or the result of `ufunc`'s casting of the input array with `ufunc.identity`.

What do you think?

**Comment by mhvk** [comment]
Hmm, trying to think through why this actually happens, I think it is because all integer reductions are automatically upcast to `int64`, and `bool` here is counted as integer. In a way, this is rather confusing, but it also means it is not the initial value as such that underlies this, but rather this attempt to try to avoid precision loss. Which I think is not unreasonable, since for `bool`, arguable `np.or.reduce` would be more logical than `np.add.reduce`...

**Comment by mhvk** [comment]
@seberg - we just had a discussion about the possible surprises from upcasting in the array API, and this is an example where it is indeed a bit surprising. I think for now it is probably best to just describe what happens (see #25753), but there is perhaps a case for any `ufunc.reduce` to always just use the type of the inputs, and let `np.sum` and `np.prod` change that behaviour.

**Comment by seberg** [comment]
@mhvk I am not sure I see the surprise here all that much.  The docs fail to properly mention promotion, and promotion can be a bit more complicated?

OTOH, there is absolutely no point in getting the boolean result, is there?!

I mean, I don't even know whether `np.True_ + np.True_` shouldn't give `int64(2)` rather than `add.reduce` and friends doing that promotion only.

**Comment by mhvk** [comment]
@seberg - the surprise to me is just that I generally do not think of bools as integers... (if they were, `True+True` should arguably just wrap and produce `False`...)

But I see your logic: if we think that `+` is not really defined for booleans (reasonable), then `np.add` should not have a boolean loop; if we then allow `bool` to be promoted to integer (also reasonable), you would indeed get 2 in a logical way (and the reduction with dtype `bool` would fail?).

It still don't quite like, though, that we special-case some ufuncs... but I'm certainly no model of consistency: I was more than happy to do some special-casing of python scalars for the comparison functions...

Anyway, @eliegoudout, the conclusion so far is that clarifying the documentation on the *existing* implementation is the right way to go!

**Comment by eliegoudout** [comment]
Thanks for all your reactions. I think this happens simply because `ufunc.reduceat` uses the default `casting` parameter of `ufunc`, which is `same kind` for `np.add`.
