### ISSUE TITLE
BUG: Weird conversion behavior from np.float32 to Python float

### ISSUE THREAD

**Issue by fandreuz** [numpy/numpy#25836]
### Describe the issue:

I found out that converting `np.float32` to a Python float via `.item()` gives a weird result. While I understand NumPy retains the float32 internal representation of the value, I feel that for such a simple value the following should not fail:
```python
np.array(5.1, dtype=np.float32) == 5.1
```

### Reproduce the code example:

```python
>>> import numpy as np
>>> np.array(5.1, dtype=np.float32).item()
5.099999904632568
```

### Python and NumPy Versions:

NumPy: 1.26.4
Python: 3.9.18

**Comment by charris** [comment]
Neither the lhs nor the rhs of the comparison is equal to `5.1`, `5.1` cannot be exactly represented in standard twos based floating point. This is a quirk of floating point arithmetic that the user needs to be aware of and take into account, that is why `assert_almost_equal` exists. In short, don't do that.

**Comment by rkern** [comment]
Specifically, there are two different things going on in the two different statements. But in both statements, the `5.1` on the LHS is first being converted to `np.float32` and then converted back up to `np.float64`. Because neither `np.float64` or `np.float32` exactly represent the decimal `5.1`, some of the bits in the `np.float64` representation get lost in that round trip.

```python
>>> np.array(5.1, dtype=np.float32) == 5.1
False
```

Here, the `ndarray` on the LHS needs to figure out a common dtype to do the `__eq__` operation with the `float` (corresponding to `np.float64`) scalar value on the RHS. As a quirk of our coercion logic, when you combine 0-D arrays and scalars, they are treated both as scalars. The biggest precision wins, so the LHS gets cast up to `np.float64` before doing the comparison; you are implicitly requesting the cast up to `np.float64` by using a `float` object on the RHS. O
OTOH, if you used a `np.float32` scalar on the RHS, you would have gotten the desired comparison.

```python
>>> np.array(5.1, dtype=np.float32) == np.float32(5.1)
True
```

```python
>>> type(np.array(5.1, dtype=np.float32).item())
float
```

`ndarray.item()` converts scalars to proper Python builtin types, in this case `float` (which corresponds to `np.float64`), so you are more or less explicitly requesting the cast up to `np.float64`. The complicated-looking number that you see shows you the precision that you lost when you converted the original `5.1` `float` down to `np.float32`.

**Comment by fandreuz** [comment]
Thanks @rkern for the explanation!
