### ISSUE TITLE
MAINT, DOC: npy_2_compat.h header shims/docs?

### ISSUE THREAD

**Issue by tylerjereddy** [numpy/numpy#25850]
Downstream in SciPy I needed to manually edit `npy_2_compat.h` per the diff below the fold to compensate for changes in gh-25812 (see also: https://github.com/scipy/scipy/pull/20108). I can't tell if this is just something that needs to be documented a bit better to use properly, or if there's a genuine issue here. What seemed to be happening is that `NPY_FEATURE_VERSION >= NPY_2_0_API_VERSION` was true when building against NumPy `1.26.4`, and then chaos ensues with things getting redefined, an underscored function that doesn't exist is declared, etc. There is a comment in that header about that check always being true for "internal" builds or something, but a quick browse of the NumPy migration guide/docs made me a bit impatient and I just hacked the header to make things work for various scenarios like building against 2.x and testing with 2.x, building against 2.x and testing against 1.x, etc.

<details>

<summary> Header changes I made </summary>

```diff
--- a/numpy/_core/include/numpy/npy_2_compat.h
+++ b/numpy/_core/include/numpy/npy_2_compat.h
@@ -70,17 +70,7 @@
  *
  * The number of built-in NumPy dtypes.
  */
-#if NPY_FEATURE_VERSION >= NPY_2_0_API_VERSION
-    #define NPY_DEFAULT_INT NPY_INTP
-    #define NPY_RAVEL_AXIS NPY_MIN_INT
-    #define NPY_MAXARGS 64
-
-    static inline npy_uint64
-    PyDataType_FLAGS(const PyArray_Descr *dtype)
-    {
-        return (unsigned char)dtype->flags;
-    }
-#elif NPY_ABI_VERSION < 0x02000000
+#if NPY_ABI_VERSION < 0x02000000
     #define NPY_DEFAULT_INT NPY_LONG
     #define NPY_RAVEL_AXIS 32
     #define NPY_MAXARGS 32
@@ -117,13 +107,7 @@
 
 
 #if !(defined(NPY_INTERNAL_BUILD) && NPY_INTERNAL_BUILD)
-#if NPY_FEATURE_VERSION >= NPY_2_0_API_VERSION
-    static inline PyArray_ArrFuncs *
-    PyDataType_GetArrFuncs(PyArray_Descr *descr)
-    {
-        return _PyDataType_GetArrFuncs(descr);
-    }
-#elif NPY_ABI_VERSION < 0x02000000
+#if NPY_ABI_VERSION < 0x02000000
     static inline PyArray_ArrFuncs *
     PyDataType_GetArrFuncs(PyArray_Descr *descr)
     {

```

</details>

**Comment by ngoldbaum** [comment]
There's another issue, just doing `#include "ndarraytypes.h"` is enough to trigger compiler warnings now:

```
  [65/152] Compiling C object pandas/_libs/pandas_datetime.cpython-311-darwin.so.p/src_datetime_date_conversions.c.o
  In file included from ../pandas/_libs/src/datetime/date_conversions.c:11:
  In file included from ../pandas/_libs/include/pandas/datetime/date_conversions.h:12:
  ../../../.pyenv/versions/3.11.6/lib/python3.11/site-packages/numpy/_core/include/numpy/ndarraytypes.h:548:1: warning: function 'PyDataType_GetArrFuncs' has internal linkage but is not defined [-Wundefined-internal]
  PyDataType_GetArrFuncs(struct _PyArray_Descr *);
  ^
  ../../../.pyenv/versions/3.11.6/lib/python3.11/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1551:12: note: used here
      return PyDataType_GetArrFuncs(((PyArrayObject_fields *)arr)->descr)->getitem(
             ^
  1 warning generated.
```

This is happening because `PyArray_GETITEM`, defined as a static inline function in `ndarraytypes.h` uses `PyDataType_GetArrFuncs`. Adding `#include "npy_2_compat.h"` fixes the warning, but at that point we might as well include that header in `ndarraytypes.h`, which I don't think was the intention.

@rgommers @mattip @charris given that Sebastian is gone and we're seeing some issues from the change that removed public access to `descr->f`, what do you think about reverting #25812?

**Comment by charris** [comment]
> what do you think about reverting #25812?

I don't think the removal `descr->f` from public access is a blocker for 2.0, but it would be nice to do.

**Comment by ngoldbaum** [comment]
Not permanently, I'm just unsure what the fix is for these header issues and we probably don't want to leave downstream nightly CI broken for two weeks.

I can also spend some time in the next day or two to try and figure out a fix.

**Comment by rgommers** [comment]
> @rgommers @mattip @charris given that Sebastian is gone and we're seeing some issues from the change that removed public access to `descr->f`, what do you think about reverting #25812?

Agreed. When there's multiple issues with somewhat unclear resolution path, plus another unrelated issue preventing us uploading a consistent set of nightlies with this change included right now, reverting is a good idea.

Full disclosure: I encouraged @ngoldbaum to merge the open C API PRs that looked ready, with the rationale that we want signal from downstream rather than leave it all sitting in open PRs while @seberg is on holiday. We've got that signal now, so this was still a useful exercise. A straight revert now is better though than leaving things as is. I'll hit the revert button on that PR now.

**Comment by ngoldbaum** [comment]
We did the revert so closing for now.

**Comment by seberg** [comment]
So basically, the way things are (and have to be) the compat header *requires* the NumPy API access, since it has runtime behavior and needs new functions.
Which  yes, means that the `PyArray_GETITEM` and `SETITEM` have to move, I am surprised I didn't realize this here, since I noticed it for some other things, but not sure maybe my local compiler was a bit forgiving.

There is one more annoyance, which SciPy probably doesn't care much about: Since you have to include the compat header (since access becomes opaque) as any opaque access you must use the `import_array()` (full NumPy header include).

I don't think that is so bad, but in some places it might be less obvious where to do the `import_array` call.  I think we should add or just modify import array to check for whether it was already imported.  That way it is completely fine to do this on every function call even (i.e. `npy_ensure_numpy_api() < 0`, a static inline function which first checks for `NULL`).

Sorry about the `->f` slot annoyance:  We have to force users to recompile (or do nothing) but the order of things is that my plan was to not break things as much in that PR, but make one big breaking PR after the first 3 of prep.
