### ISSUE TITLE
BUG: `assert_warns` ignores `kwargs` unless `args` is passed

### ISSUE THREAD

**Issue by mdhaber** [numpy/numpy#25989]
### Describe the issue:

Some tests in SciPy (scipy/scipy#20031) were written under the assumption that `assert_warns` accepts a `match` parameter like `pytest.warns`. Unfortunately, `assert_warns` accepts the parameter but ignores it, so these tests passed even though the intended warning was not emitted.

In these cases, I think `assert_warns` should have raised an error when attempting to pass `**kwargs` to a user-provided callable, but this isn't attempted unless `*args` is passed. Should there be an error if `**kwargs` is passed without `*args`?

### Reproduce the code example:

```python
from numpy.testing import assert_warns
import warnings

with assert_warns(UserWarning, match="A"):
    warnings.warn("B", UserWarning)
```

### Python and NumPy Versions:

1.25.2
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

**Comment by mattip** [comment]
>  Should there be an error if **kwargs is passed without *args?

Yes, that seems like a bug.

I agree with the recommendation in the related issue to prefer `pytest.warns`, maybe we should go a step further and deprecate `assert_warns`.

**Comment by mdhaber** [comment]
> maybe we should go a step further and deprecate assert_warns

There are still some uses on the SciPy side, but I'd be willing to change them over to `pytest`, so I'd support this.

`assert_raises` at least gives an error:
```
TypeError: 'match' is an invalid keyword argument for this function
```

But if you're willing to deprecate one because it doesn't support `match`, maybe deprecate both? There are a lot of different errors/warnings out there.

**Comment by ngoldbaum** [comment]
There's a decent amount of downstream usage for both, although `assert_raises` seems a bit more popular:

https://github.com/search?q=%22from+numpy.testing+import+assert_warns%22&type=code
https://github.com/search?q=%22from+numpy.testing+import+assert_raises%22&type=code

I don't have a strong opinion about this but I agree it probably makes sense to point people at pytest instead of trying to maintain these as if numpy doesn't itself depend on pytest.

Probably a first step before deprecating anything would be to replace internal usages of `assert_raises` and `assert_warns` with pytest. It looks like there are still lots of places we use those.
