### ISSUE TITLE
MAINT: What should we do about np.strings.partition?

### ISSUE THREAD

**Issue by lysnikolaou** [numpy/numpy#25993]
As of NumPy 1.x, an array returned from `np.char.partition` has one more dimension than the input array, and includes the separator string n times, where n is the number of items in the input array.

```python3
>>> import numpy as np
>>> arr = np.array(['hello,world', 'something,else'])
>>> np.char.partition(arr, ',')
array([['hello', ',', 'world'],
       ['something', ',', 'else']], dtype='<U9')
```

In the context of calling `partition` on arrays, it doesn't make much sense to me to return the separator n times. So, the question is, should we maybe diverge from the CPython behavior and do something less wasteful than that in NumPy? If so, will we make it to rc1? I can work on a PR as soon as we got some consensus on what to return instead, but if we don't make it, let's remove `np.strings.partition` for now and leave it in `np.char`, so that we have freedom over what its API is going to be.

To me, returning the following 3-tuple makes more sense (maybe others have better ideas):
1. bool array that signifies whether the separator was found (1 byte per item vs 4 bytes per item for unicode arrays)
2. string array for all the items before the separator
3. string array for all the items after the separator

cc @ngoldbaum @mhvk

**Comment by mhvk** [comment]
That's a tricky one. Certainly, in your example having 9x4 bytes for each comma or empty string seems excessive. I think if we do anything, though, it should follow the order of CPython, i.e., string array of before, string array of separator/empty, string array of after.

For me, what complicates this further is that `np.char.split` returns an object array of list:
```
In [6]: np.char.partition(np.array(['0 1 2', 'a']), ' ')
Out[6]: 
array([['0', ' ', '1 2'],
       ['a', '', '']], dtype='<U3')

In [7]: np.char.split(np.array(['0 1 2', 'a']))
Out[7]: array([list(['0', '1', '2']), list(['a'])], dtype=object)
```
I don't think it is very nice if `.split()` returns something where you have to index the element to get the parts, while for `.partition()` one first has to index the part (to get all elements).

p.s. Since this is not obvious, perhaps for now leaving it just in `np.char` is not a bad idea...

**Comment by ngoldbaum** [comment]
The problem with `split` is the API contract forces us to produce a ragged array.

`partition` is different because you'll always get 3 entries in the trailing dimension.

I agree it would be best if we could figure out a uniform way to handle this. For `split` we could do things like setting entries that come "after" the last split to empty string or force people specify `maxsplit`, but fundamentally the python API doesn't really make sense for an ndarray library. I'm not sure offhand what's best.

pyarrow doesn't have a `str.partition` equivalent, but it looks like they handle this in `pyarrow.compute.split_pattern` by returning a `ListArray` (e.g. a ragged array):

```
In [4]: a
Out[4]:
<pyarrow.lib.StringArray object at 0x104eaa860>
[
  "hello",
  "world"
]

In [5]: pa.compute.split_pattern(a, pattern="l")
Out[5]:
<pyarrow.lib.ListArray object at 0x158561840>
[
  [
    "he",
    "",
    "o"
  ],
  [
    "wor",
    "d"
  ]
]
```

For the specific question posed in the issue, I think returning a boolean array instead of an array containing empty strings or the partition character is probably best, since I suspect that most people will just convert the array to a bool anyway to see where there are valid splits.

**Comment by mhvk** [comment]
I guess one thing to consider is whether there is any specific implementation that would allow one to write a routine that works on arrays, and automatically works on single strings as well. This is partially what makes me like the tuple route but also makes me feel that the middle one, for separator, should be a string array, with separator or empty as entries. It means one can more easily reconstruct things.

**Comment by ngoldbaum** [comment]
For some historical context, the reason the separator was returned in the python implementation is [to use it as a boolean flag](https://marc.info/?l=python-dev&m=112529473001162&w=2). Reconstructing the original string is still trivial since the user knows the separator they passed to `partition` in the first place. And to me, it makes more sense to return a boolean if the intention is to signal that a match was found or not.

That said, keeping consistency with the single-string case is also very worth doing so if the only way to keep that is to return a string array of separators or empty string, that's fine with me.

I also looked a little bit at the `split` question, it looks like at least ONNX defines a [padded split](https://github.com/onnx/onnx/blob/a600e2fe60fcec561a448aabacc43033e5025220/onnx/reference/ops/op_string_split.py#L25) wrapper around `char.split`, so there's at least one piece of prior art where someone went out of their way to not get the object array of lists, despite the memory overhead.

**Comment by lysnikolaou** [comment]
> For split we could do things like setting entries that come "after" the last split to empty string or force people specify maxsplit

I think we should probably leave `split` alone and have it return an array of dtype `object`. Calling `split` on an ndarray makes little sense and, to me, the current behavior is the least confusing to the end user.

> That said, keeping consistency with the single-string case is also very worth doing so if the only way to keep that is to return a string array of separators or empty string, that's fine with me.

I don't understand what exactly consistency means in this context. Would this be consistent?

```python3
>>> import numpy as np
>>> a = np.array(['hello,world'])
>>> np.strings.partition(a, ',')
(array(['hello'], dtype='<U5'), array([ True]), array(['world'], dtype='<U5'))
>>> a = np.str_('hello,world')
>>> np.strings.partition(a, ',')
(np.str_('hello'), np.True_, np.str_('world'))
```

> I also looked a little bit at the split question, it looks like at least ONNX defines a [padded split](https://github.com/onnx/onnx/blob/a600e2fe60fcec561a448aabacc43033e5025220/onnx/reference/ops/op_string_split.py#L25) wrapper around char.split, so there's at least one piece of prior art where someone went out of their way to not get the object array of lists, despite the memory overhead.

This is interesting. Maybe worth adding it as a separate API? So have both `numpy.strings.split` and `numpy.string.padded_split`?

**Comment by ngoldbaum** [comment]
> Would this be consistent?

I think so, yes. You can pass a single string and an array into the function and you get back the correct result either way.

>  Maybe worth adding it as a separate API then? So have both numpy.strings.split and numpy.string.padded_split?

Yeah, let's do this and not try to force `split` to have an API that makes sense for an array library. 

Maybe we could do the same for the new API we're spitballing for `partition`? Although I can't think of a good name to use. That way we can leave `partition` in `np.strings`, but then when we come up with a new function that makes more sense, add it and add a note to the `partition` docstring that the other function is probably what people want. You could also do it with a keyword argument, but that's likely less discoverable.

My only concern with hiding `partition` and `rpartition` in numpy 2.0 is it means `np.strings` isn't quite a drop-in replacement for `np.char`. But also [it's not exactly a popular function](https://github.com/search?q=%22np.char.partition%22&type=code) so maybe that's fine.

**Comment by mhvk** [comment]
I think in my example I wasn't quite clear, if one uses `np.string.partition` then there is of course no problem, but I was, arguably wrongly, thinking of a function that takes some string input `s` and then doing `s.partition(...)` - and how it would be nice if the result could be interpreted independently of whether `s` was `str` or array-like. But of course, this would only work for `chararray`, so is not directly relevant to a new *function* in `np.strings`.

Anyway, overall I think for both `partition` and `split`, what is returned by `str` is just not quite useful for what needs to be returned by an array routine. In that respect, it would seem fine to delay this a bit, and think, e.g., where there would be a more general routine that allows one to select which part, or how many splits, one wants.

**Comment by rgommers** [comment]
It would be good to get this off the list of blocking items for `2.0.0rc1`. It should require only a diff of a few lines I think, e.g. adding an underscore to the names to ensure they are not exposed publicly yet. Could you open a PR @lysnikolaou?

**Comment by lysnikolaou** [comment]
@rgommers Opened #26033.

**Comment by ngoldbaum** [comment]
Closed by https://github.com/numpy/numpy/pull/26033.

**Comment by lysnikolaou** [comment]
Should we maybe keep this open until `partition` is implemented as a ufunc?

**Comment by ngoldbaum** [comment]
Ah sure, sorry for closing prematurely

**Comment by ngoldbaum** [comment]
Changed the milestone so it doesn’t show up as a 2.0 blocker.
