### ISSUE TITLE
BUG: (numpy 2) defect in string summation ?

### ISSUE THREAD

**Issue by neutrinoceros** [numpy/numpy#26062]
### Describe the issue:

Reducing string arrays with `np.sum` produces unexpected results.
This is specific to the dev and maintenance branches, as the operation is simply not supported in any release (including 2.0.0b1).

### Reproduce the code example:

```python
import numpy

arr = np.sum(["a", "b", "c", "d"])
print(arr)
print(repr(arr))
```

Expected output:
```
abcd
'abcd'
```
Actual:
```
d
'\x00\x00\x00d'
```

### Error message:

```shell
no error message
```

### Python and NumPy Versions:

```
2.1.0.dev0+git20240315.dc33ac4
3.12.2 (main, Feb 22 2024, 09:53:39) [Clang 15.0.0 (clang-1500.1.0.2.5)]
```

### Context for the issue:

Originally discovered while testing astropy against numpy dev
xref https://github.com/astropy/astropy/issues/16211

The failure in astropy bisects to gh-26012, but I think it might just be surfacing a bug in `add_strided_loop`, which was introduced in gh-25347

**Comment by seberg** [comment]
@ngoldbaum do you know how come `StringDType` is used here, seems something the promoter should probably maybe prevent it for now at least?

But, also indicates a bug, because:
```
np.add.reduce(["a", "b", "c"], dtype=np.dtypes.StringDType)
np.add.reduce(np.array(["a", "b", "c"], dtype=np.dtypes.StringDType))
```
both return the same wrong result.

**Comment by seberg** [comment]
I have gh-26066 to fix the new summation, although it might be that we really should indicate reduction better there.

It doesn't fix the other part of this issue.  Maybe for string inputs it can be argued that this is fine, but in general, I do not think we should silently promote old-style strings to the new StringDType here.

**Comment by ngoldbaum** [comment]
I agree that stringdtype shouldn't get picked up here. We have an `add` ufunc in main for unicode so not sure offhand why that's not getting picked up with no stringdtype operands.

**Comment by seberg** [comment]
Aha, the reason is that we call promoters with `NULL, dtype, NULL` for reductions and that makes the `lall_strings_promoter_dtypes` match.  We can fix that by checking in the promoter, but it does beg the question a bit if we need a "skipping" mechanism, so that we resolve again but ignoring any promoter previously found.

**Comment by seberg** [comment]
> Glad you've got a fix coming, happy to review.

Haven't started to look into it yet, but will try to tomorrow.  We'll probably break ABI for that (which is fine, this is new ABI nobody can be using yet).

The best thing seems to me seems a `match` semantic, OTOH, I don't love duplicating the logic.  We could also call the promoter immediately (even if another one matches better and we discard the result later); which seems a tad tedious, but easier to implement than first checking everything and one function is easier than two?

**Comment by ngoldbaum** [comment]
I'm not sure if the information is available when the promoters are called, but is it possible to check if the promoter the dtype is registered with is actually in the signature at all? It only makes sense to use the stringdtype promoter for an `add` signature like `(string, some_dtype, string)`, but because the reduce signature is `(NULL, some_dtype, NULL)` the string promoter is used anyway. If there was a check to see if the entries in those NULLs were actually `stringdtype` we'd avoid this problem.

**Comment by seberg** [comment]
The info can't be available, since it's the promoters job to return it?  So I think whatever you do it is just a way to spell "matches" (i.e. via a "must contain DType X"), but at that point it seems not very useful to not just use "matches" (which yes, is awfully generic, but...).

It might be nice to be able to just register "any input dtype is X", maybe `dtype, dtype, X` could even be it (I am not sure).  But dispatching is tricky, and I do think we need enough info via the types to define an order between (at least "matching") promoters.
(I suppose one could in principle allow multiple matching ones so long they _agree_ exactly on the precise result).

**Comment by seberg** [comment]
Forgot to close in other PR.

**Comment by neutrinoceros** [comment]
Thanks a lot @seberg !
For posterity, since I can't find any direct references: the accepted fix was gh-26090
