### ISSUE TITLE
DOC: Change to `np.bool` not mentioned in the migration guide

### ISSUE THREAD

**Issue by jorenham** [numpy/numpy#26203]
### Issue with current documentation:

The changes to `np.bool` are mentioned in the [2.0.0 release notes](https://github.com/numpy/numpy/blob/v2.0.0rc1/doc/source/release/2.0.0-notes.rst#changes), but I can't find anything about it in the [migration guide](https://github.com/numpy/numpy/blob/v2.0.0rc1/doc/source/numpy_2_0_migration_guide.rst), ~even though it's a breaking change~.

related to #26199

**Comment by rgommers** [comment]
It's not a breaking change; `np.bool` does not exist in numpy 1.24-1.26

**Comment by jorenham** [comment]
@rgommers Oh I must've missed that then, I was under the impression that `np.bool` was an alias to `builtins.bool`

**Comment by rgommers** [comment]
yes, long ago - that was deprecated in 1.20.0 and then removed in 1.24.0. It's noted in the 1.24.0 release notes as a breaking change.

**Comment by jorenham** [comment]
Either way, shouldn't this still be in the migration guide, since `np.bool_` is but a temporary alias?

**Comment by rgommers** [comment]
Not really, since (as you found out) it's hard to use `np.bool` now unless you drop 1.x support. It's easier to use regular docs and (now or later) drop the `np.bool_` type annotation as a nudge. Users who already use `bool_` right now don't have to do anything right now; new users looking for it will find `np.bool` first since it's more discoverable.

**Comment by jorenham** [comment]
A wise man said in https://github.com/numpy/numpy/pull/25080#issuecomment-1795918165 that 

> We should keep that for quite a while, in order to not force people to write if/else stuff depending on the numpy version. In the long run it can go, but there is no hurry I think.

Which in my mind falls into the category of "deprecated, do not use". Or is this a miscategorization on my part?

**Comment by rgommers** [comment]
More or less - "discouraged, do not use for new code" I'd say. At some point we'll probably deprecate it, and then it'll start emitting a warning, so if that's release 2.6.0 or so, it will end up in the notes for that release. "deprecated" has a very well-defined meaning (https://numpy.org/neps/nep-0023-backwards-compatibility.html), and will cause many downstream projects to have to migrate away from it straight away, since they turn warnings into errors in their CI.

**Comment by jorenham** [comment]
Ok that clears things up, thanks 😄
