### ISSUE TITLE
ENH: <support datatype FP8>

### ISSUE THREAD

**Issue by xiguadong** [numpy/numpy#26405]
### Proposed new feature or change:

Hi :
Do you have any plan to support FP8 which proposed in https://arxiv.org/pdf/2209.05433 ?

**Comment by jakevdp** [comment]
I don't know of any proposal to include fp8 types in numpy itself, but you might take a look at the [ml_dtypes](https://github.com/jax-ml/ml_dtypes) package, which defines several flavors of fp8 dtypes for use with NumPy.

**Comment by rgommers** [comment]
+1 for `ml_dtypes` here.

We may end up incorporating `bfloat16` into numpy itself at some point, but `float8` seems like a bridge too far, at least in the near future (and no one has proposed actually doing this anyway). So I'll close this since the question is answered and a solution available. Thanks @xiguadong and @jakevdp
