### ISSUE TITLE
BUG: Mypy error on random choice with list of enums 

### ISSUE THREAD

**Issue by q-wertz** [numpy/numpy#26465]
### Describe the issue:

An error 
```
Argument 1 to "choice" of "Generator" has incompatible type "list[DsAlg]"; expected "Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]"Mypy[arg-type](https://mypy.readthedocs.io/en/latest/_refs.html#code-arg-type)
```
is raised by mypy when using `choice` (either from `Generator` or direct function) on a list of enums.

### Reproduce the code example:

```python
import enum
import numpy as np

class Test(enum.Enum):
    A = enum.auto()
    B = enum.auto()
    C = enum.auto()
    D = enum.auto()


np.random.choice([Test.A, Test.B, Test.C], size=100)  # <-- mypy error

_rng = np.random.default_rng()
_rng.choice(list(Test), size=100)  # <-- mypy error
_rng.choice([Test.A, Test.B, Test.C], size=100)  # <-- mypy error
```

### Error message:

```shell
Argument 1 to "choice" of "Generator" has incompatible type "list[DsAlg]"; expected "Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]"Mypy[arg-type](https://mypy.readthedocs.io/en/latest/_refs.html#code-arg-type)
```

### Python and NumPy Versions:

1.26.4
3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417]

MyPy version: mypy 1.10.0 (compiled: yes)

**Comment by rgommers** [comment]
I don't think this is a bug. It's about whether `ArrayLike`, which includes `_SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]]`, supports lists/sequences of arbitrary unknown objects (in this case, enums).

That reduces down to: is an enum acceptable for `dtype[Any]`. And I think the answer is no, since `np.dtype(enum)` or `np.dtype(Test.A)` doesn't work.

This code example when run will produce an object array. But I don't think it's reasonable to accept NumPy's already very flexible type annotation to support any arbitrary Python object that may be able to turn into an object array.

Here is how `dtype` is implemented: https://github.com/numpy/numpy/blob/fba4fc16a26e77ec4ce2b1900577f088b1d5a7a6/numpy/__init__.pyi#L641-L656

It looks to me like this can be closed.

**Comment by q-wertz** [comment]
Thanks for the explanation.

A "workaround" is to use the built-in `random` library
```
import enum
import random

class Test(enum.Enum):
    A = enum.auto()
    B = enum.auto()
    C = enum.auto()
    D = enum.auto()


random.choice([Test.A, Test.B, Test.C]) 
```

Should I close the issue or will some moderator close this?

**Comment by rgommers** [comment]
> A "workaround" is to use the built-in `random` library

The workaround is to add a `# type: ignore` comment. Mypy is a very limited tool, so you'll have to do that regularly in your code. Don't change working code because Mypy is unhappy.
