### ISSUE TITLE
Would numpy 2.0 adopt Array API for finfo attributes being built-in python floats ?

### ISSUE THREAD

**Issue by vfdev-5** [numpy/numpy#26523]
Hello,
I wonder whether numpy 2.0 will be array-API compatible in terms for finfo attributes. In numpy, some of finfo attributes, like eps, min, max, smallest_normal are of type `np.floating`, but the array-API specifies them as built-in python floats (https://data-apis.org/array-api/latest/API_specification/generated/array_api.finfo.html#finfo):

```python
>>> import numpy as np
>>> f = np.finfo("float32")
>>> f
finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
>>> f.eps
np.float32(1.1920929e-07)    # should be a python built-in float according to Array-API
>>> np.__version__
'2.0.0rc2'
```

For the context, this question is coming from the jax project which is trying to be compatible with numpy and also adopts array-API.

Thanks!

**Comment by ngoldbaum** [comment]
See https://github.com/data-apis/array-api/issues/405, this is because numpy has support for extended precision types, so python float doesn't work for longdouble. We should probably add a comment to the array api test skips explaining why we do that: https://github.com/data-apis/array-api-tests/blob/4a04c6ec1b7b13f30c25744c696de8a49c735f4e/array_api_tests/test_data_type_functions.py#L143

**Comment by seberg** [comment]
Closing, NumPy behavior is correct, I would prefer if many of these issues would be opened first at the Array API.
