### ISSUE TITLE
spin test should run the full test suite by default

### ISSUE THREAD

**Issue by asmeurer** [numpy/numpy#26588]
### Proposed new feature or change:

It's a bad developer experience that `spin test` does not actually run all the tests by default. I don't see a particularly good reason to do this, given that the full test suite doesn't actually take that long to run. On my machine, `spin test` runs in 1 minute and `spin test -m full` runs 2 minutes. Whatever minutes of developer time are saved here are wasted in triplicate by people submitting pull requests thinking that all the tests pass when they actually don't.

I propose making `spin test` run the full tests by default, and adding `spin test --fast` to do a faster run.

I had mentioned this previously at https://github.com/numpy/numpy/pull/25914

**Comment by seberg** [comment]
Going to close this.  I think `spin test` should be the default for what is useful in day-to-day.  And day-to-day slow tests fail so rarely, I prefer being surprised by the failure in CI rather than having to wait longer the many times `spin test` is run.

Yes, that is an opinion that it is nicer to trade perfect accuracy against much faster test running by default.

I think(?) some other maintainers had the same thinking, but if you disagree let me know.

**Comment by asmeurer** [comment]
As I said, you could always add a `spin test --fast` if you're running the local tests enough time that it's an issue. The 1 minute saved by skipping the slow tests pales in comparison to the hours wasted by not finding bugs before pushing (both wasted time for the contributor and for reviewers).
