### ISSUE TITLE
BUG: A symmetric matrix and a symmetric matrix transposed by the same vector have different results

### ISSUE THREAD

**Issue by bjfrbjx** [numpy/numpy#26668]
### Describe the issue:

A symmetric matrix and a symmetric matrix transposed by the same vector have different results.

### Reproduce the code example:

```python
import numpy as np
n = np.arange(120).reshape(120, 1)
S = np.exp(n.T * n / 120)
print(np.all(S == S.T))
x =np.cos( np.pi * n/30 + phi)
print(np.dot(S, x)[0])
print(np.dot(S.T, x)[0])
```

### Error message:
```
True
[-9.15933995e-16]
[-4.88498131e-15]
```

### Python and NumPy Versions:

1.23.1

**Comment by Will-20** [comment]
Would this be a good first issue for a newb contributor?

**Comment by eendebakpt** [comment]
Another example where rounding errors can create unexpected results:
```
import numpy as np
x=np.exp(100*np.random.rand(10_000))
np.sum(x)- np.sum(x[::-1])
```
I suspect that due to the different layout of `S` and `S.t` the calculation is done in a different order which introduces small rounding errors.

For more (technical) information on floating point arithmetic, see https://floating-point-gui.de/ or https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by bjfrbjx** [comment]
ok，i got it。the “order” ......
