### ISSUE TITLE
BUG: debugging doesnt work in pycharm with numpy2.0

### ISSUE THREAD

**Issue by rtsscy** [numpy/numpy#26723]
### Describe the issue:

After upgrading to numpy2.0, running any test or any custom configuration on debug mode stops working in pycharm 2023.2.3. (Running tests still work) 
I get a exit code 1. Empty suite

### Reproduce the code example:

```python
-
```

### Python and NumPy Versions:

Python 3.11. Numpy 2.0.0

**Comment by rgommers** [comment]
Thanks for the report @rtsscy. I'm afraid we're going to need more detail here to say anything constructive. Are you getting any traceback? If not, does the issue still occur for you if you create a clean environment from scratch with numpy 2.0 (rather than upgrading an existing env? Or can you give step by step instructions on how to reproduce it (what command to run or button or menu item in PyCharm to use)?

**Comment by rtsscy** [comment]
I realised that i had to upgrade my pyarrow version, it is working now. Now blocked on issue 26710. Thanks!

**Comment by rgommers** [comment]
Great, thanks for the update!
