### ISSUE TITLE
BUG: Comparison functions return True_ or False_

### ISSUE THREAD

**Issue by bje-** [numpy/numpy#26774]
### Describe the issue:

Numpy comparisons don't return `True` or `False`. Instead, they return `np.True_` or `np.False_`. This is very clumsy and breaks a lot of my test cases. I tried this example from the 2.0 documentation:

https://numpy.org/doc/stable/reference/arrays.scalars.html

### Reproduce the code example:

```python
import numpy as np
f16 = np.float16("0.1")
f32 = np.float32("0.1")
f64 = np.float64("0.1")
f16 == f32 == f64
```

### Python and NumPy Versions:

2.0.0
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

### Context for the issue:

Like the documentation, I am expecting the result of the comparison to be `False`, not `np.False_`.

**Comment by andyfaff** [comment]
As far as I know comparison of numpy scalars in this manner has always returned a numpy boolean type.

On 1.26.4:

```
>>> f16 = np.float16("0.1")
>>> f32 = np.float32(f16)
>>> type(f16 == f32)
<class 'numpy.bool_'>
>>> f16 == f32
True
>>> repr(np.True_)
'True'
>>> np.True_ == True
True
>>> np.True_ is True
False
```

On 2.0.0:
```
>>> f16 = np.float16("0.1")
>>> f32 = np.float32(f16)
>>> type(f16 == f32)
<class 'numpy.bool'>
>>> f16 == f32
np.True_
>>> repr(np.True_)
'np.True_'
>>> str(np.True_)
True
>>> np.True_ == True
np.True_
>>> np.True_ is True
False
```

The only major difference between the two versions is that the `repr` has changed, to make it more like the canonical string representation required to reconstruct the object.

To reiterate the f16==f32 comparison has always returned `np.True_`/`np.False_`, and never `True`/`False`.

One should normally only reserve `x is True` for when you're trying to see if `x` is the actual `True` object. Otherwise you should be using `x == True`, or `if x:` (for scalars).

That said, the output 2.0 documentation is different to what is observed for in a REPL, and we should probably update it.

**Comment by bje-** [comment]
Thanks. I didn't think to interrogate the types, it just looked like a switch had been made from `bool` to `np.bool`. I am not concerned about backward compatibility issues with updating the doctests, but geez, it's ugly!

```python
>>> dist(1,43) == distances[1,43]
np.True_
```

**Comment by ngoldbaum** [comment]
Unfortunately it can't be named `np.True`, because `True` is a reserved keyword:

```
In [1]: np.True
  Cell In[1], line 1
    np.True
       ^
SyntaxError: invalid syntax
```

If you're updating doctests and don't want to fix them like it's an emergency, you might be interested in the "legacy" print mode in `np.printoptions`.
