### ISSUE TITLE
BUG: Incorrect representation of floats in numpy 2

### ISSUE THREAD

**Issue by elac-safran** [numpy/numpy#26864]
### Describe the issue:

The representation of float is meant to be disambiguated in numpy 2.

While this is a tad annoying for codes assuming that float64 should be represented as natural numbers, I understand it is a design choice. However, the representation of floats returns a string of the kind "np.float64(...)", rather than just "float64(...)".

This creates a nasty side effect when one tries to evaluate number representations using function `eval`.

Below is a screen capture of an `ipython` console.
Note that the `numpy.zeros(3)` returns `array([0., 0., 0.])`, not `np.array([0., 0., 0.])`.

![image](https://github.com/numpy/numpy/assets/84327932/1a301cc3-2d07-4b7b-b2b6-9625c2d37100)

### Reproduce the code example:

```python
import numpy

print(repr(numpy.zeros(3)))  # expected: "array([0., 0., 0.])" - OK

print(repr(numpy.cos(0.0)))
# expected: "float64(1.0)"
# actual: "np.float64(1.0)", with "np" hard-coded!

# Consequence:
eval(repr(numpy.zeros(3)), {"array": numpy.array})  # works

eval(repr(numpy.cos(0.0)), {"cos": numpy.cos})  # raises NameError: 'np' is not defined
```

### Python and NumPy Versions:

Python 3.12.4
Numpy 2.0.0

**Comment by rkern** [comment]
The right namespace for `eval()`ing (what is possible to `eval()`, at least) is `{'array': numpy.array, 'np': numpy}`. If `eval()`ing is your concern, we've made it easier by using `np.` than if we had left it out. Otherwise, you'd have to add a whole bunch of individual objects to that namespace. `array` is now an outlier (that we won't change now because it is so, so old).

In general, we're not too fussed about ensuring absolute roundtripping through `eval()`. And in any case, that roundtrip convention still requires one to specify an appropriate namespace context, the definition of which is left in the air.

**Comment by elac-safran** [comment]
Hello @rkern. Thank you for your reply.
I beg to differ, though:

1. Exposing the entire namespace in the global dictionary (using `eval`) is not good practice.
2. The package name is `numpy`, not `np`; the latter is a convenient alias, but should not be hard-coded in number representation.
3. There is a clear inconsistency between the representation of `array` and numpy floats (and possibly other symbols). By the way, `type(numpy.cos(0.0)` returns `numpy.float64`!

**Comment by rkern** [comment]
1. Using `eval()` at all isn't the best practice, either. In any case, you can make a dummy object with `float64` and the others explicitly listed as attributes and plop it into the namespace a `np`, if you want. It doesn't really change the security picture, though, if I recall all the clever jailbreaks you can do with just a `type` object. Again, we do not care much about roundtrippability through `eval()` per se.
2. That alias sure is convenient, though. Whether it should or shouldn't be in the repr is purely a matter of taste; there is no rule or guideline that says anything about it. As discussed in [NEP 51](https://numpy.org/neps/nep-0051-scalar-representation.html#alternatives), the kind of roundtrippability that we care (somewhat) about is users copy-pasting from the output into the input in an interactive prompt. And because we vigorously recommend that users `import numpy as np`, that means `np.`.
3. Yeah, it's inconsistent, and I pointed out why. As for what `type()` does, that's `type.__repr__` working (though I suspect you might be in IPython, in which case that gets overridden by IPython's pretty-printer), which we don't control (or care about being consistent with).

All this was litigated during the [NEP 51](https://numpy.org/neps/nep-0051-scalar-representation.html#alternatives) discussion. Since I don't think we're going to reopen that, so I'm going to go ahead and close this.
