### ISSUE TITLE
DOC: Running numpy2 with previous type promotion rules using np._set_promotion_state("legacy")

### ISSUE THREAD

**Issue by stenhasselquist** [numpy/numpy#26952]
### Issue with current documentation:

I don't explicitly see this in the migration guide documentation (https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide), but if we want to run code that uses the previous type promotion rules, we use:

`np._set_promotion_state("legacy")`

Will this be a feature that is supported in future releases of numpy, or are there plans to deprecate the "legacy" type promotion rules?

Thanks!

### Idea or request for content:

Some others like us might have reason to run their code using numpy 2.0 but with the previous type promotion rules, so there may be a need to explain the "legacy" option.

**Comment by ngoldbaum** [comment]
That function is private API.

The only public way to control the promotion behavior is via an environment variable read once at startup. Also I’m pretty sure the plan is to remove the old promotion code eventually.

**Comment by seberg** [comment]
> Will this be a feature that is supported in future releases of numpy, or are there plans to deprecate the "legacy" type promotion rules?

No the reason for the "feature" was mainly for implementation and experimentation *before* 2.0.  It is still there to assist tracking down changes  (there is also the `weak_and_warn` option and it might be helpful to try to avoid promotion changes).

It was never meant for production code, even if I know that a hand-full of people might have opted in to new behavior before NumPy 2.

There won't be a deprecation period either unless something huge new comes up at least.  The feature will just be gone in 2.1 (or maybe 2.2, since 2.1 has a super short release time probably).

**Comment by seberg** [comment]
Closing the option is removed for NumPy 2.2.
