### ISSUE TITLE
BUG: StringDType: integer indexed assignment does not work for arena strings.

### ISSUE THREAD

**Issue by egesip** [numpy/numpy#27003]
### Describe the issue:

When the strings are "allocated" in the arena (len >= 16), assignment through integer indexing does not modify the array.
Curiously, it works with boolean indexing.
Thanks !

### Reproduce the code example:

```python
import numpy as np
from numpy.dtypes import StringDType
a = np.array(['a'*16, 'b'*16], dtype=StringDType())
b = np.array(['d'*16, 'e'*16], dtype=StringDType())
a[[0, 1]] = b
print(a) # expecting ['d'*16, 'e'*16], but getting ['a'*16, 'b'*16]
# curiously a[[True, True]] = b works...
```

### Python and NumPy Versions:

2.0.1
3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]

**Comment by ngoldbaum** [comment]
Thanks for the report! I have a fix in #27047.

> curiously a[[True, True]] = b works...

The fancy indexing code is incredibly complicated. The case of indexing with a bool array uses a different code path from indexing with an int array. The former uses `array_assign_boolean_subscript`, which it turns out has always done the correct thing (since b272bc605ce anyway). Integer indexing used a codepath in `array_assign_subscript`, which makes the implicit assumption that input and output descriptors from a cast within the same dtype are equivalent. That was never true but it only really breaks inside NumPy with StringDType.
