### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by langeleipe** [numpy/numpy#27030]
### Steps to reproduce:

I installed numpy in klipper using https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/wiki/Measure-resonances-with-Fysetc-Portable-Input-Shaper 
After that I tried to use numpy based on https://www.klipper3d.org/Measuring_Resonances.html from the "measuring the resonances" section.
This were the commands I preformed regarding installing python, numpy and trying to use numpy:
sudo apt install python3-numpy python3-matplotlib libatlas-base-dev libopenblas-dev
~/klippy-env/bin/pip install -v numpy
~/klipper/scripts/calibrate_shaper.py /tmp/resonances_x_*.csv -o /tmp/shaper_calibrate_x.png

The calibrate_shaper.py tries to import numpy, numpy starts initialisation but fails to import numpy.core._multiarray_umath, see the error message below.
While browsing the "file explorer" I can find files like multiarray.py , a file umath.py , and a  file _multiarray_umath.cpython-38-arm-linux-gnueabihf.so  . I can't find a file named _multiarray_umath, and I am not allowed to change file names.

### Error message:

```shell
pi@speeder-pad:~$ ~/klipper/scripts/calibrate_shaper.py /tmp/resonances_x_*.csv -o /tmp/shaper_calibrate_x.png
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/klipper/scripts/calibrate_shaper.py", line 11, in <module>
    import numpy as np, matplotlib
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.9 from "/usr/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Additional information:

I am sorry for being stupid but I just don't understand why it isn't working. I tried the recommended steps, reinstalling numpy. I can't read the python3 file and I don't understand where to dictate the PATH but neither seems to be the issue?

**Comment by mattip** [comment]
I think the problem is here
```
sudo apt install python3-numpy python3-matplotlib libatlas-base-dev libopenblas-dev
~/klippy-env/bin/pip install -v numpy
~/klipper/scripts/calibrate_shaper.py /tmp/resonances_x_*.csv -o /tmp/shaper_calibr
```

You are `apt` installing a numpy into your system's `python3`, and also `pip` installing a numpy into your `~/klippy-env` virtualenv. But then when running the script, you are using the system python, not the one in your `~/klippy-env`. So let's try analyze what is going on. 

### your system python
This is the one at `/usr/bin/python3`, and is currently used to run the script. But somehow this is python3.9. What version of operating system are you running? If I recall correctly, Ubuntu 20.04 shipped with python3.8, Ubuntu 22.04 shipped with python3.10. I think when you `sudo apt install python3-numpy` you are installing a numpy for a different version of python than the one in `/usr/bin/python3`. That whole mess is why people use virtual environments (or conda environments): to isolate their project python from their operating system python.

### the `klippy-env`
Apparently you have created a virtual environment, but are not using it. To "activate" the virtual environment (which is highly recommended), you should run `source ~/klippy-env/bin/activate`. Now when you run `which python3`, you should see `~/klippy-env/bin/python3`, and when you run `python3 -c "import numpy; print(numpy)" you should see a path inside the virtual environment

### running your script
In general, I always try to specify the python I use to run a script, so instead of
```
~/klipper/scripts/calibrate_shaper.py ...
```

I would verify `which python3` points to the correct python, and then explicitly use
```
python3 ~/klipper/scripts/calibrate_shaper.py
```
