### ISSUE TITLE
BUG: Disagreement between apt python3-numpy and pypi numpy versions

### ISSUE THREAD

**Issue by 23pointsNorth** [numpy/numpy#27039]
### Describe the issue:

There is a disagreement between the apt and pypi versions, meaning that installing libraries from both would depend on different version of numpy. I haven't seen a discussion that would point to a particular reason for halting the 2.0 in the apt package.

Apt:
```
apt search python3-numpy
Sorting... Done
Full Text Search... Done
python3-numpy/jammy-updates,jammy-security,now 1:1.21.5-1ubuntu22.04.1 amd64 [installed,automatic]
  Fast array facility to the Python 3 language
```

Pypi: https://pypi.org/project/numpy/ -> `2.0.1`

Would it be possible to syncronize the packages, such that e.g. the whole ROS [ecosystem](https://github.com/ros-perception/vision_opencv/issues/535) and transition to numpy 2.0.

### Reproduce the code example:

```python
none
```

### Python and NumPy Versions:

1.21.5 and 2.0.1

**Comment by seberg** [comment]
It is the job of the user to make sure that versions are compatible.  Debian ships some versions and they are all consistent and compatible.

If for some reason, a user installs a newer NumPy into an environment (presumably, since debian will give huge warnings about modifying the main install), then they may have to update other libraries too.  OpenCV has compatible libraries available.

If you have a concrete question about how to update a library to be compatible, please don't hesitate to continue.  But the version that debian ships is not an issue, it is just at an older state (and must remain there).
