### ISSUE TITLE
BUG: ARGSORT does not work for ndarray elements in (0,1) and many decimals

### ISSUE THREAD

**Issue by Fractal2017** [numpy/numpy#27103]
### Create a sample array (a 1D NumPy array) where each element is an array of one element, with values between 0 and 1, with at least 8 decimal places
data = np.array([[0.12345678], [0.90123456], [0.98765432], [0.00001234], [0.56789012]])

print("Original data:")
print(data)
```
Original data:
[[1.2345678e-01]
 [9.0123456e-01]
 [9.8765432e-01]
 [1.2340000e-05]
 [5.6789012e-01]]
```
### argsort should get the indices sorted but somehow it only uses one value 0
indices = np.argsort(data)

print("\nSorted indices:")
print(indices)
```
Sorted indices:
[[0]
 [0]
 [0]
 [0]
 [0]]
```

### As a result sorting the array does not produce the order expected
sorted_data = data[indices]
print("\nSorted data:")
print(sorted_data)
```
Sorted data:
[[[0.12345678]]
 [[0.12345678]]
 [[0.12345678]]
 [[0.12345678]]
 [[0.12345678]]]
```

### Reproduce the code example:

```python
import numpy as np

# Create a sample array (a 1D NumPy array) where each element is an array of one element each, with values between 0 and 1, to at least 8 decimal places, without scientific notation
data = np.array([[0.12345678], [0.90123456], [0.98765432], [0.00001234], [0.56789012]])

print("Original data:")
print(data)

# Use argsort to get the indices of sorted array
indices = np.argsort(data)

print("\nSorted indices:")
print(indices)

# Now you can use these indices to sort your original array
sorted_data = data[indices]
print("\nSorted data:")
print(sorted_data)
```

### Error message:

```shell
No error message
```

### Python and NumPy Versions:

Numpy == 1.26.4
Python == 3.12.4

### Context for the issue:

Using argsort to obtain the top K values after sorting an array of values from a cosine distance calculation

**Comment by WarrenWeckesser** [comment]
Your array `data` is a *two-dimensional array*, with shape (5, 1). By default `argsort` acts along the *last* axis of the input array.  In your case, `argsort` is applied to each (trivial) row, and since each row contains just one element, the result for each row is `[0]`.

Either add the argument `axis=0` (e.g. `argsort(data, axis=0)`) to apply `argsort` to each column (which means just the one column that you have), or flatten the input (e.g. `argsort(data.ravel())`) so that `argsort` is applied to all the data, treated as a 1-d array.
