### ISSUE TITLE
BUG: np.argwhere(torch tensor).shape != (np.argwhere(np array).shape == torch.argwhere(torch tensor).shape)

### ISSUE THREAD

**Issue by guillaume-troadec** [numpy/numpy#27138]
### Describe the issue:

When computing the argwhere of a torch tensor using np.argwhere, the shape is flipped compared to computing torch.argwhere on a torch tensor, and np.argwhere on a np.array.

Perhaps this might be intended behaviour and not a bug, but at the very least I think this would benefit from clearer documentation given this inconsistency silently occurs.

Thanks for maintaining numpy, have a nice day :) 

### Reproduce the code example:

```python
import torch
import numpy as np

torch.manual_seed(0)

a = torch.rand((5, 4, 2)) > 0.5

# torch.argwhere of a torch.Tensor
b = torch.argwhere(a)

# np.argwhere of a torch.Tensor
c = np.argwhere(a)

# np.argwhere of a np.array
d = np.argwhere(np.array(a))

print(b.shape) # 16, 3
print(c.shape) # 3, 16
print(d.shape) # 16, 3
```

### Python and NumPy Versions:

1.26.4
3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 9.4.0]

**Comment by jakevdp** [comment]
This happens because `argwhere` uses the `nonzero` method of the input, and torch has a different implementation of `nonzero` than NumPy:
```python
print(np.shape(a.nonzero()))
# torch.Size([16, 3])

a_np = np.asarray(a)
print(np.shape(a_np.nonzero()))
# (3, 16)
```
In general, if you're mixing array libraries I'd suggest explicitly converting your arrays to numpy before calling any numpy functions, otherwise you'll likely run into inconsistencies like this one.

**Comment by ngoldbaum** [comment]
Closing since this isn't a NumPy issue per se and there's a workaround.
