### ISSUE TITLE
BUG: `np.ma.allequal` fails when comparing masked array with itself

### ISSUE THREAD

**Issue by MatejUrbanQC** [numpy/numpy#27201]
### Describe the issue:

`np.ma.allequal(a, a, fill_value=False)` should return `True` if `a` is a masked array with the mask being all `False`

It works if the mask is `nomask` but not if it is `[False, False, ...]`

The bug only occurs if the masks of the two arrays are object equal (see example)

### Reproduce the code example:

```python
import numpy as np
a = np.ma.masked_array([1,2,3], mask=[0,0,0])
b = np.ma.masked_array([1,2,3], mask=[0,0,0])
assert np.ma.allequal(a, b, fill_value=False) # this works
assert np.ma.allequal(a, a, fill_value=False) # this fails
```

### Python and NumPy Versions:

numpy: 2.0.0
python: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]

**Comment by ianharris** [comment]
I had a look at this. The `np.ma.allequal` function contains three conditional blocks. An if, and elif, and an else. In the failing case above the else block is being executed, which simply returns `False`. The elif block is not executed as it's conditional is the boolean `fill_value`. And the if statement is not executed because in this case, the condition can never be True - which I'm not sure is the intention.

The issue seems to arise from the `np.ma.mask_or` function which is called to make a logical OR mask from the masks of the two masked arrays input into `allequal`. In the specific case where the two input masked arrays are the same, `mask_or` will return the mask of the first input array. In other cases, `mask_or` will try to "shrink" the mask. Shrinking the masks in the examples above would give the value `np.ma.nomask`.

Returning to the if statement in `allequal` the condition is that the logical OR mask has the value `nomask`. I believe there are three possible solutions:

1. Modify `mask_or` so that it tries to shrink the mask in this case. This could potentially break other functionality though.
2. Call `_shrink_mask` on the mask returned from the call to `mask_or` within the `allequal` function.
3. Add a conditional check to the start of `allequal` to check if the two input masked arrays reference the same object.

I'm interested in contributing so happy to implement a fix. But it would be good to get an opinion from a more seasoned contributor about which strategy to pursue.

**Comment by mattip** [comment]
#27360 closed this. Please reopen or open a new issue if there is still more to do.
