### ISSUE TITLE
ENH: linear combination 

### ISSUE THREAD

**Issue by bp208322** [numpy/numpy#27370]
### Proposed new feature or change:

In order to compute efficiently $y = a_1 \cdot x_1 + a_2 \cdot x_2 + ... $,
a practical syntax would be: 
`y = np.linear_combination(a,[x1,x2,...])` with `a` 1d-array and any `[x1, x2, ...]` of the same length

**Comment by bp208322** [comment]
Hereafter is an example where the linear combination is made by hand.
Maybe there exist some numpy functions doing the job but I don't see how.
```python
import numpy as np 

# elementary (3,3)-arrays
x1 = np.array([0,1,1, 0,0,1, 0,0,0]).reshape(3,3)
x2 = np.eye(3)
x3 = np.array([0,0,0, 1,0,0, 1,1,0]).reshape(3,3)
x = np.array([x1,x2,x3])
print('x=\n',x)

# coefficients
a = np.array([1,2,3])
print('a=\n',a)

# linear combination
y = (a[0]*x[0]) + (a[1]*x[1]) + (a[2]*x[2])
print('y=\n',y)
```

**Comment by ianharris** [comment]
From the documentation: https://numpy.org/doc/stable/reference/generated/numpy.dot.html

> numpy.dot(a, b, out=None)
> ...
> * If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

which is similar to the case you have above - just your axes for `x` are in a different order. In this case, you could transpose your `x` `ndarray` before calling `dot` to get the linear combination result. For example:

```
y = x.transpose([1, 2, 0]).dot(a)
```

**Comment by bp208322** [comment]
Thank you @ianharris ! It solves my question.
Maybe to add in the examples section of `dot` documentation ?

**Comment by ianharris** [comment]
As it's a documented case, I think there is merit in adding an example. However, a final decision on it's inclusion would be up to one of the maintainers; I'm guessing there is a balancing act between providing enough examples to provide clarity, but not so many that the documentation becomes too long.

That said, if you're interested, you could open a PR and then see what feedback you get from reviewers. If you do, I'd modify the example you have above, however. Specifically, you can do it without the `transpose` function. I think it's important to keep an example as focused as possible to the functionality you're trying to show. So, I would modify it to:

```
    The linear combination of 2-D arrays 
    `y[i, j] = sum(a[:] * x[i, j, :])`
    can be obtained through the following:

    >>> x1 = np.eye(3)
    >>> x2 = np.ones((3, 3))
    >>> x3 = np.array([[0, 1, 1], [0, 0, 1], [0, 0, 0]])
    >>> x = np.stack([x1, x2, x3], axis=-1)
    >>> a = np.array([1, -1, 2])
    >>> y = np.dot(x, a)
```

The changes I've made.

1. Updated spacing in the example to align with common standards,
2. Created `x3` as a (3, 3) ndarray rather than a 1-D array and then reshaping,
3. Created `x` using `np.stack` with an argument of `axis=-1` - this stacks `x1`, `x2`, and `x3` in the order we want for the dot product so no need for the `transpose`.

A PR will probably need an associated github issue. I'm not sure if the norm for this repo is to update the existing issue or create a new one, though.

**Comment by mhvk** [comment]
`.dot` is actually often a bit tricky because it is hard to get it to do the same for a stack of vectors `a` instead of a single one. Easier is the more recent addition of `vecdot`:
```
np.vecdot(x, a, axis=0)
array([[2., 1., 1.],
       [3., 2., 1.],
       [3., 3., 2.]])
```

In terms of documentation, I agree with @ianharris's worry that the documentation would become too long. So, I think the first question, @bp208322, is whether you raised the issue because you knew about `dot` and `vecdot`, but didn't realize they were applicable after reading their docstrings, or that you didn't realize there were ways to get an inner product? (note there's even `np.inner` -- `np.inner(x.transpose([1, 2, 0]), a)` also gives the right answer). A simpler PR that would just help a bit is to add `vecdot` to the `See Also` sections of `np.dot` and `np.inner`, as well as the `ndarray.dot` method.

**Comment by bp208322** [comment]
Thanks for the answer.
I knew about `dot`, but not `vecdot` which is finally the ideal solution for me.
I'm using Python daily for about 1 year which is probably short and usually find answer in the doc or on stackoverflow.com, but not in this case. That is why I opened (maybe too fast) this issue.
`See also vecdot` would probably have helped me.

**Comment by charris** [comment]
> See also vecdot would probably have helped me.

Want to make a PR for that?

**Comment by mhvk** [comment]
`vecdot` is fairly recent, so no surprise that it is not yet mentioned much.  PR to add it to `See Also` appreciated!

A PR would indeed be welcome. I just checked, and `np.ndarray.dot` does not have a docstring at all - so just `np.dot` and `np.inner` would suffice.
