### ISSUE TITLE
BUG: populating the identity cache is not thread safe

### ISSUE THREAD

**Issue by jakevdp** [numpy/numpy#27386]
### Describe the issue:

Using `np.finfo` and `np.iinfo` with Python 3.13/numpy 2.1 free-threading can lead to errors like the following:
```
  >     return ml_dtypes.finfo(dtype).min < 0
  E     RuntimeError: Identity cache already includes an item with this key.
```
(source: https://github.com/jax-ml/ml_dtypes/actions/runs/10840175629/job/30081990075?pr=188)
`ml_dtypes.finfo` inherits from `numpy.finfo`, and this error is coming from the NumPy implementation; looks to be a race condition when multiple threads hit the Identity cache at once.

### Python and NumPy Versions:

Python 3.13; numpy 2.1

**Comment by ngoldbaum** [comment]
I think this might actually be happening because of `pytest-xdist`? I only see test failures running the `ml_dtypes` tests locally under `pytest-xdist`.

**Comment by ngoldbaum** [comment]
Also on my Mac `CustomFloatTest.testRoundTripToInt_float8_e8m0fnu_multi_threaded` is not collected by pytest, I'm not sure how to run that test.

**Comment by jakevdp** [comment]
We disabled the test at head, so if you're trying to run the ml_dtypes tests you'll have to use an older commit.

Sorry I wasn't able to put together a numpy-only reproducer, but I figured it would be pretty straightforward if you have a Python 3.13 free-threading environment locally

**Comment by ngoldbaum** [comment]
OK, I can reproduce this on my mac reasonably reliably with `pytest -n 100`.

I ran plain `pytest` with no `pytest-xdist` in a loop for five minutes and never saw test failures, so I'd like to understand why that matters.

I don't actually know much about `pytest-xdist` so I'm not sure why it matters here.

**Comment by ngoldbaum** [comment]
Reading up on how `pytest-xdist` works - it's spinning up new python executables and communicating with them over sockets. I think that `xdist` simply makes it much more likely to hit threading bugs, especially if tests themselves spawn threads. You can easily hit a situation where the number of threads in use is substantially larger than the number of hardware threads and timing bugs begin to be easier to hit.

I think the "Identity cache already includes an item with this key." error is happening because while we added locking to the identity cache, we never actually made sure that filling it happens on only one core. I convinced myself back in https://github.com/numpy/numpy/pull/26693 that a pointer comparison check would be sufficient, but that's clearly not the case here.

I think the real fix is to lock the dispatch cache with a critical section while the `promote_and_get_info_and_ufuncimpl` recursion is happening. I have a fix I'm working on along those lines, hopefully there will be a PR.

It looks like the Jax test suite will once again be a great way of discovering NumPy bugs! I

t might also make sense for us to add locking around the C API functions that touch NumPy's global ufunc state - it looks like a lot of the remaining test failures I'm seeing are related to that.
