### ISSUE TITLE
Operator inconsistency

### ISSUE THREAD

**Issue by ananski-the-3rd** [numpy/numpy#27393]
### Describe the issue:

Consider the following examples:

Note that the only difference between Ex. 1 and Ex. 2 is that the second used the shorthand "*=" operator whereas the first uses assignment and multiplication separately. The two should be equivalent, but they are not.

Ex. 1 prints:
[[4]
 [2]]

Ex. 2 throws an error.

### Reproduce the code example:

```python
## Ex. 1:

import numpy as np
a = np.array([[3], [2]])
a[0] = a[0] * 1.5
print(a)


## Ex. 2
import numpy as np
a = np.array([[3], [2]])
a[0] *= 1.5
print(a)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<main.py>", line 12, in <module>
numpy._core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

### Python and NumPy Versions:

3.12
2.1.1

**Comment by gamc12world** [comment]
I  think NumPy arrays can perform any kind of ufunc operation, but they require compatible data types.

**Comment by rkern** [comment]
Basic operators like `*` are implemented by so-called [ufuncs](https://numpy.org/doc/2.1/reference/ufuncs.html) that will dispatch the actual computation to efficient C code based on the dtypes of the inputs, but _also_ the dtype of the _output_ if it's known. If you look at the signature for [`np.multiply`](https://numpy.org/doc/2.1/reference/generated/numpy.multiply.html), you will see that it can take an optional `out=` argument that will be the array to write the data to.

When you do `a[0] = a[0] * 1.5`, this gets turned into, roughly, `a[0] = np.multiply(a[0], 1.5)`. No `out=` argument specified. So it only looks at the dtypes of the inputs to decide which dtype-specific implementation to dispatch to. For our purposes, there are 2 implementations to look at, one that does `int64 * int64 -> int64` and one that does `float64 * float64 -> float64`. Since the inputs are mixed, we try our casting rules and see that `int64` can be upcast to `float64`, so the integer input is cast to a `float64` and the `float64 * float64 -> float64` implementation gets used. The result of that gets downcast back to `int64` when `a[0] = ...` goes to assign the value back into the array.

When you do `a[0] *= 1.5`, however, something a little different happens. Since the output destination is now known (`a[0]` is an `int64` array), the implementation of the inplace multiplication operator essentially does this: `np.multiply(a[0], 1.5, out=a[0])`. This causes the ufunc to look for a loop that can deal with `int64 * float64 -> int64`. Since our rules decide based on the inputs that `float64 * float64 -> float64` is the only implementation that we can use, it then checks to see if the `float64` output can be downcast back to the `int64` output that is fixed. Our default rules dictate that we cannot safely downcast that way (for ufunc resolution).

It *is* a good question why the downcast is allowed during assignment (e.g. `a[0] = 4.5`) but not during inplace arithmetic. Allowing the downcast during assignment is a deliberate design decision that allows us to more comfortably work with low-precision arrays and still use plain Python `int`s and `float`s to manipulate them without having to first convert them all to the low-precision scalar types. We can't really do that in the inplace arithmetic because the ufuncs don't know that they are being called in that context. We know that this is a kind of an inconsistency, but it's one that we are generally comfortable with.
