### ISSUE TITLE
Inconsistent promotion rules for comparison/equality operators

### ISSUE THREAD

**Issue by bemoody** [numpy/numpy#27572]
In numpy 1.24.0 through 1.26.4, if NPY_PROMOTION_STATE is set to "weak", the following expressions raise an OverflowError:
```
np.int8(1) < 1000
np.int8(1) <= 1000
np.int8(1) == 1000
np.int8(1) != 1000
np.int8(1) > 1000
np.int8(1) >= 1000
```
In numpy 2.x, in contrast, all of these give the expected (mathematically correct) results.  (Likewise, they all give the expected results when NPY_PROMOTION_STATE is set to "legacy".)

Given that I think the intention for NPY_PROMOTION_STATE is to provide behavior that is forward-compatible with 2.x, can this be fixed in 1.26?

A non-trivial example is https://github.com/pandas-dev/pandas/issues/60023 : pandas uses comparisons involving INT64_MIN / (U)INT64_MAX to determine whether a value can be safely cast to a numpy integer.

Raising exceptions for __eq__ and __ne__ can also give some *particularly* surprising results, such as
```
np.int8(1) == np.int32(1000) == 1000 is False
np.int8(1) == 1000 == np.int32(1000) is an overflow error

{9} == {np.int8(9)} is True
{0x1_0000_0000_0000_0000} == {np.int8(9)} is False
{0x1_0000_0000_0000_0001} == {np.int8(9)} is an overflow error
```

**Comment by seberg** [comment]
No, it can't be changed.  The intention of the promotion state was for testing: both to prepare libraries for the switch and to see how the change affected downstream.
Since NumPy 2 is released, it is probably better to just use that for testing purposes (it also has the promotion state switch for testing purposes).

So if you are using this for testing, sorry, I can only suggest to use NumPy 2.  If you are using this for production: that is your choice, but you are on your own if things don't work.
