### ISSUE TITLE
BUG: Accumulation uses wrong logic to decide GIL release

### ISSUE THREAD

**Issue by hawkinsp** [numpy/numpy#27709]
### Describe the issue:

`generic_wrapped_legacy_loop` calls `PyErr_Occurred`, which requires the GIL: https://github.com/numpy/numpy/blob/98464cc0cbc1f211482a0756ded305bed1599f18/numpy/_core/src/umath/legacy_array_method.c#L99

This function can be called from `PyUFunc_Accumulate` in a context where the GIL has been released: https://github.com/numpy/numpy/blob/98464cc0cbc1f211482a0756ded305bed1599f18/numpy/_core/src/umath/ufunc_object.c#L2925

We may release the GIL for a large array if https://github.com/numpy/numpy/blob/98464cc0cbc1f211482a0756ded305bed1599f18/numpy/_core/src/umath/ufunc_object.c#L2919C25-L2919C42 `PyDataType_REFCHK(descrs[0])` is true, but that's not a sufficient test: a legacy dtype, even those that do not require reference counting may lead to `generic_wrapped_legacy_loop` being called. In the repro below, this happens with `ml_dtypes.bfloat16`, from the `ml-dtypes` pip package.

### Reproduce the code example:

```python
In [1]: import numpy as np, ml_dtypes
In [2]: x = np.zeros((999999,), ml_dtypes.bfloat16)
In [3]: np.cumsum(x)
Segmentation fault: 11
```

### Error message:

```shell
Segfault. If Python is built with debugging enabled, then we received a `PyGILState_Check` error from `PyErr_Occurred`.
```

### Python and NumPy Versions:

2.1.3
3.12.3 (main, May 30 2024, 08:00:27) [Clang 15.0.0 (clang-1500.3.9.4)]

### Runtime Environment:

n/a

### Context for the issue:

Running TensorFlow's tests under NumPy 2.1.3.

**Comment by ngoldbaum** [comment]
Just to clarify, is this a regression or a new issue you noticed?

**Comment by hawkinsp** [comment]
I noticed it when trying a NumPy 2.1.3 upgrade: it was literally the only new test that broke in Google's entire codebase under NumPy 2.1.3 versus 2.1.2. Why the two differ I do not know. (The test that failed is this one: https://github.com/tensorflow/tensorflow/blob/e4456065ee3454e82ffd8510de066f0ab9053dc3/tensorflow/python/kernel_tests/control_flow/scan_ops_test.py#L154 from which I distilled the reproducer above)

I hesitate to call it a recent regression because I can produce a segfault with earlier NumPy versions on my laptop, even back to 1.26 or earlier.

**Comment by ngoldbaum** [comment]
Weird, thanks for the detail and the thorough analysis.

**Comment by ngoldbaum** [comment]
https://github.com/numpy/numpy/commit/6756b4ee005c25a4f66ac89fdd4d86180e7e8363 looks like a possible culprit for triggering a new code path in the tensorflow test, I don't see anything else that seems related in the commit log for 2.1.3.

**Comment by seberg** [comment]
> but that's not a sufficient test: a legacy dtype, even those that do not require reference counting may lead to generic_wrapped_legacy_loop being called

Yes, they'll always go into this code path, but that is why the `ldata->pyerr_check` is there.

There is a disconnect here, the accumulate code isn't quite up-to-date, it assumes pyapi is equivalent to `hasobject` which is wrong.  It should be using the loop flags instead so that is a bug.

That said: `np.dtype(ml_dtypes.bfloat16).flags & 16 != 0`.  You are indicating the need for the Python API for some reason, and NumPy honors that for ufuncs.  That is correct, I think, although I don't think you should need it?!
@hawkinsp are you sure you want to set this flag?

So there we are checking for errors (correct based on flags!), but accumulate has a bug because it incorrectly thinks the GIL doesn't have to be released.

**Comment by hawkinsp** [comment]
> That said: `np.dtype(ml_dtypes.bfloat16).flags & 16 != 0`. You are indicating the need for the Python API for some reason, and NumPy honors that for ufuncs. That is correct, I think, although I don't think you should need it?! @hawkinsp are you sure you want to set this flag?

I don't think so, fixed in https://github.com/jax-ml/ml_dtypes/pull/231. We've apparently set this since the very first version of this code in 2017.

I'll note the docs here: https://numpy.org/devdocs/reference/c-api/types-and-structures.html#c.NPY_NEEDS_PYAPI
are fairly vague as to precisely what this flag means.

Per the docs:
> Indicates this data-type requires the Python C-API during access (so don’t give up the GIL if array access is going to be needed).

What exactly is "array access" in this sentence? Access from ufuncs? Access via, say, the buffer protocol? Access from some of the PyArray_ArrFuncs?

> 
> So there we are checking for errors (correct based on flags!), but accumulate has a bug because it incorrectly thinks the GIL doesn't have to be released.

Yes, I think NumPy still has a bug here.

**Comment by seberg** [comment]
> What exactly is "array access" in this sentence?

IMO, the only thing that makes sense is "everything", and that is what the code does overall, I think.  But, I bet it was also very unclear in places.

Of course, I strongly dislike the idea of "everything", since it can reasonably differ (e.g. some casts need it, but not all or so).  So the underlying machinery is now finegrained, but falls back to this.
