### ISSUE TITLE
BUG: bit generator spawns different child generators despite having the same random state

### ISSUE THREAD

**Issue by JakobGruen** [numpy/numpy#27882]
### Describe the issue:

When using the `default_rng` to spawn child rngs, the random states of the children are different, even if I reset the state of the parent generator. 

If the random states are the same, all the generators' functions should produce the same result given the same input. I think this should include spawning children. 

### Reproduce the code example:

```python
import numpy as np

# create rng and save state
rng = np.random.default_rng()
print(rng.bit_generator.state)
state = rng.bit_generator.state

# spawn a child
child1 = rng.spawn(1)[0]
print(child1.bit_generator.state)
print(child1.uniform(0, 1, 2))

# reset the state and confirm
rng.bit_generator.state = state
print(rng.bit_generator.state == state)

child2 = rng.spawn(1)[0]
print(child2.bit_generator.state)
print(child2.uniform(0, 1, 2))
```

### Python and NumPy Versions:

Python 3.12.7

numpy 1.26.4
Also in numpy 2.1.3

### Context for the issue:

I am not completely sure if this is a bug or intentional behavior, but it is confusing at least. I could not find any explanation of this behavior in the documentation and it seems counterintuitive. 

If the seed is set for the first rng, it still produces different child states, but they are always the same. 

I was trying to spawn child and grandchild rngs to be able to reproduce only parts of my simulation without having to rerun everything. But when I tried to recreate it from a child rng, I got different results. If I set the seed in the beginning, I can still recreate the whole simulation and I could create a list of new seeds instead of spawning children, but I would prefer not to do it that way.

**Comment by rkern** [comment]
Spawning is [covered here](https://numpy.org/doc/2.1/reference/random/parallel.html#seedsequence-spawn). Please note that the state that is spawned is the `SeedSequence` from the initial seeding of the `BitGenerator`, not the current state of the `BitGenerator`. This is somewhat obscured by `Generator.spawn()` really being syntactic sugar for reaching down to call `SeedSequence.spawn()`, but we do point to the documentation that covers it thoroughly.

We can still talk about solving your problem, but we'd need more details, and the [Discourse forum](https://discuss.scientific-python.org/) would probably be a better venue. In short, my advice would probably be to avoid resetting the states of `BitGenerator`s. I don't know what your use case is for it, but there's probably better ways to accomplish what you are doing. I've discussed similar use cases [here](https://github.com/scikit-learn/scikit-learn/issues/16988#issuecomment-1518037853) and [here](https://github.com/scipy/scipy/issues/18078#issue-1606033097) with recommended patterns.

**Comment by rkern** [comment]
Spawning `Generator`s in the parent process and sending them down to the child processes should still work fine and insulate you from the details of working manually with `SeedSequence` (also a viable option, but there are simpler ways). You do need to save the spawned `Generator` faithfully (i.e. by `pickle`) immediately before consuming anything from them (either random method calls or further spawning), but that would be good practice, regardless.

I suspect what led you down the wrong path was trying to manually reach into the PRNG state and saving that instead of using `pickle`, which will save every important detail, including the `SeedSequence` state. See this [discussion](https://mail.python.org/archives/list/numpy-discussion@python.org/message/AMJFEIDQAOSHRRXK4HFBQVJGBFHGVGQK/) for more details and alternatives (if you absolutely must avoid `pickle`).

**Comment by JakobGruen** [comment]
Yes, I suppose using `pickle` would be the best option. I was passing along some other parameters in a JSON file (so that I can read it easily) and wanted to avoid adding another file. But as you say, that led me down the wrong path...
