### ISSUE TITLE
DOC: Explicitly spell out abi3 (in)compatibility

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#27979]
### Issue with current documentation:

I have built a number of packages against NumPy and looked at things like the [depending on NumPy](https://numpy.org/devdocs/dev/depending_on_numpy.html#understanding-numpy-s-versioning-and-api-abi-stability) docs. However, I don't see it mentioned anywhere under what circumstances you can safely build `abi3` wheels, if any (and I actually don't know the answer :facepalm: !). So it would be great to add a note about this explicitly to the docs.

### Idea or request for content:

:point_up:

**Comment by ngoldbaum** [comment]
We do test building a C extension with the Python 3.6 and latest limited API, using both C and Cython:

https://github.com/numpy/numpy/blob/main/numpy/_core/tests/test_limited_api.py

So I'd say "it's supported" and we'd like to hear bug reports if you run into any issues.

Doc updates to the C API docs indicating our support for building third-party extensions that use the numpy C API are welcome.

**Comment by seberg** [comment]
There are at most two notes:
1. There are some niche APIs that cannot be public in the stable API.
2. There were issues/bugs in the header before NumPy 2 (and also one later on newer Python versions due to a Python header change).
   But that isn't much of a limitation in practice anymore, since you can just pin to a newer version if you run into it.

Basically, there is nothing in NumPy that would have a problem with the stable API, unless the API exposes Python internals that are not exposed.
