### ISSUE TITLE
BUG: lexsort segfaults on StringDType

### ISSUE THREAD

**Issue by otsaloma** [numpy/numpy#27984]
### Describe the issue:

Hi! I've been switching some code to the new `StringDType` and I came across a segfault when feeding `StringDType` arrays to lexsort. The example below is the same as in the documentation for lexsort: https://numpy.org/doc/stable/reference/generated/numpy.lexsort.html

### Reproduce the code example:

```python
#!/usr/bin/env python3

import numpy as np
from numpy.dtypes import StringDType

# Works
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
print(ind)

# Works
surnames2 = np.array(surnames, str)
first_names2 = np.array(first_names, str)
ind = np.lexsort((first_names2, surnames2))
print(ind)

# Segfaults
surnames2 = np.array(surnames, StringDType())
first_names2 = np.array(first_names, StringDType())
ind = np.lexsort((first_names2, surnames2))
print(ind)
```

### Python and NumPy Versions:

```
2.2.0
3.12.8 (main, Dec  4 2024, 12:15:27) [GCC 14.2.0]
```

### Runtime Environment:

```
[{'numpy_version': '2.2.0',
  'python': '3.12.8 (main, Dec  4 2024, 12:15:27) [GCC 14.2.0]',
  'uname': uname_result(system='Linux', node='thalatta', release='6.11.10-amd64', version='#1 SMP PREEMPT_DYNAMIC Debian 6.11.10-1 (2024-11-23)', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '.../venv/lib/python3.12/site-packages/numpy.libs/libscipy_openblas64_-6bb31eeb.so',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.28'}]
```

**Comment by tail-call** [comment]
Reproduces on Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.4)] on darwin, Numpy 2.2.0

<details><summary>Crash log</summary>
<pre>
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Python [69601]
Path:                  /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.13.0 (3.13.0)
Code Type:             X86-64 (Translated)
Parent Process:        zsh [69583]
Responsible:           kitty [1231]
User ID:               503

Date/Time:             2024-12-12 10:06:41.9720 +0700
OS Version:            macOS 14.6.1 (23G93)
Report Version:        12
Anonymous UUID:        66111A0E-A8EE-8FA5-8BA0-50DD5D0F521A

Sleep/Wake UUID:       19CEACD9-F374-45F1-8E7A-C409CDF51582

Time Awake Since Boot: 280000 seconds
Time Since Wake:       1892 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x10B2E746D)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000070
Exception Codes:       0x0000000000000001, 0x0000000000000070

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [69601]

VM Region Info: 0x70 is not in any region.  Bytes before following region: 4331028368
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      102264000-102266000    [    8K] r-x/r-x SM=COW  /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x10B2E746D)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Python                        	       0x10b2e746d PyErr_Occurred + 16
1   _multiarray_umath.cpython-313-darwin.so	       0x10c335b06 PyArray_LexSort + 2454
2   _multiarray_umath.cpython-313-darwin.so	       0x10c352a6a array_lexsort + 138
3   Python                        	       0x10b1de187 cfunction_vectorcall_FASTCALL_KEYWORDS + 94
4   Python                        	       0x10b181d6d PyObject_Vectorcall + 75
5   _multiarray_umath.cpython-313-darwin.so	       0x10c2f1c78 dispatcher_vectorcall + 376
6   Python                        	       0x10b181d6d PyObject_Vectorcall + 75
7   Python                        	       0x10b2b5411 _PyEval_EvalFrameDefault + 10898
8   Python                        	       0x10b2b27d6 PyEval_EvalCode + 207
9   Python                        	       0x10b3284b5 run_eval_code_obj + 97
10  Python                        	       0x10b327e26 run_mod + 157
11  Python                        	       0x10b32673e pyrun_file + 141
12  Python                        	       0x10b325b58 _PyRun_SimpleFileObject + 272
13  Python                        	       0x10b325818 _PyRun_AnyFileObject + 66
14  Python                        	       0x10b34e6cf pymain_run_file_obj + 187
15  Python                        	       0x10b34e3b9 pymain_run_file + 94
16  Python                        	       0x10b34d513 Py_RunMain + 1263
17  Python                        	       0x10b34dbdb pymain_main + 371
18  Python                        	       0x10b34dc8e Py_BytesMain + 42
19  dyld                          	       0x20245b345 start + 1909

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffe21414 0x7ff7ffe1d000 + 17428


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00006000017080e0  rcx: 0x0000000000000003  rdx: 0x0000000000000003
  rdi: 0x000000010b589160  rsi: 0x0000000000000003  rbp: 0x00000003057a3230  rsp: 0x00000003057a3230
   r8: 0x0000000000000061   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000002
  r12: 0x0000000000000000  r13: 0x000000010b100b10  r14: 0x00006000017080b0  r15: 0x000000010c39c170
  rip: <unavailable>       rfl: 0x0000000000000202
 tmp0: 0x000000010b2e746a tmp1: 0x000000010b2e746a tmp2: 0x000000010b938ec4


Binary Images:
       0x202455000 -        0x2024e5fff dyld (*) <18f658dd-20f3-324d-b7ac-8a9c60b574b3> /usr/lib/dyld
       0x10bbd7000 -        0x10bbfefff _umath_linalg.cpython-313-darwin.so (*) <dcc445c8-85f9-3c6f-a59c-4497162058ce> /Users/USER/*/_umath_linalg.cpython-313-darwin.so
       0x10afc4000 -        0x10afd6fff _ctypes.cpython-313-darwin.so (*) <79240ca2-cd41-316b-84b6-a123952aea42> /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload/_ctypes.cpython-313-darwin.so
       0x10ae65000 -        0x10ae79fff _pickle.cpython-313-darwin.so (*) <1496c3bb-1414-3179-9d27-90b14adf49de> /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload/_pickle.cpython-313-darwin.so
       0x10aad1000 -        0x10aad6fff _struct.cpython-313-darwin.so (*) <2410714c-7f19-3e0b-8a49-c07fb4a9c14d> /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload/_struct.cpython-313-darwin.so
       0x10aa32000 -        0x10aa32fff _contextvars.cpython-313-darwin.so (*) <5db42a44-316d-38e6-bffb-8e581a78a873> /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload/_contextvars.cpython-313-darwin.so
       0x10aa80000 -        0x10aa8afff math.cpython-313-darwin.so (*) <8c61d294-3b26-384a-81bb-6225c430d0ef> /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload/math.cpython-313-darwin.so
       0x10aa46000 -        0x10aa54fff _datetime.cpython-313-darwin.so (*) <5d125419-982e-324a-943f-074978c8fdcf> /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload/_datetime.cpython-313-darwin.so
       0x10c1e7000 -        0x10c79efff _multiarray_umath.cpython-313-darwin.so (*) <e594e1d4-839b-3adf-b603-9d9cfbb305a1> /Users/USER/*/_multiarray_umath.cpython-313-darwin.so
       0x10b11f000 -        0x10b4befff org.python.python (3.13.0, (c) 2001-2024 Python Software Foundation.) <f1af652e-465e-3c90-99b4-9308a3aef0e5> /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/Python
    0x7ff7ffe1d000 -     0x7ff7ffe4cfff runtime (*) <785a360c-c838-3095-94d4-2cc4faf5d5de> /usr/libexec/rosetta/runtime
       0x10a27d000 -        0x10a2d0fff libRosettaRuntime (*) <3e6996b2-eddb-3269-b841-bb2b3c546f07> /Library/Apple/*/libRosettaRuntime
       0x102264000 -        0x102265fff org.python.python (3.13.0) <bb2ba445-920c-3799-9bbf-4841bd266f0a> /usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=320.6M resident=0K(0%) swapped_out_or_unallocated=320.6M(100%)
Writable regions: Total=1.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.1G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                           923.2M       18 
MALLOC guard page                   96K        6 
Rosetta Arena                     4096K        2 
Rosetta Generic                    968K      239 
Rosetta IndirectBranch             224K        3 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             16.0M        1 
Stack Guard                         16K        1 
VM_ALLOCATE                       7512K       19 
VM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)
__DATA                            4499K      159 
__DATA_CONST                      6622K      113 
__DATA_DIRTY                       348K       60 
__LINKEDIT                       177.4M       18 
__OBJC_RO                         71.8M        1 
__OBJC_RW                         2198K        2 
__TEXT                           143.2M      169 
mapped file                       14.4M       34 
shared memory                       32K        2 
===========                     =======  ======= 
TOTAL                              1.5G      854 
TOTAL, minus reserved VM space     1.5G      854 



-----------
Full Report
-----------

{"app_name":"Python","timestamp":"2024-12-12 10:06:42.00 +0700","app_version":"3.13.0","slice_uuid":"bb2ba445-920c-3799-9bbf-4841bd266f0a","build_version":"3.13.0","platform":1,"bundleID":"org.python.python","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.6.1 (23G93)","roots_installed":0,"name":"Python","incident_id":"E39E3FB3-E173-45B6-B240-B310B190B32F"}
{
  "uptime" : 280000,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 503,
  "deployVersion" : 210,
  "modelCode" : "Mac15,9",
  "coalitionID" : 1485,
  "osVersion" : {
    "train" : "macOS 14.6.1",
    "build" : "23G93",
    "releaseType" : "User"
  },
  "captureTime" : "2024-12-12 10:06:41.9720 +0700",
  "codeSigningMonitor" : 1,
  "incident" : "E39E3FB3-E173-45B6-B240-B310B190B32F",
  "pid" : 69601,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-12-12 10:06:40.7481 +0700",
  "procStartAbsTime" : 6922039843878,
  "procExitAbsTime" : 6922069209904,
  "procName" : "Python",
  "procPath" : "\/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/Resources\/Python.app\/Contents\/MacOS\/Python",
  "bundleInfo" : {"CFBundleShortVersionString":"3.13.0","CFBundleVersion":"3.13.0","CFBundleIdentifier":"org.python.python"},
  "storeInfo" : {"deviceIdentifierForVendor":"787583A1-DAB6-52EB-BF2B-DBD30F05219A","thirdParty":true},
  "parentProc" : "zsh",
  "parentPid" : 69583,
  "coalitionName" : "net.kovidgoyal.kitty",
  "crashReporterKey" : "66111A0E-A8EE-8FA5-8BA0-50DD5D0F521A",
  "responsiblePid" : 1231,
  "responsibleProc" : "kitty",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 4294967295,
  "wakeTime" : 1892,
  "sleepWakeUUID" : "19CEACD9-F374-45F1-8E7A-C409CDF51582",
  "sip" : "enabled",
  "vmRegionInfo" : "0x70 is not in any region.  Bytes before following region: 4331028368\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      102264000-102266000    [    8K] r-x\/r-x SM=COW  \/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/Resources\/Python.app\/Contents\/MacOS\/Python",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000070","rawCodes":[1,112],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000070"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":69601},
  "vmregioninfo" : "0x70 is not in any region.  Bytes before following region: 4331028368\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      102264000-102266000    [    8K] r-x\/r-x SM=COW  \/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/Resources\/Python.app\/Contents\/MacOS\/Python",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":2950989,"threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":12976796208},"r12":{"value":0},"rosetta":{"tmp2":{"value":4489187012},"tmp1":{"value":4482561130},"tmp0":{"value":4482561130}},"rbx":{"value":105553140416736},"r8":{"value":97},"r15":{"value":4500078960,"symbolLocation":0,"symbol":"npy_atimsort"},"r10":{"value":0},"rdx":{"value":3},"rdi":{"value":4485321056,"symbolLocation":0,"symbol":"_Py_tss_tstate"},"r9":{"value":0},"r13":{"value":4480568080},"rflags":{"value":514},"rax":{"value":0},"rsp":{"value":12976796208},"r11":{"value":2},"rcx":{"value":3},"r14":{"value":105553140416688},"rsi":{"value":3}},"queue":"com.apple.main-thread","frames":[{"imageOffset":1868909,"symbol":"PyErr_Occurred","symbolLocation":16,"imageIndex":9},{"imageOffset":1370886,"symbol":"PyArray_LexSort","symbolLocation":2454,"imageIndex":8},{"imageOffset":1489514,"symbol":"array_lexsort","symbolLocation":138,"imageIndex":8},{"imageOffset":782727,"symbol":"cfunction_vectorcall_FASTCALL_KEYWORDS","symbolLocation":94,"imageIndex":9},{"imageOffset":404845,"symbol":"PyObject_Vectorcall","symbolLocation":75,"imageIndex":9},{"imageOffset":1092728,"symbol":"dispatcher_vectorcall","symbolLocation":376,"imageIndex":8},{"imageOffset":404845,"symbol":"PyObject_Vectorcall","symbolLocation":75,"imageIndex":9},{"imageOffset":1664017,"symbol":"_PyEval_EvalFrameDefault","symbolLocation":10898,"imageIndex":9},{"imageOffset":1652694,"symbol":"PyEval_EvalCode","symbolLocation":207,"imageIndex":9},{"imageOffset":2135221,"symbol":"run_eval_code_obj","symbolLocation":97,"imageIndex":9},{"imageOffset":2133542,"symbol":"run_mod","symbolLocation":157,"imageIndex":9},{"imageOffset":2127678,"symbol":"pyrun_file","symbolLocation":141,"imageIndex":9},{"imageOffset":2124632,"symbol":"_PyRun_SimpleFileObject","symbolLocation":272,"imageIndex":9},{"imageOffset":2123800,"symbol":"_PyRun_AnyFileObject","symbolLocation":66,"imageIndex":9},{"imageOffset":2291407,"symbol":"pymain_run_file_obj","symbolLocation":187,"imageIndex":9},{"imageOffset":2290617,"symbol":"pymain_run_file","symbolLocation":94,"imageIndex":9},{"imageOffset":2286867,"symbol":"Py_RunMain","symbolLocation":1263,"imageIndex":9},{"imageOffset":2288603,"symbol":"pymain_main","symbolLocation":371,"imageIndex":9},{"imageOffset":2288782,"symbol":"Py_BytesMain","symbolLocation":42,"imageIndex":9},{"imageOffset":25413,"symbol":"start","symbolLocation":1909,"imageIndex":0}]},{"id":2950990,"name":"com.apple.rosetta.exceptionserver","threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":34097745362944},"r12":{"value":140705915693264},"rosetta":{"tmp2":{"value":0},"tmp1":{"value":4496830765379},"tmp0":{"value":10337986281472}},"rbx":{"value":4496830765379},"r8":{"value":7939},"r15":{"value":4831842304},"r10":{"value":15586436317184},"rdx":{"value":0},"rdi":{"value":0},"r9":{"value":0},"r13":{"value":4465765232},"rflags":{"value":582},"rax":{"value":268451845},"rsp":{"value":10337986281472},"r11":{"value":112},"rcx":{"value":17314086914},"r14":{"value":4489187016},"rsi":{"value":2616}},"frames":[{"imageOffset":17428,"imageIndex":10}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8628031488,
    "size" : 593920,
    "uuid" : "18f658dd-20f3-324d-b7ac-8a9c60b574b3",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4491931648,
    "size" : 163840,
    "uuid" : "dcc445c8-85f9-3c6f-a59c-4497162058ce",
    "path" : "\/Users\/USER\/*\/_umath_linalg.cpython-313-darwin.so",
    "name" : "_umath_linalg.cpython-313-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4479270912,
    "size" : 77824,
    "uuid" : "79240ca2-cd41-316b-84b6-a123952aea42",
    "path" : "\/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/lib\/python3.13\/lib-dynload\/_ctypes.cpython-313-darwin.so",
    "name" : "_ctypes.cpython-313-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4477833216,
    "size" : 86016,
    "uuid" : "1496c3bb-1414-3179-9d27-90b14adf49de",
    "path" : "\/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/lib\/python3.13\/lib-dynload\/_pickle.cpython-313-darwin.so",
    "name" : "_pickle.cpython-313-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4474081280,
    "size" : 24576,
    "uuid" : "2410714c-7f19-3e0b-8a49-c07fb4a9c14d",
    "path" : "\/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/lib\/python3.13\/lib-dynload\/_struct.cpython-313-darwin.so",
    "name" : "_struct.cpython-313-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4473430016,
    "size" : 4096,
    "uuid" : "5db42a44-316d-38e6-bffb-8e581a78a873",
    "path" : "\/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/lib\/python3.13\/lib-dynload\/_contextvars.cpython-313-darwin.so",
    "name" : "_contextvars.cpython-313-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4473749504,
    "size" : 45056,
    "uuid" : "8c61d294-3b26-384a-81bb-6225c430d0ef",
    "path" : "\/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/lib\/python3.13\/lib-dynload\/math.cpython-313-darwin.so",
    "name" : "math.cpython-313-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4473511936,
    "size" : 61440,
    "uuid" : "5d125419-982e-324a-943f-074978c8fdcf",
    "path" : "\/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/lib\/python3.13\/lib-dynload\/_datetime.cpython-313-darwin.so",
    "name" : "_datetime.cpython-313-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4498288640,
    "size" : 5996544,
    "uuid" : "e594e1d4-839b-3adf-b603-9d9cfbb305a1",
    "path" : "\/Users\/USER\/*\/_multiarray_umath.cpython-313-darwin.so",
    "name" : "_multiarray_umath.cpython-313-darwin.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4480692224,
    "CFBundleShortVersionString" : "3.13.0, (c) 2001-2024 Python Software Foundation.",
    "CFBundleIdentifier" : "org.python.python",
    "size" : 3801088,
    "uuid" : "f1af652e-465e-3c90-99b4-9308a3aef0e5",
    "path" : "\/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/Python",
    "name" : "Python",
    "CFBundleVersion" : "3.13.0"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703126638592,
    "size" : 196608,
    "uuid" : "785a360c-c838-3095-94d4-2cc4faf5d5de",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4465348608,
    "size" : 344064,
    "uuid" : "3e6996b2-eddb-3269-b841-bb2b3c546f07",
    "path" : "\/Library\/Apple\/*\/libRosettaRuntime",
    "name" : "libRosettaRuntime"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4331028480,
    "CFBundleShortVersionString" : "3.13.0",
    "CFBundleIdentifier" : "org.python.python",
    "size" : 8192,
    "uuid" : "bb2ba445-920c-3799-9bbf-4841bd266f0a",
    "path" : "\/usr\/local\/Cellar\/python@3.13\/3.13.0_1\/Frameworks\/Python.framework\/Versions\/3.13\/Resources\/Python.app\/Contents\/MacOS\/Python",
    "name" : "Python",
    "CFBundleVersion" : "3.13.0"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 140703487148032,
  "size" : 25769803776,
  "uuid" : "4fbce036-4b8b-3f24-954d-e2c0e9f9cc90"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=320.6M resident=0K(0%) swapped_out_or_unallocated=320.6M(100%)\nWritable regions: Total=1.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.1G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nKernel Alloc Once                    8K        1 \nMALLOC                           923.2M       18 \nMALLOC guard page                   96K        6 \nRosetta Arena                     4096K        2 \nRosetta Generic                    968K      239 \nRosetta IndirectBranch             224K        3 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             16.0M        1 \nStack Guard                         16K        1 \nVM_ALLOCATE                       7512K       19 \nVM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)\n__DATA                            4499K      159 \n__DATA_CONST                      6622K      113 \n__DATA_DIRTY                       348K       60 \n__LINKEDIT                       177.4M       18 \n__OBJC_RO                         71.8M        1 \n__OBJC_RW                         2198K        2 \n__TEXT                           143.2M      169 \nmapped file                       14.4M       34 \nshared memory                       32K        2 \n===========                     =======  ======= \nTOTAL                              1.5G      854 \nTOTAL, minus reserved VM space     1.5G      854 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "4a2832827f8dd6135730b6dc39bdb5bf283f0566",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    },
    {
      "rolloutId" : "645eb1d0417dab722a215927",
      "factorPackIds" : {

      },
      "deploymentId" : 240000005
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000007
    }
  ]
},
  "reportNotes" : [
  "PC register does not match crashing frame (0x0 vs 0x10B2E746D)"
]
}

Model: Mac15,9, BootROM 10151.140.19, proc 16:12:4 processors, 48 GB, SMC 
Graphics: Apple M3 Max, Apple M3 Max, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Apr  4 2024 20:57:11 version 23.30.58.0.41.51.138 FWID 01-baea9d27
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

</pre>
</details>

**Comment by ngoldbaum** [comment]
Thanks! I can reproduce this.

**Comment by ngoldbaum** [comment]
see https://github.com/numpy/numpy/pull/27992
