### ISSUE TITLE
DOC: np.gradient, how many varargs when axis is provided

### ISSUE THREAD

**Issue by schmassmann-m** [numpy/numpy#27995]
### Issue with current documentation:

[np.gradient](https://numpy.org/devdocs/reference/generated/numpy.gradient.html) documentation says:
`numpy.gradient(f, *varargs, axis=None, edge_order=1)`
_If axis is given, the number of varargs must equal the number of axes._ 
It does not specify, whether the number of axes of the array, or the number of axes the user specified in axis. Unexpectedly the latter is the case.
```
import numpy as np
res1=np.gradient(np.random.random((5, 6, 7)),.1,.2,axis=(0,1))
res2=np.gradient(np.random.random((5, 6, 7)),.1,.2,.3,axis=(0,1))
```
The last line raises  `TypeError: invalid number of arguments`, in versions 1.18.1 & 1.19.1.

### Idea or request for content:

I propose to amend the documentation, e.g. by amending the italic sentence above by:
_If axis is given, the number of varargs must equal the number of axes **provided in the axis keyword**._
or by changing numpy's code, such that the number of `varargs` can be either the number of dimensions of the array `f`, or the number of axes provided in the axis keyword. 
Should the behavior I describe be a bug instead of unclear documentation, feel free to shift this to the BUG category.

**Comment by Uvi-12** [comment]
@schmassmann-m I believe that if the described behavior where a mismatch between varargs and axis leads to unexpected results is unintentional, it should be classified as a bug, and validation should be added. However, if this behavior is intentional, the documentation should be updated to clearly explain the expected relationship between varargs and axis to avoid any confusion. 

@ngoldbaum Please help to clarify this. I’d like to work on this.
