### ISSUE TITLE
TST,DOC: Bump `scipy_doctest` (or remove pin) and fix new failures

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#28019]
@ev-br ping FYI,  since the new scipy-doctest release (less than an hour ago) the refcheck has universal failures.

I suspect, this is all just bad documentation that needs fixing, but not sure yet.  In either case, until fixed both CircleCI and the "benchmark" tests which also still run the refcheck are expected to fail.

(Currently, also the linter just started failing...)

**Comment by mattip** [comment]
We should pin tools to a specific version, and update in a controlled fasion.

**Comment by mattip** [comment]
I see we do not pin matplotlib, scipy, pytz, pandas. Should we?

**Comment by ev-br** [comment]
Here's  failing job: https://app.circleci.com/pipelines/github/numpy/numpy/30210/workflows/1d8f4112-60a7-42f9-ae82-3ff7ed57b6b5/jobs/44299

Two kinds of issues:
- the fix for https://github.com/numpy/numpy/issues/28002 : dtype methods were never tested and now they are, with predictable results :-). 
- we discovered in https://github.com/scipy/scipy/pull/22027#issuecomment-2536212386 that the doctester was missing inherited methods. I suspect the polynomial failures are of this variety.
 
The issues at `.strides`, `.shape` and `.fields` (duplicated many times over across dtype classes) are certainly bad/non-ideal examples.

**Comment by seberg** [comment]
Should have been closed when merging gh-28023
