### ISSUE TITLE
Unsafe type conversion in numpy.bincount when passing list instead of array

### ISSUE THREAD

**Issue by jni** [numpy/numpy#3138]
`np.bincount` is [supposed](http://docs.scipy.org/doc/numpy/reference/generated/numpy.bincount.html) to raise a `TypeError` if the input array-like contains elements of float or complex type. However, this is not the observed behavior when the input is an array-like (in this case, a list), rather than an array. 

``` python
>>> import numpy as np
>>> x = [1.0, 2.0, 3.5, 3.7]
>>> np.bincount(x)
array([0, 1, 1, 2])
>>> np.bincount(np.array(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'
>>> np.__version__
'1.7.0'
```

**Comment by addisonhuddy** [comment]
Any luck on this fix. Just ran into it.

**Comment by maximilianh** [comment]
Ran into this, too.

**Comment by jaimefrio** [comment]
The blame is on `PyArray_FromAny`'s behavior: it only enforces safe casting if the input is an array, not if it's a sequence. There's even a TODO comment in the code fixing this behavior:

https://github.com/numpy/numpy/blob/maintenance/1.14.x/numpy/core/src/multiarray/ctors.c#L1738

I think we should implement that change, but I'm afraid it would be a deprecation nightmare. Any thoughts?

**Comment by praful-potphode** [comment]
Any luck on this fix. Just ran into this issue.

**Comment by WarrenWeckesser** [comment]
`bincount` will also accept a list of strings containing integers, but it will not accept the same data stored in an array:
```
In [16]: x = ["1", "4", "0", "0"]

In [17]: np.bincount(x)
Out[17]: array([2, 1, 0, 0, 1])

In [18]: np.bincount(np.array(x))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[18], line 1
----> 1 np.bincount(np.array(x))

TypeError: Cannot cast array data from dtype('<U1') to dtype('int64') according to the rule 'safe'
```
It also accepts lists that contain a mix of floats and strings (as long as the strings can be coverted to integers).

I think we should fix this, so that the handling of non-array inputs matches the handling of array inputs.  The question is, do we need to deprecate the handling of lists of strings and floats?  Or can we call this a plain old bug and just fix it?  Locally I have an implementation of the latter working, but I can work on deprecating the behavior if that is preferred.

**Comment by WarrenWeckesser** [comment]
I ended up going with deprecation: https://github.com/numpy/numpy/pull/27076

**Comment by jni** [comment]
Amazing! Thank you @WarrenWeckesser! Made my day! 😂 😊
