### ISSUE TITLE
constructing bytearray or bytes from numpy array of length 1

### ISSUE THREAD

**Issue by j8spencer** [numpy/numpy#3147]
tested with numpy 1.6.2, python 3.2.3.  Win7, 64-bit.

When creates a 'bytes' object from a numpy array of length 1, the result is a 'bytes' string with the length of the value of the single element, not a single byte equal to the single element.  This is inconsistent with creating a 'bytes' string from a list.  Since an array of length 1 is still an array and still iterable, the result should be a byte string matching the contents of the array.  Example:
\>\>\> bytes(np.array([3], np.uint8))
b'\x00\x00\x00'
\>\>\> bytes([3])
b'\x03'

I would expect both to give the second result.

The same behavior is observed with bytearray.

**Comment by gustavofuhr** [comment]
@j8spencer if do .tostring() in your np.array it will work as expected.

**Comment by seberg** [comment]
While the exact reported issue, will actually go away soon, there is nothing much we can do about it I think. The problem is that `bytes` is overloaded, since you can do `bytes(3)` to create `b'\x00\x00\x00'` and fixing this would basically mean you would not allow `list[np.array(3)]` in the future (the `np.array([3])` case will go away).

I would also point to `memoryview(np.array(3))` or `np.array(3).data`, which both give an object that can't possibly be interpreted as an integer.

If anyone disagrees, feel free to reopen/open a new issue.

**Comment by j8spencer** [comment]
Hadn't thought of the overloaded bytes constructor.  But even so, the example is `bytes(np.array([3]))`, not `bytes(np.array(3))'.  The syntax here is saying, "create a list of one element (namely, 3), then convert that entire list to an array, then convert each element in the array to bytes and concatenate them.  What results is something like "create an array with a length equal to the first value in this list, then convert that array to a concatenated byte string."  

I don't know how the `array([3])` case is going away, but I think the syntax of it is pretty clear--give me an array of one element.  `array(3)` is saying something very different, and those two seem confused somewhere.  `bytes()` seems to be getting an array of 3 elements when it should get an array of 1 element.  

If it's going to be fixed, all is well.  But this seems like an issue in the array constructor, not with bytes() overloading.

**Comment by seberg** [comment]
No, just `bytes` and `operator.index(np.array([3]))` behaviour. But we changed the latter (already in master), so only `bytes(np.array(3))` remains to be like `bytes(3)` which I do not think we can change.

**Comment by seberg** [comment]
@j8spencer, ok good riddence. It of course is fixed in the exact opposite direction as you wanted it to be fixed ;). But it does not really change much. Numpy arrays are memoryview/buffers as well as sequences and `bytes` handles both differently. Now if there was a `bytes.from_buffer` or `bytes.from_sequence` you could maybe choose, but there is not....

**Comment by seberg** [comment]
OK, nvm. since your array was uint8, it of course gives the same result, on numpy master:
```
In [2]: bytes(np.array([3], dtype=np.uint8))
Out[2]: b'\x03'

In [3]: bytes(np.array([3], dtype=np.uint16))
Out[3]: b'\x03\x00'
```
bytes recognizes it as a memoryview, failing to interpret it as an integer.
