### ISSUE TITLE
Timezones and Datetime64

### ISSUE THREAD

**Issue by PythonCHB** [numpy/numpy#3290]
A new version of datetime64 dtype was added to numpy recently, and as of 1.7, is considered experimental.

As of 1.7, datetime64 attempts to handle timezones by:

- Assuming all datetime64 objects are in UTC
- Applying timezone offsets when parsing ISO 8601 strings
- Applying the Locale timezone offset when the ISO string does not specify a TZ.
- Applying the Locale timezone offset when printing, etc.

(note that no timezone handling is done when converting to/from the stdlib datetime object)

However, this behavior makes it very difficult to use datetime64 in a timezone agnostic way, or if you need to work with a timezone that is not the system Locale one.

Complete and proper timezone management could be a very useful, but the current system is only useful in a few small cases, and makes common use cases very difficult. Good timezone handling is a large and difficult problem -- it is unclear whether numpy wants to take it on.

There has been much discussion on the numpy mailing list, and a new datetime64 NEP is progress, but in the meantime, I propose we make the following changes to make datetime64 far more useful and less prone to error:

 * Assume that datetime64 is timezone "naive", as the standard library datetime object does -- it is up to the user to do any time zone offset conversions.
 * Do not apply a timezone offset when converting to an ISO string
 * Never use the Locale settings for anything, without the user explicitly asking for it.
 * raise an exception when parsing an ISO 8601 string that has a timezone offset other than 0 (Z)

**Comment by mangecoeur** [comment]
> Never use the Locale settings for anything, without the user explicitly asking for it.

Please can this be introduced! Numpy amuses itself by displaying timezone offsets for values which purposefully don't have time-zones - but it makes it look like they do. I happen to travel between time zones quite often (with the machine updating local accordingly) and it would be nice if my program would output the same thing twice rather than trying to be "helpful" in this way.

Also, strongly disagree with
> Naive vs. UTC -- they are almost exactly the same 

A naive datetime is one for which no timezone information is known or desired. It could be for instance you are running a theoretical model with no relation to a real location, so a timezone is meaningless.
 A UTC datetime is one where a timezone has been defined and is desired, and is chosen to match an international convention on the "baseline" time zone. A naive datetime should never, ever be presented with a "timezone offset" or anything like it because that makes no sense, while for a UTC datetime this does make sense.

Its precisely this kind of vagueness that makes dealing with times such a pain, because you end up with data where its never clear if the value you have is in UTC, naive, includes DST, etc - and part of that is because tools (like numpy) don't really help you out and everyone ends up throwing unix timestamps around till no one has a clue what's going on...

**Comment by PythonCHB** [comment]
On Thu, Mar 12, 2015 at 11:42 AM, mangecoeur <notifications@github.com>
wrote:

> Never use the Locale settings for anything, without the user explicitly
> asking for it.
>
> Please can this be introduced!
>
Well -- it takes someone to get in and fix the code....


> Numpy amuses itself by displaying timezone offsets for values which
> purposefully don't have time-zones - but it makes it look like they do.
>
well, they sort of do -- currently numpy datetimes are ALWAYS UTC, and they
use the Locale to set a time zone. THis is quite broken, as you know, but
it's logical.

I happen to travel between time zones quite often (with the machine
> updating local accordingly) and it would be nice if my program would output
> the same thing twice rather than trying to be "helpful" in this way.
>
> Also, strongly disagree with
>
> Naive vs. UTC -- they are almost exactly the same
>
> Fine -- conceptually they are very different. But implementation-wise,
they are almost exactly the same. As you say:

 > A naive datetime should never, ever be presented with a "timezone
offset" or anything like it because that makes no sense, while for a UTC
datetime this does make sense.

and that, in fact, the the only difference implementation wise-  naive, you
numpy wouldn't add an TZ offset, UTC, it might. That's it. And a user code
could treat a naive DT as UTC and add the offset itself. That was my poiint.

> Its precisely this kind of vagueness
>
It's only vague if numpy doesn't make it clear which is in use- naive or
UTC. My point was that either is just fine.

> that makes dealing with times such a pain, because you end up with data
> where its never clear if the value you have is in UTC, naive, includes DST,
> etc
>
I see it as kind of like text encodings -- you need to know on IO and you
need to be clear in your data files. It would be nice of the tools took car
of al that for you, but that is very, very hard to do. So something useful
is better than nothing.

-CHB


-- 
Christopher Barker, PhD

Python Language Consulting
  - Teaching
  - Scientific Software Development
  - Desktop GUI and Web Development
  - wxPython, numpy, scipy, Cython

**Comment by shoyer** [comment]
Just FYI, I'm working on implementing this in #6453.
