### ISSUE TITLE
Division broken when dtype specified

### ISSUE THREAD

**Issue by justinvf-zz** [numpy/numpy#3484]
In a head build using python 3:

``` python
>>> np.__version__
'1.8.0.dev-069e9b0'
>>> np.divide(.4, 1.0, dtype=np.float)
0.0
>>> np.divide(.4, 1.0)
0.40000000000000002
```

**Comment by jcrist** [comment]
This just bit me in numpy 1.9.1:

```python
# python 2
>>> np.divide(82.5, 10.0, dtype='f8')
8.25

# python 3
>>> np.divide(82.5, 10.0, dtype='f8')
8.1999999999999993
```

**Comment by charris** [comment]
Whoa, that's bad. Gives an error message in 1.10-devel, but still
```
>>> np.divide(82.5, 10.)
8.25
>>> np.divide(82.5, 10., dtype='f8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: found a loop for ufunc 'true_divide' matching the type-tuple, but the inputs and/or outputs could not be cast according to the casting rule
```
It should not be working in integers just because of `'f8'`. This looks like more than a simple bug... The error message is also incomplete.

**Comment by charris** [comment]
The problem is somewhere in `type_tuple_type_resolver`. And specific to `dtype='f8'`.
```
In [3]: true_divide(82.5, 10., dtype='f4')
Out[3]: 8.25

In [4]: true_divide(82.5, 10., dtype='f8')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-567cf519068c> in <module>()
----> 1 true_divide(82.5, 10., dtype='f8')

TypeError: found a loop for ufunc 'true_divide' matching the type-tuple, but the inputs and/or outputs could not be cast according to the casting rule
```

**Comment by charris** [comment]
The reason double is special is that there are `true_divide` loops with integer inputs and double output.

**Comment by Dobatymo** [comment]
there are still problems with division: https://stackoverflow.com/questions/45278112/numpy-integer-division-sometimes-yields-wrong-results-when-casted
`>>> np.true_divide(200, 100, dtype=np.float64)
-0.56000000000000005
>>> np.true_divide(200, 100, dtype=np.float32)
2.0`
python 3, numpy 1.13.1

**Comment by njsmith** [comment]
Confirmed, and there's a more detailed diagnosis in the stackoverflow link.

**Comment by charris** [comment]
Goes through a byte type I think
```
In [6]: int8(200)
Out[6]: -56
```

**Comment by charris** [comment]
There is a check somewhere that is incorrect. For laughs I changed the default output to float32 ...
```
In [2]: np.true_divide(200, 100, dtype=float64)
Out[2]: 2.0

In [3]: np.true_divide(200, 100, dtype=float32)
Out[3]: 1.951564e-20

In [4]: np.true_divide(200, 100, dtype=float16)
Out[4]: 2.0
```
Note that now it is now the float32 type that has problems. Frankly, I'm suprised that it worked at all.

**Comment by charris** [comment]
I think the problem is in the handling of casting due to
```
NPY_DEFAULT_ASSIGN_CASTING = NPY_SAME_KIND_CASTING
```

**Comment by charris** [comment]
Yep, that's it. Changing https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_type_resolution.c#L2175 to
```
                    NPY_SAFE_CASTING, casting,
```
Fixes the problem. Probably the call should be changed so that `input_casting` is passed.

**Comment by charris** [comment]
Of course, that breaks a lot of other things. What we have here is a classic cluster f***. Looks like the `type_tuple***` resolvers need a rewrite.

**Comment by charris** [comment]
Turns out that #5963 was not a correct fix.

**Comment by charris** [comment]
Another curiousity, casting `int64` to `float16` is regarded as valid with "same_kind" casting, which is why
```
In [1]: true_divide(11100000, 100000, dtype=float16)
/home/charris/.local/bin/ipython:1: RuntimeWarning: invalid value encountered in true_divide
  #!/usr/bin/python
Out[1]: nan
```

What is going on is that if the dtype is specified, a valid loop must have an output type that matches exactly. For float16 that is "ee->e", and since same_kind casting of int64 to float16 is valid, away we go. Now if we specify `dtype=float64`, the first match has signature `bb->d`, and since same_kind casting allows casting float64 to int8, voila, the wrong answer. 

Trying to change the behavior is tricky because much current code assumes the current behavior.

**Comment by charris** [comment]
I think the only change that dosen't break the world is to remove all the int loops for true_divide.

**Comment by njsmith** [comment]
ugh, SAME_KIND is so conceptually incoherent.

Removing `true_divide`'s int loops seems like a reasonable approach though.

**Comment by charris** [comment]
See #9469.

**Comment by charris** [comment]
@njsmith i think the real problem is what `dtype=` means. If I had my druthers, it would mean that inputs would be cast to that type and the output would have to match. So in this case the only valid loop signature when `dtype=np.float64` would be `dd->d`. The `casting` keyword would then only apply when `out` was specified, which is where `same_kind` is somewhat useful. We could rewrite things to do that, but the change is big enough that I suspect many things would break. OTOH, the current behavior is not easy to understand and results in a buried mine just waiting for someone to step on it.

**Comment by charris** [comment]
PS, I haven't checked, but I suspect `dtype` does not have a consistent meaning across all ufunc methods.

**Comment by njsmith** [comment]
Yeah, the lack of a coherent theory about what `dtype` means bothers me too. Defining it to mean "this is the output type I want" would make *some* sense, and I think actually work if our type resolution code would try to pick the "best" intermediate type instead of casting int64 to float16, but (a) that's not how our type resolution code works, and (b) I feel like there are cases where dtype is used to indicate intermediate precision or similar.
