### ISSUE TITLE
Incompatible numpy.float64.__round__()

### ISSUE THREAD

**Issue by pepalogik** [numpy/numpy#3511]
`round(x)` (i.e. `object.__round__(self)`) is expected to return an `int`, but for numpy floats, it returns a numpy float.

**Comment by anntzer** [comment]
Kindly bumping the issue, which has become more annoying now that indexing an array with a float raises a visible deprecation (e.g., you have to write `array[int(round(some_float))]`).

**Comment by njsmith** [comment]
I'd be fine with matching python here, but we need to run it by the mailing list.

Not clear what the right kind of deprecation is... Normally FutureWarning since there's no error involved, but that would both be very annoying (basically makes round unusable -- you get this noisy warning even if what you're doing is round(a).astype(int)), and the change is relatively low risk compared to most FutureWarning changes, since the actual values returned are identical before and after the change.

**Comment by seberg** [comment]
We changed float scalar rounding a while ago to align with Python (although not quite sure which NumPy version).
