### ISSUE TITLE
return mutiple field selection as ro view

### ISSUE THREAD

**Issue by charris** [numpy/numpy#3641]
This transition is scheduled for 1.9

**Comment by charris** [comment]
Bumping this again to 1.11.

**Comment by charris** [comment]
@ahaldane Should this be closed? What is the status? I'm tempted to close this and not make the attempt.

**Comment by ahaldane** [comment]
I would like it to be fixed at some point! #6053 already implements a possible fix, where I actually make multiple-field selection return a writeable view.

I don't think #6053 can be done for 1.11, but maybe 1.12. It needs some discussion since it introduces a behavior change. I think based on the confusion that periodically pops up related to field access and assignment which #6053 would resolve, there is a fair case in favor of the change.

#6053 needs a rebase, which I have sitting on my compute at home. I am just finishing up a project at work and hopefully will have more time for numpy soon.

**Comment by charris** [comment]
It's been tagged for 1.12, so we can deal with it over the next 3-4 months.
