### ISSUE TITLE
numpy.cast does not work with struct dtypes

### ISSUE THREAD

**Issue by fjarri** [numpy/numpy#4148]
Tested on `numpy 1.8`.

If I have an array with a struct dtype, and attempt to cast it to the same dtype:

```
import numpy

dtype = numpy.dtype(dict(
    names=['val1', 'pad'],
    formats=[numpy.int8, numpy.int8]))
#dtype = numpy.float32

arr = numpy.ones((5, 6), dtype)
print(numpy.cast[dtype](arr))
```

I get a cryptic error:

(python 3.3.2)

```
~> python tt.py
Traceback (most recent call last):
  File "tt.py", line 9, in <module>
    print(numpy.cast[dtype](arr))
  File "/Users/bogdan/.pyenv/versions/3.3.2/lib/python3.3/site-packages/numpy/core/numerictypes.py", line 866, in <lambda>
    cast[key] = lambda x, k=key : array(x, copy=False).astype(k)
TypeError: expected an object with a buffer interface
```

(python 2.7.5)

```
~> python tt.py
Traceback (most recent call last):
  File "tt.py", line 9, in <module>
    print(numpy.cast[dtype](arr))
  File "/Users/bogdan/.pyenv/versions/2.7.5/lib/python2.7/site-packages/numpy/core/numerictypes.py", line 866, in <lambda>
    cast[key] = lambda x, k=key : array(x, copy=False).astype(k)
TypeError: expected a readable buffer object
```

**Comment by eric-wieser** [comment]
Another bug then - `np.cast` is not documented

**Comment by mattip** [comment]
`cast[k](x)` is a different way to spell `np.array(arr, copy=False).astype(np.obj2sctype(dtype))`. 
`np.obj2sctype(dtype)` returns the canonical name for a dtype, so `np.obj2sctype('i')` is np.int32. But in the case of a structured dtype it returns `np.void`. So the failing call is `np.array(arr, copy=False).astype(np.void)`, which fails.

We export `cast` from `numerictypes.py` but I could not find use of it in tests or in python code around numpy.

The error message has changed since `astype` has changed. On HEAD, python3 I get 
```
ValueError: Can't cast from structure to non-structure, 
   except if the structure only has a single field.
```

Not sure what to do here, my inclination would be to deprecate it.

**Comment by melissawm** [comment]
I don't see any errors on 1.22, and `np.cast` has a docstring, so my guess is that it's been resolved. Please reopen if this is not the case.
