### ISSUE TITLE
Extend __numpy_ufunc__ to most numpy.core.multiarray functions?

### ISSUE THREAD

**Issue by pv** [numpy/numpy#4164]
The `__numpy_ufunc__` mechanism likely is easily extended to all relevant numpy.core.multiarray functions. This would also enable several pure-Python Numpy functions (e.g. hstack, vstack, ...) to work transparently with 3rd party classes --- as long as array/asarray are not called, things should work out transparently.

It might also make sense to add a helper function to multiarraymodule so that the override mechanism can be invoked from Python side. This could be a sensible alternative e.g. in the case of linear algebra functions.

**Comment by shoyer** [comment]
Now that `__numpy_ufunc__` is within sight, shall we try to reboot this one? I'll miss the SciPy developers meeting, but I'll be sticking around through the sprints and would be happy to collaborate on a proposal/prototype.

**Comment by mhvk** [comment]
I think I added this somewhere else, but for reference, I used `__numpy_ufunc__` internally to help overwrite all the `ndarray` methods (some of which are ufuncs, but not all); it turned out much of the boiler-plate code was the same (see https://github.com/astropy/astropy/pull/2583/files#diff-e5e9598ff2150e7d4487df941f76f6d0R1171)

**Comment by shoyer** [comment]
Here's the list of functions to wrap that I made during the SciPy sprints:

Things to wrap:
- Misceleanous duck-array stuff:
    - concatenate & stack
    - insert
    - broadcast_to (broadcast_arrays is implemented in terms of this)
    - select & choose (see also 3-arg where below)
    - reshape
    - take? einsum?
- Aggregation functions (that don’t already call the method). These could be gufuncs if we had an `axis` argument, so perhaps `__numpy_ufunc__` would be appropriate here?
    - nan-skipping: nanmean, nansum…
    - median
    - percentile
    - searchsorted
- Other things that should be (g)ufuncs but aren’t -- these could also use __numpy_ufunc__?
    - 3-argument where
    - around & isclose -- these take optional arguments
    - matmul (dot?)
    - sort/argsort
    - tensordot

Most of these could use something quite similar to `__numpy_ufunc__`, even if they aren't quite ufuncs. A few of things have signatures that are quite different (e.g., `concatenate` and `stack`), so they would need a different approach -- possibly special `__numpy_concatenate__` and `__numpy_stack__` methods.

**Comment by teoliphant** [comment]
Have we considered adding a simple multiple-dispatch mechanism to numpy in addition to this approach for ufuncs.      The rest of the numpy functions could be multiple-dispatch enabled.   

It would be very simple to implement a multiple-dispatch approach that just raises an error if there is no concrete implementation registered for the type.   

R does this with S4 and Julia does this as well.   Python also uses flavors of multiple-dispatch in various ways in copy_reg and pickle.   The numpy ufunc itself uses multiple-dispatch under the covers. 

I think it makes the most sense for NumPy to implement a simple multiple-dispatch concept which would be very easy to communicate to downstream developers.

**Comment by njsmith** [comment]
Travis-- you should talk to @shoyer about this while you're in the same
room, he and I just spent a few hours talking about related topics :-)

**Comment by shoyer** [comment]
We had more discussions about this at the BIDS meeting this past weekend. Our notes from the meeting are on Hackpad: https://bids.hackpad.com/Duck-arrays-in-NumPy-6MgLmEnkNhT

Based on these discussions, I plan to make a concrete proposal for `__array_concatenate__` (as a NEP) in the near future. Once we have that figured out, it should give us a template for moving forward.

**Comment by mhvk** [comment]
@shoyer - am intrigued. One suggestion: I think more fundamental than concatenation is the underlying combination of two things: (i) the ability to generate an output array of possibly new shape with otherwise identical generalized dtype (type, units, whatever a duck array needs); and (ii) insertion. This because really concatenation is nothing more than:
```
out = generalized_empty_like(arrays[<suitable-pick-for-base>], new_shape)
for array, slice in arrays, <suitable-slices>:
    out[slice] = array
```
where `<suitable-pick>` should be the same one that would be picked for any other case where there is a list of various arrays.

The above seems to suggest one doesn't generally need a `__array_concatenate__` method as much as a `__empty_like__` method that overrides how the output array is created -- something that will be needed anyway to construct arrays for other operations such as arithmetic.   (And of course one has to take care with `__setitem__` -- in the case of `Quantity` this implies ensuring unit conversion on top of possible float/int, etc., conversion.)

p.s.  This thread may be the wrong place to comment; if so, do direct me elsewhere.

**Comment by njsmith** [comment]
I think there are some notes on empty_like in that hackpad as well. But
note that one issue with the setitem approach is that some duck arrays will
probably be immutable. (E.g. dask can implement concatenate trivially, but
doesn't currently support setitem.)

**Comment by mhvk** [comment]
>(E.g. dask can implement concatenate trivially, but doesn't currently support setitem.)

Maybe not `__setitem__` but surely something similar, since otherwise how can one construct a new array from many pieces?

But I guess my main point would still be that concatenate requires creating a new array and insertion, both of which are fundamental to any array operation which results in a new array, so one might as well start there.

**Comment by njsmith** [comment]
> Maybe not __setitem__ but surely something similar, since otherwise how
can one construct a new array from many pieces?

You can create a dask array however you like, but once it's created you
can't modify it further.
.
Another issue with the empty_like approach is that if you concatenate a
mixture of different types then it isn't clear what the output type should
be. (E.g. sparse_array.__array_concatenate__ might want to choose whether
to return a sparse or dense array depending on how many non-zeros the
result had -- concat(1x10 sparse + 1x1000000 dense) -> dense, concat(1x10
dense + 1x1000000 sparse) -> sparse.)
.
Presumably @shoyer will include these kinds of examples in his NEP's
rationale section :-).

**Comment by mhvk** [comment]
Fair enough -- I'll wait for the NEP!

**Comment by shoyer** [comment]
Yes, I think supporting immutable arrays is an important use cases. Immutability is pretty common for objects intended to be used in a distributed context.

It would be nice to be able to support duck arrays more generically when possible by defining NumPy's functions on top of more generic operations. For example, `stack` and its variants can be written in terms of duck array operations on stack. Likewise, it's certainly a good idea to support a generic `__array_empty_like__` which `np.concatenate` could be built out of. This is particularly useful for duck arrays that adhere very closely to the design of numpy's ndarray. However, that doesn't preclude checking for more specific overrides like `__array_concatenate__`.

**Comment by mattip** [comment]
Can we close this? We have now [NEP 18](http://www.numpy.org/neps/nep-0018-array-function-protocol.html) `__array_function__` and [NEP 18](http://www.numpy.org/neps/nep-0022-ndarray-duck-typing-overview.html) duck arrays

**Comment by mhvk** [comment]
Agreed, closing.
