### ISSUE TITLE
trapz returns wrong values when x is out of order

### ISSUE THREAD

**Issue by jprafael** [numpy/numpy#4601]
Internally, trapz uses np.diff() to calculate dx. This makes the assumption that the x values are increasing monotonically. This leads to wrong values when x does not have this property:

```python
x = array([0, 1, 2])
y = array([0, 2, 4])
trapz(y, x) # 4, correct value
trapz(y[::-1], x[::-1]) # -4, incorrect value

idx = random.permutation(arange(3))
x_shuffled = x[idx]
y_shuffled = y[idx]
trapz(y_shuffled, x_shuffled) # 1, incorrect value
```

This limitation of trapz should be fixed by sorting both y,x values before proceeding. I can sugest two possible courses of action: Either properly document trapz, indicating this limitation, and add a new "safe_trapz" that fixes this. Or do the exact opposite, have trapz sort the input values, and add a "fast_trapz" that doesn't.

**Comment by fizyxnrd** [comment]
I second this opinion.  Trapezoid rule implies positive definite intervals, so that negative increments should only be possible when the function being summed has a negative value.  I certainly don't want data that looks like x = [1 2 3 1 1], y = [1 1 2 1 1] to give me the current result of -0.5.  Even if the data is malformed, I can't think of a circumstance where this result is warranted, and I think this result is an error.  It might well make sense to throw an error if the series is not monotonic (decreasing or increasing) but the summation should definitely make use of abs(diff(x)) instead of just diff(x).

**Comment by jaimefrio** [comment]
A simple check like `np.all(x[:-1] <= x[1:])` could be used, either to raise an error, or before triggering a sort. PRs are always welcome, would you like to try your hand at fixing this?

**Comment by fizyxnrd** [comment]
I'll take a stab at it.  The github ecosystem is new to me, so I'll be working through that.  Should a PR come from a fork, or just a single file?

**Comment by rgommers** [comment]
@fizyxnrd you normally send a PR from a branch created just for this issue (not master) on your own fork of numpy. See http://docs.scipy.org/doc/numpy-dev/dev/ for a guide on how to use git/github for numpy development.

**Comment by fizyxnrd** [comment]
It seems a substantial (nearly all) of the scipy community sees the sensitivity to x-array ordering as a feature rather than a defect.  While I believe this position has an equally valid point of view (the disagreement is over who has to keep track of their minus signs explicitly) it seems that changing the behavior will cause far more upset than molification.

**Comment by jaimefrio** [comment]
adding [link](http://thread.gmane.org/gmane.comp.python.scientific.devel/19486/) to the discussion and closing then. Thanks anyway.
