### ISSUE TITLE
f2py doesn't update .mod file

### ISSUE THREAD

**Issue by fermat618** [numpy/numpy#4775]
Hello,

When
`f2py -c foo.f90 -m bar`
and a foo.mod exists. F2py doesn't update the .mod file, and what worse, it used the .mod file implicitly. If I changed something in the  .f90 file, the .mod file will not be consistent with the .f90 file.

The .mod file is an intermediate file, as the same as .o, so if we don't use it explicitly on a command line, it should be regenerated, at least, it should not be used. 

The module variable with `parameter` attribute will not be written in the .o file, but in the .mod file. I have just encounter an odd bug because f2py implicitly used inconsistent .mod file.

**Comment by HaoZeke** [comment]
This feels like a slight conceptual misunderstanding of the Fortran compilation process. A `.mod` file is not the equivalent of `.o`. Indeed, in Fortran, a `.mod` file is the unit of compilation (equivalent to a file in `C/++`. This is why it is expected and correct to not overwrite the `.mod` file indiscriminately based on an `.f*` file.

That said, the linker itself should (and does) throw an error if incompatible modules are used (e.g. GCC 4.x and GCC 11.x or GCC and Intel)

**Comment by HaoZeke** [comment]
Closing for now.

**Comment by bilderbuchi** [comment]
> This feels like a slight conceptual misunderstanding of the Fortran compilation process. A .mod file is not the equivalent of .o. Indeed, in Fortran, a .mod file is the unit of compilation (equivalent to a file in C/++. This is why it is expected and correct to not overwrite the .mod file indiscriminately based on an .f* file.

Are you sure about this interpretation? In the "Modern Fortran" book by @milancurcic, I read

> In addition to the compiled object file (.o), building a module also outputs a compiled module file (.mod). the compiler users these files for optimization. They're not portable across compilers, and sometimes even across compiler versions.

To me, it sounds strange that this file should not be updated on compilation when the Fortran source file is changed. 
And indeed, a quick test in a CMake/Ninja-built codebase bears this out - if I e.g. add a function to the source file of a module, the .mod file gets regenerated. 
Notably, this does not happen for smaller changes (like adding a multiplier to a line computing some value) -- maybe this only happens when the module _interface_ changes. Is this what you allude to with the word "indiscriminately"?

*(FWIW, as a not-too-experienced Fortran user, I understood a Fortran _module_, i.e. the block from `module bla` to `end module bla`, to be the unit of compilation, but not the .mod file.)*

**Comment by HaoZeke** [comment]
So the distinction is between what the language standard defines and what the build system implements.

If there is an existing `.mod` file then that is used by the compiler instead of the `.f90` file *unless* the build system (not the compiler) explicitly regenerates the `.mod` file. This is why in practice, CMake and other build systems generate the `.mod` file but it is important to remember that the `.mod` file is generated with a separate compiler command.

Some [details of the file](https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/program-structure/using-module-mod-files.html).

In particular, recall that the purpose of the `.mod` file is to keep logical sections of Fortran code in separate directories, and that `mod` definitions can be spread out across files. This is why the following Makefile (from here) works:
```makefile
m1.mod: test1.o
test1.o: test1.f90
ifort -c test1.f90
test2.o: m1.mod test2.f90
ifort -c test2.f90
test3.o: m1.mod test3.f90
ifort -c test3.f90
```
Note that the module files are used for generating the `.o` files.

Essentially the point is that the *compiler* generates the `.mod` files from Fortran source file(s). `f2py` neither has nor should ever modify compile time outputs. Also the real problem here is that the `-c` flag calls `np.distutils` and that does not regenerate the `.mod` file on changes, but instead transparently compiles the the source with any existing modules in its path. If the `.mod` files must be regenerated the cleanest approach is to simply clear them out.

Conceptually the approach to this is:
Fortran file(s) --> some modules --> output objects

Note further that from the [Fortran Wiki example on linking and compiling modules](https://fortranwiki.org/fortran/show/Compiling+and+linking+modules):

```bash
# Compiling, generates a .mod file
gfortran -ffree-fortran -c testModule.f mainProg.f
# Linking, uses existing .mod files without regeneration
gfortran testModule.o mainProg.o
```

**Comment by HaoZeke** [comment]
Build systems, as you mentioned have their own logic for figuring out when to regenerate `.mod` files, as you noticed it is typically on the basis of when the interface changes.

Unfortunately making `np.distutils` include such logic feels a bit out of scope. `np.distutils` proxies over to a compiler command, not to a build system (though support for different build systems is planned) at which point this will be fixed.

**Comment by bilderbuchi** [comment]
Thank you for the illuminating and extensive reply, I'm gonna bookmark that :D 

I think in my mental model until now, the compiler created the .mod and .o files during _compilation_ (so I mentally filed them both under "object files"), and uses both during _linking_.
I had thought that that aligned with what you point out in the Fortran wiki -- compiling *generates* a .mod file, linking *uses* -- in this  sense I don't see the difference between a .mod and a .o file. What I did not realise is that even the compiler does _not_ always regenerate a .mod if already present (gfortran seems to detect an interface change and regenerate then).

Luckily, I'll be using f2py as part of a build system, so if any regeneration needs to be done, I'll let cmake figure it out. :D
I just need to be careful during manual experiments.
