### ISSUE TITLE
append bug : masked array

### ISSUE THREAD

**Issue by bblay** [numpy/numpy#478]
The source ```data``` should not be modified by ```numpy.append```:
```
import numpy, numpy.ma

data = numpy.arange(20).reshape(4,5)
data[:2, :2] = -1
data = numpy.ma.masked_less(data, 0)

print "Before", data.shape, data.mask.shape 
new_array = numpy.append(data, data[:, :1], axis=1)
print "After", data.shape, data.mask.shape 
```
Output:
```
Before (4, 5) (4, 5)
After (4, 5) (5, 4)
```
(using v1.6.1)

**Comment by jjhelmus** [comment]
The original issue from @bblay has been fixed for quite some time as indicated by @pelson and is still fixed in the current master.  The inappropriate mask issue was dicussed on the numpy mailing list in [September 2010](https://mail.scipy.org/pipermail/numpy-discussion/2010-September/053001.html).  Trac ticket (1623) became GH #2219 and was closed with the addition of **ma.append** in #4339.  I believe with this change this issue can be closed.

**Comment by jjhelmus** [comment]
As an example of the new behavior

``` Python
import numpy as np

print np.version.version

data = np.arange(6).reshape(3,2)
data = np.ma.masked_greater(data, 0)
new_arr = np.ma.append(data, data[:, -1:], axis=1)

print "data.shape", data.shape
print "data.mask", data.mask
print "data.mask.shape", data.mask.shape
print "new_arr.mash", new_arr.mask
print "new_arr.mask.shape", new_arr.mask.shape
```

```
1.11.0.dev0+941a4e0
data.shape (3, 2)
data.mask [[False  True]
 [ True  True]
 [ True  True]]
data.mask.shape (3, 2)
new_arr.mash [[False  True  True]
 [ True  True  True]
 [ True  True  True]]
new_arr.mask.shape (3, 3)
```

**Comment by charris** [comment]
OK, thanks for the heads up. Closing.
