### ISSUE TITLE
Enhancement request: add ndmin option to genfromtxt

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#4811]
A couple years ago, `loadtxt` was given the argument `ndmin`.   `genfromtxt` should also have this option.

See, for example, http://stackoverflow.com/questions/24247103/numpy-genfromtxt-collapse-recarray-when-data-file-has-only-one-row/

**Comment by WarrenWeckesser** [comment]
Another example: http://stackoverflow.com/questions/39629337/numpy-genfromtxt-flattens-my-data

**Comment by emirkmo** [comment]
This is actually a huge issue when using genfromtxt for importing data in to python for scientific uses. I have to sanitize every input with an extra call to np.atleast_1d(). This is easily missed by novice users, and was causing big problems in their codes dealing with large, automatically generated datasets (for my students and colleagues.)

After learning about it, I've been able to retro-actively debug 2 simple data-reduction pipelines, which would "randomly" fail. If it was included as an option in genfromtxt, I think incidence of such mistakes would decline substantially.

**Comment by seberg** [comment]
I now think the better option may be to add `squeeze=False` instead of this.  `ndmin` has somewhat weird behaviour for structured dtypes (which span the "column", so their existence removes a dimension when parsing).  Suddenly `ndmin=2` returns _more_ dimensions then what should ever happen (effectively 3).

Using the `squeeze=False` kwarg (pandas has this) you could still advise users to follow with `arr.squeeze(0)` for the (rare `ndmin=1`) use-case.
