### ISSUE TITLE
BUG np.where half-initializes subclass of output

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#5095]
In numpy 1.9, the behaviour of `np.where(condition, first, second)` changed, in that the output no longer always is an `ndarray` instance but an instance of the subclass of `first`. However, `__array_finalize__(self, obj)` is called with `obj=None`, and hence the subclass can not properly initialize itself (according to the documentation [1], `None` is reserved for the case where a new instance is created via `__new__`). This change in behaviour has caused some problems (e.g., https://github.com/astropy/astropy/pull/2958, also discussion in https://github.com/astropy/astropy/issues/1274). 

I should add that I do not necessarily believe the old behaviour was preferable, but it would be good if the current behaviour is documented.

Going forward, an option which I think would be ideal (though not necessarily practical...), is if `np.where` would do the equivalent of

```
out = first.copy()
out[condition] = second[condition]
```

In this way, subclasses can check if the second argument is consistent with the first (e.g., for our `Quantity` class, check the units and possibly convert). This might be done most easily if, somehow, `np.where` could be turned into a `ufunc` and passed through the `__numpy_ufunc__` mechanism.

[1] http://docs.scipy.org/doc/numpy/user/basics.subclassing.html

**Comment by WeatherGod** [comment]
Sorry for resurrecting an old thread, but I finally tracked down the source of an obscure bug in one of our production systems, and I think it relates to this. The line `(np.where(x > 224, 224, x)/25.4).filled(0)` where `x` was a masked array, used to work fine because np.where() returned a masked array that had a method `filled()`. I know I can use `np.ma.where()`, and I will going forward, but changing the behavior of np.where() did break legitimate code.

**Comment by charris** [comment]
I've put a preliminary `1.10` milestone on this so that it gets looked at.

**Comment by mhvk** [comment]
@charris - be sure to reopen the issue, otherwise it probably won't get looked at at all! (@juliantaylor -- a proper solution would still be very welcome!)

**Comment by njsmith** [comment]
Fwiw would be comfortable with not considering this a 1.10 blocker and
instead letting it sit until someone who has a specific interest in
subclasses shows up with a proposal+fix. Right now it sounds like no one is
sure what a proper fix would even be. And while the behavior in master
might not be optimal, it's not clear that there's even any back compat gain
to be had, given that master matches 1.9 and so everyone who wants to
support 1.9 already has to adapt regardless. Leaving it in 1.10 won't
create any new additional burden.

**Comment by shoyer** [comment]
`np.where` works like a ufunc, though I know it isn't implemented that way internally. So I think the right solution to this is probably to simply use `__numpy_ufunc__` and let subclasses/duck-types override the functionality that way.

@mhvk's proposed solution is interesting, but it won't work for all duck-array types:
```
out = first.copy()
out[condition] = second[condition]
```

The problem is that some of the duck-array types for which `where` is most useful are actually immutable (e.g., `dask.array`). These types need their own solution, which they can implement with `__numpy_ufunc__`.

**Comment by WeatherGod** [comment]
I should also point out that my code example used to work because the *condition* was a masked array. Depending on the type of `first` would have been misleading in my case as my example has just an integer there.

**Comment by WeatherGod** [comment]
...and looking over my company's internal bug tracker, this *may* be the source of another bug that was customer-facing, causing our shipped netCDF files to have very negative values in places that should have been masked, and our contours to look a bit silly. We never figured out the exact cause of the issue, but I am now going to see if an np.where() was used.

**Comment by charris** [comment]
Perhaps we should raise an error until the subclass issue is fixed. @juliantaylor Have you had any time to pursue your solution?

**Comment by WeatherGod** [comment]
I think I would be more comfortable with a warning. The sneaky nature of
this problem indicates that the results are more like a degraded result
rather than "wrong", especially in the face of duck-typing elsewhere. A
warning would have pulled me to this spot in the code faster, and I would
have reported it sooner as such. It is quite possible that other people
have encountered similar problems and merely shrugged and worked around it,
or didn't figure out the source of it.

**Comment by charris** [comment]
So this is still up in the air. Pushing off to 1.12.

**Comment by mhvk** [comment]
Closing since one can now override `np.where` with `__array_function__`. Hopefully, eventually `where` becomes a proper ufunc.
