### ISSUE TITLE
Add ndarray.keys() and ndarray.values() methods

### ISSUE THREAD

**Issue by jzwinck** [numpy/numpy#5134]
It would be useful for duck typing if ndarray had keys() and values() methods.  Here's how I would implement them in Python:

```
def keys(self):
    return self.dtype.names

def values(self):
    return self.flat
```

The way I've shown, keys() would return a tuple and values() would return an iterator (as dict does in Python 3).

This would make it easier to write generic code which handles structured arrays, dicts, and other mapping types transparently, for example:

```
np.array([(1, 3), (4, 5)], dtype=[('a', int), ('b', int)])

{ 'a': [1, 4], 'b': [3, 5] }
```

Without this, I currently have ugly code such as:

```
def hasColumn(data, name):
    columns = data.dtype.names if isinstance(data, np.ndarray) else data.keys()
    return name in columns
```

As far as I know, these methods would actually be implemented in C, specifically by adding to `array_methods` in multiarray/methods.c (and using `flat` from multiarray/getset.c).

**Comment by mhvk** [comment]
Seeing this now that it got high on the "recently updated" list. It seems useful for arrays that happen to contain fields, but like others on the mailing list, I think is only confusing if present for regular arrays. It does seem the implementation is nearly trivial: just return `array.dtype.fields.keys()` (this will even give you an `AttributeError` for a regular array).

I guess the main question is whether the additional complexity is worth it (is there any memory overhead for each instance if the number of slots used increases?). This especially since duck-typing a dictionary will not get you all that far (e.g., `len(array) != len(array.keys())`). I guess the overall question is to what extent one would try to emulate the [mapping protocol](https://docs.python.org/3/c-api/mapping.html). Arguably, this makes most sense for `recarray` (but I can see your point above that then you're still stuck with doing an `isinstance` and taking a `recarray` view).

**Comment by jzwinck** [comment]
@mhvk: I don't intend to emulate the entire mapping protocol--that's not feasible since some things like "len" and "in" already do something else for arrays.  Using `array.dtype.fields.keys()` as you suggest instead of `array.dtype.names` to get an `AttributeError` (instead of `None`) for regular arrays seems like a good idea.

I have never heard of memory overhead being the rationale for rejecting new methods.

**Comment by eric-wieser** [comment]
Related: #7552

**Comment by njsmith** [comment]
The memory overhead is ~nil, the cost is per class rather than per instance.

I'm a little concerned about adding more coupling between ndarray and specific dtypes, but in some ways that ship has sailed, so the marginal cost may not be that high. (I.e., this might require jumping through some ugly hoops as we better decouple ndarray and dtypes, but we may have to jump through those hoops anyway to support stuff like `.real`.)

The proposed semantics don't at all match how dict works in either python 2 or python 3, though... and `.flat` is probably a bad idea in any context.

**Comment by eric-wieser** [comment]
I think if we were to implement `values`, it would want to return a `ndarray_values_view`, which for `value = arr.values()` does nothing other than map `values[i]` to `values[arr.dtype.names[i]]`. We wouldn't need to support any ND indexing here either.

**Comment by mhvk** [comment]
If we do it, we might as well match the python3 dict protocol, so `keys` and `values` would be iterables, but they do not have to be indexable. Similarly, `items` needs to return an iterable of tuples.

But one could also start more simply: only implement `keys()` (which just returns `dtype.fields.keys()`, raising `AttributeError` for non-structured arrays). Then, as noted in #7552, at least one can turn the array into a dict (of views) and work from there.

**Comment by jzwinck** [comment]
What's proposed in #7552 is good enough to satisfy this.
