### ISSUE TITLE
ENH: Weight support for np.var

### ISSUE THREAD

**Issue by MechCoder** [numpy/numpy#5164]
Is there any reason why there is no `weights` keyword for `np.var` similar to `np.average`? We sometimes need to custom code for this in sklearn sometimes, for example, [Here](https://github.com/scikit-learn/scikit-learn/pull/3474/files#diff-383546d17769864242e4668d2338b449R136)

If this is agreed upon, I can submit a Pull Request.

**Comment by tpoole** [comment]
A weighted variance is calculated in exactly the same way as a single-variable weighted covariance.

**Comment by charris** [comment]
Weights are available for cov since #4960 has been merged. @MechCoder Check it out. It isn't quite as convenient as the `ndarray.var` method, but should suffice. In fact, the var method is implemented in `numpy/core/_methods.py`, so it probably would not be difficult to use bits of the code in #4960 to implement weights. Make a PR if you wish.

**Comment by MechCoder** [comment]
Sorry for the non-replying. I shall have a look right now.

**Comment by melissawm** [comment]
I believe the discussion here is similar to #8581, so this can be closed in favor of that issue. Please reopen if this is not the case.
