### ISSUE TITLE
Possible overflow for long integer in matrix multiplication

### ISSUE THREAD

**Issue by creasyw** [numpy/numpy#5435]
I try to play with the Fibonacci number and find this issue. The operation is relatively easy:

```python
np.dot(np.array([[1,1],[1,0]]), np.array([7540113804746346429, 4660046610375530309]))
```
in which the latter matrix contains the 91st and 92nd Fibonacci number. The correct result should be:
```python
array([12200160415121876738,  7540113804746346429])
```
But the program returns:
```python
array([-6246583658587674878,  7540113804746346429])
```

I am not sure if this is the bug of the program, or I should do something different with this kind of extreme long integers.

Thanks in advance!

**Comment by argriffing** [comment]
@creasyw If you want to work with large integers or high precision floating point numbers, numpy is not the best way to go.  That said, you can force numpy to use python integers by explicitly using "object" data types:

```python
>>> np.dot(np.array([[1,1],[1,0]], dtype=object), np.array([7540113804746346429, 4660046610375530309]))
array([12200160415121876738L, 7540113804746346429], dtype=object)
```

**Comment by charris** [comment]
What @argriffing said. Numpy is for numerical work, hence tends to be restricted to the numerical types directly supported by the hardware, and for integers the arithmetic is modular, so rather than overflow, the numbers wrap around. If you need arbitrary precision integers, you need to use something like python's integers, which are slow for computation, but allow precision limited by memory and time.

**Comment by creasyw** [comment]
@argriffing and @charris, thank you so much!
