### ISSUE TITLE
linspace does not properly handle denormal values

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#5437]
This is pretty low priority since AFAIK no user has actually run into this, but, since it [was pointed out on python-ideas](http://news.gmane.org/gmane.comp.python.ideas):
```
In [4]: np.linspace(0, 2e-323, 10)
Out[4]: 
array([  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         1.97626258e-323])
```

The problem is that `linspace` does `step = (stop - start) / (samples - 1)`, and here that becomes
```
In [5]: (2e-323 - 0) / 9
Out[5]: 0.0
```

The correct output would be something like `[0, 0, 5e-324, 5e-324, ...]`.

**Comment by abarnert** [comment]
The obvious solution to this is to transform the algorithm to do the multiplication before the division. For example:

    (stop*i + start*(num-i-1)) / (num-1)

And the obvious problem is that, having done that, large values now overflow to infinity, instead of small values underflowing to 0, which to me seems just as bad.

The only way I can immediately think of to avoid both problems is to have both algorithms and switch between them based on the size of the inputs… but maybe someone more numerically sophisticated has a better answer. (There were three other alternatives suggested on python-ideas, but they're all effectively equivalent to this one.)

Meanwhile, the rearranged implementation has another advantage: while they both have about the same amount of total error distributed nicely as 1ulp errors around the range, and each one looks nicer than the other in some cases, in the most common cases where there's a difference, it's generally the alternative version that looks nicer. For example, linspace(0, 10, 11)[3] will give you rounded-up 0.30000000000000004 with the current implementation, but rounded-down 0.3 with the alternative. (Of course NumPy's own display shows both of these as 0.3, but when you extract the values as Python floats you can see the difference.)

**Comment by jaimefrio** [comment]
With tha same "divide before multiplying" idea, I don't think that something like :

```
np.arange(num, dtype=dtype) / (num-1) * (stop - start) + start
```

will overflow to infinity any more than what we have right now. Conceptually it is the same as always creating `linspace(0, 1, num)`, which should never be a problem (I think...) and then rescaling and translating.

The only obvious drawback is that we then do the most expensive operation (division), `num` times instead of just one, so there will be a performance hit. I would say that `linspace` is more in need of correctness than it is of performance though.

**Comment by argriffing** [comment]
> The only obvious drawback is that we then do the most expensive operation (division), num times instead of just one, so there will be a performance hit. I would say that linspace is more in need of correctness than it is of performance though.

Can this not be done with one division, by multiplying by a reciprocal you compute once?  Or am I missing something...

**Comment by jaimefrio** [comment]
@argriffing We tried that out on #5438, and there are subtle precision issues that make it fail other tests.
