### ISSUE TITLE
array2string handles floats differently for structured array and ndarray

### ISSUE THREAD

**Issue by adrn** [numpy/numpy#5463]
This may not be a bug per se, but it is unexpected (to me):

```
>>> arr = np.array([1.10000000000003,2.1], dtype='<f8')
>>> np.array2string(arr, separator=', ')
'[ 1.1,  2.1]'
```

vs.

```
>>> arr = np.array((1.10000000000003,2.1), dtype=[('x','<f8'),('y','<f8')])
>>> np.array2string(arr, separator=', ')
'(1.10000000000003, 2.1)'
```

(this is with Numpy v1.9.1)

**Comment by eteq** [comment]
@adrn - part of the reason is that `arr` in the second case is a scalar (length-0), even though its a record array.  ``array2string`` ignores all the formatting rules if given a scalar, and instead lets the ``style`` tell it how to format:
```
>>> arr = np.array([1.10000000000003,2.1], dtype='<f8')
>>> np.array2string(arr,style=lambda x:str(x)[:3])
'[ 1.1  2.1]'
>>> arr = np.array((1.10000000000003,2.1), dtype=[('x','<f8'),('y','<f8')]) 
>>> np.array2string(arr,style=lambda x:str(x)[:3])
'(1.'
```

That said, I still see what you're reporting even for a multi-item record array.  I *suspect* what's happening there is there's some undocumented behavior where numpy converts record arrays to strings and then does the formatting on *that* instead of the individual elements.  I'm thinking that because of this:
```
>>> arr2 = np.array([(1.10000000000003,2.1),(4,5)], dtype=[('x','<f8'),('y','<f8')])
>>> np.array2string(arr2,formatter={'numpystr':lambda x:'arg'})
'[arg arg]'
```
Which indicates that ``array2string`` thinks each record array element is a *str*, rather than a float.

A couple possible workarounds: One option would be to just use the formatter argument and do something like 
``` np.array2string(arr2,formatter={'numpystr':lambda x:np.array2string(x['x']) + ','+ np.array2string(x['y'])})
```
Another option is to do ``np.array2string(arr2['x'])`` and ``np.array2string(arr2['y'])`` and then recombine the pieces... not sure which is actually better/easier...

**Comment by eteq** [comment]
Oh, but I should add: I'd very much prefer to see this fixed in numpy itself somehow, if possible, rather than having to use this kind of workaround!
