### ISSUE TITLE
Creation of arrays inside an object array

### ISSUE THREAD

**Issue by oricou** [numpy/numpy#5466]
I want to declare an array of object and later to include arrays in it. I can do it this way:

```
import numpy as np    
v = np.empty([2,2], dtype=object)
for i in range(len(v.flat)):
  v.flat[i] = np.ones([3])
```

But since Numpy has iterators, I wanted to use them:

```
v = np.empty([2,2], dtype=object)
for i in np.nditer(v, flags=['refs_ok'],op_flags=['readwrite']):
  i[...] = np.ones([3])
```

and the message is:

```
ValueError: could not broadcast input array from shape (3) into shape()
```

It seems, according to stackoverflow, it is an example which could be usefull for your discussion on creation of object array.

**Comment by seberg** [comment]
I am honestly not sure if this makes more sense or not (I would say it probably makes sense). But you can use `i[()] = ...` since you want to do *item* assignment not *view* based/sliced assignment anyway.

Oh, and be careful with nditer and objects I forgot what the traps were, but I am pretty sure there are traps with the buffer and reference counts.

**Comment by oricou** [comment]
Thanks for the answer.

**Comment by seberg** [comment]
I will close this, since I think it is correct as is (though I agree it can be confusing, but if the LHS is an array, we assume that we want to assign whatever is inside the array). If someone disagrees, please say so or reopen.

**Comment by oricou** [comment]
Maybe you could add an explanation about [()] in the page http://docs.scipy.org/doc/numpy/reference/arrays.nditer.html and in nditer ref page.
