### ISSUE TITLE
documentation on sliced arrays leaves out critical detail

### ISSUE THREAD

**Issue by dinosg** [numpy/numpy#5477]
I'm a Python beginner, coming from Matlab. So was puzzled that taking an array, say, 

A = arange(35).reshape(7,5)

the trying to get a slice, like 
A[:,0:3]

gives
array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22],
       [25, 26, 27],
       [30, 31, 32]])

that is, 3 array elements from the 2nd dimension instead of 4 (which was specified)... Deep down somewhere else, a web page on Numpy says subscripting an array with a:b  extracts elements from a to b NOT INCLUDING b.  This is non-intuitive and needs to be highlighted.  (or else, made compatible with something rational like Matlab).  The fewer differences people need to keep track of so they can do multiple languages, the better

**Comment by Nodd** [comment]
I went the same path a few years ago. It feels strange at first but it has its advantages too. Anyway, this behavior is present in all python, this is not something from numpy.
Notice that arange(35) builds an array of 35 numbers from 0 to 34, 35 is not included.

More infos: 
- http://python-history.blogspot.fr/2013/10/why-python-uses-0-based-indexing.html
- http://stackoverflow.com/questions/11364533/why-are-slice-and-range-upper-bound-exclusive

**Comment by njsmith** [comment]
This isn't specifically a numpy thing, but rather a thing baked deeply into
python -- list slices, range(), etc. all work this way.

I'm not sure what docs you were looking at. Certainly across all the
manuals and tutorials and books about python and numpy I'm sure that many
of them do mention this :-). And as experts we often rely on feedback from
newcomers to find out where docs are confusing. Can you point to the docs
you were reading, perhaps with specific suggestions on what changes would
have made them work better for you? Or if they were party of the numpy
manual you could even just make the changes and submit a pull request --
github makes this fairly easy, you don't even need to leave your web
browser.

By the way, you can write :3 instead of 0:3 to save some clutter. And :3 it
gives you the first three elements, which may make the behaviour easier to
remember. The half-open interval convention also has other benefits, like
a[:n] and a[n:] divides a python array into two disjoint pieces, where in
MATLAB you have to remember to write a(1:n), a(n+1:end). And in python a
slice from n:m has (m - n) elements, as compared to (m - n + 1) in MATLAB.
In general I find the python convention much easier to work with once one
gets used to it -- basically all the fiddly +1's and fencepost errors
disappear. (If you Google "Dijkstra half-open interval" you can find one of
the most illustrious computer scientists of all time opining on these
issues.)

**Comment by Nodd** [comment]
http://wiki.scipy.org/NumPy_for_Matlab_Users used to be a very good introduction for Matlab users but seems down. Has the url changed ? (This is the first result in google when searching for "matlab numpy")

**Comment by dinosg** [comment]
numpy user guide,
release 1.8.1

march 2014
specifically, the sliced array section in the introductory portion.  the 
fact this is mentioned in python documentation... well maybe but I 
hadn't seen it, I was depending on numpy to help me with arrays so I 
don't have to deal with the lists and tuples of Python exclusively.

**Comment by argriffing** [comment]
I agree with @dinosg that this should probably have extra emphasis in the docs.  My reasoning is that if you are coming to python/numpy with experience in R or Matlab or Julia or Fortran or Mathematica, then you might see some weird things in numpy which you will have to look up, but a lot of things will look familiar.  But when it comes to arrays and indexing, these familiar things will be wrong.

For example say that I've googled numpy indexing and I find http://docs.scipy.org/doc/numpy/user/basics.indexing.html.  Because I'm using numpy 'in anger' to solve some problem I just skim through the code on that page.  The first thing I actually read is
```python
>>> x = np.arange(10)
>>> x[2]
2
>>> x[-2]
8
```
OK as a hypothetical newbie I think I'm following this.  I'm probably thinking that `x` must be something like `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]` so it makes sense that `x[2]`, which must be the second element of the array, is `2`.  I'm on a roll, and now I see that it also makes sense that `x[-2]` is `8` if it counts backwards, maybe requiring `x[-0]` to be `10`.  Wait how could that work... oh well, negative indices are weird anyway.  Let's go to the next bit of code.
```python
>>> x.shape = (2,5) # now x is 2-dimensional
>>> x[1,3]
8
>>> x[1,-1]
9
```
umm, what?

I think this tutorial page is great, but maybe some changes to the first few examples could be helpful for newbies.  Even just showing the values of `x` in the code might be really useful.  Also, I've used numpy a lot but I always use `reshape` when I need to do something like in this second example.  Is it recommended to set the `shape` directly?

**Comment by njsmith** [comment]
@agriffing: That all makes sense to me. Any interest in taking a go at
making the changes?

(I agree that setting .size directly is maybe not the best habit to instill
in new users, though it is supported. FYI note that it isn't quite the same
as .reshape though, because the latter returns a view rather than modifying
the array in-place.)

**Comment by Nodd** [comment]
@dinosg The wiki page "Numpy for matlab user" is now online, it's a very good introduction. You'll find some notes about indexing here.

**Comment by dinosg** [comment]
thanks a ton

**Comment by mattip** [comment]
I am inclined to close this since no PR was forthcoming and in the mean time popularity of python means the slicing notation is not as strange as it was 4 years ago. If you disagree, please open a new issue or PR with clear suggestions of documentation changes that would make it easier for beginners.
