### ISSUE TITLE
numpy.core.multiarray.datetime_data should return tuple in reverse order

### ISSUE THREAD

**Issue by blbradley** [numpy/numpy#5589]
`datetime_data` is a great function to expose for time unit extraction. It currently works like this:

``` python
import numpy as np
from numpy.core.multiarray import datetime_data

td = np.timedelta64(1, 'Y')
datetime_data(td.dtype)
# ('Y', 1)
```

`timedelta64` constructor takes the arguments in the reverse order from which `datetime_data` returns them. I think it would be more intuitive if they were the same.

**Comment by WarrenWeckesser** [comment]
`datetime_data` returns only the time *units*, represented as a tuple, in the correct order.  Note that your example is potentially confusing: the `1` in the tuple returned by `datetime_data` is not the value of the timedelta `td`.

-----

Some background (maybe more than anyone needs :smile:):

In general, the units of `datetime64` and `timedelta` include a string that represents the "base" unit (e.g. 'ns' for nanosecond, 's' for second, 'Y' for year, etc.), *and* an integer count that gives the number of base units per unit of the 64 bit integer that is stored for the date or timedelta.  This means we can count time in, say, units of 10 seconds rather than seconds.  To specify this general form, the unit can be specified as a tuple, `(unit, count)`, where `unit` is the string representation of the base unit and `count` is the number of base units per unit of the date or timedelta integer.  For example, in the following, `d` represents one minute; the units are "tens of seconds", and the data stored in the 64 bit integer is 6:
```
In [78]: d = np.timedelta64(6, ('s', 10))

In [79]: d
Out[79]: numpy.timedelta64(6,'10s')

In [80]: d == np.timedelta64(60, 's')
Out[80]: True
```
Note that the units of `d` are displayed as `'10s'`.  Such a string can also be used as an input to `np.datetime64` or `np.timedelta64`.

(When `datetime64` or `timedelta64` are given a string with no numerical prefix as the base unit instead of the more general tuple, the count is assumed to be 1.)

`datetime_data` returns only the *unit* of the object, in the correct order:
```
In [89]: datetime_data(d)
Out[89]: ('s', 10)
```
It always returns the tuple, even when the count is 1:
```
In [104]: datetime_data(np.datetime64(9876543210, 's'))
Out[104]: ('s', 1)
```
As its docstring says (emphasis added), "the returned tuple can be passed as the *second argument* of `numpy.datetime64` and `numpy.timedelta64`".  E.g.
```
In [105]: u = datetime_data(d)  # Get the units of `d`

In [106]: u
Out[106]: ('s', 10)

In [107]: d2 = np.timedelta64(12, u)  # Create a new timedelta with the same units as `d`.

In [108]: d2
Out[108]: numpy.timedelta64(12,'10s')
```
