### ISSUE TITLE
may_share_memory returning false negative?!

### ISSUE THREAD

**Issue by behzadnouri** [numpy/numpy#5604]
when setting write flag to false and using `__array__`:

    >>> class Foo:
    ...     def __init__(self, arr, write=True):
    ...         self.arr = arr
    ...         self.arr.setflags(write=write)
    ...     def __array__(self):
    ...         return self.arr
    ... 
    >>> a = Foo(np.arange(10))
    >>> np.may_share_memory(a, a)
    True
    >>> a = Foo(np.arange(10), False)
    >>> np.may_share_memory(a.arr, a.arr)
    True

so far so good, but:

    >>> np.may_share_memory(a, a)
    False

is this false negative or am i missing something? (numpy `1.9.1`)

**Comment by jaimefrio** [comment]
What seems to be happening is that `may_share_memory` calls `PyArray_Converter` on its two inputs, which, if the inputs are not themselves of an ndarray subclass, calls `PyArray_FromAny` requesting `NPY_ARRAY_CARRAY` in the flags parameter. So even though `PyArray_FromAny` does call your class' `__array__` method, if the resulting array is not C contiguous, aligned and writeable, a copy will be returned, hence the `False` return. You get the same wrong result if you return `self.arr[::2]` from your class.

This certainly seems to me buggy behavior. The simplest solution would be to remove the requested `NPY_ARRAY_CARRAY` flag from the call in `PyArray_Converter`, since it only applies it to non-ndarray subtypes. But I am afraid that may break lots of third party code. Any thoughts anyone?

**Comment by pv** [comment]
Would probably be safer to not use PyArray_Converter in the
may-share-memory function. This sort of logic on what to do with
non-ndarray inputs is probably best spelled out in the function.

**Comment by njsmith** [comment]
I can't think of any code that would be broken by fixing this -- did you
have an example in mind?

**Comment by seberg** [comment]
Unless we have a very specific example of code breakage, I would suggest that this is a bug fix and the chance of someone falsely thinking they are safe is much much worse.

**Comment by jaimefrio** [comment]
Removing the `NPY_ARRAY_CARRAY` from `PyArray_Converter` doesn't break any numpy tests, and indeed fixes this issue. That is of course no guarantee that it won't break e.g. scipy of course.

Looking into this I have realized that the issue (if it is indeed an issue and not a feature) is a little more far reaching: numpy doesn't really treat objects exposing any form of the array interface as first class citizens. Reusing the `Foo` class from the original issue:

```
>>> a = Foo(np.ones(10))
>>> np.add(a, a)
array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])
>>> np.add(a, a, out=a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: return arrays must be of ArrayType
>>> np.add.accumulate(a)
array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])
>>> np.add.accumulate(a, out=a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: output must be an array
```

This is a flagrant contradiction with what the docs on subclassing state, see [here](http://docs.scipy.org/doc/numpy/reference/arrays.classes.html#numpy.class.__array__).

It is triggered by `PyArray_OutputConverter` (and similar code in `ufunc_object.c`) calling `PyArray_Check` and only letting through `ndarray` subclasses. I think that the right thing to do would be to, if `PyArray_Check` fails, add a call to `PyArray_HasArrayInterface` both in `PyArray_Converter` and in `PyArray_OutputConverter`, and if that suceeds, then call `PyArray_FromAny` with the flags parameter set to zero.

There may be subtleties to this that I am missing, so perhaps the right thing to do is to ping the list.
