### ISSUE TITLE
gradient() fuction for bi-dimensional array returns first in y direction and then in x

### ISSUE THREAD

**Issue by helderc** [numpy/numpy#5628]
Seems the return of gradient() function, for a two dimensional array, is changed compared to matlab. The biggest problem is it's not documented.

See, in MATLAB:

```matlab
x = [1,2,3; 4,5,6];
[gx, gy] = gradient(x)

gx =
     1     1     1
     1     1     1

gy =
     3     3     3
     3     3     3
```     

     
Now, in NumPy:
 
```python
x = np.array([[1,2,3], [4,5,6]])
[gx, gy] = np.gradient(x)

gx
array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

gy
array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])
```
       
As we can see, the return of gradient() at NumPy is not in x direction and later in y. It is in y direction and then x. In my opinion that is ok this change. However, when you are trying to port a large code from matlab to python, like  me, this behavior can  be a pain. Also, the return is not well explained at
docs, since there is only shown the gradient with a one-dimensional array.

**Comment by shoyer** [comment]
The result of np.gradient are ordered by dimension/axis, which for NumPy is always from left to right. So, for a 2D array:

- axis=0 is rows
- axis=1 is columns

This makes sense from the perspective of consistency with NumPy.

That said, I'm sure a documentation patch to clarify this would be gratefully accepted. The documentation is indeed rather vague.

**Comment by helderc** [comment]
@shoyer What text should I put there? I was thinking about some complement to the text in `return` part:

`N arrays of the same shape as f giving the derivative of f with respect to each dimension.` If f is bidimensional, then N will have two elements where N[0] stands for gradient in columns and N[1] in rows direction.

**Comment by shoyer** [comment]
I would probably preface that by saying "For example" and use "two dimensional" rather than "bidimensional". But otherwise this looks about right to me.

**Comment by shoyer** [comment]
Also note that there is already an example with 2D input. It might be a bette idea to include this text specifically to help describe that example rather than putting it in the description of parameters (where it is arguably redundant).

**Comment by rcatwood** [comment]
Sorry but I still find the documentation that I can find, ambiguous. What does it mean to say 'axis=0 is rows' ? does that mean that the value of the coordinate, 0,  changes as you move along a row or changes as you move across a row? likewise  what is the gradient 'in the columns direction? is it dU/dx0  or dU/dx1 ? 

It doesn't make sense to me or agree with what I obtain . Here is a 2-dimensional dataset. 
xyplane
[[  0.   6.  12.  18.  24.  30.]
 [  1.   7.  13.  19.  25.  31.]
 [  2.   8.  14.  20.  26.  32.]
 [  3.   9.  15.  21.  27.  33.]
 [  4.  10.  16.  22.  28.  34.]
 [  5.  11.  17.  23.  29.  35.]]


Clearly the gradient 'in rows' is 6 everywhere. 

So if grad=numpy.gradient(xyplane) and it says that grad[0] is the gradient 'in rows' then it should be 6 everywhere. however it is 1, which is the gradient 'in columns'. 
grad[0]
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]
grad[1]
[[ 6.  6.  6.  6.  6.  6.]
 [ 6.  6.  6.  6.  6.  6.]
 [ 6.  6.  6.  6.  6.  6.]
 [ 6.  6.  6.  6.  6.  6.]
 [ 6.  6.  6.  6.  6.  6.]
 [ 6.  6.  6.  6.  6.  6.]]

Could someone clarify in terms of mathematical symbols e.g. partial derivative of value with respect to coordinate zero , coordinate 1, etc.  ? Dispense with mentioning 'row' and 'column' because the screen output is rather arbitrary?

**Comment by abdurrezzak** [comment]
Has this problem been solved? It is too disturbing that many tutorials (on quivers etc. [example)](https://pythonforundergradengineers.com/quiver-plot-with-matplotlib-and-jupyter-notebooks.html) do not even mention this because they do not care about mathematical correctness. Here is my code which obviously gives an incorrect output.  

`import matplotlib.pyplot as plt
import numpy as np
matplotlib.axes.Axes.quiver
matplotlib.pyplot.quiver
matplotlib.axes.Axes.quiverkey
matplotlib.pyplot.quiverkey

n = 50
x = np.linspace(-2,2,n)
y = np.linspace(-2,2,n)
X, Y = np.meshgrid(x, y)

def V(x, y):
    return (x**2 + y**2)

DPX, DPY = np.gradient(VV)
fig, ax  = plt.subplots()
q = ax.quiver(X, Y, DPX, DPY)
plt.show()`

**Comment by eric-wieser** [comment]
This problem is one only of documentation. The docs were improved, but it sounds like not by enough.

In your example, the problem is actually that `meshgrid` behaves inconsistently with gradient. Perhaps the gradient docstrinng should call that out as a common mistake in the examples section
