### ISSUE TITLE
On Py3, import numpy adds an "mtrand" package to sys.modules

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#5680]
Noticed this while randomly reading through the source code to `mtrand.c` (as generated from `mtrand.pyx`):

```
~$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> "mtrand" in sys.modules
False
>>> import numpy
>>> "mtrand" in sys.modules
True
>>> import mtrand
>>> mtrand
<module 'numpy.random.mtrand' from '/usr/lib/python3/dist-packages/numpy/random/mtrand.cpython-34m-x86_64-linux-gnu.so'>
>>> numpy.random.mtrand
<module 'numpy.random.mtrand' from '/usr/lib/python3/dist-packages/numpy/random/mtrand.cpython-34m-x86_64-linux-gnu.so'>
>>> sys.modules["numpy.random.mtrand"]
<module 'numpy.random.mtrand' from '/usr/lib/python3/dist-packages/numpy/random/mtrand.cpython-34m-x86_64-linux-gnu.so'>
```

The problem is the following code inside the Cython-generated module init function:

```
  #if PY_MAJOR_VERSION >= 3
  {
    PyObject *modules = PyImport_GetModuleDict(); if (unlikely(!modules)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (!PyDict_GetItemString(modules, "mtrand")) {
      if (unlikely(PyDict_SetItemString(modules, "mtrand", __pyx_m) < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    }
  }
  #endif
```

which is just... "if this is python 3, then do `sys.modules["mtrand"] = this module`".

I don't know why Cython does this. If you look at the above REPL trace, it's clear that the `mtrand` module does end up with a properly qualified `__name__`, and does end up in the proper fully-qualified place in `sys.modules` as well, so... maybe this is just a bug in Cython, and the C code I quoted above should just not be generated?

**Comment by njsmith** [comment]
Thread here: https://mail.python.org/pipermail/cython-devel/2015-March/004337.html

Summary so far: It looks like Cython is correct to generate this code (and in fact should be generating even more code that uses the fully-qualified module name); the problem is that Cython thinks it is compiling a module whose fully-qualified name is "mtrand", when actually it is "numpy.random.mtrand". I do not know how one is supposed to pass this information on to Cython and have enquired.

**Comment by scoder** [comment]
The normal way to pass the fully qualified module name is via the module name in the distutils Extension object. If numpy doesn't build with distutils, Cython should still be able to detect the correct module name if the module's .pyx file is inside the final package directory (i.e. all `__init__.py` files are in place) when it's being processed by Cython.

**Comment by njsmith** [comment]
It looks like we're calling the 'cython' command line tool directly, and
the file is *not* in the final place. AFAICT there is no way with the
cython command to override the autodetected module name.

Do we have to rearrange our source tree? It'd be much nicer to just pass a
command line option or add a pragma to the source file.

**Comment by rgommers** [comment]
This doesn't look like a high-prio defect. If Cython doesn't support either a command line option or something we can put inside the ``.pyx`` file now, can we add it to Cython and wait until that new feature is released? Cython releases quite frequently, so that seems like a better option than rearranging the source code layout (and this can't really be a numpy-only issue).

**Comment by scoder** [comment]
The vast majority of Python packages are built via distutils. And within the few that aren't, it's rare that the module sources are placed in different spots than where they eventually belong, as it's actually quite cumbersome to explicitly configure an separate mapping from some (but not all) source files to their final target destination instead of just dropping them there.

That being said, instead of calling the `cython` script, you can just write your own entry point that repeats the tiny intro dance from `Cython.Compiler.Main.main()`, and then pass the `full_module_name` into `compile()`.

https://github.com/cython/cython/blob/b4f3280c583b48e1b8b1b091c6d50e623fdb4cd2/Cython/Compiler/Main.py#L649

You might also want to take a look at `cythonize()` in `Cython.Build` for a nicer interface, although that's geared towards `distutils` usage.

https://github.com/cython/cython/blob/b4f3280c583b48e1b8b1b091c6d50e623fdb4cd2/Cython/Build/Dependencies.py#L708

**Comment by rgommers** [comment]
@scoder off the top of my head, Scipy, Statsmodels and NIPY build their Cython code in similar ways as Numpy does. And if you have a large package, it's not that uncommon to have separate ``src/`` or similarly named sub-directories for C/C++/Cython code. Regarding ``distutils`` usage, yes that's the majority of projects - but Numpy and Scipy support also Bento as a build system, Python itself and many other projects use ``make`` (or ``CMake``, or ...). So I'm not saying something very strange here.

**Comment by rgommers** [comment]
And I don't want to write entry points, I want to be able to call the ``cython`` command as a compiler. That's the only good, build-system-independent design.

**Comment by mattip** [comment]
Closing. This no longer occurs. Please reopen if I misunderstood.
