### ISSUE TITLE
Possible bug with multiple views and basic slicing 

### ISSUE THREAD

**Issue by ebolyen** [numpy/numpy#5716]
We were able to reproduce this in numpy 1.8.1 and 1.9.2. When given a slice from the beginning of the array (relative to the end) to some other point (also relative to the end) with a step size greater than 1, we receive a view which appears to operate as expected. However, when this view is viewed as an `|S<n>` dtype where `<n>` is greater than 1 we receive a `ValueError`:

```python
In [1]:import numpy as np

In [2]: char_array = np.fromstring("ABCDEFG", dtype='|S1')

In [3]: char_array.size
Out[3]: 7

In [4]: char_array.view('|S7')
Out[4]: 
array(['ABCDEFG'], 
      dtype='|S7')

In [5]: sliced = char_array[-7:-3:2]

In [6]: sliced
Out[6]: 
array(['A', 'C'], 
      dtype='|S1')

In [7]: sliced.size
Out[7]: 2

In [8]: sliced.view('|S2')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-8887abf56c24> in <module>()
----> 1 sliced.view('|S2')

ValueError: new type not compatible with array.

In [9]: sliced.dtype
Out[9]: dtype('S1')

In [10]: sliced.copy().view('|S2')
Out[10]: 
array(['AC'], 
      dtype='|S2')
```

Changing the slice step to 1 works as expected. Performing a copy and then creating a view will also work as expected.

**Comment by jaimefrio** [comment]
This is related to #5508. Right now a view can only be taken of a contiguous array. An array with a negative stride is not considered contiguous, even if, as is your case, the memory segment is. hence the error.

This is not really a bug, but a feature. But if we consider it a new feature request rather than a bug report then it is completely pertinent.

**Comment by njsmith** [comment]
No, I think this is different -- notice that the step size here is not
negative, only the offset is. I think the behaviour reported here is
actually correct.

The problem here is that your 'sliced' array is genuinely not contiguous --
when you ask for every second item (::2), then the only way numpy can do
that while also returning a view (i.e., not copying), is by returning an
array that points to discontiguous pieces of memory -- the "A" and the "C"
are not next to each other, there is a "B" still in between them (even if
the view is skipping over that). So when you ask for an "|S2" view, there's
not much we can do -- "|S2" requires that the A and C are next to each
other to work. When you make a copy, then it just pulls out the A and the C
and puts them into a new contiguous memory region, so now the view works.

On Tue, Mar 24, 2015 at 11:59 AM, Jaime <notifications@github.com> wrote:

> This is related to #5508 <https://github.com/numpy/numpy/pull/5508>.
> Right now a view can only be taken of a contiguous array. An array with a
> negative stride is not considered contiguous, even if, as is your case, the
> memory segment is. hence the error.
>
> This is not really a bug, but a feature. But if we consider it a new
> feature request rather than a bug report then it is completely pertinent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5716#issuecomment-85643606>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by ebolyen** [comment]
Thanks for your fast responses, just as a followup, it would appear that step sizes greater than 1 regardless of the start and end indicies will cause this situation. Which I think jives with what @jaimefrio was saying about non-contiguous views, which a step of size 2 or 3 should be. This would be a nice feature to have, but it is completely understandable if the internals of numpy prevent this from being viable or efficient. 

Feel free to close, if that is indeed the case, otherwise I am happy to edit the original post to reflect a feature request.

**Comment by njsmith** [comment]
Yeah, we'd need to add, like, a discontiguous string type "S2-alternating" or something, which stored a 2-byte string in 3 bytes with one byte of padding in the middle. One could do this if one really wanted to, but I don't think it would be a good idea, and certainly won't show up in numpy itself any time soon.

Good luck!

**Comment by ebolyen** [comment]
Thanks @njsmith and @jaimefrio!

**Comment by jaimefrio** [comment]
I really need to start reading things more carefully... But yes, non-contiguous arrays like yours are not going to happen any time soon. Although negative strided ones might eventually do.
