### ISSUE TITLE
Increase maximum number of array dimensions?

### ISSUE THREAD

**Issue by wmayner** [numpy/numpy#5744]
At my lab, we're working with arrays with very many dimensions. We've run up against the hardcoded limit of 32 dimensions for `np.array`s. What is the rationale for this limit, and is it possible to increase it? Thanks!

**Comment by charris** [comment]
This has been discussed before, but is not completely trivial. I'd point you to the mailing list archives, but my browser currently crashes on http://dir.gmane.org/gmane.comp.python.numeric.general.

**Comment by njsmith** [comment]
Mostly the reason we have a finite limit is laziness -- there are a number
of places in the code that just statically allocate a MAX_DIM buffer
instead of writing slightly more complicated code using malloc/free. I
think we'd be happy to accept patches to remove the limit, and this could
be done incrementally, one place at a time. It shouldn't be difficult, just
a bit tedious.

Given the current situation where we do have a single static limit, I think
we hesitate a bit to just bump up that limit, because once we try handling
all the weird 0.1% long-tail use cases then we'll keep having to bump the
limit up arbitrarily far, and that impacts all the users who don't need
massively high dimensions.

**Comment by wmayner** [comment]
Hello again (5 years later)!

We're running into this problem again. It seems that in the meantime it's been noticed by others. 

@njsmith, I could try to implement a dynamic solution as you described, but I don't have a lot of experience with C and I have no experience with NumPy internals. Looks like `NPY_MAXDIMS` appears in the source 234 times; the tedium isn't a problem, but it's possible that this would change behavior meaningfully somewhere. Is this still feasible? If it's still worth trying, it would be a huge help if you or another maintainer could describe the approach you had in mind in more detail.

@jcmgray, @mrocklin, @jrbourbeau, would this be useful for Dask beyond dask/dask#5595?

**Comment by seberg** [comment]
I think the biggest/toughest chunk for relaxing either `MAX_ARGS` or `MAX_NDIM` will be the `NPY_ITER` code.  But as an experiment, it may be better to try with some other functions and see how it goes/what the impact is before diving into that directly (more as a trial balloon).

I do not know if the heap allocations would mean overhead, but I assume that can be made so low, that it just doesn't matter.   Or should we consider again to simply bump up `NPY_MAXDIMS` slightly, because the use-case is different from one that adds many dimensions of size 1?

**Comment by charris** [comment]
I suspect that the original 32 came from `2*32` for 32 bit systems, so 64 might be the proper number for `MAX_DIM` these days, although actual memory address buses were about 48 bits last time I looked.

**Comment by jrbourbeau** [comment]
> would this be useful for Dask beyond dask/dask#5595?

Yes, the maximum number of dimensions impacts dask arrays (at least those backed by numpy arrays) outside of `tensordot`. For example:

<details>
<summary>dask.array.empty example:</summary>

```python
In [1]: import dask.array as da

In [2]: x = da.empty((1,) * 33)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/github/dask/dask/dask/array/utils.py in meta_from_array(x, ndim, dtype)
     90             if ndim > x.ndim:
---> 91                 meta = meta[(Ellipsis,) + tuple(None for _ in range(ndim - meta.ndim))]
     92                 meta = meta[tuple(slice(0, 0, None) for _ in range(meta.ndim))]

IndexError: invalid index to scalar variable.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-2-021c43ce84db> in <module>
----> 1 x = da.empty((1,) * 33)

~/github/dask/dask/dask/array/wrap.py in wrap_func_shape_as_first_arg(func, *args, **kwargs)
     70
     71     dsk = dict(zip(keys, vals))
---> 72     return Array(dsk, name, chunks, dtype=dtype)
     73
     74

~/github/dask/dask/dask/array/core.py in __new__(cls, dask, name, chunks, dtype, meta, shape)
   1053             raise ValueError(CHUNKS_NONE_ERROR_MESSAGE)
   1054
-> 1055         self._meta = meta_from_array(meta, ndim=self.ndim, dtype=dtype)
   1056
   1057         for plugin in config.get("array_plugins", ()):

~/github/dask/dask/dask/array/utils.py in meta_from_array(x, ndim, dtype)
     96                 meta = meta.reshape((0,) * ndim)
     97     except Exception:
---> 98         meta = np.empty((0,) * ndim, dtype=dtype or x.dtype)
     99
    100     if np.isscalar(meta):

ValueError: maximum supported dimension for an ndarray is 32, found 33
```

</details>

That said, it doesn't seems to be a limitation lots of users are running into (https://github.com/dask/dask/issues/5595 is the only reported issue I'm aware of)

Just out of curiosity, @wmayner how many dimensions are you typically dealing with? Would the previous suggestion from @charris help?

**Comment by wmayner** [comment]
@jrbourbeau, we likely wouldn't need more than 64 dimensions for now, so if increasing to 64 is an option, @charris, that would be great.

In case it's helpful to motivate the change, I'll describe our use case:

We're representing the probabilities of state transitions over a single timestep in a discrete dynamical system. If the system has `N` elements with `n_i` states each, then there are `S = n_0 * n_1 * ... * n_(N - 1)` states of the system, and the joint distribution of states at `t = 0` and states at `t = 1` has `S * S` elements.

Our approach is to use separate dimensions to index the state of each element at `t = 0` and `t = 1`, so we need `2 * N` dimensions. This is useful because in our calculations we need to multiply different marginal distributions together; in many cases these distributions are over the states of distinct but overlapping sets of elements, so it isn't a straightforward outer product. But if each element has its own dimension, then we can take advantage of broadcasting semantics and just use the `*` operator to implement the product we need, which is efficient and conceptually simple. (If anyone has any suggestions for a more efficient way to do this, let me know!)

Increasing the limit to 64 would allow us to represent systems of up to 32 elements instead of 16, which would be a qualitatively significant improvement for our research questions.

@njsmith's point about hesitating to increase the limit for long-tail cases is well taken, though. But if the overhead is very low, then increasing to 64 would be a simple stopgap solution until we can make the allocations dynamically.

**Comment by charris** [comment]
@wmayner That sounds like something that could be more flexibly handled by some custom code.

**Comment by seberg** [comment]
I would like to know what @jcmgray reason was for opening the dask issue on the limited number of dimensions numpy/dask support and whether that is related to memory size (something like 2**48), etc.

**Comment by jcmgray** [comment]
Hi, yes I have run up against this limit quite a few times.

As some technical context, basically when simulating quantum systems its natural to represent each system as a dimension (rather than manually 'vectorizing' them into a joint dimension). This is particularly true for tensor networks (basically graphs with an array at each node, with ``ndim`` given by the number of incident edges), where the number of dimensions of each array changes pretty dynamically throughout manipulations.

In a very common case each dimension is of size 2, and I guess this is a key point: ``2^32 * float32`` e.g. is still only ~16GB so even for straight numpy arrays well within what would be tractable in a fairly moderate HPC setting.

In principle ``dask`` might be a great, simple way to handle these sizes of array out-of-core/in a distributed fashion, but because 'chunked' dimensions are still dimensions (even if size 1), the ``ndim`` limit comes into play.

The problem is particularly compounded for ``dask.array.tensordot`` (*the* key function for tensor networks!), for which the current implementation first computes the outer product, then sums over the shared dimensions. Meaning that even if for ```z = tensordot(x, y, axes=....)``` each array ``x``, ``y`` and ``z`` all have ``ndim<32``, the intermediate array can break the limit. 

I should say, this isn't a blocker for me right now, and these borderline HPC cases are understandably I guess not ``numpy``'s focus. But it's certainly possibly to bump up against this particular limit quite easily in the quantum setting.

**Comment by mattip** [comment]
If I understand correctly, the shape of  a ndarray as described would contain only zeros and ones, otherwise memory use would explode. This would be better served by a different data structure, and is not a sufficient reason to fundamentally change ndarray.

Any proposal to make the number of dimensions flexible would need to be carefully benchmarked and should come with a cache of vectors that could be reused rather than repeatedly calling malloc/free.

**Comment by matthew-brett** [comment]
What would be the cost of just bumping MAX_DIMS up to 64?

**Comment by jcmgray** [comment]
> If I understand correctly, the shape of a ndarray as described would contain only zeros and ones, otherwise memory use would explode. This would be better served by a different data structure, and is not a sufficient reason to fundamentally change ndarray.

If this was in reference to my usecase - the arrays are generally filled with complex numbers, and yes, the memory does explode! To be clear, my view is just that a moderate increase in MAX_DIM, to e.g. 64, would be potentially useful.

**Comment by cmatt23** [comment]
I've been running trade studies on how different models interact with each other. Each dimension in my results array is linked to a particular input parameter (whether that is a single value or a range of values). Since I am using multiprocessing pools to run the simulations in parallel, my problem with the 32 dimension limit arises when I return the data from the pool and reshape it to match the inputs (+ a couple dimensions for outputs).

So far my workaround has been to write different versions of the same functions to evaluate the effects of different combinations of inputs independently.I would also appreciate an update to this, even if just to 64 dimensions to start with. Thanks!

**Comment by seberg** [comment]
To be clear, the "64 to start with" is exactly the thing that makes this harder to just decide on for me at least... 64 is the absolute plausible limit at this time, I would personally prefer much less, e.g. 40 or 48 since both should be plenty in a `2**N` scenario.

**Comment by eric-wieser** [comment]
> Each dimension in my results array is linked to a particular input parameter (whether that is a single value or a range of values).

Have you considered using xarray, which lets you name your dimensions, meaning you do not need to insert padding dimensions of length 1?

**Comment by jcmgray** [comment]
As [noted here](https://github.com/dgasmith/opt_einsum/issues/80), this does also currently limit the total number of indices involved in an ``numpy.einsum`` expression, which is a much easier threshold to breach:

```python
import numpy as np
import string

d = 11
# total dims involved = 3 * d
# but max number of array dims = 2 * d

x = np.random.uniform(size=[2] * 2 * d)
y = np.random.uniform(size=[2] * 2 * d)

chars = string.ascii_lowercase + string.ascii_uppercase
eq = f"{chars[0 * d:2 * d]},{chars[1 * d:3 * d]}"
print(eq)
# abcdefghijklmnopqrstuv,lmnopqrstuvwxyzABCDEFG
#            ........... ...........
#                  contracted

z = np.einsum(eq, x, y)
# ValueError: too many subscripts in einsum
```
(n.b. this is just the simplest illustrative equation - I know one could use ``tensordot`` for this specific case).


The following ``if (ndim_iter >= NPY_MAXDIMS) {`` part of ``c_einsum`` is the relevant numpy code:

https://github.com/numpy/numpy/blob/4cba2d91e1546872d29af6b25ad35947f27e03ac/numpy/core/src/multiarray/einsum.c.src#L947-L964

(Possibly for this particular problem there are also other fixes other than increasing  ``NPY_MAXDIMS``.)

I do fairly regularly come across this limitation in real contractions! Currently I need to switch to e.g. [``ctf``](https://github.com/cyclops-community/ctf) in these cases.

**Comment by mofeing** [comment]
As many in this post, I frequently bump into this issue. In the end, I forked and just increased the maximum number of dimensions to 64. I just had to update some tests but I works flawlessly.

> As [noted here](https://github.com/dgasmith/opt_einsum/issues/80), this does also currently limit the total number of indices involved in an `numpy.einsum` expression, which is a much easier threshold to breach:
> 
> ```python
> import numpy as np
> import string
> 
> d = 11
> # total dims involved = 3 * d
> # but max number of array dims = 2 * d
> 
> x = np.random.uniform(size=[2] * 2 * d)
> y = np.random.uniform(size=[2] * 2 * d)
> 
> chars = string.ascii_lowercase + string.ascii_uppercase
> eq = f"{chars[0 * d:2 * d]},{chars[1 * d:3 * d]}"
> print(eq)
> # abcdefghijklmnopqrstuv,lmnopqrstuvwxyzABCDEFG
> #            ........... ...........
> #                  contracted
> 
> z = np.einsum(eq, x, y)
> # ValueError: too many subscripts in einsum
> ```

@jcmgray Your code gives me no problem now and I didn't need to change `einsum.c.src`

I want to do a PR but first wanted to ask if there is still any blocking issue.

**Comment by mattip** [comment]
This might be something to consider for a NumPy 2.0 release

**Comment by NoureldinYosri** [comment]
> I am OK with just saying some of scipy can only do 32 dims
I think this is okay for our use case (cirq simulation).

---

Is there a list of things within numpy that will break with 64 dimensions?

**Comment by seberg** [comment]
The public iterator API/ABI for the "old style" iterator https://github.com/numpy/numpy/blob/main/numpy/core/include/numpy/ndarraytypes.h#L1139 and the macros blow mostly (there is a multiiter, and a few other iterators although those matter less).

**Comment by mattip** [comment]
After sleeping on this, maybe it is OK to error out if using the old style iterator (i.e. `PyArray_IterNew`) with an array that is too big? I think we would also have to refactor some of SciPy to avoid this, it seems to be used quite extensively there. Maybe we could provide a migration guide for people still using the simpler iterator.

**Comment by seberg** [comment]
I don't think SciPy has a lot, maybe even just in `ndimage`, we have quite a lot within NumPy, pandas has a bit (but shouldn't care about high dimensions), etc...

**Comment by mattip** [comment]
I get quite a few hits when doing `git grep PyArray_IterNew` in scipy

**Comment by NoureldinYosri** [comment]
Are the "old style" iterator planned to be supported or dropped in future versions? If it will be dropped then it doesn't make sense to make it support 64 dimensions.

---

I think a first step would be to provide it through special install as I suggest earlier https://github.com/numpy/numpy/issues/5744#issuecomment-1613581105 this will allow the people who need this (e.g. quantum computing community) to use and test  the library and see if anything breaks. Eventually the change can be made permanent in numpy v2 as @mattip suggested in https://github.com/numpy/numpy/issues/5744#issuecomment-1613581105. 

This way we unblock Cirq and similar libraries allowing researchers to simulate quantum systems with more than 32 qubits, while giving time to other libraries to update their code to support the 64 dims if they need to.

What do you think?

**Comment by mattip** [comment]
> I think a first step would be to provide it through special install

As @seberg stated previously, that is only the tip of the iceberg. You now need to rebuild special versions of all the other libraries that use `NPY_MAXARGS`: we already know that SciPy, and Pandas use it (or implicitly use it via `PyArray_IterNew`). Since this is all open source, I think you could do the experiment: change the define, build NumPy and let us know how it goes.

**Comment by seberg** [comment]
My suggestion is the following:
* We remove `NPY_MAXDIMS` and renaming it to something that is a mouth-full like `NPY_OLD_STYLE_ITER_MAXDIMS`
  * I can accept doing this even if we end up *not* increasing the limit.  Just so I can tell those that want to bump it:  It's on you, we need some work to be done before that can happen.  (without bumping, there is the "needs major release" hurdle additionally) 
* *Someone* replaces the current legacy iterator within NumPy with a size agnostic one, which we make public  (this is the work that needs to be done)
  * If we find a enough motivation and dev cycles, we can backport that into a/the `numpy2_compat` package which would allow us to make all of downstream compatible *for* them!  (still feels magical to me that this can be done, but it's possible :))
  * If we do not find enough dev-cycles, SciPy, we will just accept that some code in downstream libs won't work for super high dimensional arrays.  If that is a problem for "Cirq", etc. then you have to work on the previous point.

Even if it is possible to ship wheels in such a way (and I doubt it is), you would double the amount of wheels that a lot of downstream needs to build.  I am pretty sure it's easier to do the full thing I said above (including that `numpy2_compat` library).

**Comment by NoureldinYosri** [comment]
I built the library with 64 instead of 32 and it works fine
```py3
>> np.ones((1,)*64, dtype=np.complex128)
array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1.+0.j]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])
```

Running the tests, most of them pass. Most of the few that fail seem to be asserting the number of dimensions <= 32 so they should be fine to modify.

<details><summary>Failed Tests</summary>

```
FAILED numpy/core/tests/test_conversion_utils.py::TestIntpConverter::test_too_many_dims - Failed: DID NOT RAISE <class 'ValueError'>
FAILED numpy/core/tests/test_indexing.py::TestIndexing::test_too_many_fancy_indices_special_case - AssertionError: IndexError not raised by __getitem__
FAILED numpy/core/tests/test_indexing.py::TestIndexing::test_too_many_advanced_indices[1-32-True] - Failed: DID NOT RAISE <class 'IndexError'>
FAILED numpy/core/tests/test_indexing.py::TestIndexing::test_too_many_advanced_indices[1-32-False] - Failed: DID NOT RAISE <class 'IndexError'>
FAILED numpy/core/tests/test_indexing.py::TestIndexing::test_too_many_advanced_indices[1-40-True] - Failed: DID NOT RAISE <class 'IndexError'>
FAILED numpy/core/tests/test_indexing.py::TestIndexing::test_too_many_advanced_indices[1-40-False] - Failed: DID NOT RAISE <class 'IndexError'>
FAILED numpy/core/tests/test_indexing.py::TestIndexing::test_too_many_advanced_indices[32-32-True] - Failed: DID NOT RAISE <class 'IndexError'>
FAILED numpy/core/tests/test_indexing.py::TestIndexing::test_too_many_advanced_indices[32-32-False] - Failed: DID NOT RAISE <class 'IndexError'>
FAILED numpy/core/tests/test_indexing.py::TestIndexing::test_too_many_advanced_indices[32-32-index2] - Failed: DID NOT RAISE <class 'IndexError'>
FAILED numpy/core/tests/test_indexing.py::TestIndexing::test_too_many_advanced_indices[32-40-True] - Failed: DID NOT RAISE <class 'IndexError'>
FAILED numpy/core/tests/test_indexing.py::TestIndexing::test_too_many_advanced_indices[32-40-False] - Failed: DID NOT RAISE <class 'IndexError'>
FAILED numpy/core/tests/test_multiarray.py::TestZeroRank::test_invalid_newaxis - AssertionError: IndexError not raised by subscript
FAILED numpy/core/tests/test_multiarray.py::TestScalarIndexing::test_invalid_newaxis - AssertionError: IndexError not raised by subscript
FAILED numpy/core/tests/test_multiarray.py::TestNewBufferProtocol::test_error_too_many_dims - AssertionError: RuntimeError not raised by array
FAILED numpy/core/tests/test_numeric.py::TestBroadcast::test_number_of_arguments - AssertionError: ValueError not raised by broadcast
FAILED numpy/core/tests/test_overrides.py::TestGetImplementingArgs::test_too_many_duck_arrays - AssertionError: TypeError not raised
FAILED numpy/core/tests/test_overrides.py::TestArrayFunctionImplementation::test_too_many_args - AssertionError: Regex pattern 'maximum number' does not match "no implementation found for 'numpy.core.tests.test_overrides.func' on types that implement __array_function__: ...
FAILED numpy/core/tests/test_regression.py::TestRegression::test_array_ndmin_overflow - AssertionError: ValueError not raised by <lambda>
FAILED numpy/core/tests/test_regression.py::TestRegression::test_frompyfunc_many_args - AssertionError: ValueError not raised by frompyfunc
FAILED numpy/core/tests/test_umath.py::test_outer_exceeds_maxdims - AssertionError: ValueError not raised
```
</details>

---


I think that having some downstream libraries  support only 32 dimensions not the full 64 dimensions is fine as a starting point. this in addition to replacing `NPY_MAXDIMS` with `NPY_OLD_STYLE_ITER_MAXDIMS` as @seberg suggested should be fine at least to get the ball rolling.

**Comment by seberg** [comment]
It would be nice to at least start fixing NumPy internals which will *also* remain limited to 32 dimensions before we bump it though.

**Comment by mattip** [comment]
> I built the library with 64 instead of 32 and it works fine

Cool. Can the large arrays  be used in the rest of your daily work or do you need to also rebuild everything else?
