### ISSUE TITLE
.H for ndarray?

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5763]
`np.matrix` has `.conj()`, `.T`, and `.H`, while `np.ndarray` has only `.conj()` and `.T` but not `.H`.

I found an extensive discussion about the idea of adding `.H` to `ndarray` a couple of years ago.

Remarks that I've interpreted as favorable towards `.H`:
Alan G Isaac http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067082.html
Ralf Gommers http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067230.html
Bryan Van de Ven http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067247.html
Dave Hirschfeld http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067249.html
Pauli Virtanen http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067256.html
Stéfan van der Walt http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067197.html

Votes against, concerns, alternatives, compromises, and devil's advocacy:
Nathaniel Smith http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067245.html
Fernando Perez (`.H()`) http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067250.html
Jerome Kieffer (`.H()`) http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067257.html
Sebastian Haase (`.H()`) http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067283.html
Dag Sverre Seljebotn (copy overhead) http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067251.html
Chris Barker (use matrix) http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067281.html
Josef Perktold http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067285.html
Stéfan van der Walt (wants ufunc views) http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067299.html

An offer to write a NEP (as of a couple years ago...):
Stéfan van der Walt http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067284.html

A summary:
Alan G Isaac http://mail.scipy.org/pipermail/numpy-discussion/2013-July/067280.html

An ancient discussion about adding `.T` which has some points relevant to `.H`:
Bill Baxter http://mail.scipy.org/pipermail/numpy-discussion/2006-July/009124.html

And an ancient voting thread that included `.T` and `.H` proposals:
Travis Oliphant http://mail.scipy.org/pipermail/numpy-discussion/2006-July/009203.html

It seems that the strongest reasons to not do this are:
1) The core ndarray interface should be kept pure without `.H`, and even `.T` was a stretch or a mistake.
2) Although `.T` is a view, `.H` would be a copy, so it would be slow/bloated and inconsistent.
3) It would be cool to automatically use conjugate transpose BLAS/LAPACK flags automatically with `.H` instead of explicitly constructing the conjugate transpose matrix, but numpy's machinery wouldn't be able to do this with a naive implementation of `.H`.

**Comment by charris** [comment]
IMHO, it is such a common operation that I think some syntax sugar is appropriate. Maybe `a.H()` ala `a.conj()`, just to emphsize that it isn't a property? I've never been opposed to a simple `a.H` however.

**Comment by njsmith** [comment]
I guess I'm still a wishy-washy -0.5 on this. ndarray has way too many
methods/attributes already -- which is a serious impediment to implementing
new duck arrays -- and .T.conj() isn't so terrible as to make this seem
very urgent. And while I'm not sure the "clever" conjugate dtype I proposed
in that email you linked is a good idea, I'm not sure it isn't, either :-).
So I'm pretty hesitant to "use up" the .H attribute without trying that (we
only get one chance, after all). I could probably be convinced otherwise.
But ideally we really like to have more than 50% opinion in favor of a new
api... I guess you could try going back to the list to try and convince
more of the doubters?

**Comment by rgommers** [comment]
@argriffing nice job on the archeology:)

**Comment by shoyer** [comment]
I'm also in favor of adding `.H` as an ndarray attribute. This is an extremely common operation when dealing with complex valued arrays.

I understand @njsmith's reluctance to "use up" the `.H` attribute, but my feeling is that the hypothetical future array package that implements lazy ufuncs is probably (a) not going to called NumPy and (b) going to entail some much broader API breakage, anyways. Turning `.H` into a view would be one of the least of my concerns in that case. NumPy itself is pretty much stuck with the strided ndarray model.

**Comment by njsmith** [comment]
Making .H a view does not require changing anything in numpy's core or
breaking api. It just ("just") requires adding a conjugate-complex dtype,
which is identical to the regular complex dtype except that casting between
them flips the sign of the imaginary part, and similarly for casts to and
from python complex scalars. If/when we overhaul the internal dtype
implementation to make adding new dtypes easier and more flexible (which is
desperately needed anyway, e.g. to allow for variable length strings,
categoricals, missing values, ...), then this really ought to be trivial to
do (just delegate to the regular complex dtype for all the hard work, and
add custom ufunc loops only in cases where there is done specific benefit,
e.g. a custom dot inner loop could take advantage of the blas conjugation
flags instead of copying).

That still obviously leaves the questions of (1) if/when this will actually
become feasible, (2) is it a good idea anyway. But that's what I'm thinking
of when I say I'm reluctant to rule this out a priori.

**Comment by shoyer** [comment]
OK, at this point I suppose we can hold out for flexible dtypes -- which I hope you'll work on soon, Nathaniel! In particular, I'd love to be able to write new dtypes in Cython or Numba.

**Comment by dbacc** [comment]
Recently, there has been a discussion about removing matrix support
https://mail.python.org/pipermail/numpy-discussion/2017-January/076290.html,

however, I believe it will be hard to convince us numerical linear algebra people from converting to ndarray if there's nothing simple like .H for complex conjugation of a matrix. 
.conj().T is just too long for being used in a numerical code that's full of matrix conjugation.

Also, the pure .conj() is rarely used in numerical linear algebra. From this point of view it makes no sense to have a direct method for .conj but not for the more common operation .conj().T

**Comment by seberg** [comment]
Closing this in favor of the above linked issue, which I think has a bit more discussion also in the direction of `.mT`, etc.
