### ISSUE TITLE
The phase of 0 is not defined, but numpy.angle(0) works

### ISSUE THREAD

**Issue by lebigot** [numpy/numpy#5778]
`numpy.angle(0)` returns 0.0.

However, in mathematics, 0 does not have any angle. I would have expected feeding 0 to `numpy.angle()` to raise an exception (or maybe generate NaN??).

Now, the standard `cmath` library has a similar function, except that it is called `phase()`. This function does return a 0 phase for 0 (unlike a mathematical phase). However, this behavior is [documented](https://docs.python.org/3/library/cmath.html#cmath.phase).

Thus, at the very least, the behavior of `numpy.angle()` for 0 should be defined in the documentation.

Since the current behavior is not officially documented yet, and since the name of the function is different from the similar `cmath.phase()` name, maybe NumPy has the opportunity to produce a more mathematically correct result for 0, like raising an exception or maybe returning NaN?

**Comment by njsmith** [comment]
It's not terribly likely that we could change this -- just because it's not
documented doesn't mean people aren't depending on it -- but I don't use
this function myself so I don't really know which answer is more useful in
practice. I guess you could ask the list, and see if lots of other people
also wish it returned nan. (Exceptions are generally avoided when possible
because they can be very inconvenient with vectorized operations, see
np.seterr if you want exceptions instead of nans in general.)

**Comment by mhvk** [comment]
Agreed that it would be better to document it rather than return `NaN` or an exception. A similar problem occurs with `np.arctan2(0.,0.)` (also returns `0`). But often when one does these types of calculation, the radius is also calculated and the angle later simply does not matter; it would be annoying if a `NaN` were returned and further calculations would start to fail. (E.g., suppose I have a large range of X,Y; I'd want conversion to polar and back to give me back my X,Y.)

**Comment by pv** [comment]
C99 standard appears to follow the view that for negative/positive zeros
along branch cuts, one takes the limit toward branch cut first, so
atan2(+0,+0)=0, atan2(+0,-0)=pi, atan2(-0,-0)=-pi

**Comment by lebigot** [comment]
@mhvk The polar/cartesian transformation is a good argument for keeping `phase(0)` at 0 (or pi/-pi), even though it is mathematically incorrect. In fact, 0*nan is nan, so a nan result would break such calculations (in addition to some of the existing code).

**Comment by lebigot** [comment]
I would conclude from this discussion that the behavior of `numpy.phase()` for 0 should simply be documented (in the same way as `cmath.angle()`'s behavior is documented).

**Comment by melissawm** [comment]
I added a note to the documentation of `numpy.angle()` to this effect. Please let me know if this is enough to close this issue.

**Comment by lebigot** [comment]
This is good, thanks.
