### ISSUE TITLE
numpy.ndarray.shape is represented by different types under Linux and Windows

### ISSUE THREAD

**Issue by Shambricool** [numpy/numpy#5809]
Under Linux it returns a tuple of ints:
```
>>> import numpy as np
>>> a = np.zeros((2,3))
>>> type(a.shape[0])
<type 'int'>
```
while under Windows it's a tuple of longs:
```
>>> import numpy as np
>>> a = np.zeros((2,3))
>>> type(a.shape[0])
<type 'long'>
```
It causes problems, for example, with writing C extensions. The following code works fine under Linux but under Windows NULL is returned and it's unobvious.
```
if (PyInt_Check(tuple_item)) {
                // do smth
            } else {
                return NULL;
            }
```
Python 2.7, numpy 1.9.2

**Comment by seberg** [comment]
You will have to use `PyLong_Check` instead. I do not think there is a reasonably way around this. On 64bit linux python2 `int` is the best type, on windows you have to use `long` to be save, that is just life....

**Comment by njsmith** [comment]
Unfortunately there's not much we can do about this :-/. For 64 bit python
2 on Windows, 'int' can only represent 32 bit integers, but Numpy shapes of
course are 64 bit. So they have to be longs, or else you'd be restricted to
arrays with only ~2 gig entries. On other 64 bit platforms, 'int' is 64
bits. I guess NumPy could ignore this and use longs anyway, but that would
be annoying and add unnecessary overhead, and in any case the decision was
made not to do that, probably before win64 even existed, so at this point
changing it would break things. And we don't want to have the types on
win64 shifting between int and long depending on how big the array is,
because that would just make writing correct code even more complicated,
and turn obvious bugs into subtle ones.

All these issues disappear on python 3, at least!

**Comment by charris** [comment]
Explanations look good, so closing this.

@Shambricool one way to look at it is that python 2 'int' is a C long. MSVC chose to make C long 32 bits on both 32 and 64 bit platforms while GCC on linux makes C long 32 and 64 bits respectively.

**Comment by jaimefrio** [comment]
Just to add to what others have said, this is indeed a Python in Windows thing:

```
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> 2147483647  # 2**31 - 1
2147483647
>>> 2147483648  # 2**31
2147483648L
```

Notice that despite using a 64 bit python, the transition from int to long happens at the 32 bit boundary.

**Comment by tylerlekang** [comment]
Hello,

Can someone please further comment as to what is actually broken, for Python in Windows 64-bit? I don't understand why it "can't" be fixed, and why just have to live with it???

For example, see below iPython session from my Windows 64-bit machine:

```
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jun 29 2016, 11:07:13) [MSC
v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: a = 5

In [2]: type(a)
Out[2]: int

In [3]: A = (a,a)

In [4]: type(A)
Out[4]: tuple

In [5]: type(A[0])
Out[5]: int

In [6]: A[0]
Out[6]: 5
```

Clearly, Python in Windows 64-bit is capable of working with int's and tuples of int's. So why isn't Numpy .shape correctly returning a tuple of int's ??? Documentation says that's what's supposed to happen: http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html

It would be one thing if we were talking about an array whose dimension length was 2^34 by 2^34, or something like that. But for a 5x5 array? Why does .shape need to return a tuple of long's to express that?

As incredible annoying as this is, I can at least live with it if someone can explain where exactly the mechanism is broken. I'll understand that since nothing is really "wrong", that it will be a low priority to fix.


Thanks!

**Comment by seberg** [comment]
Feel free to create a pull request if you like, though t to admit I have trouble seeing why it is such a big problem. Code normally has to check for both anyway on python 2. In the end this is just a conversion from `ssize_t` to a python object and if there is a nice way to do it so that it returns an int if possible, seems OK.

**Comment by seberg** [comment]
It seems we would be just making a real bug in code outside numpy less likely, not really getting rid of it...

**Comment by tylerlekang** [comment]
Why wouldn't it be as simple as doing something like this?

```
def intify_tuple(tup):
    tup_int = ()
    for tup_ent in tup:
        tup_int = tup_int + (int(tup_ent),)
    return tup_int

...
array_dims_int = intify_tuple(array_dims)

return array_dims_int
```
