### ISSUE TITLE
f2py: incorrect call to Python interpreter

### ISSUE THREAD

**Issue by berquist** [numpy/numpy#5812]
Using the following wheel from PyPI on OS X 10.9.5:
```
numpy-1.9.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
```
the shebang in `/usr/local/bin/f2py` is incorrect:
```
#!/Users/travis/build/MacPython/numpy-wheels/venv/bin/python
```

**Comment by rgommers** [comment]
Hmm, that looks wrong. @matthew-brett want to have a look at this one?

**Comment by matthew-brett** [comment]
Oops - yes - thanks for the report.

**Comment by matthew-brett** [comment]
I think this is because of:

https://github.com/numpy/numpy/blob/master/numpy/f2py/setup.py#L53

The f2py setup.py function is writing the shebang line of f2py using `sys.executable`, which is the right thing to do, unless you are making an egg or a wheel, in which case the path to the python from which the f2py code will eventually run may well be different to the path to the python from which it is built, and the shebang line should read `#!python`.

Any numpy.distutils experts out there who know the right way to fix this?  @cournape ?
