### ISSUE TITLE
Unexpected behaviors : numpy.fromfile on windows 7 - Python 2.7

### ISSUE THREAD

**Issue by oam31** [numpy/numpy#5823]
I'm running the following code :

```python
    import numpy as np

    f=open( 'band_PA2.lum', 'r' )
    f.seek(3608)
    tab = np.fromfile( f, dtype=np.float32, count=902 )
    print(tab.size)
```

(To download the file test : https://dl.dropboxusercontent.com/u/21272835/band_PA2.lum)

The correct tab.size is: **902**

But on Windows 7 - Python 2.7.9 - Numpy 1.9.2, the size is... **276** !!!  **Why ???**

On  Windows 7 (same computer) - Python 3.4.3 - Numpy 1.9.2, the size is correct, it's 902. 
Correct also on OS X, Ubuntu with Python 2.7.x

**Comment by njsmith** [comment]
Before you reach the NumPy code in your example, can you double check that
the seek call is doing what you want/expect? Technically seek(arbitrary
integer) is not guaranteed to do anything meaningful for a file on windows
opened in text mode. It might, but the os doesn't make any guarantee -- all
that's guaranteed is that you can pass back values that you got from
calling tell() -- so it might be putting you somewhere unexpected in the
file. (You're getting text mode because you wrote 'r' instead of 'rb' in
the open() call. And python 3 has its own implementation of text versus
binary io and doesn't rely on the OS's implementation.)

**Comment by oam31** [comment]
Of course! 
```python
f=open( 'band_PA2.lum', 'r' ) --> f=open( 'band_PA2.lum', 'rb' )
```
Thanks a lot!
