### ISSUE TITLE
PendingDeprecationWarning in Python 3.4

### ISSUE THREAD

**Issue by charris** [numpy/numpy#5849]
The `imp` module will be deprecated in favor of importlib. It is used in
- setupegg.py
- runtests.py
- numpy/_import_tools.py
- numpy/testing/utils.py
- numpy/distutils/misc_util.py
- numpy/core/setup.py

**Comment by charris** [comment]
I suggest putting off dealing with this until Python 3.6 or some such. The importlib module looks to be changing version to version and the documentation sucks.

**Comment by enlighter** [comment]
I was thinking about contributing through this bug, so went looking and would like to confirm the status for this issue @charris . 
I see that in numpy/core/setup.py, the current master code uses `_import__()`, i.e. using the `importlib` module. Code snippet from numpy/core/setup.py :

```
> def generate_api(ext, build_dir):
>             script = join(codegen_dir, module_name + '.py')
>             sys.path.insert(0, codegen_dir)
>             try:
>                 m = __import__(module_name)
>                 log.info('executing %s', script)
>                 h_file, c_file, doc_file = m.generate_api(os.path.join(build_dir, header_dir))
> 
```
So my question is, has this issue automatically been solved through all the stacked code changes to the repository over the 3 years since? If so, then please close this issue as resolved.

**Comment by enlighter** [comment]
From the documentation https://docs.python.org/3/library/imp.html, `imp` module was deprecated in Python 3.4, so what I suggested above seems to be the case.

**Comment by mattip** [comment]
closing. Our code now only uses `imp` in `test_reloading.py` and `numpy/compat/py3k.py`, and only on python before 3.4 (including 2.7)
