### ISSUE TITLE
Is there a list of functions which do/don't release the GIL?

### ISSUE THREAD

**Issue by DanielSank** [numpy/numpy#5897]

**Comment by njsmith** [comment]
No. In general this changes as we make improvements or refactor things, and
even if there were such a list it wouldn't be terribly useful, since the
interpreter pretty much reserves the right to release the gil at any point.
It's probably safe to assume that the gil will usually be released by
regular ufuncs called on simple data types like float64, but beyond that...
no guarantees.

**Comment by DanielSank** [comment]
It would be useful to know whether delegating numpy calls to threads will speed up or slow down a piece of code. The current method is for each user to write a little test script for every function of interest :-)

Perhaps there are some groups of functions which release the GIL and are unlikely to change in that regard. A small table would be nice to have. The documentation at present makes one small remark about array operations releasing the GIL, but that's it.

**Comment by melissawm** [comment]
General agreement is that this might not be super useful, but creating some general documentation on how NumPy interacts with the GIL might be an option.

**Comment by seberg** [comment]
This came up again in the triage meeting.  I still think that there is relatively few use in a list.
Most functions on large data (>512 elements) that don't need the GIL should release the GIL.  I am sure there are some bugs in that functions that should release, don't.
