### ISSUE TITLE
 When np.arange is called with certain parameters the output array is unexpected!

### ISSUE THREAD

**Issue by Condla** [numpy/numpy#5949]
The problem is reproducable on two different machines:
x) Windows 7, Python 3.4.3, numpy 1.9.2
x) Centos 6, Python 2.6.6, numpy 1.4.1

When np.arange is called with start parameter 0.5 and stop parameter 1.1 the returned array includes one more value than expected. Any other combinations of start and stop parameters I tried so far deliver the expected output.
Here are two examples of the concrete problem, which are also shown in the screenshot attached.
np.arange(0.5, 1.1, 0.1) returns: array([ 0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1])
np.arange(0.5, 1.1, 0.2) returns: array([ 0.5,  0.7,  0.9,  1.1])
![python_numpy_arange_bug](https://cloud.githubusercontent.com/assets/4442327/8023256/ed7cd11e-0d02-11e5-90ff-87d9bb882ae4.png)

**Comment by njsmith** [comment]
This is surprising but correct, because floating point is weird. The reason is this:
```
In [4]: a = np.arange(0.5, 1.1, 0.1)

In [5]: a
Out[5]: array([ 0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1])

In [6]: a[-1]
Out[6]: 1.0999999999999999
```
So you see that the last entry in that array actually is less than 1.1, so according to the definition of `arange` it actually should be included. Of course the fact that it is less than 1.1 is dependent on the exact way the rounding error happened to work out, and might be different across different versions of numpy or even across different platforms and compiler versions... but there is no general way to solve this; there will always be rounding error in some cases, and sometimes it will produce weird results for `arange`.

This is why the `arange` docs say: "When using a non-integer step, such as 0.1, the results will often not be consistent.  It is better to use `linspace` for these cases."

There's not much we can do about this, except perhaps improve the docs. Since you've just run into the problem, do you have any suggestions for how the docs could have been clearer and prevented your confusion?

**Comment by Condla** [comment]
Thanks for the clarification. It's actually pretty clear this way and linspace is indeed more predictable.
I guess I should have re-read the docs after I stumbled upon this issue.
I hereby close this issue.
