### ISSUE TITLE
argsort/sort with O(n) algorithms: counting-sort, radix-sort

### ISSUE THREAD

**Issue by d1manson** [numpy/numpy#6050]
You can already sort with [couting-sort](https://en.wikipedia.org/wiki/Counting_sort) using numpy: as stated in an [SO answer](http://stackoverflow.com/a/18502321/2399799), it is simply:

``` python
np.repeat(np.arange(1+x.max()), np.bincount(x))
```

But there is no way (as far as I can tell) to do an argsort.

I think it would be fairly easy to implement and slot into the argsort/sort documentation.   The benefit of counting sort is that it's O(n), although it only works for not-too-large non-negative integers...however those are actually quite common in the real world!  Pandas uses it behind the scenes [apparently](http://wesmckinney.com/blog/tag/pandas/).

**Comment by jaimefrio** [comment]
I've been toying with the idea of adding some of the O(n) sorting algorithms to NumPy for some time now: counting sort for u/int8s and bools, radix sort for larger ints, timsort for object arrays...

The most difficult thing to do is figure out how to adapt the current NumPy API to fit the new functionality without cluttering it to much. At some point I was thinking on adding to the current options of quicksort, mergesort, heapsort, that sort and argsort provide, two more options: fastest and stable, probably with better names. The idea is that these two new selectors do not have to point to new implementations (you could map fastest to quicksort and stable to mergesort and be done with it), and if they do, they do so in a more or less concealed manner, so that the internals can be changed at will without breaking any user code.

**Comment by njsmith** [comment]
If thinking about such changes then it would also be good to keep in mind
the possibility of moving sort to become a gufunc, and possibly
generalizing the api so we don't have exactly 3 sorts which every type
implements.

**Comment by d1manson** [comment]
Everyone loves a super fast sort!

In terms of API, why not keep the old `kind` kwarg for backward compatibility, but then add other keywords to control each requirement/hint.  Any/all hint kwargs could be ignored in initial/future implementations:

* `stable` - `True`/`False`.
* `nearly_sorted` - `True`/`False`
*  `small_int_range` - `True`/`False`
* `small_float_set` - `True`/`False`
etc.

**Comment by hameerabbasi** [comment]
I realize this is an old issue, but this will be super useful.
