### ISSUE TITLE
Documentation guidelines: dead link to Q+A

### ISSUE THREAD

**Issue by SuperFluffy** [numpy/numpy#6107]
The [other points to consider section][1] in the documentation contains the following statement:

> Questions and Answers : For general questions on how to write docstrings that are not answered in
> this document, refer to http://docs.scipy.org/numpy/Questions+Answers/.

If you try to open that URL you will quickly get the following error thrown at you:

> Not Found
> 
> The requested URL /numpy/Questions+Answers/ was not found on this server.

Please fix, as I am quite interested in that section.

[1]: https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#other-points-to-keep-in-mind

**Comment by rgommers** [comment]
@SuperFluffy that Q&A page doesn't exist anymore (was part of the docwiki editor app that we discontinued). Much of the answers on that page are now more obvious than they were back then, because the numpy docstrings themselves are in good shape. If you have any specific questions though, please post them here. We'll answer them, and add them to the howto document if needed.
