### ISSUE TITLE
Feature request: Support for arbitrary byte length integers

### ISSUE THREAD

**Issue by krlk89** [numpy/numpy#6130]
I have binary files where information is stored in 1 to 8 byte(s) long integers (depening on the file).

Would be nice to be able to manually specify byte length of integer when reading from binary file and adding the integers to a (structured) numpy array.

At the moment I can only read files where integers are either 1, 2, 4 or 8 bytes long.

**Comment by njsmith** [comment]
You can't have a numpy array where some entries have 2 bytes and others have 8 bytes, etc.; it's a fundamental architectural limitation of numpy that all elements in an array have to have the same size. (The only partial exception is structured dtypes, and these require each element in the array to contain the same set of possibly-inhomogenous fields.)

OTOH if what you have is a file that either contains a bunch of 1 byte integers, or else contains a bunch of 2 byte integers, etc., then this can be done pretty easily with numpy. One could get fancy constructing dtype strings like `"i4"` programmatically, but I'd probably keep it simple with something like:
```
dtype_for_size = {
    1: np.int8,
    2: np.int16,
    ...
}
np.fromfile(..., dtype=dtype_for_size[size])
```

Since afaict there's nothing for numpy to do here, closing the ticket. Feel free to reopen if this is wrong.

(Also, stackoverflow is often a good place to ask questions about how to best accomplish things like this -- if my quick comments above are confusing or inapplicable, then asking a question there is probably the quickest way to get a more complete answer.)

**Comment by krlk89** [comment]
Thanks for the reply.

Sorry if my original post was not clear enough, I don't want a non-homogeneous numpy array. Inside one input file all integers are of same size and I don't need to combine multiple inputs to one array.

What my problem is: How can I add an integer that is either 3, 5, 6 or 7 bytes in length to a numpy array? These data types seem to be unsupported by numpy. Or am I missing something?

**Comment by njsmith** [comment]
Yes, those data types are unsupported by numpy.

On Wed, Jul 29, 2015 at 1:00 PM, Kaarel <notifications@github.com> wrote:

> Thanks for the reply.
>
> Sorry if my original post was not clear enough, I don't want a
> non-homogeneous numpy array. Inside one input file all integers are of same
> size and I don't need to combine multiple inputs to one array.
>
> What my problem is: How can I add an integer that is either 3, 5, 6 or 7
> bytes in length to a numpy array? These data types seem to be unsupported
> by numpy. Or am I missing something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6130#issuecomment-126079342>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by krlk89** [comment]
Can I reopen the feature request (with some clarification)? Or will it be pointless?

**Comment by argriffing** [comment]
Here's a related scipy issue for 24-bit (3 byte) integer data https://github.com/scipy/scipy/issues/1930.

**Comment by njsmith** [comment]
That scipy issue has an example of how to read 3 byte integers into a 4
byte array. That's going to be much easier, and also much more useful in
most cases, than adding full native 3-byte integer support to numpy.

**Comment by ahaldane** [comment]
Here's another strategy to read a 5-byte integer file:

    def read5bfile(filename):
        data = fromfile(filename, 'V5')
        result = zeros(data.shape, 'V8')
        result[:] = data  # pads with 0
        return result.view('i8')

You probably have to be careful about endianness if that matters.

**Comment by krlk89** [comment]
What about a structured array? *E.g.* something like this:

def read5bfile_structured(filename):
    x = np.fromfile(input_file, dtype = [("record", 5b_as_8b), ("counter", "<u4")])

**Comment by argriffing** [comment]
@krlk89 according to some docs 'V' means raw data (void).
http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html
http://docs.scipy.org/doc/numpy/reference/arrays.interface.html#arrays-interface

**Comment by ahaldane** [comment]
@krlk89, that's right, 'V' stands for void type. This represents a series of bytes with no interpretation. When you 'cast' to a void type of different length, numpy will pad the original bytes with 0 if the new type is longer (eg V5 to V8), or it will truncate the bytes if the value is shorter (eg V8 to V5).

It sounds like your file is composed of structures, which are composed of a 5 byte integer followed by a 4 byte counter value. Here's how I would read it (assuming the 5 byte integer is little-endian):

    np.fromfile(f, 'V5,u4').astype('V8,u4').view('i8,u4')

The 'astype' step casts the V5 to a V8 (padding with 0), and then the 'view' reinterprets the 8 bytes as an 8-byte integer. If your integer is big-endian things are trickier.

Actually, thinking out loud, maybe it would be a good improvement to numpy if byteswapping a void type reversed the bytes. It doesn't currently, making it tricky to deal with big-endian data because of the way padding/truncation of voids work.

**Comment by ahaldane** [comment]
By the way @krlk89, it just occurred to me that my strategy will also get you into trouble if your 5-byte integers are signed, since they then need to be padded with 0xff instead of 0x00 when casting to 8 bytes. So maybe the solution linked by @njsmith is better.

**Comment by krlk89** [comment]
@ahaldane Thanks a lot for the help, my file consists of little-endian unsigned integers, so I can apply your solution directly!

Is there a way to keep the column names though? I need to do some arithmetics with the count column and it would be of help.

**Comment by ahaldane** [comment]
Sure, ``'u8,u4'`` is just shorthand for ``[('f0', 'u8' ), ('f1', 'u4')]`` so you can replace the last format with that, with different names:

    np.fromfile(f, 'V5,u4').astype('V8,u4').view([('record', 'u8' ), ('counter', 'u4')])
