### ISSUE TITLE
Inconsistent dtype behavior of numpy.where()

### ISSUE THREAD

**Issue by ndjensen** [numpy/numpy#6155]
The numpy.where() function was rewritten in numpy 1.9 to speed it up.  I
traced it to this changeset.
https://github.com/numpy/numpy/commit/593e3c30c24f0c61a271dc883c614724d7a57e1e

The weird thing is the 1.9 behavior changed the resulting dtype in some situations when using scalar values as the second or third argument.  To illustrate, I wrote a simple test script and ran it against both numpy 1.7 and 1.9.  Here are the results:

```
2.7.9 (default, Jul 25 2015, 03:06:43)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
***** numpy version 1.7.2 *****

=== testing numpy.where with integers ===
numpy.where([True], [numpy.float32(1.0)], 65535).dtype
float32
numpy.where([True], [numpy.float32(1.0)], 65536).dtype
float32
numpy.where([True], [numpy.float32(1.0)], -32768).dtype
float32
numpy.where([True], [numpy.float32(1.0)], -32769).dtype
float32


2.7.9 (default, Mar 10 2015, 09:26:44)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
***** numpy version 1.9.2 *****

=== testing numpy.where with integers ===
numpy.where([True], [numpy.float32(1.0)], 65535).dtype
float32
numpy.where([True], [numpy.float32(1.0)], 65536).dtype
float64
numpy.where([True], [numpy.float32(1.0)], -32768).dtype
float32
numpy.where([True], [numpy.float32(1.0)], -32769).dtype
float64
```

In 1.7 the resulting dtype is consistent but then in 1.9 the resulting dtype is influenced by the value of the int.  It appears it is somehow related to whether the value falls within the
range of a short.  Ideally it would not upcast to float64 if not necessary, but an alternative solution would be to have it consistently upcast.  The same tests with numpy.ma.where() consistently produce float64 results.  Regardless of solution, the behavior should be more consistent when passing in a scalar without a cast.

**Comment by ndjensen** [comment]
This is related to #5095.

**Comment by ndjensen** [comment]
Behavior with NaNs is inconsistent too, though that appears to be much older than the 1.9 code.  It would be cool if NaNs were more consistent, and a step further, if where with NaNs had the optimizations like operators to not upcast.

```
=== testing numpy.where with NaNs ===
numpy.where([True], numpy.float32(1.0), numpy.NaN).dtype
float64
numpy.where([True], [numpy.float32(1.0)], numpy.NaN).dtype
float32
numpy.where([True], numpy.float32(1.0), [numpy.NaN]).dtype
float64
numpy.where([True], [numpy.float32(1.0)], [numpy.NaN]).dtype
float64
```

**Comment by juliantaylor** [comment]
hm the where change also included a change to the upcasting rules specifically to avoid this:
https://github.com/numpy/numpy/blob/master/doc/release/1.9.0-notes.rst#special-scalar-float-values-dont-cause-upcast-to-double-anymore

too bad some special cases where missed.

**Comment by ndjensen** [comment]
Yeah I saw that and noticed it works as described for things like multiply * operator, but not where().  Wasn't sure if where counted as an "operation" in this regards.  To get around it I'm just going to try and update usage of where with NaNs in our system to explicitly cast NaN to numpy.float32.

**Comment by OmerJog** [comment]
is this still an issue?

**Comment by seberg** [comment]
The behaviour is still the same. However, I do not think it is an actual issue the NaN cases above actually all are expected (and consistent with what ufuncs do. Compare with `np.add(in1, in2).dtype`):
```
=== testing numpy.where with NaNs ===
numpy.where([True], numpy.float32(1.0), numpy.NaN).dtype
# float64  because both inputs are scalar and NaN defaults to float64.
numpy.where([True], [numpy.float32(1.0)], numpy.NaN).dtype
# float32 is 1-D, NaN is scalar/0D → float64(NaN) is demoted to float32. 
numpy.where([True], numpy.float32(1.0), [numpy.NaN]).dtype
# float64 since float64(NaN) is 1-D array, since it is inside the list!  <--- Confusing?
numpy.where([True], [numpy.float32(1.0)], [numpy.NaN]).dtype
# float64, both are arrays, so normal promotion of float64 and float32
```
The third one may be confusing. The reason is that the way numpy does value based promotion of scalars is broken. NumPy first always converts to arrays, and then decides that 0-D arrays can be demoted sometimes. So the `[NaN]` is actually `np.array([NaN])` which has float64.

Too much information moving forward:

On the one hand, this is nice, because it creates no difficulties for functions first converting everything to an array. On the other hand it is inconsistent, since the dimension of the array has such a weird effect. We/I want to get rid of some of this. However, we may want to keep the current behaviour for python scalars. One of the main problem may be python functions (also in downstream libraries), which do `np.asarray(...)` as first step, but would like the scalar behaviour if possible. That is likely wide spread, but tagging on a warning might be very hard. We may need to rip of the bandaid...
