### ISSUE TITLE
linspace(retstep=True) does not return step size in some cases

### ISSUE THREAD

**Issue by eyaler** [numpy/numpy#6170]
bins, step = linspace(1,4,1,retstep=True) gives ValueError: need more than 1 value to unpack
this happens when num<=1

**Comment by jaimefrio** [comment]
Works on latest master for me:

```
In [13]: np.linspace(1, 4, 1, retstep=True)
Out[13]: (array([ 1.]), nan)
```

There were a number of changes to `linspace` after `1.9`, namely to properly handle denormals, but the overall logic was also improved. What version of numpy are you using?

**Comment by eyaler** [comment]
1.9

**Comment by jaimefrio** [comment]
I'm going to close it as fixed then. A 1.10 beta release should be coming out shortly, would be great if you could validate it fixes your problem. Oh, and thanks for reporting the bug.

**Comment by georgezhukov1998** [comment]
I guess the issue should be reopened. The following code
```
n = 10000
maxx = 100
numx = 100
arrx,deltax = np.linspace(0, maxx, numx, retstep = True,endpoint = True)
print(arrx,deltax,deltax*numx)
```
should return something like:
`[0. 1. 2.... 99. 100.]    1    100`
because endpoint == True.

However, that code returns:
`[  0.           1.01010101   2.02020202   3.03030303 ... 97.97979798  98.98989899 100.        ] 1.0101010101010102 101.01010101010101 100`

Note that deltax value is OK if endpoint = False. In that case output looks like:
`[0. 1. 2.... 98.  99. ]    1    100`

I used last version of numpy - 1.19.2, Python - 3.8.5
