### ISSUE TITLE
Wrong result for integer power on underflow

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#6215]
Should be 0, but returns infinity:

```
>>> np.intp(10) ** np.intp(-127)
__main__:1: RuntimeWarning: divide by zero encountered in long_scalars
__main__:1: RuntimeWarning: overflow encountered in long_scalars
inf
```

**Comment by jaimefrio** [comment]
What seems to be happening is this:

```
>>> np.intp(10)**np.intp(127)
...:1: RuntimeWarning: overflow encountered in long_scalars
0
```

coupled with the logic [here](https://github.com/numpy/numpy/blob/maintenance/1.10.x/numpy/core/src/umath/scalarmath.c.src#L1036).

Perhaps negative exponents should always be sent to a floating point power function, rather than computing the inverse as an integer power, then inverting?

**Comment by seberg** [comment]
Seems we now have an error in place for negative integer powers. The error about very large powers overflowing mentioned in the second comment is also mentioned in other issues, i.e. gh-10964, so closing.
