### ISSUE TITLE
ENH: Automatic copy on overlap

### ISSUE THREAD

**Issue by pv** [numpy/numpy#6272]
Tracking issue as a continuation to gh-6166
- [x] add copy-on-overlap to nditer, as optional flag gh-8043
- [x] use it for ufuncs gh-8043 
- [ ] check whether copy-on-overlap is respected in indexed assignment
- [x] respect it for `dot()` gh-8539
- [ ] check other places in numpy that may need checking

<s>Some initial code, https://github.com/numpy/numpy/compare/master...pv:copy-overlap
</s>

**Comment by charris** [comment]
@seberg @pv I was under the impression this was pretty much done for 1.13. Is that the case?

**Comment by pv** [comment]
It's done for ufuncs (and thus also for binops and most of numpy.linalg), and dot. There however may still be some problematic code paths in other operations, such as in indexed assignment.

**Comment by seberg** [comment]
It is true, it might be only smaller things left, had not thought about it much (in general things with an out argument are in danger that are not a ufunc):
 * `copyto` (should be identical to non-advanced indexing assignments)
 * `median`/`percentile` (use `_ureduce` python function which could possible get the treatment)
 * `np.choose` seems to have an `out` argument, so in principel can overlap.
 * `np.take` can overlap with `out`
 * The weird indexing likes (which I would avoid personally but...) `put`, `putmask`, `place`.
 *  `np.around`
 * (possibly `apply_(along|over)_axis`)
 * and probably a few more, looked around a bit but not very systematically

**Comment by ahaldane** [comment]
Reviewing this as part of my 10 random issues, as requested in a [3/20/19 request](https://mail.python.org/pipermail/numpy-discussion/2019-March/079250.html).

I am 95% sure this is done and just forgotten to be closed, because in 2019 I have seen these overlap checks in the assignment code, including in code involving assignment to slices of an array.

I'm going to go ahead and close this, please reopen if that's wrong.

**Comment by matthew-brett** [comment]
Is this really safe to close?   Has anyone checked the list above?

**Comment by mattip** [comment]
I think the only unresolved case is when an array has overlap due to striding tricks. PR #12609 tries to make arrays with 0 strides read-only, in response to issue #2705.

**Comment by matthew-brett** [comment]
But specifically - has someone gone through that list above and checked whether they are resolved or not?   It seems to me that this issue should stay open until someone has done that.

**Comment by ahaldane** [comment]
I'll go through it now...

**Comment by seberg** [comment]
Indexing assignments do use it, advanced indexing does not. I doubt a lot of the other functions I listed above never got treatment.

**Comment by ahaldane** [comment]
These seem OK:
 * `copyto` is OK since it goes through `PyArray_AssignArray`, which has an overlap check.
 * `_ureduce` code (eg, median/percentile) looks OK since it is pure python and delegates to ufuncs
 * `around` is ok because it delegates to ufuncs

Problematic:
 * `np.take` There is no overlap detection. Demonstration: `np.take(x, [1,2,3], out=x[2:5], mode='wrap')  -> `array([1., 1., 1.])`. 
 * `np.choose` no apparent overlap detection. Demonstration: `np.choose([0,0,0], [x[:3], x[:3], x[:3]], out=x[1:4], mode='wrap')` -> `array([1, 1, 1])`
 * I didn't carefully check, but I expect put and others in that file are the same.

Note that for both of these, with `mode='raise'`, which is the default, a copy of out is always made to avoid clobbering out if an error occurs during processing, so there will be no risk of overlap. (incidentally, this seems unexpectedly inefficient for most people!). 

So if we think those last ones should be fixed, we should keep this open.

**Comment by mattip** [comment]
Closing, #13182 covered the last outstanding cases. Please reopen if I misunderstood
