### ISSUE TITLE
odd boolean result for np.dtype

### ISSUE THREAD

**Issue by jreback** [numpy/numpy#6294]
numpy 1.9.2

python objects should report a bool of `True` except for empty ones

```
In [1]: bool(1)
Out[1]: True

In [2]: bool([])
Out[2]: False

In [3]: bool(np.dtype('int64'))
Out[3]: False

In [4]: bool(np.dtype('float'))
Out[4]: False
```

https://github.com/libdynd/dynd-python/issues/353

**Comment by jcrist** [comment]
The issue here has to do with how python evaluates `__bool__`/`__nonzero__` when not defined (see the docs here: https://docs.python.org/3/reference/datamodel.html#object.__bool__). If `__bool__` isn't defined, it falls back to `__len__`. `np.dtype` objects define `__len__` to be the number of fields in the dtype (https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/descriptor.c#L3607-L3618). Scalar dtypes have no fields, so they evaluate as False:

```python
>>> bool(np.dtype('f8'))
False
>>> bool(np.dtype([('a', 'f8')]))
True
```

To me the boolean behavior seems non-intuitive. If there's no opposition, a simple solution would be to just define `__bool__`/`__nonzero__` to return `True` for all dtypes.

**Comment by jcrist** [comment]
Related old issue: https://github.com/numpy/numpy/issues/2298

**Comment by shoyer** [comment]
I agree, that seems like a solid solution to me. I don't think many people are relying on the old behavior.
