### ISSUE TITLE
augmented assignment doesn't vectorize as expected

### ISSUE THREAD

**Issue by dadkins** [numpy/numpy#6305]
The following code, written as a loop,

a = np.array([0, 0, 0])
v = [1, 2, 1]
for i in v:
  a[i] += 1

results in a = [0 2 1].

I attempted to vectorize it, as follows

a = np.array([0, 0, 0])
v = [1, 2, 1]
a[v] += 1

which resulted in a = [0 1 1].

Why are these two versions not equivalent?

**Comment by njsmith** [comment]
It's because python expands 'a[v] += 1' into something like 'tmp = a[v];
tmp += 1; a[v] = tmp', so the link between the indexing and the adding gets
lost. Since this happens at the interpreter level, there's nothing numpy
can do about it.
.
To work around this, numpy provides special indexing-plus-assignment
versions of all its operators -- try np.add.at(a, v, 1)

**Comment by dadkins** [comment]
Thanks for the pointer. I didn't realized the syntax wouldn't work directly.
