### ISSUE TITLE
The `f` attribute of the object returned by numpy.load is not documented

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#6337]
When reading an `npz` file, `numpy.load` returns an object that has an attribute called `f`.  `f` has attributes with names and values corresponding to the names and values of the variables stored in the file.  Since `f` does not have a leading underscore, I assume `f` is intended to be part of the public API, but `f` is not documented in the docstring of `numpy.load`.

Here's an example (see http://stackoverflow.com/questions/32682928/loading-arrays-from-npz-files-in-pythhon/32683037#32683037):

```
In [1367]: foo = np.load('foo.npz')

In [1368]: foo.keys()
Out[1368]: ['A', 'C', 'B']

In [1369]: foo.f.A
Out[1369]: array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.])

In [1370]: foo.f.B
Out[1370]: 
array([[ 0,  1],
       [-1,  0]])

In [1371]: foo.f.C
Out[1371]: array([ 3.14159265,  2.71828183,  0.57721566])
```

**Comment by charris** [comment]
Interesting. `f` seems a bit obscure. @teoliphant Do you recall what it stood for?

**Comment by njsmith** [comment]
It is described in the docstring for np.lib.npyio.NpzFile (which it looks
like was written by Pauli in 2009, after being implemented by Travis back
in 2007). I assume the name "f" is because it provides "field"-style access
instead of dictionary-style access. The actual semantics are that all
attribute lookups on my_npz.f are converted into __getitem__ lookups on
my_npz.
.
Probably should just be documented in the "Notes" section of the np.load
docstring, next to the other notes on special cases that apply to npz files.

On Sun, Sep 20, 2015 at 8:49 PM, Charles Harris <notifications@github.com>
wrote:

> Interesting. f seems a bit obscure. @teoliphant
> <https://github.com/teoliphant> Do you recall what it stood for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6337#issuecomment-141870186>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by WarrenWeckesser** [comment]
@njsmith Thanks.  I've updated my answer on stackoverflow so that it refers to the `NpzFile` class for a description of the `f` attribute.

It would be nice if the documentation could be tweaked so that the `NpzFile` class docstring becomes part of the online documentation.  Then the new note in the `load` docstring could link to the `NpzFile` docstring.

**Comment by teoliphant** [comment]
@njsmith is basically correct.   It stood for "field" and was a short letter so that it took as little typing as possible to provide the ability to translate getattr to getitem.
