### ISSUE TITLE
issus about numpy number comparison after accumulate

### ISSUE THREAD

**Issue by boscotsang** [numpy/numpy#6345]
In [1]: import numpy

In [2]: a = numpy.array([0.9, 0.05, 0.03, 0.02])

In [3]: a
Out[3]: array([ 0.9 ,  0.05,  0.03,  0.02])

In [4]: a = numpy.add.accumulate(a)

In [5]: a
Out[5]: array([ 0.9 ,  0.95,  0.98,  1.  ])

In [6]: a>0.95
Out[6]: array([False,  True,  True,  True], dtype=bool)

In [7]: a>numpy.float64(0.95)
Out[7]: array([False,  True,  True,  True], dtype=bool)

After accumulate the array, it seems that the precision of the number cause some issue while comparison. Could you help me out this problem? Thanks

**Comment by juliantaylor** [comment]
this an expected rounding error due to the finite precision of the floating number type, neither 0.9, 0.05 nor their product can be represented exactly with binary based ieee754 floats so you introduce errors in every operation
the resolution or machine precision (epsilon) of float64 is 1e-15 so you need to give your computation some leeway, e.g. via:

a > 0.95 + np.finfo(np.float64).resolution*3

three epsilon is an upper bound on the error of this operation as you have three sources of error, the rounding of the numbers 0.9 and 0.05 themselves and the sum of the two values, in practice the error might be smaller as the rounding error can go in both directions.

see also
http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html
