### ISSUE TITLE
argsort(argsort()) behavior not stable?

### ISSUE THREAD

**Issue by wendykan** [numpy/numpy#6357]
When sorting a list of exactly the same values, when the length is < 16, the order is preserved, when length > 16, the order is scattered. 

    >>> np.argsort(np.argsort([2]*16))
    array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

    >>> np.argsort(np.argsort([2]*17))
    array([ 0, 14, 13, 12, 11, 10,  9, 15,  8,  6,  5,  4,  3,  2,  1,  7, 16])

This is avoided when it's sorted by mergesort:

    >>> np.argsort(np.argsort([2]*17,kind='mergesort'),kind='mergesort')
    array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

**Comment by njsmith** [comment]
Yeah, there's a little table in [the documentation] (http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html) explaining that of the supported sorting modes, only mergesort is stable.

@charris: if people are being confused because they expect default sorts to be stable in python, I guess that's kind of an argument for making mergesort the default. And it'd be backwards compatible because it only guarantees more than the current default. But I assume there's some good reason why not, like it's noticeably slower or something?

**Comment by wendykan** [comment]
Thanks @njsmith!

**Comment by charris** [comment]
@njsmith It is slower and uses extra memory.

**Comment by njsmith** [comment]
Oh duh, on the memory part. Well, too bad then :-).
