### ISSUE TITLE
Error easy_installing Numpy

### ISSUE THREAD

**Issue by sstikons** [numpy/numpy#6365]
I'm using easy_install to install numpy and getting the install error shown below. Can somebody please tell me what is causing this error and what I can do to fix it?

![image](https://cloud.githubusercontent.com/assets/14841518/10108734/aca07436-6390-11e5-8f69-9f8e019742bd.png)

**Comment by njsmith** [comment]
You're trying to compile numpy from source, but as the message says at the
bottom, you need visual studio compilers installed to compile numpy from
source.
.
The most direct solution would be to install the compilers using the URL
listed on that message... But I don't recommend that.
.
The simplest solution might be to switch to using pip instead of
easy_install. This would be a good idea regardless (easy_install had been
deprecated for years). If you're using a 32 bit python, then this should
just work, because there are prebuilt numpy binaries that pip knows how to
find; on 64 bit python it won't be able to find them automatically but you
could try cgohlke's builds (you can Google them).
.
Or, if you just want a working version of the whole scientific stack
without hassles, then you should start over and instead of installing
python from python.org, use one of the scientific python distributions like
Anaconda or winpython.
.
http://scipy.org/install.html

**Comment by sstikons** [comment]
Great advice! I installed Anaconda... has everything I need. Thank you.
