### ISSUE TITLE
Inconsistent behaviour in array multiplication using *=

### ISSUE THREAD

**Issue by 0mar** [numpy/numpy#6379]
I saw similar reports in #6074 and #4707, but I didn't find any report matching this issue exacly.
When multiplying arrays `a` and `b`, `a*=b` and `a=a*b` are not equivalent if their types are different.

The same happens with addition.

In Numpy 1.8.2, on python 3.4, different behaviour is observed in the following two cases:

```python
import numpy as np
```
# 1
```python
a1 = np.array([1,2])
c = np.array([0.7,0.7])
a1*= c
print(a1,a1.dtype)
```
Output:
```[0 1] int64```
# 2
```python
a1 = np.array([1,2])
c = np.array([0.7,0.7])
a1= a1*c
print(a1,a1.dtype)
```
Output
```[ 0.7  1.4] float64```

However, I'm not sure whether this is a bug, or just a matter of semantics.

**Comment by seberg** [comment]
There is no inconsistency here, because the first example corresponds to:
```
a1[...] = a1 * c
```
since it is in-place the data type cannot change, so that there is an (unsafe) cast involved. Note that there *is* a deprecation warning about this, and it may be turned into an error in the future (or maybe it was already in 1.10). Which will force the user to make the cast manually.

If you have any further questions, feel free to ask.
