### ISSUE TITLE
Atomic dtypes are not interned by unpickling

### ISSUE THREAD

**Issue by ogrisel** [numpy/numpy#6422]
When debugging an inconsistent behavior in `joblib.hash` (joblib/joblib#251) we noticed that atomic dtypes are always interned by default:

```python
>>> np.dtype('float32') is np.dtype('f4')
True
```

Note that this is not the case for compound dtypes:

```python
>>> np.dtype('f4, f8') is np.dtype('f4, f8')
False
```

This is all fine. The problem however is that this behavior is not preserved when unpickling atomic dtypes:

```python
>>> import pickle
>>> dtype_f4 = np.dtype('f4')
>>> dtype_f4 is pickle.loads(pickle.dumps(dtype_f4))
False
```

Apparently it comes from the fact that the `__reduce__` method of the `dtype` class asks to build the new instance with the `copy=True` constructor argument to explicitly disable the dtype interning both for atomic and compound data types. This makes it behave as follows:

```python
>>> np.dtype('f4') is np.dtype('f4', copy=True)
False
```

This unpickling behavior is quite surprising. Is this intended? Why not make atomic dtypes always (or never) interned in a consistent manner?

**Comment by njsmith** [comment]
dtypes are definitely not singletons in general, and shouldn't be compared using `is`. The reason you often get the same object back is purely a side-effect of internal convenience choices (it's easier to do `return the_global_f4_object` than to make a new one from scratch all the time).

I believe that the unpickling behavior is just that it was the most convenient way to write the unpickling code. The way it works for, say, a `np.dtype(">f4")` (note the endian-ness flag) is that it generates code that first creates a new "f4" dtype object, and then uses `__setstate__` to set the endian flag. But it would be really bad if you called `__setstate__` on the global object :-). In principle you could carefully set `copy=True` or `copy=False` depending on whether the `__setstate__` call was going to do anything non-trivial, but it's easier and safe to just always use `copy=True`.

Closing because I'm not immediately seeing anything to do here, but feel free to re-open if you think there's more to do.

**Comment by ogrisel** [comment]
Alright thanks for the explanation. If the dtypes get refactored at some point it would be great to take that as an opportunity to implement consistent interning behavior at unpickling time for the sake of the principle of least astonishment but this is no big deal.

In particular the endian flag could be passed by default in the constructor by `__reduce__` and there would be no need to use `__setstate__` and ideally dtypes could be made immutable.

**Comment by njsmith** [comment]
Alas, we cannot make them fully immutable, because that would break existing pickles which unconditionally use `__setstate__`! I actually added some sad faces next to my scratch notes on immutability earlier today, based on what I learned from this bug :-(.

I guess this is not really a big deal since most immutable python objects are only immutable by convention, and we can let `__setstate__` mutate without allowing other operations to mutate. But: :-(.
