### ISSUE TITLE
ma.put issue

### ISSUE THREAD

**Issue by dieterv77** [numpy/numpy#6425]
The following snippet does not behave as expected:

import numpy.ma as ma
z = ma.array([3.0, ma.masked])
data = ma.zeros(10)
ma.put(data, [1,2], z)

print data[3] # will throw an IndexError

If after initializing z, I do
z.mask = ma.getmaskarray(z)
then everything works fine.

**Comment by jjhelmus** [comment]
For me the expected results are obtained when the the mask of data is expanded using `data.mask = ma.getmaskarray(z)`, indicating this is an issue with the "shrunk" mask of data.  

The issue is that the logic in [lines 4414-4415 of ma/core.py](https://github.com/numpy/numpy/blob/d573c634404da658653b35414053bc82f9a358d3/numpy/ma/core.py#L4414-L4415) assume that the mask of the values can be used to create the mask for the entire array, which is not true.  I believe in this case the mask should be expanded using getmaskarray and then the mask of the values put into this expanded mask.

I will submit a PR to address this bug later today.
