### ISSUE TITLE
Weird behavior with float128*python long

### ISSUE THREAD

**Issue by pv** [numpy/numpy#6455]
It appears operations between float128 and python longs have some strange corners:

```
>>> import numpy as np
>>> np.__version__
'1.11.0.dev0+9cc55dc'
>>> a = np.float128(0.8)**8000
>>> a
5.246817223924217961e-776
>>> b = 2**64
>>> b
18446744073709551616L
>>> a*b
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'numpy.float128' and 'long'
>>> b*a
Traceback (most recent call last):
  File "<console>", line 1, in <module>
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

The first one makes some sense, but the second one is strange. (Apparently, this can also trigger segfaults, cf. https://stackoverflow.com/questions/33072998/how-to-multiply-a-super-large-number-with-a-super-small-number-in-python )

Results are similar with Numpy 1.8.2

**Comment by ewmoore** [comment]
If #7459 is merged, both `a*b` and `b*a` here will raise the unsupported operation `TypeError`.  For all other types where this multiplication works, we end up returning a builtin python type.   For `b = 2**64` we probably could return a long double, since `2**64` fits, but all that really does it push the precision loss out to larger sizes. 

Alternatively, we could do as python does and just force cast the `int` to the floating type. By deferring to python in this case that's effectively what we do for the `float64` case right now.  I admit to preferring this choice.  That this doesn't fail for all other types means that this is a wart waiting for people to trip on.

**Comment by seberg** [comment]
Seems 1.16 (with python 3.7) will segfault, probably due to not catching the maximum recursion depth specifically. Test to easier copy paste for the future:
```python
import numpy as np
a = np.float128(0.8)**8000
b = 2**64
b * a  # May raise a TypeError, currently crashes.
```

**Comment by mattip** [comment]
connected to #13003?

**Comment by seberg** [comment]
I do not think so, since `Decimal.dtype` is not defined. Although the fix may look similar, in the sense of using pythons recursion safe-guard macros.

**Comment by seberg** [comment]
This is all effectivly fixed by various cleanups (the last one bing NEP 50).
