### ISSUE TITLE
np.allclose returns memmap object when comparing a memmap array to a normal array

### ISSUE THREAD

**Issue by lesteve** [numpy/numpy#6475]
This is a new behaviour in numpy 1.10 and according to the doc np.allclose is supposed to return a bool. Is it an intended change?

Note that the returned object still has the right truthiness value so it should not be a problem except in conditions like `if np.allclose(...) is True:`. In our case a doctest fails but we could work around the failure if needed.

A snippet reproducing the behaviour:
```python
import tempfile
import os

import numpy as np

dtype = 'f8'
shape = (3, 4)
array = np.ones(shape, dtype=dtype)

temp_folder = tempfile.mkdtemp()
filename = os.path.join(temp_folder, 'test.mmap')

memmap = np.memmap(filename, mode='w+', shape=shape, dtype=dtype)

memmap[:] = array[:]

print('all close: {!r}'.format(np.allclose(array, memmap)))
```

Output with numpy 1.10.1:
```
all close: memmap(True, dtype=bool)
```

Output with numpy 1.9.3:
```
all close: True
```

**Comment by lesteve** [comment]
After bisection the first bad commit is at 2ae0529.

**Comment by charris** [comment]
The source of the problem is
```
    x = array(a, copy=False, subok=True, ndmin=1)
    y = array(b, copy=False, subok=True, ndmin=1)
```
The `subok=True` allows `memmap` to pass through, whereas in the original `alltrue` a copy was made. This is probably a good thing.

**Comment by charris** [comment]
So I think the question is whether or not to convert the result from memmap. An easy way to do that is to use `np.array(result, copy=False)` and I'm tending that way, but not yet convinced we want to do that. @lesteve Is the current behavior causing problems for you?

**Comment by njsmith** [comment]
For the case of allclose specifically there's an argument for just calling
bool on the result.
.
Part of the problem here is the usual issue where we have no consistent
semantics for array subclasses. Returning a memmap object makes no sense,
but that's a more general bug: lots of operations on memmap objects return
memmap objects that shouldn't. (E.g. all ufuncs.) For other subclasses who
knows. Certainly there's an argument that isclose on np.ma objects should
return a np.ma object, and that allclose should match np.all(isclose).

**Comment by charris** [comment]
#6628 forces bool return.

**Comment by lesteve** [comment]
> #6628 forces bool return.

Great thanks a lot!
