### ISSUE TITLE
Augmented assignment and type conversion

### ISSUE THREAD

**Issue by CarloGraziani** [numpy/numpy#6477]
Hello.  Here's a bit from an iPython session:
-------------------------------------------------
In [1]: import numpy as np
In [2]: x = np.arange(10)
In [3]: x
Out[3]: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
In [4]: x = x / 2.0
In [5]: x
Out[5]: array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])
In [6]: x = np.arange(10)
In [7]: x /= 2.0
In [8]: x
Out[8]: array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

So, oddly, the in-place assignment does integer division, while the copying assignment does float division.  I observe analogous behavior for the other arithmetic ops.  Is this expected behavior?

**Comment by argriffing** [comment]
I think the second one gives a TypeError in the numpy development branch, because it knows you are asking for float division but an in-place operation can't change the dtype. If you are using a recent numpy version then IPython might be eating a warning?

**Comment by njsmith** [comment]
Yes, what version of numpy and ipython? I believe the latest version of numpy (1.10, released last week) actually flipped the switch to make the second one an error, and if you have a recent-but-not-quite-that-up-to-date numpy it should be issuing a warning, and an up-to-date ipython should be displaying that warning.

**Comment by CarloGraziani** [comment]
Hm. OK, numpy 1.8.2 (from the np.__version__ string), and Python 2.7.5.  I tried it in the straight python shell, and got the same behavior, with no warning.

I see from the repository that numpy is at 1.10, so I can tell the answer is "update numpy" (and, in any event, "don't do it that way").  Thanks for the pointer about in-place ops restrictions.  It's obvious when you think about it, but thinking about it isn't obvious...

**Comment by njsmith** [comment]
1.8 should be issuing a warning; the problem is that python likes to hide these warnings by default :-/. (There are good reasons for this in general -- you don't want to annoy random end users about some deprecated code deep inside some program they happen to be using -- but they don't make much sense at the interactive shell.) *I*Python has fixed this in recent versions, and the regular python shell will probably fix it in the next release (3.6). You might want to upgrade ipython while you're at it.
