### ISSUE TITLE
Add a build step at the end of .travis.yml that uploads working wheels to a known location

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#6493]
There are projects that want to run their tests against the latest numpy master, and it would be a lot easier for them if there was a wheel they could just download. Some of them do `pip install git+http://...path/to/numpy/master`, but this has two disadvantages: (a) everyone has to rebuild from scratch all the time, (b) sometimes (hopefully rarely, but...) master is broken and this just doesn't work.

The solution is that we should have an `after_success:` block in .travis.yml so that after each commit has passed its tests, we upload the corresponding wheel somewhere, probably one of these rackspace accounts that everyone seems to have access to.

(Ideally we would only do this if *all* tests pass, but unfortunately this is impossible with travis currently: https://github.com/travis-ci/travis-ci/issues/929 . In the mean time, uploading each build variant iff its tests pass seems like a reasonable compromise.)

@ogrisel volunteers to do this in a few weeks, so if it's, say, mid-November and it hasn't happened, then someone should nag him ;-)
(https://github.com/numpy/numpy/issues/6462#issuecomment-148167879)

**Comment by matthew-brett** [comment]
I believe the python-Pillow guys have been using travis-after-all to trigger builds for for the OSX wheels for some time:

https://github.com/alrra/travis-after-all
https://github.com/python-pillow/Pillow/blob/master/.travis.yml#L79

I'm not sure how reliable that is.

**Comment by ogrisel** [comment]
I use wheelhouse-uploader for scikit-learn (which I maintain myself): here is an example usage:

https://github.com/scikit-learn/scikit-learn/blob/master/appveyor.yml#L74

Here is the documentation (README.md):

https://github.com/ogrisel/wheelhouse-uploader

I don't have time to do the PR myself this (at PyCON FR right now and sprinting on sklearn next week) but can provide sporadic help if you want to give it a try.

BTW: we already have the following container for stable wheels for the scipy stack:

http://wheels.scipy.org/

we could setup a dedicated container for CI related wheels for the master branch of each project (under Linux assuming they are all built with the same version of Linux on travis) for instance:

http://travis-wheels.scipy.org/

Maybe we can reuse the same rackspace container as http://travis-wheels.scikit-image.org/ and just add a new DNS if the scikit-image people agree (ping @stefanv :). Otherwise I can create a new dedicated container for this workflow.

**Comment by mhvk** [comment]
Out of curiosity: how does one ensure this only runs when merging stuff in master? (rather than on every PR that is being tested.)

**Comment by ogrisel** [comment]
Good question, thanks for asking: for security reasons, it does not have the credentials to do the upload in the PR, only after the merge. This makes it skip the upload automatically in PRs but will do the upload once merge in master (or in a release branch), assuming the proper credentials have been configured as a secret variable on the main github repo.

**Comment by stefanv** [comment]
I'm happy to add whichever DNS you need.

**Comment by ogrisel** [comment]
@stefanv could you please add a CNAME entry for travis-dev-wheels.scipy.org pointing to?

66ce22ef0bf26a5e2cca-4ffdece11fd3f72855e4665bc61c7445.r49.cf2.rackcdn.com

**Comment by ogrisel** [comment]
@stefanv are you ok to add the DNS entry? It would be great to have a shorter URLs in `.travis.yml` files of those projects.

**Comment by stefanv** [comment]
I transferred the ownership of the DNS to you, if I recall correctly.

**Comment by ogrisel** [comment]
For scikit-learn.org yes, but here I would just need to have a new `CNAME` entry for travis-dev-wheels.scipy.org pointing to:

    66ce22ef0bf26a5e2cca-4ffdece11fd3f72855e4665bc61c7445.r49.cf2.rackcdn.com

Hence on the scipy.org domain.

**Comment by stefanv** [comment]
Ah, sorry, I didn't read properly.  Done.
​

**Comment by ogrisel** [comment]
Thanks!

**Comment by ogrisel** [comment]
As #6768 is now merged in master I think this issue can now be closed.

**Comment by rgommers** [comment]
Great, thanks Olivier!
