### ISSUE TITLE
[Suggestion] Comparison functions for float point numbers

### ISSUE THREAD

**Issue by cy18** [numpy/numpy#6510]
I think this would be useful and easy to implement.

    greater_close(a, b) = greater_equal(a, b) | isclose(a, b)
    less_close(a, b) = less_equal(a, b) | isclose(a, b)
    greater_no_close = greater(a, b) & ~isclose(a, b)
    less_no_close = less(a, b) & ~isclose(a, b)
    
The results are element-wise, just like the original functions.

I'm not sure if it is useful enough to be a part of numpy. If so, I will try to implement them and make a pull request.

**Comment by njsmith** [comment]
This kind of new functionality requires discussion on the mailing list (numpy-discussion), because that brings in a larger crowd with more diverse perspectives to give feedback -- we try to use open bugs more to keep track of day-to-day maintenance tasks. So I'd suggest bringing this up there? And I'll close this for now -- we can re-open it if there turns out to be a consensus that we want to add these, and in the mean time there isn't any immediate action to take.

(Personally I'd be dubious about adding such functions to numpy, just because approximate comparisons like these are always dangerous and tricky and have very few valid use cases. But this discussion can happen on the mailing list :-).)
