### ISSUE TITLE
split produces empty arrays with wrong number of dimensions

### ISSUE THREAD

**Issue by mattjj** [numpy/numpy#6575]
This line works on numpy 1.9.3 but errors on 1.10.1 (current conda version):

```python
np.concatenate(np.vsplit(np.zeros((2,2)), [1, 1]))
```

It's because the split call has an empty array with the wrong shape, as indicated in the FutureWarning that prints:

```python
In [1]: np.vsplit(np.zeros((2,2)), [1, 1])
/Users/mattjj/miniconda/lib/python2.7/site-packages/numpy/lib/shape_base.py:431: FutureWarning: in the future np.array_split will retain the shape of arrays with a zero size, instead of replacing them by `array([])`, which always has a shape of (0,).
  FutureWarning)
Out[1]: [array([[ 0.,  0.]]), array([], dtype=float64), array([[ 0.,  0.]])]
```

However, it looks like in 1.9.3 this wasn't the case:

```python
In [1]: np.vsplit(np.zeros((2,2)), [1, 1])
Out[1]:
[array([[ 0.,  0.]]),
 array([], shape=(0, 2), dtype=float64),
 array([[ 0.,  0.]])]
```

This seems like a regression. Is this intended behavior?

(I'm on OS X using conda and Python 2.7.10, and switching between versions with `conda install numpy` and `conda install numpy=1.9.3`.)

**Comment by charris** [comment]
Looks like 1.9.3 and master may have gotten out of sync.

**Comment by charris** [comment]
The only thing new is #5771 which changed the condition for raising the warning and implementing the behavior seen in 1.10. The warning was first issued in 1.9, and it looks like 1.8, which  had no warning, behaves as 1.10 does now. Hmm, So it looks like 1.9 got ahead of the game due to what might be a bug ;)

**Comment by njsmith** [comment]
I guess if 1.9 jumped the gun and no one noticed then we might as well go
for it in 1.10 too :-). What I'd be worried about is if there are a mix of
cases where it used to work and cases where it used to not work, and 1.10
accidentally normalized them all to not working + issuing a warning. If
that happened then we don't want to switch to making them all with a
abruptly, just the ones that used to work should keep working.

**Comment by charris** [comment]
@njsmith I'm tempted to just move to the future behavior for everything. Will want to test it against pandas, etc., first. Agree that backing up from 1.9 would be awkward, so the other option is to simply back out the bug fix, #6371, which went in just a month ago. I think @seberg is traveling, so no opinion there.

**Comment by charris** [comment]
@MichaelCurrie Was there a particular reason that motivated your patch? Will things break if the future comes earlier than expected?

**Comment by njsmith** [comment]
Thanks for tracking that down! Now that I look at #6371, my vote is that for 1.10.2 we just revert that PR, i.e., put things back to the 1.9 behavior. (So that 1.10.2 has the future behavior for the cases that already had the future behavior in 1.9, but continues to have the old behavior for the cases that warned and had the old behavior in 1.9.)

Rationale: It's a FutureWarning, and `git tag --contains c91b4c370` says that the warning was only added in 1.9, so switching to the future behavior in 1.10 is a *very* short deprecation cycle. And then on top of that, switching in a point release seems *really* risky -- best case no-one cares, worst case we have to do 1.10.3 next week, and right now I think our focus should just be on putting out fires so everyone can switch to 1.10.

**Comment by charris** [comment]
I'm thinking, rollback to 1.9 for 1.10, go into the future for 1.11.

**Comment by njsmith** [comment]
Agreed on 1.10, and I don't really have an opinion on whether to switch in
1.11 or to wait, except that it would be nice to have a policy so we could
spend less time guessing :-)

**Comment by charris** [comment]
Hard to have a policy for an oddity like this. What we will have after a rollback is a function whose behavior depends on where the empty array occurs. That is embarrassing and if we cannot go back, we have to go forward. I'm still not convinced that should not happen in 1.10.2. @rgommers Do you have an opinion to offer?

**Comment by WarrenWeckesser** [comment]
Sorry for not keeping up with exactly which behavior it is that "jumped that gun" or which behavior is restored by "rolling back", but I hope that in the long run, all the arrays created by a  `split` function have the same number of dimensions, with empty arrays have a 0 in the `axis` slot but otherwise the same lengths as all the other arrays.

For example, the following behavior in `1.10.1` is unexpected (and incorrect, I think):

```
In [25]: x = np.zeros((3, 4, 5))

In [26]: x0, x1, x2 = split(x, [1, 1], axis=-1)

In [27]: x0.shape
Out[27]: (3, 4, 1)

In [28]: x1.shape  # Should be (3, 4, 0)
Out[28]: (0,)

In [29]: x2.shape
Out[29]: (3, 4, 4)
```

and

```
In [30]: x0, x1, x2 = split(x, [0,0], axis=1)

In [31]: x0.shape  # Should be (3, 0, 5)
Out[31]: (0,)

In [32]: x1.shape  # Should be (3, 0, 5)
Out[32]: (0,)

In [33]: x2.shape
Out[33]: (3, 4, 5)
```

**Comment by WarrenWeckesser** [comment]
Sorry for the noise--now I see that that is exactly what the `FutureWarning` says will happen.

**Comment by charris** [comment]
The more I think about it, the more the original looks more like a bug fix than something that needed a `FutureWarning`.

**Comment by seberg** [comment]
Did not read all, but if it was already right in those cases, we should probably have fixed it in 1.10...
That may be a bit late now though, it used to be an 'bug fix but lets be on the safe side' ( for the original warning).

**Comment by charris** [comment]
I made #6592 to remove the `FutureWarning` and preserve the dimensions of empty arrays in the result in all cases.

**Comment by charris** [comment]
Fixed by #6592 by moving to future in 1.11. The change in behavior was reverted in 1.10 by #6578.

**Comment by mattjj** [comment]
Thanks, that was really fast and thorough!

**Comment by MichaelCurrie** [comment]
@charris sorry I didn't get back to you immediately; it seems this issue is resolved now and my patch is moot.  Thanks for taking care of it.
