### ISSUE TITLE
Some functions in numeric.py call python all on ndarrays.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#6629]
That is not efficient. Unfortunately, the places where all is used can mix arrays and scalars, so the array method is not appropriate. However, np.all could be imported from numpy or fromnumeric.

**Comment by r0fls** [comment]
I peeked at this and saw only two instances: `allclose` (at line 2294) and `isclose` (line 2359).  Are there any other places in mind? All other uses of `all` in numeric appear to already be using the numpy array method.

Also, I tried importing `all` from fromnumeric and got an error -- presumably because of its use of `anyarray`, defined in numeric. I was able to copy that definition of `all` into numeric.py and pass the nosetests. Is there a different way, so that it's not in both places?

Last, is there a way I can benchmark this to see if it's actually improved, before making a pull request?

**Comment by yashmehrotra** [comment]
@charris Hi, I would like to work on this. in `numpy/core/numeric.py`, I found 3 instances of `all()`. So apart from directly replacing them with `np.all`, is there any thing else too ?

**Comment by yashmehrotra** [comment]
@charris Any updates on this one?

**Comment by njsmith** [comment]
@yashmehrotra: Sorry we missed your comment. Generally if there's a bug and no-one has actually said "I'm doing this", then everyone will be overjoyed if you just get to work -- no permission needed :-)

**Comment by yashmehrotra** [comment]
@njsmith Thanks

**Comment by yashmehrotra** [comment]
@charris @njsmith I checked the `numeric.py` file and it is already using the `np.all` function instead of python's built-in `all`. There is a `from .fromnumeric import *` call at the end of `numeric.py`. I confirmed this by printing the function details when it is called and it is already using the `np.all()`.

So, IMO, this issue is already resolved.

**Comment by charris** [comment]
OK, thanks for checking @yashmehrotra .
