### ISSUE TITLE
memory leak in nested dtypes in numpy.recarray

### ISSUE THREAD

**Issue by mherkazandjian** [numpy/numpy#6636]
The following code snippet causes the peak memory to increase indefinitly. I managed to trace
it down to the dtype used in the recarray. Basically for a nested dtype such as [('a', [('b', 'i')])] 
there is a memory leak.

```
import numpy
import resource

dtype = [('a', [('b', 'i')])]  # using this dtype causes a memory leak
# dtype = [('a', 'i')]           # using this dtype does not cause a memory leak

def alloc_and_init():
    x = numpy.recarray((), dtype)
    x.a.b = 1                  # set value (case of dtype with leak)
    # x.a = 1                    # set value (case of dtype with no leak)
    return x

x = alloc_and_init()
before = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
before0 = before

print '%-04s %10s %10s %10s' % ('i', 'mem peak', 'mem diff', '    mem diff since init')

for i in xrange(100000):

    x = alloc_and_init()

    after = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    delta = after - before

    delta_MB = delta / 2.0**20
    after_MB = after / 2.0**20
    delta_all_MB = (after - before0) / 2.0**20
    print '%-04d %-10.3f %-10e %-10e' % (i, after_MB, delta_MB, delta_all_MB)
    before = after

print 'done'
```

**Comment by ahaldane** [comment]
Thanks for the report.

It looks like this particular case has been fixed in 10.2 by #6500, by changing the line in record.py

    return obj.view(dtype=(self.dtype.type, obj.dtype.fields))         # old
    return obj.view(dtype=(self.dtype.type, obj.dtype))                # new

However, I think there is still a bug to fix. For example, the following setup causes the leak:

    d = numpy.dtype([('a', 'i')] )

    def alloc_and_init():
        numpy.dtype(d.fields)

which seems to be related to a behavior change between 1.9.3 and master. In 1.9.3 we get

    >>> d = np.dtype([('a', 'i')])
    >>> np.dtype(d.fields)
    TypeError: data type not understood

 but in master there is no error. I'll continue investigating later.

**Comment by mherkazandjian** [comment]
cool. tnx for the update. i'll investigate also.

Are there unit tests that check for these things ?

**Comment by ahaldane** [comment]
Ah I figured it out. In #5920 calls to `PyDict_GetItemString` were replaced with calls to `PyMapping_GetItemString` in order to allow the behavior change I mentioned at the end of my last comment. 

However `PyDict_GetItemString` returns a borrowed referece while `PyMapping_GetItemString` returns a new referece, so we need to add some decrefs in there.
