### ISSUE TITLE
Subsetting recarray by fields yields a structured array

### ISSUE THREAD

**Issue by aldanor** [numpy/numpy#6641]
I would expect this to return a record array as well:

```python
>>> np.rec.array([1, 2])
rec.array((1, 2), 
      dtype=[('f0', '<i8'), ('f1', '<i8')])

>>> np.rec.array([1, 2])[['f0', 'f1']]
array((1, 2), 
      dtype=[('f0', '<i8'), ('f1', '<i8')])
```

**Comment by ahaldane** [comment]
Hmm, I agree!

I've recently been updating recarrays to do this kind of thing properly, but I didn't think of this case in `__getitem__`. It looks like I correctly propagated the 'np.record' dtype in this case, but forgot to propagate the 'np.recarray' container. I get:

    >>> np.rec.array([1, 2])[['f0', 'f1']]
    array((1, 2), 
      dtype=(numpy.record, [('f0', '<i8'), ('f1', '<i8')]))

(the fact that you do not see the np.record dtype is probably because you are not using the absolute latest version of numpy, I would guess)

I'll look into a fix/enhancement.
