### ISSUE TITLE
optimized blas detection broken in master and 1.10

### ISSUE THREAD

**Issue by juliantaylor** [numpy/numpy#6675]
merge of gh-6183 broke cblas detection on linux distros:

```
np.show_config().
...
blas_opt_info:
    libraries = ['blas']
    library_dirs = ['/usr/lib']
    language = f77
```

cblas is required for numpy to use it in `dot`

**Comment by charris** [comment]
Works for me
```
blas_opt_info:
    libraries = ['tatlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
    language = c
    include_dirs = ['/usr/include']
```
I think you need to be more specific about what is broken.

**Comment by juliantaylor** [comment]
you have atlas installed directly, not a generic blas like typically on debian based systems
direct atlas detection is special cased in numpy

**Comment by charris** [comment]
Is it fixable using `site.cfg`?

**Comment by juliantaylor** [comment]
to my knowledge no

**Comment by charris** [comment]
How about something like `cc -lcblas` ? That should work for gcc, and maybe MKL and LLVM as well.

**Comment by charris** [comment]
Or, shelling out, `ldconfig -p | grep <whatever>`.

**Comment by juliantaylor** [comment]
I still don't know what the issue with the original code was

**Comment by charris** [comment]
See #6175.

**Comment by juliantaylor** [comment]
would be simplest to just skip the check on windows then, its apparently not needed there anyway

**Comment by boegel** [comment]
Related to this: what is a good way to check whether numpy was built/linked against BLAS?

Before numpy version 1.10, I was using this as a sanity check:

```
python -c "import numpy.core._dotblas"
```

That worked fine, but doesn't work anymore with numpy v1.10 since `_dotblas.so` was removed.

I'm now looking into a proper replacement for this.
It seemed like this may serve as a good sanity check:

```
nm <prefix>/numpy/core/multiarray.so | grep blas_dot
```

but it seems like this is not a universal check, i.e. it only seems to work when linking numpy against Intel MKL.
When linking numpy v1.10.1 against OpenBLAS, this check fails, but I do get good performance  (a matrix-matrix multiplication of a random 1000x1000 matrix is fast) and the compilation looks fine (numpy is being built with `-DHAVE_CBLAS` and linked with `-lopenblas`, etc.).

Is there a better generic way of checking whether numpy was built with proper BLAS support, that regardless of with which BLAS numpy was linked?

**Comment by charris** [comment]
Hmm, there really isn't a "good" way. You can do
```
In [7]: np.__config__.blas_opt_info['define_macros']
Out[7]: [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
```
and search the output, but that isn't easy. One thing the might be good in the future would be to have a dictionary with all the defined macros (there are many others) as keys, but that will take some work. A workaround might be
```
In [10]: 'HAVE_CBLAS' in dict(np.__config__.blas_opt_info['define_macros'])
Out[10]: True
```

**Comment by boegel** [comment]
@charris: that looks like a reasonable suggestion, thanks!

**Comment by boegel** [comment]
@charris: seems to work, but only with numpy 1.10, not with 1.9.x (even though it *is* linked against a proper BLAS, and is fast)? Does that make sense? Is that related to the `_dotblas.so` change?

```
$ python -c "import sys; import numpy; print numpy.version.version; print numpy.__config__.blas_opt_info['define_macros']"
1.9.2
[('SCIPY_MKL_H', None)]
```

```
$ python -c "import sys; import numpy; print numpy.version.version; print numpy.__config__.blas_opt_info['define_macros']"
1.10.1
[('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
```

**Comment by boegel** [comment]
Hmm, seems like I'm wrong w.r.t. the `blas_dot` symbol when linking against `OpenBLAS`... In some circumstances the `blas_dot` symbol *is* there.
Seems like it's related to either using `-fPIC` or aggressiveness of optimization (symbol is not there with `-O3` and GCC, but is there with `-O2`)?

**Comment by charris** [comment]
Ah, yes. `HAVE_CBLAS` is new in 1.10, you need to use your former version for earlier numpy.

**Comment by boegel** [comment]
OK, good, I can live with that. Thanks for the suggestion @charris!
