### ISSUE TITLE
ifft RAM requirements

### ISSUE THREAD

**Issue by Leberwurscht** [numpy/numpy#6693]
Hi,

I was trying to reduce the RAM requirementes of my program and noticed that the numpy.fft.ifft function needs a lot more RAM for the computation than numpy.fft.fft. I don't understand why, as the formulas for fft and ifft are nearly the same...
My numpy version is 1.8.2.

```python
  import numpy as np
  datain = np.ones((1000,1000,100), dtype=np.complex) # 1.6 GB allocated
  x=np.fft.fft(datain); del x # running this line takes up 3 GB of RAM
  x=np.fft.ifft(datain); del x # running this line takes up 6 GB of RAM
```

I look at the RAM consumption by executing `top -d.05 | grep ipython` in a second terminal window.

**Comment by seberg** [comment]
The division/scaling factor needed for ifft is not done in an in-place manner, so a second array the same size as the result is necessary. Note that you cannot compare the memory in a single run easily, since python will not free memory immediately in all cases.
Another performance bug is the `astype` cast, which as far as I can see in all cases will create an unnecessary copy.

**Comment by charris** [comment]
@seberg `a.astype(..., copy=False)` should fix the copy problem.
