### ISSUE TITLE
Testing Single-element NumPy Array Against Empty Python List

### ISSUE THREAD

**Issue by cgshep** [numpy/numpy#6722]
When I test a single-element NumPy array against a regular Python list, `np.array([1]) != []`, the result evaluates to neither true nor false, while one of multiple elements evaluates to true.  E.g. 'boo' is printed with the following:

``` python
a = np.array([1])
b = np.array([1,2])

if a != []:
    print("foo")

if a == []:
    print("moo")

if b != []:
    print("boo")
```

Using the interpreter:

```
>>> import numpy as np
>>> a = np.array([1])
>>> b = np.array([1,2])
>>> a != []
array([], dtype=bool)
>>> a == []
array([], dtype=bool)
>>> b == []
False
```

This seems strange.  Was this intended?

Tested with Python 2.7.10 and 3.4.2, using Numpy 1.10.1.
Linux 4.2.6-200.fc22.x86_64 (Fedora 22)

**Comment by seberg** [comment]
Yes, this is intended, it is normal broadcasting rules. The list is interpreted as an array. The single element can be broadcast. Note this:
```
In [1]: a = np.array([1])

In [2]: a + []
Out[2]: array([], dtype=float64)

In [3]: a == []
Out[3]: array([], dtype=bool)

In [4]: bool(np.array([]))
Out[4]: False

In [5]: a != []
Out[5]: array([], dtype=bool)
```
The first add shows broadcasting rules (1 can be broadcast, and broadcasting *can* result in 0 size!). Normally arrays will complain with logical operators, since they have many elements and this is not possible. But `bool(np.array([]))` works to be more like lists I guess, and the first part always gives such an empty array.
The only "fix" I can think of right away would be to also throw an error in this case, since it is probably useless anyway.

The general point I guess is: do not ask an array for its truthness, it is not very well defined. And since the operators return boolean arrays, you cannot use it for an if clause easily.

**Comment by mhvk** [comment]
Yikes, first time that broadcasting doesn't seem to make sense, although reading the broadcasting rules [1] carefully, I do see it is consistent.  Still, really, would one have expected this to work?
```
In [91]: np.ones((1000,1,0,1,1,1,1)) + []
Out[91]: array([], shape=(1000, 1, 0, 1, 1, 1, 0), dtype=float64)
```

Anyway, agree that for arrays, one should really avoid implicit assumptions about them being boolean. Comparison operators returning arrays is the best solution in most cases, but this means one often has to do `np.all` or `np.any` in if-statements.

[1] http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

**Comment by seberg** [comment]
I have argued long times why it can be very useful that 0 is also just N (poor zero being considered not N :p). So yes, *I* would expect it to work ;). The weird thing may be that the bool conversion works for arrays in some cases, when it usually (for good reasons) does not work.
On the other hand, it is true that by python logic and empty container is `False` so it is not incorrect, just a bit tricky and I doubt we should change it, but I would not rule it out in principle.

**Comment by njsmith** [comment]
Yeah, the part that I find surprising and objectionable is that
bool(array([])) returns False instead of raising an error. It's no good
saying that this follows the general python logic for containers, because
the general python logic for containers says that empty containers are
falsey *and non-empty containers are truthy*. Implementing only half of
this logic is utterly useless -- what can a user do with this behavior?
With lists you can write 'if list: ...' to dispatch on empty versus not
empty, but not arrays. I'd be +1 to deprecating this and making it an error
later, so that bool(arr) consistently raises an error whenever arr.size !=
1.
