### ISSUE TITLE
nan in float64 does not evaluate to nan

### ISSUE THREAD

**Issue by nheeren** [numpy/numpy#6746]
Hello 

It is very likely that this is a nooby misunderstanding from my part. But shouldn't
`np.float64(np.nan) is np.nan`
evaluate as `True`(on Python3)?
These two do at least:
`np.isnan(np.float64(np.nan))`
and
`np.float(np.nan) is np.nan`
Thanks, Niko

**Comment by seberg** [comment]
Hello, just a small misunderstanding....

No, it definetely should not. The returned NaN is a numpy type, not a python type. Also NaN is **not** a singleton in the first place, so two NaNs are not generally the same in any case. `np.float` is actually just python's `float`, so it does nothing, but even then `float('nan') is not float('nan')` (your version only worked because it happens to be a no-op doing nothing at all).

There are many NaN's (even on the hardware level). `is` is **not** really a useful operator for numbers, and that is also true for NaN.

**Comment by nheeren** [comment]
Great -- thank you for your help understanding this!
