### ISSUE TITLE
polyval syntaxes don't match

### ISSUE THREAD

**Issue by jradavenport** [numpy/numpy#6749]
`numpy.polyval(coeffs, x)`

versus

`numpy.polynomial.polynomial.polyval(x, coeffs)`

Is there any reason these don't match? Given that these have both been around for a while, is there any sensible way to unify these?

**Comment by charris** [comment]
Not really ;) The choice was deliberate to make `polyval` look more like a function of `x`. Note that the coefficients are ordered differently also. The original thought was to deprecate `numpy.polyval` at some point, but it is so commonly used that we will probably never get around to it.

**Comment by nennigb** [comment]
There is also another error prone difference since : 
  - `numpy.polyval` used _descending_ power ordering for the coefficients, ie, `x**(n) a[0] + ... a[n]`, [doc](https://numpy.org/doc/stable/reference/generated/numpy.polyval.html)
  - `numpy.polynomial.polynomial.polyval` used _ascending_ power ordering, ie, `a[0] + ... + x**n a[n]`, [doc](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.polyval.html)
for a polynomial of degree `n`.

I suggest to add a warning somewhere in both function (or at least in `numpy.polynomial.polynomial.polyval`)  documentation. Initially, I was thinking that `numpy.polyval` was just an alias of the same function... 
We could add in the note section:
> This function is different from  `numpy.polyval` and used a reversed convention for coefficient ordering.

**Comment by eric-wieser** [comment]
@nennigb, this is true of every single function of the forms `np.poly*` and `np.polynomial.polynomial.poly*`. Everything in the `np.polynomial` namespace uses `a[0]` as the scalar coefficient.
