### ISSUE TITLE
Numpy.rec.fromarrays losing dtype metadata between versions 1.9.2 and 1.10.1

### ISSUE THREAD

**Issue by bmoscon** [numpy/numpy#6771]
in 1.9.2 if I run the following:

(assume dtype has metadata associated with it)

rtn = np.rec.fromarrays(arrays, dtype=dtype, names=names)
#For some reason the dtype metadata is lost in the line above.
rtn.dtype = dtype

the metadata is preserved (even those fromarrays lost it, at least I can re-set it).

In the latest version of numpy setting rtn.dtype to a dtype with metadata no longer works. The metadata is lost. Not sure if this is a bug or an intentional change.

**Comment by njsmith** [comment]
What do you mean by "dtype metadata"?

**Comment by bmoscon** [comment]
I believe this commit changed the functionality:

https://github.com/numpy/numpy/commit/a93b86217e9ff8cc1060aaf362cd682b518cfb7b

in __array_finalize__ it resets the dtype.

**Comment by bmoscon** [comment]
this is what i mean by "dtype metadata":

http://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.metadata.html#numpy.dtype.metadata

**Comment by njsmith** [comment]
Ah, I was afraid of that :-). The .metadata field is sort of only
accidentally there in the first place and has never been used for anything.
It should probably be removed entirely... In the mean time it's hard to say
whether any particular handling of it is a "bug" since there's no theory of
what "correct operation" looks like...
.
What are you using it for? I believe you are the first user we've ever
found who was doing anything with it.

**Comment by ahaldane** [comment]
For reference, we also discussed metadata in #5973

**Comment by bmoscon** [comment]
Yeah thats fine, I just wanted to know if this was a bug, or was the result of a bug being fixed. Let me know what you decide!

**Comment by njsmith** [comment]
To be honest, the most likely outcome right now is that the bug gets
ignored and sinks into obscurity... None of us use this feature, and none
of us know what it is used for or why it should exist in the first place,
so we're not too motivated to spend time on it on the first place, and even
if we were then it's impossible to actually make a productive decision
without any use cases in mind.
.
The reason I asked what you're doing with .metadata is because if no one
answers this question then probably the only thing that will happen to
.metadata is that it'll eventually get removed...

**Comment by bmoscon** [comment]
@njsmith we're serializing down pandas dataframes and numpy arrays for compression and then storage into mongoDB. We store some data in the metadata as we do this to carry along with us for later use.

**Comment by anntzer** [comment]
fwiw h5py uses metadata to represent HDF5 VLEN dtypes, see http://docs.h5py.org/en/latest/special.html and https://github.com/h5py/h5py/blob/12054612432069874f3b73098838b16552045098/h5py/h5t.pyx#L1562
pinging @andrewcollette

**Comment by andrewcollette** [comment]
@anntzer, thanks for the heads-up.  We do use this attribute in h5py, as a way to "hint" what type of object is stored in a NumPy "O" dtype object array.  This is central to how h5py represents certain HDF5 types with no direct NumPy equivalent.

For years we used to squirrel away this information in the "title" of the dtype's fields, but that led to problems.  Ironically, as part of the pull request which added general-purpose VLEN support in h5py, we switched from that approach to the metadata attribute, under the assumption it was better supported.  That PR is here:

https://github.com/h5py/h5py/pull/355

From our perspective the best thing would be for NumPy to preserve the contents of the metadata dict wherever possible, but otherwise ignore it.

**Comment by charris** [comment]
Looks like this needs a fix. @ahaldane How much work is that?

**Comment by mhvk** [comment]
The line in `__array_finalize__` where [the dtype is set] (https://github.com/numpy/numpy/commit/a93b86217e9ff8cc1060aaf362cd682b518cfb7b#diff-5f49d7d945b415e2e0d309f558a6f539R430) seems correct in itself. Rather, it seems odd that if one sets the dtype the metadata gets lost. (That said, in another issue that I cannot immediately find, I think it was being discussed that setting the dtype directly should be deprecated....)

**Comment by ahaldane** [comment]
I see how to fix it, in `_use_inherit`. I think it's easy, I'll do it in a little while.
