### ISSUE TITLE
dtype keyword for np.random.randint and np.random.rand

### ISSUE THREAD

**Issue by sebix** [numpy/numpy#6790]
As brought up at the mailinglist, this code ates up much memory:

```
spectrumArray = np.random.randint(0,255, (2**20,2**12)).astype(np.uint8)
```

> It has also crossed my mind that np.random.randint and np.random.rand could use an extra 'dtype' keyword. It didn't look easy to implement though. 

See this thread on the mailinglist: [[Numpy-discussion] array of random numbers fails to construct](https://mail.scipy.org/pipermail/numpy-discussion/2015-December/074306.html)

**Comment by njsmith** [comment]
This came up on the mailing list as a feature request from someone who
wanted to generate many gigabytes of random uint8s, so couldn't afford the
memory overhead of generating uint64s and then calling astype.

**Comment by gfyoung** [comment]
How is the ```dtype``` parameter processed into C data types (e.g. ```long``` or ```long long```) when creating an ```array``` or ```matrix``` object?  I have been knee-deep in ```randint``` code, and as a first thought, is there anything wrong with initializing ```rv``` and ```array``` depending on the requested ```dtype```?

**Comment by jaimefrio** [comment]
Take a look [here](http://docs.scipy.org/doc/numpy-1.10.0/reference/c-api.dtype.html). When numpy C code wants to cover all the possible integer types, it typically has versions for:

 * `npy_byte`
 * `npy_short`
 * `npy_int`
 * `npy_long`
 * `npy_longlong`

plus their unsigned counterparts.

The simplest solution would be to leave the generation of the random numbers alone, i.e. make no changes to `rk_interval`, and simply cast the result to the requested type, one item at a time, rather than the whole array at once. This will not be optimal in some senses, but it will keep a lot of behavior consistent with the current one, which may not be a strict requirement, but is certainly not a bad thing.

I'm guessing the Cython way of doing this would be to move the loop copying the random numbers into the output array [here](https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/mtrand.pyx#L966), into a separate function defined with [fused types](http://docs.cython.org/src/userguide/fusedtypes.html). If this doesn't make sense, ask and I'll try to explain...

**Comment by gfyoung** [comment]
Fused types, interesting...I've never used them before, but the DOC seems to cautioning us against using them for the time being.  Thus, it seems best to go the less Cythonic route for now.  At least the functionality would be in place, and if necessary, another PR could be put up to refactor the code once fused types are more stable.

**Comment by jaimefrio** [comment]
Scipy uses fused types in several places. We are different projects, but close cousins to say the least: unless someone else makes a compelling argument against their use in NumPy, I think you can assume that it is safe to use them.

Unless you have a better alternative, I think it's either an if-elif monster with 10 branches, copying the bytes one at a time, or fused types. The first is ugly, the second will be slower, but perhaps not noticeably so, depending on how slow

**Comment by jaimefrio** [comment]
<hit send to soon, continuing>the actual random number generation is.

What do you have in mind.

**Comment by gfyoung** [comment]
Ah!  Okay, that's good to know.  I was initially going by the DOC, which warned against using them.  However, if ```scipy``` has been able to use them without harm, then they certainly merit more consideration as a possible implementation.

**Comment by gfyoung** [comment]
Also, it occurs to me that one might also want to expand ```numpy.random.RandState.tomaxint``` to account for ```dtype```.  However, that seems even more complicated to implement.  The PR I'm working on right will only account for ```randint``` and ```rand```.

**Comment by gfyoung** [comment]
Just curious, does anyone know of a significant use case for specifying ```dtype``` for ```rand```?  Otherwise, I think this issue is good to close as well.

**Comment by charris** [comment]
Someone might want floats instead of doubles, that would about double the speed.

**Comment by charris** [comment]
That's probably an easier project than randint. Might raise the topic on the list for discussion.

**Comment by gfyoung** [comment]
Sent out email <a href="http://thread.gmane.org/gmane.comp.python.numeric.general/62217">here</a>.  I'll try putting together a PR for this once I start getting feedback.

**Comment by gfyoung** [comment]
Goodness, it's been some time since I've taken a look at this.  While I got no feedback with my email, the consensus appears to be that there should be an initiative to change this.  Currently, I'm thinking that I would first add it to `standard_normal` and `random_sample` because the signatures are nicer to work with (not sure how I would "nicely" add it with `rand` and `randn` since they take `*args` for shape, which I'm not sure I fully understand.  Aliasing the two also seemed logical IMHO).

In any case, the default `dtype` appears to be `np.float64` for both functions.  It seems that following a similar infrastructure as was done with `randint` would be logical.  However, I'm not sure how to downcast to `np.float32` or `np.float16` in light of what I witnessed with the `randint` implementation.  Can you also extract two `np.float32` from an `np.float64` (doesn't seem like you can, but I just wanted to double check)?  Or are there separate algorithms?

**Comment by adler-j** [comment]
I am in need of this feature lately, and a very nice addition (while we're at it) would be to also add support for complex numbers, i.e.

```python
>>> np.random.rand(2, dtype=complex)
array([ 0.51123582+0.70529597j,  0.81638056+0.59491201j])
```

**Comment by bashtage** [comment]
> and a very nice addition (while we're at it) would be to also add support for complex numbers

For uniforms I think you can just 

```python
>>> np.random.rand(4).view(np.complex128)
array([ 0.70357853+0.28991696j,  0.61981945+0.74790194j])
```

**Comment by adler-j** [comment]
Sure, but that syntax is not very flexible and requires quite some intelligence from the user, for example:

```python
>>> np.random.rand(4, dtype=np.float32).view(np.complex64)
```

Having a uniform interface that works with any dtype would be the most convenient.

**Comment by bashtage** [comment]
I think the generic challenge is generating quality random numbers for different precision across many different distributions is not completely obvious.  Some are easy, like uniforms (get right number of random bits, multiple by 1/2**b for the right b -- there are other ways, but this is most common, and used by NumPy). Normals with Box-Mueller are also probably OK, although there will be little in terms of gains for speed since trig functions are slow.  

Any sort of general interface across all RNGs is going to add a lot of cruft that may have very little use.

**Comment by adler-j** [comment]
Certainly agree with the above, but having a general interface for the core method `numpy.random.rand` shouldnt be out of reach.

**Comment by se4u** [comment]
[I had exactly the same use case today.](https://github.com/numpy/numpy/issues/6790#issuecomment-168555702). So I'd be happy if this feature is added to the library. I made this [patch](https://gist.github.com/se4u/e44f631b249e0be03c21c6c898059176) to numpy based on the master today and it seems to work correctly:

``` python
>>> import mtrand
>>> print mtrand.standard_normal(size=(10,10), dtype="float32").dtype 
float32
```

This patch does not handle all datatypes but it may cover the 80% use case.

**Comment by bashtage** [comment]
@se4u 32-bit dtype support is available for some core distributions in https://github.com/bashtage/ng-numpy-randomstate .  It also supports alternative PRNG so it is possible to generate 32 bit normals about 3-4x faster than numpy can generate 64 bit normals.

Docs http://bashtage.github.io/ng-numpy-randomstate/doc/build/html/index.html

**Comment by se4u** [comment]
Wow, the `ng-numpy-randomstate` project is great. Thank you for creating
and sharing it.

**Comment by charris** [comment]
I don't think it would be difficult to extend the dtype keyword to `numpy.random.rand`. I would suggest it support float{64, 32, 16} and complex{64, 128}. I'm not sure what to do about extended/quad precision versions, might just ignore them for the time being.

**Comment by se4u** [comment]
@Charles : On the Cython side, the code can be generated using fused types
to avoid duplication, but I am not sure how to avoid code duplication in
`randomkit.c`. In my patch I just wrapped the call to the `rk_gaussian`
function which returns a double by a function `rk_gaussian_32bit` which
casts it to 32 bit, but it's wasteful to first generate `double` values and
then to convert them to a float.

As for `complex` dtypes, that can be handled completely in python by just
generating twice as many real values as the number of requested complex
values as then changing the view of the numpy array before returning to the
user.

**Comment by charris** [comment]
> but it's wasteful to first generate `double` values

Yep, and not acceptable, as we would be stuck with it forever. I don't think it difficult to deal with all the floating types except extended and quad.

**Comment by se4u** [comment]
The easiest/cleanest way to fix the c code may be to change `randomkit.c`
to c++ and then to just use templates to define the functions that we
require. Thought?

**Comment by charris** [comment]
Look at how it is done for integers. C++ is a no go.

**Comment by NumesSanguis** [comment]
Is someone still working on this feature? Since I'm dealing with audio and deep learning, I wanted to add white noise to a signal. For DL, float64 is overkill, so it would be nice if we could generate a uniform distribution as float32 from the start with:

    noise = np.random.uniform(low=-1.0, high=1.0, size=signal_len, dtype=np.float32)

**Comment by bashtage** [comment]
xref #13163 . This is fixed in the randomgen branch.

**Comment by mattip** [comment]
Closing, the new API supports dtype. Please reopen if needed.
