### ISSUE TITLE
why there is much difference between numpy.dot and BLAS's dgemv/dgemm?

### ISSUE THREAD

**Issue by citihome** [numpy/numpy#6887]
It seems numpy.dot is not equals to blas's gemv/gemm, here is the experiment:

```
>>> import numpy
>>> numpy.show_config()
lapack_opt_info:
    libraries = ['openblas']
    library_dirs = ['/usr/local/anaconda/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_opt_info:
    libraries = ['openblas']
    library_dirs = ['/usr/local/anaconda/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_info:
    libraries = ['openblas']
    library_dirs = ['/usr/local/anaconda/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_lapack_info:
    libraries = ['openblas']
    library_dirs = ['/usr/local/anaconda/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_mkl_info:
  NOT AVAILABLE
>>> A=numpy.random.randn(100,50)
>>> x=numpy.random.randn(50)
>>> from scipy import linalg
>>> gemv = linalg.get_blas_funcs("gemv")
>>> numpy.all(gemv(1,A,x)==numpy.dot(A,x))
False
>>> gemm = linalg.get_blas_funcs("gemm")
>>> numpy.all(gemm(1,A,x)==numpy.dot(A,x))
False
```

I don't know why, could any one show me how to construction a BLAS based function equals to numpy.dot

**Comment by charris** [comment]
The difference seems to be roundoff error. Numpy uses CBLAS, not BLAS, and it seems that there might be code/compiler differences between the two.

**Comment by citihome** [comment]
I also tried CBLAS using cython, the differences also exist. And what is the solution, how to fixed it?

**Comment by charris** [comment]
You also get errors of the same order by reversing the order of the elements.
```
In [28]: p1 = gemv(1.,A,x)

In [29]: p2 = gemv(1.,A[:,::-1], x[::-1])

In [30]: abs((p1 - p2)/p1).max()
Out[30]: 1.8220311846482082e-15
```
I think that the functions being executed are not quite the same, but that the differences are not large enough to indicate an error. It would be interesting to track down eactly which functions are being executed, but it doesn't look like a problem. Note that a straight sum differs from both.
```
In [31]: p3 = einsum("ij, j", A, x)

In [32]: abs((p1 - p3)/p1).max()
Out[32]: 4.7842309799524032e-15
```
Such differences can depend on the compiler, the code, the optimization settings, and the path through the resulting routine.

**Comment by citihome** [comment]
the code(https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/cblasfuncs.c) seems that it is depends on cblas cblas_gemv exactly. thus I don't know where the difference comes from

**Comment by jacobnzw** [comment]
In my algorithm, the differences (which are mostly small enough such that `allclose` checks out) in using `dot` and `einsum` for multiplication of 3 matrices are very decisive. When I use `dot`, my code does not encounter errors, but with `einsum` I get errors, even though I use it correctly. This is kind of unnerving as I was expecting same results to be returned. 

Is there anything that can be done to unify the results of `dot` and `einsum`? I wonder how, say, MATLAB is dealing with something like this.

**Comment by seberg** [comment]
@jacobnzw which version of numpy are you using, how decisive is very decisive and how complex is the einsum version?

**Comment by jacobnzw** [comment]
I'm using Numpy 1.11.3 from Anaconda (I guess it's the MKL version, I certainly have `mkl`, and `mkl-service` packages installed) on Windows 10.

Here is little example replicating the conditions in my algorithm to demonstrate the difference in `dot` and `einsum`.
```python
import numpy as np
from scipy.linalg import cho_factor, cho_solve

# create inverse of symmetric positive definite matrix
A = np.random.randn(5,5)
K = A.dot(A.T)
iK = cho_solve(cho_factor(K), np.eye(K.shape[0]))

# very badly conditioned symmetric PD matrix
Q = 1e8 + K

# max difference in dot and einsum
print(np.abs(iK.dot(Q).dot(iK) - np.einsum('ij,jk,kl', iK, Q, iK)).max())
```
I'm getting a difference of `2.1979212760925293e-07`, which is enough to cause my algorithm to crash with `LinAlgError` due to loss of positive definiteness. (That's the gist of it. I'd have to include the whole algorithm to get the details, but that's impractical because it's strewn across several files).

**Comment by seberg** [comment]
It is an older issue, and the reported difference seems not overly large compared to the typical numbers returned by this code (of around 1e10), I get a relative difference of at most 1e-13 I think, which compared to the numerical precision of 1e-15 or so, seems not that huge?

To answer the old questions: No, you cannot unify einsum and dot, since they use completely different code paths and optimizations (and with that operation order, etc.).
