### ISSUE TITLE
Function numpy.linalg.det returns incorrect value

### ISSUE THREAD

**Issue by nvgeele** [numpy/numpy#6890]
When running the following code snippet:

``` python
import numpy as np
m = [[253.0, 32581341.0, 16387064.0], 
     [253.0, 32581088.0, 16387064.0], 
     [253.0, 16322548.0, 16387064.0]]
print np.linalg.det(m)
```

You will get `7.66182433814` as output. This is incorrect as the determinant of this matrix is [supposed to be zero](http://wolfr.am/9gbUMxYD)

Operating system: OS X 10.11
Tested with both CPython 2.7.10 / Numpy 1.10.0.post2 and PyPy 4.0.1 / Numpy 1.10.0

**Comment by charris** [comment]
There numerical precision problems with almost singular matrices. Note that singular is not numerically well defined for floating point. In this circumstance such things as column/row scaling, etc, makes a difference. Because we use `*getrf` on the (Fortran ordered) matrices, perhaps we should scale the (C ordered) columns ourselves so as to get the best row pivoting behavior.  Anyway, for example
```
In [29]: mm = m/amax(m, axis=0, keepdims=True)

In [30]: mm
Out[30]: 
array([[ 1.        ,  1.        ,  1.        ],
       [ 1.        ,  0.99999223,  1.        ],
       [ 1.        ,  0.5009784 ,  1.        ]])

In [31]: det(mm)
Out[31]: 0.0
``` 

But. as I say, there are no guarantees for exactly singular. Note that one advantage of the scaled matrix is that `abs(det)` is <= the array dimension.

**Comment by LintangWisesa** [comment]
Round the value, it will give you the best answer
```
import numpy as np
a = np.array([[2,1,4],[4,2,1],[5,1,3]])
print(round(np.linalg.det(a)))
```

**Comment by mattip** [comment]
Closing, please reopen if the explanations of numerical instability are not clear.

**Comment by jatron** [comment]
Here's another example where numpy.linalg.det returns an incorrect value. The correct value is zero.
```
>>> import numpy as np
>>> m = [[ 2,   4,   40],
...      [ 4,  40,  208],
...      [40, 208, 1312]]
>>> print(np.linalg.det(m))
2.3646862246096143e-12
```

**Comment by melissawm** [comment]
Hi @jatron , this is expected, it is how [floating point arithmetic](https://en.wikipedia.org/wiki/Floating-point_arithmetic) works.

**Comment by mattip** [comment]
I locked this discussion. If you think you have new insights on this issue, please open a new one after carefully reading the discussion here and the linked information about why this happens.
