### ISSUE TITLE
BUG: MaskedArray Objects are Fortran- and C-Contiguous Simultaneously

### ISSUE THREAD

**Issue by gfyoung** [numpy/numpy#6911]
```
>>> from numpy.ma.core import MaskedArray
>>> from numpy import isfortran
>>> m = MaskedArray([1, 2, 3])
>>> m
masked_array(data = [1 2 3],
             mask = False,
       fill_value = 999999)
>>> m.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
>>> isfortran(m)
False
```

OS: Windows (win32)
Python: 2.7.11 (32-bit)
Numpy: v1.10.2

I think it may be related to #6646, but I'm not sure yet.

**Comment by njsmith** [comment]
That's because this array actually is both C and F contiguous :-). This is the "relaxed strides checking" change, which makes the contiguity flags simply determined by the array's memory layout and nothing else.

(And IIRC isfortran has some really confusing semantics/confusing name where it actually tests F-but-not-C contiguity.)

**Comment by njsmith** [comment]
Anyway, closing because I think that's all there is here, but definitely reopen if I'm missing something.

**Comment by gfyoung** [comment]
Ah, okay, good to know.  Thanks!
