### ISSUE TITLE
astype converts numpy array values to 0.0 for structured dtype

### ISSUE THREAD

**Issue by mpconte** [numpy/numpy#7058]
import numpy as np

dtype = np.dtype([('Point', 'f', (3,))])
ones = np.ones(1, dtype=dtype) **--> array([([1.0, 1.0, 1.0],)], dtype=[('Point', '<f4', (3,))])**
flattened_dtype =  np.dtype([('x', 'f'), ('y', 'f'), ('z', 'f')])
flat_ones = ones.astype(flattened_dtype) **--> array([(0.0, 0.0, 0.0)], dtype=[('x', '<f4'), ('y', '<f4'), ('z', '<f4')])**

**numpy version 1.9.2**

**Comment by charris** [comment]
Also in 1.11.

**Comment by ahaldane** [comment]
I will check when I get home, but I suspect this is another version of the long-standing bug which could be fixed by #6053. Specifically, I think this is example 'v3' in the example there: When numpy does not find a matching field-name on the lhs, it simply assigns 0 to the rhs field.

**Comment by ahaldane** [comment]
I'd also add, @mpconte's example is in some sense the current desired behavior: Assignment between two structures array currently works by matching up field names between the lhs and rhs. If a field name on the rhs is not present in the lhs, that field gets assigned 0. This is not documented anywhere, but there are comments in the code suggesting it is intentional.

**Comment by charris** [comment]
That makes sense.

**Comment by mpconte** [comment]
Thanks for the insight.
I also just discovered that using **view** instead of **astype** acutally gives me the result I'd expect, regardless of field names, thanks.
