### ISSUE TITLE
Value Error Cannot Copy Sequence of XX to array axis with dim YY

### ISSUE THREAD

**Issue by meslami-netrias** [numpy/numpy#7103]
A list of dataframe objects cannot be converted to a numpy array due to a vstack issue with the conversion.  The list itself should be converted into a numpy array rather than forcing the conversion of each individual dataframe.  A work around is here but requires an extra read/write to memory which will not scale.

http://stackoverflow.com/questions/32948867/valueerror-cannot-copy-sequence-with-size-5-to-array-axis-with-dimension-2

**Comment by ahota** [comment]
I've just run into this bug with bitarray objects as well. I haven't quite yet found the pattern that causes it however, because it doesn't seem to be correlated to the object's shape the way I originally thought.

For example:
```
>>> import numpy
>>> from bitarray import bitarray
>>> 
>>> #same shape fails
>>> a = numpy.array([bitarray('10101') for i in range(3)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot copy sequence with size 5 to array axis with dimension 1
>>> 
>>> #same shape, length of 1, succeeds
>>> numpy.array([bitarray('1') for i in range(3)])
array([[1],
       [1],
       [1]], dtype=uint8)
```

However, even if the length of the bitarrays are different, the call may still fail:
```
>>> numpy.array([bitarray('1'*i) for i in range(3)])
array([bitarray(), bitarray('1'), bitarray('11')], dtype=object)
>>> 
>>> numpy.array([bitarray('1'*(i+1)) for i in range(3)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot copy sequence with size 2 to array axis with dimension 1
```

**Comment by seberg** [comment]
Going to close this, both comments are unrelated.  The first about dataframes: that isn't how NumPy works, there are workarounds (e.g. using `empty` and filling, and yes there is a possibility of making it easier, but there are more issues about that open).
The second about bitarray:  Not sure, its working for me, but there are bitarray inanities anyway due to `memoryview` usage now.  The comment is too old and in the wrong place anyway.
