### ISSUE TITLE
Update Building From Source on Windows

### ISSUE THREAD

**Issue by gfyoung** [numpy/numpy#7104]
I was updating Cygwin and attempted to locate the Devel packages described <a href="http://www.scipy.org/scipylib/building/windows.html">here</a> (i.e. ```gcc``` and ```gcc-mingw```), but I can't seem to find them.

Did you mean the following:
<b>gcc-core</b>
<b>gcc-fortran</b>
<b>mingw-gcc-core</b>
<b>mingw-gcc-fortran</b>

**Comment by rgommers** [comment]
That text looks very much out of date. I think we should simply say "building with Cygwin should work, but isn't regularly tested. The same compilers and dependencies as on Linux are needed." I don't think there's much of a point in giving a lot of details, they'll go out of date again.

**Comment by gfyoung** [comment]
Since I'm in the middle of updating Cygwin anyways, I'll try walking through the installation instructions and put up a PR to update the instructions.

**Comment by gfyoung** [comment]
@rgommers : Where can I find the pages that contain the instructions?  I tried doing a search through the GitHub repository, and nothing came up.

**Comment by gfyoung** [comment]
The documentation <a href="http://www.scipy.org/scipylib/building/windows.html">here</a> is so old that it doesn't account for the fact that ```Cygwin``` now has stable versions for both ```32-bit``` and ```64-bit``` out.  I suspect an overhaul will be needed here and perhaps some revision to the RST file <a href="https://github.com/numpy/numpy/blob/master/INSTALL.rst.txt">here</a>.

**Comment by rgommers** [comment]
Here's the source: https://github.com/scipy/scipy.org/blob/master/www/scipylib/building/windows.rst

An update of that page would be great. More details in numpy's INSTALL.txt are less desirable imho - I'd like to keep detailed build info on the scipy.org pages linked above. Keeping them in one place makes it easier to update them. The numpy userguide and INSTALL.txt should link to the scipy.org pages for detailed build info. They themselves should only give the basics for OS X and Linux, and nothing but the link for Windows (because there is nothing called "basics" on Windows, it's always complex).

**Comment by gfyoung** [comment]
Closing this issue for the version in `scipy.org`
