### ISSUE TITLE
arange from numpy function has some limits....I propose a python function that overcome these limitations

### ISSUE THREAD

**Issue by francescopelizza-omega** [numpy/numpy#7115]
arange from numpy is a function to generate list of floats from a start to an end number with a defined float number.

The "arange" function works fine for some cases, but in my case where I have to generate numbers that constitute parameters in a Quantum Mechanical calculation, numbers can be missing or be more than what I want, since many time each number is calculated in a couple of days or more. I need to avoid extra numbers or missing numbers to avoid loss of data. And sometimes the script will pass to a cycle function wrong numbers for start and stop, or the same number as starting and ending point, but I can not avoid this because they are numbers coming from Quantum World, and I need a function that sort out anything on its own because is inserted in for loops and things like that.

Also arange function does not take the "stop" number as the last number of the list, but it will terminate before, so to have the last wanted number in the list you have to use the formulae  arange(start,stop+inc,inc) or arange(start,stop+n,inc) where n allows is bigger than zero.

Some cases that give me problems are the following:
Defective lists of numbers:
1) arange(1,10+0.0000001,0.00000001) some numbers are missing
2) arange(1,10+0.0000001,1) generate float without any decimal after the point
3) arange(1,10,0.0000001) some numbers are missing
4) ...other combination gives problems

Empty lists of numbers:
1) arange(1,10,-1)
2) arange(1,-10,1)
3) arange(1,1,1)
4) arange(1,1,0.5)
5) arange(1,-10,0.005)
6) so on....

I made a python function that goes across any of these problems, taking account of using the absolute value of the given incremental step number.

Numbers can be float or integers, any exception of number ordering is kept under control to generate anyway at least a list of one number, if the stop number is bigger than the starting one, they get switched to generate anyway a list of numbers. And it can go down until 14 decimal places of incremental steps without generating wrong numbers due to the binary conversion of floats!
Some use of this function are eventually weird or really exotic, but in using python as a code to deal with computation without crashing for silly numbers ordering from the quantum world, is essential.

Do you agree with the improvements I put in this function called "CYCLE" can be of help?

I would like to share it with the community.

Here attached the function I made

```
#!/usr/bin/python

def CYCLE(start, stop, step):
	var=[]; x=start; y=x; Astart=start; Bstop=stop; step=(abs(step) if step != 0 else 0.1); start=(Astart if start > stop and step < 0 else start);
	if (start > stop): x=Bstop; y=x; stop=Astart;
	if y+step <= stop:
		while x < stop+step:
			x=(round(x, 14) if isinstance(x,float) else int(x));
			if x <= stop: var.append(x);
			x=x+step;
	else: var=[start];
	return(var);

print CYCLE(1,1.00001,0.000000001); #put any number as starting (start), ending (stop) and incremental (step) steps to see the realiability of the function
```

**Comment by seberg** [comment]
Hey, thanks for your effort. I have to admit, I have some serious doubts about this. The first part of the problematic cases are definitely true, and they are why we ask everyone to use `np.linspace`. `np.arange` should ideally *not* be used with floating point numbers in general (this is mentioned in the documentation of arange).

I am aware `linspace` can be unhandy at times, but it seems not quite a trivial thing to improve, however if you have some nice ideas they would be very welcome!

For this code specifically, I have some trouble understanding what you want to do with inverted ranges and negative steps (the code seems to have small bugs in that regard?). Also I do not like the approach of rounding, while practical in many cases, it could be a trap when you want to generate small numbers such as from `1e-13` to `3e-13` in small steps.

That is to say that while I think we probably could improve things such as `np.linspace`, I am not sure how exactly to do it, and I have my doubts about this specific approach as it stands. Also, please avoid `np.arange` for floats and if you are unhappy with `np.linspace` as well, go ahead and mention it or please post your suggestions again. I don't want to sound overly negative, but I will close this for now, because I think `np.linspace` is the function we should discuss and not `np.arange`.

**Comment by francescopelizza-omega** [comment]
Well yes the code is of course strange. It deals with some of my problems.

The first need is to always have a list of numbers, even if it means to 
have a list of one number, but I need it.

Sometimes extracted incrementals values from computation comes out 
randomly positive or negative so i prefer to do the absolute value of 
the increment.

If for an user error, or because from the Quantum Mechanical systems 
numbers ranges, from start to stop comes out inverted in sequence, a 
normal function will not give my any list, but I need it anyway, and the 
best thing is to rebuild the natural numerical order from the smallest 
to the bigger.

Rounding is something I hate, but due to the binary conversion of 
numbers we are subject to systematic numerical errors conversion and 
rounding makes anything so far to x.y-e-14 numbers still fully accurate. 
And in physics, unless you work for fundamental measurements, you never 
need to go lower in decimal places.

The use of Decimal create conflicts and is too much time consuming. 
Anyway it present some systematical numerical errors eg 0.00001 becomes 
9.9999999999995642354312545345451344E-5

|np.linspace| is handy but limited in its function requiring too many 
specification for my needs

That's why I made this function called CYCLE, and it does a very nice 
job until 14 decimals, and I really need it, that's why I would like to 
have feedback from people dealing computation with python, if they also 
like that solution

**Comment by rkern** [comment]
This is not a particularly good place to get the feedback that you are looking for. Please post to the one of the mailing lists instead.

http://www.scipy.org/scipylib/mailing-lists.html
