### ISSUE TITLE
error in numpy mask doc

### ISSUE THREAD

**Issue by sunchaoatmo** [numpy/numpy#7117]
In http://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html#the-numpy-ma-module
Indexing and slicing, the example is:

x = ma.array([1, 2, 3, 4, 5], mask=[0, 1, 0, 0, 1])
mx = x[:3]
mx
masked_array(data = [1 -- 3],
mask = [False True False],
fill_value = 999999)
mx[1] = -1
mx
masked_array(data = [1 -1 3],
mask = [False True False],
fill_value = 999999)
However, for mx, given we assigned mx[1] as -1 ,so the output is supposed to be unmasked for mx[1]. I tested it with Python 2.7.11, here is the output:

import numpy.ma as ma
x = ma.array([1, 2, 3, 4, 5], mask=[0, 1, 0, 0, 1])
mx = x[:3]
mx
masked_array(data = [1 -- 3],
mask = [False True False],
fill_value = 999999)

mx[1] = -1
mx
masked_array(data = [1 -1 3],
mask = [False False False],
fill_value = 999999)

**Comment by maniteja123** [comment]
Hi, I am not a dev but AFAICS, the documentation has the wrong answer. Since this is same as manually unmasking by assigning the masked element. [This](http://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html#unmasking-an-entry) is my reference here. Also a warning is currently raised on the master when trying to assign the value.

>
FutureWarning: Currently, slicing will try to return a view of the data, but will return a copy of the mask. In the future, it will try to return both as views. This means that using `__setitem__` will propagate values back through all masks that are present.
>

Hope it answers the question. And I apologize if I am understanding something wrong and it would be great if the experts could correct me.

**Comment by sunchaoatmo** [comment]
Thanks for your reply, I aplogize I didn't make it clear, I mean after you assign value to the masked array, its mask should be changed to false, which is the output from python 2.7, and explained in "Unmasking an entry" secontion of the document.
But the document is incorrect for this case in "Indexing and slicing" see this line:
mx
masked_array(data = [1 -- 3],
             mask = [False  True False],
       fill_value = 999999)
>>> mx[1] = -1
>>> mx
masked_array(data = [1 -1 3],
             mask = [False  True False],
       fill_value = 999999)

**Comment by maniteja123** [comment]
I am sorry for being not clear. You got it right here. It seems the section in the doc was updated in around 2009. It possibly is a error and there are no doctests which would have caught this.

**Comment by sunchaoatmo** [comment]
Gotcha, thanks again, do you know whether there is any possble way to update the doc, hope we can help other people in the future.

**Comment by maniteja123** [comment]
It looks like [this](https://github.com/numpy/numpy/blob/master/doc/source/reference/maskedarray.generic.rst) is the document. I suppose this error can be fixed in the doc. Having said that, it would be better to seek the opinion of the devs to proceed because it hadn't been touched for quite sometime.

**Comment by madphysicist** [comment]
If you ran the commands in the example and got different output from what is listed, you can create a PR and fix it. It is likely that they have not been updated after a change was made to the API and I am pretty sure the devs would appreciate you catching and fixing that.
