### ISSUE TITLE
__array__ not called on ufunc out parameters

### ISSUE THREAD

**Issue by adler-j** [numpy/numpy#7158]
In the `__array__` [documentation](http://docs.scipy.org/doc/numpy-1.10.0/reference/arrays.classes.html#numpy.class.__array__) it says:

> If a class (ndarray subclass or not) having the `__array__` method is used as the output object of an ufunc, results will be written to the object returned by `__array__`.

however, this does not seem to be the case, as this example shows:

``` python
import numpy as np

class NDLike(object):
    def __init__(self, values):
        self.values = np.asarray(values)
    def __array__(self):
        return self.values
    def __array_wrap__(self, result):
        return type(self)(result)
    def __repr__(self):
        return "[%s]\n%s" % (type(self), self.values)

    # Adding these make no difference
    def __array_prepare__(self, array, context=None):
        return array.values if isinstance(array, NDLike) else array
    __array_priority__ = 1000000.0
```

this works:

``` python
>>> x = NDLike([1, 2, 3])
>>> np.negative(x)
[<class '__main__.NDLike'>]
[-1 -2 -3]
```

while this doesnt:

``` python
>>> x = NDLike([1, 2, 3])
>>> out = NDLike([0, 0, 0])
>>> np.negative(x, out=out)
TypeError: return arrays must be of ArrayType
```

Clearly, there is no attempt to call `__array__` on `out`.

It seems either the documentation is wrong, or the implementation is lacking.

Enviromenment: Windows 10, python 2.7.11, numpy 1.10.1

**Comment by ahaldane** [comment]
From grepping I confirm `__array__` is not used anywhere in the ufunc code.

I havent followed ufuncs much, but I'm writing here because I wonder if this is related to the discussion of the unclear behavior of the `out` and `subok` arguments to ufuncs in #5706 starting [here](https://github.com/numpy/numpy/pull/5706#discussion_r39394101). It appears there that `__array_prepare__` can be used to return a new array to be used as the output parameter.

**Comment by seberg** [comment]
My guess is, this was true up until numpy 1.7 when Mark redid ufuncs (don't know the history exactly, just guessing). So I will say, the documentation is wrong, but maybe the implementation is lacking as well ;).
One problem I see with supporting `__array__` for the out argument is that it may not return a view (unlike `__array_interface__`, which maybe could be supported with less possible oddness).

This does not mean that it doesn't sound like it might be good to support this again, but since I expect this is the case since numpy 1.7 I would probably not see it as a regression. Also I wonder if all that `__numpy_ufunc__` ideas don't cover this better in any case.

However supporting a bit more here is not very complex to implement, just grep for the error message and include some logic before it. So we could discuss that.

 @ahaldane I don't think this touches current masked arrays since they are subclasses and not array-likes so you can use them as out argument.

**Comment by adler-j** [comment]
I'll try to get this fixed and make a pull request then, is that ok?

**Comment by seberg** [comment]
@adler-j please, go ahead! Just to warn you though that I am not quite sure what exact behaviour we want, so please do not be disappointed if things don't go very smooth. Still the easiest way to discuss it is having a specific proposal and a PR.

**Comment by seberg** [comment]
Closing (this very old issue), the related PR was closed long ago, but this issue was forgotten.  Basically `__array__` and the ufunc out-argument can't work right now because `__array__` has no view guarantees.  Other array-likes might work, but I suggest open a new issue if that is wanted.
