### ISSUE TITLE
numpy.stack name is confusing given that it's different from hstack, vstack

### ISSUE THREAD

**Issue by aukejw** [numpy/numpy#7183]
[`numpy.stack`](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.stack.html) stacks a sequence of arrays along a _new_ axis.

`hstack`, `vstack`, on the other hand, actually perform a `concatenate`: they stacks arrays along an existing axis.

The name `stack` seems counterintuitive and confusing. I understand that for backward compatibility it should not be altered, but perhaps the difference can be emphasized in the documentation?

**Comment by madphysicist** [comment]
The documentation for `stack` currently begins with "Join a sequence of arrays along a new axis." The link to `concatenate` says "Join a sequence of arrays along an existing axis." The words new and existing are pretty clear there.

Would you like to add links to `hstack` and `vstack` in the docs for `stack` with explicit mention of the fact that they stack along existing row/column axes? The place to do that would be `numpy/core/shape_base.py`. `stack` is on line `282`, `hstack` on `232` and `vstack` on `180`.

**Comment by aukejw** [comment]
I agree, the documentation on both functions is very clear. Since I was familiar with `vstack` and `hstack` behaviour, I naively assumed (without reading the docs, of course) that `stack` would also concatenate along an existing axis -- of course, that's what `concatenate` is for.

Added `dstack` in the PR as well, since it seemed to be referenced in both `vstack` and `hstack` docs. If necessary, I can try to make the descriptions fit on one line.

**Comment by madphysicist** [comment]
I made a couple of comments on the PR that may help you with that :).

**Comment by aukejw** [comment]
I addressed your comments, shall I squash the two commits?

**Comment by madphysicist** [comment]
It would be better to ask that on the PR than on the issue thread. That is a question above my pay grade, but the maintainers have generally asked me to squash when there are more than two commits on a branch. I think two is OK most of the time.

**Comment by aukejw** [comment]
Alright, I'll wait until further notice. Thanks for your help.

**Comment by shoyer** [comment]
`numpy.stack` is actually pretty new -- it only was released in NumPy 1.10. It's worth taking a look at the discussion in my original PR for the full context: #5605.

I actually intentionally omitted `vstack` and `hstack` from the docstring for `stack`, because these routines are less general and powerful than `stack` and `concatenate`. The way that `vstack`/`hstack`/`dstack` handle arrays of different dimensionality is quirky and difficult to predict for most people without experimentation. In contrast, `stack` and `concatenate` are a better fit for NumPy as a library for manipulating N-dimensional arrays.

If I had my way, I would actually consider deprecating `vstack`/`hstack` instead. Of course, we can't really do that because of numpy's very strong backwards compatibility guarantees, but I would like to nudge users away from using these functions. `stack` and `concatenate` (coupled with numpy's axis manipulation routines) are enough for nearly every use case. The `*stack` functions are mostly just noise.

That said, none of this is explicitly stated in the docs right now. If you can figure out a way to do that, I would be very grateful for it.

**Comment by njsmith** [comment]
We should definitely do a better job of conveying actual usage guidelines
in our docs. (Other examples that come to mind: no warnings against matrix
or subclassing.) I'd be +1 to putting a prominent note at the top of hstack
etc. saying "this function continues to be supported for backcompat, but
you should really prefer concatenate or stack (keeping in mind it was added
in 1.10)".
.
Don't forget row_stack and column_stack in this discussion either.

**Comment by madphysicist** [comment]
Would there be any use to deprecating at this stage?

**Comment by seberg** [comment]
I think we can document them to ask people to not use them. Actual deprecation(warnings) at this point is definitely going too far. Maybe in a few years ;). Especially since the "prefered" option cannot be used, until nobody needs to support versions of numpy < 1.10.

**Comment by aukejw** [comment]
@shoyer given that discussion, it's very clear why you reject this PR. As I was familiar with the *stack functions (but not with stack) I wanted to emphasize the difference between the former and the latter.

Specifying in the docs that *stack shorthands should be avoided, and that concatenate should be used instead, seems very reasonable.

**Comment by njsmith** [comment]
@aukejw: Yes, sorry for the mishap with #7191. If you're up for making a new branch and submitting a new PR then it sounds like everyone agrees that a doc update would be good -- just a somewhat different one :-).

**Comment by aukejw** [comment]
Alright, I'll be on holiday until the 14th, so if some else wants to pick this up, that's fine as well.. If not, you can expect a new PR around Feb 14.

**Comment by shoyer** [comment]
Fixed by #7253
