### ISSUE TITLE
Use of tokenize in numpy header slows reads and writes by 300%

### ISSUE THREAD

**Issue by aminusfu** [numpy/numpy#7185]
https://github.com/numpy/numpy/issues/5170 fixed some Python2/3 compatibility issues by filtering a leading "L" from the repr of longs while reading from disk. A subsequent commit (https://github.com/charris/numpy/commit/a8e027ff49fdfdce4d845eef7e1f8cd939ae840a) applied the same approach to writing.

Unfortunately, because it uses the "tokenize" module, the new `_filter_header` function now consumes on the order of 75% of the time of a call to `numpy.save()`; in other words, it nearly quadruples the time! We've had to write our own version of numpy.save to regain acceptable performance in our NumPy-based database product. Given that the number of objects in the header is small, it is _much_ faster to strip the "L" as needed when forming the repr of each value rather than converting the repr of the complete dictionary back to tokens:

```
    for key, value in sorted(d.items()):
        # Need to use repr here, since we eval these when reading
        if isinstance(value, long):
            value = repr(value)[:-1]
        else:
            value = repr(value)
        header.append("'%s': %s, " % (key, value))
```

**Comment by njsmith** [comment]
Thanks for the report! Can you submit the change as a pull request?

**Comment by aminusfu** [comment]
I can for the writes, but some thought will have to be given (by sager heads than mine) to how best to reclaim the performance of reads in the presence of existing "L" chars in files which were written out before these changes.

**Comment by ahaldane** [comment]
Reviewing this as part of my 10 random issues, as requested in a [3/20/19 request](https://mail.python.org/pipermail/numpy-discussion/2019-March/079250.html).

I am leaning towards closing this old issue. It will be less relevant once we drop py3 support since headers with the "L" in the int will no longer be produced.

I also suspect this performance issue only turns up if you are saving a large number of very small arrays, so it's a pretty unusual and perhaps not so important case. @aminusfu if you are still around, do you have example code I can run demonstrating the slowdown?

**Comment by seberg** [comment]
Since Allan suggested closing this (because apparently it is mainly about `L` present due to files written in Python 2), I am going to close this without further investigating if there may still some merit to it now.  If there is, please open a new one.
