### ISSUE TITLE
AttributeError on cos on sparse matrix (but not on sin)

### ISSUE THREAD

**Issue by Phyks** [numpy/numpy#7234]
Hi,

```python3
>>> import numpy
>>> numpy.cos(u)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/site-packages/scipy/sparse/base.py", line 525, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: cos not found
>>> numpy.sin(u)
<5x5 sparse matrix of type '<class 'numpy.complex128'>'
	with 8 stored elements in Compressed Sparse Row format>
```

Which is weird because the sin is working but not the cos.

In my case, `u` is a `Qobj.data` attribute (from qutip, see http://nbviewer.jupyter.org/github/jrjohansson/qutip-lectures/blob/master/Lecture-0-Introduction-to-QuTiP.ipynb#Creating-and-inspecting-quantum-objects). This type is basically a wrapper on top of `scipy.sparse`: https://github.com/qutip/qutip/blob/master/qutip/sparse.py.

Is it expected? Are there any ways to workaround?

Thanks!

EDIT: Better example (minimalistic) would be:

```python3
>>> import numpy; import scipy.sparse as sp
>>> numpy.cos(sp.eye(5))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/site-packages/scipy/sparse/base.py", line 525, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: cos not found
>>> numpy.sin(sp.eye(5))
<5x5 sparse matrix of type '<class 'numpy.complex128'>'
	with 8 stored elements in Compressed Sparse Row format>
```

**Comment by njsmith** [comment]
It doesn't make much sense to call numpy functions on a sparse array -- you're ending up doing something like, creating a single element numpy array of python objects where the single element is the sparse array object, and then numpy doesn't know how to do `sin` or `cos` on a random object that it knows nothing about, so it tries calling the object's `.sin` or `.cos` method. You could cut out the middleman by leaving numpy out of this entirely and calling these methods yourself :-). There are plans afoot to let numpy integrate better with scipy.sparse, but for now that's how it works.

Then, your actual problem is that scipy.sparse turns out to have a `.sin` method but not a `.cos` method. (I think this is because `sin(0) == 0` so `sin` preserves sparsity, but `cos` doesn't, and they don't want to make it easy to accidentally de-sparse a matrix.) What you want to do about that I'm not sure -- you could file a bug with the scipy project asking for this method to be added, I guess, though since I think it's an intentional omission I'm not sure what they'll say. Or you could call `.toarray()` to get a real numpy array and then call whatever functions you like. :-)

I don't see anything that numpy itself could do for you here, so closing for now -- but if I'm missing something please feel free to reopen.

**Comment by Phyks** [comment]
Ok, indeed you are right this may not be of great interest. The original issue was that I was assuming calling `cos` on a shaped object would compute the cosine of this object (that is what `scipy.linalg.cosm` does). So I guess this can be safely closed I think.
