### ISSUE TITLE
numpy.void and numpy.ma.mvoid with structured dtypes should support indexing with multiple fields

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#7262]
A structured ndarray can be indexed with multiple fields:

```
In [14]: X = numpy.empty(shape=1, dtype="(2)3S,(2)3U")

In [15]: X[["f0","f1"]]
Out[15]: 
array([([b'', b''], ['', ''])], 
      dtype=[('f0', 'S3', (2,)), ('f1', '<U3', (2,))])
```

However, the corresponding `numpy.void` type cannot:

```
In [16]: X[0][["f0","f1"]]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-16-4f230bb69b0d> in <module>()
----> 1 X[0][["f0","f1"]]

IndexError: invalid index
```

The same is true for masked arrays.

For consistently, `numpy.void` with a structured dtype should support indexing with multiple fields exactly like `numpy.ndarray` does.

**Comment by ahaldane** [comment]
I actually had fixed this in #6208, but I backpedaled because mutli-field subscripts work strangely (see #6053). My plan was to get #6053 in first, and then go back and enable this.

#6208 has already partially set up the fix: All that's left is to change the `if(Py_Ustring_Check(ind)` in `voidtype_subscript` to test for an array of strings too.
