### ISSUE TITLE
linspace floats

### ISSUE THREAD

**Issue by emilienkofman** [numpy/numpy#7289]
I'm not sure if it's a bug or intended behavior, but may it make sense to obtain the same result in the two following linspace examples?

```
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
>>> import numpy
>>> numpy.version.version
'1.12.0.dev0+bd905a8'
>>> numpy.linspace(2.0, 3.0, num=5)
array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])
>>> numpy.linspace(2.0, 3.0, 0.25)
array([], dtype=float64)
```

**Comment by maniteja123** [comment]
Hi, I am not a developer and but it seems that 0.25 is taken as 0 in number of samples, which is a non-negative integer. I also suppose what you meant was ``np.arange(2.0, 3.0, 0.25)`` which takes step size. Please correct me if I am wrong.

**Comment by seberg** [comment]
Sure, we should implement an `index_deprecate` for python side code, and then at some point change it to `operator.index` logic here (or if you just want to do it here, try operator.index, if fail try with "int" and give a (visible)deprecationwarning just like all the other integer deprecations).

**Comment by emilienkofman** [comment]
Ah ok the third argument is always supposed to be a number of samples, and never a step (as like as in the `range` built-in). It's a bit misleading, maybe a deprecated message would help to understand this behavior but I don't get exactly what do you plan to implement (I could try to fix it if it's not a major change).

**Comment by seberg** [comment]
The best way to get the integer is to not do `int(num)`, but instead do `operator.index(num)`. But we should not just change it. Instead we should do a deprecation cycle on it. Something like a:
```
try:
    num = operator.index(num)
except TypeError:
    num = int(num)
    warnings.warn("Some text", DeprecationWarning, stacklevel=2)
```
would do. Could think about making this part our own little function, so that we can reuse it elsewhere.

**Comment by njsmith** [comment]
@emilienkofman: the bug is that right now we call `int` on the number-of-samples argument, which is too aggressive: for example it will happily turn `float`s into integers, which is usually a mistake.

What we would like is for it to instead call `operator.index` (for the stdlib `operator` module), which is like `int` but less aggressive. (It's called `index` because the original place this kind of problem was noticed was in indexing expressions like `mylist[0.5]`, where you also want to raise an error instead of converting the value to `int`.)

We can't just switch from the current behavior to the behavior that we would like, because that might rudely break people's code. So what @seberg is suggesting is that first, we define a helper function called `index_deprecate` (or whatever), which tries calling both `int` and `index`, and if both succeed then it is happy; and if `int` succeeds but `index` fails then it succeeds (so it doesn't break people's code) BUT it issues a DeprecationWarning (so people get solve warning that their code will break in the future when we stop calling `int`, and have a chance to fix it ahead of time).

There are probably other places that could also use such a function -- we've been cleaning up a lot of these integer things in numpy's C code, but haven't really looked at numpy's python code yet.
