### ISSUE TITLE
np.array([np.array([np.nan, np.nan]) > 1e8 raises FloatingPointError

### ISSUE THREAD

**Issue by eXcuvator** [numpy/numpy#7352]
Reproducable example:

np.seterr(all='raise')
np.array([np.nan, np.nan]) > 1e8 

FloatingPointError: invalid value encountered in greater
### 

np.seterr(all='raise')
np.array([np.nan]) > 1e8

works as expected (returns False)

**Comment by njsmith** [comment]
`seterr(all="raise")` means that you want all computations involving nan to raise an exception. (That's one of the flags included in "all".) So it's the second case that's buggy, not the first.

I'm not sure why the two cases differ, but IIRC it is a general property of the "invalid" flag in general that hardware and low level software are a bit inconsistent about checking and signalling it. So even though the second case is theoretically wrong, it might or might not be something we can practically fix.

**Comment by seberg** [comment]
Going to close this, since it is not the behaviour anymore.

**But:** current NumPy disregards C99/IEEE for comparisons.  We never set the floating point warning flags (or clear them manually, which can't be avoided for some compilers and older SSE).  As Nathaniel noted, C99/IEEE says that `>` should do this, and C99 has `isgreater` to avoid setting it.
