### ISSUE TITLE
Internal Rate of Return calculation with different pay and compound period

### ISSUE THREAD

**Issue by joddoj** [numpy/numpy#7367]
http://docs.scipy.org/doc/numpy/reference/generated/numpy.irr.html#numpy.irr

On the link I posted, I can use the irr to calculate it only and only if the pp and cp are the in years, which is lame. What if I my pp is in months and cp is in quarters, then what ? Please someone tell me.

**Comment by seberg** [comment]
Yeah, it is totally lame. But also I frankly do not see this changing in numpy. I think more any serious financial stuff should not be inside numpy, but rather in its own package, the current state inside numpy is already dubious to me.

Since I do not think there is anything to do here for numpy itself and thus there is no real TODO here for numpy, I will close it. Feel free to reopen if someone disagrees.

More complex financial functions should be part of their own package and not numpy. Maybe the PyData community by now has something, but don't know. I would be happy for the numpy functions doc giving pointers to newer alternatives.
