### ISSUE TITLE
Result of sum depends on array order

### ISSUE THREAD

**Issue by burrowsa** [numpy/numpy#7368]
I've come across this strange behavior when using ```numpy.sum```. The result of ```numpy.sum``` changes depending on the order of the values in the array:

```
In [1]: import numpy as np
In [2]: b = np.array([ -462914.25      , -4450888.        , -3546839.        ,
            7919.85400391, -3874966.25      , -1358369.625     ,
         -420256.46875   ,  -336801.9375    ], dtype=np.float32)
In [3]: bs = np.array([-4450888.        , -3874966.25      , -3546839.        ,
       -1358369.625     ,  -462914.25      ,  -420256.46875   ,
        -336801.9375    ,     7919.85400391], dtype=np.float32)
In [4]: np.float32(-462914.25) + np.float32(-4450888.) + np.float32(-3546839.) + np.float32(7919.85400391) + np.float32(-3874966.25) + np.float32(-1358369.625) + np.float32(-420256.46875) + np.float32(-336801.9375)
Out[4]: -14443115.0
In [5]: np.float32(-4450888.) + np.float32(-3874966.25) + np.float32(-3546839.) + np.float32(-1358369.625) + np.float32(-462914.25) + np.float32(-420256.46875 ) + np.float32(-336801.9375 ) + np.float32(7919.85400391)
Out[5]: -14443115.0
In [6]: np.sum(b), np.sum(bs), sum(b, np.float32(0))
Out[6]: (-14443116.0, -14443115.0, -14443115.0)
In [7]: np.__version__
Out[7]: '1.10.4'
In [8]: 
```

If I change the example above to use ```numpy.float64``` throughout, the discrepancy goes away.

I been able to reproduce this in numpy 1.9.2 and 1.10.4 but not in 1.8.1

I have reproduced this issue on my own system (RHEL7, python 2.7) and on pythonanywhere (both python 2.7 and python 3.4.3)

**Comment by seberg** [comment]
We use pairwise summation along the fastest axis (memory order wise) which increases the numerical accuracy normally. Note that you are reporting differences of one ULP (the last bit) of float32, those have to be expected since numpy optimizes the way it iterates an array (though in this case you already put the order in).
We now use pairwise summation sometimes, but numpy does not provide Kahan summation or so for increased accuracy (even with kahan I guess an ULP difference may occur, not sure).

**Comment by njsmith** [comment]
FTR in pathological cases even Kahan summation can have multiple ULPs of rounding error. There exist algorithms for correctly rounded sum, but they're *much* more complicated and require allocating varying amounts of temporary storage.

But yeah, in general numpy (and floating point in general) are going to show funny effects of rounding error, and you have to be prepared for small ("unit in the last place" aka ULP) variations. Numpy has a number of strategies for summation it will try to pick depending on speed and accuracy, and naive `((a[0] + a[1]) + a[2]) + ...` is often not the best choice :-). And there's a reason that float64 is the default: float32 *really* is tricky to use correctly, because it just doesn't have enough bits of accuracy in a lot of situations; I would avoid it unless you *really* know that you need it and have some reasonable working understanding of numerical accuracy issues.

**Comment by seberg** [comment]
Going to close this, but feel free to follow up on it.
