### ISSUE TITLE
`np.array` behaviour different when `order=None` and `order='A'`

### ISSUE THREAD

**Issue by vighneshbirodkar** [numpy/numpy#7374]
When you refer to the documentation of `np.array` here
http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.array.html
The page says that `order='A'` is default, while the function prototype indicates `order=None` is default. Initially I assumed that both of them give the same results, but that is not the case. See the following snippet.

``` python
>>> import numpy as np
>>> from numpy.lib.stride_tricks import as_strided
>>> a = np.array((100000,),  dtype=np.float64)
>>> b = as_strided(a, strides=[8, 512], shape=[10, 64])
>>> b.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
>>> c = np.array(b, order=None, copy=True)
>>> c.flags  # see that C_CONTIGUOUS is False
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
>>> d = np.array(b, order='A', copy=True)
>>> d.flags # see that C_CONTIGUOUS is True
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

I expected that when `order=None` and `copy=True` the output would be C-Contiguous, since `order=None` is the default in the function prototype. I believe that either `None` should behave exactly like `'A'` or the documentation of the function prototype should be changed to mention that `'A'` is the default order.

Numpy Version = '1.10.2'
Python 2.7.6

**Comment by charris** [comment]
Looks like a bug to me.

**Comment by jakirkham** [comment]
So, just change the default to `"A"`? Should we have an assertion that checks it is some flavor string?

**Comment by seberg** [comment]
The default is "K" actually (which is awesome enough not documented). Probably the case since 1.7, so I would tend to say that we should fix the documentation rather then the implementation?!

Which also leads back gh-7217 should we think about making "A" map to "C if not F" (and copy if not the case)? I guess likely not, may be too much hassle, in case someoneone is using `order="A"` explicitly.

**Comment by jakirkham** [comment]
Ah, ok. I remember seeing this in the code before. Was thinking `A` and `None` behaved the same. After all that is what the docs state.

> If order is ‘A’ (default), then the returned array may be in any order

( http://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html#numpy.array )

Yeah, it doesn't look like we are even explaining `K` at all. So, we should explain it.

Hmm...yeah I feel weird about this one. Though changing the docs doesn't break anyone's code. So, I think I agree.

**Comment by njsmith** [comment]
...what *does* `K` do here?

**Comment by seberg** [comment]
Yeah, it is a bit fun isn't it. If you have `copy=False` it does the same as "A". If you have `copy=True` it does what it does for `np.copy` (i.e. copy the data, but keep the memory layout as close as possible to the current).
What I was meaning in regard to gh-7217, we could in principle change "A" to ensure that the array is either C or F-contiguous. That means forcing a copy when the array is not already contiguous, so that it does not do the same thing as "K" in the `copy=False` case.

**Comment by mattip** [comment]
Now documented that the default is `K`. Closing.
