### ISSUE TITLE
add ReLaPACK to numpy?

### ISSUE THREAD

**Issue by carlkl** [numpy/numpy#7379]
I want to draw the attention to a new linear algebra called [ReLaPCK](http://hpac.rwth-aachen.de/~peise/relapack) sitting on the top of BLAS and Lapack, see:

http://hpac.rwth-aachen.de/~peise/relapack
https://github.com/HPAC/ReLAPACK   (MIT license)

according to the authors this library even beats optimized Blas/LAPACK implementations in several cases. The API seems to be very simple: just use the augumented functions names instead of the original Lapack functions: [relapack.h](https://github.com/HPAC/ReLAPACK/blob/master/inc/relapack.h)

Integration into numpy: how could this look like?

**Comment by njsmith** [comment]
Looks like it's written in C, and has an option of configuring so that it's an ABI compatible drop in replacement for regular LAPACK, so numpy wouldn't necessarily need to do anything to integrate it.

The actual blocked algorithms remind me of what I've seen in @fgvanzee's FLAME library, though the implementation here appears to be much more elementary and unambitious (just a single set of straight line C code implementing one recursive blocked algorithm for each algorithm). Guess I should read the paper...

Would be good to see if it's actually fast before doing much else :-)

Cc @tkelman, who was complaining about slowness in openblas's LAPACK routines...

**Comment by pv** [comment]
The symbols are renamed, so you'd need some changes in numpy to support it. But that'd be a matter of adding it to `system_info.py` and some defines in linalg/setup.py and umath_linalg.c.src.

**Comment by njsmith** [comment]
@pv from skimming the source/docs they also have some support for exporting the regular symbol names; seems a bit tricky but I guess it should work.

**Comment by carlkl** [comment]
Adding ReLaPACK to i.e. OpenBLAS and us it from there seems to me the right approach, see https://github.com/xianyi/OpenBLAS/issues/788

**Comment by fgvanzee** [comment]
I haven't read the paper yet either, but we have close ties to Elmar and Paolo. (My PI was Paolo's advisor in grad school.)

The Achilles heel of many blocked algorithms in LAPACK is the self-similar subproblem (e.g. the smaller Cholesky factorization that appears in a blocked algorithm for Cholesky factorization); the other subproblems are usually level-3 operations, implemented by a BLAS library. The self-similar subproblem is usually slow, because it is typically solved via an unblocked implementation (i.e. in terms of level-1 and -2 operations). What Elmar and Paolo appear to have observed is that by performing additional recursive blocking for these self-similar subproblems (before switching to an unblocked code), you can extract higher performance, and since this is typically the bottleneck of those operations, the impact is more pronounced.

libflame *could* implement similar recursion for its factorizations and related operations, but currently does not.

**Comment by rgommers** [comment]
There's ReLAPACK in OpenBLAS now. That's the right place, so let's close this. Thanks everyone.
