### ISSUE TITLE
Docs for array creation routines: section "ones and zeros" should be renamed

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7408]
The "ones and zeros" sections contains also entries for `full` and `full_like`, which logically belong to that section but are not for "ones and zeros" :-)
I don't have a good suggestion, though.

**Comment by charris** [comment]
Maybe `Arrays filled with a single value`.

**Comment by mattip** [comment]
Closing, the format of the [page](http://www.numpy.org/devdocs/user/basics.creation.html) has changed.

**Comment by anntzer** [comment]
Actually the issue is still present at https://numpy.org/devdocs/reference/routines.array-creation.html#ones-and-zeros, so perhaps worth reopening?

**Comment by rossbar** [comment]
@anntzer is right, the problem is in the heading in array creation routines in the reference guide. Relevant source file: `doc/source/reference/routines.array-creation.rst`

**Comment by melissawm** [comment]
There doesn't seem to be a [name for these](https://en.wikipedia.org/wiki/List_of_named_matrices). However, `Arrays filled with a single value` doesn't go with `empty`, `empty_like` or `identity` to me. Since the next section is "From existing data", I'd suggest something like "From shape or value" but that may be too vague.
