### ISSUE TITLE
Attempt to change None values in array changes first line instead

### ISSUE THREAD

**Issue by DrewDevereux** [numpy/numpy#7457]
This is surely wrong:
```
>>> a
array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, None]], dtype=object)
>>> a[a==None]=4
>>> a
array([[4, 4, 4],
       [1, 2, 3],
       [2, 3, None]], dtype=object)

```

**Comment by njsmith** [comment]
Yep, it's wrong.

`a == None` is broken -- it just returns `False` (try it!). On recent numpy (I think 1.10? but maybe not until the not-quite-released-yet 1.11) you will get a warning that something weird is happening:
```
FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
```
Making `a == None` return `False` was a poorly-thought-out "feature" added a long time ago, and unfortunately we can't just change it because there may be existing code out there that depends on it -- so we're issuing a warning now, and after a while once people have had a chance to update their code then we'll make the change.

Then on top of that you're hitting a second bit of stupidness: `a[False]` should raise an error or something, but instead numpy tries to cast the `False` to integer, so you get `a[False]` -> `a[int(False)]` -> `a[0]`. This also issues a warning:
```
VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
```
and should become an error in 1.12. (This warning has been around for longer, and we tried to make it an error in 1.11, but failed because it turned out that too many downstream projects were still dependent on the old broken behavior :-/. You might not see this warning, because by default Python hides deprecation warnings -- try running with `python -Wdefault`, or even better switch to using `ipython` for interactive use. It's better in all ways than the default `python` prompt, including that it will show you when you're hitting deprecated behavior.)

(@seberg: why does a[False] not do boolean indexing?)

**Comment by charris** [comment]
Maybe because
```
In [2]: False.__index__()
Out[2]: 0
```
Python booleans subclass integer.

**Comment by njsmith** [comment]
I guess we're working on it:
```
In [1]: np.arange(10)[np.array(True)]
IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index
```

**Comment by seberg** [comment]
That is the reason, but one after another thing, we can clear it up. It actually does work for 0-d arrays (i.e. 0darray[False] will work), because that one was invalid always. For the rest, boolean indexing of non 0-d arrays with 0-d arrays, the code should all be there, and once the deprecation warnings are gone for the int deprecation and that 0-d boolean array future warning is gone, it should just work (though it may not be perfectly tested since it never worked).

**Comment by seberg** [comment]
So in some way, it is a chain. In the future we go from `False.__index__()` -> `np.array(False)` (Because the first we reject/deprecate) -> Remove the `arr[np.array(False)` error path.
At the last point, we have to double check I actually implemented all that impossible broadcasting logic correctly, which is dubiously tested, since I might have only done some manual tests back in the day since those code paths are dead right now.

**Comment by seberg** [comment]
Closing this, since both weird things are already in deprecation period.
