### ISSUE TITLE
no documentation of ufunc behavior for method of same name

### ISSUE THREAD

**Issue by mikofski** [numpy/numpy#7519]
The topic of this mailing list post by Sebastian Walker, [using numpy functions on an array of objects](https://mail.scipy.org/pipermail/numpy-discussion/2009-February/040026.html), is not completely clear to me in the documentation for ufunc or at least I could not find it.

The content of this except should cover it

> `numpy.sin()` is a ufunc. **Unary ufuncs will call the method of the same
> name on objects in an object array (or the scalar itself if given an
> object scalar).** For example:
> 
> ```
> In [8]: class MyClass(object):
>   ...:     def __init__(self, x):
>   ...:         self.x = x
>   ...:     def __repr__(self):
>   ...:         return 'MyClass(%r)' % (self.x,)
>   ...:     def sin(self):
>   ...:         return MyClass(self.x+1)
>   ...:
>   ...:
> 
> In [9]: sin(MyClass(4))
> Out[9]: MyClass(5)
> 
> In [10]: sin([MyClass(4), MyClass(5)])
> Out[10]: array([MyClass(5), MyClass(6)], dtype=object)
> ```
> 
> You'll notice that `numpy.sin()` does not try to call the `list.sin()`
> method when given the list. It interprets it as an object array, and
> calls the `MyClass.sin()` method on each of the elements.

This information could potentially improve many packages such as @ddale [Quantities](https://github.com/python-quantities/python-quantities) and @lebigot [Uncertainties](https://github.com/lebigot/uncertainties).

**Comment by njsmith** [comment]
I don't think this is a general fact about ufuncs, but rather an ad hoc hack inside several survivor ufuncs.

Also, this behavior is kinda broken and causes problems, so I hope we are able to deprecate it soon. I would recommend *not* trying to build new things on top of it.

A fast better solution is the `__numpy_ufunc__` approach, which is sadly stalled for the moment because no one currently is finding bandwidth to review the old discussions and propose a path forward. But if people are going to put in energy to trying to improve this particular thing then that's the route that will be most effective.
