### ISSUE TITLE
Issues building numpy from source on linux

### ISSUE THREAD

**Issue by pseandersson** [numpy/numpy#7540]
Hi
I have tried to build and install numpy on my linux computer. But I run into troubles with NumpyDistribution and setuptools, see the attached log to see the error messages.

I tried to modify numpy_distribution.py by adding the missing members, but it got corrupted in the end with entry points....

What do I miss?
[numpy_build_log.txt](https://github.com/numpy/numpy/files/215111/numpy_build_log.txt)

**Comment by charris** [comment]
Where did you get numpy?

**Comment by pseandersson** [comment]
I've got it from github, https://codeload.github.com/numpy/numpy/tar.gz/v1.11.0

**Comment by rgommers** [comment]
Two likely possibilities from looking at the build log:

- ``BLAS_SRC`` and ``LAPACK_SRC`` is almost never used, I have no idea if it's even supposed to work. Did you find install instructions somewhere that recommend this?
- maybe it matters if you you ``setup.py install`` instead of ``setup.py build install``? Now you're triggering ``bdist_egg`` and ``easy_install``, which are best avoided.

**Comment by njsmith** [comment]
If you wait until tomorrow when the binaries get posted, `pip install numpy` will start giving you a binary without having to build it from source. (Using OpenBLAS.)

Until then, `pip install numpy` will attempt to build from source in a much much more well-tested fashion than your rather odd setup.py command-line. (Or even after tomorrow you can use `pip install numpy --no-binary :all:` if you really want to build from source.)

**Comment by pseandersson** [comment]
@rgommers  I found BLAS_SRC and LAPACK_SRC among the warning messages.
It doesn't matter if i do "python3 setup.py install --prefix /my/prefix" or using the build command.

@njsmith  I'll test pip install, just need to build it.

**Comment by pseandersson** [comment]
@njsmith The computer has no internet access, so I need to build it from source.

**Comment by njsmith** [comment]
@pseandersson: Okay, but you will still be following a much more well-trodden path if the way you build from source is to (a) download the official release .tar.gz from PyPI instead of using a git snapshot, (2) use `pip install numpy-1.11.0.tar.gz` instead of messing about with `setup.py`.

Alternatively, you can download a pre-built .whl file from https://ccdd0ebb5a931e58c7c5-aae005c4999d7244ac63632f8b80e089.ssl.cf2.rackcdn.com/ -- you want the file named like `numpy-1.11.0-cp<YOUR PYTHON VERSION>...`. Again, you download this and then run `pip install <path to the .whl file>`.

**Comment by pseandersson** [comment]
@njsmith ok I will try again to make pip work so I can go the easy way.

**Comment by pseandersson** [comment]
Finally I've got @rgommers 's solution to work fine.

**Comment by pseandersson** [comment]
I added these line to numpy/distutils/numpy_distribution.py:
`self.include_package_data = True`
`        self.entry_points = {}`
