### ISSUE TITLE
np.unique issue

### ISSUE THREAD

**Issue by jpreistad** [numpy/numpy#7560]
I came across something that might be a bug in the numpy unique function. Here is an example.

In my case, a is a numpy array holding indices referring to pairwise equal elements in two other vectors (not shown). It could for instance be:

a=np.array([[1,2],[3,4],[1,2],[5,6,7]])

In this case, element 1 and 2 are pairwise equal in the two arrays not show. The same goes for element 3 and 4, and elements 5,6,7.

Since the [1,2] pair is occuring twice, I want to remove the duplicate entry. I use

In [18]: np.unique(a)
Out[18]: array([[1, 2], [3, 4], [5, 6, 7]], dtype=object)

However, what causes me trouble, is when there are only two pairwise identical elements:

In [19]: a=np.array([[1,2],[3,4],[1,2],[5,6]])
In [20]: np.unique(a)
Out[20]: array([1, 2, 3, 4, 5, 6])

Now, the output has a completely different meaning for my purpose.

Is the unique function supposed to work this way?

**Comment by jaimefrio** [comment]
[`unique` flattens its input](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.unique.html) before figuring out the unique values. In the first case, because your lists have different lengths, you get a 1D array of object dtype. In the second case, because all the lists have equal lengths, you get a 2D array of integers, which when flattened produces the seemingly odd result.

If you want to preserve behavior, you will need to make sure that what you pass in to `unique` is a 1D array of lists.

Closing this as a non-issue, but feel free to ask follow-up questions, either here, or in the mailing list, which is probably a better option to get help, as more people read that.

**Comment by jpreistad** [comment]
Thanks for your prompt feedback. This explains the behavior.
