### ISSUE TITLE
Regression in linalg.norm() using dtype=object

### ISSUE THREAD

**Issue by mgeier** [numpy/numpy#7575]
In NumPy 1.10.1, this works:

```python
>>> import numpy as np
>>> np.linalg.norm(np.array([np.array([0, 1]), 0, 0], dtype=object))
array([ 0.,  1.])
```

In NumPy 1.11.0, however, it raises an exception:

```python
>>> import numpy as np
>>> np.linalg.norm(np.array([np.array([0, 1]), 0, 0], dtype=object))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/linalg/linalg.py", line 2116, in norm
    x = x.astype(float)
ValueError: setting an array element with a sequence.
```

Probably this

```python
if not issubclass(x.dtype.type, inexact):
    x = x.astype(float)
```

should be changed to

```python
if not issubclass(x.dtype.type, (inexact, object_)):
    x = x.astype(float)
```

?

Does that make sense?

If yes, I can make a PR.

**Comment by pv** [comment]
The old result looks like undefined behavior --- indeed, np.linalg.norm 
for other orders than 1,2 does not give results for this input.

**Comment by mgeier** [comment]
Thanks for the quick response!

I don't see any undefined behavior here ... but I'm also unsure what you mean by "other orders than 1,2" ...

In NumPy 1.10.1 it seems to work also for higher dimensions, if you mean that:

```python
>>> np.linalg.norm(np.array([np.array([[0, 1], [-1, 0]]), 0, 0], dtype=object))
array([[ 0.,  1.],
       [ 1.,  0.]])
>>> np.linalg.norm(np.array([np.array([[0, 1], [-1, 0], [0, 0]]), np.array([[[0], [1], [5]]]), np.array([[[[[0, 1]]]]])], dtype=object))
array([[[[[ 0.        ,  1.41421356],
          [ 1.41421356,  1.41421356],
          [ 5.        ,  5.09901951]]]]])
```

I was using this (admittedly only up to 3 dimensions) for months, and it always worked great.
I think it is a great feature that most NumPy operations can also be applied to object arrays containing "normal" arrays with different (but compatible) shapes.

**Comment by pv** [comment]
By order, I mean the `ord` keyword.
.
How you are using it is not mentioned in the documentation, and I think 
that it worked previously is due to an implementation detail.

**Comment by mgeier** [comment]
I've submitted PR #7587, which fixes this issue and adds a regression test. CI passes.

@pv:
This may not be mentioned in the documentation, but it is quite obvious how it is supposed to work, it still works for all other NumPy functions and operators, it worked perfectly for `linalg.norm()` until it was broken in #7088 and it is *extremely* useful. It allows a very concise and readable implementation of operations on coordinate grids and vector fields, both of which are used extensively in the [Sound Field Synthesis Toolbox for Python](http://sfs.readthedocs.io/). With the regression discussed here, most of the functions of this library would have to be rewritten, needing significantly more code and leading to significantly less readability.

So *please*, let me help you fix this!

About your concerns regarding the `ord` keyword:
Any function arguments and even the specific algorithm the function `linalg.norm()` implements, is actually irrelevant to this issue. Using object arrays shall "only" broadcast all contained arrays to the same shape (if they are compatible) and then do whatever operation element-wise. This is how it works in all other NumPy functions and operators, I don't see a reason why it should suddenly stop working in `linalg.norm()`, while it continues to work everywhere else (but please don't disable it everywhere else!).

**Comment by pv** [comment]
Functions and operators on arrays typically apply the operation 
elementwise, eg. `sin(x) == np.array([y.sin() for y in x], 
dtype=object)`. When non-unary, arguments are broadcast and operation is 
applied elementwise. Unary functions in general do not broadcast stuff 
contained in an object array to the same shape.
.
The behavior of `norm` derives from the expression `sum(x**2)**(1/2)`. 
Reductions on object arrays call the corresponding Python operations 
repeatedly, which for arithmetic sum() calls `+` which broadcasts. 
max-norm on the other hand fails, apparently because Python `max(x,y)` 
unlike `+` does not act on arrays.
.
That norm(x, ord=y) for y!=1,2 previously raised errors indicates that 
the behavior with object arrays was likely not intentional. It is 
relevant to the discussion --- the behavior appears not designed, but a 
byproduct of the implementation, so it has to be understood whether it 
was desirable in the first place.

**Comment by charris** [comment]
I agree with @pv that using np.norm for object arrays is not well defined in general, especially for the case illustrated. The best argument I can see for fixing this is backwards compatibility, but that doesn't strongly appeal to me. Is there no better way to write the code that uses this? As is, it must be a bit obscure.

**Comment by pv** [comment]
The most robust thing to me would be to add a function along the lines of  `def norm(x): return sqrt(dot(x, x))` to the toolkit that requires this, and then import that instead of linalg.norm when these special objects are to be handled. The other numpy.linalg functions AFAIK don't work at all with object arrays.

OTOH, restoring bug-for-bug backward compatibility in linalg.norm probably does not cost much either, except in fixing in place semantics that seem a bit obscure to me, and function differently than some other Numpy unary functions on object arrays.

**Comment by mgeier** [comment]
Thanks @pv for the suggested work-around!
It looks quite simple, but do you know if that has potential performance implications compared to using `linalg.norm()` (using object arrays)?

**Comment by mgeier** [comment]
@charris wrote:

> Is there no better way to write the code that uses this? As is, it must be a bit obscure.

I think it is not at all obscure, but let me give an example. The function [point()](http://sfs.readthedocs.io/en/latest/index.html#sfs.mono.source.point) is supposed to calculate the sound pressure field according to this equation:

                      1  e^(-j w/c |x-x0|)
        G(x-x0, w) = --- -----------------
                     4pi      |x-x0|

This is implemented as follows:

```python
def point(omega, x0, grid, c=None):
    k = util.wavenumber(omega, c)  # k = omega/c
    x0 = util.asarray_1d(x0)  # the position of the point source
    grid = util.as_xyz_components(grid)  # an object array holding x/y/z arrays

    r = np.linalg.norm(grid - x0)
    return 1 / (4*np.pi) * np.exp(-1j * k * r) / r
```

The object arrays this is all about are created with the function [as_xyz_components()](http://sfs.readthedocs.io/en/latest/#sfs.util.as_xyz_components).

I think the code is very close to the original equation and therefore easy to read, isn't it?
I don't think the code can be made any simpler, but if you have a suggestion, I'd really like to hear it!

Note that the x/y/z arrays that comprise `grid` don't have to have the same shape. They can be whatever is returned from [meshgrid()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html) (including but not limited to the option `sparse=True`), but any of the components can also be scalars. They don't have to form a regular grid in any way, they can also define arbitrary point clouds.

This of course still works with @pv's work-around, but I feel it's strange that I have to manually re-implement a function that's available in NumPy already.
