### ISSUE TITLE
timedelta64 only accepts int timedeltas

### ISSUE THREAD

**Issue by nikolauspschuetz** [numpy/numpy#7617]
timedelta64 only accepts timedeltas of type int; it does not support timedeltas of other int types, such as int64.

**Comment by shoyer** [comment]
Yep, this is definitely a bug. To reproduce:
```
In [23]: np.timedelta64(np.int64(123), 'us')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-4c4ef02c5760> in <module>()
----> 1 np.timedelta64(np.int64(123), 'us')

ValueError: Could not convert object to NumPy timedelta
```

**Comment by yashmehrotra** [comment]
@shoyer Hi, I was looking into this bug and found that it works fine in python2 but throws an error in python3. The reason is, the function `PyInt_Check` is overrided in python3 , and it returns `false` when we check for raw integers.

The overrided `PyInt_Check`  is returning false, as it internally checks whether the value returns `true` for `PyLong_Check` [here](https://github.com/numpy/numpy/blob/925473229f9594046dc5e5a38d93103edd57f41b/numpy/core/include/numpy/npy_3kcompat.h#L37).

What do you suggest should be done here ?

P.S. : We also get the same error when we call `np.datetime` (Due to the same flow)

**Comment by shoyer** [comment]
It *looks* like `PyArray_IsScalar(object, Integer)` may be the right check for NumPy integer scalars, but I'm not 100% sure since the [documentation for that function](http://docs.scipy.org/doc/numpy/reference/c-api.array.html#c.PyArray_IsScalar) is rather terse.

@seberg How do you do type checks for integers in indexing operations?

**Comment by seberg** [comment]
I only check if it can cast with "same type" to intp IIRC. For scalars, I try `PyArray_PyIntAsIntp`, which I changed to raise an error when `operator.index` fails or it is a bool.

**Comment by seberg** [comment]
There is an unfortunate thing here, since intp is too small for datetime on some platforms, you cannot use the `operator.index` trick here I guess :(.
