### ISSUE TITLE
accessing undefined field raises incorrect Exception

### ISSUE THREAD

**Issue by andsok75** [numpy/numpy#7641]
In numpy 1.11.0, trying to access an undefined field of a structured array raises ValueError, rather than IndexError as in version 1.8

`a = np.empty(1,dtype=[('f','u4')])`
`a['g']`

yields

ValueError                                Traceback (most recent call last)
<ipython-input-14-fb4195a73db6> in <module>()
----> 1 a['g']

ValueError: no field of name g

Is that a feature? In any case, shouldn't it raise lookup error instead.

**Comment by charris** [comment]
IIRC, it was a deliberate change. Do you mean `KeyError`?

**Comment by andsok75** [comment]
I had a quick look at the recent release notes, but I could not find this change documented there. I'm using Python 2.7

**Comment by ahaldane** [comment]
Are you sure? I just checked out 1.8.0 and it gives ValueError. 1.8.3 and 1.9.3 also give ValueError.

I made a couple PRs starting in 1.10 which modified a lot of this code, but I made sure to leave it as ValueError to preserve compatibility. As you can see in #5636, for example, I wanted to change it to KeyError, however I held back because of backward compatibility. There are a number of unit tests that explicitly check for ValueError.

**Comment by andsok75** [comment]
Interesting. Perhaps there is a bug on our end, that only manifests with the older version 1.8.

**Comment by ahaldane** [comment]
Curious. What does `numpy.__version__` say? And what is the exact error message when you get the IndexError?

**Comment by david-jennings** [comment]
On numpy 1.11.0, the following code raises ValueError as expected, but with numpy 1.8.2 it raises IndexError:

`import numpy as np`
`print np.__version__`
`records = np.empty(5, dtype=[('a', 'f8')] )`
`for record in records:
    record['foo']`

yields

1.8.2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: invalid index

$ python --version
Python 2.7.6

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

**Comment by ahaldane** [comment]
Oh OK, that makes sense. What actually changed behavior is indexing a "structured scalar" rather than an array (very subtle, I know!). Indeed, in #5947 I changed it so structured scalars behave like structured arrays, so they give the same errors:
```
>>> arr = np.empty(5, dtype=[('a', 'f8')] )
>>> scalar = arr[0]
>>> arr['b']
ValueError: no field of name b
>>> scalar['b']  # this is what changed in 1.10
ValueError: no field of name b
```
I didn't think to put the change in the release notes. @charris is it worth putting a belated note in the 1.11 notes?

**Comment by seberg** [comment]
I think we can close this issue. That the exception is not ideal is also mentioned in gh-8519.
