### ISSUE TITLE
Bug: Different behaviour in numpy.int64 with oct and hex function.

### ISSUE THREAD

**Issue by Daetalus** [numpy/numpy#7642]
Consider this, in CPython:

``` python
>>> import numpy as np
>>> a = np.int64(0)
>>> oct(a)
'0L'
>>> a.__oct__()
'0'
>>> a.__hex__()
'0x0'
>>> hex(a)
'0x0L'
```

CPython get different result. CPython directly calls `tp_as_number->nb_hex` in `hex` function, and Pyston calls `cls.__hex__(v))`. So in Pyston, `hex(a)` will get `0x0`, like `a.__hex__()` in CPython.

What is the best way for handle it? Add a workaround in Pyston, or address it in numpy, let the two ways has same result? Thanks! @undingen @njsmith

**Comment by njsmith** [comment]
(Note also that this seems to be python 2 only, and that so far it's only been checked on 64-bit linux)

I'm sure that this inconsistency is not an intentional thing on numpy's part, so if you want to just fix it in numpy then that'd be fine with us.

On 64-bit linux, `0x0` actually seems like the correct result to me... `0x0L` is weird. On a 32-bit system, or on win64, then `0x0L` would make more sense.

**Comment by undingen** [comment]
just to add a little more info:
- ```hex(a)``` calls into cpythons/pystons ```long_hex()``` because it's set in ```tp_as_number->nb_hex```
- ```a.__hex__()``` calls into numpys ```gentype_hex()```/```array_hex()```

**Comment by undingen** [comment]
there is a similar problem for pow:
```python
>>> print np.int8(2) ** np.int8(-2)
0.25
>>> print np.int8(2).__pow__(np.int8(-2))
0
```
first one calls into `byte_power()` second into `gentype_power()`.
This makes pyston fail 3 tests when checking master.

**Comment by mattip** [comment]
Closing. While there still may be instances of `array_*` and `gentype_*` mixups, these particular ones are no longer relevant. Please open a new issue (or search for the existing ones) if the problem reoccurs
