### ISSUE TITLE
numpy 1.11 has different floordiv behavior on infinity and 0 comparing to numpy 1.10

### ISSUE THREAD

**Issue by will133** [numpy/numpy#7709]
I'm getting a different floordiv behavior when switching from 1.10 to 1.11.  Is this intentional?  It seems more inconsistent comparing to the normal division behavior:

```
# Old (numpy 1.10):
>>> import numpy
>>> x = numpy.float64(12.)
>>> x // 0.
inf
>>> x // numpy.inf
0.0
>>> x / 0.
inf
>>> x / numpy.inf
0.0

# New (numpy 1.11):
>>> import numpy
>>> x = numpy.float64(12.)
# Why nan?
>>> x // 0.
nan
# Why -0.0 when 12. is a positive number on a positive inf?
>>> x // numpy.inf
-0.0
>>> x / 0.
inf
>>> x / numpy.inf
0.0
```

This is on Linux 64-bit (numpy 1.11.0) from the conda environment with git_revision (4092a9e160cc247a4a45724579a0c829733688ca).

**Comment by charris** [comment]
Floor division is now computed using `divmod` so that it is compatible with `%`. `divmod` in turn is based around `fmod` as in python, indeed, the implementation is taken from python. See #7258. The nan is used so that the function can be used for arrays, whereas python raises a `ZeroDivisionError`. We could possibly adjust the behavior for numpy scalars to raise a error, but it is probably better to remain compatible with arrays and array scalars. The `-0.0` looks like a bug.

**Comment by mhvk** [comment]
Mathematically, I guess `divmod(12., 0.)` should be `inf, nan`, not `nan, nan`. In principle, since there is already a separate path for [`b=0`](https://github.com/charris/numpy/blob/542c88b8e10d4d7b9d80b31bb2f971b7e6d4cdb4/numpy/core/src/npymath/npy_math.c.src#L623), it would not take lead to any slowdown for the main path to assign a properly signed infinity.

On the sign: almost certainly related to testing for sign of ratio as [`(a / b) > 0`](https://github.com/charris/numpy/blob/542c88b8e10d4d7b9d80b31bb2f971b7e6d4cdb4/numpy/core/src/npymath/npy_math.c.src#L652).

**Comment by charris** [comment]
> I guess divmod(12., 0.) should be inf, nan, not nan, nan

I thought about that, but as I was replacing a `ZeroDivisionError`, nan, nan seemed more appropriate. It is an arguable point.

**Comment by njsmith** [comment]
> as I was replacing a `ZeroDivisionError`, nan seemed more appropriate

In regular float division we replace `ZeroDivisionError` with `inf`, though (as required by IEEE754):
```
In [1]: 1.0 / 0.0
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-1-42176c28e89e> in <module>()
----> 1 1.0 / 0.0

ZeroDivisionError: float division by zero

In [2]: np.divide(1.0, 0.0)
/home/njs/.user-python3.5-64bit/bin/ipython:1: RuntimeWarning: divide by zero encountered in true_divide
  #!/home/njs/.user-python3.5-64bit/bin/python3.5
Out[2]: inf
```

So I guess I agree that returning `inf` makes more sense, though I also agree that it isn't super clear...

**Comment by charris** [comment]
The argument for the other way round is that the divmod function determines the remainder first rather than doing a division. However, if `+/- inf` seems a better choice to most I'll happily change it before current behavior get too widespread. IIRC, the original changes broke some pandas tests which were fixed...

**Comment by charris** [comment]
@jreback Thoughts...

**Comment by jreback** [comment]
This is the behavior in pandas master, which I think matches. On integers we *do* return a ``NaN`` on ``//`` though.

```
In [1]: s = Series([12])

In [2]: s // 0
Out[2]: 
0    inf
dtype: float64

In [3]: s / np.inf
Out[3]: 
0    0.0
dtype: float64

In [4]: s / 0.
Out[4]: 
0    inf
dtype: float64

In [5]: s = Series([12.])

In [6]: s // 0
Out[6]: 
0   NaN
dtype: float64

In [7]: s / np.inf
Out[7]: 
0    0.0
dtype: float64

In [8]: s / np.inf
Out[8]: 
0    0.0
dtype: float64
```

**Comment by charris** [comment]
@jreback Any preference on how it ought to behave? Note that current behavior doesn't keep me up at nights, but if we want to change it, it should be before 1.12.

**Comment by seberg** [comment]
np.floor(np.inf) == np.inf`, so I think I have a slight tendency to prefer infinity as well. Not sure how it plays with divmod though.

**Comment by seberg** [comment]
This seems fixed now, giving `inf` for floor division and `inf+nan` for divmod.
