### ISSUE TITLE
"subclassing ndarray" example doesn't preserve superclass semantics

### ISSUE THREAD

**Issue by bcdarwin** [numpy/numpy#7745]
E.g., in the example [here](https://github.com/numpy/numpy/blob/master/numpy/doc/subclassing.py#L390):

```
>>> obj = RealisticInfoArray(np.arange(5), info='spam')
>>> obj.sum()
RealisticInfoArray(10)
```

which is a bit surprising since you'd expect a scalar ...

**Comment by birm** [comment]
It's due to the way __new__() is written in the example, using a [view](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.view.html). As a result, changing the view type will also change the type of the result.

If you're looking for workarounds, then I'd recommend having a custom sum (and max, min, etc) method that changes the view back to ndarray, and return something like  `obj.view(type=np.ndarray).sum()`. You could also just force-cast the result to int or float, but I don't think that would be a good option.

**Comment by mhvk** [comment]
@bcdarwin - it is not so obvious what one would want. E.g., in astropy's `Quantity` class, numbers have a unit, and summing an array of those should not loose that information.  (And indeed, we end up overriding quite a lot to ensure that scalars are turned into array scalars of `Quantity` type...)  Certainly, I'd personally would have been much happier if only array scalars existed!

**Comment by mattip** [comment]
Closing. Please reopen if there is more we can do to document or otherwise explain the bahaviour
