### ISSUE TITLE
enhancement: numpy.loadtxt( add skiprow param predicate)

### ISSUE THREAD

**Issue by mw66** [numpy/numpy#7761]
currently numpy.loadtxt take param: skiprows : int

http://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html
skiprows : int, optional
Skip the first skiprows lines; default: 0.

Sometimes the txt file contains bad record we can just throw away, so how about add a param:
skiprow : predicate

user can customize its behavior by passing a function / or lambda expr to skip some particular row.

**Comment by birm** [comment]
Do you think using filter() on nditer() on the array would be a good fit for this case?

**Comment by mingwugmail** [comment]
It's better to throw away garbage data at array creation time, rather than later after creation.

At least it saves operation & memory.

**Comment by birm** [comment]
okay, check our #7765, is that what you were expecting?

**Comment by mingwugmail** [comment]
Yes.

But line 988 should be:

if not skipfun(items):

https://github.com/numpy/numpy/pull/7765/commits/ad868036530e9e5da27092ab27840b12770a0322

**Comment by seberg** [comment]
Since this is so old, and you can pass a row iterator with the lines skipped (so the work-around is not super long and probably faster), I am going to close this feature request.

We can open a new one if it comes up again.  `pandas` actually supports a callable for `skiprows`, although it uses only the row number.
