### ISSUE TITLE
 NPY_FLOAT problem in PYTHON C API 

### ISSUE THREAD

**Issue by 1a1a11a** [numpy/numpy#7764]
I have the following code: 

    npy_intp dims[2] = { dd->xlength, dd->ylength };
    PyObject* ret_array = PyArray_EMPTY(2, dims, NPY_FLOAT, 0);

    int i, j;
    float* array, **matrix = dd->matrix;
    for (i=0; i<dd->ylength; i++){
        array = (float*) PyArray_GETPTR1((PyArrayObject *)ret_array, i);
        for (j=0; j<dd->xlength; j++)
            if (matrix[i][j])
                array[j] = matrix[i][j];
    }

When the float number is very small (print as 0.0000000 in C), sometimes after it is copied into numpy array, the number gets in python is extremely large (10^8 ~ 10^38), however, if I use NPY_DOUBLE and convert the float number to double, everything is solved. 
Is that a bug in numpy? Or maybe I got something wrong?

**Comment by jaimefrio** [comment]
When your float number in `matrix` is **exactly** zero, the `if` condition skips writing that value into the array, so you get whatever random garbage was in that memory address beforehand.

You should either use `PyArray_ZEROS` instead of `PyArray_EMPTY`, or removethe condition inside your loop.

Not a NumPy issue, so closing. If you have further questions this are best discussed in the mailing list.
