### ISSUE TITLE
r_ type change when empty tuple

### ISSUE THREAD

**Issue by kingjr** [numpy/numpy#7825]
I am using  numpy 1.11.0.

I'm not sure whether this is an intended feature or a bug but doing `np.r_[0, 1, ()]` makes an array of floats rather than an array of integers.

The typical use case of this empty tuple is when you have a `data` vars that varies in dimensionality: e.g. `data = np.zeros(10); np.r_[0, 1, data.shape[1:]]`I wouldn't have expected that I needed to add  `as_dtype(int)`.

**Comment by pslacerda** [comment]
In fact `()` is an array of floats.

It's because `numpy.array(())` returns an array of `dtype.float64`. There is no fix for this except to look other values types (e.g `1` of `numpy.r_(0, 1, ())`). But this breaks if `()` is the only value.

https://github.com/numpy/numpy/blob/master/numpy/lib/index_tricks.py#L313-L327

So looks like there is no solution.

**Comment by kingjr** [comment]
Ok, I'll close the issue then.
