### ISSUE TITLE
F2PY: Python callback to "raise" does not stop execution when in a fortran routine called by another fortran routine

### ISSUE THREAD

**Issue by MarkWieczorek** [numpy/numpy#7855]
I am trying to create a simple Fortran program that uses a callback statement to raise a Python exception and stop execution. This appears to work fine when Python calls directly the Fortran routine that contains the Python callback statement. However, if this Fortran routine is called by another Fortran routine, the Python callback to the raise exception doesn't seem to work.

Here are the two fortran routines in a file `pystop.f95`

```
subroutine routine1()
    external routine2
    print*, "In ROUTINE1"
    call routine2()
    print*, "Back to ROUTINE1. Shouldn't be here!"
end subroutine

subroutine routine2()
    external pystop
    print*, "In ROUTINE2"
    call pystop() ! This will be defined to raise a Python exception
    print*, "Called PYSTOP. Shouldn't be here!"
    return
end subroutine
```

and here is the corresponding Python signature file `pystop.pyf`

```
python module pystop
    interface
        subroutine routine1()
        end subroutine routine1

        subroutine routine2()
            intent(callback,hide) pystop
            external pystop
            call pystop()
        end subroutine routine2
    end interface 
end python module pystop
```

They are compiled using

```
python3 -m numpy.f2py -c pystop.pyf pystop.f95
```

In the ipython terminal, I import pystop, and define the callback function

```
In [1]: def f(): raise SystemExit

In [2]: import pystop

In [3]: pystop.pystop = f
```

Next, `routine2` works as expected

```
In [4]: pystop.routine2()
 In ROUTINE2
capi_return is NULL
Call-back cb_pystop_in_routine2__user__routines failed.
An exception has occurred, use %tb to see the full traceback.

SystemExit

To exit: use 'exit', 'quit', or Ctrl-D.
```

However, `routine1` does not stop when it encounters the raise expection!

```
In [5]: pystop.routine1()
 In ROUTINE1
 In ROUTINE2
capi_return is NULL
Call-back cb_pystop_in_routine2__user__routines failed.
 Called PYSTOP. Shouldn't be here!
 Back to ROUTINE1. Shouldn't be here!
An exception has occurred, use %tb to see the full traceback.

SystemExit

To exit: use 'exit', 'quit', or Ctrl-D.
```

This is a problem, as I need to program to stop executing when it hits the exception! Is this a bug? And is there anyway to get around this problem? (Also what does `Call-back cb_pystop_in_routine2__user__routines failed.` mean?)

**Comment by andymwood** [comment]
I've wasted a couple of days with exactly this problem, but I think I've solved it.

If you use the following for pystop.pyf you should find that execution ends in the correct place. No changes to pystop.f95 are necessary.

```
python module pystop__user__routines
    interface pystop_user_interface
        subroutine pystop()
            intent(callback,hide) pystop
        end subroutine pystop
    end interface pystop_user_interface
end python module pystop__user__routines
python module pystop
    interface
        subroutine routine1()
            use pystop__user__routines
            intent(callback,hide) :: pystop
            external pystop
        end subroutine routine1
        subroutine routine2()
            use pystop__user__routines
            intent(callback,hide) pystop
            external pystop
        end subroutine routine2
    end interface 
end python module pystop
```

It appears that if a Fortran subroutine can reference a callback function, then in the C code generated by f2py, there is a call to `setjmp` before the call to the Fortran subroutine. The callback function is called by a call to `PyObject_CallObject` which returns NULL if the callback raises an exception (hence 'capi_return is NULL' in your output). If that happens, then `longjmp` is called, which should return execution to the point specified by `setjmp`.

Since your original version of pystop.pyf did not specify `pystop` as an external callback within `routine1`, the C code had no call to `setjmp` before the call to `routine1`, so it couldn't call `longjmp` after the exception occurred. 

> Also what does Call-back cb_pystop_in_routine2__user__routines failed. mean?

It's just reporting that an exception was detected in the callback function.
