### ISSUE TITLE
Cannot create numpy array of strings consisting of null character

### ISSUE THREAD

**Issue by alexanderwhatley** [numpy/numpy#7858]
I want to create a numpy array whose elements are strings composed of the null character. However, numpy for some reason is setting these strings to the empty string:

>>> a = "\0" * 2
>>> np.repeat(a, 9)
array(['', '', '', '', '', '', '', '', ''],
      dtype='<U2')

A regular python list comprehension however works fine:

>>> [a for i in range(9)]
['\x00\x00', '\x00\x00', '\x00\x00', '\x00\x00', '\x00\x00', '\x00\x00', '\x00\x00', '\x00\x00', '\x00\x00']

**Comment by seberg** [comment]
Numpy strings are always zero padded, so this is impossible. You will have to use an object array (unless your string/bytes are all the same length anyway).
This is a known issue, to resolve it, however, new string types would be necessary.

**Comment by njsmith** [comment]
What "zero padded" means here is: in an array of numpy strings, all the strings have the same length (2, in your case, as shown by the `"<U2"` dtype), and are stored in the same number of bytes (because each entry in a numpy array has to be the same size to keep the array layout regular; otherwise indexing wouldn't know where to find things). But people would like to store different length strings into the same numpy array. So when storing a short string like `"a"` into an array where strings are, say, 3 characters long, numpy actually stores the string `"a\x00\x00"`. That is, it uses nul bytes to pad out the short string to match the length of the storage. And then when reading this string back, it sees the nul bytes at the end, strips them off, and returns `"a"`. So that works great for allowing strings of multiple lengths to be stored into the same array....

... Except for the problem that you hit: there's no way for numpy to tell the difference between nul bytes that are actually supposed to be at the end of the string, versus ones that were just added as padding. So your strings are getting stored as `"\x00\x00"`, but then when reading them out again numpy discards the "padding" and gives you `""`.
