### ISSUE TITLE
asarray should detect recursion to prevent infinite loops

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#7901]
I grant that this one is quite abusive, but bugs that lead to this problem _can_ happen:

```
$ ipython3 --pylab
Python 3.5.0 (default, Nov 20 2015, 16:20:41) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: TkAgg
Python are go!

In [1]: L = []

In [2]: L.append(L)

In [3]: L.append(L)

In [4]: X = asarray(L)
^C^C^\Quit (core dumped)
```

Ergo, numpy gets into an infinite loop using 100% CPU and hangs.  Interestingly, the following variant does not lead to the same problem:

```
$ ipython3 --pylab
Python 3.5.0 (default, Nov 20 2015, 16:20:41) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: TkAgg
Python are go!

In [1]: L = []

In [2]: L.append([L,L])

In [3]: X = asarray(L)

In [4]: print(X.ndim)
32 # huh?

In [6]: print(X)
# lots of ASCII-art
```

**Comment by seberg** [comment]
The second case makes sense, it tries to resolve the dimension (and type) of the ndarray, and gives up and returns an object array at 32, which is the maximum possible dimension of an array. The resulting shape is `(2, 1) * 16`.

Now to the first one, the resulting shape there should be (in some sense) shaped `(2,) * 32`, since it each list nesting has again two lists inside. It might not be surprising that it runs into issues, but it should really just throw a MemoryError after a short while. Might be interesting to see where it hangs, could also be some other small bug not directly related to this.

In any case, I think we might want to change it for things to just error out when it hits dimension 32, if you want to take a look at it that would be even cooler. Though I have to say that your construct is rather weird....

**Comment by eric-wieser** [comment]
In all cases, numpy is doing a depth-first search into each list element (capped at depth 32) to find the shape of the array. The first example would eventually complete, but only after iterating over 2**32 objects. The second example iterates over a much smaller 2**16, so completes fairly quickly.

Even if we fix this for recursive objects, we're still screwed for objects like:
```python
class InfiniteArray(object):
    def __len__(self):
        return 2
    def __getitem__(self, i):
        return InfiniteArray()  # not even an identity check will save you here

np.array(InfiniteArray())  # uh oh
```

**Comment by gerritholl** [comment]
@eric-wieser I assume that in your comment, 2**32** should read `2**32` and **2**16 should read `2**16`, correct?

**Comment by eric-wieser** [comment]
Fixed, good spot

**Comment by seberg** [comment]
I don't think we should do anything about the recursion, so closing the issue.

(A potential improvement may be to check for interrupts occasionally and if we ever cap at 32-dims we might "fix" this since we do a depth first search).
