### ISSUE TITLE
Segfault in argsort with strangely ordered objects

### ISSUE THREAD

**Issue by dsm054** [numpy/numpy#7934]
Tracked down a segfault in pandas to this:

```
>>> import sys, numpy as np
>>> sys.version
'3.5.2 (default, Jul  5 2016, 12:43:10) \n[GCC 5.4.0 20160609]'
>>> np.__version__
'1.11.1'
>>> class Boom:
...     def __lt__(self, other): return True
... 
>>> np.array([Boom()]*16).argsort()
array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])
>>> np.array([Boom()]*17).argsort()
Segmentation fault (core dumped)
```

It's easy enough to fix on the pandas side by not creating an object which is less than itself in the first place, and I'll make a PR to fix that.  But ISTM we should be able to avoid a segfault during a sort even if the comparisons are inconsistent.

**Comment by charris** [comment]
The quicksort falls back on insertion sort for small arrays, which is why the 16 element array doesn't bomb. For larger arrays it depends on sentinel values and they don't work in this case. I suppose we could check array bounds in the object case, which would slow things down, but perhaps not to a fatal extent because, objects. What I'd really like to do is set the user's computer on fire before the segfault. It would be the traditional solution demonstrated in many Hollywood simulations.

**Comment by charris** [comment]
Mergesort and heapsort seem OK with this.
