### ISSUE TITLE
numpy.matrix extraction / indexing returns scalar instead of array

### ISSUE THREAD

**Issue by olcc** [numpy/numpy#7957]
Hello, 
In the following code I expect the extraction to return `m11` as an array (just like `a11`).
```
import numpy
A = numpy.array([[1,2],[3,4]])
M = numpy.matrix(A)

a11 = A[...,1,1]    # -> array(4)   -> That's fine with me
m11 = M[...,1,1]    # -> 4          -> Gni??? Why not the same as above?
```

**Comment by mhvk** [comment]
Matrix is intrinsically 2-dimensional, so your `...` gets ignored (see https://github.com/numpy/numpy/blob/master/numpy/matrixlib/defmatrix.py#L314); in contrast, an `ndarray` can have other dimensions, and the `...` is seen to indicate that you really want a slice rather than an index.

Aside: there seems to be some consensus that one should not use `matrix` at all, since it is rather limited. Instead, store the matrices in arrays and use `np.matmul` (or the `@` operator on python >=3.5) for matrix multiplication.

**Comment by seberg** [comment]
@mhvk there is more to i. Its a subclassing issue. The matrix class does nonsense, it has this `_getitem` flag, instead of just passing a base class view into `__getitem__` now `np.ndarray.__getitem__` returns the scalar, the matrix class does then not discriminate between array scalar and scalar array (just checks 0d).

So far so good, you could fix that, even remove that `_getitem` flag, and instead also do the clean thing and define `__setitem__` best. However, things will probably always be problematic in the case where the matrix is of object type (in which case it is right now also buggy). Frankly, I don't see how any subclass could handle that case correctly currently (short of checking for the ellipsis -- and in some cases maybe array indices).

**Comment by olcc** [comment]
I agree with your reasoning. For the moment I'll work around the problem by casting to ndarray (it's an old code that uses matrix a lot)
