### ISSUE TITLE
Error when offsets in construction of dtype are given as int32

### ISSUE THREAD

**Issue by anton-d** [numpy/numpy#8059]
When one constructs a dtype and gives the offsets as int32 (or int16), a subsequent use of the dtype leads to a crash.

The following example shows the construction of two dtypes: one with offsets as a list of python int's, the socond as a list of int32's.

```python
offsets1 = [0]
offsets2 = [np.int32(o) for o in offsets1]

dtype1 = np.dtype(dict(
    names=['f0'],
    itemsize=4,
    offsets=offsets1,
    formats=['u4']
))

dtype2 = np.dtype(dict(
    names=['f0'],
    itemsize=4,
    offsets=offsets2,
    formats=['u4']
))
```

When using the first dtype the result is as expected:

```python
>>> np.fromstring(b"\x00"*4, dtype1, count=1)
array([(0,)], 
      dtype=[('f0', '<u4')])
```

Using the second dtype leads to a crash:

```python
>>> np.fromstring(b"\x00"*4, dtype2, count=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/numeric.py", line 1807, in array_repr
    ', ', "array(")
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 447, in array2string
    separator, prefix, formatter=formatter)
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 325, in _array2string
    _summaryEdgeItems, summary_insert)[:-1]
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 496, in _formatArray
    word = format_function(a[-1])
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 235, in repr_format
    return repr(x)
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/numeric.py", line 1869, in array_str
    return array2string(a, max_line_width, precision, suppress_small, ' ', "", str)
  File "/home/anton/anaconda2/envs/py3/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 438, in array2string
    x = a.item()
SystemError: <built-in method item of numpy.ndarray object at 0x7f5aab26d940> returned NULL without setting an error
```

Python Version: 3.5.2 |Anaconda 4.1.1 (64-bit)
Numpy Version: 1.11.1

**Comment by pslacerda** [comment]
Worked as expected here
Python Version: 3.4.2 | Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
Numpy Version: 1.12.0.dev0+3a27323

**Comment by charris** [comment]
I still see it here. 
```
In [1]: np.__version__
Out[1]: '1.12.0.dev0+c90d7c9'

In [2]: offsets2 = [np.int32(o) for o in [0]]

In [3]: dtype2 = np.dtype(dict(
    names=['f0'],
    itemsize=4,
    offsets=offsets2,
    formats=['u4']
))

In [4]: np.fromstring(b"\x00"*4, dtype2, count=1)
Out[4]: <repr(<numpy.ndarray at 0x7f8c75109990>) failed: SystemError: error return without exception set>
```

**Comment by ahaldane** [comment]
I see the bug, it's in [unpack_fields](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/common.c#L870). I sort of introduced it by using `unpack_fields` in more places, though I think the bug was pre-existing in that function.

One possible possible fix is to cast `off` to python int using `Py_TYPE(off)->tp_as_number->nb_int(off)` beforehand, but the weird thing about that is that then we are allowing floats and strings other numerical objects to be in the `offset` position in a structured dtype.

So maybe it would be nice to just disallow anything but python ints as offsets. The place would be in `_convert_from_dict`, which currently seems to allow *any* value to be used as an offset

    >>> d = np.dtype({'names': ['A'], 'formats': ['i4'], 'offsets': ['ASD']})

After writing this, I think I'll try the 2nd solution, to convert to int at the moment of dtype creation.

**Comment by charris** [comment]
Maybe use the index conversion?
