### ISSUE TITLE
numpy.mean precission problem in float16

### ISSUE THREAD

**Issue by nouiz** [numpy/numpy#8217]
In the deep learning community, there is a big push to use float16 much more frequently. Theano is working in that direction. One problem we have when converting a script that do computation in float32 to do computation in float16 is on the NumPy side. After doing much computation in Theano, user will frequently accumulate information in a vector/list of scalar that is not in float16 and call numpy.mean on it. We have many examples doing that.

The final result fit in a float16 result, the problem is the way numpy.mean work:  it use the input dtype for the call to numpy.sum and this sum overflow frequently in float16. If NumPy would force the sum output in float32 when the inputs is in float16, then do the division in float32 and cast the result in float16, there won't be this problem. This is what Theano does to help make using float16 easier.

The user can add the dtype parameter to numpy.mean to work around that. But this is a complication that isn't necessary I think.

What do you think about having a PR on NumPy that implement this small change? I can do it, but I'm not sure you would accept such changes that increase precision during the computation temporaries. 

It is @abergeron that discovered this problem.

**Comment by charris** [comment]
I'm not opposed. Why the push to operate with float16?

**Comment by juliantaylor** [comment]
I am very confused in the use of float16, isn't that more a storage format?
Is it due to memory usage?
float16 is very very limited in accuracy and range, you have to be extremely careful when using it. On regular computers it is also not faster, probably even slower as it needs converting to float the cpu can handle on every operation.

Anyhow, for float16 the current mean algorithm is probably already not enough, numpy sums it and then divides which is sometimes already not accurate enough for float32.
A better approach might be to accumulate the mean via provisional means `m_k = (x_i - m_k-1) / (i+1)`

**Comment by juliantaylor** [comment]
hm sum is already accumulating float16 in a float32 internally and we do have output dtype changing for integers and bool in mean, so there shouldn't really be an issue with implicitly doing float16 mean in float32.
Though casting back to float16 would be new somewhat unusual behaviour.

**Comment by abergeron** [comment]
@juliantaylor 
The push for float16 is mostly for computations on GPUs.  And even then we usually do the actual computations in float32 and just use float16 as a storage format.  But since memory on GPUs is limited, it helps.  It also helps limiting the memory bandwith.  And for deep learning, the precision is usually good enough, with most algorithms working without modifications.

**Comment by nouiz** [comment]
I did a PR that do not change the output dtype:

https://github.com/numpy/numpy/pull/8222
