### ISSUE TITLE
nanpercentile returns 0-d array instead of scalar with axis=0

### ISSUE THREAD

**Issue by jorisvandenbossche** [numpy/numpy#8220]
Consider the following examples:

```
In [1]: a = np.arange(6)

In [2]: np.percentile(a, 50)
Out[2]: 2.5

In [3]: np.percentile(a, 50, axis=0)
Out[3]: 2.5

In [4]: np.nanpercentile(a, 50)
Out[4]: 2.5

In [5]: np.nanpercentile(a, 50, axis=0)
Out[5]: array(2.5)

In [6]: np.__version__
Out[6]: '1.11.2'
```

All return a scalar, except for `nanpercentile` when `axis=0` is specified.

**Comment by charris** [comment]
Still present in `1.12.0.dev0+a5db940`

**Comment by jorisvandenbossche** [comment]
I think it boils down to the usage of `apply_along_axis`:

```
In [24]: np.apply_along_axis(np.percentile, 0, a, 50)
Out[24]: array(2.5)
```

This returns a 0-d array. But for `apply_along_axis`, this is maybe the expected result? 
If so, it can easily checked for in `nanpercentile` (something like `if result.ndim == 0: result = result.item()`), but not sure if that would be an appropriate solution

**Comment by foice** [comment]
On similar situations I get that the percentile is computed to be identically zero for all the components of the axis. It seems to be happening for large arrays only.

``` np.apply_along_axis(np.percentile, 0, T2T_cij_lsi200_600histo, 67) ```

     array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

whereas if I ask for the mean I get some numbers (hopefully correct!).

**Comment by foice** [comment]
It's a different thing. Sorry for the pollution. I was under the impression my array had only few hundred components, whereas it has 1M almost all at the initialization value (done with `np.zero`). When applying np.percentile over the whole data it takes these values from the initialization and,  since they are 1M, win over the non-zero component, making the percentile zero. It is strange however that  `np.percentile` and `np.mean` do not behave the same with my array of mostly `np.zero` values.

**Comment by juliantaylor** [comment]
`np.percentile` and `np.mean` are two very different things, they should not produce the same result except in rather specific situations. If the documentation of `percentile` is not clear enough on what it does please open a new issue.

**Comment by foice** [comment]
I think I know the difference (in mathematics) between the mean and the percentile. In both cases if I enter an array made of zeroes, I'd say the result should be zero. In my case the array had 600 values between 0 and 1 and 1 milion zero values. So up to numerical rounding both should give zero (both mean and percentile). Instead np.mean for some reason ignores the values that are zero (zero because of the initialization of the array). Is this how np is supposed to work?

**Comment by pv** [comment]
np.mean certainly does not work that way. Please move the discussion to 
stackoverflow if you need clarification on this.
