### ISSUE TITLE
Crash using NPY_OWNDATA on Windows under Cython

### ISSUE THREAD

**Issue by nonhermitian** [numpy/numpy#8253]
I have tried building a NumPy array from a c-pointer using Cython and the example found at [http://stackoverflow.com/questions/23872946/force-numpy-ndarray-to-take-ownership-of-its-memory-in-cython](http://stackoverflow.com/questions/23872946/force-numpy-ndarray-to-take-ownership-of-its-memory-in-cython):

```python
from libc.stdlib cimport calloc
import numpy as np
cimport numpy as np

np.import_array()

cdef extern from "numpy/arrayobject.h":
    void PyArray_ENABLEFLAGS(np.ndarray arr, int flags)

cdef data_to_numpy_array_with_spec(void * ptr, np.npy_intp N, int t):
    cdef np.ndarray[int, ndim=1] arr = np.PyArray_SimpleNewFromData(1, &N, t, ptr)
    PyArray_ENABLEFLAGS(arr, np.NPY_OWNDATA) #Here is the problem line
    return arr

def test():
    N = 10
    cdef int * data = <int *>calloc(N, sizeof(int))
    arr = data_to_numpy_array_with_spec(data, N, np.NPY_INT32)
    return arr
```

When calling with NPY_OWN_DATA on Windows, Python will crash when the resulting array object is destroyed. Removing the offending line cures the problem, but then the underlying memory is not released.  The same code works without error on Linux and OSX.  This was tested on both Windows and Linux using NumPy 1.11.1 (I don't recall the NumPy version used on OSX).

**Comment by njsmith** [comment]
What happens if instead of using `calloc` to allocate the memory, you use `PyDataMem_NEW_ZEROED`? (it has the same signature as `calloc`)

**Comment by nonhermitian** [comment]
You solution does indeed fix the problem.  Is there some reason why calling ```PyDataMem_NEW_ZEROED``` works but not a direct call to ```calloc``` under Windows?

**Comment by njsmith** [comment]
Oh, it does do a direct call to `calloc`. The problem is that because of how the Windows C runtime works, different libraries (for example: numpy and your code) might end up using different `calloc` implementations even though they each just call `calloc`. And memory that's allocated by one version of `calloc` can only be free'd by the matching version of `free`...

Basically, I don't think there's anything we can do about this: the solution is that if you want to take advantage of `NPY_OWNDATA` then you have to make sure that you allocate the memory using the same allocator that numpy's using, and that's why it conveniently exposes that allocator with the `PyDataMem_*` APIs.
