### ISSUE TITLE
numpy.ma.array did not create "Masked data", and "Mask" arrays on multi axes, even though it show blank/masked data

### ISSUE THREAD

**Issue by LSW1980** [numpy/numpy#8295]
```python
face = scipy.misc.face()
random_mask = numpy.random.randint(0, 2, size=face.shape)
masked_array = numpy.ma.array(face, mask=random_mask) # No "Masked data", and "Mask" arrays created
plt.imshow(masked_array)  #Did not show any change even though having missing/masked data!
                                          #Suspect may have to do with multi axes, size ==> (768, 1024, 3) in this case.
```

**Comment by eric-wieser** [comment]
I think the problem here is that `matplotlib` does not recognize masked arrays in `imshow` - you should consider reporting the problem there instead. As you say, the image shows no sign of being masked when it is plotted.

Bear in mind that what you're doing here is masking RGB components separately - it's not clear what that means.

You can get a reasonable outcome with
```
mask_2d = masked_array.mask.any(axis=-1, keepdims=True)
plt.imshow(np.where(mask_2d, np.nan, masked_array / 255))
```
![image](https://user-images.githubusercontent.com/425260/30094357-add7278e-9280-11e7-901a-555ec5b0797b.png)
