### ISSUE TITLE
why is int 32 bit on my 64 bit system?

### ISSUE THREAD

**Issue by simonm3** [numpy/numpy#8310]
I am running windows 10 64 bit. The int normally holds a 64 bit value. I have found an issue using sklearn which returned a negative number due to overflow unless I wrapped the result in np.int64(x)

I also note that np.iinfo reports an int variable as 32 bit even when it holds a 64 bit value.

c = np.int(sys.maxsize)
c, type(c), np.iinfo(c), np.finfo(float)

(9223372036854775807,
 int,
 iinfo(min=-2147483648, max=2147483647, dtype=int32),
 finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64))

**Comment by seberg** [comment]
python's int tends is/was long. Which is why it is also a long in numpy. One might think about changing it in Python 3, but I guess it gets trickier over time. Now a long in windows 64bits is 32bits. IT is quite simply a bug in sklearn which *should never use int for indexing purposes, etc.*. There is `np.intp` for that specific reason.

**Comment by MSeifert04** [comment]
`np.int_` or `int` as `dtype` is defined as `long`. The `long` type is however just 4bit on Windows (even 64 bit): https://msdn.microsoft.com/en-us/library/9c3yd98k.aspx

**Comment by seberg** [comment]
I suppose its a bug what np.iinfo reports, but then you are throwing a python integer into it, which it probably does not know what to do with

**Comment by seberg** [comment]
If you look at the code, its not wonder. Since it just makes a "default int-type" from python ints (which it should probably not do and instead raise an error), but the real problem is still not using `np.intp` most likely.
