### ISSUE TITLE
np.uint64 + np.int64 = np.float64

### ISSUE THREAD

**Issue by acdr000** [numpy/numpy#8333]
This is with Python 2.7.10, Numpy 1.9.2, Scipy 0.16.0:
```
>>> a = np.uint64(15000000000000000)
>>> b = np.int64(1)
>>> c = a + b
>>> type(c)
<type 'numpy.float64'>
```
I get that it's ambiguous what data type `int + uint` should return, but I figure it should either be `int` or `uint`. `float` should be out of the question entirely.

Edit: This behaviour also occurs with smaller numbers. I just used a very large number to show where this can actually be a major problem: `a + 1 == a` returns `True`!

**Comment by shoyer** [comment]
This was an intentional choice. NumPy has no integer type that can hold all uint64 and int64 values, so float64 was chosen by design.

Also, by design, this behavior (like most of NumPy) does not depend on array values, only dtypes. Otherwise, this could lead to unpredictable behavior when working with large arrays.

If you're not happy with NumPy's default casting rules, you should cast inputs yourself to a common dtype.

**Comment by acdr000** [comment]
> This was an intentional choice. NumPy has no integer type that can hold all uint64 and int64 values, so float64 was chosen by design.

If it's because of the risk of over/underflowing, then `uint + uint` and `int + int` should also return `float`s. (After all, `np.uint64(18446744073709551615) + np.uint(1)` also doesn't fit into a `uint`.) When you try this, though, you just get an overflow warning. I don't see why `uint + int` can't just return a `uint` or `int` (not sure which, I admit), and raise an overflow/underflow warning when appropriate.

**Comment by shoyer** [comment]
You are welcome to bring this up on the mailing list (
numpy-discussion@scipy.org) if you want to hear more perspectives, but
given how long this behavior has existed I think it would be very difficult
to change now.

**Comment by charris** [comment]
Yes, this behavior is nasty. I would probably have kept the C conversion rules for integers -- signed + unsigned of same rank converts the signed to unsigned -- but given the long history of the float conversion and the upcasts for lesser types,  it is probably too late to change. I say probably, because if anyone can think of a good solution I'd go for it. But I can't think of a good solution myself.
