### ISSUE TITLE
suggestion: add issorted function for checking if array is sorted

### ISSUE THREAD

**Issue by talkaminker** [numpy/numpy#8392]
matlab has it: [issorted](https://www.mathworks.com/help/matlab/ref/issorted.html)
It is often used, easy to implement but a fast implementation is hard to do without cython or numba.
having a builtin function for it will be nice.

**Comment by jaimefrio** [comment]
What improvement over `np.all(a[:-1] <= a[1:])` do you expect from such a function?

**Comment by talkaminker** [comment]
two improvement:
1) a function is simpler than coming up with an implementation on your own.
2) speed: you solution creates a temporary array which is costy.
comparing your solution with a simple numba jitted function shows that for sorted arrays the numba function is 3 times as fast. for not sorted arrays it can be much faster since a loop can exit in the middle.

**Comment by jaimefrio** [comment]
My thoughts about this in more detail:

 1. If you want to move this forward, it will have to be discussed in the mailing list, as it is a change to the API. My impression is that the general feeling is that the namespace is already overcrowded, so new functions have to bring a lot to earn a place at the table.

 2. Because of that overcrowding, new functions are not found easily: I'm not sure that a function name would be more discoverable than asking (and answering with the above code snippet): "How do I determine if a numpy array is sorted?" in StackOverflow.

 3. NumPy creates intermediate arrays all of the time. That's not an excuse for sloppy disregard for efficiency, but it's also not that much of a big deal.

 4. To realize all of the benefits of an implementation like you propose would probably require writing templated C code for all default dtypes. People that can write, review, or later modify such code are a scarce resource, so the associated maintenance cost is pretty high.

Because of all of the above I'm -1 on this, but please, don't let my lack of enthusiasm discourage you from pursuing this by proposing it on the mailing list.

**Comment by jaimefrio** [comment]
I'm going to close this for now, mostly to help keep the issue tracker manageable. Will be happy to reopen it if you decide to post this same request to the mailing list and the collective wisdom decides this is a worthwhile investment.

Thanks for taking the time to report this and engage in the discussion, it is much appreciated even if the outcome is a "won't fix" decision.

**Comment by jgehrcke** [comment]
For the record, https://stackoverflow.com/a/47004533/145400 and https://stackoverflow.com/a/47004507/145400. These answers mention `np.diff(a)>=0` (highest vote, also claims "numpy solutions are all O(n)") and `np.all(a[:-1] <= a[1:])` (not really discussed). I think the answers might need some discussion, if anyone is interested.

**Comment by pxcandeias** [comment]
If this is the recommended solution to check for strictly increasing values in an array (or a sorted array in general), then I recommend to mention that in the `numpy.interp` documentation page:

https://numpy.org/doc/stable/reference/generated/numpy.interp.html

**Comment by jorenham** [comment]
A simple trick like `a[0] <= a[-1] and np.all(a[:-1] <= a[1:])` will effectively half the average runtime if your input are random arrays.
