### ISSUE TITLE
Virus detected when attempting to download  numpy-1.11.3-cp35-none-win32.whl

### ISSUE THREAD

**Issue by Gonadar** [numpy/numpy#8397]
When attempting to download the latest numpy windows binary, it is quarantined due to the presence of Trojan:Win32/Spursint.A!cl.  This should be removed, and root caused as to how this could have made it into the package.

**Comment by njsmith** [comment]
This is almost certainly a false positive (i.e., your virus scanner making stuff up). I don't think I've ever heard of a virus warning that *wasn't* a false positive...

What virus scanner are you using?

**Comment by njsmith** [comment]
Also, what is "the latest numpy windows binary"? What file from what URL?

**Comment by Gonadar** [comment]
The virus scanner is Windows Defender (out of the box default) of Windows 10.  Address is: https://pypi.python.org/packages/28/49/c6c6a85e0a10d5ddc9db7e961c213b821d15a3f5c9f726f4354845d790fc/numpy-1.11.3-cp35-none-win32.whl#md5=f8b64f46cc0e9a3fc877f24efd5e3b7c

**Comment by pv** [comment]
I don't see anything:
https://www.virustotal.com/en/file/ab2af03dabecb97de27badfa944c56d799774a1fa975d52083197bb81858b742/analysis/1482138245/

**Comment by pv** [comment]
You should check if the md5sum of the file you downloaded matches 
f8b64f46cc0e9a3fc877f24efd5e3b7c --- if not, the infection most likely 
occurred on your machine.
.
import hashlib; text = open("numpy-1.11.3-cp35-none-win32.whl", 
"rb").read(); print(hashlib.md5(text).hexdigest())

**Comment by Gonadar** [comment]
Hmm, interesting, the sums match up:

>> wget --no-check-certificate https://pypi.python.org/packages/28/49/c6c6a85e0a10d5ddc9db7e961c213b821d15a3f5c9f726f4354845d790fc/numpy-1.11.3-cp35-none-win32.whl#md5=f8b64f46cc0e9a3fc877f24efd5e3b7c
>> md5sum numpy-1.11.3-cp35-none-win32.whl

f8b64f46cc0e9a3fc877f24efd5e3b7c *numpy-1.11.3-cp35-none-win32.whl

Could there be some problem with Windows Defender?

**Comment by pv** [comment]
False positive is likely if other products don't recognize it.
.
Also:
https://www.metadefender.com/#!/results/file/YTE2MTIxOVNKYkdhZExyVmVISmZmcE9McjR4/extracted/files

**Comment by njsmith** [comment]
Here are some other harmless packages that Windows Defender has blocked because of "Trojan:Win32/Spursint.A!cl":
* https://github.com/google/material-design-lite/issues/1754
* https://github.com/explodybits/hookr-plugin/issues/9

This is almost certainly a bug in Windows Defender. (It's very common for anti-virus tools to mess up like this.) There isn't really anything we can do about it.

@Gonadar: I'd suggest filing a report with Microsoft here: https://www.microsoft.com/en-us/security/portal/submission/submit.aspx

(For future reference, that's the link for users to report false positives; there's also [this link](https://www.microsoft.com/en-us/security/portal/developer/ContactUS.aspx) for developers who want to report a false positive in their own package, but it requires the developers to reproduce the issue first, so not very helpful when none of us use windows...)

**Comment by Gonadar** [comment]
Got it, okay will do -- I'll fire off a report to Microsoft so that this false positive can be avoided in the future.  Thanks very much for looking into this.
