### ISSUE TITLE
func call: numpy array column selection passed by value?

### ISSUE THREAD

**Issue by mingwugmail** [numpy/numpy#8425]
```
>>> def foo(x): x += 1
... 
>>> a = np.arange(10, dtype=np.float64).reshape((2,5))
>>> a
array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])
>>> a[:, [2, 3]]
array([[ 2.,  3.],
       [ 7.,  8.]])
>>> a[:, [2, 3]] += 1
>>> a
array([[ 0.,  1.,  3.,  4.,  4.],
       [ 5.,  6.,  8.,  9.,  9.]])
```
as expected, but
```
>>> foo(a[:, [2, 3]])
>>> a
array([[ 0.,  1.,  3.,  4.,  4.],
       [ 5.,  6.,  8.,  9.,  9.]])
```
nothing changed.
```
>>> foo(a[:, [2]])
>>> a
array([[ 0.,  1.,  3.,  4.,  4.],
       [ 5.,  6.,  8.,  9.,  9.]])
```
nothing changed.
```
>>> foo(a[:, 2])
>>> a
array([[ 0.,  1.,  4.,  4.,  4.],
       [ 5.,  6.,  9.,  9.,  9.]])
```
this one works as expected.

why foo(a[:, 2]) and foo(a[:, [2]]) one call by ref, the other call by value?

Is there any numpy documentation about this?

**Comment by charris** [comment]
`def foo(x): x += 1` doesn't return the result.

**Comment by mingwugmail** [comment]
"why foo(a[:, 2]) and foo(a[:, [2]]): one call by ref, the other call by value?"

That's the question.

**Comment by charris** [comment]
Hmm, apparently the slice means different things depending on whether or not it is on the left side of an assigment.
```
In [40]: b = a[:, [2, 3]]

In [41]: b
Out[41]: 
array([[ 2.,  3.],
       [ 7.,  8.]])

In [42]: foo(b)

In [43]: b
Out[43]: 
array([[ 3.,  4.],
       [ 8.,  9.]])
```
I find that odd. @seberg ?

**Comment by charris** [comment]
What is stranger is that `b` doesn't own its data, so it should not be a copy. It is also F contiguous, which doesn't make sense. OTOH, `In [7]: b = a[:, 2:4]` works as expected. So it is something related to the fancy indexing, a subject I avoid...

**Comment by seberg** [comment]
Nothing odd here, `a[:, [2]]` is advanced indexing and thus returns a copy and not a view. The fact that it does not own its own data is some internal transposing happening in advanced indexing and could probably be avoided if there is a good reason for it.

**Comment by seberg** [comment]
Or maybe it is odd, I wouldn't know ;). to me it is all exactly what is expected...

**Comment by seberg** [comment]
Disregarding that the documentation can probably use a lot of improvements, it does say here: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#advanced-indexing that a copy is made so that the function call would modify the copy. I am sure all numpy tutorials should also cover this fact about advanced (or call it fancy if you like) indexing.

The `a[..., [2]] += 3` line is a single operation, that python translates to:
```
tmp = a[..., [2]] + 3
a[..., [2]] = tmp
```
doing it inside the function call makes it not a single operation anymore, but instead:
```
tmp = a[..., [2]]
# func(tmp) called now:
tmp += 3
```
note that only `tmp` is modified, and `a` is not modified explicitly there. Do to the copy logic of advanced indexing, modifying `tmp` does not work in that case.

Feel free to keep discussing, but the non-modification itself is very much expected and necessary.
