### ISSUE TITLE
Incorrect error message when setting element of unmasked array to ma.masked

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#8461]
When setting an element of an unmasked array to `ma.masked`, the error message is `ValueError: setting an array element with a sequence.`.  This error message is confusing or outright wrong.  The same error message happens in other contexts, for example, if warning are turned to errors then `UserWarning: converting masked element to nan` becomes the same error message.

```
In [301]: A = arange(5)

In [303]: A[0] = ma.masked
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-303-286b16dc7aa0> in <module>()
----> 1 A[0] = ma.masked

ValueError: setting an array element with a sequence.
```

**Comment by eric-wieser** [comment]
This is super weird. Ultimately, the problem is that `->f->setitem` on numeric types does not know how to handle 0d arrays. The bug doesn't exist for string types, because that `setitem` handler _does_ know how to deal with it.

It's not clear to me how we end up calling `setitem` here at all - there's something special going on with `masked` that I can't reproduce with a plain 0d array

**Comment by eric-wieser** [comment]
It gets weirder:

```
>>> a = np.zeros(2)
>>> a[0] = np.ma.masked
ValueError: setting an array element with a sequence.
>>> b = np.zeros((2, 2))
>>> b[0] = np.ma.masked
UserWarning: Warning: converting a masked element to nan.
```
