### ISSUE TITLE
SELinux prevents "import numpy"

### ISSUE THREAD

**Issue by avipersin** [numpy/numpy#8462]
Python 3.4
numpy 1.12.0rc2

We attempted to perform an upgrade of numpy from version 1.10.4 to the latest version using "pip install numpy --upgrade". The upgrade completed without any errors, as expected.

When attempting to "import numpy" from a script that runs on the web server, SELinux complains.

The traceback points to numpy/core/__init__.py line 14:  "from . import multiarray" and then outputs:
```
ImportError: libopenblasp-r0-39a31c03.2.18.so: cannot open shared object file: No such file or directory
      args = ('libopenblasp-r0-39a31c03.2.18.so: cannot open shared object file: No such file or directory',)
      msg = 'libopenblasp-r0-39a31c03.2.18.so: cannot open shared object file: No such file or directory'
      name = 'multiarray'
      path = '/usr/local/lib/python3.4/site-packages/numpy/core/multiarray.cpython-34m.so'
      with_traceback = <built-in method with_traceback of ImportError object> 
```
Looking into this further we found that "libopenblasp-r0-39a31c03.2.18.so" did exist. The only thing we can think of was that the ".so" file was located in a hidden folder. I forget the name of the folder but it started with a ".". Perhaps SELinux prevents access to hidden folders and causes a "libopenblasp-r0-39a31c03.2.18.so" file not found error?  

This hidden directory did not exist in our previous numpy 1.10.4 installation which we reverted back to.

Maybe a connection to https://github.com/numpy/numpy/issues/8076?

**Comment by pv** [comment]
Is this actually a problem of the SElinux policy, rather than of numpy 
packaging? If you install stuff as root, you may need to tweak the policies.

**Comment by avipersin** [comment]
@pv I presume it is a problem with numpy. Whether the hidden directory has anything to do with it, I'm not sure. Something has changed between versions 1.10.4 and 1.12.0rc2 that causes the error I reported above.  Maybe there is an issue with the .whl file installed from PyPi...

We always install packages as root and never have a problem with the SELinux policies.

**Comment by charris** [comment]
What policy version? What mode is SElinux running in? What does the SElinux log show? I note that the policy seems to get regular updates on fedora. Back in the day, I also routinely disabled SElinux because of problems, so it isn't unlikely that something needs a tweak.

**Comment by njsmith** [comment]
I can't think of anything relevant that would have changed between those
two releases. 1.10.2 also ships libopenblas in a hidden directory IIRC. And
I know almost nothing about SELinux, but I thought it only cared about the
labels attached to files, not their names. Agreed that it would be helpful
to check the SELinux logs, whatever those are in this case...

**Comment by avipersin** [comment]
SELinux status:                 enabled
SELinuxfs mount:                /selinux
Current mode:                   enforcing
Mode from config file:          enforcing
Policy version:                 30
Policy from config file:        targeted

```
Jan  9 16:37:09 avc:  denied  { getattr } for  pid=8015 comm="test.cgi" path="/etc/httpd/conf/mime.types" dev="md121p3" ino=912288 scontext=system_u:system_r:httpd_sys_script_t:s0 tcontext=system_u:object_r:httpd_config_t:s0 tclass=file permissive=1
Jan  9 16:37:09 avc:  denied  { read } for  pid=8015 comm="test.cgi" name="mime.types" dev="md121p3" ino=912288 scontext=system_u:system_r:httpd_sys_script_t:s0 tcontext=system_u:object_r:httpd_config_t:s0 tclass=file permissive=1
Jan  9 16:37:09 avc:  denied  { open } for  pid=8015 comm="test.cgi" path="/etc/httpd/conf/mime.types" dev="md121p3" ino=912288 scontext=system_u:system_r:httpd_sys_script_t:s0 tcontext=system_u:object_r:httpd_config_t:s0 tclass=file permissive=1
Jan  9 16:37:09 avc:  denied  { ioctl } for  pid=8015 comm="test.cgi" path="/etc/httpd/conf/mime.types" dev="md121p3" ino=912288 ioctlcmd=0x5401 scontext=system_u:system_r:httpd_sys_script_t:s0 tcontext=system_u:object_r:httpd_config_t:s0 tclass=file permissive=1
```
I'm not sure why importing numpy is accessing server config files...

@njsmith You are correct, SELinux should not care about filenames.

**Comment by njsmith** [comment]
Those access log lines have nothing to do with numpy. It looks like something in your program is using the stdlib `mimetypes` package, which attempts to load the mime database from various places. If you `import http.server` then that could be why. Those errors look harmless to me.

Backing up, is there any reason to think that SELinux is even involved here? If you temporarily turn off SELinux enforcement, then does that fix the numpy import error?

Can you set the environment variable `LD_DEBUG=libs,files,scopes` before running your script with the error message, and upload the output? (It may help to also set the envvar `LD_DEBUG_OUTPUT` to point to a file where you want it to write the output instead of your terminal.)

Also, re-reading: you say that you installed numpy 1.10.4 and 1.12.0rc2 the same way, but that your 1.10.4 install didn't have a hidden `.libs` directory. But the 1.10.4 whl on pypi *does* have a hidden `.libs` directory, so I'm guessing your 1.10.4 was built from source on your machine and is using your system BLAS, while for 1.12.0rc2 you're using the pre-built wheel with its included BLAS.

**Comment by avipersin** [comment]
"test.cgi" is a file I made that is called from the web browser. It has various imports and Python code. When I ```import numpy``` from that file it crashes. But when I remove that import everything else works fine. 

I'm not sure why numpy would try to access ```mime.types```, which is a server config file. Maybe 
libopenblas is trying to read the mimetypes file?

- Setting the SELinux enforce mode to "permissive" fixes the import error. Also, while enforcing, the import works with our version numpy 1.10.4 that does not have the ```.libs``` directory. 
- Using numpy 1.12.0rc2 and calling "import numpy" from the terminal works fine as SELinux is not invoked, so it seems it is an SELinux problem.
- I'm pretty sure numpy was originally installed via pip. Maybe at the time it was installed (over a year ago,) there was no ```.libs``` directory?  However, I do see that it does exist in the current 1.10.4 version.

**Comment by charris** [comment]
IIRC, there was a script to label/relabel files given the policy. Ah, the output of `fixfiles --verify` might be interesting. Looks like actual relabeling is best carried out with a reboot.

**Comment by njsmith** [comment]
Ah-hah, here's the issue:
* https://bugzilla.redhat.com/show_bug.cgi?id=1388533#c4
* http://blog.siphos.be/2011/04/selinux-and-noatsecure-or-why-portage-complains-about-ld_preload-and-libsandbox-so/

Basically SELinux by default, in a somewhat complex set of circumstances I don't understand, will set a special flag that tells ld.so to disable a bunch of its normal library loading rules "for security". There's no warning in the SELinux logs when this happens, and even if there were it wouldn't say anything particularly useful because the actual error doesn't happen until a while later when ld.so tries to load the library and doesn't look in the right place.

So I don't think there's any way to fix this on numpy's end, or by relabeling. You need to somehow tweak your SELinux policy to enable the `noatsecure` permission on whatever "domain transition" is affecting your cgi script. This is way beyond my knowledge, but there's some examples in that link...

**Comment by njsmith** [comment]
You should probably also file a bug with your distributor asking that they modify the SELinux policy for their webserver so that CGI scripts can use RPATH... you can point to this bug for why.

**Comment by charris** [comment]
@njsmith Oh, good find.

**Comment by avipersin** [comment]
@njsmith Thanks, just trying to understand this...

When the cgi is called SELinux has some sort of sanitation routine that prevents numpy from accessing ```libopenblasp-r0-39a31c03.2.18.so``` from the ```.libs``` directory? But if that library is loaded externally (like our current setup not through the ```libs``` directory,) then it works?

If that's the case maybe we can build numpy 1.12.0rc2 from source and continue using the systems BLAS.

**Comment by charris** [comment]
@avipersin My understanding is that the library is no longer in the search path, hence one of the workarounds being adding a link to the library in the search path that is considered safe.

**Comment by charris** [comment]
This is out of our hands, so closing. @avipersin If you find a solution, post it here so others can find it also.

**Comment by avipersin** [comment]
We have not been able to identify the exact SELinux config option that prevents cgi's from accessing hidden directories.

For now, any library that has a hidden ```.libs``` directory we install from source and it works fine. The only libraries we've come across so far with this hidden directory are:
* numpy
* netcdf4

Note: It is only the Linux wheels that ship with the ```.libs``` directory, the Windows versions do not have this hidden directory.
