### ISSUE TITLE
incorrect output from isrealobj

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#8465]
`np.isrealobj` is implemented as the opposite of `iscomplexobj`, but this incorrectly returns True for non-numeric types:
```
In [1]: np.isrealobj("a")
Out[1]: True
```

**Comment by shoyer** [comment]
I agree that it is strange to call a string a "real object". This should probably be true only for numeric dtypes.

On the other hand, this function has worked like this for a long time -- git blame shows it going back to Travis Oliphant in 2002!

**Comment by sethtroisi** [comment]
This seems to match the [function documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isrealobj.html#numpy.isrealobj): `Return True if x is a not complex type or an array of complex numbers.`

There's already a couple of helpers here
`np.isreal()`
`np.iscomplex()`
`np.isinf()`
`np.isnan()`
`np.isscalar()`

also
`np.issubdtype(<var>, np.integer)`
`np.issubdtype(<var>, np.floating)`
`np.issubdtype(<var>, np.string_)`

I'm happy to look into changing `np.isrealobj` or adding `np.isstring` if there's a consensus on what that should be done. (implicit: otherwise maybe this should be closed)

**Comment by mattip** [comment]
Closing, since the implementation matches the documentation and we are unlikely to change this longstanding behavior. It would be better to think fo `isrealobj` as an alias to `is_not_complexobj`. Please reopen if needed.
