### ISSUE TITLE
np.clip broadcasts input array to fit a_min/a_max

### ISSUE THREAD

**Issue by befelix** [numpy/numpy#8471]
```np.clip``` allows to clip multi-dimensional arrays by taking arrays for `a_min` and `a_max`. However, when providing bounds that are array-likes that don't match the source sometimes one can weird results.
For example, while
```
a = np.arange(5)
a.clip([0, 0], [1, 1])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-ad92301a6712> in <module>()
      1 a = np.arange(5)
----> 2 a.clip([0, 0], [2, 2])

ValueError: operands could not be broadcast together with shapes (5,) (2,)
```
raises an error as expected, the following passes:
```
a = np.arange(5)[:, None]
a.clip([0, 0], [2, 2])

array([[0, 0],
       [1, 1],
       [2, 2],
       [2, 2],
       [2, 2]])
```
I guess what's happening is that the input array is broadcasted to fit the constraints. Is this expected? I would have expected an error to be raised instead.

**Comment by seberg** [comment]
I would say it is a matter of taste, both behaviours make sense. We do have a tendency to generally allow broadcasting. For example, in principle you might want to try different clip values or so.
Since it works that way currently, I would say we should stick with it (we even have a PR that started making clip a ufunc, which would be nice, and would cement that behaviour a bit, but it was a bit tricky to limit the behaviour changes as much as possible IIRC).

So, I think this is expected (just saw it actually says so in the `a_max` doc string). Which does not necessary mean you cannot convince everyone otherwise. I will close this, but please feel free to continue the discussion.

**Comment by befelix** [comment]
Thanks for the clarification. Note that the documentation states that 'a_min' will be broadcasted to fit `a`, but here `a` is being broadcasted to fit `a_min`.

If this is expected and consistent then that's fine. For me it introduced a strange bug where a function that required a (N, 2) array was working fine with (N, 1) arrays because clip was broadcasting them to (N, 2). 

Would you be open to a PR request that adds a note about this behavior? Or is this broadcasting too much of an expected thing?

**Comment by seberg** [comment]
Of course, go ahead, we always like improvements :).
