### ISSUE TITLE
Wrong results with arange using float parameters and an integer dtype result

### ISSUE THREAD

**Issue by SamyCookie** [numpy/numpy#8560]
Hi,

I use arange like this :
```
arange(0.1, 10000, 0.4, dtype=np.uint32)
>>> array([0, 0, 0, ..., 0, 0, 0], dtype=uint32)
arange(0.1, 10000, 0.9, dtype=np.uint32)
>>> array([    0,     1,     2, ..., 11108, 11109, 11110], dtype=uint32)
```

I know that you note in the documentation: 
> When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use linspace for these cases.

But with the use of integer type, we can see that results totally wrong.

It is also noted that:
> Because of floating point overflow, this rule may result in the last element of out being greater than stop.

But in this case, with the use of integer type, we can see that there is not only the last result that can be greater than stop.

Of course, my failing examples can be replaced by this solution:
```
arange(0.1, 10000, 0.4).astype(np.uint32)
>>> array([   0,    0,    0, ..., 9998, 9999, 9999], dtype=uint32)
arange(0.1, 10000, 0.9).astype(np.uint32)
>>> array([   0,    1,    1, ..., 9997, 9998, 9999], dtype=uint32)
```
which is exactly what I expected in the first case.

The documentation warns about inconsistent results, but the first previous results displayed seems too weird to me to be normal. Maybe I am wrong and if all of this correspond to the described behaviour, feel free to close this ticket.

**Comment by charris** [comment]
When you specify `uint32` the fractional parameters are rounded to integer, zero in this case. If dtype is not specified, the default is float because of the floating parameters, hence better results. However, even in that case the floating representation of `.1` and `.4` is not be exact and you may get unexpected results. The thing to do is either use all integers and scale, or see if `linspace` can be used.
