### ISSUE TITLE
Request: add Knuth and Bayesian blocks binning methods to histogram

### ISSUE THREAD

**Issue by Gabriel-p** [numpy/numpy#8620]
The [astropy package](http://docs.astropy.org/en/stable/index.html) hast two very useful bin methods that could be added to `histogram`:

* [knuth_bin_width](http://docs.astropy.org/en/stable/api/astropy.stats.knuth_bin_width.html#astropy.stats.knuth_bin_width)
* [bayesian_blocks](http://docs.astropy.org/en/stable/api/astropy.stats.bayesian_blocks.html#astropy.stats.bayesian_blocks)

**Comment by shoyer** [comment]
CCing people who have worked on automatic bin selection for `np.histogram` in case they have opinions: @madphysicist @nayyarv

**Comment by rgommers** [comment]
That seems way too specialized for numpy. And for a practical problem, looks like a gamma function is needed (so depends on ``scipy.special``, can't do in ``numpy``).

For ``scipy.stats.binned_statistic`` this may make sense though.

**Comment by nayyarv** [comment]
Yeah, I considered it when I made the first PR but decided against it - the methods I selected were very simple, easily maintainable and could do some good downstream for plotting libraries (and others) without resulting in a ton of bugs/edge cases that would keep getting sent back to numpy.

Overall, the technical debt introduced by the knuth/bayesian blocks methods simply isn't worth the marginal benefit, especially for a package like numpy (and probably scipy too).

**Comment by madphysicist** [comment]
I think this would be fine for scipy, especially since the building blocks are already there, but I will defer to people with actual experience in the matter.

While we are all gathered here, I would like to ask if there is any interest in Wand's estimator. It is supposedly as good as you can get in terms of MISE: http://www.stat.cmu.edu/~rnugent/PCMI2016/papers/WandBinWidth.pdf, found via http://stats.stackexchange.com/a/55205/102011. The implementation I am thinking of would have an additional order parameter that would have a default value.

**Comment by bsipocz** [comment]
There is clear consensus above that these don't belong to numpy ,so I'm going to close this issue.
If there is a notion that these would be a net benefit to scipy (most bugs got already smoked out of them while the code was in astroML and then in astropy), and if there is a want for it, then I'm happy to do the upstreaming myself as I have some familiarity with the code itself.
