### ISSUE TITLE
Need to add NumFOCUS logo and donation button to numpy.org

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#8752]
Help would be much appreciated. Note that the website is kept in a separate repo: https://github.com/numpy/numpy.org

Instructions for the donation button are in https://github.com/numpy/numpy.org/issues/9

**Comment by rushabhy** [comment]
Can I give it a try?

**Comment by shoyer** [comment]
@rushabhy Yes, please!

**Comment by ZZhaoTireless** [comment]
Hi, I pulled my request in [numpy.org](https://github.com/numpy/numpy.org) since @rushabhy have not followed up the task for a long time. If he still would like to do this, I am fine to close my PR : )

**Comment by rushabhy** [comment]
@ZZhaoTireless Thanks for asking. I was confused about the location of the button to be added and asked about the same on [numpy/numpy.org#9](https://github.com/numpy/numpy.org/issues/9). But I guess no one replied (got any notification about it) because I didn't mention anyone. Since you are already done with this, I would like you to keep your PR and merge it. I'll find something else to fix. :smile:

**Comment by ZZhaoTireless** [comment]
@rushabhy Thank you very much. I am a new contributor, and I just tried to learn from contribution and practice. Hope you do great for future tasks :D

**Comment by rgommers** [comment]
This was done in https://github.com/numpy/numpy.org/pull/10, thanks all!
