### ISSUE TITLE
DEP: Deprecate `np.masked_array.mini`

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8764]
It's not at all clear why this exists, or how `MaskedArray.mini` is different from `MaskedArray.min`

This was introduced in 80f6f5062022104f3a57de05cb119df23c2b5de4 by @stefanv, in a patch claimed to be authored by Pierre ( @pierregm? )

**Comment by charris** [comment]
@stefanv @pv Any recollection of why this method exists? It doesn't appear to be used anywhere in numpy or scipy.

**Comment by charris** [comment]
@eric-wieser I'll guess there is something special about the return value.

**Comment by stefanv** [comment]
I guess this was an attempt to address what happens in the cases where: a) the array is reduced to a scalar because no axis was specified and b) the case where the entire array is masked.

E.g.:

```
n [11]: x = np.ma.MaskedArray(np.ones((3, 3)), mask=np.ones((3, 3)))

In [12]: x.min()
Out[12]: masked

In [13]: x.mini()
Out[13]: 
masked_array(data = --,
             mask = True,
       fill_value = 1e+20)
```

In the first case, returns `np.ma.core.MaskedContent`, in the second an MaskedArray scalar that is masked.

```
In [16]: x = np.ma.MaskedArray([[1,2,3], [4,5,6]], mask=[[True,False,True], [False, True, False]])

In [17]: x.min()
Out[17]: 2

In [18]: x.mini()
Out[18]: 
masked_array(data = 2,
             mask = False,
       fill_value = 999999)
```

An int64 in the first case, a MaskedArray scalar in the second.

**Comment by eric-wieser** [comment]
So `.min()` is the same as `.min(keepdims=True, axis=axis).squeeze(axis=axis)`?

**Comment by stefanv** [comment]
Yes, and given the one-liner you've shown, I would certainly deprecate and remove it.
