### ISSUE TITLE
Make median a member of the class numpy.ndarray

### ISSUE THREAD

**Issue by quentinbodinier** [numpy/numpy#8797]
Everything is in the titile : it is confusing to have certain functions directly callable on an ndarray, such as mean, whereas it is not doable for median directly.

To explain this a bit better, assume that `a` is of class `ndarray` .
Then , to get the mean, you simply have to execute `a.mean()`.
However, to get the median, you need to go with `np.median(a)`.

This is both confusing and not homogeneous. It would be nicer, therefore, to be more consistent and add median as a member of the ndarray class.

**Comment by charris** [comment]
I believe that this has been proposed before. I'm not opposed, but there is a general reluctance to add more methods. I don't recall the exact arguments that were made for and against.

**Comment by rkern** [comment]
I have a strong reluctance to adding more methods. If you want consistency, always use the functions.

**Comment by rkern** [comment]
Basically, we have to draw a line somewhere. There's an essentially-unbounded number of functions that *could* be added to the `ndarray` interface as methods. Each one adds to the maintenance burden of numpy and every project that tries to make an `ndarray`-alike class. `.mean()` and many other current methods don't really need to be there. It would have been a good idea to keep `ndarray` more minimal than it currently is. That ship has long since sailed, but the mistake does not need to be compounded. Because of this, the consistency argument holds less weight for me than the maintenance burden.

**Comment by juliantaylor** [comment]
you can also argue the other way around too. median not being a member has caused us significant headaches do to having to keep subclass compatibility with external projects that had to rely on hacks and implementational details to override it.
We have to maintain median anyway, be it in function or method form, the latter would have saved us, other projects and in particular users a lot of problems when subclasses are involved.

**Comment by eric-wieser** [comment]
@juliantaylor: An alternative approach to that might be to use `@functools.singledispatch` to make overloading the free functions possible for subclasses

**Comment by rkern** [comment]
That's a specific argument for `median` qua `median`, and it does hold some weight with me. Can you cite specifics?

**Comment by juliantaylor** [comment]
For median subclasses currently rely on median calling mean or sum to provide the overrides. It is not a particularly large deal but I also don't see high costs in making it a member method.
Then of course where to draw the line is the bigger issue, but if something deserves promotion it should probably be median.

Thought the singledispatch method does sound very interesting median. Is there enough practical experience from the julia area with their multiple dispatch capabilities to say if this really works out in practice?

**Comment by njsmith** [comment]
Making median a gufunc + __numpy_ufunc__ seems more maintainable to me than
making median another ad hoc method.

**Comment by quentinbodinier** [comment]
Hey thanks everyone for the inputs.

I do understand this is not a new issue and it has been proposed and discussed already. In any cases, this is more than anything an issue of consistency and elegance and I do agree with the fact that adding all methods to the ndarray class is both infeasible and undesirable. 

As for the specific details relating to the `median` method, I do not think I can bring any valuable input. 

Thanks again for the nice answers and clarification

**Comment by mhvk** [comment]
> Making median a gufunc + __numpy_ufunc__ seems more maintainable to me than making median another ad hoc method.

This would indeed seem to be the nicest solution, especially since we already sort-of started doing that with `np.dot` and `np.matmul`. But that also means we might need to implement supporting `gufuncs` in #8247... (or at least have a warning for `__array_ufunc__` users that it is likely that more functions are going to use that mechanism).

**Comment by eric-wieser** [comment]
But once again, this catches us out with having no `axis` argument to gufuncs

**Comment by mhvk** [comment]
See #8810 and #5197 for feature requests for adding `axis` to `gufunc`. Since the explicit request here, of adding `median` as a method, is likely not going to happen, I'll close this.
