### ISSUE TITLE
When to use DEPRECATE and DEPRECATE_FUTUREWARNING

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#8829]
There are plenty of invocations of `DEPRECATE` containing the text "this will raise an error in the future.".

Given this, what distinguishes these two cases?

**Comment by charris** [comment]
DEPRECATE is when something will go away/disappear, hence the error. I'm not quite sure what the other is, but it looks like a `FutureWarning`, which means that something will change behavior but not go away. @njsmith Is that your understanding?

**Comment by njsmith** [comment]
Technically the difference is that `DEPRECATE` issues a `DeprecationWarning`, and `DEPRECATE_FUTUREWARNING` issues a `FutureWarning`. Technically the difference between these two warnings is that `DeprecationWarning`s are invisible by default, and `FutureWarning`s are visible by default. Our policy has been that `DeprecationWarning` is sufficient for cases where if you do nothing then working code might eventually turn into code that throws an error, and `FutureWarning` is needed for cases where if you do nothing then working code might eventually turn into code that silently does something different.

**Comment by eric-wieser** [comment]
Thanks for the input

**Comment by seberg** [comment]
Yeah, FutureWarning whenever behaviour changes instead of just going to error (Sometimes its also Deprecation -> Error -> New behaviour, etc. can be tricky....).

In case you are checking/reviewing these things. Since both macros can have an error return (if the warning is set to an error), they need to be tested both for the warning as well as for the error. We have a deprecation test file/class to help with it. But that does not have to be used (though using the file may make things easier to find in some cases). The original reason for it was to circumvent a problem with warnings that is now generally cleaned up within the numpy test suit.

Both macros should have a comment with the date and the numpy version that they were introduced to make follow up easier, IIRC.
