### ISSUE TITLE
Add H member to array for calculating the Hermitian

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#8882]
`numpy.matrix.H` exists, but with the addition of the `@` operator to Python most people use `np.array`.  It is currently possible to write `arr.T.conjugate()`, but `arr.H` would be clear and succinct for people working with complex matrices.  Please consider adding an `H` shortcut.

**Comment by njsmith** [comment]
This has been considered and rejected in the past because `.T` returns a view, which is cheap and allows updates to the underlying array, but `.H` would return a copy, which is expensive and does not allow modification of the underlying array. So they're less parallel then you'd think, and in particular we think it's actually a good thing if operations that might involve allocating lots of memory have function-call parentheses on them to remind you that you're performing some non-trivial action.

I did at some point suggest the somewhat wacky idea of adding a "conjugated complex" dtype that stores the value `x + yj` as the tuple `(x, -y)`. This would make it possible to have a `.H` property that returns a view. But no-one has followed up on this suggestion. Whether this is due to lack of time or because everyone recoiled in horror, I can't say :-). It could be both...

**Comment by NeilGirdhar** [comment]
@njsmith Okay, thanks for taking a look.  I swear I did a search for Hermitian here!

I agree with that if `.T` returns a view (didn't know that) that `.H` should either do the same or else not exist.

**Comment by NeilGirdhar** [comment]
@njsmith https://github.com/numpy/numpy/search?q=hermitian&type=Issues&utf8=%E2%9C%93 returns nothing, so I guess it was before this project started using Github.  Anyway, this bug will prevent other people from making the same suggestion.
