### ISSUE TITLE
fromregex doesn't handle one group

### ISSUE THREAD

**Issue by paalge** [numpy/numpy#8891]
Hi
I'm trying to get a group out from numpy fromregex, but it fails with:
```bash
File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 1242, in fromregex
    newdtype = np.dtype(dtype[dtype.names[0]])
TypeError: 'NoneType' object is not subscriptable
```
Minimal working example is:
```python
import numpy as np
# Working, but gives two groups
regexp =r'Setup # \d.*\n((.*))\n'
print(np.fromregex('test.txt',regexp,dtype=np.str))
# Not working, as it wants one grou
regexp =r'Setup # \d.*\n(.*)\n'
print(np.fromregex('test.txt',regexp,dtype=np.str))
```
were the `test.txt` contains:
```text

Setup # 1
2017 2 18 0 0 1  35.62  36.48 2   1.00 4820.00 4920.00   1.00 32.768 428 
00005 00006 00002 00004 00008 00007 00004 00007 00007 00006 
```

From the source of fromregex it looks like one group and multiple groups are handled different, were two groups are just returned but the one is converted with the cryptic `newdtype = np.dtype(dtype[dtype.names[0]])`

Is this a bug or have I misunderstood something?

Tested on Linux Mint 18 
Python 3.5
Numpy: 1.13.0.dev0+ad7ee70

Also with Numpy 1.11

**Comment by WarrenWeckesser** [comment]
@paalge, a belated "thanks" for reporting the issue.  Sorry no one responded in the years since you reported the issue!

The dtype that you pass to `fromregex` *must* be a structured datatype; `dtype=str` is not a structured datatype.  The code was not checking that the dtype was structured, but it was assuming it was, which resulted in a cryptic error message when the function executed code that expected dtype to be structured.

In gh-19928, I added an explicit check that the dtype is a structured datatype, so now you'll get a clearer error message.  Note that *both* your examples will given an error, because `dtype=str` does not given a structured datatype.

**Comment by paalge** [comment]
Thank you for looking into this, and figuring out that both were examples were wrong (though I'm sure the second one ran fine in my code). I can't remember anymore why I didn't understand the structured part. I'll close this issue as it is now patched.
