### ISSUE TITLE
FutureWarning in recfunctions.join_by

### ISSUE THREAD

**Issue by isaacgerg** [numpy/numpy#8940]
Currently using numpy 1.12.0 on windows 7.

`joinedDataset = np.lib.recfunctions.join_by(['filename','x','y'], dataset, metricsDataset, jointype='inner', usemask=False)`

Yields the following warning:

> c:\Python35\lib\site-packages\numpy\ma\core.py:6589: FutureWarning: Assignment between structured arrays with different field names will change in numpy 1.13.
> 
> Previously fields in the dst would be set to the value of the identically-named field in the src. In numpy 1.13 fields will instead be assigned 'by position': The Nth field of the dst will be set to the Nth field of the src array.
> 
> See the release notes for details
>   d = np.concatenate([getdata(a) for a in arrays], axis)

I assume for numpy 1.13 recfunctions will be written to appropriately do the join.  Is this correct?

**Comment by eric-wieser** [comment]
The PR for this behaviour change is #6053

**Comment by charris** [comment]
@ahaldane Can you answer the question?

I changed the warning message NumPy version in #9058.

**Comment by ahaldane** [comment]
Hmm OK, this is a legitimate warning.

It looks like I will need to change the `join_by` code a little bit. The problem presumably  occurs because `dataset.dtype` and `metricsDataset.dtype` have the same fields but in a different order.

Here is reproducible code:
```python
>>> a = np.zeros(3, dtype=[('a', 'i4'), ('b', 'f4'), ('c', 'u1')])
>>> b = np.ones(3, dtype=[('c', 'u1'), ('b', 'f4'), ('a', 'i4')])
>>> numpy.lib.recfunctions.join_by(['a', 'b'], a, b, jointype='inner', usemask=False)
FutureWarning
```

The fix would/will be to change the line `ma.concatenate((r1k, r2k))` to `ma.concatenate((r1k[keys], r2k[keys]))`.

I'll have to look for more closely for similar cases before we merge #6053.

**Comment by ahaldane** [comment]
Thanks @isaacgerg for the report, it is very helpful.

**Comment by ahaldane** [comment]
We probably want to silence this error or modify `join_by` in some way for 1.13. I'll take a look in a little while.
