### ISSUE TITLE
Unconditionnal usage of sys.base_prefix in mingw32ccompiler.py

### ISSUE THREAD

**Issue by diorcety** [numpy/numpy#9017]
I can't compile the master branch on msys2 with python2.7. The usage of sys.base_prefix is not available

@rolk

**Comment by diorcety** [comment]
cf https://github.com/diorcety/numpy/commit/d4cdf30c2cac93e47be6b8664f0bf3e1f8e3243d ?

**Comment by rolk** [comment]
@diorcety 
Your suggested patch looks good to me, that's probably the same thing I would have done, so I would submit it as a patch. ("BUG: Make extensions compilable with MinGW on Py2.7"). It may be that you get problems to compile an extension in a virtualenv; I don't have a 2.7 installation to check.

**Comment by kmuehlbauer** [comment]
@diorcety Have the same problem #9276. Will you PR your patch?

**Comment by rolk** [comment]
@kmuehlbauer: @diorcety seems to be MIA for the moment. I have created PR #9280. Do you have the opportunity to test?

**Comment by kmuehlbauer** [comment]
Thanks @rolk for getting back to this that fast. We will test that patch at https://github.com/conda-forge/numpy-feedstock soon. There are atm two conda-forge packages which do not build on win py2.7 for numpy 1.13 due to this. I'll have an update here or in #9280 if this fixes the issue for conda-forge.

**Comment by diorcety** [comment]
Yeah, i'm off for few days :)

**Comment by seberg** [comment]
Closing, as this is distutils, and distutils is sunset.
