### ISSUE TITLE
ENH: Add a `writeable=True` argument to ufuncs

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9069]
This argument would indicate whether the result _needs_ to be writeable

Proposed semantics when set to `False` (the default, `True`, is the current behaviour)

* `abs(uint)`, `positive(int)`, `conjugate(int)` all return an unmodified view of their original data
* `binop(x, binop.identity)` returns a view of `x`
* When all arguments to `op(x1, x2, ...)` share a zero stride, the output has a zero stride in the corresponding location
* If we implement a `conjugate_complex` type, then `conjugate(complex)` would return a conjugate view on the original
* If none of the above optimization match, do the ufunc as normal
* Always set `.flags.writeable` to False, in case future optimizations are made

**Comment by njsmith** [comment]
Is there any reason to think that this optimization would make any real difference in apps? I'm hesitant to add to the ufunc public interface surface area, and a bunch of special cases to the internal dispatch, for something that seems kind of marginal. Basically, is this the best use of our complexity budget?

**Comment by eric-wieser** [comment]
This is inspired by the fact that right now `int_arr.conjugate()` already returns a view despite `np.conjugate(int_arr)` not doing so. Neither form should do that by default, as this means that right now we see https://github.com/numpy/numpy/pull/9060#issuecomment-299720329.

So the alternative would just be to add an argument to the method, but it would be weird for them to be inconsistent

**Comment by njsmith** [comment]
Ah, I see. That makes sense, though I still feel like this is a big hammer for a small nail... And note that setting `flags.writable = False` isn't enough to hide whether an array is a view, because modifications to (any other views of) the original array might also modify the non-writable view.

Some other possible strategies for the original problem:

* Have `cov` skip the `conj` call if the dtype isn't complex
* Have a `conjugate_maybe_view` function that wraps up that check into something reusable
* Implement the wacky `conjugate_complex` dtype idea, and then add a `.H` that consistently returns a view.
* Accept a minor slowdown in `cov`

These all seem more attractive to me then adding an argument to every ufunc that most of them can't use.

**Comment by shoyer** [comment]
> These all seem more attractive to me then adding an argument to every ufunc that most of them can't use.

+1

I don't like the idea of allowing ufuncs to return views of the original data. That seems very hard to predict. We should leave these sort of optimizations to higher level array libraries.

**Comment by mhvk** [comment]
My tendency would be to update the `conj` method docstring and explicitly state that it returns a view for non-complex numerical types (in fact, it would seem fine if it were to just return `self`); I don't really see why `ndarray` methods should map exactly to `ufunc`s.

**Comment by eric-wieser** [comment]
Yep, I think I agree that this is a bad idea, so closing.
