### ISSUE TITLE
Misleading __array_ufunc__ error

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9079]
Here's a very simple `__array_ufunc__`, which is likely to be one of the first tests people try:
```python
class foo(np.ndarray):
     def __array_ufunc__(self, *args, **kwargs):
         print(args, kwargs)
         return super().__array_ufunc__(*args, **kwargs)
```

Unfortunately, the error given is a little unhelpful:

```
>>> a = np.array(1).view(foo)
>>> a + a
(<ufunc 'add'>, '__call__', foo(1), foo(1)) {}
(<ufunc 'add'>, '__call__', foo(1), foo(1)) {}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-24070be0e9db> in <module>()
----> 1 a + a

TypeError: operand type(s) do not implement __array_ufunc__(<ufunc 'add'>, '__call__', foo(1), foo(1)): 'foo', 'foo'
```

Some kind of hint that `ndarray.__array_ufunc__` was not able to handle things either might be helpful.

**Comment by shoyer** [comment]
How would we surface this information? The only types that the ufunc machinery works with directly are of type `foo`.

This problem goes away if you call `getattr(ufunc, method)` directly instead of calling `__array_ufunc__`. Possibly we should give this guidance even for ndarray subclasses, in preference to using `super()`. We already give this sort of guidance for duck array types.

(cc @mhvk)

**Comment by mhvk** [comment]
With `getattr` one gets infinite recursion, which I guess is somewhat clearer:
```
home/mhvk/python/try.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
      4 class MyA(np.ndarray):
      5     def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
----> 6         getattr(ufunc, method)(*inputs, **kwargs)
      7 
      8 

RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by shoyer** [comment]
The right way to do this example with either version is to unwrap each of `inputs` into base ndarray objects.

**Comment by mhvk** [comment]
More concretely - I think the error message is the problem, because at least as I would read it, it would not be clear to me that `do not implement __array_ufunc__(...)` means `__array_ufunc__` returned `NotImplemented`. What if it just were 
```
TypeError: operand type(s) all returned NotImplemented upon calling __array_ufunc__(..)
```
That would seem to at least get people to think what happened (and perhaps read the documentation)

@shoyer - I think @eric-wieser's point was that most people would on their first try not think to unwrap the arguments and get very confused.

**Comment by shoyer** [comment]
@mhvk sounds good to me -- "all returned NotImplemented upon calling" is much more descriptive than "do not implement".

**Comment by charris** [comment]
Changed milestone, I'm not going to wait on this.

**Comment by shoyer** [comment]
Give me 5 minutes, I'll make the PR!

**Comment by eric-wieser** [comment]
I'm still not sure that this should fail. It's very confusing that:
```
class foo(np.ndarray):
     def somefunc(self, *args, **kwargs):
         return super().somefunc(*args, **kwargs)
```
would fail, yet
```
class foo(np.ndarray):
    pass
```
would be fine. Forwarding to a method shouldn't change behaviour.

A proposal: change `ndarray.__array_ufunc__` to the following (in 1.14, or 1.13.1):

```
def __array_ufunc__(self, ufunc, method, *args, **kwargs):
    def _replace_self(a):
        if a is self or type(self) is super and a is self.__self__:
            return a.view(np.ndarray)
        else:
            return a

    args = tuple(_replace_self(a) for a in args)
    if 'out' in kwargs:
        kwargs['out'] = tuple(_replace_self(a) for a in args)
    return getattr(ufunc, method)(*args, **kwargs)
```

Which would mean that:

* Forwarding to ndarray means "I don't care about ufunc, treat me like a normal array"
* In a invocation with multiple subclasses, the dispatch is repeated if one class doesn't care, with itself replaced by a raw array.

**Comment by mhvk** [comment]
@eric-wieser - to me that seems a way to very nasty bugs; as, is `ndarray.__array_ufunc__` implements exactly what we tell users to do for other classes: return `NotImplemented` if it isn't sure that it can handle all arguments. I think this is good practice.....
- Explicit is better than implicit.
- Special cases aren't special enough to break the rules.
- In the face of ambiguity, refuse the temptation to guess.
- If the implementation is hard to explain, it's a bad idea.

(arguably, some of these mean we shouldn't do `__array_ufunc__` at all...)

**Comment by eric-wieser** [comment]
> Special cases aren't special enough to break the rules.

I would argue that right now we are breaking the rules, by breaking transparent forwarding in a surprising way. Also, the `if (obj.__array_ufunc__ == ndarray.__array_ufunc__)` check in the C code was causing me significant headaches with regard to bound methods, and I don't think it's a terribly good way to handle dispatch

**Comment by mhvk** [comment]
Part of the problem is that `ndarray` calls the ufunc again, which would lead to infinite recursion if it just passed on subclasses that define `__array_ufunc__`. In principle, this could be solved if instead `ndarray.__array_ufunc__` would become the implementation of the ufunc for arrays -- since then it can just be one of the `__array_ufunc__` implementations which get tried, and it would be OK to let it handle all subclasses as regular arrays since any `__array_ufunc__` implementations of those subclasses would be called before `ndarray`s anyway. Your suggestion of doing `view` would effectively implement that now, but would also set up expectations that would be hard to break if turned out to be a mistake.

Anyway, for 1.14, I do hope to get to letting `ndarray.__array_ufunc__` call deeper into the ufunc machinery (if only for speed!), but for 1.13 I felt it was more important to get something in that works "well enough" -- and is restrictive enough that we can determine from real usage how it should be adapterd (in this respect, note that it has been since 1.10 that I thought we could get rid of the annoying factor 2 slowdown in Quantity because we could not change inputs before the actual calculation in `__array_prepare__`. -- and having units on one's physical quantities is a benefit that simply cannot be overstated...)

p.s. I updated #8892 with a brief version of this; possibly it is better to continue the discussion there, or at least in an issue that does not have the current title!

**Comment by njsmith** [comment]
The usual way this would work for other special methods is that `ndarray.__array_ufunc__` would be happy to accept any *subclass* of ndarray, and then the subclasses-before-superclasses rule would make sure that it just never sees any of those subclasses unless explicitly invoked on them, or if inherited.

This is pretty messy given the need to support the legacy behavior of accepting arbitrary objects and casting them to object arrays, though.

**Comment by charris** [comment]
Just a comment on the timeline. I'm going to put out v1.13.0rc1 tonight and let it sit there 2-4 weeks. The whole release process will probably take 6-8 weeks, depending. So there is sometime between now and the final to argue about this...

**Comment by mhvk** [comment]
Hmm, it does seem @eric-wieser, @njsmith and I came to the same conclusion about what the desirable final behaviour for `ndarray.__array_ufunc__` would be... I remain somewhat uncomfortable with adding yet more checks and views to `ndarray.__array_ufunc__` before calling the ufunc again, though I see that what's needed (https://github.com/numpy/numpy/issues/9079#issuecomment-300550725) may be simpler than it seemed a few hours ago... 

But what I'd really like is to see if we can speed things up! Sadly, I don't have a feeling for is how difficult it would be to do the most common and most useful thing right. In particular, if we determine that all arguments are ndarray subclasses, how easy it is to call directly into the actual ufunc C code for array inputs?

**Comment by eric-wieser** [comment]
> ut for 1.13 I felt it was more important to get something in that works "well enough" -- and is restrictive enough that we can determine from real usage how it should be adapterd

I completely agree, this gets 90% of the way to being useful enough, and I think is just fine for `1.13`

> Your suggestion of doing view would effectively implement that now, but would also set up expectations that would be hard to break if turned out to be a mistake.

Indeed - this was very much something I don't think we want to rush into 1.13, but just an idea to consider in a future release.

> This is pretty messy given the need to support the legacy behavior of accepting arbitrary objects and casting them to object arrays, though.

I don't see how this is the case. Only subclasses of ndarray should ever be calling `ndarray.__array_ufunc__` with themself as the self argument, and ndarray subclasses were never a candidate for object array coercion.

A counterargument against my proposal - for `A + B`, it allows class `A` to choose to hide itself and become an ndarray, even if `B` is willing to accept it.

**Comment by mhvk** [comment]
> A counterargument against my proposal - for `A + B`, it allows class `A` to choose to hide itself and become an ndarray, even if `B` is willing to accept it.

Is this true? If A passes on to `ndarray.__array_ufunc__`, your scheme above, where you only convert `self`, would turn `A` into an ndarray, but then `ndarray` would notice that `B.__array_ufunc__` exists and return `NotImplemented`; `B` would then see `A` again.

But there is a problem for (oddly), `a1 + a2` (different instances of `A`): my logic above would lead to a `TypeError`... This does seem to argue that `A.__array_ufunc__` better convert *all* instances of its own class to `ndarray` before supering...

**Comment by eric-wieser** [comment]
> but then ndarray would notice that B.__array_ufunc__ exists

Nope - `ndarray.__array_ufunc__` would end up calling `ufunc(ndarray, B)`, and then `B` would get its turn. 

> But there is a problem for (oddly), a1 + a2

While my case does handle that, it probably doesn't do anything helpful when `a1` tries to wrap the result of `ndarray.__array_ufunc__`, as it would discover that the result was already wrapped by `a2`.

> This does seem to argue that A.__array_ufunc__ better convert all instances of its own class to ndarray before supering

I think to avoid double-wrapping confusion, this is indeed the best strategy, regardless of how `ndarray.__ufunc__` pans out - I think we already recommend this in the example implementation?

**Comment by njsmith** [comment]
> I don't see how this is the case. Only subclasses of ndarray should ever be calling `ndarray.__array_ufunc__` with themself as the self argument, and ndarray subclasses were never a candidate for object array coercion.

The problem is that the conventional way Python dunder method dispatch works is that the initial call (`np.add(a, b)`) doesn't have any actual logic in it; all it does is dispatch to a dunder method (`a.__array_ufunc__` or `b.__array_ufunc__`) to implement the actual operation.

So if we follow this rule then we can infer that `ndarray.__array_ufunc__` should never return `NotImplemented`, because it knows how to handle ndarray subclasses (by treating them as ndarrays) and also how to handle non-ndarray subclasses (by coercing them to arrays). And it should certainly never invoke `__array_ufunc__` on some other object.

And similarly, the conventional dispatch rule would just be subclasses-before-superclasses, left-to-right.

But....... if you put these two rules together, then `ndarray + unrelated_obj` will never call `unrelated_obj.__array_ufunc__`, so something needs to break.

On further thought, I guess this the problem isn't actually caused by object array coercion behavior in particular, it's caused by having any coercion at all – a class that implements both `__array__` and `__array_ufunc__` creates the same problem. If `myclass` has `__array__` and `__array_ufunc__` methods, then obviously `np.add(ndarray_obj, myclass_obj)` should somehow end up calling `myclass.__array_ufunc__`, but if someone explicitly calls `ndarray.__array_ufunc__(ndarray_obj, np.add, "__call__", (ndarray_obj, myclass_obj))` then I *think* that should end up calling `myclass_obj.__array__`? I'm pretty sure it shouldn't call `myclass.__array_ufunc__`, at least.

In the original formulations of `__array_ufunc__` dispatch, this wasn't an issue because we phrased it as: first check for `__array_ufunc__`, then fall back to the old-style behavior, and implicitly assumed that `ndarray.__array_ufunc__` didn't exist, so ndarrays were handled by the fallback clause. The problem here comes from trying to adapt the system into something where it makes sense to have a `ndarray.__array_ufunc__`.

Clearly ufunc dispatch needs to special case ndarrays somehow. Two ways to conceptualize this I can think of:

* Option A: Adjust the rule to be: first check for `__array_ufunc__` *while ignoring any types that have `__array_ufunc__ == ndarray.__array_ufunc__`*, then fall back to the old-style behavior. (I think this is what's currently implemented?) The problem with this is that now `ndarray.__array_ufunc__` is just... totally unrelated to how actual ufuncs work, even conceptually. It could do literally anything and everything would still work, which means that we have no guidance to help us decide what it should do. Even if the ufunc implementation never actually looks up this method and calls it, I feel like this should be an invisible optimization, rather than part of the actual semantics – it should act *as if* it calls the method. So if we go this route my preference would actually be to leave `ndarray.__array_ufunc__` undefined. It seems more honest than throwing something arbitrary in? At the very least we should admit that the only contract is "do something that subclassers find so helpful that it's worth giving it this funny name just so they can call it using `super`". I really have no idea what that is; in general I feel like the most helpful thing we could do for subclassers is to convince them to stop subclassing ndarray :-)

* Option B: Adjust the rule to be: first, ufunc dispatch scans all the inputs calling `__array_ufunc__` methods. `ndarray.__array_ufunc__` is written so that it *never* coerces; if any of the arguments are non-ndarray-subclasses then it returns `NotImplemented`. If all `__array_ufunc__` methods return `NotImplemented`, then the dispatch code calls `asarray` on all the arguments, and then tries again (and this time `ndarray.__array_ufunc__` will succeed.

  ...but this would mean that calling `np.add(sparse_array, dask_array)` coerces both of them to ndarrays instead of raising `TypeError`, which seems really bad to me.

So, uh, maybe I only have one idea, and it's to give up on `ndarray.__array_ufunc__`. Anyone else got anything?

**Comment by mhvk** [comment]
Yes, in the `__array_ufunc__` section in `subclassing.py`: https://github.com/numpy/numpy/blob/master/numpy/doc/subclassing.py#L444

**Comment by eric-wieser** [comment]
> So if we follow this rule then we can infer that ndarray.__array_ufunc__ should never return NotImplemented ... ndarray + unrelated_obj will never call unrelated_obj.__array_ufunc__

This isn't true if `ndarray.__array_ufunc__` is allowed to reinvoke the ufunc - see my updated above comment with a callstack

**Comment by njsmith** [comment]
> This isn't true if `ndarray.__array_ufunc__` is allowed to reinvoke the ufunc - see my updated above comment with a callstack

Right, the sentence you quoted is saying that `ndarray.__array_ufunc__` should not be allowed to reinvoke the ufunc.

**Comment by mhvk** [comment]
@njsmith - we're stuck with subclasses ;-) And, given that, should support chains of them calling via `super` without having to check that the relevant parent actually has `__array_ufunc__` defined...

Anway, I think we are indeed in your option A and I think my plans are reasonably well stated as option B...  But with some modifications:
* Option B.2: Adjust the rule to be: first, ufunc dispatch scans all the inputs, calling `__array_ufunc__` methods. `ndarray.__array_ufunc__` is written so that it *never* coerces anything non-trivial (i.e., nothing but plain numbers, etc.); if any of the arguments are non-ndarray-subclasses then it returns `NotImplemented`. If all `__array_ufunc__` methods return `NotImplemented`, and at least one was not `ndarray.__array_ufunc__`, then the ufunc raises `TypeError`; otherwise, it falls back to old behaviour.

**Comment by mhvk** [comment]
@eric-wieser - I think it is really not a good idea to call the ufunc again without being sure that no arguments have an `__array_ufunc__`. This really should only be done by classes such as `MaskedArray` which need it to determine whether what they contain can be handled by the ufunc (see NEP).

**Comment by shoyer** [comment]
I'll throw out a proposal for types that ndarray could safely coerce in an `ndarray.__array_ufunc__` method:
- types corresponding to NumPy scalars (bool, int, float, complex, str, bytes)
- homogeneous lists of these types
- objects that implement `__array__` but not `__array_ufunc__`

I think that's it. In my fantasy world, `np.array()` would follow these same rules (aside from looking for `__array_ufunc__`).

**Comment by njsmith** [comment]
> @njsmith - we're stuck with subclasses ;-) And, given that, should support chains of them calling via super without having to check that the relevant parent actually has `__array_ufunc__` defined...

We're certainly stuck with not breaking existing subclasses. I'm *really really* not convinced that this means that numpy needs to actively support people using multiple inheritance hierarchies with multiple superclasses that all define `__array_ufunc__` and have it keep working over time as `__array_ufunc__` definitions disappear and appear (which is the case where what you said makes sense IIUC).

If people want to do that, then fine, cool, it's free software... but we *know* that it's going to be incredibly confusing and fragile, and if numpy inserts itself into that resolution chain in that then it means that when things break, it's our fault, and they'll show up in our bug tracker asking us to solve their essentially unsolveable self-inflicted problems. And then when we try to fix that it'll break someone else (see: confusing and fragile), and around we go again. For proof, see, like, every `__array_wrap__`/`__array_priority__`-related bug report.

I think we're much better off making the numpy side of things as simple as could possibly work, and then letting people who want to do really complicated things figure out how they want to adapt to that. Notice that your B.2 counter-proposal is dragging in two new subtle rules: a distinction between "trivial" and "non-trivial" coercion, and an extra embedded 'if' clause in the fallback rule. That's a pretty heavy cost when the only payoff is that we get to implement an `__array_ufunc__` method whose semantics we can't decide on and that we want to discourage people from using...?

@shoyer: I think you're at least missing the, umm, 4 different types of buffer interface (python 2 style buffers, PEP 3118-style buffers, `__array_interface__`, `__array_struct__`)?

The more I think about this the more I think maybe we should just drop `ndarray.__array_ufunc__` from 1.13, and we can think about adding it back later if we come up with some good principled semantics...

**Comment by shoyer** [comment]
I agree with @njsmith that we don't need to support complex inheritance chains. Inheritance for non-abstract types is fragile. Multiple inheritance and subclass hierarchies are *extremely* fragile. It's basically hopeless to support outside of a shared codebase and should not be encouraged.

>  I think you're at least missing the, umm, 4 different types of buffer interface

Thanks, edited to fix. This reminds me that it would be nice to actually define a `np.ArrayLike` abstract base class. Even if we can't make ufuncs themselves strict, we could perhaps use it for static typing (e.g., with mypy) to encourage sane type choices...

**Comment by mhvk** [comment]
Having slept on it, I think we actually answered what `ndarray.__array_ufunc__` should do in the NEP, which is place itself at the bottom of the type graph, implying basically what @shoyer stated. Specifically, it should *not* coerce subclasses that defined `__array_ufunc__`, since by doing so they explicitly state that they have incompatible type (see @pv's nice type graphs in the NEP); given this, I see little point in it coercing `self` -- I'd rather stick with the situation where @eric-wieser's example at the top raises a `TypeError` -- I don't think this is much of a burden for subclasses -- they need to recast the output anyway.

p.s. Separately, I really don't see what is wrong with `ndarray.__array_ufunc__` being there primarily for subclasses; it has been quite annoying that `ndarray.__array_finalize__` is `None` instead of just a function that does nothing.

**Comment by mhvk** [comment]
Maybe it is good to think a bit about a bigger picture: in mine, `ndarray.__array_ufunc__` *beomes* the actual implementation of the ufunc for arrays, and the `ufunc`s themselves just dispatch. One could imagine the constants to have their own `__array_ufunc__`, which implements the ufuncs for single numbers.

**Comment by pv** [comment]
The return of the revenge of the ndarray subclasses :)
.
The origin of the strange behavior here with the effect of overriding 
__array_ufunc__ seems to be that a particular ndarray subclass needs to 
signal if it is handled using legacy __array_priority__ mechanism or 
__array_ufunc__.
.
The current choice was to use __array_ufunc__ having a non-default value 
to signal this. This then means that merely defining it has side effects.
.
The other option is to use the presence of __array_ufunc__ to signal it, 
but this forbids having ndarray.__array_ufunc__ which also breaks the 
super() pattern.
.
The ideal situation could indeed be that ufunc dispatch is dumb and 
doesn't do any ndarray special casing, and ndarray.__array_ufunc__ does 
all the work. It doesn't sound impossible to do this, but keeping all 
the legacy stuff still working sounds like some careful thinking would 
be required. However, I'm not sure it can solve the issue that defining 
trivial __array_ufunc__ has side effects.

**Comment by njsmith** [comment]
> One could imagine the constants scalars to have their own `__array_ufunc__`

Doh, I'd forgotten about this issue too. We certainly can't have `ndarray.__array_ufunc__` define the real implementation without some implicit cast-to-ndarray rule in the dispatch, because there will always be tons of supported ufunc calls where no arguments have `__array_ufunc__`. It's not just scalars, it's also, like, lists and memoryviews and ...

And btw, numpy's scalar classes should presumably match ndarray, and either all have `__array_ufunc__` or none do, right?

Anyway, I guess another way to express my distress at not having a clear underlying theory here is that given a class like this:

```python
class foo(ndarray):
    def __array_ufunc__(self, *args, **kwargs):
        return super().__array_ufunc__(self, *args, **kwargs)
```

obviously the preferred behavior is that it should act identically to `ndarray`, and if that's impossible (as it seems to be) then I can cope with it raising an error because `
ndarray.__array_ufunc__` is undefined, but anything else seems truly bizarre and confusing. Obviously we *can* define it to do something, but the whole point here is to get away from complex fragile systems that we can't understand or touch without breaking things.

Note also that we can ship some ad hoc implementation now, or we can take our time and come up with a set of consistent semantics, but we can't do both. Once we start shipping ad hoc semantics then we'll get locked into supporting exactly the set of bugs we ship forever – experience with `__array_wrap__` makes this pretty clear I think.

**Comment by mhvk** [comment]
@pv described the issue well: the reason the `super` call doesn't work as quite expected is that without `__array_ufunc__` you get old behaviour, but by defining `__array_ufunc__` you have "chosen to live in the future", and in that future `ndarray` no longer is at the top, but rather at the bottom of the type-casting hierarchy, i.e., it no longer just assumes anything is an array.

Of course, the idea for `__array_ufunc__` was to help impose a type-casting hierarchy. But in consequence any class that defines `__array_ufunc__` and still wants to use the ufunc on array instances -- which would seem by far the most common use case -- has to replace all instances of itself before passing things on, whether or not the passing on is by calling the ufunc via `getattr(ufunc, method)` or via `super` (and then handle the output).

Now to get the example here working, one is effectively asking `ndarray.__array_ufunc__` to make assumptions about what its subclass (and associated type above it in the hierarchy) would want -- and the more I think about it, the more that seems a wrong-headed things to do: indeed, in practice, that `ndarray.__array_wrap__(self, obj)` "helpfully" changes the object to `type(self)` is exactly what causes quite a few problems.

Anyway, my suggestion would be to act on the actual title of this issue, which is that the error message is misleading, and otherwise give people a chance to try the current implementation. After all, we did explicitly note that the current API is provisional, and the fact that one should not pass on one's own classes in the arguments is explicitly documented.

**Comment by charris** [comment]
I think this should be closed. If any disagree, please reopen.
