### ISSUE TITLE
Behaviour change in 1.13 for expand_dims

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9100]
From the mailing list, this used to succeed, but now fails, thanks to [these lines](https://github.com/numpy/numpy/pull/8584/files#diff-ba13cf8822527da9907ca1822369030dR290) in #8584.

```python
x = np.zeros((2, 3, 4))
np.expand_dims(x, 20)
```

This failing absolutely seems like correct behaviour to me - unfortunately, correctness is not the metric we get to use, as this breaks matplotlib (matplotlib/matplotlib#8610).

Evidently, we need to restore the old behaviour, but with a deprecation warning

**Comment by njsmith** [comment]
For anyone else confused by this: it sounds like the old behavior was not to insert multiple dimensions so that the resulting array indeed had 20 dimensions, but rather to silently pretend the call said `np.expand_dims(a, a.ndim)`. Definitely a bit surprising and error prone.

Also definitely something that needs a nice long deprecation cycle to fix though...

**Comment by charris** [comment]
@eric-wieser Has this been fixed?

**Comment by eric-wieser** [comment]
No. Would appreciate if someone else could take this on. Should be a simple fix to limit the input to a.ndim

**Comment by charris** [comment]
I note that `normalize_axis_index` is not imported into the `np.` root. Was that intentional?

**Comment by eric-wieser** [comment]
Mainly just that adding a public function would probably incur a mailing list discussion - whereas adding an internal helper does not. In particular, `normalize_axis_index` does not support axis tuples.
