### ISSUE TITLE
numpy masked array regression in 1.13.0rc1

### ISSUE THREAD

**Issue by jswhit** [numpy/numpy#9121]
With version 1.12.1 the following script

```python
from numpy import ma, __version__
print __version__
x = ma.array(1, mask=True)
print x[...],type(x[...])
```

produced

```
1.12.1
-- <class 'numpy.ma.core.MaskedConstant'>
```

With 1.13.0rc1 I get

```
1.13.0rc1
-- <class 'numpy.ma.core.MaskedArray'>
```

This means that `x[...] is ma.masked` returns `False` in 1.13, when it used to return `True`.

So it appears that the behaviour of scalar masked arrays has changed.  This is causing test failures in [netcdf4-python](https://github.com/Unidata/netcdf4-python).

**Comment by ahaldane** [comment]
This was an intentional change in #8905, but we didn't note it in the release notes. (Probably we should).

I think the new behavior is more correct because in general indexing with `[...]` gives back an array, and converts scalars to arrays:
```python
>>> np.array(3)[...]
array(3)
>>> np.int64(3)[...]
array(3)
>>> np.arange(2)[...]
array([0, 1])
```

if you goal is to convert a 0d array to a scalar, I think you should replace `x[...]` in your code by `x[()]`. Indexing with `()` is the usual way of converting 0d-arrays to scalars, and in a sense is the opposite of indexing with `...`.
```python
>>> x = np.ma.array(1, mask=True)
>>> x[()] is np.ma.masked
True
```

**Comment by jswhit** [comment]
OK - thanks for the clarification.  Close if you wish.

**Comment by charris** [comment]
@ahaldane Probably worth a note in the 1.9.0 release notes under compatibility.
