### ISSUE TITLE
dot method with broadcasted array causes an error

### ISSUE THREAD

**Issue by unnonouno** [numpy/numpy#9165]
This code raises an exception.
```
import numpy

x = numpy.zeros(1, 'f')
x = numpy.broadcast_to(x, (2))
y = numpy.zeros((2, 2), 'f')
x.dot(y)
```
like this:
```
ValueError: On entry to SGEMV parameter number 8 had an illegal value
```

I checked source code and found a problem. `dot` method calls `cblas_matrixproduct`: https://github.com/numpy/numpy/blob/maintenance/1.12.x/numpy/core/src/multiarray/cblasfuncs.c#L242
And it calls `gemv` here: https://github.com/numpy/numpy/blob/maintenance/1.12.x/numpy/core/src/multiarray/cblasfuncs.c#L655
`cblas_?gemv` does not permit `incx = 0`: https://software.intel.com/en-us/mkl-developer-reference-c-cblas-gemv?language=en
But when a broad-casted array is given, its strides is zero, and `ap1s` is zero: https://github.com/numpy/numpy/blob/maintenance/1.12.x/numpy/core/src/multiarray/cblasfuncs.c#L653

Please check it.

I'm using numpy 1.12.1, Python 3.5.3 and Ubuntu 14.04.

**Comment by pv** [comment]
What is your `numpy.__version__`?

**Comment by unnonouno** [comment]
I updated the detail.

**Comment by eric-wieser** [comment]
Nice catch. Want to submit a patch yourself?

**Comment by k-kapp** [comment]
On a related note, please look at the line of code, and the preceding 2 LOCSs [here](https://github.com/numpy/numpy/blob/master/numpy/lib/stride_tricks.py#L119). Would the condition `not shape and array.shape` ever evaluate to `True`? If the `tuple` constructor can indeed return `None`, `0` or `False` (or other falsy values that I do not know of), then that might be the case, but otherwise, that condition either needs to be fixed or we should take the `if` block out.

**Comment by unnonouno** [comment]
OK, I'll try to make a patch. I'm planning to make a copy of an array on this situation. It requires additional memory, but I can use `gemv` function which is optimized. Is this plan OK?

**Comment by mattip** [comment]
This no longer fails. Closing
