### ISSUE TITLE
make np.seterr() and friends capable to distinguish between np and non-np FPU raises

### ISSUE THREAD

**Issue by dimpase** [numpy/numpy#9172]
One fallout from discussions in https://github.com/numpy/numpy/issues/9007 was that `seterr()` cannot always distinguish between FPU flags raised outside numpy and these raised inside numpy. The former are beyond numpy's control, and it ought to be possible to be able to ignore these, while keeping track of possible FPU flag raises inside numpy.

**Comment by njsmith** [comment]
I don't immediately see any way to do this... Can you give more details on what you have in mind?

**Comment by dimpase** [comment]
Naively, one could save the FPU status before calling outside code, and then compare the saved state of FPU with the new one. If there is a discrepancy, an error handler, set up in a function one could name `seterr_external()`, would be called.

**Comment by njsmith** [comment]
How are you defining "external code"? Right now we detect fp issues by comparing the state of the fpu before and after running a ufunc loop. Which ufunc loops are "external"? I would guess that the ones defined in `scipy.special` for example should probably be treated like any other floating point code, while your problem was with a ufunc loop that's built into numpy...

Eric's point that we might want to disable the `seterr` machinery for object loops makes sense but I'm not sure how to generalize that.

**Comment by eric-wieser** [comment]
Isn't this easy? The implementation just becomes "Don't check the FPU flags after an object loop" in numpy.

**Comment by dimpase** [comment]
"External" code is the code that deals with Python types which numpy does not know how to handle.

E.g. code that is in `a.__mul__(np.blah(...))`, called by ufunc after it found out it cannot handle `(np.blah(...)).__mul__(a)`, is an example of such an "external" ("supernatural", so to speak) code. 

As opposed to external library code e.g. lapack, that numpy calls to deal with linear algebra on numpy data, is not "external" in the sense I am talking about. (nothing "supernatural" for numpy here).

Perhaps the ufunc situation (and vectorised versions of this situation) are the only cases that need to be looked into, I don't know.

**Comment by eric-wieser** [comment]
Given that we used it to diagnose this problem, `np.frompyfunc` also should consider dropping the FPU flags, but maybe that's a subset of object loops

**Comment by seberg** [comment]
I am going to close this, mainly because it is pretty old and there is no clear TODO here, beyond skipping FPE checks (which I am planning on supporting).

We can skip checking the floating point exceptions for object loops, etc. (and I am planning to do this).  I guess that should be a 95% solution only in any case though.  NumPy will sometimes chain multiple things (e.g. a ufunc with casts) and that could mean that we chain an object loop (that does not need FPE flags) with a cast that does need them.  And untangling them would seem pretty tricky – or at least slow (and require flagging an operation as "may poison FPE flags").
