### ISSUE TITLE
RuntimeError: "release unlocked lock" in numpy mtrand.RandomState.randint

### ISSUE THREAD

**Issue by yangkky** [numpy/numpy#9192]
#### Description
While training a model in gensim, I sometimes get a RuntimeError:

```
2017-05-09 13:37:56,183 : INFO : PROGRESS: at 96.88% examples, 409235 words/s, in_qsize 15, out_qsize 0
Exception in thread Thread-34:
Traceback (most recent call last):
  File "/Users/kevinyang/anaconda/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/kevinyang/anaconda/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kevinyang/anaconda/lib/python3.5/site-packages/gensim/models/word2vec.py", line 822, in worker_loop
    tally, raw_tally = self._do_train_job(sentences, alpha, (work, neu1))
  File "/Users/kevinyang/anaconda/lib/python3.5/site-packages/gensim/models/doc2vec.py", line 717, in _do_train_job
    doctag_vectors=doctag_vectors, doctag_locks=doctag_locks)
  File "gensim/models/doc2vec_inner.pyx", line 428, in gensim.models.doc2vec_inner.train_document_dm (./gensim/models/doc2vec_inner.c:5444)
  File "mtrand.pyx", line 1266, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:15836)
RuntimeError: release unlocked lock
```
This is reproducible for the same inputs, but does not happen for all inputs. 

The line of gensim that calls the numpy code that gives the error is here: 
https://github.com/RaRe-Technologies/gensim/blob/fdc01ab1ee350ce223ab9209e911352fba5d4290/gensim/models/doc2vec_inner.pyx#L428

And I reported the bug to gensim here: 
https://github.com/RaRe-Technologies/gensim/issues/1311

#### Steps/Code/Corpus to Reproduce
Unfortunately, I don't know how to reproduce this on a smaller corpus. I've attached the training code (in a Jupyter notebook). 
[bug_report.zip](https://github.com/RaRe-Technologies/gensim/files/988035/bug_report.zip)

The corpus used in the code is [here](
https://drive.google.com/file/d/0BzIF1ox2Vmq5RkUyU2dNWkswS2s/view?usp=sharing):

#### Versions
```
Darwin-16.5.0-x86_64-i386-64bit
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
NumPy 1.12.1
SciPy 0.19.0
gensim 1.0.1
FAST_VERSION 1
```

**Comment by charris** [comment]
I assume that `model.random.randint` is in fact `numpy.random.randint`. This is the first report of this error that I have heard of and it is a bit strange because, IIRC, the locks are all handled by a context manager. The code could probably use another inspection, but other things could be in play.

**Comment by njsmith** [comment]
> File "mtrand.pyx", line 1266, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:15836)

> NumPy 1.12.1

This is also odd... I tried checking out the v1.12.1 tag, and line 1266 of mtrand.pyx is in the middle of a docstring, and mtrand.c:15836 is somewhere irrelevant too. Where did you get your numpy?

**Comment by njsmith** [comment]
Oh, from the gensim bug report I see that the error message is actually from numpy 1.11.1, which puts us [here](https://github.com/numpy/numpy/blob/v1.11.1/numpy/random/mtrand/mtrand.pyx#L1266), which makes more sense, in that that is a line where it attempts to release a lock :-).

It's still weird though since, like @charris says, every access to that lock is using a `with` statement, so it shouldn't be possible for the lock to be unlocked already when we try to release it. Something funny must be going on.

Are there multiple threads accessing the `RandomState` object?

**Comment by yangkky** [comment]
Sorry, yes the error I posted is from version 1.11.1. I still get the error sometimes with 1.12.1 though. I'm trying to reproduce it now so I can show that error message.

**Comment by pv** [comment]
Is gensim or you using multiprocess, or is all code single-process?

**Comment by yangkky** [comment]
gensim is using multiprocess.

**Comment by pv** [comment]
Then gh-9248 is likely related.

**Comment by mattip** [comment]
Closing. Please reopen if it is still relevant and not solved by the new random APIs for handling forked processes.
