### ISSUE TITLE
BUG: MemoryError during != masquerades as NotImplemented

### ISSUE THREAD

**Issue by JohnGallant** [numpy/numpy#9277]
This applies to numpy versions:
 - 1.10.1 tested on Linux with Python 2.7.10 
 - 1.11.1 tested on Windows with Python 2.7.11

This is the expected behaviour:
```
>>> small = np.ones((100,100),dtype=np.float32)
>>> small != 0
array([[ True,  True,  True, ...,  True,  True,  True],
       ..., 
       [ True,  True,  True, ...,  True,  True,  True]], dtype=bool)
```

With a suitably-sized large array, I get:
```
>>> big = np.ones((40000,50000),dtype=np.float32)
>>> big != 0
True
```

Digging a little:
```
>>> big.\_\_ne__(0)
NotImplemented
```

which was rather confusing until I tried:
```
>>> np.not_equal(big,0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
```

So it seems that if there is a MemoryError during creation of the boolean output array, the exception is caught but misinterpreted, NotImplemented is raised instead and the evaluation of '!=' reverts to a Python object comparison. Obviously this will only happen when the 'big' array is around the right size so that it fits in memory but uses most of available memory. In the case shown above, available memory is a bit over 8GB.

**Comment by seberg** [comment]
My guess is that this is pretty much fixed:
```
In [14]: big != 0
/usr/local/bin/ipython:1: DeprecationWarning: elementwise != comparison failed; this will raise an error in the future.
  #!/usr/bin/python3
Out[14]: True
```
if you do `import warnings; warnings.simplefilter("always")` (or the according python flags on startup), you should see the deprecation warning, though I am not sure since when it exists, but I do think it should be there on 1.11.

One could think about special handling certain errors I suppose, since for a MemoryError to "just don't raise errors" doesn't make much sense. I wonder what python policy is on this, since normally, at least for a long time, comparison did not raise errors.

**Comment by njsmith** [comment]
In python in general comparisons are allowed to raise errors; it's just that there's a strange bit of code in numpy's comparison functions that swallows all errors and then returns `NotImplemented`. This is a great example of why that's a bad idea :-).

To be clear, @seberg isn't saying that this is fixed in any released version of numpy, but rather that we already started the process of fixing it a while back (by adding the `DeprecationWarning`), and it's on the list to fix for real in some upcoming release.

**Comment by JohnGallant** [comment]
Thanks for the quick responses. Yep, the deprecation warning is there in both 1.10 and 1.11 when it is turned on ... although a hidden deprecation warning for a runtime error is not exactly ideal! 

I really appreciate the work that has gone into numpy, and it's only when something weird like this happens that I realise how much hidden cleverness there is under the hood, which nearly always does what I want.

**Comment by seberg** [comment]
Yeah DeprecationWarnings are hidden in python, we sometimes do a VisibleDeprecation warning (so another warning type) to flush them up a bit more. Here, maybe we should actually go that way for one release.
