### ISSUE TITLE
BUG: np.void(b'test') enters recursion loop in repr

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9345]
Regression in #8983, perhaps. @ahaldane?

**Comment by ahaldane** [comment]
Yes, I have come across some infinite recurions as a result of #8983 too. But I didn't want to work on a fix yet since I think #8981 (perhaps also #9332) will fix it, hopefully soon.

**Comment by ahaldane** [comment]
LGTM. Either update or let me know you don't want to change the test, and I think we can merge.

**Comment by mattip** [comment]
Any progress on this? It seems like a serious regression

**Comment by mattip** [comment]
This issue is causing a ``RuntimeError('maximum recursion depth exceeded',)`` when calling ``testing.assert_equal`` on a ``np.void`` in the ``build_err_msg`` function, i.e. in ``test_scalar_copy`` from ``test_regression.py`` which was added lately. Lucky for CPython that can be caught, unfortunately it crashes the PyPy interpreter.

**Comment by eric-wieser** [comment]
I think some serious thought needs to go into which code has the job of printing arrays and scalars. We're in this mess because:

* Some scalars do `repr(np.array(self))
* Some arrays do `repr(arr[idx])` on each item

Of course, this gives a potential for co-recursion.
Unfortunately, in 1.13, the break in this co-recursion depended on the data type, and the regression accidently assumed it was cut in the same place each time
It'd be great if we could make this link unconditionally cut.
