### ISSUE TITLE
ENH: Port scipy's refguide-check 

### ISSUE THREAD

**Issue by charris** [numpy/numpy#9415]
Port scipy's refguide-check. This is a test run at checking, I think. @ev-br Could you add some details?

**Comment by rgommers** [comment]
Here's the checker: https://github.com/scipy/scipy/blob/master/tools/refguide_check.py

The docstring at the top of that file has details on what it does. A plan of attack for this issue:

- Copy the file to the ``tools/`` dir in the numpy repo
- Change the occurrences of ``scipy`` with ``numpy``, same for listing of submodules 
- Run it manually, find missing entries in the numpy reference guide.
- Fix those, rinse and repeat. Instead of fixing, some numpy entries likely have to be added to the list of things to skip.
- Once things work locally, add to the numpy TravisCI build matrix (like https://github.com/scipy/scipy/blob/master/.travis.yml#L25)

**Comment by tylerjereddy** [comment]
Mostly dealt with by #12253 -- there will have to be follow-up PRs to refine behavior and add missing functions / submodules, but let's deal with those in smaller issues / PRs as needed.
