### ISSUE TITLE
DOC: Add extended documentation of '@' operator,

### ISSUE THREAD

**Issue by charris** [numpy/numpy#9419]
@rgommers 

>Another idea, from the "deprecate np.matrix" discussion: add numpy documentation describing the preferred way to handle matrices, extolling the virtues of @, and move np.matrix documentation to a deprecated section.

**Comment by melissawm** [comment]
If this is still relevant, I'm wondering if the best place to add this discussion on the `@` operator is [this page on linear algebra](https://numpy.org/devdocs/reference/routines.linalg.html). Note that this page is actually a mix of common linear algebra operations and functions in the `np.linalg` module - maybe they should be split up? Finally, the [ndarray](https://numpy.org/devdocs/reference/arrays.ndarray.html) documentation says:

> Matrix operators `@` and `@=` were introduced in Python 3.5 following PEP465. NumPy 1.10.0 has a preliminary implementation of `@` for testing purposes. Further documentation can be found in the matmul documentation.

Can we lose the *preliminary/testing purposes* warning?

**Comment by rgommers** [comment]
> If this is still relevant, I'm wondering if the best place to add this discussion on the `@` operator is [this page on linear algebra](https://numpy.org/devdocs/reference/routines.linalg.html). 

I would say yes to mentioning `@` there and a one line to one paragraph summary of what it does. Not all users know what it is, so that would make it more discoverable. For the rest it should refer to the `matmul` docs I'd say.

> Note that this page is actually a mix of common linear algebra operations and functions in the `np.linalg` module - maybe they should be split up?

I don't think so. The docs are arranged by functionality, not by module. And the split between linear algebra functionality in the main namespace and the `linalg` one is mostly an accident of history.
