### ISSUE TITLE
Floating point invalid signal on nan comparisons on Win vs. OSX/Linux

### ISSUE THREAD

**Issue by pv** [numpy/numpy#9513]
Not sure if this is a bug, but the behavior of floating point warnings differs on linux vs. Windows:
```
>>> import numpy as np
>>> with np.errstate(invalid='raise'):
...    np.array([np.nan]) > 0
```
It does not appear to raise FloatingPointError on clang/gcc on Linux/OSX. It raises on Windows 64-bit (on numpy 1.13.1 as shipped by Anaconda, and also apparently by the Numpy wheels on pip, both MSVC-compiled?).

C99 as I understand specifies that `nan > 0` should signal. Why the behavior differs from C99 (vectorization?)?

It would be nice if this numpy behavior wasn't platform-dependent. It can be worked around of course, but it seems like it should not be like this in the ideal case (iow, it's annoying if you write clean code on one platform, and then it spams warnings on another). 

Maybe numpy should just ignore the invalid flag in comparisons, if that is the de facto behavior?

**Comment by seberg** [comment]
Going to close this.  We can open a new issue though:

NumPy now *never* signals for these, the history is that gcc didn't signal for a long time, at least when SSE was used and eventually the signals were blanket ignored.  Rather than reintroducing them, I switched to the `C99` `is_lessequal`, etc. family of functions.  The SSE code (unfortunately) probably still clears FPEs manually.  (Maybe some other code also, because some compilers used to have issues around FPEs)
