### ISSUE TITLE
Multivariate Lognormal

### ISSUE THREAD

**Issue by dmadeka** [numpy/numpy#9525]
Quick Question - Is there any interest in having a multivariate lognormal sampler in NumPy? The mapping from a multivariate normal isn't direct, and there are some minor nuances to take care of. Something like: https://gist.github.com/dmadeka/5ee0c54ba5184235830594d769d9520b

**Comment by njsmith** [comment]
It seems like a useful thing in general, but I have a concern: numpy's existing `lognormal` takes `mean` and `sigma` parameters that specify the standard parameters for the underlying normal, *not* the mean and sd of the actual lognormal distribution. The part of your code that makes it trick and valuable is that you parametrize by the mean and covariance matrix of the actual lognormal. But it's going to be very confusing if we have a `lognormal` and `multivariate_lognormal` that have different and incompatible interpretations of their parameters.

Anyone have any ideas how we could support both of these calling conventions without it being really confusing?

**Comment by dmadeka** [comment]
@njsmith Ahh, right. I think in many cases, you have the mean and covariance of the lognormal itself (say if you're modeling those parameters directly), and would like to generate more samples for it. 

Let me think about it - but the obvious solution is to have a parameter like (this is bad naming) `param_type='lognormal'` and keep the default behavior to be just sampling the multivariate normal with the mean and covariance that is passed to the function and then exponentiating? So, by default the `multivariate_lognormal` behaves like the `multivariate_normal` but it allows an override and maybe the `lognormal` can as well?

**Comment by dmadeka** [comment]
@njsmith Any ideas on this?

**Comment by shoyer** [comment]
It's not clear to me that there is actually a strong need for this. Is there other software that provides precedent for using the mean and standard deviation of the result to parameterize a log normal distribution? R, for example, uses the same convention as NumPy: https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Lognormal.html

To be honest, I'm not even sure it makes sense to have a log-normal random number generator in NumPy in the first place, given that the implementation simply `exp(random_normal(...))`. Obviously we

**Comment by dmadeka** [comment]
@shoyer Actually, I would argue it's more useful than the canonical lognormal, which is just an exponentiation. The need is if the parameters of a distribution are inferred from another source, and the distributional assumption is lognormal - sampling when you have the mean and variance of the lognormal adds a layer of complexity. For example, I needed to derive it myself to do it - and realized all my R colleagues use [a hacked version](https://www.rdocumentation.org/packages/MethylCapSig/versions/1.0.1/topics/mvlognormal) - that doesn't have the spectral clipping etc. If there was a numpy equivalent to tf.contrib, that would probably be the ideal place for this

**Comment by eric-wieser** [comment]
Does this perhaps belong in `scipy.stats`?

**Comment by WarrenWeckesser** [comment]
What is the current appetite for adding more distributions to `random`?  I suspect it is fairly low, and even if there is interest in adding more, I wouldn't give the multivariate log-normal distribution a high priority.  SciPy is probably a better place for it (but it is a bigger project for SciPy, because it requires adding all the distribution functions, not just random variate generation).

**Comment by rkern** [comment]
Practically 0, at least for more "named" distributions like this one. I do think there might be some room to fill out some of the more fundamental building blocks, like having all of the possible endpoints for sampling U(0, 1): `[0, 1]`, `(0, 1)`, `(0, 1]`, in addition to the current `[0, 1)`, or [Campbell's algorithm for sampling all possible normal floats in `[0, 1]`](https://mumble.net/~campbell/2014/04/28/uniform-random-float). Maybe some more options for shuffles or choices that don't fit into the current call signatures for one reason or another.

The one exception to the "no more named distributions" might be a `bernoulli(p)` because it's a pretty fundamental building block. I thought more people knew the `random() < p` trick (though that I naturally called it a "trick" rather than an "idiom" ought to have been a clue), but have seen some contortions in the wild using `binomial(1, p)` instead.

As far as SciPy's concerned, multivariate distributions don't need a whole lot because there isn't actually much shared infrastructure for them that the univariate ones, just some common conventions for the methods that one is able and ready to implement. I, for one, am happy to include multivariate distributions that just have sampling implemented. Often, that's the only useful thing that is _worth_ implementing for them.
