### ISSUE TITLE
NaT significantly slows down comparison and arithmetic operations with numpy.datetime64 and timedelta64

### ISSUE THREAD

**Issue by dmbelov** [numpy/numpy#9528]
Here are the examples that show how slow they
```
numpy.random.seed(0)
time_delta_i = numpy.random.randint(0, 1e6, 1e6).view('m8[us]')

%timeit time_delta_i < numpy.timedelta64(1, 'm')
1000 loops, best of 3: 1.55 ms per loop

time_delta_i[::10] = numpy.timedelta64('NaT')
%timeit time_delta_i < numpy.timedelta64(1, 'm')
/usr/bin/anaconda/bin/ipython:257: FutureWarning: In the future, 'NAT < x' and 'x < NAT' will always be False.
10 loops, best of 3: 118 ms per loop
```

Can this be fixed?

**Comment by seberg** [comment]
Haahahahaha, awesome, yes, this can be fixed/improved. (the FutureWarning seems to be given for every single NAT, instead of at least only once per inner loop run). Will change the behaviour a tiny bit when the error is raised, but I am not worried about that. Mind you, even then it might be given more then once in some cases, but it should be pretty untypical at least.

I am a bit confused, which numpy/python versions are you using? beause the randint line for me does not like the `1e6` (correctly), but the NAT warning is also quite new I thought.

**Comment by seberg** [comment]
Ok, that was funny and easy enough, create a PR to close it, note that even then it will be slower, but less then a factor of two probably.

Mind you, this is not perfect, but it is tricky to get perfect. In uncommon (hopefully) cases, it can still be much slower and kill threading performance. Luckily at some point the warning period is over, and this does not matter anyway.

**Comment by seberg** [comment]
Especially when you have different time units, it should still happen once for every 8000 elements or so unfortunately.... Not sure how much that means speed wise.
