### ISSUE TITLE
numpy.sum result is different from python build-in sum

### ISSUE THREAD

**Issue by mailbox4ad4** [numpy/numpy#9596]
I use 1.13.1 to test below code.

I create a 441 sine wave sample, then use numpy.sum and python build-in sum function to calculate the result. It is very strange that is when my sample is 440, then result is almost the same. If my sample size is 441, then result become very different. demo code as below:

```
from math import sin, pi
import numpy

signal = []
step = 360.0 / 441
current = 0.0
for i in range(0, 441):
    signal.append(sin(current * (pi / 180.0)))
    current = current + step
    if current >= 360:
        current = current - 360

signal440 = signal[:440]
print("441  numpy.sum = ", numpy.sum(signal))
print("441 normal sum = ", sum(signal))
print("440  numpy.sum = ", numpy.sum(signal440))
print("440 normal sum = ", sum(signal440))
```
Result is:
```
441  numpy.sum =  -1.08002495836e-12
441 normal sum =  -1.1547308248482935e-12
440  numpy.sum =  0.0142471037061
440 normal sum =  0.014247103705947308
```
0.1 difference is very large to me.
What do I miss ? Do I use numpy.sum in the wrong way ?
Please help~

**Comment by njsmith** [comment]
It's not a difference of 0.1, it's a difference of 0.1 × 10**-12 (notice the "e-12" at the end). Your sums after 440 points are also different by about 0.1 × 10**-12, but you don't care because the numbers are much larger overall. The only thing that changed is that all your numbers became very close to zero, so now the same difference "feels" much larger. This is called "catastrophic cancellation", and is an unavoidable aspect of working with floating point.

`math.fsum` uses a slow-but-exact summation algorithm, and for me it returns -1.0485102369672816e-12, so it looks like in this case `numpy.sum` was slightly more accurate than `sum`. But it hardly matters, because even just calculating the `sin` values in the first place already introduced a similar amount of error, and there's no point in trying to get 30 digits of precision on the summation when the numbers you're trying to sum only have about 16 digits of precision.

**Comment by eric-wieser** [comment]
That's a 0.000_000_000_001 difference, not a 0.1 difference. This kind of thing happens because in general, (a + b) + c != a + (b + c) for floating point numbers.

**Comment by mailbox4ad4** [comment]
Understood, thank for the reply
