### ISSUE TITLE
Segmentation fault when trying to convert numpy array to the C array with ctypes

### ISSUE THREAD

**Issue by creotiv** [numpy/numpy#9647]
Python 2.7.12
Numpy 1.13.0

Here is error reproduction:
```
import numpy as np
from ctypes import POINTER, c_float

data =  np.ascontiguousarray(np.array([1]*10000, dtype=np.float32)/255).ctypes.data_as(POINTER(c_float))
print data.contents.value # ok

data =  np.ascontiguousarray(np.array([1]*1000000, dtype=np.float32)/255).ctypes.data_as(POINTER(c_float))
print data.contents.value #giving segmentation fault
```

**Comment by creotiv** [comment]
Also as mention (Ixop) 
If brake that on two lines then no segmentation fault raised
```
x = np.ascontiguousarray(np.array([1]*10000000, dtype=np.float32)/255)
data = x.ctypes.data_as(POINTER(c_float))
print data.contents.value # no more segmentation fault
```

**Comment by pv** [comment]
This looks like correct behavior. The ctypes pointer is raw data 
pointer, and does not force the original array to stay alive. You need 
to explicitly hold a reference to the original array to keep it alive. 
Otherwise, Python will free it and you get the crash when you try to 
access the now-freed memory.
.
That you don't get segmentation fault in the first case is good luck 
(probably behavior of the allocator etc.) -- the memory is already freed 
and referencing it is not valid.

**Comment by creotiv** [comment]
If two same lines of code giving different result it's not a correct behavior.
There should be added exception to not use inline linking in this situation.

**Comment by pv** [comment]
If you are dealing with raw memory pointers, you are supposed to know 
about and explicitly deal with the life cycle management of the buffers.

**Comment by eric-wieser** [comment]
@creotiv, what do you mean by "inline linking"?

**Comment by creotiv** [comment]
sorry, i mean dot-linking.

4 Сен 2017 г. 20:42 пользователь "Eric Wieser" <notifications@github.com>
написал:

@creotiv <https://github.com/creotiv>, what do you mean by "inline linking"?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/numpy/numpy/issues/9647#issuecomment-327007353>, or mute
the thread

**Comment by eric-wieser** [comment]
Seems like the fix here is to add a reference from the ctypes object to the array
