### ISSUE TITLE
ENH?: Add `compiler` and `fcompiler` to facilitate MKL building

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#9662]
When building with MKL, I currently need to do:
```
python setup.py build --compiler=intelem install
```
Then for SciPy it's worse/longer:
```
python setup.py config --compiler=intelem --fcompiler=intelem build --compiler=intelem --fcompiler=intelem install
```
If we could add a `compiler` and `fcompiler` option to `site.cfg` (that I could store in `~/.numpy-site.cfg`) these could both just become `python setup.py install`. Would it be okay to add this option?

A related problem is when I do `./runtests.py` for SciPy, it builds with GCC, even though my standard install uses ICC / MKL. I assume that these `compiler` / `fcompiler` options would be read during the `./runtests.py` phase, too, which would fix this problem, too.

**Comment by rgommers** [comment]
You can already specify ``compiler`` in ``setup.cfg`` (see e.g. https://stackoverflow.com/questions/3297254/how-to-use-mingws-gcc-compiler-when-installing-python-package-using-pip for format), and it's possible to add more options there (e.g. http://renesd.blogspot.co.nz/2017/02/setupcfg-solution-to-python-config-file.html).

However there's two issues with doing it that way:
1. IIRC you have to put ``setup.cfg`` in the ``distutils`` directory, it won't find ``~/setup.cfg``.
2. You may not want this for all packages but only for ones using ``numpy.distutils``. 

And ``site.cfg`` makes sense as well if things are coupled like ICC and MKL are (because MKL paths are in ``site.cfg`` already). So this sounds fine to me. And yes, it would be picked up when using ``runtests.py``.

**Comment by InessaPawson** [comment]
Given numpy.distutils has been officially deprecated, do we wish to continue working on this PR or should we close it?
