### ISSUE TITLE
DOC: Make it more clear that np.array is not a type

### ISSUE THREAD

**Issue by Kristian60** [numpy/numpy#9739]
unexpected behavior - for me that it.
Maybe this is by design, but i found them to be odd.

```
isinstance(np.array(1),np.array)
>>> TypeError: isinstance() arg 2 must be a type or tuple of types

isinstance(np.array(1),(np.ndarray, np.generic))
>>> True
```

and being an array this puzzled me a bit
```
len(np.array(1))
>>> TypeError: len() of unsized object

np.array(1)[0]
>>> IndexError: too many indices for array
```

**Comment by mhvk** [comment]
@Kristian60 - `np.array` is just a function to return an `np.ndarray` instance from much more arbitrary input than the class can handle:
```
In [22]: type(np.array(1))
Out[22]: numpy.ndarray
```

As for the second item, if you do not give any dimensions, the result is a so-called "array scalar", which is 0-dimensional and hence has no length and is not indexable; in many ways, it is like a single integer.

Since your report is mostly about confusion about implementation, would you have a suggestion on how to document things better?

**Comment by charris** [comment]
```
In [1]: isinstance(np.array(1),np.ndarray)
Out[1]: True

In [2]: np.array(1)[()]
Out[2]: 1
```

Note that `np.array` is a function, not a type, and that scalar arrays cannot be indexed with numbers, but rather with `()` or `...`.

**Comment by sameshl** [comment]
@eric-wieser Is this still a problem? I could fix the documentation if required.

**Comment by mattip** [comment]
@sameshl where would you suggest changing it? I would be more tempted to close this without changing anything

**Comment by sameshl** [comment]
@mattip I could make it more it more clear by adding it under a `..note::` directive at https://docs.scipy.org/doc/numpy/user/quickstart.html#array-creation if needed. But now that I see that it is pretty well documented under the same section, even I think closing this issue might be the best option if the current documentation seems alright to you

**Comment by mattip** [comment]
Closing
