### ISSUE TITLE
Cython .27 breaks NumPy on Python 3

### ISSUE THREAD

**Issue by charris** [numpy/numpy#9754]
```
    numpy/random/mtrand/mtrand.c: In function ‘__pyx_pymod_exec_mtrand’:

    build/src.linux-x86_64-3.6/numpy/core/include/numpy/__multiarray_api.h:1537:144: warning: return makes integer from pointer
```
I've opened a Cython issue https://github.com/cython/cython/issues/1882, but we need to fix our testing environment until it gets fixed.

**Comment by scoder** [comment]
This is a bug in NumPy. It should be raising a proper exception here, via Cython code, instead of raising the exception from C and then returning with an explicit return value (that Cython cannot see or control) from the Cython generated module init function. Basically, it's executing a return from global module code here.

Could you change the import macro into an inline function written in Cython code? That should fix it.

**Comment by mattip** [comment]
this seems to have been fixed, can we close it?

**Comment by charris** [comment]
Yes, go ahead.
