### ISSUE TITLE
Linspace silently fails with single-value multidimensional inputs for endpoints

### ISSUE THREAD

**Issue by seth-a** [numpy/numpy#9759]
For example

    linspace(-array([[3]]), 5, 10)

produces 

    array([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.]])

This should probably throw an error, as it will if there is more than a single value:

    linspace(-array([[3, 3]]), 5, 100)

Or get the single value, which happens if the array is one dimensional:

    linspace(-array([3]), 5, 10)

    
    array([-3.        , -2.11111111, -1.22222222, -0.33333333,  0.55555556,
        1.44444444,  2.33333333,  3.22222222,  4.11111111,  5.        ])

**Comment by lagru** [comment]
@seth-a Thank you for reporting this!

NumPy's behavior for your examples has changed (at least) since version 1.16. With that version `numpy.linspace` accepts array_like values for `start` and `stop` and inserts a new dimension at `axis`. With that your examples give:

<details>
<summary>Click to expand</summary>

```python
>>> np.linspace(-np.array([3]), 5, 10)
array([[-3.        ],
       [-2.11111111],
       [-1.22222222],
       [-0.33333333],
       [ 0.55555556],
       [ 1.44444444],
       [ 2.33333333],
       [ 3.22222222],
       [ 4.11111111],
       [ 5.        ]])
>>> np.linspace(-np.array([[3, 3]]), 5, 100)
array([[[-3.        , -3.        ]],

       [[-2.91919192, -2.91919192]],

       ... shortened ...

       [[ 4.91919192,  4.91919192]],

       [[ 5.        ,  5.        ]]])
>>> np.linspace(-np.array([3]), 5, 10)
array([[-3.        ],
       [-2.11111111],
       [-1.22222222],
       [-0.33333333],
       [ 0.55555556],
       [ 1.44444444],
       [ 2.33333333],
       [ 3.22222222],
       [ 4.11111111],
       [ 5.        ]])
```

</details>

I testet this on `master` and `maintenance/1.16.x`. I assume that you encountered a valid bug which got fixed on the way. 

@charris If you have the time, I think this issue can be closed.

**Comment by mattip** [comment]
Closing. Please reopen if I misunderstood, and report the version of NumPy and python you are using
