### ISSUE TITLE
Variable length array inside record array?

### ISSUE THREAD

**Issue by PeterKucirek** [numpy/numpy#9811]
Hello,

I've been experimenting with the very powerful [structured arrays](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.rec.html) feature of NumPy to store some very complex data types. I know that it's possible to specify a sub-array like so:

```python
import numpy as np
test_type = np.dtype([('index', 'i4'), ('data', 'f8', 8)])
```

In this case, `test_type` contains a 8x1 sub-array called "data". 

My question is: it it possible to specify "data" as above, but with a variable length per record? So some records might have 2 elements, and other might have 10 elements. 

I should mention that using an `object` dtype and storing a Python List is totally out of the question, as I need this to work inside a Numba accelerated kernel.

Thanks

**Comment by ahaldane** [comment]
No, in general numpy can't have variable-sized datatypes because it needs to be able to index and iterate over memory by assuming all elements have the same size (using the array strides). 

You can think of numpy-arrays a lot like C-arrays, and structured-types are like C-structs. You can't have variable-sized struct arrays in C either.

By the way, we are in the process of rewriting the structure array docs for 1.14 in #9056. You can check out a preliminary version [here](https://ahaldane.github.io/user/basics.rec.html), if you happen to find anything is unclear, let us know.

I'm going to close for now, but feel free to discuss further.
