### ISSUE TITLE
Unexpected behavior when indexed additive assignment to an ndarray

### ISSUE THREAD

**Issue by itumekanik** [numpy/numpy#9830]
import numpy as np
A = np.zeros( (4, 4) )

#Expected behaviour is A[0,1] be 20 but it is not the case 
A[[0, 0],[1, 1]] += [10, 10]

print(A)
print(A[[0, 0],[1, 1]])
print(sum(A[[0, 0],[1, 1]]))
print(A)

**Comment by kenogo** [comment]
Well, so it took me a while to understand what you mean. But I think I got you now. However, I don't think there are unexpected results here! Let's look at what's happening.

```
>> print(A[[0, 0], [1, 1]])
[0. 0.]
```

This is crucial. Because this is what you're adding too. You're just adding arrays. So the result of your sum is ```[10, 10]```. Now what your assignment does is it first assigns the first 10 to `A[0, 1]` and then it assigns the second 10. There's no way to change this behavior to your code, and it's completely expected behavior, because `+=` FIRST adds, THEN assigns. It doesn't do some weird stuff like, adding the first part of an array, assigning the sum, and then adding the second part.

**Comment by MSeifert04** [comment]
I think what you want is an unbuffered operation, for example [`np.add.at`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ufunc.at.html)

**Comment by itumekanik** [comment]
Thank you for your comments... My purpose in expecting  A[0,1] be 20 was for finite element assemblage purposes. It would be nice if i could do something like this and everything adds up correctly (which by the way things work as is in scipy sparse solvers)

rows = [0, 3, 2, 0 ....... ]
cols  = [1, 4, 5, 1 .......]     #the first and 4th numbers in each array are the same so the corresponding data
                                       #should be added to give 20
data =[10, 60, 80, 10, .....]

A[rows, cols]+=data

At the same time i completely understand the current behavior have same use cases which may also be meaningful but my expectation is not so weird i believe. 

if i was performing the same operation element wise with ordinary loop such as:

N = len(rows)  #assuming cols have the same lenght
for i in range(N):
    A[row(i), col(i)] += data[i]
 
The result for  A[0,1] will definitely be 20.....

**Comment by seberg** [comment]
This is already impossible becasue there is no such operation as `a[...] += b`, this operation is actually  just `tmp = a[...] + b; a[...] = tmp` (python will do this, not numpy).

The unbuffered thing is the right hint, it is right now very slow, so for addition I would point to `np.bincount` which, most of the time, should be able to handle it as well, and is much faster.

Anyway, feel free to discuss, or note if you think it is still an issue, but right now I think there is nothing we can possibly do here.
