### ISSUE TITLE
chained comparisons??

### ISSUE THREAD

**Issue by DylanDmitri** [numpy/numpy#9857]
Support for chained comparisons? I want to be able to use

`1940 <= data.yearID <= 1942`

rather than

`(1940 <= data.year) & (data.year <= 1942)`

Probably ya’ll can’t do this because [PEP 535](https://www.python.org/dev/peps/pep-0535/) was rejected, but oh well.

**Comment by eric-wieser** [comment]
Not possible, because `arr_1 and arr_2` is evaluated as `arr_2 if bool(arr_1) else arr_2`, and `bool(arr)` has to raise in order to protect against common mistakes.

**Comment by njsmith** [comment]
As you both note, this is impossible without first changing python.

PEP 535 hasn't been rejected or accepted yet; it's still a draft.
Unfortunately it also has a subtle and confusing flaw: it would allow us to
support '0 < arr < 1', but '0 < 1 < arr' would still return True without
ever calling any NumPy code. To solve this would require actually making
chained comparisons stop short circuiting, which is a backwards
incompatible change.

I think we some point we should at least make the attempt to do this; my
guess is most people don't even realize that chained comparisons are short
circuiting or take this into account when writing code (e.g. did you
realize that in 'a < b < func()', 'func()' might never be called?), and we
could potentially gather data on this (e.g. by surveys, talking to
students, examining some large corpus of code to see how much would
actually be affected in practice). But unfortunately Guido does happen to
be one of the people who knows that chained comparisons are
short-circuiting and intentionally takes advantage of it when writing code
(e.g. writing things like 'cheap1() == cheap2() == expensive()'), so we'd
need pretty convincing evidence to convince him that he's an outlier.

On Oct 12, 2017 20:17, "Eric Wieser" <notifications@github.com> wrote:

Not possible, because arr_1 and arr_2 is evaluated as arr_2 if bool(arr_1)
else arr_2, and bool(arr) has to raise in order to protect against common
mistakes.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/numpy/numpy/issues/9857#issuecomment-336339215>, or mute
the thread

**Comment by seberg** [comment]
Indeed, closing since there is nothing much to do for numpy.

**Comment by xoviat** [comment]
Actually, I think that there is a solution to this problem:

`1940 <= data.yearID.all() <= 1942`

The `all` method would not return a boolean object, but rather a `ContextualizedComparison` that would pick `any` or `all` when simplified to a `bool`.

**Comment by njsmith** [comment]
The desire is for the result of the expression to be an array, not a bool
at all.
