### ISSUE TITLE
ENH: Decimal support for np.log

### ISSUE THREAD

**Issue by garrypolley** [numpy/numpy#9955]
This issue was found when working on: https://github.com/numpy/numpy/pull/9952

It seems to be related to: https://github.com/numpy/numpy/issues/9791

Comment on prior review:
> This should be possible to fix - right now, it calls Decimal.log, but that doesn't exist. The fix would be to modify something in generate_umath which currently attaches PyUFunc_O_O_method for dtype=object, to allow multiple method names to be tried.

I'm not sure of the implementation, but depending on how `np.log` is implemented it may be possible to do the same work around as `__round__` is doing, and try to call `.log` or `.log10` in the case of `Decimal`. 

Once completed this should allow `np.lib.financial.nper` to support Decimal type. So its documentation and test(s) should be updated.

**Comment by seberg** [comment]
I do not think we should test multiple methods for objects (or at least discuss it bigger), at least unless there is a clear standard. Note that `log10` should even work fine. And it is completely unreasonable to call log10 from log, since those are different.
I guess it could be reasonable to call the math functions for exact python floats, but I think we should add another issue then.
