### ISSUE TITLE
np.load() fails to read empty archive created by np.savez()

### ISSUE THREAD

**Issue by jzwinck** [numpy/numpy#9989]
Try this:

    np.savez('nothing.npz') # OK
    np.load('nothing.npz') # error

Loading fails:

    OSError: Failed to interpret file 'nothing.npz' as a pickle

It should succeed (and give you an object with no arrays inside).  Likewise for `savez_compressed()` (which also currently fails).

I'm using NumPy 1.13.1.

**Comment by kchomski-reef** [comment]
Implementation of `_savez` (which both `savez` and`savez_compressed` use underneath) makes it possible to create empty archive, which `load` function cannot unpickle later:
```python
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

Can we add `array` as a required argument to `savez` and `savez_compressed` function calls?
Because currently only filename is required:
```python
def savez(file, *args, **kwds):
    ...

def savez_compressed(file, *args, **kwds):
    ...
```

It will be also more compatible with `save` function:
```python
def save(file, arr, allow_pickle=True, fix_imports=True):
    ...
```

**Comment by billmetangmo** [comment]
Hi . I am using Numpy 1.15.2 and still have this error. When do u think it will be available on a specific version ( not master branch) ?

Thanks
