### ISSUE TITLE
int128, uint128 support?

### ISSUE THREAD

**Issue by jason-s** [numpy/numpy#9992]
Are there plans to add uint128 (and perhaps int128) support?

I'm doing some stuff with linear feedback shift registers (LFSRs) that in the 64-96 bit range. The operations I need are just `<<`, `>>`, and bitwise operations; I don't care if math operations like multiply aren't the fastest in the world.

**Comment by charris** [comment]
There are no current plans to add new number types, although NumPy uses 128 bit integers internally for some things. If/when the type system gets sorted so that it is easier to add new types we may take a look at adding larger integers and quad precision floats, but that will not happen anytime soon.

**Comment by charris** [comment]
The mailing list is a better place for these types of questions, so I'm going to close this.

**Comment by caniko** [comment]
Why are we still using a mailing list? Aren't there better ways to communicate? Jira, YouTrack, etc...

**Comment by eric-wieser** [comment]
Python as a language still uses mailing lists, so it seems sensible for numpy to follow suit. It would be nice if we could provide a web interface to the mailing list like https://mail.python.org/archives/list/python-ideas@python.org/ does.

**Comment by shaunc** [comment]
Is this the best link to the discussion? Doesn't seem like much...

https://www.mail-archive.com/numpy-discussion@python.org/msg06689.html
